### ISSUE TITLE
Missing info about "col*" classes in FieldRowPanel documentation

### ISSUE THREAD

**Issue by it-management** [wagtail/wagtail#10061]
In Wagtail 3.0 documentation of FieldRowPanel are mentioned "col*" class names for child Panels, bat the whole section is missin in Wagtail 4.0 and later documentation.

The classes are still present in "core.css" and can be used. 
There is alsono mension of this functionality change in Release notes.

**Comment by dassudip2001** [comment]
![Screenshot from 2023-02-13 11-22-58](https://user-images.githubusercontent.com/85440350/218381288-20ee9465-d324-42ca-8483-3e4bc8972004.png)
* can you mean this  is not present Wagtail 4.0

**Comment by dassudip2001** [comment]
Can I delete my previous comment ?

**Comment by thibaudcolas** [comment]
@gasman strange! I don’t recall why I might have removed this as we do support the same `col*` classes as before. Might have intended to move this documentation elsewhere?

I’ll re-review how the implementation works to be sure, and revert the documentation deletion.

**Comment by thibaudcolas** [comment]
Reverted in fdc36a6989 (main), d83a1cf193 (4.2), 1e34827555 (4.1). I can confirm the `col*` class names are still supported. Have reworded the docs slightly because the grid works differently when setting less than the full 12 columns – it’s proportional to the column count. For 12 columns, the result is the same as before.
