### ISSUE TITLE
Attempting to delete a Collection you aren't permitted to delete confusingly throws a "not found" error

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#10085]
### Issue Summary

Attempting to delete a Collection which you are not permitted to delete will throw a `404 Not Found` error, instead of rendering the template that says "You're not allowed to do that" (or whatever). 

### Steps to Reproduce

1. Give a user Edit but not Delete permission on Collection X.
2. User attempts to edit the collection from `/admin/collections/X/`.
3. Due to #10084 the user will erroneously see the "Delete Collection" button.
4. Clicking that button results in a `404 Not Found` error.

### Source of Bug

This is happening because of how `collections.Delete.get_queryset()` is used by other code. It limits the Collections it returns to those for which the User actually has delete permission. But since `DeleteView.get_object()` calls `SingleObjectMixin.get_object()`, which calls `Delete.get_queryset()` to source its single object, that queryset being empty because the user doesn't have delete permission triggers a 404. This prevents the view from saying "You don't have delete permission on this Collection" (or whatever it's supposed to be doing).

# Proposed Solutions

1. It could be that fixing #10084 will be sufficient, as users will no longer be able to get to the deletion view for unpermitted Collections. 
2. Maybe defining `Delete.get_object()` so that it'll use a different queryset than what `Delete.get_queryset()` returns would work?

**Comment by laymonage** [comment]
Thanks, I can confirm this issue exists.

**Comment by laymonage** [comment]
Hmm, after looking into #10084, I think your first proposed solution is right – fixing that should be sufficient. This 404 behaviour also exists with `EditView` and the `"change"` permission.

As you mentioned, these views consider the permissions ahead-of-time as part of the query, instead of fetching the object and checking the permission afterwards.

I don't think this is a problem, and it may well be the preferred behaviour, as it imposes a better restriction: by showing a 404, we basically don't give the user the permission to even _know_ that the collection _exists_. If we give a redirect with a message "Sorry, you don't have permission to edit/delete this collection", we're giving away the fact that there _is_ a collection with that ID.

Other websites also have a similar behaviour, e.g. if you try to access a private repo on GitHub that you don't have access to, GitHub will throw a 404 instead of saying you don't have access.
