### ISSUE TITLE
Collections that a user cannot delete incorrectly show the Delete Collection button in the edit form

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#10084]
### Issue Summary

When a user without permission to delete a Collection views the edit form for said Collection, the "Delete Collection" button erroneously appears in the form.

### Steps to Reproduce

1. Give a user Edit but not Delete permission on Collection X.
2. User attempts to edit the collection from `/admin/collections/X/`.
3. User sees "Delete Collection" button, even though they're not allowed to delete it.
4. Clicking that button actually triggers a different bug, which I reported in #10085.  

### Proposed Solution

I've looked into why this happens, and I see the exact problem in the code:
The `wagtailadmin/collections/edit.html` template doesn't use the `can_delete` context var that `collections.Edit.get_context_data()` adds. It just uses the generic edit form template code, which hides the Delete button only if the `delete_url` var is falsey, ignoring `can_delete` entirely.

Fixing this should be as simple as overriding the `actions` block in `wagtailadmin/collections/edit.html` to make it take `can_delete` into account.

**Comment by HimanshuGarg47** [comment]
I tried to reproduce issue in chrome browser, In my case User does not sees "Delete Collection" button. 
![image](https://user-images.githubusercontent.com/78200614/220083545-36e0a979-1106-4c29-b7db-b35c2e8449b2.png)

**Comment by coredumperror** [comment]
> I created new user and give permissions of add, edit for collections.

Did you give the user those permissions through the Group system, or give it to them directly on the User? I failed to mention that I'm talking about giving the user this permission through their Group, via granting Permission for a given Collection which then applies to all that Collection's descendants.

**Comment by HimanshuGarg47** [comment]
Yes, I give user permissions through Group (in my case Editors group)

**Comment by laymonage** [comment]
I can't replicate this on Wagtail 6.1. Since this issue was created, we did some work on the permission policies in Wagtail 5.1 so that might've fixed it. Could you confirm whether this is still an issue @coredumperror? Thanks!

**Comment by laymonage** [comment]
Oh, actually, never mind. I was able to replicate this after assigning the delete permission to a different collection:

<img width="882" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/a39dc7c5-289f-434a-b721-8caa573d5605">

The issue is because the `can_delete` check only happens in the generic EditView's `get_context_data`, and by the time the collections Edit view overrides it with instance-specific check, the `delete_url` is already generated.
https://github.com/wagtail/wagtail/blob/6fa39856747523da90e2e0f40bf2322d784b6708/wagtail/admin/views/generic/models.py#L914-L920
https://github.com/wagtail/wagtail/blob/6fa39856747523da90e2e0f40bf2322d784b6708/wagtail/admin/views/collections.py#L143-L149

**Comment by coredumperror** [comment]
Great! Glad you managed to track down the ultimate source. I never realized it required a second Collection to have delete perms.
