### ISSUE TITLE
`public()` filter method does not remove alias pages of private pages from queryset

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/wagtail#10111]
### Issue Summary

The `public()` filter method of the page queryset does not remove alias pages of private pages from the queryset.

### Steps to Reproduce

1. Checkout the latest version of the bakerydemo. 
2. Edit the `get_context` method of the `BlogIndex` in `bakerydemo/blog/models.py` to only show public pages, by adding the `.public()` filter method:
   ```python
    def get_context(self, request):
        context = super(BlogIndexPage, self).get_context(request)
        context["posts"] = (
            BlogPage.objects.descendant_of(self).live().order_by("-date_published").public()
        )
        return context

   ```
3. Have a look at what is listed on the blog index: http://localhost:8000/blog/
4. Set one of the pages to be private, e.g. by defining a password: http://localhost:8000/admin/pages/77/edit/
5. Check the index again to see that the page you set to private is not displayed anymore. 
6. Now create an alias copy of the page you set to private: http://localhost:8000/admin/pages/77/copy/?next=%2Fadmin%2Fpages%2F61%2F
7. Check the blog index and see that the alias page is listed on the index. 
8. Try to visit the alias page and see that it is protected like the original page (I have added `alias-` to the beginning of the slug when creating it): http://localhost:8000/blog/alias-desserts-benefits/

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

- I would expect the alias page to not be listed in the index because the index uses the `public()` filter. 
- I first ran into this in the context of translated pages, which are first created as alias pages. 
- I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / ~~no~~) With bakerydemo. 

### Technical details

-   Python version: 3.9.9
-   Django version: 4.1.7
-   Wagtail version: 4.2 (discovered on 2.16)

**Comment by GeekGawd** [comment]
Hi! @tbrlpld Yes, this seems to be an issue and I checked it against the lastest bakerydemo version (66aa55551b007a1310d8f75f6fd34ac8d42e1aa4) and Wagtail version: 4.2a.

As, to what I can see in the code, set_privacy is not called during copy or it is checked anywhere if the page is private or not. This will require further investigation from my side, and if I find a fix I will submit the PR.

**Comment by tbrlpld** [comment]
Thanks @GeekGawd for trying to reproduce. Your video seems so show some thing a bit different from what I am describing above. E.g. you are copying the page outright instead of creating an alias. Also,, to check the effect of the `public()` method of the queryset you would want to look at the blog index page instead of the blog post pages.

Hope this helps to avoid confusion.

**Comment by GeekGawd** [comment]
Ohhhh! I will update the video and my comment to avoid confusion. Thanks! @tbrlpld

**Comment by gasman** [comment]
I think there are a couple of sub-questions to be answered here:

* What is the desired behaviour when creating an alias of a page that has privacy settings defined directly on it?
* What is the desired behaviour when creating an alias of a page that doesn't have privacy settings defined directly on it, but inherits them from an ancestor page?
* Do we implement that behaviour by changing the logic of `public()` to follow the alias and reading the settings at the other end, or by copying the settings to the alias?

The first two can be answered by reasoning that aliases are intended to be a "lightweight" variation of copying pages, so it makes sense to match that behaviour - and the desired behaviour for copying pages is given by the open issue #6212 and corresponding PR #6406 (which had fallen off my radar for reviewing, but is back on it now :-) ). Namely: the copied (or aliased) page should receive the same settings as the source page if they are defined directly on it, but NOT if they're only inherited.

I haven't checked whether the fix in #6406 also indirectly fixes this issue - it's quite possible that it does, if the code paths for copying pages and creating aliases share the appropriate bit of logic so that the privacy setting record is copied across in both cases. Either way, though, I think that copying the privacy setting across _is_ the correct fix, rather than modifying the behaviour of `public()`:

* Having to follow the alias relation within `public()` would add extra complexity and database queries (probably not as much as if it was taking account of inherited privacy settings too, but still more than we want)
* If we're having to fix this for ordinary page copies too, it makes sense to handle aliases in the same way
* If we _didn't_ copy the privacy setting across at this point, we'd presumably have to do so later on when turning the alias into a real page copy (as we do when translating the page), so we're just pushing the problem further down the line.

**Comment by tbrlpld** [comment]
Thanks @gasman 

> Namely: the copied (or aliased) page should receive the same settings as the source page if they are defined directly on it, but NOT if they're only inherited.

Yup, that sounds reasonable. 

One question that remains for me is: how to we handle later updates to the privacy settings on the original page? Consider this situation

1. Original page is private.
2. An alias of the original page is created. 
3. Following the proposed fix, the same protection rule from the original page is created for the alias page. 
4. Original page is made public
5. What happens to the alias page?

It seems to me that in this scenario, we would want different behaviours for alias and copied pages. Copied pages are independent pages that only matched the original page at creation time and are independent thereafter. Alias pages however should follow the original page until they are "ejected". So I would assume that we would need to keep track of a pages alias when modifying privacy settings on a page.

**Comment by GeekGawd** [comment]
Hi! @gasman I have made a PR. Much of the discussion and the code was already done in #6406 . The files had changed since the last time, so it needed to be written to another file. Also, it only handled restriction_type `password`, I have also changed that to work with all restriction types and written test cases for it. If you get the time do check it out.
