### ISSUE TITLE
Rich text docs should say that only h2,h3,h4 are available by default

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail#10124]
The features provided on a default Wagtail installation are not aligned with what the documentation describes.

Here is the code and the default features displayed on the panel:
class HomePage(Page):
    body = RichTextField(null=True)

    content_panels = Page.content_panels + [
        FieldPanel('body'),
    ]

![image](https://user-images.githubusercontent.com/81170508/220243279-ee79ba4d-ed18-46ae-8e07-64a87abc920b.png)

But on the [documentation](https://docs.wagtail.org/en/stable/advanced_topics/customisation/page_editing_interface.html#limiting-features-in-a-rich-text-field), it says:
**The feature identifiers provided on a default Wagtail installation are as follows:
h1, h2, h3, h4, h5, h6 - heading elements
bold, italic - bold / italic text
ol, ul - ordered / unordered lists
hr - horizontal rules
link - page, external and email links
document-link - links to documents
image - embedded images
embed - embedded media (see [Embedded content](https://docs.wagtail.org/en/stable/advanced_topics/embeds.html#embedded-content))**

It seems that h1, h5, h6, bold and italics are missing. Even though I specify "bold" and "italic" in features attribute, they do not show.
![image](https://user-images.githubusercontent.com/81170508/220243837-9b24187f-78ff-4d60-9583-30b9467e4f4e.png)

Same as the features are not enabled by default.
From the documentation, it says:
**We have few additional feature identifiers as well. They are not enabled by default, but you can use them in your list of identifiers. These are as follows:
code - inline code
superscript, subscript, strikethrough - text formatting
blockquote - blockquote**

It proves in my code that only blockquote works.
![image](https://user-images.githubusercontent.com/81170508/220244097-28d7357f-a813-4c55-818d-d4546aabb508.png)

Even if I register the features mentioned above that are not working in wagtail_hooks.py, they still do not work.

Wagtail version: 4.2
Django version: 4.1.6
python version: 3.10

**Comment by gasman** [comment]
Hi @aliceni81,
See the discussion on #9281 and #9905 - bold, italic, code, superscript, subscript and strikethrough do not appear in the block listing because they are formatting to be applied within a paragraph, not blocks in themselves. If you select a span of text, a formatting toolbar with those options will be shown, and can be pinned to the top of the text area.

The h1/h5/h6 options are intentionally disabled by default because we want to encourage editors to use the correct heading type for the document hierarchy, and h1 will usually be the overall page title (which is handled outside of rich text) - the documentation is indeed incorrect here, and should only list h2, h3, h4 as provided by default.

**Comment by aliceni81** [comment]
@gasman Got it, thanks a bunch. Have a good day!
