### ISSUE TITLE
Avoid Internal Link URLs rendering as href="None"

### ISSUE THREAD

**Issue by csebianlander** [wagtail/wagtail#10134]
### Is your proposal related to a problem?

#5851 describes an issue wherein pages outside of any site root or without a `wagtail_serve` URL route ends up with links that render as `<a href="None">` within various admin pages.

I want to flag that this **also** happens with hyperlinks set up using the "Internal Link" functionality in the rich text editor. I'm not sure whether this qualifies as a bug so much as undesirable behavior:

When a page is changed so it meets one of the criteria above (e.g., Page A is deleted or unpublished in lieu of Page B, which will share Page A's original parent and slug but will utilize a new/different page type), the result is a broken link to "none" that is now _untraceable_ to its original link destination (unless one uses a cached copy of the database or, say, the Wayback Machine to find a functional version).

### Describe the solution you'd like

When an internal link points to a location outside the site root or without a `wagtail_serve` URL route, as a content manager I would ideally like this link to either

- change to an External Link type pointing to the final rendered URL, or
- include some information or context about the former page link destination.

The key here is that even if the link breaks (which it simply will in some cases) the link itself should still resolve as it used to so that 404 errors can be properly traced and remediated.

**Comment by Imshk** [comment]
@csebianlander can you provide more details on this issue ?

**Comment by csebianlander** [comment]
Sure. Screenshots and descriptions below.

Say I have two blog posts, in this case "Test move blog" and "Test move blog 2". The first has a hyperlink to the second set up using the Wagtail "internal link" option,  like so:

![Screen Shot 2023-03-03 at 12 22 49 PM](https://user-images.githubusercontent.com/29648039/222787117-ca5d86c9-514e-4f68-9c49-0ee23ff2e9b4.png)

Note the destination URL path in the lower left.

OK, now let's say I decide to archive blog 2. I decide to move it to an "Archived Pages" section of Wagtail, which is not mapped to a site root or URL route:

![Screen Shot 2023-03-03 at 12 23 30 PM](https://user-images.githubusercontent.com/29648039/222787285-68bf9eb2-abd5-422a-ad8d-d51c7818d866.png)

![Screen Shot 2023-03-03 at 12 23 46 PM](https://user-images.githubusercontent.com/29648039/222787422-fe777919-a29a-4dc0-9e54-3afbe47217d1.png)

![Screen Shot 2023-03-03 at 12 23 53 PM](https://user-images.githubusercontent.com/29648039/222787494-3004bc08-fb0a-44a9-a43e-6bf0abcb5a76.png)

Once I have done this, when I go back to my first blog post, the link to the now-moved post is not only broken but broken in a way that is irretrievable; it does not have or know the URL path it once pointed to, and instead attempts to resolve to a relative URL path of `None`.

![Screen Shot 2023-03-03 at 12 24 15 PM](https://user-images.githubusercontent.com/29648039/222787674-62bf8686-7b59-4b31-8632-39fffdcaad9f.png)
![Screen Shot 2023-03-03 at 12 24 42 PM](https://user-images.githubusercontent.com/29648039/222787685-3e86acec-ea88-403a-b2be-564a3862e25e.png)

This behavior makes it really hard to remediate ripple effects of moving/deleting/archiving pages, because if a 404 is caught downstream after that action has been taken, there's no more connective tissue to know where the link pointed to in the first place and therefore construct an appropriate new link (or redirect).

**Comment by priyanshpsalian** [comment]
The possible solution to this would be as follows:-


1.Apply a patch to the ImageChooserPanel widget: If you're unable to upgrade to a newer version of Wagtail, you could try applying a patch to the ImageChooserPanel widget code. Specifically, you would need to modify the "wagtail/images/widgets.py" file to replace the following line:

return format_html('<img src="{}" alt="{}" style="max-height:100px; max-width:100px;">', image_url, image.title)

with this line:

return format_html('<img src="{}" alt="{}" style="max-height:100px; max-width:100px;">', image.get_rendition('fill-100x100').url, image.title)

This change should ensure that the image is properly displayed in the preview thumbnail.

2.Use a different image selection widget: If neither of the above solutions works for you, you could consider using a different image selection widget in Wagtail, such as the "AdminImageChooser" widget provided by the wagtailaltgenerator package. This widget has similar functionality to the ImageChooserPanel widget but may not have the same display issues.

**Comment by gasman** [comment]
@priyanshpsalian Your comment is not related to this issue (there's no mention of images in the original post) and looks a lot like it was generated with ChatGPT. Please don't do that - it's not helpful.

**Comment by gasman** [comment]
Unfortunately I can't really see how this might be fixed without breaking various long-established aspects of Wagtail's design. Internal links in Wagtail content always reference the page by ID, rather than path / parent / slug, to ensure that links stay intact if that page is renamed or moved. The flipside of this is that if you move a _new_ page to match the slug/parent of a previously existing one, links won't be repointed to the new page - but I think the current behaviour is what's desired more often than not.

In the upcoming version 5.0, the confirmation screen when deleting a page now lists the references that would be broken by the deletion, which will mitigate this a bit by letting you know what needs to be fixed up manually - but of course that won't help if you're archiving pages rather than deleting them. (The same information is available from the info sidebar when editing the page - you'd just need to make a point of checking that before archiving a page).

There are various possible scenarios by which a page could become unroutable - either by moving the page itself, or one of its ancestors, or by changing / removing the site record - so I could see it becoming very messy (and resource-intensive) to catch those actions and fix up links at the point of that happening. The alternative is to try and figure out what the correct URL should be at the point of encountering a `None` URL, but then you have the equal if not bigger problem of tracing the history of that URL to figure out what it would have been immediately before it broke.

And even if that could be solved, it's likely that you'd end up with a solution that only works with your particular workflow for archiving pages, and I'm not sure how common that setup really is - if someone else chose to archive pages by unpublishing them instead, or moving them to a section that _is_ routable but is marked as private, they'd need a whole other solution.
