### ISSUE TITLE
`self.model` instead of `Page` in `PagesAPIViewSet` `get_base_queryset` method.

### ISSUE THREAD

**Issue by Zogsha** [wagtail/wagtail#10156]
### Is your proposal related to a problem? No

I attempted to build a viewset for a specific page type by inheriting from `PagesAPIViewSet`. I assumed that I only needed to change the model to my `CustomPage` and that all the endpoints for that specific `CustomPage` would be available.

For example, in my particular use case, since I know that my page has only one parent and subpage type, the slugs, for my `CustomPage`, are unique. Therefore, I could handle `detail_view` by slug and not check if it's unique. Currently, it is possible to override methods like `detail_view` to add a slug and an URL in the `get_urlpatterns` method.

However, for the `listing_view`, the `get_base_queryset` method is used in `PagesAPIViewSet`. This method uses `queryset = Page.objects.all().live()`. Hence, `listing_view` doesn't specifically list my `CustomPage`, even though I set my model to `CustomPage`.

Although it is possible to achieve everything I want to do with the built-in API endpoint, I thought it would be easier to build a specific page type API viewset.

### Describe the solution you'd like

I propose to change `queryset = Page.objects.all().live()` to `queryset = self.model.objects.all().live()`. I think this change won't affect the normal behavior of the API, but it allows us to create specific endpoints for each page type more easily.

**Comment by AnuragMishraa** [comment]
Your proposed solution of changing `queryset = Page.objects.all().live()` to `queryset = self.model.objects.all().live()` would allow you to create specific endpoints for each page type more easily, as you would be able to access the queryset of your custom page type rather than the generic `Page` queryset.

This change should not affect the normal behavior of the API, as `PagesAPIViewSet` already uses the `model` attribute to retrieve the appropriate model for each endpoint. Therefore, using `self.model.objects.all()` instead of `Page.objects.all()` would simply ensure that the appropriate queryset is used for each viewset that inherits from `PagesAPIViewSet`.

It's worth noting that this change could potentially cause issues if other parts of the API rely on the `Page` queryset. Therefore, it may be a good idea to test the impact of this change thoroughly before implementing it in production. Additionally, it's always a good idea to follow best practices for Django REST framework and use mixins and serializers to create custom viewsets, as this can make it easier to create and maintain specific endpoints for each page type.

**Comment by AnuragMishraa** [comment]
Hey! please assign me this issue.

**Comment by priyanshpsalian** [comment]
Based on the description you provided, it sounds like the proposed solution is reasonable and would allow for easier creation of specific endpoints for each page type in Wagtail.

To implement the proposed solution, you would need to modify the "get_base_queryset" method in the PagesAPIViewSet class. Specifically, you would replace the line "queryset = Page.objects.all().live()" with "queryset = self.model.objects.all().live()" in your custom viewset class that inherits from PagesAPIViewSet.

This would ensure that the queryset used for listing pages in the API is based on the custom page type you specify in your viewset, rather than the default "Page" model used by PagesAPIViewSet.

Overall, this change should not affect the normal behavior of the API and would make it easier to create specific endpoints for each page type in Wagtail.

**Comment by lb-** [comment]
@priyanshpsalian your comment doesn't add anything constructive to this issue and reads like it's been automatically generated by ChatGPT, I'll hide it for now as it's unhelpful.

**Comment by lb-** [comment]
@Zogsha have you tried extending the method get_base_queryset instead?

See https://docs.wagtail.org/en/stable/reference/pages/queryset_reference.html#wagtail.query.PageQuerySet.type


Something like this should work I think...

```
class CustomAPIViewSet(PagesAPIViewSet):
    def get_base_queryset(self):
        queryset = self.super().type(CustomPage)
        return queryset
```

**Comment by Zogsha** [comment]
Now I think I understand. It's because `get_base_queryset` is used in child_of and descendant_of filters as well, to find parent pages. So even though my viewset inherits from `PageAPIViewSet`, `get_base_queryset` needs to query all `Page` object, in order to find the parent.

@lb- I think I should extend `get_queryset` instead of `get_base_queryset`, and filter the queryset as you mentioned : `queryset = super().get_queryset().type(CustomPage)`. Thanks.

Sorry for the inconvenience, but as I looked for `PagesAPIViewSet` code, it felt odd to me that `get_base_queryset` don't use the `model` attribute.

I think this should be closed.

**Comment by lb-** [comment]
No problems @Zogsha - a reminder we also have the Slack channel for community support and Stackoverflow for community questions. 

https://github.com/wagtail/wagtail#-community-support

I'll close this now.

**Comment by lb-** [comment]
@Zogsha one more reminder to read the docs on Page querysets, they have a bunch of helpful features and also that Django querysets are lazy and can be appended to all the way down until the query is actually resolved. 

https://docs.wagtail.org/en/stable/reference/pages/queryset_reference.html

Hope you get to solve your problems well.
