### ISSUE TITLE
SQLite FTS search backend ignores content type

### ISSUE THREAD

**Issue by gsakkis** [wagtail/wagtail#10188]
### Issue Summary

Searching for snippets of specific type in the Wagtail admin fetches all snippets that match, regardless of their type.

### Steps to Reproduce

1. Create two simple searchable snippet types, for example `Advert` and `Todo`:
<details>
  <summary>models.py</summary>

```python
from django.db import models

from wagtail.admin.panels import FieldPanel
from wagtail.search.index import Indexed, SearchField
from wagtail.snippets.models import register_snippet


@register_snippet
class Advert(Indexed, models.Model):
    text = models.CharField(max_length=255)

    panels = [
        FieldPanel('text'),
    ]
    search_fields = [
        SearchField('text', partial_match=True),
    ]

    def __str__(self):
        return self.text


@register_snippet
class Todo(Indexed, models.Model):
    entry = models.CharField(max_length=255)

    panels = [
        FieldPanel('entry'),
    ]
    search_fields = [
        SearchField('entry', partial_match=True),
    ]

    def __str__(self):
        return self.entry
```
</details>

2. Create two instances for each type, e.g. `ad1`, `ad2`, `todo1`, `todo2`.
<img width="501" alt="Screenshot 2023-03-06 at 1 45 52 AM" src="https://user-images.githubusercontent.com/291289/223036141-2a9858bc-63c2-41e4-b2b9-4ccc504d27c6.png">
<img width="492" alt="Screenshot 2023-03-06 at 1 46 04 AM" src="https://user-images.githubusercontent.com/291289/223036145-7fd96829-3e3d-4912-963b-7c26cffdedf3.png">

3. Search for `ad1` in the `Todo` search box:
<img width="486" alt="Screenshot 2023-03-06 at 1 47 57 AM" src="https://user-images.githubusercontent.com/291289/223036516-384609c9-cfe8-467e-b8b0-d3e0d1ecc4d5.png">

4. Likewise search for `todo2` in the `Ad`search box:
<img width="527" alt="Screenshot 2023-03-06 at 1 48 20 AM" src="https://user-images.githubusercontent.com/291289/223036556-3f6536bb-9a6d-4666-8e2a-c3bbe2b57f8e.png">

### Technical details

-   Python version: 3.8.16
-   Django version: 4.1.7
-   Wagtail version: 4.2
-   Browser version: https://www.whatsmybrowser.org/b/GB7VV

**Comment by achiverram28** [comment]
I am new to this project and would like to understand this and take this issue

**Comment by Hanoon02** [comment]
Yep, I'm getting this issue too. I think the search is matching index wise too. Plus partial_search is doing no effect on Snippet search.

Python 3.10.6
Wagtail 4.1

**Comment by thibaudcolas** [comment]
@gsakkis thank you for the excellent report!

@achiverram28 there’s a fair bit of research to do here – I’d suggest to start by reproducing the issue like @Hanoon02 has, then you can investigate the code.

**Comment by thibaudcolas** [comment]
@gsakkis trying to reproduce this, things seem to work as expected as far as I can tell. Are you sure the matches you’re seeing aren’t just because of the number (1, 2) in the CharField?

**Comment by laymonage** [comment]
Thanks for the report!

To anyone interested in reproducing this issue, could you try doing this with longer strings? For example:

- Create an Advert with the string "an advert with the word todo in it"
- Create a Todo with the string "a todo with the word advert in it"
- Search with the query "todo" and "advert" on both models, see if the issue persists?

Snippets are stored in separate tables, and in fact there's nothing that really distinguish them from regular Django models on the database level. We don't make use of the content type unless you've enabled some of the optional features (e.g. `RevisionMixin`), which you have not. Thus, I don't see a way for this to happen.

**Comment by Hanoon02** [comment]
@laymonage , so i tried the way you said, and for queries "todo" and "advert", there seems to be no result. But when i searched the whole phrase "a todo with the word advert in it", i'm getting the search result showing the Advert "an advert with the word todo in it". I have attached the image below. It happens vice versa too

Someone else can verify it too
Python 3.10.6
Wagtail 4.1


<img width="1346" alt="image" src="https://user-images.githubusercontent.com/90821506/223402051-fb5b475d-4d7b-4f08-b44f-8e5e2a76b789.png">
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/90821506/223402860-d044c4bd-334a-48fa-af89-bd8feb0bd0dc.png">

**Comment by Hanoon02** [comment]
@thibaudcolas , I'm getting this error without the nums too

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/90821506/223403605-97092e8f-0ab6-49f6-aef8-197d61b3b8b4.png">
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/90821506/223403841-777cb38f-d599-4cae-abad-185d9239e61d.png">

**Comment by gasman** [comment]
I think this might be a bug in the SQLite FTS search backend - have independently stumbled upon what might be the root cause of this while working on #9901.

[The `search` method](https://github.com/wagtail/wagtail/blob/6ec6895f4fa4de9d87e0d1631966bd0dc4d77298/wagtail/search/backends/database/sqlite/sqlite.py#L487) works by [running the search query over the `IndexEntry` model](https://github.com/wagtail/wagtail/blob/6ec6895f4fa4de9d87e0d1631966bd0dc4d77298/wagtail/search/backends/database/sqlite/sqlite.py#L521) - which contains the searchable content of all models - and then [filtering the initial queryset to just the object IDs returned in that search](https://github.com/wagtail/wagtail/blob/6ec6895f4fa4de9d87e0d1631966bd0dc4d77298/wagtail/search/backends/database/sqlite/sqlite.py#L550). However, neither of those steps ever checks that the content type matches the model we're searching on. As a result, searches will return items that don't contain the search term, but have an ID that matches some other model that does.

One for the "how did this go unnoticed for so long" list 🤦

**Comment by gasman** [comment]
Replicated on a new Wagtail project as follows:

* Start project with `wagtail start searchcontenttype`
* Edit home/models.py to:

```python
from django.db import models

from wagtail.admin.panels import FieldPanel
from wagtail.models import Page
from wagtail.search import index
from wagtail.snippets.models import register_snippet


class HomePage(Page):
    advert = models.ForeignKey('Advert', blank=True, null=True, on_delete=models.SET_NULL)
    todo = models.ForeignKey('Todo', blank=True, null=True, on_delete=models.SET_NULL)

    content_panels = Page.content_panels + [
        FieldPanel('advert'),
        FieldPanel('todo'),
    ]


@register_snippet
class Advert(models.Model, index.Indexed):
    title = models.CharField(max_length=255)

    search_fields = [
        index.SearchField('title'),
    ]

    def __str__(self):
        return self.title


@register_snippet
class Todo(models.Model, index.Indexed):
    title = models.CharField(max_length=255)

    search_fields = [
        index.SearchField('title'),
    ]

    def __str__(self):
        return self.title
```
* `./manage.py makemigrations ; ./manage.py migrate ; ./manage.py createsuperuser ; ./manage.py runserver`
* Log in to http://localhost:8000/admin/
* From Snippets -> Adverts, create an advert with title "Red Bull gives you wings" (this will have ID 1)
* From Snippets -> Todos, create a todo with title "Buy milk" (this will also have ID 1)
* From Pages, edit the homepage, click "Choose advert"
* Enter "mil" into the search box - no results are returned
* Now finish typing "milk" - "Red Bull gives you wings" now appears in the results

This happens because the SQLite search backend runs a search for "milk" on IndexEntry without filtering on content type, finds the IndexEntry for the todo with ID 1, and filters the Adverts queryset by ID 1, again without ensuring that the content type matches.

**Comment by gasman** [comment]
This `./manage.py shell` session shows that the issue is not specific to the admin UI, and is a general issue with the SQLite search backend (have not yet confirmed whether other backends are affected):
```
>>> from home.models import Advert
>>> from wagtail.search.backends import get_search_backend
>>> s = get_search_backend()
>>> s.search("milk", Advert)
<SearchResults [<Advert: Red Bull gives you wings>]>
```
