### ISSUE TITLE
`MultipleChooserPanel` reference docs incorrectly namespaced as part of `wagtail.snippets.edit_handlers`

### ISSUE THREAD

**Issue by bingimar** [wagtail/wagtail#10288]
MultipleChooserPanel is mentioned as released in version 4.2 but is nowhere to be seen. 

### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/reference/pages/panels.html#multiplechooserpanel

(Insert the permalink of the section heading in the Wagtail docs. Choose the most specific section / lowest-level heading to which your suggested change would apply. (In the docs, hover over the heading to see the permalink icon.))

### Details

Feature is mentioned that has not been released

(Write your answer here.)

Perhaps mention what version it will be released in.

**Comment by laymonage** [comment]
It _is_ released in 4.2 and can be seen in `wagtail.admin.panels.MultipleChooserPanel`: https://github.com/wagtail/wagtail/blob/stable/4.2.x/wagtail/admin/panels/multiple_chooser_panel.py#L8

I noticed that the docs incorrectly mentions it as `wagtail.snippets.edit_handlers.MultipleChooserPanel`, due to the RST module namespace not being reset to `wagtail.admin.panels` after the reference docs for `SnippetChooserPanel`.

I'll change the issue title accordingly.

**Comment by bingimar** [comment]
ah thanks for clearing that up.

**Comment by gasman** [comment]
Looks like this has fixed itself [in the 5.0 docs](https://docs.wagtail.org/en/latest/reference/pages/panels.html#multiplechooserpanel) due to us removing the docs for the deprecated panels including SnippetChooserPanel - will open a PR targetting 4.2.

**Comment by gasman** [comment]
Fixed in #10298
