### ISSUE TITLE
Proxy models and snippets

### ISSUE THREAD

**Issue by bufke** [wagtail/wagtail#1029]
It would be useful to support proxy models with snippets.

For example it would work around a lack of nested [inline support](https://groups.google.com/forum/#!searchin/wagtail/$20object$20has$20no$20attribute$20$27formsets$27/wagtail/jEX8DMQUR1c/onzyZTSCo4EJ)

```python
class FaqCategory(Orderable, models.Model):                                         
    page = ParentalKey('core.FaqPage', related_name='related_faq_categories') 
    category_name = models.CharField(max_length=500)                                                                                       
    panels = [ 
        FieldPanel('category_name'),                                                
    ]                                                                               

class FaqCategorySnippet(FaqCategory):                                              
    class Meta:                                                                     
        proxy = True                                                                

FaqCategorySnippet.panels = [                                                       
    FieldPanel('category_name'),                                                    
    InlinePanel(FaqCategorySnippet, 'related_faq_items', label="Questions"),        
    PageChooserPanel('page'),                                                       
]                                                                                   
register_snippet(FaqCategorySnippet)  
```

I'd expect the result would be a functional FaqCategory nested in a page edit view. A more complete version of it with related_faq_items in the snippet. However it seems the proxy model is ignored so I can have it only one way or another.

The only work around for this use case I'm aware of would be using django admin or making everything a Page.

**Comment by kaedroho** [comment]
Thanks @bufke. I think this approach would cause issues for your use case though...

All models with a ``ParentalKey`` to a page can stored in JSON format in the ``wagtailcore.PageRevision`` model. The page editor will always the JSON representation of the latest revision of the page rather than the live one (to account for live pages that have draft changes).

So if an editor changes ``FaqCategorySnippet`` in the snippets section, it will update the live version in the database but not the version that is shown in the page editor. So the next time the page is published, any changes made in the snippets section would be overwritten.

**Comment by zerolab** [comment]
Closing in favour of #4973 / #5202
