### ISSUE TITLE
Pinned Draftail toolbar doesn't display formatting type for selected text

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#10305]
### Issue Summary
When you select text that has special formatting (`code style`, headings, _italics_, etc), the floating Draftail toolbar highlights the format it's been given, but the pinned toolbar does not.

### Steps to Reproduce

1. Edit any page in Bakerydemo that has a rich text field that uses Draftail.
2. Select some text and give it italic formatting.
3. Notice that the `I` icon in the toolbar is now highlighted.
4. Press the Pin button in the toolbar to pin it to the top of the rich text field.
5. The highlight on the `I` icon is now gone.

This happens for every type of formatting. I'm guessing that it's related to the color of the highlight itself. It may actually be getting rendered, but is invisible due to being white-on-white in the pinned toolbar, rather than white-on-purple like the floating one.

### Technical details
This happens in vanilla Bakerydemo run in Gitpod (which uses Wagtail 4.2), viewed in Chrome.

**Comment by elhussienalmasri** [comment]
Hi , I found the solution and it ,s work for me ,  as you mention ,may it s take a background color white , and yes ,
pinned Draftail-Toolbar take white Background , so the solution is remove background from Draftail or change Draftail color
but as I think if Draftail background changed so it ,s return to default color mean the color like Floating Draftail ,
and may Draftail Background must be white color , so what I think is the solution is to change the color or background of active Icons and it work for me , and now as you see on the record the highlight still on the Icons ,because it ,s now darker,
and this what I make and I open  a PR on this issue, I only change a little code
 , if you want to review it ,and if you have other  suggestions please let  me know ,Thanks

https://user-images.githubusercontent.com/90080237/232266374-0e85c38e-fd8c-4bba-b4bd-274a826d07a8.mp4

**Comment by thibaudcolas** [comment]
This has been fixed in #11261.
