### ISSUE TITLE
Title/Slug autosync no longer works for non-Page models in 5.x

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail#10517]
### Issue Summary

For snippets, using fields title and slug together previously (i.e. <5.0) enabled the default autocomplete feature on the slug field.

After reading the release notes, with the note that if you're just using title/slug, [no changes should be made](https://docs.wagtail.org/en/stable/releases/5.0.html#title-field-auto-sync-with-the-slug-field-on-pages-now-relies-on-data-attributes), the autosync is not working without creating a base form to make the needed changes.

### Steps to Reproduce

Example model (autosync working pre-5.x):

```python
@register_snippet
class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("Category Name"))
    slug = models.SlugField(
        max_length=100,
        help_text=_("How the category will appear in URL"),
        unique=True, 
        allow_unicode=True,
    )

    panels = [
        FieldPanel("title"),
        FieldPanel("slug"),
    ]
```

To workaround, I have needed to change the panels as follows and add a baseform definition to add missing title field data attributes:

```python
class CategoryForm(WagtailAdminModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['data-controller'] = 'w-sync'
        self.fields['title'].widget.attrs['data-action'] = 'focus->w-sync#check blur->w-sync#apply change->w-sync#apply'
        self.fields['title'].widget.attrs['data-w-sync-target-value'] = '#id_slug'
        
@register_snippet
class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("Category Name"))
    slug = models.SlugField(
        max_length=100,
        help_text=_("How the category will appear in URL"),
        unique=True,
        allow_unicode=True,
    )

    base_form_class = CategoryForm

    panels = [
        FieldPanel("title", classname="title"),
        FieldPanel("slug", widget=SlugInput),
    ]

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Blog Category")
        verbose_name_plural = _("Blog Categories")
        ordering = ["title"]
```

This workaround overcomes the issue, though only on title losing focus.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

-   Python version: 3.10.6
-   Django version: 4.2.1
-   Wagtail version: 5.0.1
-   Browser version: Chrome 114

**Comment by lb-** [comment]
Thanks for the report @enzedonline - I worked with that migration and title/slug combos outside of pages was not tested. The release notes probably could have been clearer that Page title/slug sync would work the same. 

Looks like you have a work around, I'll check in with others on the core team for whether we want to officially continue to support this. It probably worked by accident previously as the code was based on their being an element with the id of the two fields, as in if your fields were named differently it would not have worked.

**Comment by lb-** [comment]
@enzedonline in regards to the 'only changes when focus is lost', I'm pretty sure that's how it used to work. 

However, if you want the slug field to changes as you type, you can try the following. 

```
self.fields['title'].widget.attrs['data-action'] = 'focus->w-sync#check blur->w-sync#apply change->w-sync#apply keyup->w-sync#apply'
```

Observe the `keyup` added to the action, this will trigger the sync as you type.

**Comment by enzedonline** [comment]
Thanks @lb

Yes, apologies, should have mentioned the docs were only discussing the Page model.

It's an extremely useful feature, considering how many models require a slug field.

It was possible to add the following line to a base admin form to set the autosync source, providing there wasn't already a 'title' field:
        `self.fields['name'].widget.attrs['id'] = 'id_title'`

I've just double-checked a 3.x site, the previous behaviour was on keyup (or possibly input?).

**Comment by lb-** [comment]
Ahh yes, I can see the previous logic was more frequent, I think we adjusted for performance and the use case where the slug field is on a different tab. 

```
$('#id_title').on('keyup keydown keypress blur', function () {
```

I recall some of that being needed for how IE11 handled copy/paste into the field. 

I'll get some guidance on this one from the core team also, maybe it's worth trying to fix the frequency of the updates in isolation.

**Comment by enzedonline** [comment]
Ok, thanks for that, that works well but needs , `widget=SlugInput` on the slug panel to slugify the sync'd text. Surprised that's not the default widget for SlugField.

**Comment by lb-** [comment]
After a bit of discussion with some of the core team, here is the proposed approach.

## 1. Official support for non-Page model slug/title sync (enhancement)

* Yes we want to be able to officially support something like a `SyncTextInput` widget. This would abstract the current approach for the title field, similar to what we are doing for the `SlugField` (except without the global widget default approach, which I think we just do for Page models).
* Those using Wagtail should be able to pass in a kwarg for the name/s of the fields they can sync with.
* This will not work by default by magically including title/slug fields in non-Page models but would be easily added by opting in for the correct widgets.
* This can be worked around right now (as per the discussion on this thread), but hopefully is not a huge change to bring into an upcoming release.
* There is a related issue #161 (which is more about other fields being able to sync their value with the title field), building out this feature may let us provide a JS only way to support that long-standing enhancement request.

## 2. Re-add `keyup` title sync (regression)

* For the built in title sync behaviour we should adopt the previous approach for updating the sync target field as the user types (keyup event).
* Not just as the user moves away from the field, this is technically a regression as it would have been an expected behaviour if someone had the Slug field showing on the same tab as the Title field.

**Comment by enzedonline** [comment]
That sounds great. Many thanks.

**Comment by lb-** [comment]
PR up #10563 - this just adds the keyup listener so we can get a fix for 5.0.2 - still working on a `SyncFieldPanel` / `SyncTextInput` approach though. Might end up doing that enhancement via #161

**Comment by gasman** [comment]
I think @lb- and I may have had a different understanding of the scope of this issue...

The root of the problem here isn't so much about whether title/slug interactions work on non-Page models - it's about whether they work when the panel definition uses a plain `FieldPanel("title")`. It just happens that for pages, the standard idiom is to avoid that by using `Page.content_panels + [...]` - but I suspect there are some common use-cases for not doing that, such as putting it in a MultiFieldPanel:

    content_panels = [
        MultiFieldPanel([
            FieldPanel("title"),
            FieldPanel("subtitle"),
        ]),
        # ...
    ]

(I think this particular example came up on Slack #support, and didn't re-raise it here as I thought it was already accounted for by this issue...)

If this only affected titles/slugs on snippets (which I'd regard as more of an advanced setup that's not officially supported by Wagtail), I'd be more on board with offering a workaround that involves replicating the Stimulus attributes. However, given that even novice developers may potentially run into this on pages, I think we really need to provide a more developer-friendly fix.

Assuming it's not going to be feasible to restore the previous behaviour of `FieldPanel("title")`, I suggest that we introduce a `TitleFieldPanel` for 5.0.2 that works the same as `FieldPanel` but supplies the relevant attributes, and document that in the 5.0 and 5.0.2 release notes. We can then separately work on a more general 'synced fields' mechanism for 5.1 or later, that potentially covers #161.

**Comment by lb-** [comment]
@gasman  that makes sense, I have a WIP start on this approach here - https://github.com/wagtail/wagtail/compare/main...lb-:fix/10517-add-title-field-panel

General approach I am taking now;

- Create a new `TitleFieldPanel` which will be documented and used by default in page models.
- This new panel will add the default `classname` 'title', the default `placeholder` of 'Page title*' and will also add the Stimulus controller attributes.
- I opted for a Panel not a Widget as it means we can avoid the confusing work around for finding the slug field only if the page is not live via CSS selectors and instead actually just read the modal and see if it is live or not.

This would be able to be used for custom panel layouts in Page models easily (and will include the placeholder which would previously have had to be added manually also). It will be able to be used on non-Page models easily (likely with a different placeholder override though).

This approach should be able to be extended to a kind of Sync or CalculatedPanel later so trying to keep documentation of the internals minimal in the proposed docs.

Hopefully I will have a PR up soon, writing tests tonight.

@enzedonline  - please review the branch above and advise if this feels like it solves for the general problem raised.

**Comment by lb-** [comment]
PR up (just a draft), unit tests still in progress but feel like this is hopefully a solid start and ready for some initial feedback if anyone is keen.

https://github.com/wagtail/wagtail/pull/10568

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail/pull/10568 ready to review
