### ISSUE TITLE
WAGTAILADMIN_BASE_URL should be mentioned in "Integrating Wagtail" docs

### ISSUE THREAD

**Issue by jaap3** [wagtail/wagtail#10741]
### Pertinent section of the Wagtail docs

The documentation on [WAGTAILADMIN_BASE_URL](https://docs.wagtail.org/en/v5.1/reference/settings.html#wagtailadmin-base-url) says (emphasis mine):

> This is the base URL used by the Wagtail admin site. It is typically used for generating URLs to include in notification emails.
> **If this setting is not present, Wagtail will try to fall back to request.site.root_url or to the request’s host name.**

Yet if you do not configure it, Wagtail will issue a warning:

`(wagtailadmin.W003) The WAGTAILADMIN_BASE_URL setting is not defined` 

https://github.com/wagtail/wagtail/blob/801eccc9304561ffe974b6e16bd977198910726d/wagtail/admin/checks.py#L175-L183

In addition, the ["Settings" section of "Integrating Wagtail into a Django project"](https://docs.wagtail.org/en/v5.1/getting_started/integrating_into_django.html#settings), doesn't mention this setting.

### Details

If`WAGTAILADMIN_BASE_URL` should always be configured, then the docs should reflect this.

**Comment by jaap3** [comment]
I ran into this on a multi-site Wagtail installation. Hadn't configured the base url before as there isn't a central wagtail url for all site, so I just picked one.

**Comment by gasman** [comment]
I don't think there's a contradiction here: the setting is not strictly required, but highly recommended because leaving it out is liable to produce unusable URLs in notification emails, in certain server configurations. Therefore, there's a warning, but not a hard error, and the documentation doesn't state that it's required.

I agree it should be mentioned in the "Integrating Wagtail" docs, though.

**Comment by Shreshth-Srivastava** [comment]
I am planning to work on this issue, my solution is that I will add the following lines into the 'Settings' section of 'integrating_into_django.md' file :

Add a `WAGTAILADMIN_BASE_URL` - This is the base URL used by the Wagtail admin site. It is typically used for generating URLs to include in notification emails :
```python
WAGTAIL_SITE_NAME = 'My Example Site'
```
If this setting is not present, Wagtail will try to fall back to request.site.root_url or to the hostname of the request. Although this setting is not strictly required, it is highly recommended because leaving it out will produce unusable URLs in notification emails in certain server configurations and you will get this warning  :
```sh
The WAGTAILADMIN_BASE_URL setting is not defined
```
