### ISSUE TITLE
Incorrect screenshot for Authors in "Your first Wagtail site"

### ISSUE THREAD

**Issue by philgyford** [wagtail/wagtail#10763]
The Authors section of the "Your first Wagtail site" page ends in a screenshot that should demonstrate the display of Authors on a blog post. But it instead demonstrates categories (or something like that).

### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/getting_started/tutorial.html#authors

### Details

The section is about adding Authors to a blog post and ends with a template in which they're displayed under a heading `<h3>Posted by:</h3>`.

However the following screenshot ([`docs/_static/images/tutorial/tutorial_10.png`](https://github.com/wagtail/wagtail/blob/main/docs/_static/images/tutorial/tutorial_10.png)) is this, with a new heading of "Posted in" and showing what looks like a couple of Categories or similar, and no authors:

![tutorial_10](https://github.com/wagtail/wagtail/assets/66670/cc209443-0265-4a12-9006-40fc362c5c47)

An updated screenshot is required.

**Comment by shindodkar** [comment]
@philgyford what type of content you want to showcase in the tutorial.

**Comment by philgyford** [comment]
I'm unclear what you're both asking. The screenshot should show authors, not categories.

**Comment by gasman** [comment]
It looks like this issue came about because the tutorial was updated in #10624 to demonstrate snippets by introducing an Author snippet - in the previous version, it used a Category snippet. The screenshot should have been updated at this point, but it wasn't.

For anyone interested in picking up this issue: the task is to work through the tutorial up to this point, then take a new screenshot to replace the current one, showing the "Posted by" authors list in place of "Posted in". This new screenshot should be saved at the existing filename [docs/_static/images/tutorial/tutorial_10.png](https://github.com/wagtail/wagtail/blob/main/docs/_static/images/tutorial/tutorial_10.png). When taking the screenshot, please take care to match the size and format of the current one.

**Comment by gasman** [comment]
cc @thibaudcolas @activus-d who worked on the original PR

**Comment by Shreshth-Srivastava** [comment]
I have tried to fix this issue, please review it.

Screenshot:

![Tutorial 10](https://github.com/wagtail/wagtail/assets/134348598/e7e8f6f7-d9ea-45ca-b515-2dda7d5ed730)
