### ISSUE TITLE
Image alt text not persisted between 'Upload' and 'Choose format' dialogs.

### ISSUE THREAD

**Issue by timothyPatterson** [wagtail/wagtail#10800]
When inserting an image into a RichTextField the alt text is not persisted between the 'Upload' tab on the 'Choose Image' dialog and the subsequent 'Choose a format', rather the default, image title is shown regardless of the alt text entered in the 'Upload' tab.

I think the fix is relatively simple:
`initial={"alt_text": image.default_alt_text},` [here](https://github.com/wagtail/wagtail/blob/44af83529e1082bc091b043147dda5a6a677573f/wagtail/images/views/chooser.py#L200)

would become:
`initial={"alt_text": image.alt_text if image.alt_text else image.default_alt_text},`

I am happy to raise a PR for the fix but would like someone to confirm that the proposed solution above is appropriate.

### Steps to Reproduce

1. Insert an image into a RichTextField using the default Wagtail RichText Editor
<img width="764" alt="Screenshot 2023-08-18 at 14 51 16" src="https://github.com/wagtail/wagtail/assets/1638245/ed228de3-8bee-420c-989e-5f0a768cfb92">
2. Choose the 'Upload' tab and enter details including the alt text, then press 'Upload'
<img width="1046" alt="Screenshot 2023-08-18 at 14 53 58" src="https://github.com/wagtail/wagtail/assets/1638245/86444c33-44bc-4b76-b8b0-b0bf62228767">
3. After successfully uploading the image, the 'Choose a format' dialog is shown with the alt text set to the image's title.
<img width="1043" alt="Screenshot 2023-08-18 at 14 54 16" src="https://github.com/wagtail/wagtail/assets/1638245/f0b0cbb8-5131-41a8-ba4b-48652c7d96f6">

### Expected behaviour
The alt text entered in the 'Upload' tab (step 2) is shown in the alt text field of the 'Choose a format' dialog (step 3).

### Technical details

-   Python version: 3.9.13
-   Django version: 4.1.10
-   Wagtail version: 4.2.0
-   Browser version: Chrome 114

**Comment by gasman** [comment]
The Upload form on a new Wagtail installation does not have an alt text field - I think this must be a customisation you've made with a custom image model:

![Screenshot 2023-08-18 at 15 13 45](https://github.com/wagtail/wagtail/assets/85097/aea2db82-de6f-4475-8fc0-ad155249dfc0)

Wagtail does not provide an alt text field on images as standard because we want to encourage editors to specify alt text that's [appropriate for the context where it's used](https://accessibility.huit.harvard.edu/describe-content-images) at the point of inserting it on the page, rather than globally per image.

**Comment by timothyPatterson** [comment]
No probs, thanks for looking and replying.
