### ISSUE TITLE
Attribute Error for last_published_by_user on Aging Pages report download

### ISSUE THREAD

**Issue by Morefra** [wagtail/wagtail#10821]
### Issue Summary

We have a wagtail project that is the migration of an existing website from Drupal to wagtail. Due to the volume of information being moved  we use python scripts to recreate the existing pages as model instance. The scripts read assigned csv files with the data and populate the models with the data read (usually one script per Page model). All model instance creations are done with "created_by"= "migrator" (migrator is a specific user for this)

When accessing the Aging Pages report in the admin panel, the "Last Updated By" field is blank and when trying to export the report as xlsx I get the following error: 

![last_published_by_user_Error](https://github.com/wagtail/wagtail/assets/143010000/88c13355-4ec5-4ffe-a048-932014bd07e7)

Looking at the source code in https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/reports/aging_pages.py I see that the "last_updated_by_user" field is an annotation from the Log model.  I'm not sure how the Log model implementation work, and if model instances created through scripts are logged in or not. 

When I manually do any update to a page through the administrator panel, the "last_published_by_user" is updated on the report and the error is fixed for that page. 

If it is the case that we are importing the pages incorrectly, I would like the correct way to do it so this error does not happen, and how to fix it for the pages already imported. 

### Technical details

-   Python version: 3.11.1.
-   Django version: 4.2.4`.
-   Wagtail version: 5.1
-   Browser version: Chrome 116.0.5845.97.

**Comment by cnk** [comment]
I can confirm this issue exists. The web view of the report copes with empty user information in the publish record in PageLogEntry but the Excel download errors.

**Comment by Chiemezuo** [comment]
## Steps to Recreate.
1. Open the shell in the project you're working on. In my case, it was the `bakerydemo` project I used. You could run the `python manage.py shell` in your terminal.
2. When the shell terminal opens up, you should: create an instance of the Page model, get the revision of that instance (because you cannot publish without a revision), save the instance, and then publish.
Note: You load the Page model into the shell like this:
`from wagtail.models import Page`
3. In the '**Reports**' section of the admin dashboard, select '**Aging pages**.' If step 2 was done correctly, you will see the instance you added from the terminal alongside previously created pages (if any).
4. At the top right section of your screen, click on the '**Download xlsx**' and you will be met with an error page.
![image](https://github.com/wagtail/wagtail/assets/29470516/8ad964e7-1a33-49de-8eb3-09f2c791fa62)
Note: In the picture above, the title of my `Page` instance is `from django shell`. It can be anything you name it is.
