### ISSUE TITLE
Make snippet/modeladmin query terms translatable

### ISSUE THREAD

**Issue by krzysztofjeziorny** [wagtail/wagtail#10837]
Query terms for filtering snippets fields are not translatable, leaving them in English terms. Here my partially translated `SnippetViewSet` filters example in German:

```python
    list_filter = {
        "first_name": ["iendswith"],
        "last_name": ["icontains"],
        "title": ["istartswith"],
    }
```

<img width="291" alt="Screenshot of a set of filters with partially untranslated terms for fields queries" src="https://github.com/wagtail/wagtail/assets/872730/1cc6d9ba-3316-40e3-bb1f-1b3e81dc5dce">

The terms are listed in the [modeladmin view](https://github.com/wagtail/wagtail/blob/dfaa488adde9d53ba5925ca7edd71a874af6ec86/wagtail/contrib/modeladmin/views.py#L61), but I'm not sure if they really come into play in the Snippets' view, or the [django-filter](https://github.com/carltongibson/django-filter) is used here. If so, please clarify, and I'll open an issue at Django Filter.

Many thanks!

<details><summary>Details</summary>
<p>

Wagtail 5.1.1, Django 4.2.4

</p>
</details>

**Comment by laymonage** [comment]
It's automatically generated by django-filter. It seems you can customise it via a setting, but it's subject to change: https://django-filter.readthedocs.io/en/stable/ref/settings.html#filters-verbose-lookups

If you need further customisations, it's better to override [`filterset_class`](https://docs.wagtail.org/en/stable/reference/viewsets.html#wagtail.snippets.views.snippets.SnippetViewSet.filterset_class) instead of `list_filter`. You'll have to define each filter on the filterset class, but you'll be able to define the label for each of them as well: https://django-filter.readthedocs.io/en/stable/ref/filters.html

**Comment by krzysztofjeziorny** [comment]
Thanks @laymonage! In my case it was a simple fix with an entry in settings.py:

```python
from django.utils.translation import gettext_lazy as _

FILTERS_VERBOSE_LOOKUPS = {
    "contains": _("contains"),
    "icontains": _("contains"),
}
```

and generating the messages afterwards.
