### ISSUE TITLE
Please add a progress bar to "wagtail_update_image_renditions" management command

### ISSUE THREAD

**Issue by andre-fuchs** [wagtail/wagtail#10853]
I love this new management command to regenerate all image renditions `wagtail_update_image_renditions`. But often the websites I had to use it on had many thousands of images and this command would need some hours to complete. I would love to see some kind of **progress feedback** in the terminal to get an idea of the time this task might need to complete. This could be text based of even a bar, like we know from packages like "tqdm".

**Comment by faishal882** [comment]
I think this enhancement is better, i have ran it locally:
without status bar:
![without_bar](https://github.com/wagtail/wagtail/assets/68147015/4e0742fb-4b55-4ac2-bb31-abf8c00fd99e)

with status bar:
![with_status_bar](https://github.com/wagtail/wagtail/assets/68147015/88a793a3-c9b6-40c4-a9e1-f72d63f3617c)

but before creating pr i would like to discuss it in community channel since its very minor change

**Comment by andre-fuchs** [comment]
Nice! I would vote for the status bar!

**Comment by faishal882** [comment]
Hey @andre-fuchs  i have created a pull request for this issue let see if it is merged, by the way i am totally in favor of progress bar or anything which shows progress status
