### ISSUE TITLE
Spotify oembed request gets 308 redirect response, and does not follow redirect

### ISSUE THREAD

**Issue by neil-justice** [wagtail/wagtail#10942]
### Issue Summary

When you try and embed a spotify URL, urllib gets a 308 response from spotify and raises an exception.

### Steps to Reproduce

1. try and embed a spotify URL, for example https://open.spotify.com/playlist/37i9dQZF1DWUZ5bk6qqDSy
2. a validation error occurs ("Cannot find an embed for this URL.")

By looking at the response body, I have found that it could be fixed by removing the trailing slash in the oembed spotify definition. 

So adding this workaround to my settings fixes it for me:

```python
_spotify = {
    # Only change: removed trailing slash (was "https://embed.spotify.com/oembed/"):
    "endpoint": "https://embed.spotify.com/oembed",
    "urls": [
        r"^https?://open\.spotify\.com/.+$",
        r"^https?://spoti\.fi/.+$",
    ],
}

WAGTAILEMBEDS_FINDERS = [
    {
        'class': 'wagtail.embeds.finders.oembed',
        'providers': [_spotify],
    },
    {
        'class': 'wagtail.embeds.finders.oembed',
    }
]
```

I can make a PR for this if that would be useful.

The other way you could fix this is by making it follow redirects when trying to do an embed, I suppose.

### Technical details

-   Python version: 3.10.8
-   Django version: 4.2.3
-   Wagtail version: 5.0.2

**Comment by lb-** [comment]
A PR would be great, thank you.

**Comment by rohitsrma** [comment]
I would like to work on this!

**Comment by lb-** [comment]
Go for it @rohitsrma

**Comment by dhruvpal05** [comment]
Here [10954](https://github.com/wagtail/wagtail/pull/10954) I have made a pull request, please review it.

**Comment by rohitsrma** [comment]
Hey @dhruvpal05 , have you encountered the same bug?

I wanted to confirm the issue, which is why I tested it. When I tried adding the Spotify URL mentioned above to the bakerydemo site, it worked perfectly. I also tested it on two different sites, and it's functioning well. I'm attaching screenshots for reference.

**Admin Panel**

![Screenshot (27)](https://github.com/wagtail/wagtail/assets/111359305/3d98ca40-51c2-4328-8762-65f6595f08f3)

**Working Image**

![Screenshot (28)](https://github.com/wagtail/wagtail/assets/111359305/6631615f-a72d-48e9-87c3-956d310b8562)


**Code**
```
spotify = {
    "endpoint": "https://embed.spotify.com/oembed/",
    "urls": [
        r"^https?://open\.spotify\.com/.+$",
        r"^https?://spoti\.fi/.+$",
    ],
}
```
@lb - Could you please assist in identifying the problem?"

**Comment by lb-** [comment]
Ok. Looks like the Spotify Embed URL changed a few years ago, maybe it's worth updating it to the new documented endpoint. 

See https://developer.spotify.com/documentation/embeds/tutorials/using-the-oembed-api and https://developer.spotify.com/documentation/embeds/reference/oembed

Also https://github.com/spotify/web-api/issues/1479
