### ISSUE TITLE
Screen Shakes When Adding Long Comments.

### ISSUE THREAD

**Issue by Vishal2002** [wagtail/wagtail#10984]
## Issue Summary

**Bug Description:**
When editing pages and entering lengthy content in the comment box, the screen experiences significant shaking, and the comment box fails to accommodate the entire content upon saving.

## Steps to Reproduce

**Steps:**

1. Click on the "Edit" option for an existing page.
2. You will be directed to the "Pages" section.
3. In the comment box, input a long comment or content.

**Expected Behavior:**
I expected the comment box to maintain its size and effectively handle long content without causing screen shaking. An ideal behavior is one that ensures a smooth user experience.

**Confirmation of Reproduction:**
- I can confirm that I was able to reproduce this issue as described on a fresh Wagtail project: **Yes**

## Technical Details

- Python version: 3.9.6
- Django version: 4.2.2
- Wagtail version: 5.0.2
- Browser version: Chrome 117

**Comment by codewithmide** [comment]
Hi @Vishal2002 do you mind sharing a screenshot or a gif of the affected part?

**Comment by Vishal2002** [comment]
Ok so I have One screen recording of this but it failed to capture the shaking of the screen.

https://drive.google.com/file/d/1wxrX8ltFvax2IEIm0ukdWk5oJ_bhzUqS/view?usp=sharing

**Comment by codewithmide** [comment]
> Ok so I have One screen recording of this but it failed to capture the shaking of the screen.
> 
> https://drive.google.com/file/d/1wxrX8ltFvax2IEIm0ukdWk5oJ_bhzUqS/view?usp=sharing

Oh, thanks for sharing. I didn't notice the screen shake but I noticed that the text inside the comment container is not wrapped inside. Do you intend to fix this?

**Comment by Vishal2002** [comment]
Yes I want to fix this

**Comment by codewithmide** [comment]
Oh great, you might want to keep an eye on the bug and share another video replicating the screen shake.👍

**Comment by rohitsrma** [comment]
I can confirm the issue exists!

https://github.com/wagtail/wagtail/assets/111359305/de33443a-cec1-4bf9-ba46-28a06c185a2c

Upon entering a long comment and scrolling down, the screen exhibits noticeable shaking, accompanied by rapid and unexpected changes in the style's top property, resulting in an undesirable user experience.

This issue happens when there are only a few fields on a page. If there are many fields, and you try to write a really long comment that's larger than the visible area of the fields, it becomes impossible to scroll down to see the entire comment and submit button.

![image](https://github.com/wagtail/wagtail/assets/111359305/951f639a-98da-43e7-8340-67bac7e18cd6)


### Proposed Solution

In my exploration, adjusting the position to relative seems to resolve both issues.

I would appreciate guidance and feedback from core team members along with any alternative suggestions before moving forward with a potential PR.

**Comment by lb-** [comment]
If you've got an idea for a fix - go for it @rohitsrma 

Just be sure to check any adverse impacts for how the comment position aligns with the content / field being commented across other field types and positions. For example, rich text fields.

**Comment by rohitsrma** [comment]
Thanks, @lb-. Also, I just discovered that when I posted that long comment, it overflowed the comment box. Should I report this as an issue or not?

![image](https://github.com/wagtail/wagtail/assets/111359305/2f4c6ff4-efd5-447b-8a59-0ed6b4efda26)

**Comment by lb-** [comment]
@rohitsrma it's probably a good issue to raise in isolation. Just search through the issues first. 

Also, we need to ensure any fix for this comment content also works for the text box and rendering of an applied comment. And we must not break the other fix for multi-line comments here. https://github.com/wagtail/wagtail/pull/11176
