### ISSUE TITLE
Inconsistent use of model verbose_name in permissions UI

### ISSUE THREAD

**Issue by chosak** [wagtail/wagtail#10982]
### Issue Summary

The object permissions UI doesn't show a model's [`verbose_name`](https://docs.djangoproject.com/en/4.2/ref/models/options/#verbose-name) if it differs from the model's name when it was created.

### Steps to Reproduce

Start a new project with `wagtail start myproject` and create a simple model like the following:

```py
from django.db import models

from wagtail.snippets.models import register_snippet

@register_snippet
class MyModel(models.Model):
    text = models.TextField()
```

In the group edit view, permissions render like this; note "My model" and "Can view":

![image](https://github.com/wagtail/wagtail/assets/654645/afca283f-99f6-4752-a926-6aed44365832)

Now, give the model a different `verbose_name`:

```py
@register_snippet
class MyModel(models.Model):
    text = models.TextField()

    class Meta:
        verbose_name = "Something else"
```

Now, the permissions render in a surprising way; note "Something else" and "Can view my model":

![image](https://github.com/wagtail/wagtail/assets/654645/8735d7b4-a5dc-479c-af6d-ac62aba6d6c0)

As a user, I would expect to see "Can view" the way all other objects are typically listed.

This behavior seems to come from this line that defines the permission "name":

https://github.com/wagtail/wagtail/blob/a8bc03dd8aad9d15fd4d8e84ace1bc89cbe96053/wagtail/users/templatetags/wagtailusers_tags.py#L101-L103

This code assumes that a model's content type's name (`perm.content_type.name`) will exactly match the name on the permission object (`perm.name`). This is true as long as the model's verbose name hasn't been changed, but, [per the docs](https://docs.djangoproject.com/en/4.2/ref/contrib/contenttypes/#django.contrib.contenttypes.models.ContentType.name), `content_type.name` "is taken from the `verbose_name` attribute of the model". So if a model's verbose name is changed, that change will show up when you look at its content type.

The issue is that when a model is first created, its automatically-generated permissions are given names that contain the model's  name at that time. For example, the above `MyModel` class generated permissions like this:

```
110|28|add_mymodel|Can add my model
111|28|change_mymodel|Can change my model
112|28|delete_mymodel|Can delete my model
113|28|view_mymodel|Can view my model
```

In the above example, the code assumes that since the content type reports its name as `Something else`, the permission's name will be `Can view something else`, but this isn't a valid assumption. The permission's name is still what it was when it was created, `Can view my model`. 

To fix this, the code could lookup the model objects corresponding to the permission content types and use those to do the substitution, maybe something like this:

```diff
diff --git a/wagtail/users/templatetags/wagtailusers_tags.py b/wagtail/users/templatetags/wagtailusers_tags.py
index c188425ad0..3da81fe0dd 100644
--- a/wagtail/users/templatetags/wagtailusers_tags.py
+++ b/wagtail/users/templatetags/wagtailusers_tags.py
@@ -95,11 +95,15 @@ def format_permissions(permission_bound_field):
                 }
             else:
                 extra_perms_exist["custom"] = True
+                perm_model_class = perm.content_type.model_class()
                 custom_perms.append(
                     {
                         "perm": perm,
                         "name": re.sub(
-                            f"{perm.content_type.name}$", "", perm.name, flags=re.I
+                            f"{perm_model_class._meta.model_name}$",  "", perm.name, flags=re.I
                         ).strip(),
                         "selected": checkbox.data["selected"],
                     }
```

### Technical details

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes
-   Python version: 3.11.1
-   Django version: 4.0.10
-   Wagtail version: 5.2a0

**Comment by FatGuyy** [comment]
**Claiming Issue**

Hello,

I would like to claim this issue and work on a solution for it. I've reviewed the problem description and the proposed code changes, and I believe I can address this issue effectively.

I will start by:

1. Analyzing the existing code to understand the issue thoroughly.
2. Implementing the proposed code changes.
3. Testing the changes in a Wagtail environment to ensure they resolve the problem.
4. Creating a pull request with the proposed changes for review.

I'll keep the community updated on my progress and will seek feedback if needed. If you have any specific insights or suggestions, please feel free to share them.

Looking forward to contributing!

Best regards,
Omkar

**Comment by Chiemezuo** [comment]
@FatGuyy How is the attempt at fixing the issue going? I'd love to be of help in any way I can.

**Comment by thibaudcolas** [comment]
@FatGuyy thanks for the update! As a first step I would recommend following the steps from @chosak on your own project, just to check that you get the same result. That’ll also be good information for us.

**Comment by laymonage** [comment]
I think this is a Django bug rather than a Wagtail bug: https://code.djangoproject.com/ticket/26756

**Comment by thibaudcolas** [comment]
@FatGuyy no need! Are you ok to proceed with a fix? Perhaps attempting the proposed solution from @chosak?

**Comment by FatGuyy** [comment]
I'll give the solution of @chosak a go.

**Comment by chosak** [comment]
Nice find @laymonage. I agree that since Wagtail has special handling it would be good to try to fix this here.

Thanks for willing to give this a try @FatGuyy. Unfortunately my initial fix suggested above won't work, since `model._meta.model_name` won't match the permission name if the model name has spaces (`breadtype` vs `Bread type`).

I wonder if, instead of trying to hack some kind of string-matching here, it would be better to handle the "view" permission separately (since this is one of the [built-in Django permissions](https://github.com/django/django/blob/e083f3082c71853a01bf149bda7fdbaf58d25f4d/django/contrib/auth/management/__init__.py#L24)). Wagtail could always display a "Can view" label if the model has a permission with a "view" action. All other permissions would display with whatever name they were given.

Here's a simple diff that does this:

```diff
diff --git a/wagtail/users/templatetags/wagtailusers_tags.py b/wagtail/users/templatetags/wagtailusers_tags.py
index 4e43d9d6a5..0fa900e3cc 100644
--- a/wagtail/users/templatetags/wagtailusers_tags.py
+++ b/wagtail/users/templatetags/wagtailusers_tags.py
@@ -1,5 +1,4 @@
 import itertools
-import re
 
 from django import template
 
@@ -98,9 +97,9 @@ def format_permissions(permission_bound_field):
                 custom_perms.append(
                     {
                         "perm": perm,
-                        "name": re.sub(
-                            f"{perm.content_type.name}$", "", perm.name, flags=re.I
-                        ).strip(),
+                        "name": "Can view"
+                        if permission_action == "view"
+                        else perm.name,
                         "selected": checkbox.data["selected"],
                     }
                 )
```

It looks like this, for example if BreadType's `verbose_name` is changed to "Type of bread":

|Current|Proposed|
|-|-|
|![image](https://github.com/wagtail/wagtail/assets/654645/300e1816-35a1-4f0c-b543-93e683ab3736)|![image](https://github.com/wagtail/wagtail/assets/654645/d5c67b73-a9d7-48b2-a3d9-fbd69f84239c)|

This approach would be worse than the current behavior where users haven't changed the verbose name but have defined a custom permission like "Can name person" -- the current behavior would show "Can name" but the proposed change would show "Can name person":

|Current|Proposed|
|-|-|
|![image](https://github.com/wagtail/wagtail/assets/654645/5cdf4479-28f5-41ca-8f0d-e8de9a797326)|![image](https://github.com/wagtail/wagtail/assets/654645/3d12a8a0-ef1a-4013-bd57-e23632b3cb5a)|

So this change would be better in some cases (where verbose name has been changed) and worse in others (in places where custom permissions were created with a specific naming pattern). Personally I think it would be better to remove the fragile regular expression matching in favor of more consistent behavior. What do you think @laymonage?

**Comment by laymonage** [comment]
I'm in favour of the consistent behaviour, but I don't think using the `if` to specifically check for `view` in your example would be a good idea. It's probably better to do something more generic e.g.

```python
    "name": f"Can {permission_action}"
```

This line probably needs to use `.rsplit(maxplit=1)` in case the action name contains `_`:
https://github.com/wagtail/wagtail/blob/953c980976231d6d2e1d26a58595710dcf10cc71/wagtail/users/templatetags/wagtailusers_tags.py#L88

It would look ugly if the action does contain `_` though, but that's also how Django does it: https://github.com/django/django/blob/e083f3082c71853a01bf149bda7fdbaf58d25f4d/django/contrib/auth/management/__init__.py#L29-L32

Or looking into Django's logic, maybe we can even just use `permission.name.split(maxsplit=2)` and join the first two elements. That should give us `Can {action}`.

Maybe we can use some kind of reverse-slugify trick to get rid of non-alphabet characters, so permissions e.g. `bulk_delete` can show up as `Can bulk delete` instead of `Can bulk_delete`.

**Comment by chosak** [comment]
Thanks @laymonage. Doesn't that approach assume that custom permission codenames will always be in the form `verb_model`?

Consider this example from the tests:

https://github.com/wagtail/wagtail/blob/953c980976231d6d2e1d26a58595710dcf10cc71/wagtail/test/testapp/models.py#L419-L423

Or an example [from the Django docs](https://docs.djangoproject.com/en/4.2/ref/models/options/#permissions):

```py
permissions = [("can_deliver_pizzas", "Can deliver pizzas")]
```

This would show up as `Can can deliver`, dropping the `pizzas`.

Perhaps I'm stretching too far to come up with failure cases, and it's on the user to realize how the permission codename might show up in the Wagtail admin. But it doesn't seem like an obvious thing to consider until it shows up strangely and then you'd realize that you have to go back and normalize the codename.

[Here's](https://github.com/wagtail/wagtail/blob/953c980976231d6d2e1d26a58595710dcf10cc71/wagtail/models/__init__.py#L3217) another place where Wagtail uses `codename.rsplit("_", maxsplit=1)[0]`, but in this case the codename is being compared against a specific list: `add`, `change`, `bulk_delete`, etc.

Another idea would be to use a similar hardcoded list here: if the rsplitted `permission_action` is one of `view`, `publish`, etc. then Wagtail displays `f"Can {permission_action}" as you propose, otherwise we display the user-provided human-readable `permission.name` instead.

**Comment by FatGuyy** [comment]
The first Suggested correction by @chosak didn't work.... but while testing other things maybe I found another issue...
![Screenshot 2023-10-13 at 10-54-16 Editing Editors - Wagtail](https://github.com/wagtail/wagtail/assets/106991458/2c841c87-d49b-4c8f-901d-125504606d5b)

See in custom permissions,
below is the code of both the models that I created.
```python
@register_snippet
class MyModel(models.Model):
    text = models.TextField()

    class Meta:
        verbose_name = "Something else"


@register_snippet
class MyModel2(models.Model):
    text = models.TextField()

    class Meta:
        verbose_name = "Something else 2"
```

**Comment by FatGuyy** [comment]
update - 
the bug is solved I am currently writing its tests.

**Comment by FatGuyy** [comment]
hello, I've done the need full and added a test for the code too.
But the test is small, can anyone tell me how can I make the test better?

**Comment by FatGuyy** [comment]
@thibaudcolas @laymonage

**Comment by lb-** [comment]
@FatGuyy have you raised a PR for this? Maybe that's a good next step - will let you get feedback on the proposed changes. 

Feel free to raise the PR as a draft if you're not fully confident with the approach.

**Comment by FatGuyy** [comment]
Hello, I m trying since 2 days to understand what exactly do I need to do. It got pretty confusing. Can someone brief me about what exactly is the desired output?
@lb-  @thibaudcolas @chosak

**Comment by FatGuyy** [comment]
@lb- @thibaudcolas @chosak @laymonage

**Comment by NXPY123** [comment]
> Thanks @laymonage. Doesn't that approach assume that custom permission codenames will always be in the form `verb_model`?
> 
> Consider this example from the tests:
> 
> https://github.com/wagtail/wagtail/blob/953c980976231d6d2e1d26a58595710dcf10cc71/wagtail/test/testapp/models.py#L419-L423
> 
> Or an example [from the Django docs](https://docs.djangoproject.com/en/4.2/ref/models/options/#permissions):
> 
> ```python
> permissions = [("can_deliver_pizzas", "Can deliver pizzas")]
> ```
> 
> This would show up as `Can can deliver`, dropping the `pizzas`.
> 
> Perhaps I'm stretching too far to come up with failure cases, and it's on the user to realize how the permission codename might show up in the Wagtail admin. But it doesn't seem like an obvious thing to consider until it shows up strangely and then you'd realize that you have to go back and normalize the codename.
> 
> [Here's](https://github.com/wagtail/wagtail/blob/953c980976231d6d2e1d26a58595710dcf10cc71/wagtail/models/__init__.py#L3217) another place where Wagtail uses `codename.rsplit("_", maxsplit=1)[0]`, but in this case the codename is being compared against a specific list: `add`, `change`, `bulk_delete`, etc.
> 
> Another idea would be to use a similar hardcoded list here: if the rsplitted `permission_action` is one of `view`, `publish`, etc. then Wagtail displays `f"Can {permission_action}"` as you propose, otherwise we display the user-provided human-readable `permission.name` instead.

What if we strip `Can` if there's one in the `permission_action` and do it the proposed way?

**Comment by laymonage** [comment]
Hey all, sorry I missed the conversations here and the PR. I forgot to leave a comment but I think @chosak's example about custom permissions not necessarily in the format of `verb_modelname` is valid, and in fact we already have something like this in Wagtail, i.e. the `submit_translation` permission in the simpletranslation contrib module.

I left a comment in https://github.com/wagtail/wagtail/pull/11606#pullrequestreview-1877508339 for more details, but I propose we revisit this. Thanks!

**Comment by lb-** [comment]
Ok. Should we be reverting the current PR or just build on top of it?

**Comment by laymonage** [comment]
I don't think it matters that much either way, but I'll look into this. If a revert is cleaner, then I'll add that to the PR.

**Comment by laymonage** [comment]
OK, this is quite complex due to the number of edge cases but I think I've nailed it down.

To recap the current state (before #11606):

Wagtail strips the model name (`verbose_name`, obtained via `ContentType.name`) from the `Permission.name` (I'll refer to the latter as "label" to prevent confusion with `Permission.codename`).

Django generates the permission label using a snapshot of the model's `verbose_name` in a `post_migrate` signal. The `verbose_name` can be changed after the fact, and the permission label will not be updated: https://code.djangoproject.com/ticket/26756. This is the root cause of the issue.

---

There are a few cases to consider here:

1. The `verbose_name` has never changed since the permission was created. This can be the case even with a custom `verbose_name` as long as the permissions don't yet exist in the database before you run `migrate`.
2. The `verbose_name` was initially unset (or set to be similar to Django's autogenerated one) when the permissions were created, and then the `verbose_name` was changed (like in this issue's example).
3. The `verbose_name` was already customised (different from the Django defaults) at the time the permissions were created, and then changed.

If we want to do the approach of "take the current permission label and try to remove the model name from it" like Wagtail currently does, we can only detect the first two cases:
1. Just strip `verbose_name` from the end of the permission label. Done.
2. Slightly trickier, but we can follow how Django computed the label in the first place: convert the model class's camelcase to spaces and lowercase, then strip that from the end of the permission label.
3. No way to detect this, as we have no idea where the `verbose_name` part of the label is.

Thus, the only reliable way to do this is to reconstruct the label instead. I'm leaning towards the solution mentioned by @chosak here:

> Another idea would be to use a similar hardcoded list here: if the rsplitted `permission_action` is one of `view`, `publish`, etc. then Wagtail displays `f"Can {permission_action}"` as you propose, otherwise we display the user-provided human-readable `permission.name` instead.

Considering that [Django generates the `"Can {action}"`](https://github.com/django/django/blob/e6fa74f02068b2c112de41e9c785f31041668a64/django/contrib/auth/management/__init__.py#L22-L35) for the permissions in the [`default_permissions`](https://docs.djangoproject.com/en/stable/ref/models/options/#default-permissions) `('add', 'change', 'delete', 'view')` only, let's check against that list to determine the permissions whose labels we want to reconstruct.

However, there's also a possibility of people customising the labels by changing the value in the database, so I think we should not reconstruct the label if it doesn't match the pattern of `"Can {action}"`.

Models can also override `default_permissions` to remove or add permissions, but a better way to do the latter is via [`permissions`](https://docs.djangoproject.com/en/stable/ref/models/options/#permissions) so you can customise the label. Using this option, you can completely customise the full codename (not just the action part) and the label of each permission. They may or may not start with "can" and may or may not end with the model name.

For all these other cases where we're not reconstructing the label ourselves, I'm inclined to use the label as the basis, and then try to remove the model name using the approach for case (1) and (2), for consistency using on a best-effort basis.

**Comment by laymonage** [comment]
Found another bug while investigating this, #11650. It's not a regression from #11606, but would be great to fix alongside this issue.
