### ISSUE TITLE
Page side panels overlap content within the form

### ISSUE THREAD

**Issue by cdanfon** [wagtail/wagtail#11038]
### Issue Summary

When using the preview panel, if the width gets adjusted it overlaps with the content elements hiding things such as the bin/duplicate/move arrows.

### Steps to Reproduce

1. Edit a page
2. Open the preview panel
3. Make the preview panel bigger by dragging the cursor towards the left-hand side

<div>
    <a href="https://www.loom.com/share/3557d7ae873b4f55a2855188adba6dec">
      <p>Editing Standard page: Standard page test - Wagtail - 12 October 2023 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/3557d7ae873b4f55a2855188adba6dec">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/3557d7ae873b4f55a2855188adba6dec-with-play.gif">
    </a>
  </div>

### Technical details

-   Wagtail version: 5.1
-   Browser version: Chrome 117

**Comment by codesmith25103** [comment]
I want to work on this issue. Assign me

**Comment by lb-** [comment]
@codesmith25103 please avoid spamming issues with claims or requests to be assigned. We don't assign issues in Wagtail, except for core team. 

However, if you are keen to support the project, this issue is unconfirmed and needs to be reproduced. I recommend you follow the steps outlined and check you can find the same issue, maybe add some extra notes and screenshots. 

Once that's done, have a look at the code that could be causing the issue, suggest where a fix may be applied with a comment. From there you can raise a PR. 

We recommend you read our guide to contributing, it will help explain some of the ways to get started. https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html

**Comment by Chiemezuo** [comment]
I can confirm for a fact that I also experienced this problem.

**Comment by lb-** [comment]
<img width="1937" alt="Screenshot 2023-10-18 at 8 18 20 am" src="https://github.com/wagtail/wagtail/assets/1396140/9be37e16-5a9a-4a6e-bdd2-29387599d839">


It looks like it's always been this way, but here is a proposed solution.

1. In `client/src/includes/sidePanel.js` we set the CSS Custom Property `'--side-panel-width'` on the side panel container `aside`.
2. If we move this to be set on some parent element that also contains the form we can adjust the margin on the form content. e.g. maybe we put this on `#main` or `.content`.
3. Then we need to add a suitable margin (remember to handle LTR cases) on the page-edit/page-create forms, we probably need to add a new styles file and root classes for this form such as `w-page-form`?
4. The styles file could be something like this.

```scss
.w-page-form {
  margin-inline-end: var(--side-panel-width, 0px);
}
```

Bit of a tricky one but should be doable. We may want to do a calc on the value though to be slightly less than the sidepanel width or account for edge cases somehow.

We also need to see whether we should NOT do this in some cases (e.g. small to medium viewports?) as the side panels intentionally take over the whole screen when open.

**Comment by lb-** [comment]
Update: I will flag this as an enhancement, it's likely that this was already accounted for in the original implementation and while this is a bit non-intuitive it works in most cases on larger and smaller viewport widths.

See `client/scss/components/_form-side.scss` & `client/scss/components/forms/_form-width.scss` - there is explicit handling for a different width when the side panels are open.

In which case, maybe the styles for the custom property usage should move to that styles file instead and consider when the side panels a. have enough room due to the existing width based approach b. should not be modified due to a small viewport width and the side panels opening 'over' the content and c. consider when minimap is open also potentially.

**Comment by Chiemezuo** [comment]
I'll take this up.
