### ISSUE TITLE
Clarify cascade of ordering parameters from ModelViewSet to views

### ISSUE THREAD

**Issue by cnk** [wagtail/wagtail#11165]
### Is your proposal related to a problem?

It is unclear to me how `ordering` set in a ViewSet and a View interact. At the moment BaseListingView has `default_ordering = None` which makes it difficult for views inheriting from this to set `ordering` at the view (rather than viewset) level. 

### Describe the solution you'd like

In #11162 Mathew suggested 

>  For 6.0 I think we should change the behaviour of `ModelViewSet` so that leaving `ordering` as None on the viewset causes it to be omitted from the `get_index_view_kwargs`, and do the same for any other attributes that might reasonably be left out of the viewset. (If we really want to be fancy we could define a custom 'undefined' value to distinguish between a developer leaving it unset on a ModelViewSet subclass, and explicitly setting it to None...)

This seems like a reasonable proposal and I would suggest starting with addressing only the ordering parameter and then using the same technique on additional parameters once ordering is taken care of.

With the proposed update, the new logic for determining the ordering for a view would be:

1. In the request, use ordering from query args, falling back to ordering set in item 2 if not provided. 
2. In the View, check for `ordering` defined in the view, if not available, use the value passed in from ViewSet  below
3. Define `ordering` in XViewSet and it will be passed to the views as default_ordering if and only if it is not "None"

I am not sure I see a use case for distinguishing between "a developer leaving it unset on a ModelViewSet subclass, and explicitly setting it to None". If someone could explain that distinction a bit better, I could try to incorporate that into a PR. Otherwise I suggest leaving that out and making a second change if and when it is needed.

**Comment by laymonage** [comment]
I'm not sure we even need `default_ordering` at all. It was added all the way back in a11378acf80cb7550b0edf4e307179ac6edc05ae, but since the view extends Django's `BaseListView`, there's also `ordering` (I pointed this in https://github.com/wagtail/wagtail/pull/10276#discussion_r1157149576).

I think we could use `ordering` instead of `default_ordering` (and thus making the attribute consistent with the one on the viewset).

**Comment by cnk** [comment]
That seems like a good suggestion. I only see 2 places where `default_ordering` is explicitly set (as opposed to being a local variable name) - the one in the generic `BaseListingView` and one in the images `BaseListingView`. It should be easy to change the internal usage - and hopefully also easy for third party packages / users as long as this is called out in the release notes.

**Comment by gasman** [comment]
Have been revisiting this code as part of the universal page listings work. The reason we have both `default_ordering` and `ordering` as attributes is that we support changing the ordering in response to a URL variable, and Django's BaseListingView has no provision for this. We set `self.ordering` after reading and validating the URL variable to indicate the final ordering actually used on the queryset, and this is subsequently read back for things like highlighting the correct arrow on the table. In Django's case, there's no distinction between the configuration setting (i.e. the preferred ordering as specified by the developer) and the result (i.e. the final ordering we actually used).

If there's a compelling reason to stick with Django's BaseListingView conventions (usually I'd consider doing things the Django Way to be an inherently good thing, but in this case I'd argue that the Django Way is addressing a simpler use-case than we need...) we could use `self.ordering` as the configuration setting and something like `self.selected_ordering` as the result. I feel like this is going to create a foot-gun for the view code, though, since it means having a `self.ordering` attribute floating around that we have to remember _not_ to use for the final querying / display logic.

At a stretch, we might be able to use `self.ordering` as both the configuration setting and the result - having `get_ordering` run suitably early in the execution, reading the (class-level) `self.ordering` setting, applying the URL variable logic, and writing back the result to the (instance-level) `self.ordering` attribute. But that brings us on to the other thing that's increasingly bothering me about Django's CBVs: the interplay between `self.foo` properties and `self.get_foo` methods and ensuring that `get_foo` is called in precisely one place. It's fine if there's an obvious linear path through the view logic, but in Wagtail's case where we have so many distinct components - tables, menus, filter forms - potentially wanting to access the value of `foo`, it's a recipe for spaghetti. It feels like `cached_property` (as we're [now using for `filters`](https://github.com/wagtail/wagtail/blob/b7605a4c1583fcffebee44d8d0560ee1e8e5fbda/wagtail/admin/views/generic/base.py#L184-L187)) is a much better solution to that. However, throwing a `cached_property` for `ordering` into the mix will rule out the possibility of using that name for the class-level configuration option, so we'd be stuck with `default_ordering`.

(Note that all of the above is coming from the perspective of my head planted in the `wagtail.admin.views.generic` code - I now need to take a step back and re-read the rest of this issue/PR chain to see how it impacts viewsets.)
