### ISSUE TITLE
"View live" link with multiple sites is not site aware

### ISSUE THREAD

**Issue by rjmoggach** [wagtail/wagtail#11160]
### Issue Summary

"View live" link with multiple sites is not site-aware

### Steps to Reproduce

1. create sites
2. create home pages for sites
3. create subpages
4. click on "View live" link for subpages

This is a bug.
Yes, I have confirmed that this issue can be reproduced as described on a fresh Wagtail project.

**Comment by gasman** [comment]
Sorry, there's not enough detail here to handle this as a bug report.

**Comment by rjmoggach** [comment]
updated issue. Happy to hear suggestions on a workaround - I started by refactoring django-multisite for my own purposes but the simplicity of wagtail sites seems more sublime...

**Comment by gasman** [comment]
I think the problem is that you're creating sites as the first step - if that's really the first thing you're doing on a newly created project, then only one page will exist at that point (the default "Welcome" page), and so you're presumably selecting that as the "root page" for all of your sites. You need to create the homepages first, _then_ set up the sites so that each site is associated with the relevant homepage.

That's only a guess, though - simply saying "create sites" and "create homepages" is skipping over so many details of what you're actually doing that there's no way to diagnose this properly.

**Comment by rjmoggach** [comment]
I'm creating multiple homepages in a migration and creating corresponding sites.

```
DOMAINS = [
    {
        "title": "siteA",
        "slug": "siteA-home",
        "domain": "site-a.lan",
        "port": 8000,
     },
    {
        "title": "siteB",
        "slug": "siteB-home",
        "domain": "site-b.lan",
        "port": 8000,
     },
]


def create_home_pages(apps, schema_editor):
    HomePage = apps.get_model("home.HomePage")
    ContentType = apps.get_model("contenttypes.ContentType")
    homepage_content_type = ContentType.objects.get_for_model(HomePage)
    root_page = Page.objects.order_by("id").first()
    default_locale = Locale.objects.first()
    for domain in DOMAINS:
        home_page = HomePage(
                title=domain['title'],
                slug=domain['slug'],
                subtitle=domain['subtitle'],
                established = domain['established'],
                body=domain['body'],
                locale_id=default_locale.id,
                content_type=homepage_content_type
            )
        root_page.add_child(instance=home_page)
        # Refresh the home page instance, this Must be a PageInstance for the next step to work
        home_page = Page.objects.order_by("-id").first()
        # Create a site with the new homepage set as the root
        site = Site.objects.create(
                hostname=domain['domain'],
                port = domain['port'],
                root_page=home_page,
                site_name = domain['title'],
                is_default_site=False
            )
```
