### ISSUE TITLE
`IndexView`: Search and filter don't work quite well together

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#11198]
### Is your proposal related to a problem?

Currently, if you implement a model admin by using the `ModelViewSet`, which uses search and a filter, the resulting listing view does not allow to search first, and then filter the result.
You have to filter your listing first, then you can also use the search field.

The problem is, that the filter-form does not know anything about the search-form. The other direction works, because the ajax-search seems to apply its query to the current browser location.

### Describe the solution you'd like

The filters in django usually always mirror all the current filter params (usually the existing query string) in every filter, so each filter applies its action to the current params.

Something similar has to be implemented here too.
It is a bit related to #11197, since the ajax-search would also require some adaptions, to automatically add its search-value to that state.

I'm not sure, how to solve this in a clean way. But it may require some JS to apply the filter-form's fields to the current query string.

### Additional context
In the discussion https://github.com/wagtail/wagtail/discussions/10446 there are designs with combined search and filtering. The solution to the above problem may also help when implementing this functionality or vice versa.

**Comment by laymonage** [comment]
Thank you for the report! I think one way to do it is to update the [shared `filters.html` template](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/filters.html) so that the `form` element is attached to a Stimulus controller, which will add/update the form's `action` attribute to apply the current search query as well (or failing that, intercept the form's submit event).

If implemented generically enough, the same controller can probably be attached to the download buttons for the export mechanism: https://github.com/wagtail/wagtail/blob/e16614bce8c2433e012df2d3f60b1dde9465b7de/wagtail/admin/templates/wagtailadmin/shared/export_buttons.html#L11-L15

so that the query params are consolidated (whether they come from the server's initial render, or updated after an ajax search).

**Comment by gasman** [comment]
Presumably with the universal listings redesign (#10446) we'll be able to wrap both the search and filter form in the same `<form>` element - which we probably can't do right now due to bulk action checkboxes getting in the way - and then both search and filtering can be handled by sending the serialized form contents as an AJAX request (or just making a plain non-AJAX request).

**Comment by lb-** [comment]
It might be worth noting that we can also use the `form` attribute if we find that moving some elements inside the form is not practical. 

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#form & https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#form


This way we could still adopt an approach that leverages the serialised from data and submits that as a POST request for he page and also Async for partial. Also  note that form action buttons can be associated with a form outside it's Dom structure. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#form

**Comment by th3hamm0r** [comment]
I think this has been fixed nicely with the new universal listing in 6.0, which combines filter and search.
