### ISSUE TITLE
Workflow/task states with a revision pointing to a nonexistent object causes crash on the dashboard

### ISSUE THREAD

**Issue by freddiemixell** [wagtail/wagtail#11300]
### Issue Summary
I'm not sure how this happened but I recently fixed a bug with a production Wagtail site where we needed to delete a revision that was referencing a snippet but had the wrong ID.

Bug:

```
AttributeError at /admin/
'NoneType' object has not attribute 'snippet_viewset'
Django Version: 4.2.2
Exception Location: wagtail/admin/views/home.py, line 192, in get_context_data
Python Version: 3.11.6
Wagtail Version: 5.0.2
```

### Steps to Reproduce

1. Create 2 revisions and then submit your snippet for moderators approval.
2. I'm not sure how this part happened but to reproduce: In the Revision objects update the object_id and the pk values to point to a number that doesn't exist in the pages. So if it was pointing to page 2 make it page 999 and pk '999' for both revision objects. I was able to do this by querying them Revision.objects.filter(id) through the django shell to reproduce after the fact in a local environment.
3. Login or just go to /admin and you'll see the error that I'm seeing. It's important that the last thing you do is submit it for moderators approval though it won't happen unless you do that.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I'm most interested in why a snippet that does exist could be saved with everything else correct in the revision table but have the wrong ID?

For example, I have revisions saved under object_id 154 and 166 for the same snippet. Is this a configuration error possibly?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes, but you have to manually query the revisions and update them like I described to get into the state. So, yes and no I haven't reproduced in the wild.

### Technical details

-   Python version: 3.11.6
-   Django version: 4.2.2
-   Wagtail version: 5.0.2
-   Browser version: Chrome 119

**Comment by laymonage** [comment]
Thanks for the report!

Not sure if this was the exact cause of your issue, but I can replicate this by deleting a snippet or a page that is currently in moderation.

Regardless, the root cause is that the `WorkflowState` does not get deleted along with the page/snippet and revision for some reason, leaving the generic foreign key to return `None`. I know that this is the default behaviour of generic foreign keys as per the Django docs (https://docs.djangoproject.com/en/4.2/ref/contrib/contenttypes/):

> If the related object is deleted, the `content_type` and `object_id` fields remain set to their original values and the `GenericForeignKey` returns `None`:
> ```pycon
> >>> guido.delete()
> >>> t.content_object  # returns None
> ```

but the docs also say:

> Note also, that if you delete an object that has a [`GenericRelation`](https://docs.djangoproject.com/en/4.2/ref/contrib/contenttypes/#django.contrib.contenttypes.fields.GenericRelation), any objects which have a [`GenericForeignKey`](https://docs.djangoproject.com/en/4.2/ref/contrib/contenttypes/#django.contrib.contenttypes.fields.GenericForeignKey) pointing at it will be deleted as well. In the example above, this means that if a `Bookmark` object were deleted, any `TaggedItem` objects pointing at it would be deleted at the same time.

and since we do define `GenericRelation`s (at least on pages),  I thought the cascade will happen anyway.

The quick fix is to check whether the `content_object` is `None`, but I'd like to investigate further to see if there's something we missed in order to make the cascading work reliably.

**Comment by laymonage** [comment]
OK, after looking at this again – the above only happens if you don't define a `GenericRelation` on the model. For pages, there's a default `GenericRelation` so I think we're covered. The [example in the docs](https://docs.wagtail.org/en/stable/topics/snippets/features.html#enabling-workflows-for-snippets) demonstrate adding a `GenericRelation` but I think we could be more explicit about that.

Regardless, I think we should be more defensive about accessing `WorkflowState.content_object` (and perhaps `Revision.content_object` for that matter) to avoid crashing when the object does not exist for some reason.

> I'm most interested in why a snippet that does exist could be saved with everything else correct in the revision table but have the wrong ID?
> For example, I have revisions saved under `object_id` 154 and 166 for the same snippet. Is this a configuration error possibly?

I can't see how this could've happened @freddiemixell. Could you check whether the objects with the id `154` and `166` exist and are completely different objects (not similar in content at all)? Just in case it might be that you had two similar objects and one of them was deleted, so when you looked at the revision for the deleted object it seemed as if the revision is for the other object with the id for the deleted one.

Also, do you have a `GenericRelation` to the `WorkflowState` defined on your workflow-enabled snippet model?

**Comment by freddiemixell** [comment]
Thank you for all that information, you rock! 🎸  I'm going to look into this more and see if I'm able to reproduce with a separate install that I could share.

It is very possible that someone deleted a snippet that was in moderation so I will test that to see if I could reproduce on our staging environment also.
