### ISSUE TITLE
Copying a page creates two entries for the copied page in recent edits section

### ISSUE THREAD

**Issue by bbusenius** [wagtail/wagtail#11323]
### Issue Summary
Copying a page creates two entries for the copied page (neither entry is for the original) in the "Your most recent edits" section.

### Steps to Reproduce

1. Navigate to any page in the admin and select "copy" from the list of options in the "More" dropdown.
2. When prompted, change the slug. You can change the title or not, the result will be the same.
3. Navigate to the admin root where "Your most recent edits" are listed. There are two entries.

This was confusing for one of our users who deleted the page further down in the "Your most recent edits" listing, thinking it was the original page.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **no**.

### Technical details

-   Python version: Python 3.9.18
-   Django version: 4.1.10
-   Wagtail version: 4.1.6
-   Browser version: Chrome 120

**Comment by thibaudcolas** [comment]
Hi @bbusenius, thank you for the report. I’m able to reproduce this on a fresh Wagtail site. Here’s the [recent edits implementation](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/home.py#L247-L298) for reference.

I created a "Potato" page, then copied it to two separate pages (one as draft, one as published), and get the following entries in "your most recent edits":

1. Clamato (potato copy, published)
2. Tomato (potato copy, draft)
3. Potato
4. Tomato (potato copy, draft)
5. Clamato (potato copy, published)

It looks like ordering is also incorrect.

**Comment by salty-ivy** [comment]
would like to investigate it.

**Comment by gasman** [comment]
Thanks to @elhussienalmasri for investigating this (in #11448). To summarise:

* The intent of this panel is to show the list of pages the user has most recently edited, omitting duplicates (in the case that the user has made multiple edits to one page), and showing the date of that most recent edit
* To do this, it retrieves the user's edits from the revisions table, groups them by page ID, annotates those with max(timestamp of revision) and orders them by timestamp descending - giving a result set of (page id, timestamp of most recent edit) records.
* It then retrieves _all page revisions matching those timestamps_, on the assumption that a timestamp uniquely identifies a revision. (Side note: this all happens in a single query, with a subselect.)
* This assumption is invalid, because copying a page copies its revision history, keeping the timestamps intact.

@elhussienalmasri's solution is to run a final pass over the queryset in Python, removing the duplicates. However, I would prefer to address the root cause of the problem: we shouldn't be using timestamp as a unique key.

There's also another quirk that happens here as a result of the revision history being copied: if user A edits a page, then user B copies it, then the copy will show up in user A's recent edits even though they've never touched it. In this case the recent edits query is not at fault - the revision history really does record a revision by that user, with a timestamp that's among their most recent edits.

I suggest that we update this panel to query the audit log, rather than revision records, since those correctly correspond to actual user actions and don't get duplicated on page copy - if the audit log had existed when this panel was built, we would certainly have used it in the first place...

Proposed approach:

* Use the same logic as before to obtain a table of (page id, timestamp of most recent edit) records, but use the PageLogEntry table (filtered by user ID and type=edit) instead of PageRevision
* In a separate query (to avoid the subselect and thus the special case for MySQL), retrieve the page objects with those IDs
* For each of those objects, look up corresponding timestamp from the first query and set it as a custom attribute `user_last_edited_at`
* Sort on that attribute (in Python), and render the resulting list
