### ISSUE TITLE
Snippet able to be commentted? 

### ISSUE THREAD

**Issue by salfe** [wagtail/wagtail#11350]
# i created a snippet view as below

![image](https://github.com/wagtail/wagtail/assets/8568451/c4536183-cbeb-4fe5-898c-fefd0fe97270)

i can see the preview/status button, but how can i enable the comment as below? i cannot find example, anyone can help?
![image](https://github.com/wagtail/wagtail/assets/8568451/a39dfeb6-5b12-4c1f-b5a2-6a830c49a054)

**Comment by thibaudcolas** [comment]
Hi @salfe, we use either [StackOverflow](https://stackoverflow.com/questions/tagged/wagtail)  or the [Wagtail Slack](https://github.com/wagtail/wagtail/wiki/Slack) for support requests like this. Please check there. If you believe we’re missing this feature or there’s a bug, please take the time to use one of our pre-set issue templates.

**Comment by salfe** [comment]
> Hi @salfe, we use either [StackOverflow](https://stackoverflow.com/questions/tagged/wagtail) or the [Wagtail Slack](https://github.com/wagtail/wagtail/wiki/Slack) for support requests like this. Please check there. If you believe we’re missing this feature or there’s a bug, please take the time to use one of our pre-set issue templates.

It is really strange of you, why i cannot post such issue here?

**Comment by gasman** [comment]
@salfe We use Github issues as a planning tool for keeping track of things to be fixed or improved - each issue is a task for a developer to work on. A support question is not the same thing as a developer task - it might translate to an improvement to the software, but it might just be someone misunderstanding how to use it, or it might be a duplicate of a problem we already know about. Often, a question is better answered by someone in the community rather than a core developer, so that's what our support channels are for. For these reasons, we don't use Github issues as a helpdesk - it makes it less effective as a planning tool.
