### ISSUE TITLE
Optimize deletion of ReferencesIndex objects in the `rebuild_references_index` Management Command for Large Datasets

### ISSUE THREAD

**Issue by katdom13** [wagtail/wagtail#11413]
### Is your proposal related to a problem?

When attempting to run the management command rebuild_references_index on a Heroku dyno for one of our websites, the command exits immediately. Attempts to increase memory using heroku run bash -a <app> -s Performance-L result in freezing and eventual timeout. Additionally, adjusting the chunk size with a custom value (--chunk_size 200) didn't resolve the issue. The website is using Wagtail version 4.2.

### Describe the solution you'd like

It appears that the command runs out of memory when executing the line [ReferenceIndex.objects.all().delete()](https://github.com/wagtail/wagtail/blob/v4.2.4/wagtail/management/commands/rebuild_references_index.py#L39), especially when the result set is substantial (e.g., 2,729,066 rows). A potential solution could be to enhance the management command to handle large datasets more efficiently.

### Describe alternatives you've considered

Two potential workarounds have been identified:

1. Manually delete ReferenceIndex.objects in chunks before running the rebuild_references_index command.
2. Override the management command file and customize the deletion of ReferenceIndex.objects in chunks, as demonstrated below:

```
from django.db import transaction
from wagtail.models import ReferenceIndex

total_rows = ReferenceIndex.objects.all().count()
batch_size = 100

for i in range(0, total_rows, batch_size):
    with transaction.atomic():
        chunk_pks = ReferenceIndex.objects.all().values_list("pk", flat=True)[i : i + batch_size]
        ReferenceIndex.objects.filter(pk__in=chunk_pks).delete()
```

**Comment by RealOrangeOne** [comment]
As an aside, the reason the reference index is quite as large as it is is because this application has separate non-Wagtail functionality in the same Django project, and before Wagtail 5.0, **all** models were included in the reference index, not just those used by Wagtail (opt-out, not opt-in).

Our short-term plan is to manually truncate the table during an upcoming upgrade, and rebuild the index with Wagtail 5.2, which will make the index much smaller. Although, some optimisation on deleting and recreating the index could still be useful!
