### ISSUE TITLE
On Safari, for a page with a workflow, clicking on Publish will hang

### ISSUE THREAD

**Issue by mgax** [wagtail/wagtail#11420]
### Issue Summary

Clicking on the _Publish_ button makes an API call to `/admin/pages/workflow/confirm_cancellation/{page_id}/` and then hangs.

<img src="https://github.com/wagtail/wagtail/assets/27617/c3b1521b-48a8-4535-8be0-65edb913849f" width="400">

### Steps to Reproduce

1. Set up [bakerydemo](https://github.com/wagtail/bakerydemo) `main` branch with Wagtail `main` branch in edit mode. Load the default data.
2. In Safari, locate the page _Blog_ -> _Bread and Circuses_. Its status should be _LIVE + DRAFT_.
3. Open the admin edit page for _Bread and Circuses_ and publish it.

If I edit `wagtail/admin/templates/wagtailadmin/shared/_workflow_init.html` and add an early `return`, the publish is successful.

```diff
--- a/wagtail/admin/templates/wagtailadmin/shared/_workflow_init.html
+++ b/wagtail/admin/templates/wagtailadmin/shared/_workflow_init.html
@@ -1,6 +1,7 @@
 <script>
     $(function() {
         ActivateWorkflowActionsForEditView('[data-edit-form]');
+        return;
 
         {% if publishing_will_cancel_workflow %}
             /* Make user confirm before publishing the object if it will cancel an ongoing workflow */
```

### Technical details

-   Python version: `3.11.2`.
-   Django version: `4.2.9`.
-   Wagtail version: `6.0a0`.
-   Browser version: [Safari 17](https://www.whatsmybrowser.org/b/IB1OO).

**Comment by laymonage** [comment]
I can replicate the issue.

We disable the action buttons once they're clicked (to prevent double-clicking).

https://github.com/wagtail/wagtail/blob/b7605a4c1583fcffebee44d8d0560ee1e8e5fbda/client/src/entrypoints/admin/modal-workflow.js#L40-L42

However, we also have different code that does the same in the `ProgressController`, which is more generic (used for all action buttons, not just ones that trigger a modal, so Save, unpublish, etc. also get disabled): https://github.com/wagtail/wagtail/blob/b7605a4c1583fcffebee44d8d0560ee1e8e5fbda/client/src/controllers/ProgressController.ts#L88-L97

When the workflow modal is closed, the button would normally be re-enabled via the following code:

https://github.com/wagtail/wagtail/blob/b7605a4c1583fcffebee44d8d0560ee1e8e5fbda/client/src/entrypoints/admin/modal-workflow.js#L58-L65

(The Stimulus state isn't updated, so you'll see the button enabled with the loading spinner. This is a bug as well.)

On Chrome and Firefox, `self.triggerElement` (which comes from `document.activeElement`) correctly points to the Publish button. On Safari, for some reason this points to the `body` element (possibly due to a race condition or a state between blur/focus of the elements). This means that the disable/enable code in `modal-workflow.js` doesn't work properly on Safari and instead you'll see the `body` element getting the `disabled` attribute toggled.

The JS code in the `_workflow_init.html` then tries to click the button:
https://github.com/wagtail/wagtail/blob/b7605a4c1583fcffebee44d8d0560ee1e8e5fbda/wagtail/admin/templates/wagtailadmin/shared/_workflow_init.html#L12-L31

On Safari, the button would still be disabled via Stimulus, so doing `.click()` has no effect.

Possible fixes would be to make sure `self.triggerElement` point to the correct element, or forcefully re-enabling the button in the `ModalWorkflow` handlers in `_workflow_init.html` JS code.

**Comment by mgax** [comment]
@laymonage thanks a bunch for the detailed walk-through, I'd have never figured this out on my own :) I've made a PR that fixes the issue for this specific case, but I'm guessing there are other places where the fix may be needed.

**Comment by lb-** [comment]
I wonder if it would be more appropriate to set the disabled attribute with a setTimeout in the progress controller?


```ts

import { debounce } from '../utils/debounce'; // add to imports

//...
    if (isLoading) {
      debounce(() => {
        // Disabling button must be done last: disabled buttons can't be
        // modified in the normal way, it would seem.
        this.element.setAttribute('disabled', '');
      }, null /* putting null here will run the function in the next Microtask, putting 0 here is equivalent to setTimeout, try null first  */)().then(() => {
        if (this.activeValue && this.hasLabelTarget) {
          this.labelTarget.textContent = this.activeValue;
        }
      });
    } else {
      this.element.removeAttribute('disabled');
```


@mgax - did you want to give that a go?

Maybe try this approach in a different branch and see how it goes. While normally reaching for a delay is not a good fix, here I think it would be appropriate.

**Comment by mgax** [comment]
I found [this SO answer](https://stackoverflow.com/a/46036876) about `document.activeElement` in Safari, which suggests that `document.activeElement` will _not_ point to the button that was clicked. I've made a JSFiddle to confirm: https://jsfiddle.net/mgaxpy/4pr7zj5d/5/.
- On Firefox it prints:
    ```
    "document.activeElement: BUTTON"
    "e.currentTarget: BUTTON"
    ```
- On Safari:
    ```
    "document.activeElement: BODY"
    "e.currentTarget: BUTTON"
    ```

Interestingly, I _was_ able to get `document.activeElement` to point to the button in Safari, by pressing _tab_ (to select the button) then _space_ (to simulate a click), but simply clicking the button with the mouse, even if highlighted, will unhighlight it and set `document.activeElement` to `<body>`.

So it seems that the bug is not caused by a race condition, but rather is expected behaviour in Safari. Maybe the right approach is to move away from `document.activeElement` and use `event.currentTarget` instead.

**Comment by laymonage** [comment]
Thanks @mgax, looks like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus documented this behaviour. I'm surprised `ModalWorkflow` relies on `document.activeElement` instead of taking the trigger element as part of its instantiation.

I think your solution makes sense! As you mentioned in the PR, there may be other cases that would benefit from the change. That said, `ModalWorkflow` is due for a major rework (replacing bootstrap dialog + jquery code with A11yDialog + Stimulus), so I think we should keep the changes to a minimum (like we have in your PR).

@lb- I don't think debouncing would completely solve the issue here. Yes it might allow the Publish to continue if there is no workflow in progress, but the issue will still happen when there is a workflow in progress.

Also to clarify: the Bread and Circuses page mentioned in this issue does not have a workflow in progress, but it does have a finished workflow and you can still trigger the issue with it. This is because of some quirks in the backend code that I won't elaborate, but basically this issue would happen if the page has been submitted to a workflow at least once.

**Comment by lb-** [comment]
Just encountered this same bug and was about to raise an issue. Glad it's already been raised.
