### ISSUE TITLE
Reorganise and refactor JS

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#1143]
The javascript admin-wide is somewhat untidy and isn't conducive to maintainability or intelligibility. `wagtailadmin/js/core.js` has for starters become a catch-all with a big `ondomready()` in which any number of arbitrary, unassociated scripts are run. Some scripts in the js root are specific only to the page editor, some contain comparatively neatly encapsulated functionality, some are a bit sprawling.

Within each of the apps, scripts have a semi-predicatable naming scheme, but no documentation of their dependencies or how they connect to or extend from other parts of the js environment.

Then there are the files like `wagtailadmin/edit_handlers/inline_panel.js` where we're serving js with django context vars, which is totally separate to the other js files, 

There's also the files like `wagtailadmin/pages/_editor_js.html` which also feel a bit isolated and undocumented from a dependency perspective, despite their obvious significance.

My hope is that we can address all these issues by taking on a system that either more closely ties javascript to the elements _and_ files to which it relates, splits up discrete js behaviours into individual files, and/or adds a modular, dependency based system like browserify.

**Comment by nealtodd** [comment]
You probably want to take a look over using Form Assets as a way to get CSS and JS that is coupled to forms/widgets/custom stuff into a template:

https://docs.djangoproject.com/en/1.8/topics/forms/media/ <https://docs.djangoproject.com/en/1.8/topics/forms/media/>

That may help with self-documenting and managing at least some of the CSS/JS by coupling it to the Django code rather than at the template level.

**Comment by davecranwell** [comment]
I was thinking more like Reactjs et al, but yes I'll consider anything

**Comment by JoshBarr** [comment]
Very exciting, Dave!

React makes a lot of sense – [plenty](http://atomic.io) of [heavy](https://developer.atlassian.com/blog/2015/02/rebuilding-hipchat-with-react/) [hitters](https://atom.io/) building good things with it.

Are you thinking we migrate the JS to a series of discrete React apps that are loaded as part of particular pages? We could use the Form Assets to ensure the correct entry point gets bundled for each view.

Springload have worked with the React + browserify workflow, but I hear that webpack is good at extracting/optimising common dependencies across multiple entrypoints, which might be very useful in the scenario above. Will need to look into it. 

The great news is that there's not very much Javascript code. In fact, there's more SASS:

```
> cloc --exclude-dir=vendor .

-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         300           7368           3947          22884
SASS                            29            863            180           6022
HTML                           192            566             15           4838
Javascript                      50            645            342           4013
JSON                             3             16              0           3302
CSS                              2            100            187            251
Bourne Shell                     1             12              4             17
XML                              1              0              0             13
-------------------------------------------------------------------------------
SUM:                           578           9570           4675          41340
-------------------------------------------------------------------------------
```

One thing that will help (especially if we need Flux) is having a consistent API for the client-side to work against. This might be as simple as having each form throw back JSON if we set an `Accept: application/json` header, or providing API methods via django-rest-framework or similar.

### Questions & conversation starters

* Does this fit in with what you've been imagining?
* How do we handle common deps across multiple React apps?
* Do we need to implement some node.js pipeline tools (gulp/grunt) across the board, or do we drive all the builds from django, with something like [django-webpack](https://github.com/markfinger/django-webpack)?
* Do we need an API for the client-side? Is it easy for forms to give us back JSON?
* Should we worry about runtime Dependency Injection or can we pre-compile everything?  
* ES6?

**Comment by dperetti** [comment]
Cool ! ReactJS + Webpack is definitely the way to go.
Also forget about Grunt, Gulp is so much better.

**Comment by davecranwell** [comment]
Honestly I haven't put much more thought into the practicalities than what you see in this ticket. ReactJS and browserify are two tools I particularly want to learn as I know almost nothing about either, but it also means I can't objectively evaluate whether they're even suitable for Wagtail - they might not be (although your enthusiasm suggests otherwise!).

From Torchbox's perspective time is quite a significant consideration. We've little experience of many of the issues/questions you're raising and we'd need to start using some of these things from scratch before we're capable of making Wagtail infrastructure decisions that would stand the test of time. Finding the time to learn some of these technologies, e.g ES6 and React could prove a problem.

I'll discuss resourcing at our end and see what time we can allocate to this. Our approach thus far has been a "path of least resistance" one. This may mean that rather than applying React and Webpack in one fell swoop, we instead focus on incrementally upgrading our (possibly poor) code in stages. Firstly  wrapping current code with modular loading systems for use with Browserify or Webpack, then gradually upgrade modules over time, then adding React, then perhaps shifting our entire syntax to ES6 module by module.

**Comment by gasman** [comment]
I believe what @davecranwell is after here is a way to keep our existing Javascript code better organised, not to re-architect it completely around a new framework. My knowledge of React is entirely second-hand, but my impression is that adopting it would be more the latter than the former.

If there are specific components of React that can help towards the goal of organising our code better, then we should certainly consider them. However, I'd be reluctant to make any changes that involve adopting new build tools without very compelling reasons for doing so - and anything that adds node/npm as an end-user requirement would almost certainly be a showstopper.

**Comment by davecranwell** [comment]
Organisation is a priority, but consistency is also important to me. My understanding of React (and here my knowledge is similarly second-hand) is that it could bring a more consistent way to architect both our Modals and our Settings Sidebar for example, to pick two considerably different UI elements at random.

React does however feel like too much of a leap at the moment given how little experience we have of it.

Organisationally however I'd like us to consider front end tooling like the various Node-based offerings. We're already thinking about how to generate static CSS from SASS, and similar tools might be used for JS. We previously removed Coffeescript compilation because it felt wrong - and I stand by that decision - but i'm starting to think Coffeescript was the right idea, executed in the wrong place. (I'm aware ES6 and Coffeescript are incomparable, this is merely an example of where we could have used FE tools previously)

It sounds like @gasman is rightly concerned about developers having to jump through hoops to develop Wagtail, however I'd say anyone qualified to be editing Wagtail's CSS or JS will be a self-selecting bunch probably already familiar with tools like Grunt or Gulp, or at least eager to experience them.

**Comment by dperetti** [comment]
> anything that adds node/npm as an end-user requirement would almost certainly be a showstopper.
That would not be required by end-users (they would use the compiled bundles from the distribution). The gulp pipeline would only be required by Wagtail contributors.

**Comment by davecranwell** [comment]
@dperetti what @gasman and I obliquely reference is an internal quandary we've had about how to deal with the different environmental requirement of wagtail core development, and wagtail implementation. At present development and implementation are identical.

**Comment by dperetti** [comment]
The great thing about React is that you can start slowly, with small components there and there, which can be integrated into the existing code base without having to refactor the whole thing.
You don't even need node/gulp to give a quick glance, you can just add this to the admin pages :

    <script src="build/react.js"></script>
    <script src="build/JSXTransformer.js"></script>

And you're ready to write and use a small component of your own.
You will absolutely love it !

**Comment by JoshBarr** [comment]
+1 for the node-based tooling. The most annoying dependencies to deal with are libsass and phantomjs which about half of all node projects require. They require compiling from source which can add some time to the initial `vagrant up` or docker image build. Once they're done, they're done. Most CI pipelines will cache them too. 

End users of the product would only have to load the node tooling if they were developing JS or CSS on the admin or contrib modules, but not in regular out-of-the-box use. We could make sure the assets are compiled and included in the package in a pre-publish hook.  

The main thing we need is a module loader for Javascript, to allow us to separate out concerns and easily reason about the code. That also gives us a good starting point for dropping in other dependencies (react, an es6 compiler, lodash etc) if we need them.

I agree with dperetti that React is really nice – especially when dealing with complex interfaces. The approach scales well, and can be started on discrete components. But I don't think we need to jump in right away. 

There's a few more immediate things that would be nice to clean up, such as moving `{% include %}` statements out of the JS code. I think we also need to address initialisation. Right now there's server-side for-loops printing Javascript code, which is a bit of an anti-pattern. Ideally any initial state that needs passing into components should be handled through serialising some JSON.

```javascript
// Commonly this sort of thing is done in the JS...

$(function() {
    {% for form in formset.forms %}
        panel.initChildControls('{{ formset.prefix }}-{{ forloop.counter0 }}');
    {% endfor %}
});

```

We should move it to...

```html
<!-- template.html -->
<script>
var formData = JSON.parse('{{formset.forms | jsonify }}');
formData.forEach(function(item, index) {
    panel.initChildControls(item, index);
});
</script>
```

I'd love to help sort out those things before we worry about adding more frameworks :) 

 ## Tasks
- [ ] investigate implication of node tooling on standard django project workflow
- [ ] move any django template logic out of javascript code
- [ ] Implement browserify

**Comment by davecranwell** [comment]
Yeah that would be really appreciated if you could help rationalise that JS.

The inline JS we run for our edit handlers has always felt a bit unusually to me somehow. Not just the python vars, but the way it's just a function run manually rather than anything more jquery-esque. The form `prefix` for example, couldn't that be defined in a data attribute on the initialising element rather than passed in as a function parameter? I may be way off the mark here, it's just been a minor bugbear.

**Comment by gasman** [comment]
There were solid design reasons for the edit handler JS being the way it is. I'm not saying it's necessarily the *best* design, but changing it may be more than a simple matter of code cleanup...

At the time I designed the edit handler API, I had no preconceptions of what kinds of Javascript behaviour might be required. As such, I defined a panel to be "a fragment of HTML and an arbitrary Javascript function to initialise it", rather than "a fragment of HTML following certain JQuery-ish conventions to specify its behaviour".

The 'server-side code generating Javascript code' anti-pattern probably can be eliminated now. That was necessary because different kinds of panel could have differing Javascript initialisers, in ways that cannot be defined statically; for example, a 'carousel item' InlinePanel will need different Javascript initialisation code to a 'related link' InlinePanel, but there's no point at which a human writes specific Javascript code for those two things. I also left open the possibility that different *instances* of the same panel might have different JS code - think of something like StreamField where one instance might have an entirely different combination of edit widgets from the next - so the original code would have looked something like

    {% for child in self.children %}
        panel.initChildControls("{{ child.form.prefix }}");
        {{ child.render_js_init }};
    {% endfor %}

In practice A) this turned out to be a generalisation too far - when I re-did this for the StreamField blocks API it considerably simplified things to have all instances of a block type running the same JS code - and B) @timheap refactored this so that the per-child initialisation happens inline within the child's HTML, so the *real* dynamically-generated code is no longer present here.

Outside of edit handlers, there are a couple of places in the admin where this pattern was copied unnecessarily - group permissions and search term editor's picks, I think - and those could certainly be cleaned up.

**Comment by JoshBarr** [comment]
Thanks for the explanation @gasman! I've made some small cosmetic changes to those scripts in #1174 (so the linter is happier), but after reading through the code base some more, I think we'd need to make some bigger changes to the modal workflow to eliminate the Django context vars from JS entirely, per Dave's original comment above.

It might be nice if, rather than registering the HTML and JS directly from the backend, we send a resource identifier  from the JS and the backend returns any step URLs and config vars over JSON. The front-end could then take care of how that component is loaded and implemented, and the endpoints would become more like a core API used to validate and expose data.

The current system does conveniently allow devs to share HTML markup between front-end and back-end via Ajax, but it's tricky to share the dynamic behaviours without implementing the UI logic twice, in Django templates and again in JavaScript (sprinkled with template vars). 

Any eventual move towards react/angular/ember on the client would require a bunch of REST endpoints for these workflows (and for the UI language translations).. Not a small job :) But the modals do sound like a fairly good place to start - since they're well contained and discrete workflows.

**Comment by apidictor** [comment]
Has anyone reviewed or worked with [Methril (github link)](https://github.com/lhorie/mithril.js)?

I haven't worked with it yet, however based on this post: [Mithril vs. Angular and React](https://medium.com/@l1ambda/mithril-vs-angular-vs-react-d0d659c24bae), it appears to unite the strengths of Angular and React with a simplified API.

React would still be a great choice otherwise! :-)

**Comment by MechanisM** [comment]
Would be nice if wagtail will use or offer some of django.js functionality. It offers nice front-end possibilities.

**Comment by JoshBarr** [comment]
I've worked with Mithril. It's very fast, amazing for such a tiny library. I'd be concerned about support and community if we adopted it around here - do you know of any large-scale production apps written in it?

**Comment by apidictor** [comment]
Hi Josh,

I don't know of any large-scale production apps written in Mithril so I've
asked about that here: https://gitter.im/lhorie/mithril.js

The concerns regarding support and community are well understood, however,
there are many support channels available to developers:
https://lhorie.github.io/mithril/community.html, which may help there.

**Comment by apidictor** [comment]
@JoshBarr My inquiry about large-scale apps in the [mithril.js gitter.im](https://gitter.im/lhorie/mithril.js) chat room received a response with a [Community Projects](https://github.com/lhorie/mithril.js/wiki/Community-Projects-and-Snippets#community-projects) link. Still no clear use on a large-scale.

Interestingly an opinionated model layer based on Flux was mentioned in the chat thread, named [Superflux](https://github.com/dvcolgan/superflux). I find it evidence of community interest in the project.

Lastly, one of many features I like about Wagtail is its performance. Seeing [this Todo app sample benchmark](http://lhorie.github.io/todomvc-perf-comparison/todomvc-benchmark/) shows the speed you mention that Mithrill has is quite noteworthy. Since Wagtail is very close to being a true multi-device friendly CMS the [JS performance over a device data connection](http://www.filamentgroup.com/lab/mv-initial-load-times.html) might be worth considering. 

I'm confident that with whatever choice is made Wagtail will be nothing but great :-)

**Comment by apidictor** [comment]
Found a fairly good sized project using Mithril at http://demo.flarum.org/#/ with details here http://tobyzerner.com/mithril/. The community activity I've seen in the last month and MSX https://github.com/insin/msx tips me further in support of Mithril over React.

**Comment by thibaudcolas** [comment]
It's been a while! I'll review this and figure out how relevant this is with recent developments.

**Comment by thibaudcolas** [comment]
I'm closing this issue, considering developments have happened that go in the direction discussed here, making me feel like this discussion was succesful:

- Webpack is part of the toolchain, even though I'm not sure how consistently it is used
- React is a favoured approach to building components inside of the admin, even though this is still ongoing.

The other consideration is that this issue in its current state feels very broad and open-ended ("refactor and reorganise"). That said, I am very open to new issues (better yet, PRs) being opened for specific parts of this, for example:

- Transition JS entry points to Webpack (not sure whether that should be done one by one or not)
- Transition specific UI components to React (not just porting the code, but also considering best practices from UI dev in React – unit tests, 100% test coverage, 0 linting warnings, split into reusable components)
- Document our "new way" of building the Wagtail admin's front-end: Webpack, React, etc.
