### ISSUE TITLE
Target for Richtext links

### ISSUE THREAD

**Issue by J0hn5mith** [wagtail/wagtail#1167]
Hi

It would be nice if one could define the target of a rich text link. I wanted to insert add a link which does not open in the current tab but rather in a new one. 

Cheers
![wagtail_-_richtext_bearbeiten](https://cloud.githubusercontent.com/assets/856276/7062754/b4932ef6-dea0-11e4-94b6-55ae30c98795.png)

**Comment by gasman** [comment]
Hi @J0hn5mith,
Thanks for the suggestion! This is probably not as simple as adding a checkbox, because most of the time the decision "should this link open in a new window?" is not one for page editors to make on an individual link basis, but rather a policy set by the site implementor - for example, "always open external links in a new window" or "never open links in a new window". We'll need to think carefully about the best approach for this.

**Comment by tmsndrs** [comment]
IMO this generally goes against agreed UX best practise and as @gasman says, if links are to open in a new tab/window it should be consistent across the site (or specific content areas) because a conversation has taken place between the developer and the editor/client, not on a link by link basis. 

I don't agree with everything in this article but more info on this here http://www.smashingmagazine.com/2008/07/01/should-links-open-in-new-windows/

**Comment by benje** [comment]
I am also looking for a simple way to set the target link behaviour for external links. I would be happy if this was a site-wide policy or a per link basis, just a simple way of achieving it.

It seems that people are asking for it, so i'd like to add my vote for a nice solution :)

Thanks as always to the devs doing an awesome job on wagtail

**Comment by nek4life** [comment]
Is there a way to accomplish this somehow without proper support from the wagtail framework? Without JS on the front-end?

**Comment by findsje** [comment]
I have a similar problem as nek4live but also i.e. I have to link to CC images as part of the license agreement for the images and I don't wan't my users to leave my website if they click the link for the image.
On an unrelated note it would be awesome to be able to have caption for images in rich text paragraphs too.

**Comment by gasman** [comment]
@findsje It's possible to implement captioned images using the [image formats](http://docs.wagtail.io/en/v1.3.1/advanced_topics/customisation/page_editing_interface.html#rich-text-image-formats) feature, although it's not particularly well documented - see https://github.com/torchbox/verdant-rca/blob/master/django-verdant/rca/image_formats.py . (This would also solve the problem with opening in a new window, as the link HTML is generated within the image format code, where you can specify your own markup.) However, given the difficulties of formatting images correctly within rich text, you're almost certainly better off using [StreamField](http://docs.wagtail.io/en/v1.3.1/topics/streamfield.html) if you need to do non-trivial things with images.

**Comment by nek4life** [comment]
Hey @gasman thanks for reopening this. I know our use case probably is an outlier and not standard practice, but running the site through a proxy under a subfolder in our SAAS ecommerce platform is the only way we've been able to run wagtail on the same domain. I agree with you philosophically that taking control away from the user isn't a best practice or even a good practice, but I'm unfortunately not the one making the decisions on where the link target should go.

**Comment by BertrandBordage** [comment]
If we implement a way to add `target="_blank"` (which I really would like to see!), we have to be aware of the **security issues** it has: https://mathiasbynens.github.io/rel-noopener/

From my own experience, I would say that external links should **mostly be opened in a new tab**, and internal links should always be opened in the same tab.

Most external links are just references or explanations of a word, behaving like a (side|foot)note. But sometimes, we want to make a main link to an external resource, so it’s natural to have it open in the same tab.

Most internal links are also references or explanations. But it feels more natural to have it opened in the same tab, since the global interface of the site stays the same. If users really want to have it opened as a note, in a new tab, they can still middle-click or something.

So in my opinion, users should have access to an “open in the same tab” boolean (defaulting to False) only on the external & mailto links. If some developers are still not convinced, we can add a parameter to `RichTextField` and `RichTextBlock`:
```python
RichTextField(can_target_link=False)
```

**Comment by benje** [comment]
I like this suggestion @BertrandBordage because it gives developers the flexibility to allow external links to open in a new tab if they wish (as opposed to authors who may not know or acknowledge best practice).

**Comment by gasman** [comment]
> Most external links are just references or explanations of a word, behaving like a (side|foot)note.

I'm not convinced that's true, and I'd want to see some hard evidence for that claim. But either way, this is missing the most important point: even if you think that a certain link behaviour is the 'logical' one for a particular user flow, _it's not your decision to make as a developer_ - it's the visitor's decision. Forcing your preference on the user is unhelpful: if they're comfortable with tabbed browsing, then they're capable of opening the link in a new tab for themselves. If they aren't, then forcibly opening a new tab will cause confusion. This is backed up by formal user testing:

https://www.nngroup.com/articles/multi-tab-page-parking/
https://twitter.com/griffinkate/status/648442317825814528

One of the key principles of Wagtail is that it doesn't impose any rules on your front-end code - as a developer, you're free to write whatever HTML you want - and so I won't push for `target="_blank"` to be banned outright (as much as I'd like to :smile:). However, another key principle is that Wagtail's design should provide a 'low friction' path that encourages developers to follow best practices, such as separation of content and presentation - on that basis, I think it's fair to make developers 'jump through some extra hoops' to implement opening links in new tabs. For me, that means:

* Wagtail will never provide "open links in a new tab" functionality _in its default configuration_.
* If sites *must* have links that open in new tabs, there should be a site-wide policy, defined by a developer, that determines when it happens - it should not be left to the content editor to decide on a per-link basis.

Examples of site-wide policies could be:

* All external links will open in new tabs;
* All external links except for the domains my-site.com or my-shop.com will open in new tabs;
* All external links in the body text of 'BlogPage' pages which are tagged as 'sponsored' will open in new tabs;
* All external links with a role of 'glossary' will open in new tabs.

The last one of these is more hypothetical - it assumes that we have some way to set custom properties (such as 'role') on links, which isn't a feature that currently exists in Wagtail (although you could probably implement something similar by adding a custom button "add glossary link" to the rich text toolbar). In this case, we do require the content editor to supply some extra information about the link - but it's not the same as letting them specify "this link opens in a new tab" directly. Again, it's about separating content from presentation: the content editor specifies what the link *is*, semantically, and the developer defines the presentation and behaviour for that class of links. (Here we're talking about the "open in new tab" behaviour, but the same mechanism could equally apply to `rel="nofollow"`, or just a different style of underline...)

Finally, if a developer really wants to defeat all of these 'best practice' safeguards and give their content editors direct control over link behaviour, they can still achieve that, by setting their site-wide policy to:

* All links with an open-in-new-tab flag of 'true' will open in new tabs

To get to that point, the developer would have to ignore several clear warning signs that what they're doing is bad practice. But if they're determined to do it, we won't stop them!

**Comment by chrisbarry** [comment]
Just to chime in on this again, I am consistently getting requests from clients to have all external links open in a new window, as if they are trying to sell / pitch to a users, they really don't want that user to lose the place where they were on their own site, and end up on something new. Perhaps this is just site own/admin bias, but I do believe I side with them somewhat.

My crappy solution is here http://stackoverflow.com/questions/33300941/making-external-links-open-in-a-new-window-in-wagtail with a jquery alternative that I think I prefer (less messing with wagtail internals)

**Comment by thibaudcolas** [comment]
Just looking into this again, #3257 is the way to go. This shouldn't be a big change if someone is up for it.

**Comment by Skorpyon** [comment]
three years and still no solution.

**Comment by thibaudcolas** [comment]
@Skorpyon see https://github.com/wagtail/wagtail/issues/1167#issuecomment-360836751 for a solution. All that's missing is for someone to care enough about this to implement it.

**Comment by thibaudcolas** [comment]
This can now be implemented as a site-wide policy thanks to #5159, to be released in Wagtail v2.5. Documentation: https://docs.wagtail.io/en/latest/advanced_topics/customisation/rich_text_internals.html#link-rewrite-handlers. Although the initial issue was about having this control per-link, there's been lots of discussion since then of how this would be better done by developers as a general policy based on the links' targets, so I'll close this issue now. If anyone wants to make the case for this capability within the link chooser UI, please open a new issue / comment in #4474.

---

If anyone wants to implement this in their project despite the general consensus that this is bad for user experience (see all of the comments above, and articles like https://css-tricks.com/use-target_blank/), here is what it would look like:

```python
    from django.utils.html import escape
    from wagtail.core import hooks

    def external_link_handler(attrs):
        href = attrs["href"]
        return '<a href="%s" target="_blank" rel="noopener nofollower">' % escape(href)

    @hooks.register('register_rich_text_features')
    def register_external_link(features):
        features.register_link_type('external', external_link_handler)
```

If you're wondering about the `rel="noopener nofollower"` bit there, have a look at https://mathiasbynens.github.io/rel-noopener/ (cf. https://github.com/wagtail/wagtail/issues/1167#issuecomment-198034461).

**Comment by enzedonline** [comment]
I understand the concern about site wide policies etc, the problem is that you may need to link to internal urls using the external link option because the target isn't a wagtail page. For example, I have a site with a lot of Django pages which it should be able to be linked to from a rich text block. If the site wide policy was to open all 'external' links in new tab then you'd have the same problem in reverse.

**Comment by marycklein** [comment]
I would like to be able to differentiate between "internal" target pages and "external" target pages when I'm using the rich text editor. I have a consistent practice regarding that on "our old (current)" website in Drupal. Speaking from the POV of an end user.
Also:
https://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/

**Comment by enzedonline** [comment]
@marycklein I ended up using a JQuery solution which does exactly as needed:

```
$(document).ready(function(){
    $('a[href^="http://"]').attr('target', '_blank');
    $('a[href^="http://"]').attr('rel', 'nofollow noopener');
    $('a[href^="https://"]').attr('target', '_blank');
    $('a[href^="https://"]').attr('rel', 'nofollow noopener');
    });
```
You can amend it to whichever protocols you want, and load it only on those page types you want or site-wide as needed.

Personally, I think the 'External Link' in draft-tail is misnamed as it presumes URL links would only be pointing off-site and not to any local non-Wagtail resource.

**Comment by marycklein** [comment]
Thank-you for this quick reply!

It will be good to have this flexibility and I appreciate your sharing this.

Not a technical person, I read a bit more after raising this concern, and realize better now that we will need to put some careful thought into our own “house rules” about how we apply this.

Thanks again!

Best,
Mary


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by Scotchester** [comment]
@matacino Please see this related comment: https://github.com/wagtail/wagtail/issues/4474#issuecomment-1028999923

**Comment by matacino** [comment]
@Scotchester  thanks! This looks all promising and exiting! 

"But™©" will there be a link-target? ;-)

**Comment by enzedonline** [comment]
@matacino check the JS solution a few comments up - applies to external links, leaves everything else alone

**Comment by dsl94** [comment]
A bit of a hack but it works
https://nemanjadev.medium.com/extending-wagtails-external-link-support-for-blank-and-nofollow-attributes-020d0403f64b

**Comment by m4w** [comment]
@gasman  your wrote:

> I'm not convinced that's true, and I'd want to see some hard evidence for that claim. But either way, this is missing the most important point: even if you think that a certain link behaviour is the 'logical' one for a particular user flow, it's not your decision to make as a developer - it's the visitor's decision.

I strongly disagree, especial in e-commerce it is very bad for revenue, when the customer leaves the page. And that is why I am using your argument against you:
I is not your decision as a developer to force the link to be opened in the same tab. It is the users.
But in this case the user is the one who is using your Rich-Text editor.  This user can then decide if the visitor should have everything under control or if there is a need for a new tab. 
I understand your strong opinion, therefore I would allow the new tab option only in the URL-Type not in the Internal-Link-Type.

I would much appreciate if you open up the possibilities.

**Comment by Ash-Crow** [comment]
I also concur that there should be a non-hacky way to open external links in new tabs (either at the single link or whole website level)

As [this page](https://theadminbar.com/accessibility-weekly/opening-links-in-new-tabs-or-not/) notes, there are situations when it is needed.

> When Links Opening New Tabs is Needed
>
> There is one major instance in which you need to have links open new windows or tabs: when the link is in the middle of a form or multi-step process, and clicking the link would cause the user to lose progress in the form or process if it opened in the same tab.
>
> For example, any time you’re creating a form, and you add a checkbox that says, “I agree to the terms and conditions” with “terms and conditions” linked to that policy, you want that link to open a new tab. Nothing is more frustrating than clicking a link in a form and losing the page, then having to start over from the beginning.

**Comment by cvhorie** [comment]
I am building a database website rich with data. I am supplying embedded links to quite a few indexing texts to aid the understanding and interconnections of the data.  So the text needs to open and be seen adjacent to the data, not replace it.
There may be some good reasons for having a link replacing the page one is working on but I have rarely found one which stands.
I have frequently opened 5+ webpages which I swap between trying to tease out a problem. To have one disappear if I accidentally forget to right click is extraordinarily disruptive.
