### ISSUE TITLE
Not allowed extension not showing in the error message.

### ISSUE THREAD

**Issue by Hlamallama** [wagtail/wagtail#11802]
### Issue Summary

Not allowed extension showing as blank when using the WAGTAILDOCS_EXTENSIONS setting.

### Steps to Reproduce
1. Start a new project with `wagtail start myproject`
2. Add WAGTAILDOCS_EXTENSIONS = ["doc", "pdf"]
3. Log onto Wagtail, navigate to Documents on the side menu
4. Add a new document with txt extension.
5. Error thrown File extension “” is not allowed. Allowed extensions are: doc, docx,  pdf. Instead of File extension “txt” is not allowed. Allowed extensions are: doc, docx,  pdf

![image (1)](https://github.com/wagtail/wagtail/assets/79466119/1d0ec461-5618-485c-a5da-85f40274ca9f)

### Technical details

-   Python version: 3.11.5
-   Django version: 5.0.3
-   Wagtail version: 6.0
-   Browser version: Chrome 122 and Firefox 123

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by rd3m** [comment]
It looks like there's a deeper issue here, the user shouldn't be presented with a successful upload message and then shown an error when they hit Update because the upload has actually failed already.

For example, with: `WAGTAILDOCS_EXTENSIONS = ["doc", "pdf"]`:
![image](https://github.com/wagtail/wagtail/assets/76932130/52a299a5-4fcf-433a-aa8e-90f7a6d706de)

The `.webp` file hasn't actually successfully uploaded, if we navigate to the list of Documents, it's not there. Hitting Update then shows the validation error:
![image](https://github.com/wagtail/wagtail/assets/76932130/ea54ddd4-ab40-43b9-bc2c-6d23a1844ce8)

I think this is happening because the `FileExtensionValidator` adds the error to `__all__` but when [checking if the form is valid](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/generic/multiple_upload.py#L151) we check the `"file"` key. If we add the error to the `"file"` key then the validation error is caught before the file is uploaded:
![image](https://github.com/wagtail/wagtail/assets/76932130/fd6fbe4b-9dd4-4d37-adf6-2cd5898fb3ec)

The below is a potential solution to get the above result but I'm not sure it's the best solution!
[In the model clean method:](https://github.com/wagtail/wagtail/blob/main/wagtail/documents/models.py#L71)
```allowed_extensions = getattr(settings, "WAGTAILDOCS_EXTENSIONS", None)
if allowed_extensions:
    validate = FileExtensionValidator(allowed_extensions)
    try:
        validate(self.file)
    except ValidationError as e:
        raise ValidationError(
            { "file": e.messages[0] }
        )
```

**Comment by RealOrangeOne** [comment]
Fixed in https://github.com/wagtail/wagtail/commit/5cc28acc563ff258d02a2cbea3de3bad87dfbfe6
