### ISSUE TITLE
Commenting not working on pages with `read_only` FieldPanels

### ISSUE THREAD

**Issue by mattibo** [wagtail/wagtail#11838]
### Issue Summary

When editing pages with `read_only` FieldPanels commenting does not work on the whole page.

* No Toggle button is visible

<img alt="image" src="https://github.com/wagtail/wagtail/assets/3369294/26627d82-adf8-4e8e-b474-aa2572fccbc9">

* Error is show in the browser

<img  alt="image" src="https://github.com/wagtail/wagtail/assets/3369294/1411bd04-2fa9-4720-b30c-8da63535a690">

I guess this is the specific line:
https://github.com/wagtail/wagtail/blob/fd08d209be121b7761f618393c2a490768a03b24/client/src/entrypoints/admin/comments.js#L22

At the execution the `fieldNode` is null.

### Steps to Reproduce

For me it can be reproduced in a Page model with following `content_panels`:

```python
content_panels = [FieldPanel("title", read_only=True, classname="title")]
```

### Technical details

-   Python version: `Python 3.11.1`
-   Django version: `Django==5.0.4`
-   Wagtail version: `wagtail==6.0.2`
-   Browser version: Edge 123

**Comment by mattibo** [comment]
After a litte bit of investigation:

A read only `FieldPanel` has no `field` key inside the context:

https://github.com/wagtail/wagtail/blob/fd08d209be121b7761f618393c2a490768a03b24/wagtail/admin/panels/field_panel.py#L331-L342

The variable `contentpath` from the `formattedfield` tag is empty:

https://github.com/wagtail/wagtail/blob/366a2a48c81f3c6283b01e7e8398e998e0bd454b/wagtail/admin/templatetags/wagtailadmin_tags.py#L1205

Therefore the tag `data-contentpath` is not filled:

https://github.com/wagtail/wagtail/blob/fd08d209be121b7761f618393c2a490768a03b24/wagtail/admin/templates/wagtailadmin/shared/formatted_field.html#L28

The `FieldLevelCommentWidget` wants to build a `fieldNode` and expects a `data-contentpath`:

https://github.com/wagtail/wagtail/blob/fd08d209be121b7761f618393c2a490768a03b24/client/src/entrypoints/admin/comments.js#L247-L253

As a consequence, the `fieldNode` is null which leads to the error inside the browser from the screenshot above and no commenting is possible.

**Comment by rohitsrma** [comment]
I can confirm that the issue exists.

When I set `read_only=True` for any field, I'm not getting option to add comments to any other fields. Also, an error shows up in the console.

![Screenshot (59)](https://github.com/wagtail/wagtail/assets/111359305/698c4bc2-796b-48b0-a237-8ff03f6b75ed)

After doing some research, I mostly agree with what @mattibo mentioned above. When I changed the context's `content_path` to `"contentpath": field.name if field else "disabled"`, the problem was fixed. But, I don't think hardcoding a value is the right way to solve this. So, I'm pretty sure the issue comes from the empty string we're using in the else condition. And, it's likely that one of these parts of the `comments.js` file is causing the problem.

https://github.com/wagtail/wagtail/blob/b664169b3288385c4a7e2c8bccda92fe5e6d402a/client/src/entrypoints/admin/comments.js#L22

https://github.com/wagtail/wagtail/blob/b664169b3288385c4a7e2c8bccda92fe5e6d402a/client/src/entrypoints/admin/comments.js#L249

@lb-, I'm trying to find out the exact issue, but it would be really helpful if you could take a look too.

**Comment by Strapchay** [comment]
i was able to fix this issue, would be able to push a fix for it soon
