### ISSUE TITLE
Wagtail allows users to create accounts using the same email multiple times

### ISSUE THREAD

**Issue by Victor-oss** [wagtail/wagtail#11919]
### Issue Summary
The found issue relates to the system allowing a user to register an account with an email that is already in use by another user. 

### Steps to Reproduce

1. Execute the docker script for wagtail development in https://github.com/wagtail/docker-wagtail-develop
2. Enter the admin interface
3. Click "Settings" and then click "Users"
4. Click "Add user"
5. Create two users with the same e-mail

This affects the functionality of recovering the password for a logged-out user since this functionality requires the email. If the option to create multiple accounts with the same email is intentional, then the login recovery should be done using the username, just like the login process. If the option to create multiple accounts with the same email is not intentional, then validation should be implemented in the email field, similar to the username field.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.8.19
-   Django version: 4.2.11
-   Wagtail version: 6.1a0
-   Browser version: Chrome 122

### Working on this

I have thoughts on skills needed and I am keen to work on this myself once the issue has been accepted.

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Hi @Victor-oss - thanks for the report.

This is the standard out-of-the-box behaviour of the Django framework. If you want to use email rather than username as the unique identifier for a user, you can define a custom user model:

https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#specifying-a-custom-user-model
https://docs.wagtail.org/en/stable/advanced_topics/customisation/custom_user_models.html#custom-user-models
