### ISSUE TITLE
"Conflicting migrations" when upgrading to 6.1

### ISSUE THREAD

**Issue by mjmare** [wagtail/wagtail#11928]
When I do a makemigrations with Wagtail 6.1 installed in a new virtual env, I'm getting this error: 

```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0092_query_searchpromotion_querydailyhits, 0093_uploadedfile in wagtailcore).
To fix them run 'python manage.py makemigrations --merge'

```
The suggested fix does work. It's output::
```
Merging wagtailcore
  Branch 0092_query_searchpromotion_querydailyhits
    - Create model Query
    - Create model SearchPromotion
    - Create model QueryDailyHits
  Branch 0093_uploadedfile
    - Alter field password on collectionviewrestriction
    - Alter field restriction_type on collectionviewrestriction
    - Alter field password on pageviewrestriction
    - Alter field restriction_type on pageviewrestriction
    - Create model UploadedFile

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Should these migration branches be merged? [y/N] y

Created new merge migration /Users/mjm/.pyenv/versions/vraagbaak/lib/python3.12/site-packages/wagtail/migrations/0094_merge_20240504_1854.py

```

But it worries me to see this error with a new version of WT.

**Comment by gasman** [comment]
Hi @mjmare,
The `0092_query_searchpromotion_querydailyhits` migration is something we've seen elsewhere - this is not part of Wagtail's own migrations, but would have been created when you ran `./manage.py makemigrations` under Wagtail 6.0, because you've imported the models from `wagtail.contrib.search_promotions` (probably in `search/views.py`) but did not add this app to INSTALLED_APPS - as a result Django treated these models as belonging to the core Wagtail app.

I'm a little surprised that it's failed in this specific way - I would have expected the 0092 migration to have been deleted at the point you upgraded to 6.1, in which case you'd either get a "cannot find migration file" error or `makemigrations` creating it again at the end of the Wagtail 6.1 migrations.

The suggested steps to resolve this are:

* Take a backup of your local database if there's anything in there that you can't risk losing
* Change any references to `('wagtailcore', '0092_query_searchpromotion_querydailyhits')` in your project's migrations to `('wagtailcore', '0091_remove_revision_submitted_for_moderation')`
* Run `./manage.py migrate wagtailcore 0091` locally to roll back the bogus migration
* Add `wagtail.contrib.search_promotions` to INSTALLED_APPS
* Delete the migration file `wagtail/migrations/0092_query_searchpromotion_querydailyhits.py` from your local Wagtail installation - or if you're not comfortable poking around in installed package files, uninstall and reinstall the wagtail package (making sure to install the same version that you were on previously)
* Run `./manage.py` migrate locally to get migrations up to date again

**Comment by mjmare** [comment]
You are correct: it was a somewhat older project which had the search app, but it was not installed in the settings. 

I can afford to throw everything in the database and the venv away. So no problem remaining here. 
I've been bitten before by the searchpromotions migration. So your answer was useful. Thanks!
