### ISSUE TITLE
New Wagtail installation has error in wagtail.search.models

### ISSUE THREAD

**Issue by moreplavec** [wagtail/wagtail#11982]
### Issue Summary
Now able to run clean Wagtail install

### Steps to Reproduce

1. pip install wagtail
2. wagtail start myprojectname
3. cd myprojectname
4. python ./manage.py runserver

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
yes

### Technical details

-   Python version: Run `python --version`.
Python 3.11.3 (3.10.x)
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
Django==5.0.6
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
Version: 6.1.1

### Result

```
...../search/views.py", line 5, in <module>
    from wagtail.search.models import Query
ImportError: cannot import name 'Query' from 'wagtail.search.models' (....../lib/python3.11/site-packages/wagtail/search/models.py)
```

**Comment by zerolab** [comment]
That is.. interesting because the start template doesn't have that line and it was last change 6 months ago https://github.com/wagtail/wagtail/blob/stable/6.1.x/wagtail/project_template/search/views.py

Are you sure that when you run `wagtail start` it uses the correct version and not an older one you have somewhere globally?
