### ISSUE TITLE
Content metrics in page editor - word count and reading time

### ISSUE THREAD

**Issue by albinazs** [wagtail/wagtail#12020]
### Is your proposal related to a problem?

In the [Content quality checkers](https://github.com/wagtail/wagtail/discussions/11063) discussion the new combined panel showcasing content metrics, along with the accessibility and sustainability check results was introduced.
The content metrics that need to be added first are the word count and reading time.

### Describe the solution you'd like

Screenshot of the proposed design:

![image](https://github.com/wagtail/wagtail/assets/51043550/098a1c64-2aae-40ce-a727-bac5cf3ba948)

### Describe alternatives you've considered

See the [Content quality checkers](https://github.com/wagtail/wagtail/discussions/11063) discussion

### Additional context

- use language-aware [Intl.Segmenter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) API for word count
- consider using [Axe plugins](https://github.com/dequelabs/axe-core/blob/develop/doc/plugins.md) for smooth cross-frame communication (support in headless)
- use debounce for the above metrics depending on the computation effort

### Working on this

Assigning this to @albinazs. Feedback is also welcome from everyone.

**Comment by thibaudcolas** [comment]
Noting the reading time research by @albinazs:

> For reading time, uses  238 words per minute (wpm) as an average silent reading rate for adults in English for non-fiction (related [studies](https://www.sciencedirect.com/science/article/abs/pii/S0749596X19300786), and more [studies](https://scholarwithin.com/average-reading-speed#:~:text=read%2020%20pages.-,Adult%20Average%20Reading%20Speed,of%20300%20words%20per%20minute)). Alternatively, we can use 265wpm following [Medium.](https://help.medium.com/hc/en-us/articles/214991667-Read-time) This method could be used for languages except Chinese, Japanese, and Korean. 

Using a meta-analysis for this makes a lot of sense to me. The one you selected ([How many words do we read per minute? A review and meta-analysis of reading rate](https://osf.io/preprints/psyarxiv/xynwg/), DOI: https://doi.org/10.1016/j.jml.2019.104047) seems solid. Impact factor of the journal it’s published in (Journal of Memory and Language, 3-4ish) is decent. And it’s great for us the underlying data and full article are available (pre-print).

For reading rates in other languages, here is the summary data they provide:

| Language | Aloud Nstudies | Silent Nparts | Silent Wpm | Aloud Nstudies | Aloud Nparts | Aloud Wpm | Expansion index |
| -------- | -------------- | ------------- | ---------- | -------------- | ------------ | --------- | --------------- |
| Arabic   | 10             | 673           | 181        | 5              | 281          | 142       | 822             |
| Chinese  | 18             | 786           | 260        | 4              | 197          | 152       | 980             |
| Dutch    | 7              | 403           | 228        | 3              | 161          | 171       | 1005            |
| English  | 144            | 15409         | 236        | 27             | 3482         | 190       | 1000            |
| Finnish  | 4              | 96            | 195        | 3              | 204          | 162       | 764             |
| French   | 6              | 215           | 214        | 4              | 307          | 180       | 1062            |
| German   | 13             | 853           | 260        | 16             | 2674         | 169       | 975             |
| Hebrew   | 5              | 168           | 224        | 2              | 83           | 147       | 782             |
| Italian   | 3              | 253           | 285        | 5              | 511          | 182       | 1006            |
| Korean   | 5              | 186           | 226        | 2              | 90           | 133       | 692             |
| Spanish  | 6              | 213           | 278        | 6              | 189          | 191       | 1025            |
| Swedish  | 5              | 129           | 218        | 3              | 55           | 163       | 897             |

The average silent reading rate here is 233 wpm. On that basis I think we can use the `238` wpm english value as our default when we don’t have a more specific number for the language, and otherwise use a number we define per language based on the above data.
