### ISSUE TITLE
Concurrent editing notifications - basic EditingSession model and ping / release endpoints

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#12077]
Part of [RFC 95 - concurrent editing notifications](https://github.com/wagtail/rfcs/pull/95)

* Define an EditingSession model and ping / release endpoints, as described by the "Base implementation" and "Handling unknown EditingSession IDs" sections of RFC 95
* This will support arbitrary models (page and snippet), and incorporate permission checks to verify that the user has edit permission over the specified object
* The EditingSession model should also provide a class-level 'clean-up' method as per "Clean-up of outdated sessions", but this does not need to be hooked up to the edit view at this point.

### Working on this

To be implemented by the Wagtail product team at Torchbox - we are not seeking external contributors for this.

**Comment by laymonage** [comment]
Just want to note that I think it is going to be much easier if the endpoint returns HTML instead of (or in addition to) JSON data. Many of our UI components are implemented using Django templates and template tags, e.g. [`avatar`](https://github.com/wagtail/wagtail/blob/a7af760aa7e72c45c545dab86eac9fd9ced7626a/wagtail/admin/templates/wagtailadmin/shared/avatar.html#L11-L21) (for rendering the user avatar) and [`dropdown`](https://github.com/wagtail/wagtail/blob/a7af760aa7e72c45c545dab86eac9fd9ced7626a/wagtail/admin/templates/wagtailadmin/shared/dropdown/dropdown.html#L23-L43) (for when there are many active sessions).

If we only return JSON, rendering those templates with the new data would need a lot of boilerplate/duplicate code on the client side. If we return HTML, we can leverage `SwapController` to just swap the contents with the response. That said, returning JSON can be useful if there is data from the server that we want to process/make use of in the client-side code.

We might have to resort to HTML-inside-JSON à la `ModalWorkflow`'s mechanism to get the best of both worlds. Not sure if that's a practice that we want to do these days, though 🤔

**Comment by gasman** [comment]
> That said, returning JSON can be useful if there is data from the server that we want to process/make use of in the client-side code.

We'll be using information from the ping endpoint to determine whether to show the "overwrite conflicting edits" confirmation dialog on saving - and most likely using that to pause auto-saving further down the line - so not returning JSON is probably going to paint us into a corner.

I think we're okay with HTML-inside-JSON - that's what StreamField / Telepath does for dynamically inserting HTML blocks that are defined by server-side templates. (Maybe Telepath would be a good fit for this too?)

**Comment by laymonage** [comment]
Implemented in #12102.
