### ISSUE TITLE
Overwriting get_url_parts makes page 404 under the new custom URL

### ISSUE THREAD

**Issue by PureTryOut** [wagtail/wagtail#12137]
### Issue Summary

As far as I can find [`get_url_parts`](https://docs.wagtail.org/en/stable/reference/pages/model_reference.html#wagtail.models.Page.get_url_parts) is supposed to return the full URL to the page. Overwriting this _should_, as far I understand it, make the page accessible via a custom URL rather than the tree-structure made through the Wagtail admin.

However although the Wagtail admin's "Live" button does link to the new custom URL, actually navigating to that page ends up in a 404.

### Steps to Reproduce

1. Create a new page type
2. Overwrite `get_url_parts` as follows:

```python
def get_url_parts(self, request=None):
    site_id, root_url, _ = super().get_url_parts(request=request)
    parent = self.get_parent().teampage
    return (site_id, root_url, "/test")
```
3. Create an instance of this new page via the Wagtail admin
4. Navigate to the site base URL with "/test" appended to it (for example by clicking the "Live" button in the Wagtail admin)

All the information I can find online suggests overwriting this method should be enough to make it available on a custom URL independent of the page tree structure of Wagtail but overwriting it just creates invalid URL's that 404.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.12
-   Django version: 5.0.6
-   Wagtail version: 6.1.2
-   Browser version: Firefox 128.0

**Comment by gasman** [comment]
> Overwriting this should, as far I understand it, make the page accessible via a custom URL rather than the tree-structure made through the Wagtail admin.

This isn't correct. Overriding `get_url_parts` will change the URL that a page reports as its own URL, but doesn't ensure that requests to that URL actually reach that page - for that, you need to override [the routing logic](https://docs.wagtail.org/en/stable/reference/pages/theory.html#anatomy-of-a-wagtail-request), such as defining a `route` method on the site's root page.

**Comment by PureTryOut** [comment]
Interesting, thanks for your swift answer. Reading that page shouldn't I be able to overwrite `route()` on the page then to accomplish this? In my (limited) testing it seems `route()` isn't called at all during/before matching the path to a page.

Also if overwriting `get_url_parts()` by itself just generates invalid URL's, shouldn't the docs mention somewhere that you should also overwrite some other function?

**Comment by gasman** [comment]
> Reading that page shouldn't I be able to overwrite `route()` on the page then to accomplish this?

No - when a request comes in for a URL such as `http://example.com/test/`, it will start by looking up the root page of the site `example.com`, which will typically be of type `HomePage` or similar - you would need to override `route` on this class to give it special-case handling for the path `/test/`, rather than just following the default behaviour of looking for a child page with the slug `test`. Overriding `route` on the class where you defined `get_url_parts` won't work, because it will never reach a page of that type.

> Also if overwriting `get_url_parts()` by itself just generates invalid URL's, shouldn't the docs mention somewhere that you should also overwrite some other function?

We'd be happy to consider a pull request to improve this part of the documentation. However, I suspect it's hard to give instructions that are broadly useful here, since there are many reasons that people might override `get_url_parts`, and a solution that works for a trivial case like `return (site_id, root_url, "/test")` may not be useful for real-world cases. Depending on how it's being used, the real solution might be to use RoutablePageMixin, or middleware to intercept the request, or a hard-coded URL path in urls.py.
