### ISSUE TITLE
404s for the editing sessions while in workflow

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#12209]
1. create a user group with only "access Wagtail admin" permission
2. create a user in said group
3. add a workflow task for said group
4. start a moderation workflow. When in the relevant task, the test user should be able to access the page edit form (because [`GroupApprovalTask.user_can_access_editor()`](https://github.com/wagtail/wagtail/blob/82aa1c1a61f910cb48de5f9af549ecef96bc102a/wagtail/models/__init__.py#L3765-L3766) returns `True`)
5. check the browser error console (or the server log). The editing sessions ping endpoint returns 404 because the user cannot edit pages per se (https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/editing_sessions.py#L39-L42)

https://www.loom.com/share/2c086b26ef47432bb4045543bd3c8099?sid=fa16f197-8cfe-4ddc-9e57-12b2f9b6bb60

Wagtail 6.2

**Comment by laymonage** [comment]
Just to note that while it's possible to fix this for pages by using `page.permissions_for_user(request.user).can_edit()`, the same issue also exists for snippets. Without https://github.com/wagtail/rfcs/pull/102 implemented, the logic of `PagePermissionTester.can_edit()` would need to be copied into the view.

**Comment by gasman** [comment]
Confirmed on bakerydemo - this can be replicated most easily by removing all permissions other than "access Wagtail admin" from the Moderators group, logging in as moderator / changeme, and opening the pages in the "Awaiting your review" panel.

We already have a switch between page models and snippets on this view, due to the different ways of retrieving the permission policy object, so it wouldn't be too much of a leap to add more page-specific and snippet-specific logic here while we await the permissions registry.

Another potential gotcha is locked pages - a user who is prevented from editing a page by a lock can still visit the 'edit' view in read-only form, and we presumably still want them to show up in the list as "currently viewing". This _does_ currently work, although I don't know whether that's because the current logic is correctly accounting for locks or not considering them at all... and if it's the latter, we'll need to make sure we don't break that in the process of introducing more rigorously correct permission checking.
