### ISSUE TITLE
ReferenceError: ModalWorkflow is not defined

### ISSUE THREAD

**Issue by Headmaster11** [wagtail/wagtail#12218]
### Issue Summary
When trying to click on button "change image" generated by ImageChooserBlock, nothing happened. Then I checked dev tools - console and see such error

Uncaught ReferenceError: ModalWorkflow is not defined
    at l.open (vendor.js?v=d346c9a3:2:855726)
    at o.openChooserModal (vendor.js?v=d346c9a3:2:835365)
    at HTMLButtonElement.<anonymous> (vendor.js?v=d346c9a3:2:832970)

### Steps to Reproduce

1. Page with ImageChooserBlock
2. Try to add new image
3. See the error in the console

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

Looks like it happens on any version higher that 6.0.1

### Technical details

-   Python version: 3.12.
-   Django version: 4.2.15.
-   Wagtail version: any higher that 6.0.1

**Comment by gasman** [comment]
Hi @Headmaster11 - thanks for the report.

I'm unable to replicate this on a fresh Wagtail project, with home/models.py edited as follows:

```python
from django.db import models

from wagtail.admin.panels import FieldPanel
from wagtail.fields import StreamField
from wagtail.images.blocks import ImageChooserBlock
from wagtail.models import Page


class HomePage(Page):
    body = StreamField([
        ('image', ImageChooserBlock()),
    ], blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('body'),
    ]
```

Additionally, your steps to reproduce don't seem to match the original bug description - does the error happen when adding a new image, or changing an existing one?

**Comment by Headmaster11** [comment]
@gasman - Hi. Thanks for checking. I've updated my comment. Current idea is - this might happen when upgrading wagtail version from 6.0.1 to any higher. I will try to check that myself on a fresh project later

**Comment by Headmaster11** [comment]
@gasman - seems like the issue was in `modal-workflow.js`. I have to manually add` <script src="{% versioned_static 'wagtailadmin/js/modal-workflow.js' %}"></script>` to several templates.

Hope, this will help someone

**Comment by laymonage** [comment]
@Headmaster11 Could you tell us more about those templates? That script [is already included in the `admin_base.html`](https://github.com/wagtail/wagtail/blob/stable/6.0.x/wagtail/admin/templates/wagtailadmin/admin_base.html#L59), so I'm surprised you have to add it manually. Did you override `{% block js %}` instead of `{% block extra_js %}`?

**Comment by Headmaster11** [comment]
@laymonage - sure. I'll better provide an example https://github.com/Headmaster11/wagtail_error/tree/main/templates . These templates are copied from the different project, but still relevant with my issue.

Based on your answer, I checked the templates and found that on version 6.0.1 these is no line with `<script src="{% versioned_static 'wagtailadmin/js/sidebar.js' %}"></script>` in admin_base. It is included in different places. I've added venv with 6.0.1 for confirmation

**Comment by laymonage** [comment]
> Based on your answer, I checked the templates and found that on version 6.0.1 these is no line with `<script src="{% versioned_static 'wagtailadmin/js/sidebar.js' %}"></script>` in admin_base. It is included in different places.

Yes, because 6.0.2 included a commit that moves the script inclusion from all the different places into a single `admin_base.html` template: 13153b50689cd42698b55482c7655ece9ace55da

I see you have https://github.com/Headmaster11/wagtail_error/blob/main/templates/wagtailadmin/admin_base.html. If you override `admin_base.html` in such a way, then it's expected to break whenever Wagtail makes changes to it, like we did in 6.0.2. Instead of copying Wagtail's template, you should extend the same template that you want to override (i.e. the first line should be `{% extends "wagtailadmin/admin_base.html" %}`), and only override specific blocks that you need to override.

See https://docs.djangoproject.com/en/stable/howto/overriding-templates/#extending-an-overridden-template for more details.

This is also the documented approach for customising the admin branding: https://docs.wagtail.org/en/stable/advanced_topics/customisation/admin_templates.html#custom-branding
