### ISSUE TITLE
The Workflow task type filter doesn't work in the task chooser modal

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#12210]
To reproduce:

- add a custom workflow task
- create said task type
- edit a workflow to add the task and choose from existing

https://www.loom.com/share/c9db3cac043a47938dd862655e9764a9?sid=33905af7-34c2-4419-bfb1-1ab598a66c25

Wagtail 6.2+
Confirmed it works in Wagtail 6.1

**Comment by laymonage** [comment]
Thanks, this is a regression in e7dac3e18d1c4fbb8eed7c7f32a51e5cbfd27fdc.

The line here uses `getAttribute()` instead of `form.method` to get the form's method, which doesn't normalise it to lowercase:

https://github.com/wagtail/wagtail/blob/d327a0dd5084bdc50fffac8ee92567d5e5dc7794/client/src/controllers/SwapController.ts#L282

so it incorrectly adds a body to the request:

https://github.com/wagtail/wagtail/blob/d327a0dd5084bdc50fffac8ee92567d5e5dc7794/client/src/controllers/SwapController.ts#L290

Another part of the code uses `form.method` which normalises it to lowercase:
https://github.com/wagtail/wagtail/blob/d327a0dd5084bdc50fffac8ee92567d5e5dc7794/client/src/controllers/SwapController.ts#L226-L227

Although if I remember correctly, I think I used `getAttribute` because the controller may be used with an input element instead of a form, in which case we can't use `.method`. I think we should use `getAttribute()` in both cases and normalise it to lowercase before checking the value.
