### ISSUE TITLE
Support omitting the `wagtail.admin` app from INSTALLED_APPS

### ISSUE THREAD

**Issue by RealOrangeOne** [wagtail/wagtail#12271]
### Issue Summary

On a project, I wanted to disable the Wagtail Admin app (`wagtail.admin`) and put it behind a feature-flag (also blocking the URL, which is the easy bit).

However, when doing this, `makemigrations` attempts to make a new migration for the new `Admin` and `EditingSession` models:

```
Migrations for 'wagtailcore':
  /site-packages/wagtail/migrations/0098_delete_admin_delete_editingsession.py
    - Delete model Admin
    - Delete model EditingSession
```

I suspect this is because the models are imported, but Django doesn't find the migrations because `wagtail.admin` isn't loaded (which is where the relevant migrations live).

I've worked around this by accepting that the `wagtail.admin` app can't be disabled, and instead just disabling the URLs instead.

### Steps to Reproduce

1. Remove the `wagtail.admin` app from `INSTALLED_APPS`.
2. `manage.py makemigrations --check`

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: 6.2.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

### Working on this

Before working on this, I'd want to confirm that this is actually a bug rather than intended behaviour. Do all the Wagtail apps need to be installed, or is it ok if some of them are optional? This is a fairly niche behaviour.

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
> I suspect this is because the models are imported, but Django doesn't find the migrations because wagtail.admin isn't loaded (which is where the relevant migrations live).

I think it's also to do with `wagtail.admin` having a module path within the `wagtail` app - if `wagtail.admin` isn't part of INSTALLED_APPS then it will consider the models in `wagtail.admin.models` to be part of the `wagtail` app instead. We had something similar with people editing the search.py module in the project template to enable logging to the `wagtail.contrib.search_promotions.models.Query` model without adding `wagtail.contrib.search_promotions` to INSTALLED_APPS, resulting in it creating a stray migration adding Query to wagtailcore. (Not sure why it shows up as a deletion here, though...)

In any case, our official stance (not sure off-hand if it's been documented as such, but it's how the overall architecture works) is that `wagtail`, `wagtail.admin`, `wagtail.search` and `wagtail.users` are required apps; everything else _should_ be optional, although it's probably rarely tested without at least `wagtail.images`, `wagtail.documents`, `wagtail.snippets` and `wagtail.sites`. (`wagtail.users` should ideally be in the latter set too, but it contains the UserProfile model that admin depends on - #3657)

In principle I wouldn't be against making admin optional, but I suspect that if we did that we'd have a hard time refactoring the 'secondary' apps (e.g. images) so that the bits that depend on admin are isolated from the bits used in a frontend-only setup.
