### ISSUE TITLE
No wagtailcore_revision is created when a page is moved

### ISSUE THREAD

**Issue by cyface** [wagtail/wagtail#12296]
### Issue Summary

When moving a page in Wagtail, no revision is created indicating the change in parent and subsequent change in URL.

### Steps to Reproduce

1. Create a page.
2. Publish it.
3. Validate wagtailcore_revision has current path and url_path.
4. Move page to a different place in the tree.
5. Check wagtailcore_revision and see only the original revision is there.

## Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Expect that key changes to a page, such as url_path and path would be captured in a revision.

**Comment by gasman** [comment]
Hi @cyface - I'd say this is the expected behaviour. While tree location is a property of a page model (and so a change of location could be regarded as an edit), logically it _has to_ be a property that exists outside of the concept of revision history - otherwise you'd run into situations such as a draft revision of a page existing in a different location to the live revision, or rolling back to an earlier revision and having it move to a previous location (at which point there's no guarantee that the parent page in question still exists).

Moving a page does create an entry in the audit log (wagtailcore_pagelogentry), so these kinds of 'global' changes are still captured.
