### ISSUE TITLE
MariaDB support?

### ISSUE THREAD

**Issue by robertsilen** [wagtail/wagtail#12304]
I see the README mentions MySQL - any reason not to add MariaDB? Its the default in most distros for several years already.

**Comment by laymonage** [comment]
Good question, thanks! I'm not sure we have any particular reason. Have just opened #12310, let's see what happens :)

**Comment by laymonage** [comment]
Looks like all our tests pass against MariaDB 10.5 and 11.4 🎉
https://github.com/wagtail/wagtail/actions/runs/10833582634?pr=12310

With a few caveats though:

- Parallel testing does not work due to https://code.djangoproject.com/ticket/33537
- Testing with `USE_TZ = False` does not work because both MySQL and MariaDB do not support loading timezone-aware fixtures (which ours are) when `USE_TZ = False`.
  - This is not specific to MariaDB. MySQL also suffers from the same issue, which is probably why we don't have a test strategy with `USE_TZ = False` for MySQL.
  - I couldn't find a Django ticket for this. We could probably work around this by removing timezone offsets from our all fixtures on the CI level before running the tests if `USE_TZ = False`.

What do you think @gasman, shall we start officially documenting MariaDB support?

It looks like we do have _some_ support for it already (see [`convert_mariadb_uuids`](https://docs.wagtail.org/en/stable/reference/management_commands.html#convert-mariadb-uuids)), but I think it would be reassuring for users if we officially mention it in https://docs.wagtail.org/en/stable/advanced_topics/performance.html#database (or a more dedicated page if we decide to have one) – and of course for us by having it in our CI matrix.

**Comment by robertsilen** [comment]
Nice, thanks.
