### ISSUE TITLE
WAGTAIL_WORKFLOW_REQUIRE_REAPPROVAL_ON_EDIT stale default in docs 

### ISSUE THREAD

**Issue by Snowrries** [wagtail/wagtail#12329]
Update WAGTAIL_WORKFLOW_REQUIRE_REAPPROVAL_ON_EDIT listed default to False.

### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/reference/settings.html#wagtail-workflow-require-reapproval-on-edit

### Details

Adjust language of docs to reflect default WAGTAIL_WORKFLOW_REQUIRE_REAPPROVAL_ON_EDIT is False
(unless I am misunderstanding the behavior I see)

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by Snowrries** [comment]
Was trying to replicate behavior listed in docs default, and found the default appears to be False if WAGTAIL_WORKFLOW_REQUIRE_REAPPROVAL_ON_EDIT is not specified.

Setting `WAGTAIL_WORKFLOW_REQUIRE_REAPPROVAL_ON_EDIT = True` in my settings produces the required reapproval behavior

**Comment by Snowrries** [comment]
I'm not opinionated on whether the docs are updated or the default is updated, just figure it should be aligned, and doc updates are lower friction.

**Comment by gasman** [comment]
Thanks for the report @Snowrries! I've done some digging into the history of the PR where workflows were implemented (#6256), and it looks like the flag was initially introduced as defaulting to True (9f70fe314e43b57c7f40a3f5b99074d02f68eebf), documented in that form (b2d2d60d22f56cbac5abfab11f07d4034223f8f0), and then changed to False in 8bf18c924a6fd138825fb37c907125cf336a546c. This last commit is broken down further in #6047, which makes it clear that this change was intentional - and so the documentation needs to be updated to match this behaviour.
