### ISSUE TITLE
Customize folder_name for get_upload_to

### ISSUE THREAD

**Issue by hovi** [wagtail/wagtail#12381]
### Is your proposal related to a problem?

I'd like to easily change folder for all wagtail images. I am integrating wagtail to my existing big django system so simple clear separation is needed.

### Describe the solution you'd like

I see there are hardcoded arbitrary values for `AbstractRendition.get_upload_to` (value `images`) and `AbstractImage.get_upload_to` (value `original_images`).

Extracting these hardcoded values to configuration would make setup much easier without creating my own classes only for this.

### Describe alternatives you've considered

I know I can override and customize `Image` and `Rendition` and that provides bigger (and in my case unnecessary) flexibility for different images across the system.
### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Hi @hovi - thanks for the suggestion. However, we have a long-standing design principle of not introducing global configuration settings for things that only affect a single class, and for that reason we chose the overrideable `get_upload_to` method as the preferred approach for customising this, rather than a setting. If we didn't do this, the settings file would be quickly swamped with settings for managing minor functionality, which is not a great experience for developers or for Wagtail maintainers.

**Comment by hovi** [comment]
Understood, that's fair enough! In that case I suggest separating these values from logic of `AbstractImage.get_upload_to`, because if I want to currently change only the `folder_name`, I need to duplicate the whole logic (copy-paste) it for every subclass I make.
