### ISSUE TITLE
Documents over 2GB cause a database error and fail to upload

### ISSUE THREAD

**Issue by ggetzie** [wagtail/wagtail#12396]
### Issue Summary

When uploading a large document (2.41GB) the upload failed with an Integer out of range error.

### Steps to Reproduce

1. Create a wagtail project
2. Attempt to upload a document where the file size is larger than the maximum int value in the database (about 2GB)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expected the document to upload normally as other documents do.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Working on this

I have prepared a pull request to modify the AbstractDocument class in documents.models to use PositiveBigIntegerField for file_size instead of PositiveIntegerField. This will resolve the issue.

**Comment by pcraciunoiu** [comment]
I just ran into this and had to override the document model and declare file_size as a `BigIntegerField`. Luckily we were already using custom document models, otherwise this would have required a data migration too. Dropping here in case it's helpful.

I do think you might as well make it a bigint so people don't hit this issue. Using django-s3direct with Wagtail works wonders, so it's easy to upload large video files these days.


```python
from django.db import models

from wagtail.documents.models import AbstractDocument

class CustomDocument(AbstractDocument):
    file_size = models.BigIntegerField(null=True, editable=False)

```
