### ISSUE TITLE
Broken query in PagePermissionPolicy.get_all_permissions_for_user()

### ISSUE THREAD

**Issue by maximiliancw** [wagtail/wagtail#12404]
### Issue Summary

I am using `django-allauth` to handle external user signups, allowing each user to create a so-called `PartnerAccount`. Upon signup, I create a profile (`PartnerPage`) for each such account, which is a subclass of Wagtail's `Page` model . Each user should be able to manage their profile without having access to the entire Wagtail backend. The profiles will be shown to the general public on the frontend of my site.

To achieve this, I assign each user to a dedicated group (created using Wagtail's `GroupForm`) and grant the group all relevant permissions (e.g., `add_page`, `access_admin`, `edit_page`, ...). The group assignment and permissions setup appear to work correctly in the admin UI when logged in as a superuser (I can see that all groups and permissions are set up correctly).

However, when I try to access Wagtail's admin area with a user created via `django-allauth`, I receive this error:
`ValueError: Cannot query "<User Object>": Must be "Group" instance.` 

The error seems to stem from a faulty query in Wagtail's permission system, specifically in [`wagtail/permission_policies/pages.py`](https://github.com/wagtail/wagtail/blob/a199096af3b4a16244d8b181707a190c28c32e88/wagtail/permission_policies/pages.py#L18).

### Steps to Reproduce

1. Create a new Wagtail project with `wagtail start myproject`.
2. Install and set up `django-allauth` for user registration.
3. Create a profile page for each user and a corresponding group with permissions (`add_page`, `access_admin`, etc.) using Wagtail's `GroupForm` (outside of the Wagtail admin UI)
4. Assign the user to the group and attempt to access Wagtail’s admin UI as the external user (not a superuser).
5. Observe the error when trying to load the page edit view in the Wagtail admin.

**I have confirmed that this issue can be reproduced as described on a fresh Wagtail project.**

### Technical details

- Python version: `Python 3.12.7`
- Django version: `Django 5.0.9`
- Wagtail version: `Wagtail 6.2.2`
- Browser version: Chrome Version 129.0.6668.100

### Working on this
The issue is that Wagtail's permission system tries to query like this:

`GroupPagePermission.objects.filter(group__user=user)`

Since the `Group` model in Django does not have a `user` field, the query fails.  
Instead, the query should be performed through the user's group memberships. For example:

`GroupPagePermission.objects.filter(group__in=user.groups.all())`

**I would be happy to create a PR for this, but I want to confirm that the error is not on my local side of things.**

---

PS: I'm wondering why this works for regular users but not for the ones I created via `django-allauth`, since both **should** be using the same authentication models under the hood.

PPS: If anyone here can help me to enable external users to manage a page with or without Wagtail UI, please let me know!

**Comment by gasman** [comment]
Hi @maximiliancw - thanks for the report. However, this doesn't give us enough detail to replicate the issue - for example, rather than saying "Create a profile page" you need to provide us with the exact code you're putting into models.py. Otherwise, someone following these steps is going to arrive at different code to you, and there's no guarantee that their version will produce the error.

> Since the `Group` model in Django does not have a `user` field, the query fails.

The `user` relation on Group is set up by the `groups` relation on Django's `PermissionsMixin` (note the line `related_query_name="user"`, which sets the name for the reverse relation to use in filter expressions):

https://github.com/django/django/blob/cee95e6172f2ea3dbf8cfd4214562cfc92f95392/django/contrib/auth/models.py#L323-L333

I'm not familiar enough with django-allauth to know whether it uses something else in place of PermissionsMixin, but this is documented as a requirement for custom user models in Wagtail - https://docs.wagtail.org/en/stable/advanced_topics/customisation/custom_user_models.html#creating-a-custom-user-model
