### ISSUE TITLE
Add support for fields with input mask

### ISSUE THREAD

**Issue by MechanisM** [wagtail/wagtail#1243]
Wagtail has envelope icon, so I think it could be added for email field.
And maybe pencil icon for text.

![Missing icons](http://i.imgur.com/IgVKBQL.png)

**Comment by SalahAdDin** [comment]
:+1:

**Comment by davecranwell** [comment]
The purpose of the icons in these fields is to indicate behaviour or validation requirements which would not otherwise be obvious from the default input styling. Indeed if every input had an icon, users would become icon-blind.

I'd be in favour of adding an email icon for the above reasons, but nothing for regular fields.

**Comment by MechanisM** [comment]
Would be nice to have also phone number field with input mask and icon ;)

**Comment by caioariede** [comment]
I'd recommend https://github.com/caioariede/django-input-mask :)

**Comment by thibaudcolas** [comment]
This hasn't received much traction over more than two years so I'm tempted to close. From what I gather, having input masks everywhere wouldn't be desirable, and having input masks in some important place is totally something people can implement in their own site should they want to.

If someone disagrees we can reopen.
