### ISSUE TITLE
Image choose permission is not assigned to default groups during initial migrations

### ISSUE THREAD

**Issue by bruecksen** [wagtail/wagtail#12581]
### Issue Summary
A User with staff status, in group Editors and Moderators with all permissions assigned (also the groups have all permissions assigned) can't see any images in the ImageChooser modal. But the user can see all the images on the image page itself. And it is also possible to add a new image in the modal (that is then correctly used in the streamfield).  But even the newly added image is not shown in the modal after going back to it.

![Image](https://github.com/user-attachments/assets/6d8242cb-8cbe-4055-97b0-c534bfd56f19)
![Image](https://github.com/user-attachments/assets/0bddcd1e-8090-4e24-bff5-b3ba7177fe84)

### Steps to Reproduce

1. Checkout current bakerydemo projekt
2. Make bakerydemo projekt run
3. Add a User account with Statt status, and all Permissions assigned
4. Log into this account
5. Edit the **Welcome to the Wagtail Bakery!** page
6. Click on the three dots next to an image and select **Change Image**
7. Image Chooser shows no images

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11
-   Django version: 5.1.3
-   Wagtail version: 6.3

**Comment by gasman** [comment]
Replicated on a `wagtail start` project by editing `home/models.py` to

```python
from django.db import models

from wagtail.admin.panels import FieldPanel
from wagtail.models import Page


class HomePage(Page):
    image = models.ForeignKey(
        'wagtailimages.Image', blank=True, null=True, on_delete=models.SET_NULL, related_name='+'
    )

    content_panels = Page.content_panels + [
        FieldPanel("image"),
    ]
```
then running `./manage.py makemigrations` and `./manage.py migrate` with no prior existing database.

It seems that migrations generally run in alphabetical order of app label when there are no dependency rules to direct otherwise, so on a fresh project where there are no cross-app dependencies on `wagtailadmin`, `wagtaildocs` and `wagtailimages`, `wagtailadmin` will win. However, as soon as a project starts introducing foreign keys to Image (within an app that comes before `wagtail` alphabetically), the dependency on `wagtailimages` in the resulting migration will push `wagtailimages` up the priority list.

Of course, this only arises as an issue if you rebuild the database from scratch _after_ the project has come that far (and you don't import an older database dump into it), and then only if you stick with the default groups. So, this is likely to be somewhat common, but not universal :-)
