### ISSUE TITLE
Caching OEmbed markup prevents markup changes for existing embeds

### ISSUE THREAD

**Issue by dryan** [wagtail/wagtail#1267]
The database caching strategy keeps the rendered embed markup. This means that if you implement a change like https://gist.github.com/kaedroho/ec2b2e83f2f4ecfb9677 to fix an issue with an embed provider, any existing embeds don't get fixed.

My thinking would be to cache the output of the oembed request instead of the embed itself, then re-render the embed from that on subsequent lookups.

**Comment by DarrenN** [comment]
Would like to chime in that this issue really bit us in production, as a change to the embed functions (to allow https in YouTube embeds) was not reflected in previously embedded videos, causing quite a bit of confusion and scrambling during a deadline.

**Comment by kaedroho** [comment]
Thanks for reporting this. A quick fix would be to clear out the ``Embed`` model every time you make a change to your embeds settings (this will cause all embeds to be refetched on the next request).

**Comment by SalahAdDin** [comment]
I don't understand.

**Comment by gambolputty** [comment]
@SableWalnut I think, what @kaedroho meant is to delete all `Embed `-objects:

`python manage.py shell`

```python
from wagtail.embeds.models import Embed
Embed.objects.all().delete()
```

After that, wagtail will lookup the embed code again.

**Comment by lb-** [comment]
Older issue but a potential candidate for a management command? 

Flagging as a good first issue to implement this approach based on the code snippet above, documentation could also be included in the embeds for this.

We already flag that you may want to delete embeds if you change something here https://docs.wagtail.org/en/stable/advanced_topics/embeds.html#deleting-embeds

So that would be a good place to add a link to the management command.

**Comment by PaarthAgarwal** [comment]
Working on it.

**Comment by 4the4ryushin** [comment]
may i take up this one?

**Comment by lb-** [comment]
@4the4ryushin - yeah go for it but please check you understand the issue fully and can reproduce the problem as described.

It may be good to add a comment with the exact steps to reproduce a scenario like this on a new Wagtail project, this will also help for any kind of PR validation when you prepare it.

**Comment by 4the4ryushin** [comment]
@lb-  i have understood the issue would soon write the steps to reproduce it,  so we are approaching it the issue in way that 
we need to write a management command for deleting the embeds in order to wagtail to re fetch embed code?
what should i name it the command?

**Comment by lb-** [comment]
Have a look at existing commands, we would need docs also. 

https://docs.wagtail.org/en/stable/reference/management_commands.html

Probably `wagtail_purge_embeds` or just `purge_embeds`

**Comment by 4the4ryushin** [comment]
Got it, on it

**Comment by lb-** [comment]
Here is the code and the tests for the purge revisions command, the new command can be implemented very much the same. Without needing any Params support. 

https://github.com/wagtail/wagtail/blob/main/wagtail/management/commands/purge_revisions.py

Tests. 
https://github.com/wagtail/wagtail/blob/main/wagtail/tests/test_management_commands.py#L591

However, these files need to live in the embeds app folder
https://github.com/wagtail/wagtail/tree/main/wagtail/embeds

**Comment by 4the4ryushin** [comment]
@lb-  thank you so much, very much appreciated saved me a lot of " dig up "

**Comment by 4the4ryushin** [comment]
> The database caching strategy keeps the rendered embed markup. This means that if you implement a change like https://gist.github.com/kaedroho/ec2b2e83f2f4ecfb9677 to fix an issue with an embed provider, any existing embeds don't get fixed.
> 
> My thinking would be to cache the output of the oembed request instead of the embed itself, then re-render the embed from that on subsequent lookups.

STEPS TO REPRODUCE THE ISSUE:

1.  create  a normal blog page , you can even follow  getting started guide https://docs.wagtail.org/en/stable/getting_started/tutorial.html#

2.  In any your template  load embed tags and and use the tag anywhere in the template to embed a demo video
 use the embed tag, https://docs.wagtail.org/en/stable/advanced_topics/embeds.html#embed-tag
 
3.  in your settings put the following setting, 
```python
WAGTAILEMBEDS_FINDERS = [
    {
        'class': 'wagtail.embeds.finders.oembed'
    }
]
```

**Comment by 4the4ryushin** [comment]
> The database caching strategy keeps the rendered embed markup. This means that if you implement a change like https://gist.github.com/kaedroho/ec2b2e83f2f4ecfb9677 to fix an issue with an embed provider, any existing embeds don't get fixed.
> 
> My thinking would be to cache the output of the oembed request instead of the embed itself, then re-render the embed from that on subsequent lookups.

STEPS TO REPRODUCE THE ISSUE:

1.  create  a normal blog page , you can even follow  getting started guide https://docs.wagtail.org/en/stable/getting_started/tutorial.html#

2.  In any your template  load embed tags and and use the tag anywhere in the template to embed a demo video
 use the embed tag, https://docs.wagtail.org/en/stable/advanced_topics/embeds.html#embed-tag
 
3.  in your settings put the following setting, 
```python
WAGTAILEMBEDS_FINDERS = [
    {
        'class': 'wagtail.embeds.finders.oembed'
    }
]
```
4.   Create a file in your app folder eg :- myapp/embeds.py
5.   put the following code in embeds.py to create custom embed finder,  https://gist.github.com/4the4ryushin/e6a5b3c0a588883538ca5fb7b5ed4e12 
at line 50 i have hardcoded an another video url to observe the changes brought by it so this custom finder would always embeds the same video regardless of any url.

6.  change the settings to use the custom embed founder 
 ```python
WAGTAILEMBEDS_FINDERS = [
    {
        'class': 'myapp.embeds.CustomEmbedFinder'
    }
]
```
7. now run the server and reload the blog page to see the if the embed video changes to our hard coded video 

expected behaviour : video  should have changed to hard coded video, as we replaced our new custom embed finder
actual behaviour:  video doesn't changes unless we deleted the Embed model object and refetch the code again .
this addresses the issue #1267

**Comment by 4the4ryushin** [comment]
@lb-  i have made made the PR https://github.com/wagtail/wagtail/pull/9568 and comment on steps to reproduce an error 
kindly review it at your ease, thank you .

**Comment by 4the4ryushin** [comment]
@lb-  thanks a lot i have applied all the suggestions , kindly review at your ease.
