### ISSUE TITLE
Difficult to use wagtail without django permissions architecture

### ISSUE THREAD

**Issue by scaryclam** [wagtail/wagtail#1384]
Hello,

I'm trying to use wagtail in an existing project, to replace the home-rolled CMS solution that we are using.
The difficulty that we are having, is that the site is not _just_ a CMS and requires a more involved permissions structure than Django can provide.

I was wondering if you would be open to accepting a PR that removes the requirement for django permissions, mainly by allowing us to move the permissions decorators into the urls.py file instead of decorating the views themselves. This would allow us to override the behavior with our own urls.py file instead of having to override the views themselves.

**Comment by tomdyson** [comment]
Hi @scaryclam, we're definitely interested in this. There's another Wagtail user who we believe needs something similar.

**Comment by scaryclam** [comment]
That's good to hear :) It's looking more likely that we'll be using wagtail in our project, so I'll pull down your master branch and start seeing what we can do to help out.

**Comment by scaryclam** [comment]
Hi, someone got in touch with me regarding this but unfortunately I had an issue with my email that resulted in losing many of them. I think I have a solution for this that shouldn't be too intrusive. I'll be trying to make a PR in the next few days, unless I find that this issue is deprecated.

**Comment by gasman** [comment]
It occurs to me that the current work on image/document collections (https://groups.google.com/d/msg/wagtail-developers/kE-aDrOIzRI/Cc2CP3KbAwAJ, https://github.com/torchbox/wagtail/wiki/Collections-RFC) is going to complicate this a bit. Currently page editing *doesn't* use simple `permission_required` decorators, because Wagtail has its own permission model for pages that's more fine-grained than Django's - and when collections are implemented, images and documents will be in the same situation.

As a result, overriding / disabling the permission model is not going to be a simple case of moving `permission_required` decorators out of views and onto URLs - because fewer and fewer areas of Wagtail admin will be using those decorators.

Instead, I think we'd have to define a swappable Permissions module to accompany each of the models we're interested in (Page, Image, Document and so on) - this module would implement a standard API that can be queried to answer questions like:

* Is user X allowed to edit document Y?
* Which collections does user X have 'add_image' permission on?
* Which users are allowed to edit documents in collection Z?
* Does user X have any image-related permissions at all?

(For pages, we have a couple of classes in `wagtailcore.models` which do this sort of task - `UserPagePermissionsProxy` and `PagePermissionTester` - but these may well need to be rewritten if we're going to generalise this to other models.)

Different versions of these modules would implement different permission policies - you could have one that implements the current fine-grained permission policy, one that implements the basic Django model-by-model policy, or a trivial 'allow everyone to do everything' policy that effectively turns off permissions entirely.

Our admin views would then be rewritten to do all of their permission tests through this swappable module, rather than hard-coding the permission mechanism as they do now.

It may make sense for me to do some of this work as part of implementing collections - that way I can ensure that the collection permission logic isn't too tightly coupled to the image/document code. Need to ponder that some more!

**Comment by scaryclam** [comment]
I've got something working right now that attempts to be as unintrusive as possible:
https://github.com/tangentlabs/wagtail/compare/master...tangentlabs:feature/remove_reliance_on_django_permissions?expand=1

The idea is to allow the permissions test to be overridden with a setting. Views arn't too much of a big deal IMO, as users can always swap out wagtails urls for their own version. If you were to keep all permissions checking code in one place, then it'll be quite simple to allow a swappable permissions mechanism.

If you'd be happier I work towards making a permissions module I'd be happy to start going down that route.

**Comment by gasman** [comment]
I think a permissions module is the way to go, yep. I suspect that swapping out the logic of the `wagtailadmin.utils` decorators isn't going to be sufficient, because there are permission tests throughout Wagtail that don't go through those decorators, such as the logic for checking whether to show a particular menu item:

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtaildocs/wagtail_hooks.py#L25-L26

- and also views where the permission is determined on a per-instance basis, such as:

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtaildocs/views/documents.py#L109-L110

As it happens, the permission logic I've been working on today for the Collections feature is heading some way down this path - 56c1a6246db89fbd5586e6b6518766d557dc0477, f83271de17e9bb7fc2a68ace57da13ae469dc44d. You'll see I've added a `wagtaildocs.permissions` module that performs all the permission testing relating to documents - either using standard Django `user.has_perm` tests, or a new custom permission model, depending on the `is_using_collections` flag. I'll probably refactor this some more so that those two cases are handled by two separate permission-tester objects - the next job would then be to generalise that pattern to work with other objects besides documents. (For the Collections feature I'll need to do that for images in the first instance - hopefully after that it'll be clearer how to deal with the rest of the models.)

**Comment by gasman** [comment]
Please see https://github.com/wagtail/wagtail/issues/2907#issuecomment-288702336 for my current thoughts on customisable permission models. Given the complexity of defining a permission policy that does everything Wagtail requires, I now think that the most effective way to make Wagtail's permission system "disappear" is to give all users blanket permissions within the permission system (either as superusers or members of a suitably privileged group), rather than to override it.
