### ISSUE TITLE
Add some example images to image filters reference

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#1685]
Here's the image filters reference as it is today: http://docs.wagtail.io/en/v1.0/topics/images/using_in_templates.html

I think it would really help people understand how these filters work by adding some example images that describe how cropping/resizing is performed with each filter.

This will be especially useful for describing the "fill" operation and how it works with focal points, "closeness", etc

For example: https://github.com/thumbor/thumbor/wiki/Crop-and-resize-algorithms

**Comment by lb-** [comment]
@kaedroho thoughts on these?

I have done my best to follow along with the example, using raw images of the same dimensions and showing how they would be cropped or resized. The green outlines maybe should be recoloured to something nicer, let me know if this is on the right track.

Maybe for the max/min I should use a lighter outline, because these represent the provided dimensions. For the fill I should not use a dashed line at all to differentiate between the min/max, showing that this will actually crop the image.

* Image CC0 source: https://pixabay.com/en/white-wagtail-bird-branch-songbird-2786117/
* Updated Docs Link: http://docs.wagtail.io/en/v1.13.1/topics/images.html

### `max-1000x500` with original 1000x2000 

![wagtail-image-template-examples-max](https://user-images.githubusercontent.com/1396140/33651008-3b0b10be-da9f-11e7-9bed-35cf3ec818d1.png)

### `min-500x200` with original 2000x2000 

![wagtail-image-template-examples-min](https://user-images.githubusercontent.com/1396140/33651009-3b6a44ee-da9f-11e7-92f2-f4b6ca58d8bd.png)

### `fill-200x200`
![wagtail-image-template-examples-fill](https://user-images.githubusercontent.com/1396140/33651235-0d3653f0-daa0-11e7-95ad-29144af53da6.png)

### `fill-200x200-c75` with focal shown
![wagtail-image-template-examples-fill-with-focal-close](https://user-images.githubusercontent.com/1396140/33651233-0cbac4e2-daa0-11e7-9e44-590750059fd0.png)

### `fill-200x200` with focal shown
![wagtail-image-template-examples-fill-with-focal](https://user-images.githubusercontent.com/1396140/33651234-0cfda33e-daa0-11e7-85ad-26df13da1543.png)

**Comment by kaedroho** [comment]
@lb- These images are excellent!

I'm not too opinionated with regards to coloring/style of the lines, maybe someone in @wagtail/ux-design or @wagtail/documentation might have some thoughts on that.

The only thing I've spotted that isn't covered is the behaviour when the focal point is off centre. The cropping algorithm performs a google maps style zoom in towards the focal point rather than centering on it so the position of the focal point is the same in the final image.

**Comment by lb-** [comment]
Updates with some refinements, including more off-center example for focal point and lines to show center of image.

### `max-1000x500` with original 1000x2000 

![wagtail-image-filter-examples-max](https://user-images.githubusercontent.com/1396140/33761376-bcd3947c-dc43-11e7-8f68-cfde078e7c99.png)

### `min-500x200` with original 2000x2000 

![wagtail-image-filter-examples-min](https://user-images.githubusercontent.com/1396140/33761377-bd0b0740-dc43-11e7-968a-0f200439028d.png)

### `fill-200x200`

![wagtail-image-filter-examples-fill](https://user-images.githubusercontent.com/1396140/33761374-bc9bc61e-dc43-11e7-9074-c65531bb0197.png)

### `fill-200x200` with off center focal shown

![wagtail-image-filter-examples-fill-focal](https://user-images.githubusercontent.com/1396140/33761372-bbca4c9c-dc43-11e7-9917-3165e4f1f037.png)

### `fill-200x200-c75` with off center focal shown

![wagtail-image-filter-examples-fill-focal-crop](https://user-images.githubusercontent.com/1396140/33761371-bb9257ba-dc43-11e7-8156-a246a5093c2c.png)

**Comment by kaedroho** [comment]
Thanks again @lb-!

When the focal point is off-centre, the crop rect will not centre on it. So in ``fill-200x200 with off center focal shown``, the red box should be moved left a little bit so the focal point in the final image is in the same position as it is in the source image.

**Comment by lb-** [comment]
@kaedroho like this?

![wagtail-image-filter-example-fill-200x200-with-focal](https://user-images.githubusercontent.com/1396140/33766057-c3d53f06-dc56-11e7-8400-10ea2fb078de.png)


Updated files location:
https://drive.google.com/drive/folders/1SOrsol5_ahFYnY-v6B4TjgSQMaEgnOk7?usp=sharing

**Comment by kaedroho** [comment]
@lb- Yep, that looks correct!

**Comment by lb-** [comment]
Updated files location: https://drive.google.com/drive/folders/1WGYv8JJgS7SVb1FEMzExzozcpdx36ftq?usp=sharing
