### ISSUE TITLE
Page chooser doesn't scope to site

### ISSUE THREAD

**Issue by lee-kagiso** [wagtail/wagtail#1700]
It allows one to pick a page from another site.

**Comment by gasman** [comment]
In many cases, this *is* what we want - if the sites belong to the same organisation (e.g. different departments of a university, or a charity running several campaigns) then editors should be able to create links between them. However, I can see that for a wordpress.com-style multi-user setup, it's not appropriate to be able to casually browse around other people's sites in the admin backend...

This could be solved by extending the permission model - in addition to 'can add pages', 'can edit pages', we would have 'can browse' (or 'can select') - that way the default behaviour would be to allow editors to browse everything, but more restrictive behaviour could be set up as required.

I don't think we'd want to link this to sites - sites only really exist to match locations in the tree to hostnames, and it's possible that developers will want to set up multiple 'private' areas under a single hostname, e.g. example.com/blogs/matthew rather than matthew.example.com.

**Comment by davecranwell** [comment]
To address a latent question: Wagtail does not currently support multi-tenancy at all. It's been written on the assumption that all the users of the system are somehow connected, at some level, with all the content that is entered into Wagtail.

**Comment by lee-kagiso** [comment]
Oops. We have 16 500 pages across 2 sites only related by industry and holding company, and a third site is on its way. We saw the ability to have multiple sites and immediately assumed it mean multi-tenant, and thought all the issues were due to Wagtail being a new CMS

We use a regex and a template context processor to work out which site it is from request.site, along with some strategic if statements to make things happen. Not perfect but it works

**Comment by tomdyson** [comment]
I think the situation is more nuanced than @davecranwell suggests. The forthcoming Collections feature and the minor extensions to the permissions model referenced by @gasman above combine with Wagtail's strong support for multiple sites to provide something very close to multi-tenancy.

**Comment by lee-kagiso** [comment]
@tomdyson another feature which would be really useful is extending the Site model to have an hstore or json field for settings, so we can get a give site's specific config is easily available from `request.site`. 

Currently we are putting everything in the settings file and having to use if statements to get the correct email template, and social tokens etc.

**Comment by tomdyson** [comment]
@lee-kagiso have you tried https://wagtailsettings.readthedocs.org/en/latest/ ? It supports site-specific settings. We may move this into wagtail.contrib in a future release.

**Comment by colinfrankb** [comment]
a possible workaround to your idea @lee-kagiso, looking at the how wagtail attaches the `site` attribute to the request using a middleware specifically `SiteMiddleware`, another middleware could be created to augment the Site instance after its attached with that configuration attribute

**Comment by lee-kagiso** [comment]
This is definitely what we need! Never knew of its existence...

**Comment by colinfrankb** [comment]
Yeah, looks very interesting

**Comment by gasman** [comment]
Closing this to reduce duplication of tickets - I'm now treating #2463 as the "master" issue for tracking multi-tenancy support (even if much of the work is happening on other PRs).
