### ISSUE TITLE
Allow ImageChooserBlock to support adding multiple images at once

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#1717]
For instance, this code is currently being used:

``` python
('image_slider', blocks.ListBlock(ImageChooserBlock(), icon='image', label='Slider')),
```

That requires the user to add images one-by-one to create an image slider. Ideally the user could open the image chooser once and select any number of images from there. The same concept could be applied to page relationships.

**Comment by alexgleason** [comment]
In case it may inspire some thinking, here is how Craft's [assets](http://buildwithcraft.com/docs/assets) are handled.

![screenshot from 2015-09-23 11 22 14](https://cloud.githubusercontent.com/assets/3639540/10052071/8fa85404-61ea-11e5-97cb-c717b07db57d.png)

Clicking the "Add" button makes this modal appear where the user can select multiple files at once.

![screenshot from 2015-09-23 11 22 46](https://cloud.githubusercontent.com/assets/3639540/10052072/8faa6d52-61ea-11e5-9bf7-136458beeb77.png)

Bonus: You can even double click the images to edit their global properties right there. You can also click and drag them to change their positions. Relationships between models are handled the exact same way (as seen in the bottom block of this screenshot).

![screenshot from 2015-09-23 11 58 45](https://cloud.githubusercontent.com/assets/3639540/10052073/8fb85c82-61ea-11e5-9b8e-e7874dc8c327.png)

**Comment by SalahAdDin** [comment]
:+1:

**Comment by benebun** [comment]
FYI there is also [this (unanswered) Stackoverflow question](http://stackoverflow.com/questions/42380241/extending-imagechooserpanel-to-allow-multiple-selections-and-uploads) in case this can be better/also tackled there.

**Comment by patta42** [comment]
I have asked the Stackoverflow question mentioned above and more or less solved the issue for,my specific problem. However, there are two problems:

- I do not remember completely what I have changed since it was a lot of trial and error
- It would benefit a lot from hierarchical collections, and [#3407](https://github.com/wagtail/wagtail/pull/3407url) looks pretty promising and nearly finished, but I don't think my solution works out of the box with this.

I am not very familiar with github and don't know if I should copy the code here. 

Anyway, here is what I remember. The code was mostly copied from wagtail and slightly modified, but I do not remember the corresponding sources., :

1. I have created an edit handler `InlineImagePanel`, which uses the (self-written) `BaseInlineImagePanel` class in its `bind_to_model` method.
2. For `BaseInlineImagePanel` (derived from `BaseInlinePanel`) I specified my own JS and HTML templates
3. The js template is the same as the js template in `wagtailadmin/templates/wagtailadmin/edit_handlers/inline_panel.js`, but it uses the js object `InlineImagePanel` instead.
4. The html template is the same as `wagtailadmin/templates/wagtailadmin/edit_handlers/inline_panel.html`, but additionally adds  CSS for the modal (`static 'wagtailimages/css/add-multiple.css`) and some more CSS for the selection of multiple images (only a simple rule for highlighting selected 
images)
5. I have added a hook to `insert_editor_js` to load the js file that implements js object `InlineImagePanel`. Furthermore, I add an URL to `window.chooserUrls.inlineImageChooser`.
6. The js file loaded in 5. first defines the function `buildExpandingImageFormset` (`wagtailadmin/static_src/wagtailadmin/js/expanding_formset.js`), Differences are the original value of the click event is saved in `addButton.addElement` and the click event is changed to open the modal dialog. The URL parameter has been set to `window.chooserUrls.inlineImageChooser` and the `imageChosen` parameter to loop over a set of selected images instead of only one
7. Then the js file loaded in 5. defines `InlineImagePanel`, which is the same as `InlinePanel`, but calls the previously defined function `buildExpandingImageFormset`
8. The URL mentioned in 5 points to an additional view copied from ImageChooser (I guess). The major difference is, again, that it uses different templates. The HTML template is from the multi-upload of wagtail, the js template, but adds a button 'Add selected or uploaded images'. The corresponding js template inserts code that, instead of adding an image when clicked, stores the image id in a global variable `window.multichooser.selected_ids`. When clicking the 'Add selected or uploaded images' button, the selected ids are passed as GET parameters to a view which returns the JSON information of the selected images, which are processed by ``imageChosen` mentioned in 6.

Hope this helps a bit.

I would be happy to publish the code, but I am not sure how to do this. The code is related to one of my apps with some additional static files located in the static files folder. I don't know how to add static files to a single app so that they are recognized by django, otherwise it might be worth to upload the code simply as a (alpha-versioned) app.
 `

**Comment by thibaudcolas** [comment]
FYI for people still interested in this, we’re considering bringing this in as part of the [Page editor 2022](https://github.com/wagtail/wagtail/discussions/7739) project, as part of general chooser improvements. Follow this discussion thread for upcoming updates / requests for feedback about choosers.

**Comment by SalahAdDin** [comment]
> Is this issue still relevant? I am working on an image gallery and sometimes users add many images to a gallery, adding 20 images one by one is tedious and not an option.
> 
> Was this issue handled anywhere else?

someone was working on this about five years ago, it is not finished yet.

**Comment by thibaudcolas** [comment]
I believe this has been addressed with the addition of a [MultipleChooserPanel](https://docs.wagtail.org/en/stable/reference/pages/panels.html#multiple-chooser-panel), implemented by @gasman in [February 2023 / Wagtail 4.2](https://docs.wagtail.org/en/stable/releases/4.2.html#multiple-chooser-panel), thanks to a sponsorship from [YouGov](https://yougov.com/) :)

I’ll close this now, if there are specific aspects that need further work please open a new issue / issues.

**Comment by gasman** [comment]
MultipleChooserPanel isn't usable within a StreamField, so I think this is still relevant.

**Comment by thibaudcolas** [comment]
@gasman we have a more specific issue for StreamField which I believe covers everything that’s here? #11318

**Comment by gasman** [comment]
@thibaudcolas Fair point! Will close this one as a duplicate then.
