### ISSUE TITLE
Provide usage figures for pages too

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#1722]
As a content manager I'd like to know how often my page is linked to from other pages, so I have an idea of the ramifications of unpublishing or deleting it.

Interface-wise I'd expect this to work the same as the document and image stats. As with images, we wouldn't be able to search the codebase for direct uses of the page (e.g `{% slugurl %}`) but we should be able to find pages linking to it in the database which is better than nothing.

Adding this to the interface has some design issues as there is little available space for the indicator.

**Comment by laymonage** [comment]
Thanks for the request! I know it's been quite a while since this issue was created, but I think now is a great time to implement this. Now that we have the `ReferenceIndex` model, we should be able to make use of it to show the usage information efficiently.

> Adding this to the interface has some design issues as there is little available space for the indicator.

The design issue has been solved now that we have the side panels in the editor, so the usage summary can be shown on the side panel just like we have for snippets:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/6379424/216374683-35f929d0-52d4-4827-8bb6-17897d7d884f.png">

Clicking the "Used x times" link would then take you to the usage view, just like with snippets:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/6379424/216374882-e8c0a48b-95c6-4777-b407-28b7b3ca44cf.png">

> As a content manager I'd like to know how often my page is linked to from other pages, so I have an idea of the ramifications of unpublishing or deleting it.

I made another issue to add the usage summary to the unpublish/delete confirmation view: #10008.
