### ISSUE TITLE
Generic ModelChooserBlock for StreamField

### ISSUE THREAD

**Issue by LiamBrenner** [wagtail/wagtail#1806]
I'd like to propose a `ForeignBlock` or similar using `models.ForeignKey` as it's base for allowing integrations with other model clusters/models. It would most likely need to extend `blocks.ChooserBlock` and shouldn't be too difficult.

**Comment by gasman** [comment]
The current recommended way of doing this would be to register your target model as a snippet (http://docs.wagtail.io/en/v1.1/topics/snippets.html), and use [SnippetChooserBlock](http://docs.wagtail.io/en/v1.1/topics/streamfield.html#snippetchooserblock).

However, in future we intend to move towards adopting [wagtailmodeladmin](https://github.com/ababic/wagtailmodeladmin) so that we can support arbitrary models within Wagtail admin without them having to be registered as snippets - and a general 'ModelChooserBlock' would be an important part of that.

**Comment by timorieber** [comment]
+1

**Comment by pymarco** [comment]
+1

**Comment by Proper-Job** [comment]
I'm sorry if I missed it, but is there a way to select a ModelAdmin instance from within a StreamField now that wagtailmodeladmin has been released?

**Comment by gasman** [comment]
@Proper-Job Not currently, no.

**Comment by Proper-Job** [comment]
Ok, thanks.

**Comment by ababic** [comment]
I think the blocker to having a ModelAdmin-based chooser has been: ModelAdmin classes know about the model they represent, but there's no easy way to access a ModelAdmin class when provided with model. Without moving to a 'django-like' registration method, where the relationships between models and ModelAdmin classes are stored in a central/reference-able place, I don't see how we can circumvent this. But that has a tonne of other implications that need thinking through. That's maybe a discussion for the developers board though, rather than here.

**Comment by JoshBarr** [comment]
We at Springload have a generic ModelChooserField in the works, but it:

* Relies on the React ecosystem 
* Relies on a very basic REST API endpoint that does 'creative' things to serializers. 
* Has no tests (yet)
* Has no translations (yet)
* Has no docs (yet)

If anyone's interested in helping out with it, I'll publish the code.

**Comment by kaedroho** [comment]
That's similar to the idea I have with admin view sets (#2113). This would be a place for "view sets" to be registered within Wagtail admin. This would automatically set up URLs to those views, menu items, admin API, etc. A generic chooser block could be implemented using this.

I think the ModelAdmin class could quite easily be based on view sets (since view sets are very similar to WagtailRegisterable that model admin uses at the moment).

**Comment by ababic** [comment]
Hi guys. Just wanted to share a few ideas on this one:

1. I was thinking of making an update to the ModelAdmin class, so that when a Model class is registered, the ModelAdmin instance saves a reference to itself on the Model class by setting a `_modeladmim_instance` attribute on it. This could then be referenced by choosers and the like. 

2. I was looking for an alternative ManyToManyField widget initially, and came accross this: https://github.com/applegrew/django-select2, which looked like it might make for a simple alternative ChooserPanel in Wagtail,  with a bit of work.

3. You may already be aware if this, but for those that aren't, there's a third-party app that offers a chooser similar to that of SnippetChooserPanel:

- https://github.com/Naeka/wagtailmodelchooser

**Comment by m1kola** [comment]
Currently there are two ways to manage non-`Page` models in Wagtail:

* Using [Snippets](http://docs.wagtail.io/en/v1.13.1/topics/snippets.html)
* Using [Model Admin](http://docs.wagtail.io/en/v1.13.1/reference/contrib/modeladmin/index.html) (contrib module)

When you register your model as a snippet it allows you to edit objects through the `Admin -> Snippets -> Your snippet name` menu and use nice chooser UI in the editing interface.

However there are few cases when this behaviour doesn't work really well:

* When you need fairly complex admin UI (with filters, for example) and have the chooser UI. In this case, most likely you would decide to use Model Admin, but Model Admin doesn't allow you to use the chooser UI. There is a workaround: you can register your model as a snippet alongside with Model Admin UI. As a result you will have two places to edit snippet: one in the `Admin -> Snippets -> Your snippet name` and one in the Model Admin UI which is confusing. Generic model chooser should solve this issue.
* When you need to have the chooser UI for snippets that do not need editing (data imported from some API, for example).

Taking into account the last point, it seems to me that the generic model chooser **must not** rely on Model Admin. I think, it should be something like the existing `register_snippet` but without exposing editing UI.

**Comment by tmsndrs** [comment]
Referencing #2756

**Comment by thibaudcolas** [comment]
For anyone interested in this – there’s been discussion (and a lot of progress) on making Wagtail’s snippets functionality more generic, powerful, and customisable: #8609

**Comment by gasman** [comment]
[ChooserViewSet](https://docs.wagtail.org/en/stable/extending/generic_views.html#chooserviewset) is now the recommended approach for building choosers (including chooser blocks) where snippets aren't suitable.

**Comment by PresidentNick** [comment]
@gasman I tried to follow to ChooserViewSet documentation to add a chooser to a block, but when I got to the step where we define the chooser block in blocks.py I get a circular error import when importing the viewset into block.py

Do you have any advice or tips I can follow to troubleshoot this? I already tried using the model string for the model field in the chooser.

**Comment by PresidentNick** [comment]
Never mind, I resolved it by separating the viewset into a new viewsets.py file instead of in views.py!
