### ISSUE TITLE
Help text on Page class

### ISSUE THREAD

**Issue by rmartins90** [wagtail/wagtail#1875]
In add_subpage.html, on the right panel where at the moment is "Pages using {{ verbose_name }}" could be replaced by something like help_text attribute on Page class Meta. It could be used to give some instructions to the editors in the momento of page creation.

**Comment by davecranwell** [comment]
See: https://github.com/torchbox/wagtail/issues/699 and https://github.com/torchbox/wagtail/pull/1683 and https://github.com/torchbox/wagtail/issues/513

This featured existed until a couple of releases ago, where it was removed because the method of providing that help text wasn't supported by a newer version of Django. I'd definitely like to see it back but it seems we're waiting on #513

**Comment by SalahAdDin** [comment]
Me too :+1:

**Comment by tmsndrs** [comment]
**UI/UX tasks**
- [ ] Visual design for 'page' help text on the add page screen
- [ ] Discuss the possibility of showing help text on the edit page screen

**Comment by shayan-oanda** [comment]
Any update on this Wagtail team? A really helpful feature for different page types.

**Comment by loicteixeira** [comment]
Issue tagged with the `some-day` milestone are accepted as but not deemed a priority to work on. It usually mean that anybody can pick it up and start working on it. However here there are a few design decisions to be made in order to be consistent with the rest of the admin (especially given that the edit page header recently got a revamp). I'll share this issue with the core-team to see what can be done on the design side.

**Comment by thibaudcolas** [comment]
We discussed this in today’s core team meeting. It looks like there is an implementation of this that’s almost there in #5607.

**Comment by lb-** [comment]
Closing this as resolved for the next 3.0 release.

see https://github.com/wagtail/wagtail/pull/8164
which replaced https://github.com/wagtail/wagtail/pull/8065
which replaced https://github.com/wagtail/wagtail/pull/5607
