### ISSUE TITLE
Separate initial data from migrations

### ISSUE THREAD

**Issue by jordij** [wagtail/wagtail#1937]
We usually find the default **Welcome to your new Wagtail site!** default homepage a nuisance. While we agree that some initial data is needed (Site and default groups ok) we don't feel like a default homepage should be automatically populated.

Here at Springload we like the idea of having initial data separated from the migrations using fixtures. What do you guys think? :)

**Comment by timheap** [comment]
I agree with this, but I also see the value of creating a fully functioning site from the outset, to get new developers up and running quickly. Perhaps a migration/fixture can be created as part of the `wagtail start` project that creates default site and 'Welcome to your new Wagtail site!' page, retaining the current work flow for new projects, but allowing developers already familiar with Wagtail to set up their project in the way that works for them?

**Comment by alexgleason** [comment]
I've been burned a few times from flushing the database, migrating, then having -1 pages. Still not exactly sure why this happens sometimes.

**Comment by timheap** [comment]
If you flush the DB, as opposed to dropping the tables and recreating the database, this would explain your problems. The initial data is constructed as part of a migration, not a fixture. After flushing the DB, the migrations will not run again as they have already been run, and the initial data will not be recreated. If the initial data was installed as part of a fixture, this problem would be avoided, although fixtures come with their own issues.

**Comment by jordij** [comment]
Yes Tim, making it optional and/or as a part of the `wagtail start` would definitely work for us.

To give some more details, our deployment flow the first time looks like:
* Create db schema (`python manage.py migrate`)
* Load project's initial data (we use `loaddata`)

The initial data obviously contains an instance of the homepage that clashes with the one being created in `wagtailcore/migrations/0002_initial_data.py`

**Comment by gasman** [comment]
> While we agree that some initial data is needed (Site and default groups ok) we don't feel like a default homepage should be automatically populated.

A slight snag with that - we can't create a default Site record unless we have a homepage for it to point to...

To be clear, there are two distinct places in Wagtail where we create an initial homepage: the `Page` instance in `wagtailcore/migrations/0002_initial_data.py`, and the `HomePage` instance created by the `wagtail start` project template as a replacement for the wagtailcore one: https://github.com/torchbox/wagtail/blob/master/wagtail/project_template/home/migrations/0002_create_homepage.py

I think the project template deals with this as well as we can hope for - the HomePage model exists as part of the project codebase, so it's possible for a developer to expand that into their final all-singing-all-dancing homepage without ever replacing it.

The wagtailcore one *is* clunky, I'll readily admit - we needed it before we added the project template and `wagtail start` command so that a new user would get something nicer than a 404 page. Now that we have the project template, the only people going the "bare metal" route will be people integrating Wagtail into an existing Django site, and I think it's reasonable to expect them to set up their own page model and site record with minimal hand-holding. On that basis, we could sensibly ditch wagtailcore's initial page record. (Indeed, having it in place just makes our documentation more awkward... http://docs.wagtail.io/en/v1.2/getting_started/integrating_into_django.html#start-developing)

The big question would be how to get there from here without breaking backwards compatibility. If we retrospectively edit wagtailcore migration 0002 to not create a homepage record, then all existing projects that expect it to be there (i.e. anything based on the `wagtail start` template, which attempts to [find and delete that page by ID](https://github.com/torchbox/wagtail/blob/master/wagtail/project_template/home/migrations/0002_create_homepage.py#L15)) will fail. If we add a new migration in wagtailcore to delete the homepage record, we'll have to be very careful not to delete anybody's *real* homepage on upgrade...

**Comment by timheap** [comment]
My preference would be to break backwards compatibility and just empty the migration, so the default site and home page are not created. A fixture, django admin command, and/or python function can be added that recreates the old behaviour for people if they need it, something like `./manage.py createsite example.com home.HomePage`

How does everyone go about creating their initial site structure, or testing data? If people use fixtures vs. migrations vs. code will determine how to go forwards.

**Comment by akx** [comment]
:+1: for separating the initial content from the migrations.

How about just making the `wagtailcore/migrations/0002_initial_data` migration configurable via `django.conf.settings`, like... `WAGTAIL_NO_INITIAL_DATA = True`?

**Comment by mvdwaeter** [comment]
I'd also prefer if it were seperated.
In my case: to speed up creating an empty feature builder server, I recreate the database, run migrations with the settings (disabling migrations for all apps):

    class DisableMigrations(object):

    def __contains__(self, item):
        return True

    def __getitem__(self, item):
        return 'notmigrations'

    MIGRATION_MODULES = DisableMigrations()

and the start to load fixture data.
However, wagtail requires the project to run migrations for permissions/root page. 
I'd suggest adding the creation of permissions and minimal setup into a management command:

    $ python manage.py wagtail_init

**Comment by gasman** [comment]
Closing as wontfix, as per the discussion on #2112. The TLDR version:

* There is some perceived ugliness in the wagtailcore / project_template migrations that we'd like to get rid of
* The proposed fix is to add a "disable the ugliness" setting which can only be employed by power users who properly understand the nature of the ugliness
* This fix doesn't eliminate the ugliness from the codebase, or from the developer experience of "non-power" users - it just adds another moving part on top of it
* There doesn't seem to be a way to actually eliminate the ugliness without breaking things.

If this last point changes, I'll be very happy to revisit this :-)
