### ISSUE TITLE
Do StreamFields need a StreamFieldPanel?

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#1939]
Is there a technical reason for StreamField needing its own panel type in order to function properly? I have a hunch it's possible it could work with a FieldPanel. But even if it can't, it should probably error out if you try to use a FieldPanel on a StreamField.

**Comment by gasman** [comment]
Good point! I could have sworn we'd already eliminated this, but I'm probably thinking of RichTextFieldPanel...

Looking at https://github.com/torchbox/wagtail/blob/c025e1d3e5b0332a0aef66b2721d96459591dd35/wagtail/wagtailadmin/edit_handlers.py#L741-L760 there are a couple of details specific to streams/blocks (namely html_declarations, and the convention of StreamField rendering its own error messages rather than leaving that up to the form furniture) that would be hard to shift elsewhere.

One possibility is to take advantage of the `StreamField.get_panel()` method - this is a way of saying "give me the most appropriate panel type for this field", and is currently used in fairly obscure circumstances when a panel definition has been omitted on an inline model or snippet. (Digging into the code now, though, it seems a bit confused about whether `get_panel` is the responsibility of the model field or the form field, and I suspect it's entirely redundant on RichTextField now, given that RichTextField works with a plain FieldPanel. That's going to need some untangling...) Since there's no valid reason to use a plain FieldPanel when a more specific panel type exists, we could reasonably have FieldPanel check for the presence of a `get_panel` method on the field, and defer to that if it exists. (With a bit of logic to stop it going round in circles, because the result of get_panel will probably be a FieldPanel subclass itself...)

A rather deep change, then, but probably a worthwhile one!

**Comment by zerolab** [comment]
The anwer is "no" as of 3.0rc1 - [release notes](https://docs.wagtail.org/en/latest/releases/3.0.html#removal-of-special-purpose-field-panel-types)
Specifically #7684
