### ISSUE TITLE
Combine documents and images in codebase

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2035]
I think we can get away with having a wagtailassets package instead of separate documents and images. They're so similar, the code shared between them is nearly the same, and when it isn't it's sometimes undesirable (#2034)

Here's an example of how the assets field type configuration looks in Craft:

![screenshot from 2015-12-14 15 55 02](https://cloud.githubusercontent.com/assets/3639540/11795210/17d4d822-a27b-11e5-9a7b-188b4e773cea.png)

**Comment by gasman** [comment]
You're right to note that there's duplication between wagtailimages and wagtaildocs that we really ought to eliminate, but I think that will be best done by pulling those common patterns (things like permission checking, chooser modals, and adding the model to the search page and dashboard) out into a reusable low-level module, rather than combining them into one app. This is something that wagtailmodeladmin (along the various other admin module proposals) is working towards.

**Comment by gasman** [comment]
Efforts to refactor these modules to reduce the duplication are now under way, e.g. in #2113.
