### ISSUE TITLE
Rich text fields should show "invisible" characters.

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#2188]
One of the banes of any rich text entry system is having to tidy your copy due to the things you can't see within it, like that final, blank paragraph you've mistakenly included with your copy-pasta content, or the fact that each of the paragraphs are in fact one giant paragraph with `br` scattered throughout.

Knowing you've ended with an extraneous paragraph _before_ previewing it and discovering the problem, will reduce the frustration of the editing experience.

**Comment by nkuttler** [comment]
Personally I'd love to simply be able to see the HTML markup inside the editor window. I'm not sure how hallo.js works internally, but I've seen many wysiwyg editors leave empty tag pairs in the markup.
Showing such things through visual cues sounds more user friendly, but I'm not too sure if a person who doesn't know the problem on a markup level would understand them anyway?

**Comment by ghostwords** [comment]
Related, I think: #741

**Comment by thibaudcolas** [comment]
I'm going to close this with the new Draftail editor soon to replace Hallo. Although the idea here would still apply, it's way less useful:

- There is no way to have empty paragraphs (or any form of empty tags) – unless people leave blank lines in the editor of course, which is perfectly valid.
- I don't know of any word processor mistakenly using `br`s for line breaks. If that happens it's intentional, and I don't think it's worth addressing.
- The preview works much better (and faster) now than two years ago.
