### ISSUE TITLE
InlinePanel Bulk Chooser

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#2203]
This repeats the call in #1717, except I don't see a reason this should be limited to ImageChooserBlocks. I'm also not calling for changes to the panel UI, which would be more of an undertaking, rather a streamlining of what we already have.

One pattern we regularly repeat in our sites is to wrap a ChooserPanel, with an InlinePanel.

Sometimes it's a SnippetChooserPanel, pointing to a "Category" snippet, in effect replicating free tagging except where there is essentially less freedom to make mistakes. Or perhaps it's an ImageChooserPanel, used to generate an image gallery.

Using an InlinePanel in these situations is quite clumsy:
1. Click the plus at the top of the InlinePanel and the panel opens. 
2. Click the "Choose thing" button, the modal opens, you choose the desired item.
3. To add the next, click the "Add thing" button
4. Click "Choose thing" _again_, again the modal opens, again the item is chosen
   ... repeat

In both scenarios, the user probably already knows _all_ the things they plan to add, before they even get to step 1. Even if they don't, they certainly shouldn't need to open 10 modals one after the other, to choose 10 things.

What would make more sense, is an interface where instead of a blank Panel appearing when you click in step 1, you are instead immediately presented with a modal in which you can choose multiple items at once, by adding a checkmark to every item in a list. Paginating through results in the modal would remember your item choices in previous pages. Having finally chosen everything, the modal would close and a panel for each of the items would be generated at once.

**Comment by benebun** [comment]
We are also running into especially with image galleries like in #1717.

The case outlined above is actual a best case scenario. More likely, the desired item is not reachable in the modal on the first page without a text search, a click on a tag or collection, or by browsing the pages, which then results in at minimum four steps _per item_:

1. Click plus to add a new panel
2. Click "Choose thing"
3. In the modal: use text search, click tag/collection, browse
4. Select thing

When adding 20+ images this is a bit tedious :)

Is anybody going to be working on this anytime soon? We haven't modified the CMS yet so not sure if this is the best issue for our first pull request…

**Comment by lb-** [comment]
Similar to - https://github.com/wagtail/wagtail/issues/1717 (called out in the description but doesn't seem to be linked)

**Comment by gasman** [comment]
I'm working on this with a target of getting it into Wagtail 4.2.

The proposed developer / user journey:

* A child model is set up in the same way as for InlinePanel (with a ParentalKey pointing back to the page or other ClusterableModel)
* The developer imports `from wagtail.admin.panels import MultipleChooserPanel` and uses that in the panel definition in place of InlinePanel - this follows the same API as InlinePanel
* The rendering for MultipleChooserPanel is visually the same as InlinePanel, but rather than the "Add new" button inserting a new empty child form, it opens up a chooser modal, corresponding to the first (and typically only) chooser widget in the child form definition.
* The chooser modal is passed an additional `multiple=true` URL parameter to enable multiple selection - in this mode a checkbox is displayed against each item in the list, a button at the bottom of the list allows confirming the selection, and the result is returned from the modal as a list of items.
* Back on the calling page, one child form for each item in the returned list is added to the MultipleChooserPanel, with the chooser widget populated with that item, and all other fields (if any) remaining blank.
* The resulting child forms can be reordered and deleted individually just like a standard InlinePanel, and the "Add new" button can be clicked again to open the modal and choose further items. (In this case MultipleChooserPanel will not enforce uniqueness on the chosen items - it will be possible to insert several copies of the same item. However, as with a standard InlinePanel the developer can set a uniqueness constraint so that this fails validation when saving.)

**Comment by gasman** [comment]
Sub-tasks:

- [ ] Build a mechanism that lets us access the Javascript API for a chooser widget definition from within the InlinePanel JS code
- [ ] Refactor the chooser widget JS API to provide an endpoint for opening the chooser modal (and passing it the `multiple=true` parameter) and receiving the result, without it being tied to a single chooser widget instance
- [ ] Modify the base chooser modal viewset to recognise the `multiple=true` parameter and return a list rather than a single item
- [ ] Update client-side code for chooser modals to add checkboxes and confirm button when `multiple=true` is enabled
- [ ] Create MultipleChooserPanel as a subclass of InlinePanel, with the "add" button swapped out for a new implementation that opens the chooser and creates populated child forms from the results
- [ ] Write documentation

**Comment by lb-** [comment]
I'd like to see how this can tie in with the Stimulus adoption for InlinePanel widgets. I think Stimulus will give us some nice options on how to connect to the JS behaviour.

See also
- https://github.com/wagtail/wagtail/issues/7915 (moving away from inline JS)
- https://github.com/wagtail/wagtail/issues/9105

Not sure how we should co-ordinate this - I had planned on doing the InlinePanel migration a bit later in the Outreachy project but maybe we should move it forward.

**Comment by gasman** [comment]
On "Build a mechanism that lets us access the Javascript API for a chooser widget definition from within the InlinePanel JS code":

There are two points where MultipleChooserPanel will need to talk to the chooser widget JS API:

* triggering the modal
* populating each widget with the data chosen

Within an InlinePanel, fields are rendered using the standard Django `Widget.render` method, which in the case of a chooser, inserts an inline `<script>new FooChooser(...);</script>` element alongside the HTML to initialise it. The resulting `FooChooser` instance _would_ be the API we want, except that:

* the return value of `new FooChooser(...)` is immediately thrown away, meaning that it's only accessible within the event handlers that it sets up itself - there's currently no 'official' way for external code to get hold of it
* even if we could access it, that wouldn't help for the initial empty state, where we want to open the modal at a moment where no `FooChooser` instances exist on the page.

However, chooser widgets do give us another route for acquiring those instances - the Telepath adapter. Currently these are only used for StreamField, but there's no reason why we can't use them here too (and any baby steps towards breaking down the wall between 'the StreamField way of doing things' and 'the regular Django form way' can only be a good thing). MultipleChooserPanel's Python-side code can pluck out the chooser widget from the form definition and telepath-pack it; the unpacked version on the JS side will be [the factory object](https://github.com/wagtail/wagtail/blob/main/client/src/components/ChooserWidget/index.js#L144-L161), which currently has the single purpose of spawning new FooChooser instances via its `render` method. I propose adding new methods to this: one for triggering the modal (independently of any individual chooser instance), and another for retrieving the chooser instance for a given HTML ID.

**Comment by gasman** [comment]
Current progress - the 'Add' button on MultipleChooserPanel is able to open the modal, with a `multiple=true` URL parameter to activate multiple selection, and the chosen items are returned to the calling page. Still to do: inserting the child forms and populating them with the chosen items.

![multiple-chooser-panel-1](https://user-images.githubusercontent.com/85097/205092652-180cff25-52c8-4559-903e-bc9efc16d101.gif)

So far I've been developing this against the wagtail-generic-chooser package, as the client sponsoring this needs it delivered before the 4.2 release date. This does mean the work done so far will need some adapting before it can land in Wagtail core (e.g. wagtail.admin.views.generic.chooser uses our tables UI framework but wagtail-generic-chooser doesn't) - but it still serves as a useful prototype for the new APIs required.

Current code can be found in:

https://github.com/gasman/wagtail-generic-chooser/tree/feature/chooser-factory-api - wagtail-generic-chooser with `openModal` method added to the chooser widget factory, and multiple choice support added to the modal
https://github.com/gasman/bakerydemo/tree/feature/multiple-chooser-panel - bakerydemo with MultipleChooserPanel implemented as a customisation of InlinePanel

The next step will require some refactoring of the InlinePanel JS (started in #9736) to expose an "add form" API endpoint - I'll create a new add-on package for the MultipleChooserPanel code, so that I can copy the InlinePanel JS into that package and have an independent instance of the JS tooling to work with. (Hopefully, this package will become immediately obsolete when this feature is shipped as part of Wagtail 4.2 :-) )

**Comment by gasman** [comment]
The prototype implementation (working under Wagtail 4.1 with wagtail-generic-choosers) is now released as a package: https://github.com/wagtail/wagtail-multiple-chooser-panel/

This depends on some new functionality in wagtail-generic-chooser (https://github.com/wagtail/wagtail-generic-chooser/pull/64) now released as v0.5: support for multiple choice in the modal (via a `multiple=true` URL parameter) and some new methods in the JS chooser widget API:

`ChooserWidgetFactory.openModal` - open the modal for the chooser, independently of any chooser instance, and trigger a callback with the chosen values
`ChooserWidgetFactory.getById` - retrieve the ChooserWidget instance for a previously-initialised widget with the given ID
`ChooserWidget.setStateFromModalData` - like `setState`, but accepts the JSON packet as returned from the modal

This functionality will need to be ported to [Wagtail's own generic chooser implementation](https://docs.wagtail.org/en/stable/extending/generic_views.html#chooserviewset), but I don't foresee any difficulties there.

The package also contains a bundled copy of the refactored `ExpandingFormset` and `InlinePanel` implementations from #9736 and #9750 - these allow us to subclass InlinePanel with our new MultipleChooserPanel implementation, and provide the all-important `addForm` API method.

**Comment by gasman** [comment]
Completed in #9886.
