### ISSUE TITLE
Ability to subclass `StructValue` to attach custom properties to StructBlocks

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#2204]
As proposed in https://github.com/torchbox/wagtail/pull/2187#issuecomment-179790713 - add a new `Meta` setting to StructBlock to specify a 'value' class to use in place of `StructValue`. This would mean that StructBlock values are not limited to dictionary-like behaviour, but can have arbitrary calculated properties too.

(The same trick would presumably work on StreamBlock/StreamValue too, although the usefulness of that is less clear...)

Probably a very minimal code change, but would warrant a decent-sized example in the documentation.

**Comment by lb-** [comment]
@gasman I will see if I can get to this one, seems to be a pretty useful feature.

Am I interpreting this right?

Add option to Meta, something like `value_class = StructValue` - I can't think of a better name either :) 

https://github.com/wagtail/wagtail/blob/8aa8ddcde986eee80e62ba6f185071e24669aeea/wagtail/core/blocks/struct_block.py#L178-L185

Then ensure that all usage of `StructValue` would  use the value from meta instead of directly calling the method. Check tests for the normal case plus also add for customised StructValue case.

Then, documentation that explains how this could be used (as per your reference comment):

```

class QuickLinkValue(StructValue):
    @property
    def url(self):
        if self.get('external_url'):
            return self['external_url']
        else:
            return self['page'].url

class QuickLinkBlock(StructBlock):
    page = PageChooserBlock(label=_("page"), required=False)
    external_url = URLBlock(label=_("external URL"), required=False)
    text = CharBlock(label=_("link text"), required=True)

    class Meta:
        value_class = QuickLinkValue

```

This can be used in your template as such:

```
<ul>
    {% for link in page.quick_links %}
      <li><a href="{{ link.value.url }}">{{ link.value.text }}></a></li>
    {% endfor %}
</ul>
```

I would also need to add documentation for an example that does not use the class of StructBlock but uses the tuple generation method.

Rough draft:
```
('quick_link', blocks.StructBlock([
    ('page', blocks.pageChooserBlock(required=False)),
    ('external_url', blocks.URLBlock(required=False)),
    ('text', blocks.CharBlock(required=True)),
], icon='link', value_class=QuickLinkValue))
```

**Comment by gasman** [comment]
@lb- Yep, that looks right to me!

**Comment by gasman** [comment]
Completed in #4117.

**Comment by c4collins** [comment]
Would it be possible to also have this work like this?
    
    class Meta:
        value_class = 'QuickLinkValue'

**Comment by gasman** [comment]
@c4collins Yes, that would be a fairly simple addition: in `_to_struct_value`, check whether `self.meta.value_class` is a string, and if so, call `django.utils.module_loading.import_string` on it before using it. (In this case, you'd have to give the full dotted path within the `value_class` string, but that's probably unavoidable.) Patches welcome!

**Comment by c4collins** [comment]
Done: https://github.com/wagtail/wagtail/pull/4797

I sometimes forget I can just poke around myself.
