### ISSUE TITLE
Display Changes for Draft

### ISSUE THREAD

**Issue by maxwhosevillage** [wagtail/wagtail#2242]
If a draft is submitted for moderation it is hard for the moderator to find out which parts of an item was changed or edited.
Therefore it could be helpful to have a chance to compare the old and the new version of a page. 

At the moment as a workaround I save the rendered html and use diff two see the changes. But it would be helpful to have a way for that in wagtail.
Maybe some more thinking is needed but still the function would help.

**Comment by JoshBarr** [comment]
I agree @maxwhosevillage, a visual diff would be a great addition to the CMS. I've prototyped one for working with revisions, but it would make sense to expand that to encompass changes between `draft` and `live` pages too. It's essentially the same thing. 

I'm interested in doing this quite apart from the rendered HTML, since my project involves using Wagtail over an API to a frontend.

**Comment by JoshBarr** [comment]
@kaedroho we briefly discussed the idea of fields/widgets providing a 'diff' or serial representation so that it is possible to compare changes between them. It needs some UI design, and we need to decide on the best approach. I had started this in #1946, but moving the discussion over here until we have a new PR for it.

**Comment by maxwhosevillage** [comment]
The revisions-feature is a first step in the right direction.
Now i can open 3 version in two windows and compare them.
It would be nice to have a view where i can see the changes in each revision.

**Comment by dprothero** [comment]
@JoshBarr have you done any work on this. We're thinking about implementing this ourselves, but it would be great to collaborate.

**Comment by almzenefits** [comment]
we are also curious about this feature - it will help our workflow tremendously.
@JoshBarr @dprothero

**Comment by phette23** [comment]
Just bringing up that we've had editors express dissatisfaction with moderation's preview of changes, too. For a page using streamfields, it appears the changes are just listed as a big plain text blob with no diff. Obviously that makes it near impossible to see small changes. It's not an easy problem but displaying some sort of diff showing changed blocks, new/removed blocks, etc. is ideal.

**Comment by gasman** [comment]
Hi @phette23 - please see #3368 which covers improving the representation of StreamFields in the comparison view. There's been some progress towards this recently in #3593, which should make it easier to match up blocks from one revision to another.

**Comment by gasman** [comment]
With #4933 I believe all points brought up in this issue are now complete.
