### ISSUE TITLE
Optimizing Images using a Postprocessor

### ISSUE THREAD

**Issue by toptalo** [wagtail/wagtail#2252]
I want to apply an external post processing program to uploaded images, like in easy-thumbnails

Example:

``` python
THUMBNAIL_OPTIMIZE_COMMAND = {
    'png': '/usr/bin/optipng {filename}',
    'gif': '/usr/bin/optipng {filename}',
    'jpeg': '/usr/bin/jpegoptim {filename}'
}
```

https://easy-thumbnails.readthedocs.org/en/2.1/ref/optimize/

is it real?

**Comment by toptalo** [comment]
Hello

**Comment by kaedroho** [comment]
@toptalo Sorry I must've missed this

This is something that is being worked on, initially we plan to use the optimisation feature that Pillow provides us (https://github.com/torchbox/Willow/pull/39) since this doesn't require any external dependencies.

That PR is just awaiting testing, if its results are comparable to ``jpegoptim``, we will use in in Wagtail. If not, we will implement support for ``jpegoptim``/``optipng`` instead.

**Comment by kaedroho** [comment]
Optimisation implemented for JPEG images in: https://github.com/wagtail/wagtail/pull/2959

**Comment by toptalo** [comment]
Cool, thanks!
