### ISSUE TITLE
Labels on 'Edit image' form need more horizontal space

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#2271]
See https://github.com/torchbox/wagtail/pull/2243#discussion_r53226298 - affects collections, but would similarly occur for any sufficiently long field name on a custom image model (such as 'Copyright').

**Comment by davecranwell** [comment]
Bear in mind: https://github.com/torchbox/wagtail/issues/1442 which is semi-duplicative.

To widen the label a little more would just put off the problem for another day. Alternative we could forcibly hyphenate it with `word-break: break-all` but that feels rather churlish. I think I've known from the start that the aesthetic might have to give way to the practical on this front.

Moving labels above fields seems like the most i18n-friendly solution. It would seem most sensible to do it globally, in fact: we don't know the width of any non-english translated strings, not just form labels. We wouldn't want to have to calculate it dynamically either. So anywhere where horizontally aligned fields exist, this is a problem either happening for many already, or about to happen, or happening for some but only at small breakpoints.

Does @heymonkeyriot has anything to add here?

**Comment by heymonkeyriot** [comment]
I agree with @davecranwell that moving the labels above the field would make the most sense. I've run in to trouble with label lengths without even particularly long words so I can imagine in German (or other languages where words can concat) it would be even worse.

As you say this feels similar to #1442 (and my duplicate of that at #2263) and I think would give a sense of consistency for the help texts then appearing underneath fields rather than to their right.

**Comment by ababic** [comment]
I'm really glad to hear there may finally be some movement on this soon. Since our first wagtail project, we've been using an override stylesheet to force labels to appear above fields and help text below. It makes everything feel so much more consistent. `FieldRowPanel`s really come into their own with the extra horizontal space made available. it's actually viable to have 3 or 4 (small) fields in a row together. Take this layout for example:

![Beer tasting notes for brewery website](http://i.imgur.com/TexbXSJ.png)

Or this one for an event, which also shows an alternative checkbox input style (it sure would be lovely to get rid of that colon from the end of the checkbox label) 

![Event panels with overrides](http://i.imgur.com/I4t6E0d.png)

For contrast, here's that same layout without the overrides in place:

![Event panels without overrides](http://imgur.com/JHDcXLY.png)

**Comment by tmsndrs** [comment]
@gasman can this be closed or does it still need work? Looks like you marked it as almost complete some time ago.

**Comment by halinh0507** [comment]
I think this issue has been fixed in the latest version. Can this issue be closed or is there anything we need to work on?

**Comment by gasman** [comment]
@halinh0507 Yep, looks like this was fixed in #4868. Thanks for prompting!
