### ISSUE TITLE
Extend WYSIWYG  with new buttons and customized behavior

### ISSUE THREAD

**Issue by sf-wind** [wagtail/wagtail#2277]
I have read through the previous issues related in WYSIWYG. I understand that it should only be used in simple formatting. However, it seems, currently the format only contains some simple formatting, and the font display is all black. 

I don't know whether it is possible. But I'd like to add some new buttons that would wrap some text with a class. Then in CSS, I can specify the color of the class. It would make the editor very easy to put in some colorful text. I don't intend to put arbitrary color, but some predefined color. 

I want to use bootstrap, and some classes like "success", "info", "warning", danger", or "text-warning", "text-danger", "text-info", "text-success" only wraps text with a class. Or, maybe wrap some text with "<code></code>". Since this text is in within a paragraph, it is not possible to use streamfield for this purpose. 

I think this is simple formatting, adhere to wagtail principle. 

Is there a way to do this? 

Thanks.

**Comment by didorothy** [comment]
I think that this could be done with a [hallo.js](http://hallojs.org/) plugin. If you look at [wagtail/wagtailadmin/static_src/wagtailadmin/js/hallo-plugins/hallo-wagtaillink.js](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/static_src/wagtailadmin/js/hallo-plugins/hallo-wagtaillink.js) as an example it would probably not be too difficult. Might require an addition of an admin link which can be added with a [wagtail_hook](http://docs.wagtail.io/en/v1.3.1/reference/hooks.html) and a corresponding view to allow you to specify the class name similar to how the hallo-wagtaillink.js pugin works.

Then to include your plugin you could override [wagtail/wagtailadmin/templates/wagtailadmin/pages/_editor_js.html](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/templates/wagtailadmin/pages/_editor_js.html) in your project's template folder to include your plugin at the right place.

I have recently done something similar, minus the additional plugin, to allow links that jump down the page to named anchors or IDs on a page with StreamField(s). Unfortunately, that code is not public at this time.

**Comment by tmsndrs** [comment]
You could achieve this with Streamfield. Create your custom block and put paragraph blocks either side of it. From what you've described it doesn't sound like semantically that this would all be in one paragraph tag. 

If you create an 'alerts' block you could include fields for the content and then a predetermined set of presentational rules defined as a separate field meaning presentation and content are separated in the database which keeps your content model cleaner.

**Comment by sf-wind** [comment]
@tmsndrs I don't think Streamfield can add classes to a "<span></span>" within a paragraph. Even if so, it breaks the normal human flow of writing content. 

Say, how to write the following piece of code?  (from getbootstrap.com)

<p>Individual form controls automatically receive some global styling. All textual <code>&lt;input&gt;</code>, <code>&lt;textarea&gt;</code>, and <code>&lt;select&gt;</code> elements with <code>.form-control</code> are set to <code>width: 100%;</code> by default. Wrap labels and controls in <code>.form-group</code> for optimum spacing.</p> 

It should have the following effects:

![image](https://cloud.githubusercontent.com/assets/4585741/13322502/91675eb6-db89-11e5-806f-f9433604258b.png)

How to do that using Streamfield?

**Comment by sf-wind** [comment]
@didorothy Thanks for your information. I think it is a bit more difficult than that. I hope to create a button. If a user clicks it, a dialog pops up with a number of selections. The user clicks one selection, the diaglog closes and the effect is shown up in the WYSIWYG. In the whole process, there is no need to have server access. But I don't know how to make it happen.

**Comment by didorothy** [comment]
@sf-wind I decided that I would build a repository that demonstrates how this could work. You can see it here: https://github.com/didorothy/wagtailhallosample 

I built and tested on Windows 10 with Anaconda Python 3.5. It should work from Linux as well with Python 3.4 or greater. Even if you don't decide to run it you should be able to see how the code works by looking at the files pointed out in the README.md. The code is not perfect as there are some potential difficulties with limiting the span. It works best when you highlight the text you want to put a span around before clicking the button (looks like a placeholder). Also there are not unit tests so you would probably want to create some. Finally, the icon is probably poor and you would need a custom icon for the button to add clarity.

It is probably also possible that you could get by without the server side code by encoding the dialog in the JavaScript of the plugin. That would take more time than I have to give but you can probably work that out if you really want to. You could look at the hallo.js code's link plugin for an example of how this might happen: https://github.com/bergie/hallo/blob/master/src/plugins/link.coffee

I think it would be good to mention that you can nest `StreamBlock`s and your nested stream block could contain blocks that could be spans with classes. I'm not sure how the Wagtail Admin interface would respond and I'm not sure that the editing interface would be the most convenient but it should be possible since you control how the `StreamField` renders by looping over the Blocks it contains and choosing the HTML tags to use based on the block type. 

Hopefully this is helpful.

**Comment by thibaudcolas** [comment]
I *think* Wagtail now has (documented) hooks for this, for Hallo and for the new Draftail editor. This should come with the 2.0 release. 

For Draftail in particular, simple inline formatting like described above can be achieved without writing client-side code. Once that release is out I'll make a demo repository for this.

**Comment by thibaudcolas** [comment]
Yep – there's now ample documentation on how to do this in the upcoming 2.0 release, over at http://docs.wagtail.io/en/latest/advanced_topics/customisation/page_editing_interface.html#rich-text-html.
