### ISSUE TITLE
Let admin fields span full width when there is no help text

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2305]
Would negate the need for: https://github.com/alexgleason/wagtailhavetheabilitytoactuallyseefieldsintheadmin

**Comment by alexgleason** [comment]
Alternatively, put help text in a different position for StreamField blocks. Such as below the label. IMO this is a better solution.

**Comment by JoshBarr** [comment]
Here's a proposal for how to handle help text in the editor view:

![editor-1](https://cloud.githubusercontent.com/assets/1715456/13505967/8264e17e-e1e0-11e5-86ad-04561a51b412.png)

**Comment by alexgleason** [comment]
Thanks Josh. I like it, but I think we still run into a problem when deeply nesting blocks.

I'm starting to take the position that this sort of content should have custom styles added to them. Here's an example of one I recently created:

![screenshot from 2016-03-03 13 32 36](https://cloud.githubusercontent.com/assets/3639540/13506612/eea76594-e14c-11e5-911e-ab15086f1596.png)

The whole thing (the dropdown and cards) is a structblock where the cards are a field within it. Like this:

```python
cards = blocks.StructBlock([
    ('style', blocks.ChoiceBlock(choices=[
        ('smallcard', 'Small card'),
        ('circlecard', 'Circle card'),
        ('squarecard', 'Square card')
    ])),
    ('cards', CardsBlock()),
])
```

I think taking the time to design deep fields like this in the admin could help mitigate the issue. But I'm still a bit bothered by the help text like that. Because in order to achieve this, it required me to inject this custom CSS into the admin:

```css
.sequence-member.blockname-card .struct-block .fields {
  width: 100%;
}
```

That means every time I create a block like this, I'll have to inject in CSS for it.

**Comment by davecranwell** [comment]
This issue is essentially a replica of at least two others, all concerned with layout of the page editor, with which I completely agree. As Wagtail's popularity grows, so do the numbers of users trying to do more with this interface, and not getting very far.

I think we need to have a proper conversation taking them all into consideration. I'll try and convene a meeting of minds.

Josh's design certainly looks the most rich and professional, but it needs extrapolating to the various layouts we have and I suspect it may still be a particular problem given the potentially infinite nesting of streamfields.

That isn't to say there's not a sweet spot in between, but the full-width label-above-input approach is certainly the most flexible, even if it's rather simple and has value given the nesting problem.

**Comment by alexgleason** [comment]
Edd and I have been working on [a simple admin CSS override](https://github.com/alexgleason/wagtailbettereditor/) to allow for deeply nested StreamFields. The screenshot doesn't do it justice but it's pretty cool. There's a couple of issues but I'll clean them up soon.

**Comment by alexgleason** [comment]
[Wagtail Atomic Admin](https://github.com/alexgleason/wagtailatomicadmin) is now a fork of wagtailadmin. I'd like it to be merged, but it changes quite a bit so I'm unsure what your opinions are. It's worth checking out; all you have to do is `pip install wagtailatomicadmin` then add it to your INSTALLED_APPS above wagtailadmin.

**Comment by tomdyson** [comment]
@alexgleason I've just tried Wagtail Atomic Admin. It's impressive! It's more usable but less attractive, IMO. Let's see if we can achieve the best of both worlds.

**Comment by alexgleason** [comment]
@tomdyson I've taken a utilitarian approach, inspired by [Craft CMS](https://craftcms.com/). Do you like the way their admin looks? It's very similar, but they have given more attention to details with subtle color hues and pixel perfect shadows and spacing.

**Comment by SalahAdDin** [comment]
@alexgleason Very interesting package.

**Comment by fabienheureux** [comment]
Hey, what is the status on this ? Any plan on implementing inside 
did try wagtailatomicadmin, but it is a bit buggy (will report bugs, being in a rush right now 🙂)
Thanks anyway for the work, it is pretty neat, less eye candy of course, but much more flexible than core wagtailadmin

**Comment by rgant** [comment]
I think there is too much focus on a _perfect_ redesign instead of just making simple quality of life changes to help things today.

I'm only nesting Blocks, not Fields, and StreamBlocks don't seem to have help_text so that isn't an issue. I found @alexgleason's  changes (thanks for getting me started) to be too dramatic, and I just added the following CSS to the editor:

```
li.sequence-member .struct-block .sequence-container {
    width: 83.33333333%;
}

li.sequence-member .sequence-member .struct-block .fields {
    width: 100%;
}
```

In wagtail it would involve the following changes:
```
diff --git a/wagtail/admin/static_src/wagtailadmin/scss/components/_streamfield.scss b/wagtail/admin/static_src/wagtailadmin/scss/components/_streamfield.scss
index 094fcdca0..e96cb271d 100644
--- a/wagtail/admin/static_src/wagtailadmin/scss/components/_streamfield.scss
+++ b/wagtail/admin/static_src/wagtailadmin/scss/components/_streamfield.scss
@@ -33,7 +33,7 @@ li.sequence-member {
     }
 
     .struct-block .sequence-container {
-        @include column(9);
+        @include column(10);
         padding-left: 0;
         padding-right: 0;
 
@@ -61,6 +61,7 @@ li.sequence-member {
 
         .sequence-member {
             border: 0;
+            width: 100%;
         }
 
         // sequences within sequences, such as a ListBlock within StructBlock
```

I'd be happy to submit a pull request if I thought it would be accepted.
