### ISSUE TITLE
Deleting the final element in a ListBlock or StreamBlock should delete the entire block

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2324]
In sequence blocks you can delete all the elements and be left with an empty box representing the ListBlock or StreamBlock. It should just delete the entire block when you remove the last element.

**Comment by timheap** [comment]
Only if there is a way of also disabling this behaviour. In one of our projects, we use a StreamBlock that has some default content, but more can be added by adding children. An empty StreamBlock in this case is a perfectly valid and useful thing in its own right, so automatically deleting it would be quite annoying.

Another case would be emptying the StreamBlock/ListBlock in order to update all of its content. You dont want to delete it, just empty it to start again. If it was deleted when it was emptied, this would be quite annoying, although not very difficult to add it back in again.

Perhaps a message along the lines of

> Looks like you've emptied this block. Do you want to `[remove it]`?

**Comment by alexgleason** [comment]
Can you give an example?

**Comment by timheap** [comment]
The [contact form on DigitalReady](http://digitalready.tas.gov.au/contact/). The form is a StreamBlock, within the page StreamField. That is the default form state. The name, email, business name, and location fields are hard coded to be present on all forms. Editors can add more form fields to the form by adding children to the forms StreamBlock, but the form StreamBlock being empty is a valid state as well.

**Comment by alexgleason** [comment]
Interesting. I wonder if you can make a template for your ListBlock subclass under maybe wagtailadmin/my_block.html and just do `{% extend "list_block.html" %}{% block class %}my-class{% endblock %}`

thus not using the `list` class and not triggering the js to delete your block.

still thinking about this. I'm not entirely sure it's valid for a listblock to serve as a placeholder like that, but I can't think of any other solution to the problem atm.

**Comment by timheap** [comment]
It suits our needs perfectly. There is nothing to say that a StreamBlock/ListBlock cant have header/footer content, and that is all the default form fields are. The other option would be to make it a StructBlock with a single child, which is the StreamBlock. The StreamBlock cant delete itself if it is part of a StructBlock, so this would solve the issue without requiring flags etc.

**Comment by gasman** [comment]
Logically an empty list block is a different thing from no list block at all (just as [1, 2, [], 4, 5] is not the same Python value as [1, 2, 4, 5]) so I think it makes sense for us to differentiate between the two cases, whatever the use-cases for that might be. Perhaps after we implement #2379 we could implement this "delete the whole block when the last item is deleted" behaviour just for sequences with min_length >= 1?

**Comment by timheap** [comment]
I think the behaviour should be opt-in, in the spirit of Python: explicit over implicit. Document the option clearly, but leave it up to developers to use it. Too much magic makes me grumpy :)

**Comment by alexgleason** [comment]
Okay, I'm still working this through in my head. I'm wondering, is there any reason why this contact form isn't fully configurable? Why are only some of the fields content managed? This seems like the opposite of "explicit over implicit" and potentially confusing to the client.

**Comment by timheap** [comment]
Because the four predefined fields have extra logic and validation behind them that are required to make the form work behind the scenes, and the data collected is the data they explicitly always want to collect. The optional extra fields are for when they think of more data they want to collect for a specific campaign or purpose.

**Comment by gasman** [comment]
Empty lists are logically different from the absence of a list, have valid use cases, and in the time since this was opened we haven't encountered any counterexamples where the opposite behaviour is more desirable - so closing this now.
