### ISSUE TITLE
Want ability to set placeholder text separately from label in fields

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2328]
Currently blocks contain only a `label` field, which renders to the field label _and_ placeholder text. Ideally I'd like to set the placeholder text separately.

For instance, say I have an email field. I'd want it to be:

label: `Email`
placeholder:  `you@example.com`

This helps guide the user on the sort of content they need to enter into the field.

**Comment by davecranwell** [comment]
That would require customising the widget of every field type, wouldn't it? Or do the latest Django versions make this easier now?

**Comment by alexgleason** [comment]
Since not all blocks have input boxes supporting placeholder text, I think it would have to be added on a per-block basis.

**Comment by heymonkeyriot** [comment]
+1 for this idea, having both the label and placeholder would make it much easier to communicate what the fields were for to the user (and would help with the conversations elsewhere about where to put help text etc.)

What are the implications of having to add this per-block?

**Comment by alexgleason** [comment]
>What are the implications of having to add this per-block?

Minimal; just adding a field and templating it. Would probably take 5 minutes to implement.

My only concern is backwards-compatibility. I haven't thought that through well enough yet and I don't want to break anyone's builds.

**Comment by mdunhem** [comment]
This could be fixed with a one line edit to the FieldBlock class and then all you need to do is supply a placeholder attribute when defining the field.
widget_attrs = {'id': prefix, 'placeholder': self.meta.placeholder or self.label}

**Comment by SalahAdDin** [comment]
This widget function i ask to wagtail team in other thread, but, maybe they forgot it.
It's necessary add some other options to the widget, as required attribute for the imput fields, it's because manually form rendering doesn't enable input field attribute edition. We can put separately each part from form field and rendering in html tags excepto the input field. It makes that will be virtually imposible edit it. The other, labels, help text, required '*' inclusive, we can rendering easily.

**Comment by mdunhem** [comment]
I now realize that I was a bit premature with my previous idea (was looking it up on my phone during lunch.) Didn't really think about the fact that the Meta class doesn't contain a placeholder attribute without explicitly adding it.

**Comment by mdunhem** [comment]
How about adding the ability to apply any additional attributes to the input, or widget, like you can in standard Django widgets? [Styling widget instances](https://docs.djangoproject.com/en/1.9/ref/forms/widgets/#styling-widget-instances)

``` python
widget_attrs = {'id': prefix, 'placeholder': self.label}

if hasattr(self.meta, 'widget_attrs'):
    widget_attrs.update(self.meta.widget_attrs)
```

Then when defining your blocks you can add a widget_attrs with:
``` python
h2 = CharBlock(icon="title", classname="title", widget_attrs={'placeholder': 'me@example.com'})
```

This would be added to the FieldBlock class and would make it available to pretty much all input blocks.

**Comment by gasman** [comment]
As mentioned on https://github.com/torchbox/wagtail/pull/2175#issuecomment-194838184, I'm concerned that having parameters to Block to determine the presentation of the form field - as opposed to the actual data model - would be setting a bad precedent:

> RichTextField and StreamField are ultimately model fields, describing a database-level data representation, and details about the form representation do not belong there. Just as Django's own APIs enforce a separation between model fields and form fields, we should find a better place to put those purely 'cosmetic' options, if we need them. (For RichTextField, the better place is probably the 'panels' definition; for RichTextBlock, we probably don't have any suitable place at the moment.)

Arguably we've already set a precedent with `icon` and `classname`, but I'd rather not take it any further.

Logically, the best place we have right now for options like this would probably be parameters to `StreamFieldPanel` in the panel definitions, but that's a bit awkward due to the nested nature of StreamFields.

**Comment by heymonkeyriot** [comment]
I think @alexgleason was principally referring to non-Streamfield/ RichTextFields e.g. TextField, URLfield etc.

I think we can be more sure what a text field is referencing and so be able to give it a placeholder (I think there may be occasions where it would still be possible to give certain RichTextFields placeholder text, but think you're correct it may well set a bad precendent)

There are a lot of use cases where Alex's original suggestion would be useful e.g.
label: `Email`
placeholder:  `you@example.com`

Think it's worth noting that this feels like it ties in more generally with the wider editor UI conversations happening at the moment.

**Comment by alexgleason** [comment]
I'm definitely referring to StreamField blocks. But those don't have panels, right? So in order to implement placeholder text for them we have to first implement a concept of StreamField panels?

**Comment by SalahAdDin** [comment]
And i'm talking about forms widgets in addition. :D

**Comment by Pomax** [comment]
This seems to be the only issue for placeholder text, and I would definitely want this for regular fields, at least on the admin side: not being able to set a placeholder text for CharField, URLField, etc (only being able to only set a `help_text`) means one cannot help admins/staff/ICs with accessibility needs to the degree they deserve.  Being able to specify a text input placeholder `sp_...` is going to help these folks so much more than just having a low-contrast-ratio help text even if it's a detailed description like "please fill in the sp identifier here, including the sp_ prefix".

**Comment by zeroepix** [comment]
For anyone ending up here trying to figure out how to add a simple placeholder to a field in Wagtail's admin view, and end up scratching their heads, it's actually quite easy. Say you've made a soldier model that content creators will use, and you want to put a placeholder in the field, just do something like this:

```
# models.py
from django import forms
from django.db import models
from wagtail.admin import widgets # to use wagtails special datetime widget

class Soldier(models.Model)::
    name = models.CharField(max_length=48)
    date_of_birth = models.DateField(null=True, default=None, blank=True)
    serial_number = models.DecimalField(null=True, default=None, blank=True)
    
    panels = [
        MultiFieldPanel(
            [
                FieldRowPanel(
                    children = (
                        FieldPanel('name', widget=forms.TextInput(attrs={'placeholder': 'Enter Full Name'})),
                        FieldPanel('date_of_birth', widget=widgets.AdminDateInput(attrs={'placeholder':'dd-mm-yyyy'})),
                        FieldPanel('height', widget=forms.NumberInput(attrs={'placeholder': 'in cm only'})),
                    )
                ),
            ],
            heading = "Personal Information",
            classname = "collapsible"
```
You can select from the widgets [here](https://docs.djangoproject.com/en/3.0/ref/forms/widgets/#built-in-widgets), plus whatever you find in wagtail\admin\widgets.py

**Comment by Pomax** [comment]
Could I ask you to file a PR against the documentation, explaining showing this pattern on the page(s) that teach people about panels, so that this information won't fall off the internet the moment this issue gets closed?

**Comment by zeroepix** [comment]
I've not done a PR before, nor worked with rst doc but I've given it a go here: [forked repo](https://github.com/zeroepix/wagtail/blob/master/docs/reference/pages/panels.rst#placeholder-text) / [pull request](https://github.com/wagtail/wagtail/pull/6308)

Let me know if I should put it somewhere else or make any changes.

**Comment by thibaudcolas** [comment]
As part of the [page editor 2022](https://github.com/wagtail/wagtail/discussions/7739) project, we’re making the the fields’ `help_text` much more prominent – it’ll always be underneath the fields, rather than off to the side, with plenty enough contrast.

Once that lands, I’ll close this issue. I don’t think we want to support using placeholder – `help_text` is a better fit for two reasons:

- Placeholder text disappears as soon as the field is interacted with. If you want to communicate what a field is for / what format is expected, might as well add it in a way users will be able to refer to even after they start ttyping.
- Placeholder text is often confused with a field actually having a value set. There is very little possibility for us to make this more obvious with styling.

The original `you@example.com` example is a good one to reflect on – it’s very easy to confuse this with the field having a value already, and if you do have users who need to be told what format an email address has to be in, they’ll welcome seeing this format at the point where they get validation errors (rather than having to empty the field to see this again).

**Comment by thibaudcolas** [comment]
I’ll close this now based on the above. Help text is now much more prominent and consistently displayed in the latest designs, and placeholder text should be considered an anti-pattern.
