### ISSUE TITLE
Hooks for CSS and JS shouldn't allow full HTML insertion

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2338]
`insert_editor_css`
`insert_editor_js`
`insert_global_admin_css`
`insert_global_admin_js`

Is there a better way for these hooks to work? Related: #2333 #2276

They require the user to insert the full HTML. This opens potential for abuse where people could use them to embed things other than styles or scripts. Implementations look something like this:

``` python
@hooks.register('insert_editor_css')
def editor_css():
  return format_html('<link rel="stylesheet" href="' \
  + settings.STATIC_URL \
  + 'demo/css/vendor/font-awesome/css/font-awesome.min.css">')
```

I think it would make more sense to pass in a _file_ (and maybe some options) rather than a full HTML tag.

That way people can't possibly misuse them, and we have more control over how the content can be rendered.

My first thought is to make it look something like this:

``` python
@hooks.register('insert_editor_js')
def editor_js():
  return {
    'files': [static('demo/js/myscript.js')],
    'options': {
        'async': True
    }
  }
```

StreamField blocks implement something similar. [Here is how a ListBlock gets its assets.](https://github.com/torchbox/wagtail/blob/824a7c50e272c3f1492551f015716a771f8cb639/wagtail/wagtailcore/blocks/list_block.py#L39) This is implementing [Django Form Assets](https://docs.djangoproject.com/en/1.9/topics/forms/media/), which could also be a great way to accomplish this. It allows for options to account for optional HTML attributes like CSS's `screen` (not sure about async for JS though).

Ideally, I'd like to see a hook implementing this. Maybe it could look like:

``` python
from django.forms import Media
from django.contrib.staticfiles.templatetags.staticfiles import static

@hooks.register('insert_editor_assets')
def editor_assets():
    return Media(
        js=[static('myapp/myscript.js')],
        css=[static('myapp/mystyle.css')]
    )
```

It appears to be the standard Django way, and it's already what we're using for StreamField.

**Comment by gasman** [comment]
What's wrong with letting people insert arbitrary HTML? I don't think there's any potential for abuse - if you can run Javascript, you effectively have complete control already. Or, to put it another way: if a developer uses those hooks for something other than what they were designed for, all they're really doing is trashing their own Wagtail installation :-)

Having said that, I think the only reason we had separate JS and CSS hooks in the first place was to ensure they were placed in `{% compress js %}` or `{% compress css %}` blocks as appropriate. Now that we've ditched django-compressor, I suspect the distinction may be entirely meaningless. Even so, I'm inclined to say "don't fix what isn't broken" - even if there's no functional difference, I think there's value in precisely defining the intent/purpose of each hook, so that we're free to change the implementation in future if necessary (and don't feel bad about breaking people's code because they chose to use them outside of our parameters).

**Comment by alexgleason** [comment]
I don't have a problem with letting people insert arbitrary HTML, it's not that at all. If the hook were named `insert_admin_markup_head` it would make sense. But the hooks don't actually do what they're named to do, and I see a potential for them being misused for that reason. Someone wanting to insert arbitrary HTML could do it within insert_css, which would be wrong.

I mean, at the end of the day, if it works it works. But I don't want to be like PHP. I think we need to be super careful about hooks because people (like me) are starting to make Wagtail plugins, and god forbid we're in a "stuck with it this way" situation for 20 years when Wagtail becomes the most widely used Python CMS.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by JoshBarr** [comment]
It might be nice if the hooks add the static assets to some kind of pipeline or build process, rather than inserting them as arbitrary HTML elements? Although that starts to get a bit too much like Rails magic, it also helps us avoid `<script />` tag soup and re-use common JS components and CSS variables from the Wagtail core.

**Comment by alexgleason** [comment]
>I would prefer to override a template block to insert HTML or CSS

Ahhhh, yes!! Just create templates at templates/wagtailadmin/ in your app instead of using hooks... brilliant.

**Comment by gasman** [comment]
@JoshBarr Keep in mind that site implementers and authors of third-party plugins won't be able to tap into Wagtail's own build pipeline (since our release packages ship with pre-built assets) and we certainly don't want to place the burden on users to set up something equivalent at their end (ref. the headaches that django-compressor caused).

While the current 'pass in an arbitrary chunk of HTML' hooks aren't particularly smart, they at least work as a "lowest common denominator" - you can build a Wagtail frontend component using whatever technologies and pipelines you like - which may be completely different from the ones used by the rest of Wagtail, or indeed be pure vanilla JS - and as long as the output of that build process is a bunch of `<script>` tags of some kind, then `insert_editor_js` / `insert_global_admin_js` will work.

Re template overriding, I don't think that's the best approach here. It's pretty brittle at the best of times - we'd need to clearly define which bits of the admin templates are guaranteed to remain stable between releases (and I suspect that doing that even on a small scale would be quite a major burden on our side, given our future plans for overhauling the Wagtail UI), and doesn't cope well with multiple components attempting to override the same thing in a non-deterministic order (we'd probably need something like django-overextends). From what I can gather, over-reliance on template overriding is one reason that django-admin is now at a point where it's pretty much impossible to make any non-cosmetic changes.

**Comment by alexgleason** [comment]
>which may be completely different from the ones used by the rest of Wagtail, or indeed be pure vanilla JS

Trying to envision what you mean here. I think you're referring to something like how django-compressor lets you do:

```
<link rel="stylesheet" type="text/x-scss" href="{% static 'css/style.scss' %}">
```

In this case, I'm even still concerned about the hook names, which say `insert_editor_css` when a name like `insert_editor_styles` is more descriptive of what it actually does.

**Comment by JoshBarr** [comment]
@gasman you're right, that does sound like the most pythonic (e.g, predictable) way of doing things. I retract my suggestion :)

**Comment by gasman** [comment]
@alexgleason That's partly it, yep. Any one approach to bundling or building assets (such as Django form media, or django-compressor) comes with its own set of assumptions that's liable to be broken by the next trendy front-end framework to come along... maybe it's the use of a non-standard content type like `text/x-scss`, or the `defer` attribute, or maybe it's a system like require.js where the exact set of files to be loaded can't be determined on the Python side (because you need to actually run the JS to discover the imports).

Right now, it's fair to say that the Node ecosystem has more advanced front-end building / bundling tools than Python, so any Wagtail add-on with truly complex front-end requirements will probably do what Wagtail itself does, and have an npm-based build process that's external to Python. As long as that process gives us *something* that we can inject into the page, the current hooks will do the job.

To be fair, there's a lot that the current "lowest common denominator" approach *can't* do, like tracking dependencies between modules - for example, if an add-on module wants to put a date picker on a particular page, then ideally we should be able to figure out whether jquery.ui.datepicker has already been imported on that page and avoid importing it again. Django form media would be the standard answer to that within the Django ecosystem, but if the add-on happens to be built on a front-end framework with its own opinions about dependency management then that might not be a good fit. As far as I can see, "how to play well with current front-end frameworks' asset packaging" is an open question, not just for Wagtail but for the Django world in general (e.g. see James Aylett's DUTH talk https://opbeat.com/events/duth/), and until a clear answer emerges as the One True Way To Do Asset Packaging, I think the pragmatic way forward is to stick with the current low-level hooks. (Perhaps there's even an opportunity for us to experiment with different asset packaging strategies as optional add-ons that sit on top of the low-level hooks... `wagtail.contrib.browserify`, anyone?)

**Comment by alexgleason** [comment]
>...ideally we should be able to figure out whether jquery.ui.datepicker has already been imported...

You're right. I was thinking about this a few days ago and didn't fully wrap my head around it. It may be the most sensible reason to re-think these hooks. Check out [the way WordPress does it](https://developer.wordpress.org/reference/functions/wp_enqueue_script/).

Scripts all have names (formatted like slugs). Then they can be added to your markup by name, and some names can depend on other names so the system makes sure to import the dependencies first, and if the same name is sent in twice it will only render one. For instance, some of those names are: `jquery`, `jquery-ui`, `colorpicker`, `tiny_mce`, etc.

**Comment by gasman** [comment]
Closing this now, as I don't think we're going to come to any conclusions here. Our approach to front-end asset management in Wagtail has and will evolve - but however much the cheap-and-cheerful approach offered by these hooks falls out of favour, I think they'll still be useful as a lowest-common-denominator, and it would be counter-productive to drop them or replace them with something less flexible.
