### ISSUE TITLE
Wagtail icon set should be extended and improved

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/wagtail#2349]
The icon set from the Wagtail font is fine but functional, and really quite limited
![image](https://cloud.githubusercontent.com/assets/11335309/13721963/d8512a90-e82d-11e5-8f09-03abb427424c.png)
#2334 raises a problem with the spinner, in #2342 I raised how the user icon could be enhanced. It's been raised [elsewhere](https://groups.google.com/forum/#!topic/wagtail/i3aUpnOkL6U) that the icon set should be extended, but can't find an existing issue here on github. @alexgleason released https://github.com/alexgleason/wagtailfontawesome, which helps, though requires the user to then obviously use FontAwesome, which brings in an additional dependency.

I think we can do better than this and think it'll enhance the general feel of the product to have some improved icons.

**Comment by gasman** [comment]
+1. As per the discussion on #2285, I think the key to a really first-rate Wagtail site is for the implementer to get involved in UI decisions, including choosing icons that are relevant to that site's business objects and thus meaningful to editors. To that end, it would make sense for Wagtail to provide a comprehensive set of icons for implementers to use, rather than just ones that represent Wagtail's own concepts.

**Comment by davecranwell** [comment]
Bear in mind https://github.com/torchbox/wagtail/issues/1224

We need to replace icon fonts with SVG sprites. Not only do they have odd results when failing to load, but they have odd results with screenreaders too, of which which some attempt to read out `content` properties.

See https://css-tricks.com/icon-fonts-vs-svg/ for more.

That's not to say implementers shouldn't be allowed to use icon fonts if they want to, but it does change how the proposed extension of the icons should occur for the core icon set.

**Comment by heymonkeyriot** [comment]
Wasn't aware of #1224. Completely agree that it makes sense for the icons to be svgs rather than font files, for all the reasons put forward on that other ticket.

I think we could start concurrently thinking about the other icons (and amends) to the existing set that could be introduced whilst work's happening on #1224. 

@gasman, completely agree we should try and go beyond just the Wagtail concepts (or at least our understanding of how they might be representated) but also think we should try and limit how many icons we provide initially. Perhaps we can stagger the enhancement over the course of a number of releases so that we start releasing incremental benefit to the use rather than all at once when "finished"?

**Comment by gasman** [comment]
As discussed above and at #2970, there are strong arguments for extending the icon set. Switching to SVG sounds like the technically better solution, but I don't want us to fall into a "perfect is the enemy of the good" situation - if SVG is going to take a while, and there's a font-based solution we can go with in the meantime, we should go with that.

I _think_ that historically, one of our major worries about using a large icon font like FontAwesome was loading time - especially on mobile. Is that something we need to consider?

**Comment by SalahAdDin** [comment]
+1 to expand :D

**Comment by tmsndrs** [comment]
@thibaudcolas Did you make any progress on this? Otherwise we'll look into it at Torchbox.

**Comment by thibaudcolas** [comment]
No, not really. The only thing worth mentioning is the React [Icon component](https://github.com/wagtail/wagtail/blob/master/client/src/components/Icon/Icon.js), which was meant to act as an abstraction layer so that changing the implementation of icons would be simpler. But at the moment this is only used for the explorer menu AFAIK.

**Comment by tmsndrs** [comment]
How would people feel about moving to Google's Material icons? It has a webfont and SVGs. 

Anyone have any performance insights on the impact this might have? 

https://material.io/icons/

**Comment by lb-** [comment]
Obligatory mention of FontAwesome 5 - https://fontawesome.com/ - has SVG as of version 5, but I am not sure on loading time with 2k+ icons though.

The material ones will work fine though, they look nice and developers can always add more if they need them.

It might be also good to consider the icon overlap between main Wagtail admin and Draftail, at the moment css icon classes are used but there is an issue relating to SVG icons: https://github.com/springload/draftail/issues/119

**Comment by thibaudcolas** [comment]
The performance impact would be on load time. The more icons there are in the set, the longer it will take to load, regardless of whether they are used or not. When it comes to rendering, I don't think there would be much of a change depending on the size of the set.

Mobile connections are slower than desktop and less reliable. If the icon font fails to load, the UI looks broken (SVG icons don't have that issue, if they are inlined they are "always loaded", and if they are external there won't be anything displayed in their place). With a bigger icon set, the download would take longer so would be more likely to fail.

Here are some numbers, gzipped for CSS & SVG:

- Current Wagtail set: `wagtail.ttf` = 22.6 KB (+ some CSS, a few KBs)
- Current Wagtail FontAwesome set: `fontawesome-webfont.woff2?v=4.7.0` = 75.6 KB (+ 7.1 KB of CSS)

Material's 900+ icons:

- As a WOFF2 icon font: 48 KB (+ very little CSS, say 0.25 KB)
- As SVG sprites: 160 KB (divided in 32 sprites by default), no CSS

FontAwesome 5's 900+ free icons:

- As a WOFF2 icon font: 56 KB for brand icons, 12 KB for regular icons, 36 KB for solid icons (+ 8 KB of CSS)
- As SVG sprites: 120 KB for brand icons, 28 KB for regular icons, 92 KB for solid icons, no CSS

Finally, depending on how the SVG sprites are loaded we would likely need to use the https://github.com/jonathantneal/svg4everybody polyfill to ensure support for IE11 (a few more KBs of JS, yay).

------

To put those numbers in perspective, at the moment Wagtail loads 354 KB of web fonts (Roboto Slab regular, and no less than 4 weights of Open Sans). For some reason Wagtail's icon font is loaded as a TTF, so 3-4 times bigger than it could be as a WOFF/WOFF2.

For the next steps, ideally we would want to use SVG icons with sensible sprites. The big advantage is that only the sprites corresponding to icons used on a given page will be loaded. If we don't want to wait for that to happen, the impact of loading a bigger icon set won't be that important if we can avoid the 56 KB of FA brand icons.

**Comment by tmsndrs** [comment]
@thibaudcolas thanks for doing this! Really helpful to understand. Sounds like we could and should implement a better solution here. I'll talk to our design team about which icon set we should go with and report back. 

What would be the next tasks we would need to complete? Mapping instances of the old icons to new?

**Comment by Fandekasp** [comment]
@tmsndrs any progress on  this issue?
I also found this issue while looking for a way to change the icons (eg set a custom spinner image).

**Comment by thibaudcolas** [comment]
We’ve made a lot of progress in switching to SVG icons, now over at #6107 for the last mile.

**Comment by thibaudcolas** [comment]
For anyone interested in this, the current provisional plan is for us to consolidate to Font Awesome 6. @nicklee and @benenright will review the feasibility design-wise and create a mapping from the existing icons to the new FA6 ones, while we complete the switch to SVG icons (#6107).

This will be an opportunity for us to be consistent with following licensing requirements for those icons, and consider which icons to document or provide that aren’t directly needed in Wagtail core but we would encourage site implementers to use for their projects.

**Comment by alexgleason** [comment]
The most awesome modern icon set is Tabler: https://tabler-icons.io

There's so much more you can do with it that isn't in Font Lame 6's free plan.

**Comment by thibaudcolas** [comment]
@alexgleason thanks for the suggestion! Could you expand on why exactly you recommend this?

Font Awesome is very well known in the dev world, and also has the advantage of being what we already use for lots of Wagtail, though with inconsistencies and older versions. If it’s about the size of the icon set, personally I’d have expected 2000 icons to be plenty enough to have for free, particularly considering that paying for more or using different icons is simple.

**Comment by alexgleason** [comment]
Try looking up "Font Awesome 6 Free Icons" and see if you can even find the full definitive list. It took me about 5 minutes to find it, because it's a filter you have to apply and not a dedicated page. The beloved icon set has become developer hostile. I would argue that FA6 isn't even _well known_ at this point, they're just a proprietary icon set like any other.

It's not sustainable to develop against if you can't easily find the list. Compare with Tabler, which is 100% free with an accessible list: https://tabler-icons.io

Tabler is created by a polite Polish man who will answer your emails and take commissions. You could actually have a working relationship with Tabler.

Finally, look at the Design category of Tabler. Streamfield is begging for it.

**Comment by thibaudcolas** [comment]
👍 Thanks, I’ll take a look at those specific categories. It’s a lot of icons to navigate so I agree it takes a bit of time to review everything that’s available, but I don’t think that’s really a barrier to usage / something Tabler Icons does better. The SVG icon set is [licensed CC BY 4.0](https://github.com/FortAwesome/Font-Awesome/blob/6.x/LICENSE.txt), so clearly not proprietary.

Anecdotally so far we’ve found Tabler icons harder to work with because the SVGs are heavily reliant on strokes for rendering. In design software (Figma in our case) the icons are harder to resize because of this. Might just be a learning curve thing though.

**Comment by alexgleason** [comment]
The stroke is part of what makes it good, since you can easily customize it.

Also, line icons are in right now. So if this is about line vs filled icons, I'd go with line icons anyway because it gives it a more premium feel.

This is subjective, and I don't have skin in the game anymore anyway. Just chiming in on what I've learned over the years.

[Kazam_screencast_00076.webm](https://user-images.githubusercontent.com/3639540/220703324-6a722e81-5b2c-4448-9365-e2773c5de10b.webm)

**Comment by thibaudcolas** [comment]
For anyone interested in this, here is an overview of all/most icons currently present in the CMS, including approximative instance count and usage: [Wagtail 4.2 icons overview](https://codepen.io/thibaudcolas/pen/dyqKxxj).

A few very specific icons are missing from this list, for example:

- A few help messages use a text "?" as their icon (TBC whether this is in test cases only or still the case in the UI).
- The horizontal rule icon in rich text is `―`.
- The line break icon in rich text comes from Draftail

**Comment by Rohitrky2021** [comment]
will i do this work of icons?

**Comment by thibaudcolas** [comment]
@Rohitrky2021 not sure I understand your question, this is currently assigned to someone else and isn’t up for grabs.
