### ISSUE TITLE
Need ability to discover third-party packages more easily

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2355]
Something @heymonkeyriot and I have been discussing lately is how to implement a resource to easily find and discover Wagtail-related packages. WordPress, for instance, has a plugin search and installer built directly into the admin GUI. Alternatively, Craft CMS has a [separate website that serves as an index](https://straightupcraft.com/craft-plugins) for all plugins.

Regardless of the approach taken, doing this will require us to index relevant packages, so I think that's the first and most important problem to solve. WordPress and StraightUpCraft handle this by user submission, but we can do better.

For instance, Bower cleverly solves this problem with a [dedicated server](https://github.com/bower/registry) that hooks into the GitHub API on the back-end, builds a list of all repositories in existence which contain a `bower.json` file in the root directory, and [presents them as JSON that any application can hook into](http://bower.herokuapp.com/packages).

Thoughts?

**Comment by heymonkeyriot** [comment]
Agree that this would be hugely useful. Likewise Bower's solution is fairly elegant, certainly as a way of finding all repos for Wagtail in existence. Agree that defining that feels like an important first step regardless of how we then subsequently present them. 

My only reservation with that as a means of populating the website is that we'd be dependent on what had been put in the readme for the data that we can show a user, there'll be a certain amount of volatility with that. The Wordpress method potentially helps with that insomuch as it requires a contributor to upload screenshots, description etc.

Adding documentation label as well because beyond http://docs.wagtail.io/en/v1.3.1/reference/contrib/index.html I'm not aware of anywhere where we document the resources Wagtail can use.

**Comment by thibaudcolas** [comment]
Hi there, this feels related to https://github.com/springload/awesome-wagtail. Could this list be considered a fix for this issue?

It's a stretch from the automated systems you were discussing, but the end goal feels similar enough.

**Comment by alexgleason** [comment]
@thibaudcolas tbh even GitHub's new tagging system which lets you [tag "wagtail"](https://github.com/search?q=topic%3Awagtail&type=Repositories) might be enough at this point. Obviously if the pool of community contributed plugins expands we will need something more comprehensive, but I'm happy to close this for now.
