### ISSUE TITLE
Prefix management commands

### ISSUE THREAD

**Issue by jaroel** [wagtail/wagtail#2447]
The update_index management command is already clashing with haystack's.
AFAIC wagtail management commands could be prefixed with 'wt_' to prevent this in the future.

**Comment by kaedroho** [comment]
Thanks for pointing this out!

Django uses argparse which supports subcommands. So it may be possible to have a syntax like ``python manage.py wagtail update_index``

Another possibility could be to add new subcommands to our ``wagtail`` command for these. Eg ``wagtail manage update_index`` or just ``wagtail update_index``

**Comment by SalahAdDin** [comment]
:+1:

**Comment by benjaoming** [comment]
I like the suggestion of `python manage.py wagtail update_index`, it's easy to remember.

If people want shortcuts, they can always add some alias in their shell's configuration. It's no more than `alias wt='python manage.py wagtail'`

**Comment by tomdyson** [comment]
We've decided to go with `manage.py wagtail update_index`, with deprecations.

**Comment by brian-maher** [comment]
Any updates on this? This is still causing issues as wagtail's update_index command clashes with that of the widely-used Django-haystack.

**Comment by gasman** [comment]
Proposed fix: #5009

**Comment by benjaoming** [comment]
>  I'm not really keen on that any more - it seems a bad idea to break standard Django conventions for all users in order to accommodate what must be a fairly uncommon scenario.

I don't think anyone proposed this. I would think this sort of change would happen with gradual deprecation and at a proper version bump.

**Comment by gasman** [comment]
> Regarding conventions... they are conventions with good reason. They can be broken for similar good reasons :)

I agree, but I don't think that a single clashing command (with one particular combination of packages) is enough reason for us to invent a non-standard namespacing scheme. If this is a wider problem in Django, then it would be better to fix it within Django - I imagine implementing a syntax like `./manage.py app_name:command_name` would be a relatively simple and welcome enhancement.

I'm also aware that this issue has been open for 2-3 years with very little progress, and at that point it makes sense to find a less radical fix, rather than waiting for it to reach the top of a developer's priority list.

**Comment by kaedroho** [comment]
> We've decided to go with manage.py wagtail update_index, with deprecations.

I'd like to just mention that I'd rather we didn't deprecate the old commands. Many people reference them in their production configs so would make it a pain to upgrade and this issue only affects a few people. There may be other options we can try, such as getting Wagtail's update_index command to call Haystack's command?
