### ISSUE TITLE
Unexpected Elasticsearch partial_match partial word matching behavior

### ISSUE THREAD

**Issue by ghostwords** [wagtail/wagtail#2475]
Partial word matching using Elasticsearch matches word fragments anchored to the beginning of words only. For example, searching for "beat" does not match "truckbeat" (while "tr", "truck" and "truckbea" match). This seems related to using Elasticsearch edge n-grams for `partial_match` search fields.

The database search backend appears to perform partial word matching correctly: "beat" matches "truckbeat".

Using Wagtail 1.4.3.

**Comment by benebun** [comment]
Also experiencing this with Wagtail 1.8. Any feedback?

**Comment by kaedroho** [comment]
Sorry for the delay in responding, I'm not sure how I missed this earlier.

Wagtail does this by design, as "partial match" is intended for autocomplete.

You should be able to change the analyzer of for your field by using the ``es_extra`` keyword argument on the search field:

```python
    search_fields = [
        # Use the ngram_analyzer which shoud already be installed by Wagtail
        index.SearchField('my_field', es_extra={'analyzer': 'ngram_analyzer'}),
    ]
```

The database backend doesn't actually support "partial matching" at all, it behaves that way because it's too dumb to even know what a word is.
