### ISSUE TITLE
Expose admin style to plugins

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2478]
Take [wagtailblocks_cards](https://github.com/alexgleason/wagtailblocks_cards) for instance. I want to use the "light blue" color in my CSS, but I have to hardcode it. If that color ever changes, it will break my plugin.

I'm wondering if there's a way to expose certain things, like maybe SCSS variables, so that third-party packages can use it.

**Comment by timheap** [comment]
If the `wagtail` npm package also included the Wagtail `.scss` files, specifically the mixins and global variables, then you could import the styles from there. @JoshBarr would probably be able to answer how this might work.

**Comment by thibaudcolas** [comment]
As of #8824, we now have CSS variables for all colors, and all fonts. I believe this solves what this issue is about much more neatly than Sass, as the CSS variables are bundled directly in Wagtail’s stylesheets. 

I’ll close this now, if there’s a use case for other variables I’m sure we’d be interested in having more available.
