### ISSUE TITLE
SnippetChooserBlock not being indexed with Elasticsearch

### ISSUE THREAD

**Issue by fawx** [wagtail/wagtail#2500]
I'm posting this here before I submit a pull request in case this has been discussed and rejected.

We use SnippetChooserBlock in tandem with pages to allow us to embed repeatable content in several pages such as a location card, an event preview, things of that nature. Definitely not appropriate use for a block.

However when the page is serialized for Elasticsearch, SnippetChooserBlock is completely ignored as it does not have get_searchable_content implemented. Here is how I made it work

```
class SearchableSnippetChooserBlock(SnippetChooserBlock):

    def get_searchable_content(self, value):
        if hasattr(value, 'search_fields'):
            fields = value.get_search_fields()
            doc = []
            for field in fields:
                doc.extend([field.get_value(value)])
            return doc
        else:
            return []
```

**Comment by gasman** [comment]
Hi @fawx - thanks for the suggestion!

Are you proposing adding SearchableSnippetChooserBlock as a new block type, or making this the standard behaviour for SnippetChooserBlock? If it's the latter, we'd have to be a bit careful, as there's no fixed rule about what a snippet chooser actually 'means'... sometimes, as in your example, it's an 'inclusion'-style relation, where you do want the snippet content to be indexed as part of the page content; at other times, snippets are used for tagging, or linking to external resources, where you don't want the snippet content to be considered part of the page.

As an example of that, suppose we were building a tourism site, where we use a SnippetChooserBlock to tag articles with a particular city, using a City snippet model that looked like this:

    class City(models.Model):
        name = models.CharField(max_length=255)
        description = RichTextField()

        search_fields = [
            index.SearchField('name'),
            index.SearchField('description'),
        ]

    register_snippet(City)

In this case, you wouldn't want to include the city description as part of the article's indexed content - that would mean that whenever you searched for a word that happened to be included in that description, you'd get lots of irrelevant results.

Not sure what the most intuitive way of distinguishing between these two scenarios would be. Having distinct `SearchableSnippetChooserBlock` and `SnippetChooserBlock` classes would be one possibility - or having a new parameter to SnippetChooserBlock: `SnippetChooserBlock(City, search_indexed=True)`. It seems like it would be neater to have all of the search indexing rules centralised in the page's `search_fields` definition, though. So, as a totally half-baked idea, how about something like:

    class Article(Page):
        body = StreamField([
            ('paragraph', RichTextBlock()),
            ('city', SnippetChooserBlock(City)),
        ])

        search_fields = [
            index.SearchField('title'),
            index.SearchStreamField('body', {
                'paragraph': True,  # always index paragraph blocks in full
                'city': ['name'],  # only index the 'name' field of city blocks
            })
        ]

**Comment by fawx** [comment]
hey @gasman,

thanks for the quick reply! I think another index field class is a better idea. I like the idea of being able to control what's indexed per page.

**Comment by gasman** [comment]
Revisiting this... I think that descending into the searchable content of a snippet model linked through a SnippetChooserBlock is rarely going to be the right thing to do. The most typical use of snippets would be something like an Author snippet, with a bio field that's shown on each article written by that author - it's better _not_ to treat that bio as part of the indexable content of the article, because that would generate a whole load of duplicate results for search terms that match the bio. More generally - the selling point of snippets is that they can be used multiple times across a site, and normally you wouldn't want one piece of content to be indexed multiple times.

For the cases where you do want it, it would be appropriate to handle that by defining a ChooserBlock subclass with `get_searchable_content` overridden as desired. That could be done via `SearchableSnippetChooserBlock` as shown above, but my preferred approach would be to set up a dedicated [ChooserViewSet](https://docs.wagtail.org/en/stable/extending/generic_views.html#chooserviewset) for the model so that it gets a dedicated FooChooserBlock, and use [base_block_class](https://docs.wagtail.org/en/stable/reference/viewsets.html#wagtail.admin.viewsets.chooser.ChooserViewSet.base_block_class) to set up a custom `get_searchable_content` method.
