### ISSUE TITLE
contrib.wagtailmedusa doesn't work anymore with Django 1.8.1+

### ISSUE THREAD

**Issue by edmellum** [wagtail/wagtail#2504]
django-medusa doesn't support Django 1.8.1+ from what I can see because of [this issue](https://github.com/mtigas/django-medusa/pull/27). The project seems dead too. :(

It should probably be mentioned somewhere that it doesn't work.

After some tweaking I managed to get django-bakery working with wagtailbakery even though it didn't seem quite as simple as medusa with the contrib package.

**Comment by grbd** [comment]
I think this should work, after installing django_medusa (I do this in a python virtual environment)

I edited the file Lib\site-packages\django_medusa\renderers\__init__.py
then change the 2nd line down on the imports so it looks like this

from django.conf import settings
**import importlib**
from .base import BaseStaticSiteRenderer
from .disk import DiskStaticSiteRenderer
from .appengine import GAEStaticSiteRenderer
from .s3 import S3StaticSiteRenderer

**Comment by edmellum** [comment]
@grbd isn't that exactly what the issue I referred to mentions though? :)
It seems far from ideal to me to edit a dependency to make this work.

**Comment by kaedroho** [comment]
We should remove the ``wagtailmedusa`` module, but we could replace it with ``wagtailbakery`` or something custom in the future though.

**Comment by gasman** [comment]
Logically, it would make sense to drop wagtailmedusa (since it's not compatible with any Django version we support) and point people at wagtailbakery instead. However, I wonder if there's an outside chance that someone wanting to upgrade their Wagtail site will prefer to monkeypatch Medusa (or even create a public fork of the project) rather than switch technologies - in which case we'd be doing them a disservice by dropping the wagtailmedusa module, and it would be better for us to deprecate it over several releases.

Although having said that, all they really need to do is take the wagtailmedusa code and host it within their own project - and if they're going to the trouble of fixing Medusa, they're probably not going to be deterred by that extra step. So maybe dropping it immediately isn't so bad after all...

**Comment by grbd** [comment]
Thanks for the link, I knew of djangobakery but not wagtailbakery, since I've been looking for a cms that can handle static exports

**Comment by atbaker** [comment]
Just to chime in - we're using django-medusa with Python 3.4 and Django 1.9 right now, and it does require some massaging to work.

I would gladly swap it out for something that's better supported, even though it means a little rework

**Comment by grbd** [comment]
If you want a way of handling the search for a statically generated site, then it may be worth having a look at the code mkdocs uses for generating the json search file that it generates / uses via javascript

**Comment by gasman** [comment]
I've added a note in 5dee12508dfa81239ac27913eaf4ebc4c39fdd71 that django-medusa is unmaintained and incompatible with Django >=1.8. Will make a decision on formally deprecating / removing / replacing it for Wagtail 1.7.

**Comment by m1kola** [comment]
I think, it's time to close this issue, because `contrib.wagtailmedusa` is no longer with us since Wagtail 1.10. See c7b778c4e9b35ab3a88c94a4c38bb4498d709a0a
