### ISSUE TITLE
DateBlock date formats

### ISSUE THREAD

**Issue by bmihelac** [wagtail/wagtail#2595]
Currently changing date format for DateBlock requires overriding both `DateBlock` and `AdminDateInput`. 

What do you think about making it more customizable? I have in mind additional kwargs, signature like this:

``` python
DateBlock(django_format='%d.%m.%Y.', js_format='d.m.Y.')
```

I'm aware of #1018 and if anyone is interested in how-to have formatted dates, here is the [gist](https://gist.github.com/bmihelac/6f63271934b6d6471d4cae9ab5adf946)

**Comment by gasman** [comment]
I'm definitely in favour of making the date format more easily customisable. I'm not sure if it really needs to be specified on a per-field basis, though - usually you'd want to consistently use the same format across your site, so wouldn't a global setting be enough? (Ideally, it would pick up Django's existing `DATE_FORMAT` / `DATE_INPUT_FORMATS` settings - but then we're stuck with the locale-handling quirks from #1028 / #1018 again, so it's probably simpler to create a new Wagtail-specific setting.)

It would be really nice if we could do the conversion between the Django-style and jQuery-style date formats automatically - someone building a Wagtail site shouldn't have to care about the fact that the date picker has both Django and JS components. (Sure, it's a pretty obvious implementation detail, but it's one that Wagtail should be able to handle itself, rather than leaving it to the end user). That way, we also avoid the risk of errors from people setting format strings that don't match.

**Comment by bmihelac** [comment]
I could work on this as soon as I catch some time.

Regarding conversion between Django and JS widget formats, I guess we can convert some simple formats but covering all options would be cumbersome. As I see datetimepicker uses

**Comment by bmihelac** [comment]
I have updated wagtaildemo, so it shows using ``WAGTAIL_DATE_FORMAT`` and custom formats in ``DateBlock``.

https://github.com/bmihelac/wagtaildemo/tree/demo-feature-date-block-formats

**Comment by gasman** [comment]
Fixed in #2983
