### ISSUE TITLE
Documentation required for AbstractImage.get_upload_to and AbstractRendition.get_upload_to

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#2601]
These two methods give site implementors control over where image files are stored but are not yet documented anywhere. This should probably be located in the advanced topics => images section.

**Comment by Dharma-09** [comment]
I will give a start to this

**Comment by lb-** [comment]
@Dharma-09 start with the python docstrings and then use the documentation autodoc system - this way we can also see nice docs in the code.

**Comment by MaryAyobami** [comment]
Hello
I'm an outreachy applicant and I'd love to contribute to this issue @thibaudcolas

**Comment by lb-** [comment]
@MaryAyobami - there is already a PR with feedback but no response since March. 

https://github.com/wagtail/wagtail/pull/8228

Please comment to the author of that PR and see if they are still intending to complete the requested changes. 

If you don't hear back in a day or so - feel free to copy that PR's changes (or see what was done), read the feedback and put a new PR up. 

Please ensure you reference the original PR AND this issue in your PR's description so we can track the contributors and close the older PR.

**Comment by gyanaranjans** [comment]
I want to work on the issue please assign me this.

**Comment by lb-** [comment]
Go for it @gyanaranjans - please read the previous comments as it links to an existing PR that has this job partially done.

**Comment by lb-** [comment]
We do not normally assign issues outside of the core team.

**Comment by Aym-n** [comment]
@gyanaranjans are you still working on this issue?

**Comment by ArijeetBanerjee** [comment]
I want to work on this issue. kindly give me permission and access to work on this issue
