### ISSUE TITLE
Feature Request: Blacklist for Richtext elements

### ISSUE THREAD

**Issue by hamsterbacke23** [wagtail/wagtail#2646]
I was happy to find the whitelister hook for richtext elements, but a bit disappointed that I could not blacklist elements, which is much more important for me having users copying stuff from word and who knows what... 
Instead of having a blacklister, it would be also ok to have an option to overwrite the original whitelist, not merge it..

In reality it seems not such a big problem, unless you copy html directly into your chrome dev tools richtext html field, but I want to make sure...

Also a way to replace html elements would be great, for example the `<b>` and `<i>` tags from hello js with `<strong>` and `<em>`

**Comment by gasman** [comment]
It looks like it should be possible to 'blacklist' an element with the following code (untested):

    def reject_tag(tag):
        tag.unwrap()

    @hooks.register('construct_whitelister_element_rules')
    def whitelister_element_rules():
        return {
            'h1': reject_tag
        }

You could probably use something similar to replace the tag with another one (although, if I recall correctly, the HTML spec specifically advises that HTML authoring tools *shouldn't* replace `<i>` with `<em>` unless they're absolutely certain that the author intended it as emphasis, rather than, say, a book title.)

I agree we ought to make this easier, though. (I'm surprised that the requirement to remove elements from the whitelist hasn't come up before - I guess most people aren't really on board with the Wagtail philosophy of taking flexibility away from editors :-) ) A couple of easy ways to do that:

1) provide the above `reject_tag` method in `wagtail.wagtailcore.whitelist`, alongside `allow_without_attributes`
2) in https://github.com/torchbox/wagtail/blob/ba807e5f45812e85bf83b49bf04d2c796ef63cda/wagtail/wagtailcore/whitelist.py#L136-L144, treat a `None` or `False` rule the same way as a `KeyError` (so that the above code could be simply `return {'h1': False}`).

**Comment by jschroeter** [comment]
I totally agree that it's necessary to be able to change the configuration of the whitelist. The whitelist is the right approach (instead of a blacklist), it just have to be fully configurable.

But I believe it's just the tip of the iceberg. What we actually want are configurable features for rich text editors like @gasman described in https://github.com/torchbox/wagtail/pull/2175#issuecomment-194838184. That means there is a single place where the features (e.g. HTML elements) are configured, which then makes it possible to keep the visible rich text editor buttons, client-side clean up logic (e.g. paste and drag & drop content) and the backend whitelist in sync according to the activated rich text editor features. For a smooth user experience it's important they are in sync, otherwise I could for example paste some markup, it will be displayed in the editor and only after I hit the save button and reload the editor I will be able to see that some of my pasted content was transformed/removed.

Of course, the configurable whitelist is one step in the right direction! 👍

**Comment by gasman** [comment]
Related: #3736, which implements the concept of rich text 'features'. Incorporating whitelisting logic into those will be the next logical development step.

**Comment by thibaudcolas** [comment]
Client-side this is solved with the new editor, which works with a formatting whitelist and discards everything not whitelisted on paste.

Server-side, I'm not sure whether the rich text features are fully hooked up yet for this to work as described here. What do you think @gasman?

**Comment by gasman** [comment]
Yep, I think this is fully covered by rich text features, as of #4079.
