### ISSUE TITLE
Support for .nvmrc

### ISSUE THREAD

**Issue by robmoorman** [wagtail/wagtail#2648]
As several CI platforms have support for automatically installing the supplied Node version via a [.nvmrc](https://github.com/creationix/nvm#nvmrc) file it would be nice to define the minimal version in it; which is v5.3.0 as described in the docs.
Also from frontend development perspective this is a config which is used a lot in the community.

**Comment by ThibWeb** [comment]
I looked into this a bit while setting up the project on my computer.

- https://github.com/torchbox/vagrant-wagtail-develop/blob/master/vagrant/provision.sh installs the latest v4.
- https://github.com/torchbox/wagtail/blob/master/.drone.yml says node 4.2.4. Not sure if Drone supports `.nvmrc`
- https://github.com/torchbox/wagtail/blob/master/.travis.yml does not seem to use node (I'm lacking some background here). Supports `.nvmrc`.
- http://docs.wagtail.io/en/latest/contributing/developing.html#coding-guidelines says 5.3.0 or higher

Also worth considering is specifying a node version / version range with the [package.json `engines` property](https://docs.npmjs.com/files/package.json#engines) so that it makes it clear what's "supported" (just advisory, not enforced).

**Comment by jjanssen** [comment]
Merged in 493a30b
