### ISSUE TITLE
Compatibility with the master branch of Django

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#2760]
(From discussion on Dutch sprint)

We can try to support compatibility with the `master` branch of Django.

Advantages:
- It will be easier to perform tasks like #2723
- We will help Django community to test further releases on early stages

Disadvantages
- Probably it will be hard to stay updated (solution: we can allow failures in builds and fix compatibility issues when we have time)
- We will need to test Django's `stable/*` branches releases anyway
## 

TODOs:
- [ ] Fix all deprecation warnings
- [ ] Tox and Travis config for the `master` and the latest `stable/*` branch
- [ ] Fix all test failures, if any

**Comment by SalahAdDin** [comment]
👍

**Comment by timgraham** [comment]
Compatibility with the master branch should be doable during the Django 1.11 release cycle but probably not during the Django 2.0 release cycle and any subsequent "dot zero" cycles unless you drop support for old Django versions more quickly than what we expected when crafting the latest release schedule. We specifically designed the schedule so that apps like wagtail wouldn't have to write a lot of conditional code based on the Django version to avoid deprecation warnings.

See https://docs.djangoproject.com/en/dev/releases/1.11/#deprecating-warnings-are-no-longer-loud-by-default for details.

**Comment by benjaoming** [comment]
For inspiration -> https://github.com/django-money/django-money/blob/master/tox.ini

**Comment by kaedroho** [comment]
Looks like this one is done now. We've set up Travis CI to test against Django master and right now it's reporting that we are compatible
