### ISSUE TITLE
FilterField doesn't set not_analysed for string fields

### ISSUE THREAD

**Issue by danni** [wagtail/wagtail#2770]
Filters in Elasticsearch aren't analysed, but `FilterField` doesn't index string fields with `index: not_analyzed`. This causes surprises when suddenly your value contains things that get tokenized, like slugs.

Currently you have to do this:

``` python
        index.FilterField('programme', es_extra={'index': 'not_analyzed'}),
```

**Comment by kaedroho** [comment]
The Elasticsearch 5 backend does not set ``'index': 'not_analyzed'`` because ES5 has separate string types to convey this information (``text`` for analyzed fields, ``keyword`` for not analyzed fields).

The Elasticsearch 1 and 2 backends do set ``'index': 'not_analyzed'`` on ``FilterField`` fields, so make sure that you are using the correct backend for the version of Elasticsearch you have installed.
