### ISSUE TITLE
When updating a file on an image or a document, the 'Uploaded' timestamp does not update when a file is replaced.

### ISSUE THREAD

**Issue by mwharrison** [wagtail/wagtail#2827]
To duplicate:
1. Upload a file to the Wagtail CMS
2. After some time passes, replace said file
3. Notice timestamp for 'Uploaded' column references original file upload time

**Comment by m1kola** [comment]
It's because `craeted_at` field is used to display "uploaded" time. `craeted_at` stores time when entry in database was created.

@mwharrison, thanks for reporting!

**Comment by derhedwig** [comment]
It doesn't even have `updated_at`... Maybe that would be nice to have too!

**Comment by lb-** [comment]
## Update

A simple resolution created on PR #5638 - as this column is the 'created at' field, I just renamed the header to 'Created' instead of 'Uploaded'. Adding the ability to show uploaded date is actually more complex than it seems, happy to get suggestions on other ways though if I have missed something.

Note that the images listing now longer appears to contain any columns so the fix above only addresses the documents listing.

However, I think a new issue should be created to cover a better long term solution to this, if there is some consensus I will create that issue with a bit of an idea on how to proceed.

## Option A - Add 'updated_at' field using Django's `auto_now_add` feature.

* This would add a new field to both the Document & Image models, which would affect all users of Wagtail that extend this model (with potential migration conflicts to resolve). This is quite minor as it is an 'addition'
* We could then add presentation of 'updated at' in the documents listing AND the 'view image' page within admin.
* This is a reasonably simple model change and might come in handy for the future having this field, even if not always shown.
* Note: 'Updated at' would NOT be uploaded at, this date would be affected by new uploads AND changes such as a title change.

## Option B - Add a specific 'uploaded_at' field

* This could work in line with Option A, essentially be specific about this data with a new field.
* Minimal changes to the model means this is quite simple.
* Risk is that we will 'forget' to ensure this field gets kept in sync in some parts of the code.

## Option C - Modify the `uploaded_by_user` relationship

* This would modify the uploaded_by_user field to be a relationship to another table, that can store both the user AND the date the upload took place, with the potential to add extra metadata about uploads in the future (even a 'history' of changes, without actually storing the old files themselves).
* This would be a more complex change and likely break a fair few things and need some solid thought, especially as Wagtail users that have their own image/document model would be affected by this.

I would love any thoughts on this but for now the PR above should resolve the immediate issue of this ticket.

**Comment by lb-** [comment]
I will create a new issue with the discussion above about improvements to the metadata fields available on documents/images modals
