### ISSUE TITLE
Redirect to Form landing page

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#2834]
Per the [comment in source](https://github.com/torchbox/wagtail/blob/stable/1.3.x/wagtail/wagtailforms/models.py#L176), it would be better to redirect to the form success page instead of rendering it on post.

A simple way to achieve that without needing to worry about adjusting url routes and such would be to use a query param... "/foo-form/?success".

If https://github.com/torchbox/wagtail/issues/2833 is accepted, the FormSubmission instance id or randomized token could be passed as well so it can be fetched and passed to the template.

If security is a concern around putting the id/token in url and leaking data to malicious users, it shouldn't be very difficult to use session data for verifying the user created the FormSubmission data or raising http404.

-- edit --

Forgot to mention another practical use for the query param (or unique url but more complicated with wagtail page routing) is it makes conversion tracking simple because you can simply check destination instead of needed developer to trigger an analytics event specific to the submission.

**Comment by karabellyj** [comment]
Hi I am new to contibuting and programming. I've read that the best way to learn is to contribute so I did redirection as suggested above using query param but a few tests started to fail. Most of them fail because of AssertionError: Couldn't retrieve content: Response code was 302 (expected 200). I see that it is due to the redirection but how to get rid of it. Should I adjust tests or my new code?

**Comment by gasman** [comment]
Hi @karabellyj - thanks for taking this on!

Adjusting the tests to reflect the new behaviour is the right thing to do here.

**Comment by karabellyj** [comment]
Solved that error by adding follow=True to the tests but now CustomSubmission tests are raising AssertionError: False is not true : Couldn't find 'Thank you for your patience!' in response and I don't see why.

**Comment by strindhaug** [comment]
I've created two pull requests to address this issue:
 https://github.com/wagtail/wagtail/pull/4024  is a m one minor change that I think should be merged anyway. It simply moves the render-part of the serve method for the landing page to a separate method so that you can override the rendering of the landing page without having to copy paste all the other stuff from the serve method.

https://github.com/wagtail/wagtail/pull/4025 is up for discussion as this adds a new optional field to the model. (And I now realize I didn't make any migrations for this, yet). This new field is a foreign key to a page; that if set, is is used to redirect to instead of rendering the landing page.

**Comment by strindhaug** [comment]
I also made another PR that implements the success parameter idea: https://github.com/wagtail/wagtail/pull/4026

To fix the CustomSubmission test errors, I  had to modify the model FormPageWithCustomSubmission, slightly so that it doesn't apply it's overrides in the render method if the success param is set.

**Comment by lb-** [comment]
@strindhaug & @gasman 

We need a way to ensure that the form_submission instance can be passed to the context of the landing page.

As per this outstanding item in #2833
> The FormSubmission instance should then be passed to the render context for the "landing page".


## Suggested Approach (without redirect)

Assuming we go with PR #4024 (which is not the redirect approach), the `render_landing_page` method should also accept a parameter `form_submission`.

Which should be generated by updating the line:
`self.process_form_submission(form)` 
to
`form_submission = self.process_form_submission(form)` 

Then 
`return self.render_landing_page(request, *args, **kwargs)`
to
`return self.render_landing_page(request, form_submission=form_submission, *args, **kwargs)`

Finally, the context should be updated in the render_landing_page return render eg.

```
 # TODO: It is much better to redirect to it
context = self.get_context(request)
context['form_submission'] = form_submission
    return render(
        request,
        self.get_landing_page_template(request),
         context
        )
```

**Comment by lb-** [comment]
Closing as redirecting does not provide a reliable way to send context and redirecting with url params will be different for every use case.

Instead #4024 provides a way for developers to override the `render_landing_page`.

**Comment by BigE** [comment]
I came across this issue trying to accomplish something similar. In my situation, I'm wanting to change the URL for tracking purposes through Google Tag Manager rather than redirecting for some other purpose. My solution to this is actually using the [RoutablePageMixin](https://docs.wagtail.io/en/stable/reference/contrib/routablepage.html) with the form page and creating a new routeable method for the submission. Inside the form template, I then set the action of the form to the submit route so the URL changes when the form is submitted. My issue now, is that the URL changes even if the form isn't valid... which is not quite what I want, but its a step in the right direction! I'm just hoping this will help someone else looking for something similar.

`class MyFormPage(AbstractEmailForm, RoutablePageMixin):

    @route(r'^submit/')
    def submit(self, request, *args, **kwargs):
        return self.serve(request, *args, **kwargs)`

`<form action="{% routablepageurl page 'submit' %}">
</form>`
