### ISSUE TITLE
StructValue rendering may cause stack overflow

### ISSUE THREAD

**Issue by dnsl48** [wagtail/wagtail#2874]
Environment:
- django >= 1.9
- logging level = debug

Current implementation of `wagtail.wagtailcore.blocks.StructValue` contains method `__str__` trying to render the block.
https://github.com/torchbox/wagtail/blob/v1.5.3/wagtail/wagtailcore/blocks/struct_block.py#L180

However, since `Django 1.9` in case we have an unbound (unresolvable) variable in the block's template (which django template engine casts to an empty string by default), `django.template.base` module tries to write debug level logs about that.
https://github.com/django/django/blob/1.9/django/template/base.py#L919

Default python `logging.Formatter` implementation tries to write stack trace in logs which invokes StructValue rendering again. It happens with python 2.7, 3.4 and 3.5 as well. https://github.com/python/cpython/blob/2.7/Lib/logging/__init__.py#L439

Endless recursion causes stack overflow.

**Comment by sam-mi** [comment]
Is there any plan to resolve this or further details on how to get around this issue? I have code that looks perfectly valid, it runs in another project, it also runs fine with I return an empty string from the __str__method mentioned above however leaving it as is causes a stack overflow. What would cause the unresolvable variable in the template? It seems to be occurring even when the template is empty.

**Comment by FlipperPA** [comment]
Just some more information: here's the trigger that Wagtail doesn't seem to be playing nicely with: https://github.com/django/django/blob/stable/1.11.x/django/utils/encoding.py#L58

If you're using the latest Django Debug Toolbar with Wagtail, I've put together a monkey patch, but it doesn't seem like a PR would be appropriate since this problem is Wagtail-specific: https://github.com/FlipperPA/django-debug-toolbar/commit/e68cfa509566bf5332c37f03c0fd9753a873d491
