### ISSUE TITLE
Inserting link on image in Hallo editor doesn't work

### ISSUE THREAD

**Issue by jossingram** [wagtail/wagtail#3023]
### Issue Summary

Inserting link in editor doesn't work sometimes. Trying to make an image a link.
### Steps to Reproduce
1. Inserting link in editor, browsing to  page through the wagtail page chooser, 
2. selecting a page. Page can't be selected, dialog stays open. 

JS error = Uncaught HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': Only one element on document allowed.
### Technical details
- Python version: Run `python --version`.
- Django version: 1.9
- Wagtail version: 1.5.3
- Browser version: Chrome

**Comment by gasman** [comment]
Hi @jossingram,

Are you by any chance using a custom image format that adds extra markup to the image, beyond the `<img>` tag (e.g. a caption)?

While I can't reproduce this issue as described on a default Wagtail install, I see the same error [has been previously reported](https://github.com/torchbox/wagtail/pull/1075#issuecomment-89169810) when using media embeds, which I _can_ replicate - I suspect it's related to having a non-editable chunk of HTML embedded within the rich text area.

I've also encountered another strange glitch which is possibly another manifestation of the same thing:
* insert an image into rich text
* _single_ click on the image so that the rich text toolbar reappears but the text cursor doesn't show
* insert a link, or another image
* the content ends up inserted inside the preview button in the page footer

**Comment by jossingram** [comment]
We use theses custom image formats:

from wagtail.wagtailimages.formats import Format, register_image_format,unregister_image_format

unregister_image_format('left')
unregister_image_format('right')
unregister_image_format('fullwidth')
register_image_format(Format('fullwidth', 'Standard', 'richtext-image standard-image', 'width-500'))
register_image_format(Format('largewidth', 'Standard Large', 'richtext-image standard-image', 'width-750'))
register_image_format(Format('smallwidth', 'Standard Small', 'richtext-image standard-image', 'width-300'))
register_image_format(Format('right', 'Float Right', 'richtext-image wag-image-right', 'width-500'))
register_image_format(Format('left', 'Float Left', 'richtext-image wag-image-left', 'width-500'))
register_image_format(Format('rightlarge', 'Float Right Large', 'richtext-image wag-image-right', 'width-750'))
register_image_format(Format('leftlarge', 'Float Left Large', 'richtext-image wag-image-left', 'width-750'))
register_image_format(Format('rightsmall', 'Float Right Small', 'richtext-image wag-image-right', 'width-300'))
register_image_format(Format('leftsmall', 'Float Left Small', 'richtext-image wag-image-left', 'width-300'))
register_image_format(Format('thumby', 'Thumbnail', 'richtext-image wag-thumbnail', 'fill-150x150'))

**Comment by jossingram** [comment]
I'm not able to recreate the preview button bug though.

**Comment by thibaudcolas** [comment]
Adding a link on an image is a common limitation of rich text editors built with `contenteditable`. We are replacing Hallo with a new editor, where this won't work either, but it won't crash the editor.

I would suggest using Streamfield to structure content if this is a common use case on your site.
