### ISSUE TITLE
js_initializer for InlinePanel

### ISSUE THREAD

**Issue by danni** [wagtail/wagtail#3204]
StreamField blocks have the really useful `js_initializer` property that lets you call a Javascript function when you add a new block to set up dynamic forms. We'd like to use this for `InlinePanel` as well.

**Comment by gasman** [comment]
Hi @danni,

If the Javascript function is for applying behaviour to a specific field in the inline panel, then `wagtail.utils.widgets.WidgetWithScript` provides a common pattern for doing that - see [`AdminAutoHeightTextInput`](https://github.com/wagtail/wagtail/blob/4f5ffe98bc4186e5a356494dff4efc517b169c1e/wagtail/wagtailadmin/widgets.py#L23) for a simple example. (Internally, this simply places a `<script>` block alongside the widget HTML so that it gets executed each time the HTML is placed on the page - which feels a bit cheap-and-cheerful, but does the job nicely...) Would this work for you?

**Comment by gasman** [comment]
Closing for now - can reopen if we find a scenario that isn't handled by WidgetWithScript.
