### ISSUE TITLE
Make timezone configurable on a per-user basis

### ISSUE THREAD

**Issue by mevinbabuc** [wagtail/wagtail#3205]
### Issue Summary
These are my timezone settings:
```
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
```
The server time is in UTC and I have pytz installed

Context:
The user is in India and in the "Go live date/time:", selects the Indian time 15:30 in the datepicker.
The time gets saved in the database as 15:30 UTC, which is incorrect. The time should have been converted to the UTC time 8:30 and then saved.

This causes the publish schedule pages feature to break as its checking for 15:30 and not 8:30 which is the server time.

Is there some setting or something that I'm missing or is the Datetime widget not time aware.

### Technical details

* Python 3.4
* Django version: 1.8.11
* Wagtail version: 1.7

@gasman @kaedroho

**Comment by gasman** [comment]
Hi @mevinbabuc - I think you need to set `TIME_ZONE` in the Django settings to Indian time. Otherwise, when the user selects 15:30, there's no way that the server can possibly know that 15:30 is supposed to be interpreted as Indian time rather than UTC. Can you give this a try, and let us know if it works?

**Comment by mevinbabuc** [comment]
This works, but we have users across geographies, in US, Canada and India, so this setup does not work nor does changing the server time.

**Comment by mevinbabuc** [comment]
Or we have to setup the expectation that the time should be entered in UTC format, which is painfull for end users

**Comment by Proper-Job** [comment]
@mevinbabuc I don't think this is a wagtail specific problem. We had a similar issue with a non wagtail Django project. The solution was to add time zone information to the user object and then actively setting the time zone on each request to the user's time zone. We also added dynamic help text to each date time field in the forms indicating which time zone is used to parse the input.

**Comment by gasman** [comment]
Yep, I think this really points to the need for a user-specific timezone setting in the Wagtail `UserProfile` model (which currently just contains email notification preferences).

**Comment by linuxsoftware** [comment]
I am working on a pull request to add per-user configuration of the current time zone to Wagtail.  I have copied/based my change on Daniel Chimeno's  #3306 work to configure the admin language.  I have got something working, but I am sure it still needs more work.

A few issues/questions:

- The time zone is activated in a new middleware.  I know that is a problem, can someone suggest a better place to do it?  Unlike the language activation which only applies for admin pages I think the time zone should apply to content pages as well.  (By default anyway, the developer might want to do something different there.)  If it was only for the admin pages I would have done the activation in the require_admin_access decorator as Daniel did.  My middleware code is straight from the Django [docs](https://docs.djangoproject.com/en/2.0/topics/i18n/timezones/#selecting-the-current-time-zone), it probably requires better error handling if that is how we are going to do it?  BTW: I only show the option to change the time zone if the TimeZoneMiddleware is installed.

- Should time zone names be localized?  I found a library [l18n](https://bitbucket.org/tkhyn/l18n) which does this, but it does yet cover all the Wagtail languages, and I can see having a separate translation scheme just for time zones is messy.  So, should all 433 time zones from pytz.common_timezones be listed out and marked for gettext?  Or just leave them in English? 

- I wasn't sure where the documentation for this should go.  It didn't seem to me to belong under Advanced Topics / Internationalisation.  (Maybe it does?).  I created a new page for Account Settings and added it there for now. 

- timezone or time zone?  I have followed the dictionary and the Django TIME_ZONE setting and written it as two words, but it is also commonly written as one word, e.g. in the title of this issue :-)

- Should I look at adding dynamic help text stating the current time zone on the DateTimeField (as suggested by Moritz Pfeiffer)?

**Comment by gasman** [comment]
Excellent work, thanks @linuxsoftware!

I think it's better for the time zone setting to only apply to admin pages - we try to stay out of the logic of front-end pages as far as possible. I suspect it's only a minority of Wagtail sites that have a concept of front-end user logins at all, and for the ones that don't, I'd say this is more likely to manifest itself as unwanted 'magic' behaviour ("sometimes dates show up wrong while you're logged in to Wagtail, and you have to log out to see the right ones...") rather than a desirable feature. Better to leave it as something that users have to specifically implement, I think.

Regarding localisation, I think it's fine to rely on the l18n library and fall back on English for any languages not covered. Any translators who are feeling industrious enough to translate 433 time zone names should contribute them to the l18n project, where they'll be more widely useful :-)

Let's go with 'time zone' as two words - I think that's more common in general usage, rather than programming lingo.

**Comment by linuxsoftware** [comment]
Thanks!  I will change the time zone setting to be for the admin pages only, activating it in  require_admin_access.

**Comment by gasman** [comment]
Completed in #4461.
