### ISSUE TITLE
Elasticsearch backend indexes draft updates of existing pages

### ISSUE THREAD

**Issue by nfletton** [wagtail/wagtail#3239]
### Issue Summary

When saving a draft version of an existing live page the Elasticsearch backend reindexes the page with the draft content. The reindexed content will potentially cause frontend search results to include the page if the search query matches the draft content.

I'm using the following search query in my view:

   search_results = Page.objects.live().search(search_query)

New content that is saved as draft is not an issue since the live() filter excludes it.

### Steps to Reproduce

1. Edit an indexed field of an existing published page
2. Insert a unique term in the indexed field
3. Click 'Save Draft'
4. On the fontend search for the unique term.
5. The editted page will be returned in the results

I can see the value of having the draft content indexed on the Wagtail backend but since the frontend shares the same index, that can be a problem.

### Technical details

* Python version: 3.5.2.
* Django version: 1.10.4.
* Wagtail version: 1.8.
* Elasticsearch: 5

**Comment by gasman** [comment]
Thanks for the report @nfletton!

It looks like this is happening because the `Page.save_revision()` method [performs a save of the page model](https://github.com/wagtail/wagtail/blob/0e9c255b034ce4bdef5b265021833790fd813ed9/wagtail/wagtailcore/models.py#L710) in order to update the `latest_revision_created_at` and `has_unpublished_changes` fields, which in turn triggers [the post_save signal handler](https://github.com/wagtail/wagtail/blob/0e9c255b034ce4bdef5b265021833790fd813ed9/wagtail/wagtailsearch/signal_handlers.py#L8) to reindex the page.

The page instance received by the signal handler is the draft version, and so it goes ahead and indexes that version, even though the corresponding `save` didn't actually write the page content to the database.

The post_save signal [has access to the `update_fields` parameter](https://docs.djangoproject.com/en/1.10/ref/signals/#post-save), so a possible fix would be to check `update_fields is not None` and if so, fetch a fresh copy of the page record from the DB to be indexed instead of the draft one. (If we wanted to be really clever, we could compare `update_fields` against the model's `search_fields` and skip the operation entirely if there's nothing new to be indexed - but that's probably overkill...)
