### ISSUE TITLE
Warn an admin before they remove their own admin access

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#3244]
As a test I just changed my own permissions and removed my administrative access. The action was successful but I was then shown a "Sorry, you do not have permission to access this area." message and I have no way of changing it back. 

If an admin removes their own admin access it would be good if they at least gave a warning that the action can't be reversed and permissions will be greatly restricted to avoid people locking themselves out. 
![screen shot 2016-12-21 at 17 31 48](https://cloud.githubusercontent.com/assets/7290588/21399499/d99aed68-c7a3-11e6-80f4-7dda8379b558.png)

**Comment by strindhaug** [comment]
It's generally a good idea to prohibit users from modifying their own access permissions at all, both because of this, and because it hypothetically could also be a way for a user to escalate their own privileges (assuming there is some other flaw/bug allowing this).

And it's much easier to safely verify that `userToModify != currentUser` than checking whether there still would be some other admin left in the system if current user demotes theirself etc.

**Comment by gasman** [comment]
Resolved in #3502 - users can no longer unset their own is_superuser (or is_active) flag.
