### ISSUE TITLE
Error running `npm run build` when trying to compile static assets

### ISSUE THREAD

**Issue by nutztherookie** [wagtail/wagtail#3253]
I get
    
    > wagtail@1.0.0 build /home/nutz/tmp/wagtail
    > gulp build; webpack --progress --colors --config webpack.prd.config.js
    
    module.js:472
        throw err;
        ^
    
    Error: Cannot find module 'internal/fs'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at evalmachine.<anonymous>:17:20
        at Object.<anonymous> (/home/nutz/tmp/wagtail/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
    Hash: 7dd35da8de6e5a085038  
    Version: webpack 1.13.0
    Time: 3861ms
                                                          Asset     Size  Chunks             Chunk Names
    wagtail/wagtailadmin/static/wagtailadmin/js/wagtailadmin.js   708 kB    0, 1  [emitted]  wagtail/wagtailadmin/static/wagtailadmin/js/wagtailadmin
        ./wagtail/wagtailadmin/static/wagtailadmin/js/common.js  3.61 kB       1  [emitted]  common
        + 165 hidden modules

when trying to run `npm run build`.

I also get 

    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents):`
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

when running `npm install`.

I'm on an Archlinux machine with
* npm -v == 4.0.5 
* node -v == v7.3.0

Any help much appreciated. Thanks

**Comment by nutztherookie** [comment]
Downgrading to node 6.9.1 helped me with this.

-> Maybe http://docs.wagtail.io/en/latest/contributing/developing.html should list the working node/npm versions?

**Comment by thibaudcolas** [comment]
I'm not sure why this would fail with node 7. The `npm WARN` for `fsevents` is expected – fsevents is OSX only.

Downgrading is the best option for now – we are discussing improving the documentation / enforcing specific versions in #2730.

**Comment by gasman** [comment]
I think this is because gulp depends on an ancient version of graceful-fs (or, at least, did at the time we created `npm-shrinkwrap.json`):

gulp 3.8.11
depends on vinyl-fs 0.3.14
depends on glob-watcher 0.0.6
depends on gaze 0.5.2
depends on globule 0.1.0
depends on glob 3.1.21
depends on graceful-fs 1.2.3

This looks familiar... I think this was one of the troublesome dependencies I kept running into when creating `npm-shrinkwrap.json` in the first place (#2522). Digging around a bit more, it looks like Gulp support on Node 7 still hasn't been properly resolved:

https://github.com/gulpjs/gulp/issues/1571
https://github.com/gulpjs/gulp/issues/1843

For now I'll update the docs to specify Node 5 or 6.
