### ISSUE TITLE
Change Page objects order from default to 'title'

### ISSUE THREAD

**Issue by maxg203** [wagtail/wagtail#3258]
### Issue Summary

I suggest changing the Page model sort order from the default behaviour to sorting by 'title'. This should sort  Page objects alphabetically (ascending), which I would argue is more useful to most people. My suggested Wagtail modification would be to change the value returned by the `get_queryset` method on the manager for the Page model. I assume Wagtail uses the default behaviour for the `get_queryset` method currently.

If you agree with this change - great, I'd be more than happy to make it for you.

If not - I'd be very interested to hear your argument against this change.

Either way, I believe the docs could be more clear in this area and again, I'd be happy to make any changes we deem appropriate.

Docs to improve: http://docs.wagtail.io/en/v1.8/topics/pages.html#page-queryset-ordering

### Steps to Reproduce

1. Enter shell
2. Get Page objects (assuming you have some) from the Page model, note the order is (I believe) default Django

### Technical details

* Python version: 2.7.12
* Django version: 1.9
* Wagtail version: 1.7
* Browser version: Chrome 54 http://whatsmybrowser.org/b/EOT46X0

**Comment by gasman** [comment]
Hi @maxg203,
The current 'path' ordering makes it possible for editors to set the ordering of pages manually, using the leftmost column of the explorer listing. I'll readily admit that there are some serious shortcomings of this feature as it stands (including the discoverability of it, and the fact that manual ordering is less desirable than automatic in all but the smallest of sections) - but nevertheless it exists, and it wouldn't really make sense to have this feature and it _not_ be the default order.

There's a proposed approach for dealing with this at #882 - under this plan, it'll be possible for individual sections of the tree to specify their own ordering, whether that's manual, alphabetical, or something else entirely.

**Comment by maxg203** [comment]
@gasman That makes sense. Thank you for that explanation. Do you think it would at least be beneficial to better document custom ordering? So in other words, in the custom page manager example in the docs, add (or extent an existing) example of how one might implement custom ordering by overriding the `get_queryset` method? This is what I'm doing now, but it took me a while to find that solution yesterday which leads me to believe the docs could be improved in this way? Just a suggestion.

**Comment by gasman** [comment]
@maxg203 Sure, that sounds like a good idea!

**Comment by iaindillingham** [comment]
I'm a bit confused @gasman -- does overriding the path ordering, by using a custom manager for example, break the user-defined ordering? When we tried this, we didn't notice any unexpected side-effects. Should we look harder?

**Comment by gasman** [comment]
@iaindillingham Defining a custom manager _in addition to_ the default one should always be safe:

    class BlogPage(Page):
        objects = PageManager()
        objects_by_date = OrderedPageManager()

I'm not specifically aware of anything that will break if you override the ordering on the _default_ manager, but I wouldn't be 100% confident that it's safe either. (The documentation for django-treebeard states that [managers must inherit from Treebeard's base manager](https://tabo.pe/projects/django-treebeard/docs/tip/caveats.html#overriding-the-default-manager) - which is the case for `PageManager` - but that implies that Treebeard has certain unwritten expectations about how the manager will behave, and that may or may not include ordering.)

**Comment by iaindillingham** [comment]
Thanks @gasman. The Treebeard docs are surprisingly terse when it comes to overriding the default manager, which is what @maxg203 and I did here. However, I believe Wagtail uses a Materialized Path tree. Whilst this requires [a custom queryset](https://tabo.pe/projects/django-treebeard/docs/tip/mp_tree.html#treebeard.mp_tree.MP_NodeQuerySet), it does so only because it overrides the delete method.

We're actually overriding the default manager because we wanted to sort items in a `FieldPanel` that references a `ForeignKey` alphabetically. Overriding the default manager seemed the best approach. Could you suggest an alternative?

**Comment by gasman** [comment]
Hi @iaindillingham - one possible alternative is to set up the sorted queryset in the `limit_choices_to` option of the ForeignKey:

    def blog_pages_by_title():
        return BlogPage.objects.sort_by('title')

    ...
        blog_page = ForeignKey(BlogPage, limit_choices_to=blog_pages_by_title)

It may well be that I'm being overly paranoid in avoiding setting the default manager's ordering, though.

**Comment by maxg203** [comment]
What are we accidentally changing by setting the default manager's ordering? I believe it to change nothing (looking at Treebeard source, see link).

If we are changing anything here, then I can see how it may not be a good idea to override the default manager in this way. As far as I can tell though, the fact that Treebeard needs to override the delete method should not matter in this case and as such it would be acceptable to change the default manager's ordering to whatever is deemed most appropriate (title?) without _any_ further consequence. 

The only potential caveat here that I can think of could be that Treebeard does something in the source code that is not documented. It does not. [Source [see lines 44-106]](https://github.com/django-treebeard/django-treebeard/blob/1fa535e6f8f5171669a8a7d4d4491993cadef6c5/treebeard/mp_tree.py#L106)

Finally, to address concerns of whether this is a Treebeard issue, I believe the `.order_by('path')` is fine and that the `.order_by('title')` should be introduced specifically at the Wagtail `PageManager` level as the `Page` model is where the `title` field is initially defined.

**Comment by gasman** [comment]
My concern is that there could be something elsewhere within Treebeard's implementation that implicitly relies on querysets being returned in path order. For example, when inserting a new node into the tree, it could conceivably allocate the path for the new node by reading `parent_node.get_children().last().path` and incrementing the result. That's a contrived example, and the more I think about it, the more unlikely it seems that there's anything like that lurking in the Treebeard code... but without reviewing the entire codebase I couldn't give a 100% guarantee that it's safe.

If you're confident enough in your understanding of Treebeard's implementation (and your ability to troubleshoot if any issues do come up...) then by all means go ahead and override the default manager in your page model. However, changing the default in Wagtail at the `Page` level isn't really an option, since there's existing functionality in Wagtail that depends on the current `path` ordering (namely, the ability to order pages manually in the admin, and have that respected in front-end queries - e.g. menus - that don't specify an ordering of their own) and plans to develop this further in future (#882, which will allow the `path` ordering to be kept in sync with title, date, or whatever else is appropriate for a given parent page). We'd be painting ourselves into a corner if we changed the Page-level default at this point.

**Comment by iaindillingham** [comment]
Just for any future readers of this thread, unfortunately the `limit_choices_to` option can't be used to sort the list, although it can be used to filter the list. Either way, it also needs a slight tweak to return a `Q` object rather than a `QuerySet`. For example...

```
def blog_pages_by_title():
    qs = BlogPage.objects.sort_by('title')
    return Q(id__in=qs.values_list('id', flat=True))
```

As I say, unfortunately this doesn't sort the list. However, filtering the list might be useful...

```
def blog_pages_by_title():
    qs = BlogPage.objects.filter(title__startswith='A')
    return Q(id__in=qs.values_list('id', flat=True))
```
