### ISSUE TITLE
Translation for 'file' ignored in WagtailImage

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#3268]
### Issue Summary

The translation of **file** in **wagtailimages** is being ignored in the **edit image view**.

I had a look at the original model and the form and only the **verbose_name** of the **file field** contains _('file'); seems ok.

When changing it temporarily to _('heeeeeelp') the view keeps displaying “file”.

### Technical details

* Python version: 3.5.0..
* Django version: 1.01.2.
* Wagtail version: 1.8.

**Comment by strindhaug** [comment]
Normally the formfield() method in django.db.models.fields.Field sets the `label` using `capfirst` of the `verbose_name`. But since wagtail/wagtailimages/forms.py overrides and initializes the WagtailImageField directly the `label` value is never set and as far as I can understand it falls back to capfirst'ing the fieldname itself.

I fixed it by adding the verbose_name capfirsted when initializing the WagtailImageField.

**Comment by gasman** [comment]
Fixed in #3396
