### ISSUE TITLE
Add striptags to page.get_admin_display_title in template

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#3328]
With the new get_admin_display_title method it is possible to return html-code.
This code should however not be used in the browser title.
Therefor I suggest to add the striptags tag to the folowing template:

wagtailadmin/templates/wagtailadmin/pages/edit.html

{% block titletag %}... with title=page.get_admin_display_title|striptags

**Comment by gasman** [comment]
Hi @robslotboom - thanks for the suggestion! Unfortunately, I don't think it fits with Django's standard rules for preventing XSS attacks, where all strings are assumed to be 'unsafe' (= will be escaped when output in templates) unless we specifically take steps in the code to mark it as an HTML string (e.g. by using `{{ foo|safe }}`).

The result of `get_admin_display_title` is **not** considered an HTML string (because that would mean that any occurrence of `<`, e.g. `"I <3 Wagtail!"`, must be interpreted as an HTML tag - there's no such thing as "a string which may contain HTML"). Therefore, the correct behaviour is for HTML-like characters to be escaped and displayed as literal `<` `>` `&` characters wherever they are used. I believe Django's template engine should take care of this automatically - if you find any places where the output of `get_admin_display_title` _is_ interpreted as HTML, then that's a bug. (If so, please report it here!)

**Comment by robslotboom** [comment]
Hi @gasman - thanks for the explanation. And no I didn’t find any html output. I created it myself using the following:
```
def get_admin_display_title(self):
		if self.subtitle:
			return format_html(
				'<span style="font-weight: 600;">{}</span> <span style="font-weight: normal;">{}</span>',
				mark_safe(self.cleaned_title),
				mark_safe(self.cleaned_subtitle)
			)
		else:
			return format_html(
				'<span style="font-weight: 600;">{}</span>',
				mark_safe(self.cleaned_title)
			)
```
