### ISSUE TITLE
Revision comparison view should compare StreamFields structurally

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3368]
Currently the revision comparison view [treats StreamFields as equivalent to rich text fields](https://github.com/wagtail/wagtail/blob/5aa8e00d77d20060f75b7ca65e28ef502c54245c/wagtail/wagtailadmin/compare.py#L60), and displays comparisons based on the rendered (and tag-stripped) HTML. This is far from ideal - StreamFields can contain a vast amount of structured content, not necessarily text-based (for example, the current comparison would not show a change to an ImageChooserBlock) and the comparison view should reflect that.

Doing the comparison _well_ would probably be a major undertaking (e.g. ensuring that a change to a single field of a StructBlock is displayed as a change to that one field, rather than a replacement of the entire field) but as a first pass, they should be handled similarly to InlinePanels so that changes are displayed in terms of insertions / deletions / updates of top-level blocks.

**Comment by atbaker** [comment]
Just chiming in with a +1 here.

I wonder if a smarter compare would also improve the feature's performance? 90%+ of our content is in StreamFields and comparing revisions often takes a long time for us - sometimes longer than 90 seconds.

**Comment by chosak** [comment]
It looks like this will be fixed by #4933 (ping @kaedroho), but I encountered a related bug that seems to fit here due to the use of rendered block HTML in comparisons.

Specifically, custom StreamField blocks that rely on parent template context variables (for example `page`) don't have those variables when they are rendered in the diff view. Consider a custom StreamField block that renders differently depending on the type of page that it is on. The StreamField docs [imply](http://docs.wagtail.io/en/v2.0/topics/streamfield.html#template-rendering) that using `{% include_block %}` and relying on parent template variables is a valid thing to do in block templates. So a developer might write their block template (or custom `get_context`) assuming that the `page` variable will be available, given that the block will only ever be inserted and rendered on pages that use `{% include_block %}`.

Unfortunately, because the `__str__`-based block rendering ([here](https://github.com/wagtail/wagtail/blob/5e5484d4d7d3fec0b860826a07903165ed6dfb31/wagtail/core/blocks/stream_block.py#L466)) ends up rendering blocks with an empty context ([here](https://github.com/wagtail/wagtail/blob/5e5484d4d7d3fec0b860826a07903165ed6dfb31/wagtail/core/blocks/base.py#L422)), that variable doesn't exist, and can cause e.g. a `ValueError` on the compare view.

From #4933 it looks like the eventual goal is to remove the use of block template rendering in the diff view, in which case this will no longer be a problem. As a workaround for now, block templates could perhaps handle a fallback case where certain variables aren't available, but it'd be nice not to have to do this. If block template rendering in diffs is going to stick around, it'd be good to add a note in the StreamField docs mentioning this gotcha with relying on upstream variables.

**Comment by gasman** [comment]
Completed in #4933
