### ISSUE TITLE
Adding hooks to customize choosers querysets.

### ISSUE THREAD

**Issue by Gagaro** [wagtail/wagtail#3371]
This would be a hook similar to `construct_explorer_page_queryset`.  We could have three new hook: `construct_page_chooser_queryset`, `construct_image_chooser_queryset`, 
`construct_document_chooser_queryset`, which would respectively be located in:

https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/views/chooser.py#L53
https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailimages/views/chooser.py#L41
https://github.com/wagtail/wagtail/blob/master/wagtail/wagtaildocs/views/chooser.py#L35

Current queryset construction could be reimplemented using these hooks.

What do you think about that?

Thanks

**Comment by gasman** [comment]
Hi @Gagaro,
Please see https://github.com/wagtail/wagtail/pull/3203#issuecomment-265503416 for my thoughts about `construct_explorer_page_queryset` - in summary, I think it was a bad idea (too low-level, and makes it impossible to guarantee that Wagtail will behave consistently across the admin).

However, `construct_explorer_page_queryset` probably won't be going away any time soon, so I can see the value of having corresponding hooks for the choosers - and since these queries all work the same way, it doesn't really risk breaking anything that isn't broken already (unlike #3203). :-) So, I would (reluctantly) accept this.

**Comment by Gagaro** [comment]
I don't really like it either, but I don't see a better way to do it with what we have in wagtail/django. I'll work on a PR.

**Comment by gasman** [comment]
Implemented in #3374
