### ISSUE TITLE
Document myimage.get_rendition()

### ISSUE THREAD

**Issue by shacker** [wagtail/wagtail#3373]
When generating image thumbnails urls for  an API endpoint, I followed the docs on [Generating dynamic image URLs in Python](http://docs.wagtail.io/en/v1.8.1/advanced_topics/images/image_serve_view.html#generating-dynamic-image-urls-in-python), which led to puzzlement over why the generated images always returned 200, rather than 304, which led to [this](http://stackoverflow.com/questions/41641910/wagtail-dynamic-image-generation-and-caching) StackOverflow question and its answer, which involved decorating the wagtail images URL definition with `cache_control`... all of which worked, but turned out to be needlessly complicated.  I've since realized I could have simply used:

`shop['img_url'] = image.get_rendition('fill-300x186|jpegquality-60').url`

which avoids the original problem, lines of unneeded  code, and the URL decoration. 

`get_rendition()` is undocumented as far as I can tell (aside from one reference in an unrelated place in the docs). It should be documented on that page, possibly even replacing the whole section on Generating dynamic image URLs in Python.

**Comment by shacker** [comment]
@jjanssen If I submit a PR for this documentation change will it be considered?

**Comment by jjanssen** [comment]
Hi @shacker, I think we can benefit from documenting `get_rendition`, but I'm not sure about replacing the whole section on Generating dynamic image URLs. I think it applies to different use-cases whereas `get_rendition` is the most basic of the two.

What are your thoughts @gasman?

**Comment by gasman** [comment]
As I recall, the original motivation for the dynamic image URL feature was to provide an API endpoint that external apps (not necessarily Python/Django ones) could use to access images in Wagtail's image library. The signature code was put in place so that we weren't automatically making the full-res images available to anyone who can fiddle a URL. (I'm not sure why we ended up adding the human-facing 'generate a URL' view in the admin - I suspect that may have been a case of miscommunication during the spec process...)

I think the addition of `ImageRenditionField` to the API (#3361) will cover 99% of the use-cases of the image URL generator. I suggest that we get #3361 merged, then move the image URL generator to a contrib app that's marked as deprecated in the docs. (Longer term, we ought to consider moving it, and [wagtailmedusa](http://docs.wagtail.io/en/v1.9/reference/contrib/staticsitegen.html), out of contrib and into external packages, so that contrib doesn't turn into "where apps go to die" :-) ) Separately to that, yep, we should definitely document `get_rendition` as the preferred Python-side API for generating image renditions.

**Comment by shacker** [comment]
Thanks @gasman and @jjanssen - documentation for for get_rendition() is in PR. I cross-linked to it from both the `image` template tag docs and the dynamic image serving docs. Let me know if this needs rearranging. I'll leave other todo items in @gasman's comment to more experienced folks.

**Comment by lb-** [comment]
@gasman 

I might be missing something - is this all resolved now with #3388 being merged?

It also appears that deprecation of `wagtailmedusa` has been completed but I don't really understand the URL generator part, does that refer to a planned removal of `Dynamic image serve view` as documented here: http://docs.wagtail.io/en/v1.13.1/advanced_topics/images/image_serve_view.html

**Comment by gasman** [comment]
@lb- Yep, I think #3388 resolves this - the question about whether to move the dynamic image serve view into a contrib module is out of scope for this issue (and while I'd be in favour of that, I'm not sufficiently bothered about it to create a ticket :-) )

**Comment by lb-** [comment]
Sounds good 👍
