### ISSUE TITLE
 [docs] Make autobuild regenerate docs builds when saving outside vagrant

### ISSUE THREAD

**Issue by chimeno** [wagtail/wagtail#3378]
Currently when running ``autobuild.sh`` inside the vagrant and making docs changes outside of it, there is not build at all.

I've fixed with:
 - upgrading watchdog from 0.8.3 to the git master branch in https://github.com/gorakhargosh/watchdog
- add a ``--debug-force-polling`` to autobuild.sh: ``watchmedo shell-command --debug-force-polling --patterns="*.rst" --ignore-pattern='_build/*' --recursive --command='make html; echo "Waiting for more changes..."' ``

I could make a PR, but I don't see when the watchdog library is installed in order to upgrade it.

**Comment by gasman** [comment]
I've never used autobuild.sh - I never knew it existed at all actually - and it looks like it was added before we had any formal / documented build environment, so it's very likely that watchdog isn't installed at all.

I don't think it should be added to [Wagtail's own doc dependencies](https://github.com/wagtail/wagtail/blob/15cd1b43cb0de0fdd11ca07cc6b83b2c77fbd99d/setup.py#L55), because it's non-essential and adds new installation requirements (LibYAML). I think it would be most appropriate to add it to the provision.sh script in vagrant-wagtail-develop.
