### ISSUE TITLE
Collection Hierarchy Support?

### ISSUE THREAD

**Issue by trumpet2012** [wagtail/wagtail#3380]
Are there any plans to better support collection hierarchies? 

We would like to be able to create and show nested collections in order to better organize our media. 

I know that Collections can be nested under one another programmatically, however there is currently no way for the users to create and view collections as a hierarchy instead of a flat structure.

I saw this question was previously raised #2800. The third-party suggested  https://github.com/anteatersa/Wagtail-Image-Folders isn't a viable solution. It appears that they simply pulled out the wagtailimages app from an old version of wagtail and added their own code to it. 

Thanks!

**Comment by trumpet2012** [comment]
Is this something that you guys would like to have as part of Wagtail, if I were to work on it and do a pull request?

**Comment by gasman** [comment]
Hi @trumpet2012 - Yes please! As you note, collections are already hierarchical at the data model level (via django-treebeard), and I believe the business logic for permissions propagating down the tree should be in place (since the behaviour for the root collection vs. other collections relies on it), so the remaining work would be to present the hierarchy to the user in the settings -> collections and image/document chooser views.

**Comment by adsk2050** [comment]
This can be another way of solving #4488 . If we are able to create a collection for each user, and give the user access to contents of only that collections, we will be able to limit their access to the image and document database. @robslotboom . Also, If someone knows how to assign collections specific to the user, could you please elaborate...

**Comment by cnk** [comment]
A UI for managing nested collections has now been merged into master and will be in the 2.11 release in a few months.
