### ISSUE TITLE
Checkbox to toggle "noindex" for pages

### ISSUE THREAD

**Issue by kno10** [wagtail/wagtail#3426]
It would be good to have a "set noindex meta" flag, to be able to disable indexing of single pages easily.
Similar to the "show in menu" toggle, and simply inserts
```<meta name="robots" content="noindex" />```
It would fits the "promote" tab, somehow, as an "anti promotion".
I am aware that this is not a "security" feature; but sometimes some minor page just shouldn't be indexed even though public.

**Comment by gasman** [comment]
Hi @kno10 - thanks for the suggestion!

Unfortunately I don't think this is going to be possible within the current design of Wagtail: we could add the flag to the basic `Page` model, but Wagtail deliberately doesn't have any control over the HTML of your front-end templates, so there's no way to ensure that the relevant tag code is in place on the base template. (We could include it in the default base.html in the `wagtail start` project template, but there's no guarantee that a project is actually using that - if they aren't, they'll end up with a checkbox in the admin that has no effect.)

Once we've implemented swappable page models (#3282), it will be possible for us to add this flag as part of the default project template, so that people starting a new project get this feature "for free" (and existing projects are unaffected). Meanwhile, there is of course nothing to stop you from adding this flag (and the relevant template logic) to your own page models within your project.

**Comment by kno10** [comment]
The same applies to e.g. the existing `search_description` and `seo_title` fields.
They also rely on compatible templates to work.

Most likely, also the "show in menus" is similar, isn't it?

**Comment by gasman** [comment]
> The same applies to e.g. the existing `search_description` and `seo_title` fields.
They also rely on compatible templates to work.

True - I'm not a huge fan of having those as standard fields either :-) At least with those fields, there's a level of interpretation about what they mean on the front-end - for example, `search_description` might just be used for the site's own search results, rather than exposed through the meta description tag.

The "noindex" flag is different to those, because it's promising a specific behaviour that developers are then required to incorporate into their sites - if they don't, the site will appear to be broken, in a potentially damaging way. (It doesn't matter too much if an editor fills in a search description that turns out never to be used; it definitely does matter if an editor was expecting their page to be hidden from Google, but it ends up appearing there.)

**Comment by mikemonteith** [comment]
@gasman Would it be more acceptable to implement this with the `X-Robots-Tag: noindex` http header instead?
That way, Wagtail wouldn't be opinionated about the html

(google noindex documentation: https://developers.google.com/search/docs/advanced/crawling/block-indexing)

**Comment by gasman** [comment]
@mikemonteith That sounds like a good plan, yep! I think that if we were to add a feature like that at this point, though, we'd need to make sure there's a clean way to disable it, so that it doesn't get in the way of people who've already implemented the equivalent functionality on their sites.

**Comment by Mr0grog** [comment]
I wonder if adding this as a type of `PageViewRestriction` (that is, as a “privacy” option) would be a good solution? Those are already customizable, so they are easy-ish to turn off. (That said, existing customization is by page class; the only global config is `WAGTAIL_PRIVATE_PAGE_OPTIONS`, which only lets you turn on/off shared password… but it’s easy to see how that could be extended to support more or all restriction types).
