### ISSUE TITLE
Pull `vagrant-wagtail-develop` inside this repo

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#3453]
It would be much more convenient if the vagrant files to build and work on the repo were contained when cloned.  Instead of requiring the developer to clone `vagrant-wagtail-develop` and modify the provision scripts and such to use the local copy instead of cloning the remote repos.

I understand if you don't want to change this due to current workflow but food for thought... running `vagrant up` from the local checkout would be much more reasonable for someone trying to contribute than a separate project and modifying the Vagrantfile/provisioners.

**Comment by gasman** [comment]
Hi @thenewguy,
I think it's important for the long-term health of the project that we keep a separation between the Wagtail repo and the kinds of "opinions" on technology that are baked in to `vagrant-wagtail-develop`.

If we were to include the `vagrant-wagtail-develop` config in Wagtail itself, people would quite reasonably expect to be able to contribute alternative configs for platforms such as Docker (and no doubt more exotic ones I haven't even heard of...), as well as different base images, database backends and so on. This then places the burden on the Wagtail core team to continually evaluate all of these competing technologies and decide which ones to formally adopt and continue supporting. (Obviously, we don't want to get into a situation where we merge a PR to support some trendy new technology that none of us have expertise in, and then let it stagnate because the original contributor lost interest in it...)

By keeping `vagrant-wagtail-develop` outside of Wagtail, it's on an equal footing with any other configs that third parties might come up with - that way the best tech will naturally rise to the top, and if something else surpasses `vagrant-wagtail-develop` in popularity, that's an entirely positive outcome.
