### ISSUE TITLE
Code injection vulnerability in CSV export function

### ISSUE THREAD

**Issue by mracter** [wagtail/wagtail#3466]
### Issue Summary

Freeform user input fields are not adequately neutralised before being made available to download in a CSV format.

An attacker could use this to insert artbitrary executable macro code into their usernames, survey comments, and article comments. When the CSV containing such input is downloaded and opened in Microsoft Excel or LibreOffice, the code would be triggered to execute on the target's computer, potentially allowing complete control over the target's machine.

### Steps to Reproduce

1. Answer a Wagtail-powered survey and putting "=cmd|' /C calc'!A0" into the "Additional Comments" input field, or any freeform input field associated with the survey.

2. Download the CSV of the survey results from the Wagtail admin interface and open in Microsoft Excel 2016. The input will be evaluated, causing Microsoft Calculator to launch on the target machine without the user intending to. Although newer versions of Microsoft Excel do show a macro warning, older versions do not, or execute the code before showing the macro warning.

This is considered a security issue, as any user with access to a Wagtail-powered platform could enter code with shell commands that would be executed on a site administrator's computer.

Please note that this issue is present in ANY feature of Wagtail that allows user-controlled input, and a CSV download facility for such input. This includes usernames, survey comments, and article comments.

### Technical details

* Python version: 2.7.6
* Django version: 1.9.7
* Wagtail version: 
  -  wagtail (1.8)
  -  wagtailmedia (0.1.3)
  -  wagtailmodeladmin (2.5.7)
  -  wagtailsurveys (0.1.1)
* Browser version: Chromium 56 (issue should be browser-independent)

Please note that this issue is estimated to affect multiple version sets.

### Recommended Resolution

It is recommended that all data fields found to begin with the following characters are prepended with an apostrophe ("'") before CSV export:

- Equals  to ("=")
- Plus ("+")
- Minus ("-")
- At ("@")

This will prevent automatic macro evaluation of all fields that begin with these characters.

Furthermore, to prevent bypass of this mechanism via line breaks or other trailing whitespaces, it is also recommended that all trailing whitespace characters are removed from any user-submitted input before storage.

**Comment by gasman** [comment]
Thanks @mracter!

It's open to interpretation where the responsibility for fixing this really lies: I think it's fair to say that interpreting strings in CSVs as formulae is a terrible misfeature on Excel / OpenOffice / LibreOffice's part. But since it's unlikely to get fixed there, we're reliant on the [Python standard `csv` library](https://docs.python.org/3/library/csv.html) to escape fields appropriately.

We should check whether the `csv` library has an option to enable the correct escaping behaviour that we're not currently using, and definitely fix that if so. (Unfortunately, from a quick look at the docs, it doesn't seem like there is such an option - in which case the real responsibility is between Microsoft and Python's `csv` library to reach an agreement on what constitutes a valid data-only CSV file.)

**Comment by gasman** [comment]
After further consideration and reading up, I'm going to side with [the Google security team's statement](https://sites.google.com/site/bughunteruniversity/nonvuln/csv-excel-formula-injection) on this one. It's a tricky call to make, since there is an expectation for us not to expose Wagtail users to unnecessary security risks. However, we have to work from the base assumption that a user's OS and supporting software (such as Excel) is patched, up to date and secure.

By any accepted definition (specifically, RFC 4180...) CSV is a plain text format, and the decision for Excel to interpret strings as formulae lies entirely with Excel. Evidently Microsoft have decided that the warning popup is sufficient mitigation for the security issue that arises from this. I don't agree, but it's not Wagtail's responsibility to police Microsoft's bad choices :-)

**Comment by bpluly** [comment]
This is wrong. You should always escape your output if it could ever be input to another system that could execute it. It's not a CSV issue its a string issue  and the Google attitude is just as wrong. Don't blame the transmission method it would be just as bad if it was a string in an API call.

If this isn't reopened then I'll open it and link to this.

**Comment by BertrandBordage** [comment]
@bpluly In theory yes, but in practice, how would you escape CSV data that would work on any software using CSV? Just because lots of users open CSVs with Excel doesn't mean we should write Excel-only CSVs.

**Comment by bpluly** [comment]
Well you can escape it with %markers just like HTML. Consuming applications can unescape it if they care. I've just done exactly that with RSS feeds from Confluence that have escaped, safe html. 

I wouldn't use single quotes, or apostrophes because that can cause more trouble, backslashes would likely be fine. A refinement would be a configurable escape character. 

I like the html escaping because its a safe replacement of any character.

**Comment by bpluly** [comment]
I suggested HTML escaping as one method as well as \ and also suggested a configurable escape.  HTML escape codes cover more than just shortforms like &amp, http://www.theukwebdesigncompany.com/articles/entity-escape-characters.php has the full list. But the actual method used is less important.

You seem to be saying that Wagtail bears no responsibility on what it produces that its up to some other agency to manage the problem.

This really has nothing to do with CSV and all to do with taking responsibility. If nothing else Wagtail should sanitise its input. If you are saying there is no sanitisation of input in forms (+) then that is something very much worse.

Providing xlsx as an output format would go a long way to at least give the user the information to make an informed choice.

If you're aware that a CSV file may be opened in Excel, Libre, or similar and it is reasonable to expect formulas to be included then it might be defensible but contentious to allow that. If it is not reasonable to expect that then it should be escaped or filtered so that another independent step is required to use that output in that way. Even if it was reasonable I would expect a user action to accept responsibility for the inclusion of possibly executable strings, or as you say .xlsx as an output format as well.

**Comment by BertrandBordage** [comment]
@bpluly Yes, it’s a matter of responsibility. But not Wagtail’s. If you open a PNG Wagtail thumbnail with a poor text editor that fills up your RAM triggering a kernel panic making you loose 3 hours of unsaved work on another file, would you blame Wagtail? No, the PNG is perfectly valid, the text editor is to be blamed for not handling binary files, or the kernel because of the panic. In a similar way, Office & folks bear the responsibility for allowing dangerous code execution.

Neither Wagtail nor the thousands of CSV providers will make CSVs Excel-oriented just because of a vulnerability in Office and friends.

We can provide an XSLX file export, but that’ll solve nothing, as we want to keep the CSV export since it’s universal.

**Comment by bpluly** [comment]
Then I'm sorry that as part of a CMS you fail to understand the responsibilities that come with that. The PNG example is spurious. 

The use case for this Issue is **user entered free form input fields**. Do you have no sanitation for these fields? This is nothing to do with CSV files, it has to do with what it is possible to export following input. If a form can be subverted and it has no constraints on the input then that form can become a vehicle for subverting another system, still moreso if there are no constraints on the output.

That is the nub of it. If you say there is no path where a form can be subverted, arbitrary strings entered and then used in another system with consequences then the OR @mracter may well accept that. 

There's any number of ways that this can be mitigated but to simply refuse responsibility for what a system allows as input and output is not sufficient.

**Comment by gasman** [comment]
> Do you have no sanitation for these fields?

Sanitise for what? No strings are inherently "unsafe" - they're just a sequence of bytes. The unsafeness only arises if you fail to perform the appropriate escaping _at the point of using it_.

If a user enters data containing a quote character, or a null byte, or `DROP TABLE students`, we will store that data exactly as supplied. (And, indeed, that will happen via a SQL query, and Django will take care of applying the right kind of escaping at that point so that the data arrives at the database in its original un-mangled form.) And when we export that data, we will format it according to the CSV spec, so that an application that reads the file according to the CSV spec will get back the expected data, byte for byte; not an escaped version of it.

> There's any number of ways that this can be mitigated

No, there is no way to engineer a CSV file to prevent Excel from evaluating formulae, other than to corrupt the data in a way that prevents it from being used by consumers that implement the CSV spec correctly.

**Comment by BertrandBordage** [comment]
Wagtail follows Django’s guideline of considering user input as HTML literals. So when users write `<script>alert('You have an XSS');</script>`, we consider that users wanted to show the code of a script, not run the code itself, so we store `&lt;script&gt;alert('You have an XSS');&lt;/script&gt;`.

We do that because this is the way to escape unsafe data in HTML. It is a norm, and HTML works because everyone follows that norm.
In [the CSV norm](https://tools.ietf.org/html/rfc4180), escaping consists in double quotes allowing to store commas and line breaks inside a cell. If we assume that users want to use only CSV for Excel, it will no longer follow the norm and fail to work on other software (cf the phone number example by @gasman).

We care a lot about security (I myself fixed a few security issues in Wagtail). But Wagtail cannot be held responsible for what happens outside of it. Literally any file can become a security issue, depending on how it is interpreted by the program reading.

**Comment by zerolab** [comment]
It is worth mentioning that popular libraries that work with CSV (e.g. league\csv for PHP apps) do not autoescape for formulas, but instead provide the means to do so programatically.

http://csv.thephpleague.com/9.0/interoperability/escape-formula-injection/ links to http://georgemauer.net/2017/10/07/csv-injection.html which recommends a good solution:

> For any cell that begins with one of the formula triggering characters =, -, +, or @, you should directly prefix it with a tab character. Note that if there are quotes, this character goes inside of the quotes

*but* the same article caveats everything with "The nasty end result is that when generating the csv export you **must know how the export is to be used.**" and that is the crux of the issue that @gasman has so patiently tried to explain..

**Comment by BertrandBordage** [comment]
This can be done using a Django signal checking that the sender is an instance of `AbstractFormSubmission` and adding an escaping to all fields that depends on the CSV use.

An Excel escaping signal recipe could be added to the `wagtail.contrib.forms` documentation.

**Comment by bpluly** [comment]
I'm not unaware of patience on all sides. :-)
The reason for escaping script tags is to prevent them being executed, not about making assumptions about what the user intended.

I was trying not to make it explicitly about Excel or Libre but to concentrate on the sane handling of free form user input which is then channelled out of that control. I have seen, as no doubt others have, the unintended consequences of not constraining output. If the input is also unstructured then the vectors of attack can open holes that had never seemed feasible or likely in the past. CMS's in general are susceptible to this, not least because often the content itself isn't cleaned by anything. The general approach then is if the vectors can't be adequately controlled to prune as hard as possible the variations in the content.

The major reason for me even commenting on this in the first place was the kind of attitude it showed to the original reporter, that this was nothing to do with this system and there was nothing that could be done.

Whereas we know there are things that can be done, and there are costs for all of them but simply shrugging the shoulders is not a helpful attitude and it may suggest that there are other areas where the same shrugging of responsibility happens but the outcome could be worse.

I'm not going to whackamole every single objection the only thing I would suggest is that you consider a couple of strategies around this. Warn the user that content of this export is used at their own risk and they are responsible for ensuring that there is no unexpected outcome from importing into any other system. At the same time provide an option to wrap affected fields in brackets (for Excel, Libre), they will then get treated as strings on being read but they're simple to resuscitate.

And the .xlsx option is a good one as well.

This will mean that likely hardly any users will need to worry, but they've been informed and it makes it clear that you care about the security of user's data and the use of Wagtail.

**Comment by kaedroho** [comment]
I've only had a brief skim through this thread so sorry if I've missed something.

I'm in favour of replacing the CSV export with XLSX and leave no option to download CSV.

I guess this is probably an unpopular opinion, but here are my arguments for it:

 - Almost all users will load this file into a spreadsheet. I don't see any reason why you would do something else, such as load it straight into a database. But If a user wanted to do this, they can easily convert XLSX to CSV.
 - XLSX files are widely supported. They work with MS Office, Google Docs, LibreOffice, Gnumeric, etc. I believe the only compatibility issues are with advanced features that we do not need (embedded objects, macros, etc).
 - XLSX supports typing, which leads to a better experience when working with dates and prevents formulas from being misinterpreted. This solves this issue without any Excel specific hacks.
 - The Python XLSX writer library is easy to install/use and it's fast. On one site, we generate XLSX files that are over 30k rows on the fly.

**Comment by gasman** [comment]
Happy to add XLSX and make it the default (assuming it doesn't add any friction to the Wagtail install, which it shouldn't as it's pure Python), but not to drop CSV. CSV has value as a simple human-readable standard recommended for open data, and as a general rule I'm against dropping existing functionality without a strong reason.
