### ISSUE TITLE
some tests do not consider swapped out models

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#3510]
I have been tweaking my testing setup to run the wagtail tests against my environment.  There are certain tests that do not take into consideration that the models may be swapped out or that particular settings should be overriden for a hardcoded string to be reliable.

Would you accept pull requests fixing these?

For example, https://github.com/wagtail/wagtail/blob/stable/1.9.x/wagtail/wagtailadmin/tests/test_collections_views.py#L166 does not take into consideration that the document model might not be `wagtaildocs.Document` with the import instead of using the `get_document_model` helper function.

And https://github.com/wagtail/wagtail/blob/stable/1.9.x/wagtail/wagtailadmin/tests/tests.py#L29 does not consider that the `WAGTAIL_SITE_NAME` might not be set correctly to produce this string

I've hit a number of these during upgrading and would be happy to put them together in a merge request as I fix them if you'd like

**Comment by thenewguy** [comment]
@tomdyson The fixes are fairly simple.  I.e. setting the correct `override_settings()` decorator or reversing the expected url instead of hard coding the path prefix '/admin'

**Comment by gasman** [comment]
Hi @thenewguy,

If I'm understanding right, the gist of your question is: "is it valid for tests to make assertions that are only true because of some specific property of the test environment (e.g. a config setting or URLconf), and aren't true for Wagtail in general?"

My answer to that is yes (but I'd be happy to hear other views - I certainly wouldn't consider myself an expert on testing best practices). A test can never be a universal statement about a piece of software's correct behaviour - all it can do is say "given input conditions A, B and C, we should see behaviour Z". The test project's config is just one possible place where those input conditions can be specified, alongside fixtures, model definitions, `setUp` methods and who knows what else.

To give an extreme example: to test that the admin menu hook works, we [add a "Kittens!" menu item in `testapp/wagtail_hooks.py`](https://github.com/wagtail/wagtail/blob/77c00ee77e6cbbe9318a1f4ff27b5d0ab8a97e30/wagtail/tests/testapp/wagtail_hooks.py#L44-L57) and then [test that this menu item is present in `wagtailadmin/tests/tests.py`](https://github.com/wagtail/wagtail/blob/77c00ee77e6cbbe9318a1f4ff27b5d0ab8a97e30/wagtail/wagtailadmin/tests/tests.py#L39-L43). Obviously, this test shouldn't be interpreted as saying "Wagtail must provide a 'Kittens!' menu item" :-) - it's a test that will _only_ ever be valid in the context of our test project, and I don't see that as a problem. (Admittedly, this bit of indirection could be avoided by setting up the hook locally in the test body, [using the `register_hook` helper](https://github.com/wagtail/wagtail/blob/6961f33078e12467fe7c4d1c2cfa055eace1aaca/wagtail/wagtailadmin/tests/test_pages_views.py#L993) - but I think it's in our interests to be as liberal as possible in how we let people write tests.)

Of course, if our test project's hard-coded settings don't cover all the conditions we need to test, then that's something we should address, via `override_settings` or otherwise. For example, if there were a bug that only surfaced when `WAGTAIL_SITE_NAME` contained a non-ASCII character, then we'd need a test case to cover that. Even then, it would still be fair game for the existing tests to make assertions according to whatever the `WAGTAIL_SITE_NAME` is set to in the test app settings.

**Comment by thenewguy** [comment]
@gasman The gist is similar but incomplete. The overall statement is that it is difficult to run the tests against the specific environment that the complete django project with everything put together runs on along with the additions of the local site.

There is value for the wagtail tests to run against the local site/environment so it is known that everything works as expected before deploy.  A few minor changes would make it much easier to do so without actually changing what is being tested.  Isn't that a good idea?

> (Admittedly, this bit of indirection could be avoided by setting up the hook locally in the test body, using the register_hook helper - but I think it's in our interests to be as liberal as possible in how we let people write tests.)

By this are you saying that this issue is out of scope and not worth the trouble?  I don't think it would add much strain on people who contribute tests but perhaps I am wrong?

An example of what has been required so far to run the wagtail tests against my environment:
```
from __future__ import absolute_import

from .common import *  # @UnusedWildImport  # isort:skip  # flake8: noqa

WAGTAIL_TEST_APPS = [
    'wagtail.tests.testapp',
    'wagtail.tests.demosite',
    'wagtail.tests.customuser',
    'wagtail.tests.snippets',
    'wagtail.tests.routablepage',
    'wagtail.tests.search',
    'wagtail.tests.modeladmintest',
    
    'wagtail.contrib.wagtailstyleguide',
    'wagtail.contrib.table_block',
    'wagtail.contrib.wagtailroutablepage',
    'wagtail.contrib.wagtailfrontendcache',
    
    'rest_framework',
    'wagtail.contrib.wagtailapi',
    'wagtail.api.v2',
]

AUTH_USER_MODEL = 'customuser.CustomUser'

INSTALLED_APPS += WAGTAIL_TEST_APPS

EXCLUDE_INSTALLED_APPS = ['cachalot', 'users']
INSTALLED_APPS=[name for name in INSTALLED_APPS if name not in EXCLUDE_INSTALLED_APPS]

# need to not test with the hashed staticfiles storage at the moment in order
# for wagtail's hardcoded tests to work as expected
# example of failing test due to this is: https://github.com/wagtail/wagtail/blob/47f7d79aec676e3388fdc3aa83c7d5a1de6ddc45/wagtail/wagtailadmin/tests/tests.py#L37
del STATICFILES_STORAGE

# wagtail document testing does not consider swapped out document models
del WAGTAILDOCS_DOCUMENT_MODEL

# Wagtail test expects this verbatim
# https://github.com/wagtail/wagtail/blob/47f7d79aec676e3388fdc3aa83c7d5a1de6ddc45/wagtail/wagtailadmin/tests/tests.py#L29
WAGTAIL_SITE_NAME = "Test Site"

# Extra user field for custom user edit and create form tests. This setting
# needs to here because it is used at the module level of wagtailusers.forms
# when the module gets loaded. The decorator 'override_settings' does not work
# in this scenario.
WAGTAIL_USER_CUSTOM_FIELDS = ['country', 'attachment']

WAGTAILADMIN_RICH_TEXT_EDITORS = {
    'default': {
        'WIDGET': 'wagtail.wagtailadmin.rich_text.HalloRichTextArea'
    },
    'custom': {
        'WIDGET': 'wagtail.tests.testapp.rich_text.CustomRichTextArea'
    },
}

# Using DatabaseCache to make sure that the cache is cleared between tests.
# This prevents false-positives in some wagtail core tests where we are
# changing the 'wagtail_root_paths' key which may cause future tests to fail.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache',
    }
}

WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.wagtailsearch.backends.db',
    }
}

from wagtail.tests.settings import WAGTAIL_ROOT
for data in TEMPLATES:
    if data['BACKEND'] == 'django.template.backends.jinja2.Jinja2':
        testapp_template_dir = os.path.join(WAGTAIL_ROOT, 'tests', 'testapp', 'jinja2_templates')
        data.setdefault('DIRS', []).append(testapp_template_dir)
```

Plus some logic to determine when these settings should be applied:
```
from os import getenv

TEST_MODE_ENV_VAR = "PROJECT_TEST_MODE"
TEST_MODE_WAGTAIL = "wagtail"
TEST_MODE = getenv(TEST_MODE_ENV_VAR, '').strip().lower()

TEST_MODE_IS_WAGTAIL = TEST_MODE == TEST_MODE_WAGTAIL

if TEST_MODE_IS_WAGTAIL:
    from .wagtail import *
else:
    from .common import *
```

It seems rather complicated instead of the tests just using `override_settings()` or one of the similar methods when they need to match against a specific string value

**Comment by gasman** [comment]
Thanks for the clarification. No, I don't think this is something we want to support - it may be that we can make the tests run on your particular config with a few straightforward patches, but if we're going to commit to ensuring the tests run on _any_ arbitrary config, then logically we have to treat any test failure on any setup as a bug, and that's just not feasible. Setting the default language to anything other than English will certainly break a huge number of tests, for example. There has to be some cutoff point for how far a settings file is allowed to deviate from wagtail/tests/settings.py before we declare it unsupported - and in terms of developer effort versus benefit, I don't think there's going to be a better place for that cutoff point than "not at all".
