### ISSUE TITLE
Layout bug for PageChooserBlock with multiple page types in target_model

### ISSUE THREAD

**Issue by pyMan** [wagtail/wagtail#3585]
### Issue Summary

About https://github.com/wagtail/wagtail/pull/3297

When defined multiple page types in PageChooserBlock's target_model the "CHOOSE A PAGE" button will become really long and ugly because it includes all the possibile page types.

In the following screenshot "SCEGLI UNA PAGINA" is the italiano "CHOOSE A PAGE" followed by my page types.

![screenshot](https://cloud.githubusercontent.com/assets/2025535/25751082/1ded261e-31b4-11e7-9b5f-464f5849e905.png)

### Technical details

* Python version: 2.7
* Django version: 1.8.x
* Wagtail version: 1.10
* Browser version: firefox dev tools 54

**Comment by lb-** [comment]
Suggested approach based on comments in PR #3297

Currently if there are a large amount of `target_model`s used, it will generate a really long string with something like 'Choose a page (Model One Page Name, Model Two Page Name, Model Three Page Name)'

This becomes quite long and is a bad UX, instead we want to specify the page type only when there’s only **one**: “Choose a page (your type)” and “Choose a page” in any other case.

**How to do this** (for anyone wanting to take this on)

Refine the `__init__` method on `AdminpageChooser`
https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/widgets.py#L159-L166

The revision should include logic to check if there is only ONE target_model and then include the title, otherwise it should default not change the `self.choose_one_text`  value, as it will simply default back to the original.

**Comment by gasman** [comment]
Fixed in #5094
