### ISSUE TITLE
Adding custom fields to the ImageInsertionForm

### ISSUE THREAD

**Issue by Minglee01** [wagtail/wagtail#3598]
### Issue Summary

Cannot add custom fields to the ImageInsertionForm

Given that https://github.com/wagtail/wagtail/blob/35305e1649c4fd10b64a3616982021340f1811ff/wagtail/wagtailimages/forms.py#L58

has ` alt_text = forms.CharField()` and the template loops over fields in form

would it be possible in the future to add custom fields?

### Technical details

* Python version:  3.6.0
* Django version:  Django (1.10.6)
* Wagtail version:  1.8

**Comment by gasman** [comment]
Hi @Minglee01,
Please can you give an example of a custom field that you'd like to add to this form?

In most situations, it would be more appropriate to define a custom image model <http://docs.wagtail.io/en/v1.10/advanced_topics/images/custom_image_model.html#custom-image-models> so that the custom field is associated with the image (and entered at the point of uploading the image), rather than being defined just for this one usage of the image.

**Comment by Minglee01** [comment]
Thanks for the quick reply. Example field could be a caption. We should be able to use an image more than once. And hide the caption on one image and show it on the second

**Comment by gasman** [comment]
Thanks for the clarification!

Generally we'd discourage embedding complex blocks such as 'image plus caption' into rich text areas - the rich text editor is a poor UI for that kind of structured content, since there's no way to edit the content after it's been inserted, and browsers tend to be quite buggy at wrapping paragraph content around those blocks. For that reason, it's unlikely that we'll be adding more configurability to images in rich text. I'd strongly recommend using StreamField for this instead: http://docs.wagtail.io/en/v1.10/topics/streamfield.html
