### ISSUE TITLE
Bulk delete from collection

### ISSUE THREAD

**Issue by devpascoe** [wagtail/wagtail#3606]
I am just making a note here that i would love to see a bulk delete feature of images from a collection. I have been testing image uploads to a heroku hosted wagtail app and had to use gevent and pgbouncer for uploads that don't time out (i'm also using storages to host the uploaded media to S3). Now that i have finished testing i have a collection with LOTS of photos uploaded. Be awesome to have a bulk delete feature (that also removes the file from S3). <3

**Comment by sbywater** [comment]
I too would appreciate this.

**Comment by vikingmoose** [comment]
Would be nice to have this. Collections are a pain to manage. Still no folder/subfolder support in 2021 :-(

**Comment by zerolab** [comment]
Hey @vikingmoose and all, bulk actions is one of the items we have the Google Summer of Code so there will be movement soon.

Can you expand on the folder/subfolder support? Wagtail 2.11 introduced collections hierarchy, and you can change the upload location by overriding [`get_upload_to`](https://github.com/wagtail/wagtail/blob/main/wagtail/images/models.py#L129) on your custom image model

**Comment by vikingmoose** [comment]
Hi @zerolab,  thanks that's great, news! 

Regading folder/subfolder support: imagine an estate agency with a ton of images of their portfolio. I understand you can create a collection for example each of the properties and upload the relevant media there, but it's not the most user-friendly way of doing it. Even with the collections in place the file storage just stores everything in a flat structure. Also once a property is sold and deleted from the DB - I was hoping by deleting a collection would also delete all the relevant images to free up space - but that's not the case since you need to delete the all the images first inside the collection..... 

The `get_upload_to` option wouldn't be sufficient as I'd need different folders for the same model. I guess I could make it work by adding a `before_create_page ` hook and create a folder with one of model field values as name the file storage, but seems like a lot of work for something pretty basic. (There are lots of filebrowsers supporting this from the early days of Django)

I think it would be nice to have something like this (apologies for the ugly photoshop):
![image](https://user-images.githubusercontent.com/5273555/110243264-ea9e6c80-7f59-11eb-9bd5-999baaaf73dd.png)
Also maybe an option to change different views (list or Icon) would also be something to think about. 

Goes without saying, Wagtail is awesome - I love it. 
Keep up the good work! 👍🏼

**Comment by lb-** [comment]
This original issue has been resolved as of Wagtail 2.15 (bulk actions) for  Images & Documents
https://docs.wagtail.org/en/stable/releases/2.15.html#bulk-actions

Steps
1. Load up the Images page
2. Select the collection
3. Check one image
4. Click the 'all' checkbox in the UI that appears at the bottom
5. Select 'all images in this listing'
6. Click delete
7. Confirm delete (listing shown)

<img width="1625" alt="Screen Shot 2022-03-21 at 7 54 30 pm" src="https://user-images.githubusercontent.com/1396140/159238716-6bc7aa0f-c2c3-46e0-83a5-2f246ab26ae8.png">

Closing now, happy for you @vikingmoose to propose a new enhancement for better collection management from within image listings.
