### ISSUE TITLE
Ory editor

### ISSUE THREAD

**Issue by garykrige** [wagtail/wagtail#3614]
I think integrating the Ory editor in some way for StreamBlocks could be very powerful:
https://github.com/ory/editor

**Comment by kakulukia** [comment]
I just found this editor and immediately thought the same as i saw it!
Id love to see my favored CMS having a great editor!

**Comment by gasman** [comment]
Thanks for pointing this out! There are indeed very strong similarities with what we're doing with Streamfield, and ideas that I'd very much like to adopt such as being able to seamlessly move the text cursor between blocks. However, given the difference in technology stack (we still need to be able to define block types in Python code) and other design decisions they've made (it seems to be built around the principle of giving editors complete freedom over page layout, rather than enforcing any structure in the data model), I think it's unlikely we'd be able to use the Ory editor as anything other than a source of inspiration.
