### ISSUE TITLE
Preview for pages fails when hostname is incorrect although site itself loads fine

### ISSUE THREAD

**Issue by Adrian-Turjak** [wagtail/wagtail#3631]
Not entirely sure if it is a bug, but the error messages that cropped up didn't help me figure out exactly what the issue was at first, so am leaving this here for you to decide.

### Issue Summary

When previewing a page, if the hostname for the site does not match the host you access it on, the preview fails. The site itself loads perfectly fine, likely defaulting to the default site regardless, but the site middleware doesn't do that for previews it seems if the hostname is misconfigured.

It was unclear what the issue was since everything else just worked fine. Some better errors, or warning in logs about misconfigured site hostnames (if they aren't already present and I missed that), would be very helpful.

### Steps to Reproduce

1. setup basic wagtail site (such as demo)
2. login to admin, make new page, attempt to preview, should work
3. rename site hostname to something other than localhost
4. attempt to edit same page, preview, should fail
5. hit publish, then view live, page should be visible
6. renamed hostname back to localhost
7. attempt to preview page again (works)

up wagtail demo (or any basic wagtail site)

### Technical details

Tested with the basic wagtail demo, clean venv.

**Comment by lb-** [comment]
@Adrian-Turjak I have been looking into this issue, thank you for submitting this.

Question - were you getting the same `Invalid HTTP_HOST header:` in your testing?

## Cause 
Wagtail admin builds a `dummy_request` for a page whenever it is being previewed, this will get the hostname/port from the saved URL info on the page. Where as normal site viewing already has a hostname/port along with the request so it uses that.

When I followed the notes you set, I did actually get an error in the console:
`Invalid HTTP_HOST header: 'foo'. You may need to add 'foo' to ALLOWED_HOSTS.`

But I also got the confusing error on the page itself:
`'WSGIRequest' object has no attribute 'site'`

It appears that the middleware to add the Site to the request is then skipped because of misconfiguration.

## Resolution

I am not super clear on this one, it would be nice if we can throw an `ImproperlyConfigured` error instead of just letting it try to complete the request.

**Comment by Adrian-Turjak** [comment]
Honestly it isn't that big a deal, I just got weirdly caught and confused by it.

I likely had `['*']` in my allowed hosts though so I probably never got that warning.

**Comment by Adrian-Turjak** [comment]
Actually I'm not even sure. I don't think I added `['*']`, but it was likely running in debug. The fact that I myself can't even remember what I did given this bug report makes me question how useful it even is. :P

**Comment by lb-** [comment]
Thanks @Adrian-Turjak we might close this for now then.

**Comment by mrts** [comment]
As of Wagtail 1.11 the issue still exists - page preview fails when hostname is incorrect. This is just FYI, the issue can remain closed.
