### ISSUE TITLE
Autogenerated slug with national characters

### ISSUE THREAD

**Issue by moreplavec** [wagtail/wagtail#3646]
### Issue Summary

Autogenerated slug contaigns national characters

### Steps to Reproduce

While creating new post/page slug is autogenerated. But it's just a copy of the title and there is no substitution for language specific letters. For example in czech there are letters like _ěščřžýáíé_ which needs to be replaced with _escrzyaie_

### Technical details

* Python3, Wagtail 1.10.1

**Comment by thibaudcolas** [comment]
Hey @moreplavec, this is the expected behaviour. You can turn this off by setting  [`WAGTAIL_ALLOW_UNICODE_SLUGS`](http://docs.wagtail.io/en/v1.10.1/advanced_topics/settings.html#unicode-page-slugs) to `False`.

If you're doing this already and it isn't working as expected, please let us know and we'll reopen the issue.

**Comment by moreplavec** [comment]
Thanks for info/help, my mistake!
