### ISSUE TITLE
Image URL generator is confusing for end users

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#3683]
### Issue Summary

In its current incarnation, the UI of the image URL generator is not very user friendly. This statement is only based on informal conversations, we haven't done any real user testing, but I think there are specific issues I can point to:

- The URL generation happens whenever any of the values change. This can seem like a good thing, but there is no visual indicator that the URL was updated, so it's not immediatly clear that you're supposed to copy the content of the field. This is also the only place within Wagtail that I've seen doing this, so not really consistent with how the UI operates overall.
- There is no clear call to action that the URL field is meant to be copied. There should be a message saying "copy the content of this field", or an explicit "Copy" button.
- People usually expect to see the result of their manipulation at the end of the form, whereas here it's in the middle.

Here is the UI for reference:

<img width="1048" alt="url-generator" src="https://user-images.githubusercontent.com/877585/27719631-dbe14726-5da7-11e7-8075-f769ba07441f.png">

### Potential solutions

- There should be a clear call to action on this page – in my opinion the best would be to have a "Copy" button next to the URL field. The Google Docs sharing feature is a good example of how this works.
- We could make the image panel scroll, so there is no need for the "you may not see the full image" disclaimer.
- With the image panel using a fixed max height, we could move the URL field below it where it is the most expected, but still above the "fold".

Any further user experience / design direction is very welcome. cc @wagtail/ux-design.

### Steps to Reproduce

1. Create an image
2. Go to its URL generation form

### Technical details

Wagtail 1.10, assuming this is in all versions of Wagtail

- JS code: [`image-url-generator.js`](https://github.com/wagtail/wagtail/blob/0cf3b13a1d54528237552ee37ee2eeb3a13d4e1d/wagtail/wagtailimages/static_src/wagtailimages/js/image-url-generator.js)
- Template: [`url_generator.html`](https://github.com/wagtail/wagtail/blob/0cf3b13a1d54528237552ee37ee2eeb3a13d4e1d/wagtail/wagtailimages/templates/wagtailimages/images/url_generator.html)

--------

This is an enhancement, and a nice UI problem to solve. I'll assign myself for now and do further investigation. I think this would be a really good potential PR for a newcomer to the project, but will want to assess this further to be sure.

NB: this would also be a good candidate for a rebuild to React.

**Comment by Harsh-Mathur-1503** [comment]
I would like to work on this issue.
Can you kindly assign it to me?
@tomdyson @thibaudcolas

**Comment by zerolab** [comment]
@Harsh-Mathur-1503 just go for it. We do not assign issues to anyone outside the core team. Please read https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html, and in particular https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html#contributing-a-solution

**Comment by Harsh-Mathur-1503** [comment]
@zerolab okay thanks for responding

**Comment by thibaudcolas** [comment]
@Harsh-Mathur-1503 please don’t at-mention people asking to be assigned in the future. As Dan mentions we don’t assign issues to anyone outside the core team and this is pretty clearly mentioned in our contributing guidelines, which are very visible on this repository.

**Comment by lb-** [comment]
## Recommended Action - Part A - Refine layout

For anyone wanting to contribute to this issue, here is a 'chunk' of changes that would make sense as a standalone PR and will require knowledge of CSS and HTML templates, with a small removal of some JS code.

**Goal:** Reorder the content so it's easier to understand that this image preview is the result of changes.

### Implementation

1. In `wagtail/images/templates/wagtailimages/images/url_generator.html` swap the preview & the URL field so the preview is seen first.
2. Change the way the image preview works so that it always will be sized the same as the source image. Use styles on `<img class="preview" src="" alt="{% trans 'Preview' %}" />` to remove the max width, we can probably just use the Tailwind class `w-max-w-none` for this. Remember to re-compile your CSS before you will see this class doing anything.
3. Now that the image is huge, we want to ensure the container that contains the image can show scrollbars. The div under `{% panel id="preview"` has no classes but we can probably make the overflow on that container, then the inner div `.inline-block` may need to remove the inline-block class. We also will want some padding inside the scrolling container and a border (remember dark/light mode) to help make the content easier to differentiate from the rest of the page. `grey.200` from client/src/tokens/colors.js could be suitable.
4. Remove the JavaScript/jQuery code that hides /shows the message about the oversie image. See `// Display note about scaled down images if image is large` in `wagtail/images/static_src/wagtailimages/js/image-url-generator.js`. Not only is this now not needed (as the user can see the whole image) but this did not work for resizing the viewport anyway.
5. We will want to help ensure the preview container does not get to high, the suggestion above is to have this get a max height. Our goal is that 'most' users on most viewport sizes will see the image 'above the fold', we may want a height using CSS clamp to get this to nicely work across all screen sizes. `max-height: clamp(25rem, 50vh, 50rem);` might be a good start.

These are rough guidelines, and may not work exactly, but hopefully it's a solid enough guide for someone to pick part of this issue up.

We will end up with _something_ like this, it's a rough POC but hopefully gives an idea.

<img width="1811" alt="Screenshot 2023-10-25 at 9 04 05 pm" src="https://github.com/wagtail/wagtail/assets/1396140/8af82a1c-f83c-46bf-8803-583262c51265">

**Comment by lb-** [comment]
## Recommended Action - Part B - Add copy button

For anyone wanting to contribute to this issue, here is a 'chunk' of changes that would make sense as a standalone PR and will require knowledge of TypeScript, Jest testing and a reading of the MDN clipboard docs. https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

**Goal:** Provide a clear 'copy' button that will copy the content of the URL and advise the user when copied and when there was an error (e.g. not supported).

### Implementation

1. Create a new `client/src/controllers/ClipController.ts` (ClipController / w-clip) Stimulus controller.
2. This controller will be similar to the Stimulus tutorial clip controller https://stimulus.hotwired.dev/handbook/building-something-real with the ability to target an input `value` to copy to the clipboard.
3. A `copy` button under or above the URL field should copy the value from the URL field to the clipboard when copied.
4. If successful, it should show a simple message 'Copied to the clipboard.', if it fails it should show a message 'Copying to the clipboard failed. These should appear under the input and be a label or description associated with the copy button (e.g. maybe aria-describedby).
5. The outer container should have `aria-live` set to ensure screen readers are alerted to changes to this URL value AND changes to messages that get shown.

### POC code

Here is a starting controller that could help, this may not be fully functional and does not have unit tests but hopefully helps. Note that this controller must be registered as `w-copy` in `client/src/controllers/index.ts` for this to work.

Instead of this controller managing the messages, we may want to use the `w-messages` Controller which has built in functionality for showing a message based on some events that are dispatched. You can see how this is used in `wagtail/admin/templates/wagtailadmin/pages/_unsaved_changes_warning.html`.

The approach below probably is a bit too complex for what's needed, e.g. we may not need the success/error classes and if we use the messages controller we probably do not need to worry about handling the success/error targets either.

```typescript
import { Controller } from '@hotwired/stimulus';

import { debounce } from '../utils/debounce';

export class ClipController extends Controller<HTMLElement> {
  static classes = ['error', 'success'];
  static targets = ['error', 'success', 'value'];
  static values = {
    duration: { default: 5_000, type: Number },
  };

  declare durationValue: number;
  declare errorClasses: string[];
  declare errorTarget: HTMLElement;
  declare successClasses: string[];
  declare successTarget: HTMLElement;
  declare valueTarget:
    | HTMLInputElement
    | HTMLTextAreaElement
    | HTMLSelectElement;

  copy() {
    if (!navigator.clipboard) {
      this.showError();
      return;
    }

    const value = this.valueTarget.value;

    if (!value) return;

    navigator.clipboard.writeText(value).then(
      () => this.showSuccess(),
      () => this.showError(),
    );
  }

  reset() {
    this.element.classList.remove(...this.errorClasses, ...this.successClasses);
    this.errorTarget.hidden = true;
    this.successTarget.hidden = true;
  }

  showError() {
    this.errorTarget.hidden = false;
    this.element.classList.add(...this.errorClasses);

    debounce(() => {
      this.element.classList.remove(...this.errorClasses);
    }, this.durationValue)().then(() => {
      this.errorTarget.hidden = true;
    });
  }

  showSuccess() {
    this.successTarget.hidden = false;
    this.element.classList.add(...this.successClasses);

    debounce(() => {
      this.element.classList.remove(...this.successClasses);
    }, this.durationValue)().then(() => {
      this.successTarget.hidden = true;
    });
  }
}
```


### POC HTML

```html
        {% panel id="url" icon="link" heading=heading %}
            <div data-controller="w-clip">
                <textarea id="result-url" rows="1" data-controller="w-action" data-action="focus->w-action#select" data-w-clip-target="value"></textarea>
                <button type="button" class="button button-secondary button-small" data-action="w-clip#copy">Copy</button>
                <div class="message">
                  <span data-w-clip-target="success" hidden>Success</span>
                  <span data-w-clip-target="error" hidden>Error</span>
                </div>
            </div>
        {% endpanel %}
```

The HTML above does not have the right message content and does not use translations, these will be required for the PR. Nor does it have any aria related attributes.

**Comment by Temidayo32** [comment]
@lb- I will like to take up this issue.

**Comment by lb-** [comment]
@Temidayo32 which part? It's probably best to just tackle one at a time.

**Comment by Temidayo32** [comment]
@lb- I will start with Part A. It should easier to tackle and get me in motion with this issue.

**Comment by lb-** [comment]
The layout rework has been done via #11181 - thanks @Temidayo32 

If you are keen on the Stimulus part, feel free to go for it. An aside is that we may just choose to call this `ClipboardController` and `w-clipboard`. It's going to be much more readable if we use a longer name here.

**Comment by Temidayo32** [comment]
Thanks @lb- I will work on the stimulus part too.

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail/pull/11317 has been created to add copy to clipboard functionality in the Image URL.

FYI @Temidayo32 - I know you mentioned you may be keen on this but looks like someone else started on this also, feel free to support by adding any thoughts to that PR.
