### ISSUE TITLE
Feature Request: hooks for website template

### ISSUE THREAD

**Issue by moreplavec** [wagtail/wagtail#3688]
### Issue Summary

I can't find any easy way how to create module and "inject" templates or generated pages with own code. For example: 

if i need plugin to insert Google Analytics code in all my wagtail websites, i have to put code into all my pages + i need to insert one specific variable into this code. So i need module + admin area to manage site-specific variable. 

I think this is what are hooks made for, but found hooks only for admin templates. What about to create website hooks like before_closing_tag_XY, after_tag_XY...

Thanks for opinion or help, if there is anything like this.

**Comment by gasman** [comment]
Hi @moreplavec,

This ability is provided by the [Django templating language](https://docs.djangoproject.com/en/1.11/ref/templates/language/) - specifically the `extends` and `block` tags which allow you to define a base template with various slots for HTML to be inserted into. Wagtail itself deliberately doesn't get involved in how you write your templates, so it wouldn't be appropriate to use hooks for this.

For site-wide variables such as Google Analytics IDs, look at the [wagtail.contrib.settings](http://docs.wagtail.io/en/v1.11/reference/contrib/settings.html) module.

**Comment by moreplavec** [comment]
Thanks for answer. I use _blocks_ and _extend_, but i need something different. Now, if i want to use Google Analytics, i have to modify templates and register snippet. For every site (wagtail website) i have. What I'm asking for is chance to modify template (rendered html). With such feature i can insert Google Analytics without editing each site template, by simply upload and activate module. When GA changed i will modify module and all my sites will work again. With code directly as part of templates i have to edit all site templates each time there is update. 

Another point is i cant simply work with, for example, files to download. With such hooks i could modify code for all links, all files aso. For example if i need to measure every downloaded file or every image gallery click, it would be easy with such hooks. Now i need to put same code on every occurency. If i need to modify this code, it would be easy, if it will be in one place globally used.

Maybe i can't explain how usefull such hooks are, maybe you can understand better if you look at some hooks provided by Wordpress. It could be same. WP can easilly modify any rendered text and it's very very usefull.

**Comment by gasman** [comment]
I see - so what you're after is a way to have a reusable Google Analytics module (for example) which can be installed on a site and immediately take effect without having to edit any template code.

We have no plans to implement anything like that in Wagtail, since it would require users to adopt a standard structure for their front-end templates: in order to have a hook that says "insert this code into the header / footer / sidebar", your templates need to have a standardised idea of what a header / footer / sidebar _is_. CMSes like Wordpress and Drupal are happy to embrace this principle, but it's something that we explicitly wanted to avoid in Wagtail because we found it too restrictive on designers - you end up building sites by plugging modules together, instead of writing HTML, and have to fight against the framework to avoid building generic "boxy" designs.

I think the extra flexibility is worth the slight inconvenience of having to say "install this module and then add `{% analytics_snippet %}` in the appropriate place on your template". Having said that, I could certainly imagine a project like [Puput](http://puput.readthedocs.io/en/latest/index.html) introducing a standard front-end framework on top of Wagtail, and having its own ecosystem of plug-in modules. Wagtail itself will not be that front-end framework though :-)

**Comment by moreplavec** [comment]
OK, thanks for info.
