### ISSUE TITLE
Migrations for complex StreamFields are very wonky and seemingly pointless.

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#3710]
My project includes a deeply complex StreamField, which we wrote to allow our users to make highly dynamic pages. Unfortunately, StreamFields seem to be rather poorly optimized in regards to how migrations are created for them, and this has led to a number of serious headaches for us.

The biggest issue is that our StreamField generates absurdly massive, apparently pointless migrations. Changing the "required" setting on a single field in a single custom block type that is used by our StreamField causes Django to generate a migration that is _197 kilobytes_ of text, almost all on one line. But nothing is actually being changed within the database when a _block's_ fields are changed, so why does a migration even get generated in the first place?

The second problem is that when we delete or rename Block classes, old migrations break, because they import that class. Here's a small snippet from one of the broken migrations I'm dealing with right now:

    ... (b'foreground_color', wagtail.wagtailcore.blocks.ChoiceBlock(blank=False, choices=[(b'#ffffff', b'White'), (b'#616265', b'Dark Gray')]))])), (b'section_title', sites.models.blocks.SectionTitleBlock(label=b'Section Title')), ...

We renamed the class `sites.models.blocks.SectionTitleBlock`, but we can't generate a new migration to deal with that rename, because `manage.py makemigrations` crashes with:

`AttributeError: 'module' object has no attribute 'SectionTitleBlock'`

How is one expected to deal with this? I did some research in the Django docs, and I haven't found any useful solutions.

**Comment by Proper-Job** [comment]
Hi @coredumperror 

I hear your pain, but that's not a problem that is unique to Wagtail.  This problem is unique to how Django manages migrations.
 
As far as I can see there are 2 solutions to this problem:

1. Keep a stub to the removed block in your models file. This way existing migrations can still reference it
2. [Squash](https://docs.djangoproject.com/en/1.11/topics/migrations/#squashing-migrations) your migrations so that the block reference gets removed (this might not always be feasible).

[This](https://docs.djangoproject.com/en/1.11/topics/migrations/#considerations-when-removing-model-fields) section in the Django docs should apply to Wagtail blocks as well.

**Comment by coredumperror** [comment]
Yeah, some further research I did after posting this issue revealed that this is just an artifact of how Django decided to handle constructing migration files. Our app just happens to generate especially heinous, utterly useless migrations, and there's nothing that Wagtail can do about that. :(
