### ISSUE TITLE
Save button is positioned strangely in image editor on mobile

### ISSUE THREAD

**Issue by kapito** [wagtail/wagtail#3711]
When in its desktop state, the image editor looks like this:

![image](https://user-images.githubusercontent.com/14837124/28215768-12a49510-68a7-11e7-8419-a03b4f6d8491.png)
This looks great, however on mobile it's a bit confusing as the save/delete buttons appear in the middle of the options (not at the end as you would expect). I think it would be more intuitive if these were placed at the very bottom so the user knows they must save even after editing the focal point; at the moment it gives the impression that it is separate and doesn't require manual saving:

![image](https://user-images.githubusercontent.com/14837124/28215631-93c67c40-68a6-11e7-8c30-844e1c6fda43.png)

**Comment by SalahAdDin** [comment]
Yes, you are right.

**Comment by thibaudcolas** [comment]
Frankly I have the same impression on desktop, since the Save/Delete buttons are clearly part of the left-hand column.

A simple fix would be to move those buttons under the three columns on desktop – I imagine they would then be positioned at the end of the whole form on mobile:

![wagtail-buttons-mobile](https://user-images.githubusercontent.com/877585/28578392-e95f86fe-7159-11e7-931f-f0ecb2dab5a9.png)

Thoughts and design propositions welcome!

**Comment by kapito** [comment]
Another potential design:
![image](https://user-images.githubusercontent.com/14837124/28625439-30e585f4-7214-11e7-86cb-5cd49d96dbb1.png)

However I'm not sure how well this would convert over to mobile.

**Comment by thibaudcolas** [comment]
Fixed in #3771.
