### ISSUE TITLE
Mobile navigation menu scrolls past its height

### ISSUE THREAD

**Issue by kapito** [wagtail/wagtail#3721]
When in its desktop form, the navigation menu is treated separately from the actual content and the content scrolls by itself: https://gfycat.com/SlowOffbeatAsiantrumpetfish

![](https://thumbs.gfycat.com/SlowOffbeatAsiantrumpetfish-size_restricted.gif)

However, when in its mobile form, the menu scrolls *with* the content which looks rather odd as there is obviously nothing underneath the menu (so you get this area of nothing in the bottom-left corner): https://gfycat.com/MarvelousLateBighornsheep

![](https://thumbs.gfycat.com/MarvelousLateBighornsheep-size_restricted.gif)

Perhaps this is intentional or I'm missing something obvious, in which case please say, but it seems to me that the menu should be fixed and be independent of the content itself even in its mobile state.

**Comment by thibaudcolas** [comment]
Thanks for the bug report @kapito.

I think this scrolling behavior makes sense on "mobile". Since the menu is generally smaller than the viewport height on those screen sizes, it would have to scroll, and having two separate scrolling contexts would be even more confusing. The viewport you tested on is quite big, on phone-size devices it feels better IMO.

For the "area of nothing", this is not what I observe on iOS / Safari: there scrolling stops at the end of the menu when it is open. So this issue is specific to either the browser engine, or viewport you are using – could you share the Firefox version this was tested with as well as the viewport size?

**Comment by kapito** [comment]
Sorry @thibaudcolas, I don't have access to that machine right now however I believe it's the most recent version of Firefox. I'll give it a go with some other browsers (Chromium, Safari, IE maybe) when I get the chance.

**Comment by thibaudcolas** [comment]
Closing as this is most likely intentional behavior of the menu.
