### ISSUE TITLE
Reuploading an image doesn’t invalidate browser caches

### ISSUE THREAD

**Issue by BertrandBordage** [wagtail/wagtail#3817]
Use case and steps to reproduce:
1. Upload an image
2. Link other objects to it, like pages, then realise something is wrong with the image (bad quality, wrong contrast, etc)
3. Reupload the file (usually with the same name) by editing the image
4. Download the file somewhere, from the front or back office, and you get the previous version if you already viewed it once and if you kept the same filename when reuploading it

This is because browsers can cache images.
When users reupload an image, they almost always have the same name as the original. And since HTTP servers are most of the time configured with a long expiry delay like a month or a year, people get stale data.

Django [has a way to deal with this](https://github.com/django/django/blob/master/django/core/files/storage.py#L61-L90) by looking for an available file name before saving the file and database row. It adds an underscore and a hash to the original filename until it finds an unused hash.

Unfortunately, Wagtail bypasses this behaviour [by deleting the image just before saving the new one](https://github.com/wagtail/wagtail/blob/v1.12/wagtail/wagtailimages/views/images.py#L102-L106).

Note that **there is a small difference with #3816**, as images also have renditions/thumbnails. As we can see [in the code](https://github.com/wagtail/wagtail/blob/v1.12/wagtail/wagtailimages/views/images.py#L107), all renditions are correctly removed, but since the name of the image file is kept the same, all renditions file name also stay the same, even if the rendition objects and files are deleted and created again later. So the same browser cache issue happens with renditions. This should be fixed by doing nothing more than the same fix as for #3816, but we have to check that renditions work anyway.

I’m working on a pull request to fix this.

**Comment by gasman** [comment]
Fixed in #3822

**Comment by pyMan** [comment]
Hi @BertrandBordage 

Just to see if I understood: you're somehow linking the image to the page without using the url generated by the url generator? Now when the image is re-uploaded the filename is changed, but the generated url is the same (because it's calculated with its database's id) so I may still have the same problem with the browser cache. Isn't it?

Another thing: if I have an already uploaded file foo.png and I re-upload that file, it becomes something like foo_<hash>.png . If I now do one more re-upload (let's say after a one more little improvement to the image) the filename comes back to be foo.png (it should be the common case). So we are back to the original problem. Let's say you moved it away from us one step further. Isn't it?

Just to understand what can happen.

Thank you
