### ISSUE TITLE
Mobile footer doesn't stick while nav-menu is visible

### ISSUE THREAD

**Issue by kapito** [wagtail/wagtail#3818]
When the nav-menu is opened on mobile viewports, the footer appears to  'unstick' and use `relative` positioning rather than `fixed`. 

![image](https://user-images.githubusercontent.com/14837124/29875265-5d4440ca-8d91-11e7-9b96-58792ff4522c.png)

**Comment by saevarom** [comment]
Looks like it only happens when the screen height is lower than the nav nav height. 

Then, the content-wrapper div becomes fixed to disable scrolling of content while nav is open. But because the nav has more content to display, you can scroll within the height of the nav. 

Setting overflow: scroll on the nav-wrapper fixes this behaviour, but I'm not sure if that's the ideal solution.

**Comment by thibaudcolas** [comment]
Closing in favor of #4641 since we intend to make the footer not-sticky on mobile.
