### ISSUE TITLE
UI component library

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#382]
At present the process of reusing the admin UI is just a case of copying and pasting the HTML from an example page. With the exception of the header, nothing is componentised and new developers creating new screens are liable to mis-paste or misunderstand the classes required on some UI. Methods used to style the same component from one page to the next are likely to fall out of sync.

I'd like a component library covering as many UI components from the Styleguide as possible. Creating a bi-color button shouldn't be a case of writing `<button class="bi-color">` tags, but rather `{% wagtailui button bicolor %}` or similar. It's not about reducing the work involved, just about ensuring it's uniform and controllable from a single point if changes are required.

The styleguide would obviously be updated with code examples too, so that the tag syntax were explained for each component.

**Comment by vaibhavjack11** [comment]
This work is really interesting for me I want to work on it, can I ??

**Comment by lb-** [comment]
@vaibhavjack11  this has been flagged as something being worked on for the page editor 2022 work https://github.com/wagtail/wagtail/discussions/7739

So it might be best to hold a bit on this until there is more feedback from @thibaudcolas - mainly due to some core infra being set up for this.

In the mean time you can check out what has been worked on in these external repos
* https://github.com/torchbox/storybook-django
* https://github.com/torchbox/django-pattern-library

**Comment by thibaudcolas** [comment]
I’ll assign this to myself to document where we’re at with our UI component library, and then close this issue.
