### ISSUE TITLE
Not possible to migrate before running collectstatic

### ISSUE THREAD

**Issue by jaap3** [wagtail/wagtail#3829]
### Issue Summary

Our deployment scripts will first migrate, then run collectstatic when deploying a Django site. A recent release of Wagtail broke this strategy and causes an exception when running the migrate management command before running collectstatic.

### Steps to Reproduce

Start a project and make sure the following settings are set:

    DEBUG = False
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'`

Run `./manage.py migrate`

This will error with:

    ValueError: Missing staticfiles manifest entry for 'wagtailadmin/js/hallo-plugins/hallo-requireparagraphs.js'

If you run collectstatic before migrate everything is fine.

### Cause

This seems to be caused by the call to `static` here: https://github.com/wagtail/wagtail/blob/9942822/wagtail/wagtailadmin/rich_text.py#L77

Since this happens at module level this call will happend as soon as this file is imported. Which apparently it is when migrate is called.

The easiest solution to me seems to just move this bit of code to where it's used: https://github.com/wagtail/wagtail/blob/9942822/wagtail/wagtailadmin/rich_text.py#L104

**Comment by gasman** [comment]
Thanks for the report @jaap3!

After some digging into the code to figure out the best way to delay the call to `static` without breaking the HalloPlugin API, the solution was easier than I expected... the `static` call can simply be left out, because Django's form media logic will fill in the static path itself: https://docs.djangoproject.com/en/1.11/topics/forms/media/#paths-in-asset-definitions

Now fixed in #3840.
