### ISSUE TITLE
Streamfield documentation issues related to the `required` argument

### ISSUE THREAD

**Issue by balazs-endresz** [wagtail/wagtail#3830]
1. The 1.12 release notes could mention that the StreamBlock needs a `required=False` argument if the StreamField has `blank=True`: http://docs.wagtail.io/en/v1.12.1/releases/1.12.html#streamfield-now-defaults-to-blank-false 
2. Are there any blocks that don't accept a `required` argument? Because it's not listed among the common ones: http://docs.wagtail.io/en/v1.12.1/topics/streamfield.html#basic-block-types
3. Is the default `required=True` for all block types? It's not mentioned consitsently for all block types: http://docs.wagtail.io/en/v1.12.1/topics/streamfield.html 
4. Examples add `required=True` to CharBlocks, while that's already the default value. E.g.: http://docs.wagtail.io/en/v1.12.1/topics/streamfield.html#structblock

**Comment by gasman** [comment]
Now addressed in #3865.

1. I've double-checked that StreamField's `blank` property always takes precedence over StreamBlock's `required` property when using a top-level StreamBlock, including when `blank` is left at its default. After some pondering, I think this is the most logical behaviour, since the StreamField definition is the most immediately visible thing. Now documented in https://github.com/wagtail/wagtail/pull/3865/commits/5112d70c7ce6fb3c6ec6d12a47c25ee4d3601f16
2. There are some blocks which don't accept `required`: `StaticBlock` (where there's no user input at all), `StructBlock` (where required-ness is only a meaningful concept on the individual child blocks) and `RichTextBlock` (which probably should accept it, but currently doesn't because of the difficulties of dealing with edge cases like `<p></p>`). For that reason, it's appropriate for it to be documented on a case-by-case basis for specific blocks.
3. Yes, required always defaults to True. Now documented in https://github.com/wagtail/wagtail/pull/3865/commits/659cdd8190e63d810a6dbf2eb03d4d75d0e431a6
4. Fixed in https://github.com/wagtail/wagtail/pull/3865/commits/e09381fa26ef4fef095106b5f818af0d5e1e6a20
