### ISSUE TITLE
Wagtail SQL call on none wagtail pages

### ISSUE THREAD

**Issue by sowinski** [wagtail/wagtail#3834]
Hi,

I have included wagtail to my project as a cms system. But I have also some old static pages which also produce allways this SQL call:

`
SELECT"wagtailcore_site"."id", "wagtailcore_site"."hostname", "wagtailcore_site"."port", "wagtailcore_site"."site_name", "wagtailcore_site"."root_page_id", "wagtailcore_site"."is_default_site", CASEWHEN ("wagtailcore_site"."hostname" = '''127.0.0.1''' AND "wagtailcore_site"."port" = '8000') THEN '0' WHEN ("wagtailcore_site"."hostname" = '''127.0.0.1''' AND "wagtailcore_site"."is_default_site" = 'True') THEN '1' WHEN "wagtailcore_site"."is_default_site" = 'True' THEN '2' ELSE '3' END AS "match", "wagtailcore_page"."id", "wagtailcore_page"."path", "wagtailcore_page"."depth", "wagtailcore_page"."numchild", "wagtailcore_page"."title", "wagtailcore_page"."slug", "wagtailcore_page"."content_type_id", "wagtailcore_page"."live", "wagtailcore_page"."has_unpublished_changes", "wagtailcore_page"."url_path", "wagtailcore_page"."owner_id", "wagtailcore_page"."seo_title", "wagtailcore_page"."show_in_menus", "wagtailcore_page"."search_description", "wagtailcore_page"."go_live_at", "wagtailcore_page"."expire_at", "wagtailcore_page"."expired", "wagtailcore_page"."locked", "wagtailcore_page"."first_published_at", "wagtailcore_page"."last_published_at", "wagtailcore_page"."latest_revision_created_at", "wagtailcore_page"."live_revision_id"FROM "wagtailcore_site" INNER JOIN "wagtailcore_page" ON ("wagtailcore_site"."root_page_id" = "wagtailcore_page"."id") WHERE ("wagtailcore_site"."hostname" = '''127.0.0.1''' OR "wagtailcore_site"."is_default_site" = 'True') ORDER BY "match" ASC | 98,487335358% | 144,35 | SelExpl
  | 
`
This call takes on my desktop computer (in debug mode with sqlite) 150ms. Is there something wrong?
And why is this SQL query also called on a none wagtail page?

### Issue Summary

Wagtail is calling SQL queries which I don't need

**Comment by gasman** [comment]
Thanks for the report @sowinski! This query is called from the wagtail.wagtailcore.middleware.SiteMiddleware class to populate the `request.site` variable. I agree that running this query on every page (including ones that have no relation to Wagtail) is undesirable, and ideally I'd like to eliminate this middleware completely.

**Comment by BertrandBordage** [comment]
Well, the site object may be needed on non-Wagtail parts of a site, depending on how it is built. For example, you may access the site object to obtain a setting object from `wagtail.contrib.settings`.

So there's no way to know if `request.site` will be needed unless you use it. Sounds familiar? That's what we call a lazy object in Django: complex computing is delayed until needed the first time in a request.

Which leads me to this conclusion: we should make `request.site` a lazy object for this kind of optimization. Unfortunately, this will be useful mostly on small projects, as most medium Wagtail sites I've been working on use `request.site` globally.

**Comment by gasman** [comment]
@BertrandBordage It would be good to do both, I think. Making `request.site` a lazy object would eliminate the redundant query in the case that the middleware can't be removed (e.g. because existing code on the site depends on it), but having the middleware there at all feels unnecessarily intrusive, and is overhead that we don't need.

(There also seems to be a common perception that our SiteMiddleware creates an incompatibility with `django.contrib.sites` - I'm yet to pin down whether that's really true, but if we can avoid the issue completely, that has to be a good thing :-) )

I propose that we handle this as follows:

* Update the `Site.find_for_request(request)` method to cache the resolved site on the request object, using a suitably non-intrusive name such as `request._wagtail_site`
* Update all Wagtail code that uses `request.site` to use `Site.find_for_request(request)` instead. (I suppose we'll need to provide a template tag too...)
* Rewrite SiteMiddleware so that it sets `request.site` to a lazy object* that calls `Site.find_for_request` (*or whatever Python construct makes sense, given that `Site.find_for_request` is doing the caching now...)
* Deprecate SiteMiddleware

**Comment by RNCTX** [comment]
In testing the most recent linked PR #5673 which implements all of this as you recommend above, the fact that the new template tag contains a leading underscore makes it unusable alone in a template.  This appears to be a django restriction:

<img width="778" alt="Screen Shot 2020-01-16 at 2 14 38 AM" src="https://user-images.githubusercontent.com/13775820/72505872-672a3500-3806-11ea-8efe-6f7d32520f1f.png">

You can guess the problem this creates by looking at the url in the error above.  Let's say I have this email unsubscribe template, which only gets a user object context from my view function that calls it.  It's pretty easy in the functionality before this patch to simply throw `{{ request.site.site_name }}` into the template to cause a query for the site name for some menu item that needs the site name, like the browser tab title.

**Comment by gasman** [comment]
@RNCTX You're not expected to use `request._wagtail_site` directly in a template - you should use something like `{% wagtail_site as current_site %}` (which sets the variable `current_site`). By making it an internal variable that's always accessed through a function / tag, we can initialise the variable on first call, rather than having to do it up-front in middleware.

**Comment by RNCTX** [comment]
It does work without the middleware.

Django provides the request variable in the `django.core.context_processors.request` processor, and wagtail_site is a valid request filter because of this, right?

https://github.com/wagtail/wagtail/blob/f745aae9d077256fa5c8f4e3e33df91fd30555b1/wagtail/core/models.py#L116

I use a set of wagtail boilerplate pages/snippets on a site (coderedcms) that loads site objects in templates this way, that's how I stumbled on this.  Seems like the functionality could stay by losing the underscore, regardless of which way it's called into the templates.

**Comment by gasman** [comment]
@RNCTX `request._wagtail_site` will be undefined if you try to access it before the first call to `Site.find_for_request`.

**Comment by timmysmalls** [comment]
@RNCTX I hope I can get back to this soon! This weekend if I'm lucky. I believe what you're asking for is also what @ababic was referring to. Apart from that, I hope my test refactors have taken away most if not all doubts about the backward compatibility of this new implementation, which I believe was a concern a few months back.

**Comment by RNCTX** [comment]
Yes, it's all working fine for me, thanks!

I suspect the big thing that most people will run into related to this is the conflict with user registration django packages like allauth, that's what I was trying to implement with wagtail when I ran across this.

**Comment by timmysmalls** [comment]
@RNCTX Same here! Allauth. And that's really a big one for me. Wagtail is, as far as I'm concerned, the best CMS out there today, period. I also love Netlify CMS, with its radical new approach, but as far as large, back-end heavy projects are concerned, Wagtail still comes out on top.

But this incompatibility is really a thorn in my eye. It just means if I need social auth on a project, Wagtail is out. In fact, if I need the regular Django sites framework for anything at all, Wagtail is out. Because, in a sense, Wagtail is not fully compatible with the framework it's built upon. And social authentication is not an uncommon feature request. And at the root of all this is a simple naming collision of `request.site`... I'm very busy this weekend, but I really hope to get to this asap, and hopefully, lay this thing to rest once and for all. If anyone wants to help out, just submit a PR to the wagtail repo I have on my account. Hopefully we can get it merged.

**Comment by rjsnh1522** [comment]
Hi,

I am still getting this error. using waigtail=2.8. can you tell me how to resolve it. please 
when I comment the  ` 'wagtail.core.middleware.SiteMiddleware'`,  `'wagtail.contrib.redirects.middleware.RedirectMiddleware'` middleware my existing site works fine.

Please tell me how to resolve it.

**Comment by gasman** [comment]
@rjsnh1522 There is no fix yet - we're still working on it.

**Comment by rjsnh1522** [comment]
@gasman  any workaround. ? I am using it with saleor. if there is no fix I will have to change lots of code at my end

**Comment by gasman** [comment]
Fixed in #5787
