### ISSUE TITLE
Pass template context into the construct_wagtail_userbar hook

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3847]
In some cases it could be useful to have template context in the `construct_wagtail_userbar` hooks to add custom menu items depending on current page (as Wagtail does with "Edit this page", "Add a child page" and other menu items).

For example, when we have a `ShopPage` that can contain `ShopsNewsIndex `, `ShopsTutorialIndex` pages and some other page types as child pages. The `ShopsNewsIndex`, `ShopsTutorialIndex`pages are most popular options so we want to create a shortcut links for these pages (see the screenshot in the end of the ticket).

To achieve this we need to write the following hook:

```python
from django.template.loader import render_to_string
from wagtail.wagtailadmin.userbar import BaseItem as BaseUserbarItem, AddPageItem
from wagtail.wagtailcore import hooks

from shops.models import ShopPage, ShopsNewsIndex, ShopsTutorialIndex


# Additional wagtail userbar menu items
class ShopExtraUserbarItems(BaseUserbarItem):
    template = 'wagtailadmin/userbar/item_page_shop_extra_links.html'

    def __init__(self, page):
        self.page = page

    def render(self, request):
        # Don't render if the page doesn't have an id
        if not self.page.id:
            return ''

        # Don't render if it's not a ShopPage page instance
        if not isinstance(self.page.specific, ShopPage):
            return ''

        news_index = ShopsNewsIndex.objects.child_of(self.page).first()
        tutorials_index = ShopsTutorialIndex.objects.child_of(self.page).first()

        index_pages = [
            (news_index, 'Add news'),
            (tutorials_index, 'Add tutorials'),
        ]
        available_index_pages = []

        # Don't render items if user doesn't have ability to add children
        for page, link_text in index_pages:
            permission_checker = page.permissions_for_user(request.user)
            if permission_checker.can_add_subpage():
                available_index_pages.append(
                    (page, link_text)
                )

        if not available_index_pages:
            return ''

        context = {
            'self': self,
            'request': request,
            'available_index_pages': available_index_pages,
        }

        return render_to_string(self.template, context, request=request)


@hooks.register('construct_wagtail_userbar')
def shop_extra_userbar_items(request, items):  # noqa
    # We have to get a page instance from another menu item (defined by Wagtail),
    # because Wagtail doesn't pass context into construct_wagtail_userbar hook functions,
    # so we can't construct menu.
    page = None
    for item in items:
        if isinstance(item, AddPageItem):
            page = item.page
            break

    # If can'te find a page instance,
    # don't add ShopExtraUserbarItems into the items list
    if not page:
        return

    # Update the items list
    items.append(ShopExtraUserbarItems(page))

```

Wagtail uses context, but doesn't pass it into hooks: https://github.com/wagtail/wagtail/blob/921cee4707ea21363d27838370b8f38d8065a3a1/wagtail/wagtailadmin/templatetags/wagtailuserbar.py#L54-L83

Also, I think, `construct_wagtail_userbar` hooks should not modify `items`: they should return a new array of items.

---

![image](https://user-images.githubusercontent.com/509198/30281851-73a5a128-970b-11e7-8a42-7f05e15e72fd.png)

**Comment by lb-** [comment]
Agreed, I have had to get the request with a work around when we have wanted to do some request specific userbar changes.

**Comment by bogh** [comment]
I suggest that the `page` property is also passed. 

Also, why is `Page.objects.get()` called individually for each item, even though the `page` variable from the context is already the page we neewd.

**Comment by lb-** [comment]
Proposed solution for this is to pass `page` as a third arg to the hook, as we are already pulling `request` from `context we do not really want to pass `context` as the third arg. Nor do we want to make a huge breaking change where everyone needs to update the first arg to be `context.

There is a function, that lets us wrap a function for backwards compatibility `accepts_kwarg` with a warning about what kwargs to use, so maybe we go with `page=page`. Otherwise this could be a breaking change or we may need another way to ensure we can support existing usage.

### Notes

https://github.com/wagtail/wagtail/blob/e674b44acb5cea698111925f65ba0fd128d48fc7/wagtail/admin/templatetags/wagtailuserbar.py#L87-L88

* Update `fn(request, items, page)`

In each usage of https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/userbar.py we also update the hook call with the `page` as the last param.

`docs/reference/hooks.md`

> Update docs

Add or remove items from the wagtail userbar. Add, edit, and moderation tools are provided by default.

The callable passed into the hook must take the `request` object a list of menu objects (`items`) and the `page` instance. The menu item objects must have a `render` method which can take a `request` object and return the HTML string representing the menu item. See the userbar templates and menu item classes for more information.

> Update example

```
def add_puppy_link_item(request, items, page):
    return items.append(UserbarPuppyLinkItem())
```

**Comment by SebCorbin** [comment]
Interested in this, will work on it if I have time, three remarks:
- I suggest we change the issue title to _Pass page context into the construct_wagtail_userbar hook_
- why not use `django.inspect.get_func_args` to allow both positional and keyword arguments?
- should we fire a future breaking change warning so that `page` arg will become mandatory in the future?
