### ISSUE TITLE
Specifying rich text features does not whitelist only these features

### ISSUE THREAD

**Issue by BertrandBordage** [wagtail/wagtail#3852]
Starting Wagtail 1.12, we can specify the features allowed in a rich text field, for example just bold and italic.

Unfortunately, there is no server side validation for that. I could work around that by overriding the `clean` method of a given model and by defining a subclass of `DbWhitelister` that contains a subset of the `element_rules` dictionary.

So if you copy/paste content from another field or document, it keeps links etc even if you didn’t allow that feature.

A solution for that could be to define a dictionary linking `features` to `element_rules`. Then in the `clean` method of `RichTextField` or block, we could define a new instance of `DbWhitelister` that gets the class attribute `element_rules` overridden by a homonym instance class containing a subset of `element_rules`.

**Comment by gasman** [comment]
Bumping to 1.14. I've made some progress on this at https://github.com/gasman/wagtail/tree/feature/feature-based-whitelisting, but dealing with embed and link handlers is going to need careful planning, so it would be a bad idea to try and rush this through for 1.13.

Currently those link/embed handler objects (PageLinkHandler etc) perform three tasks:

1. Converting the pseudo-HTML from the database into real HTML for front-end rendering
2. Converting the pseudo-HTML from the database into HTML that the rich text editor can use (with page IDs stashed in `data-id` attributes, etc)
3. Converting the output of the rich text editor to database-pseudo-HTML.

It seems to make a lot of sense to decouple task 1 from the other two, since:

* When we introduce draft.js or any other rich text editor that has a non-HTML native data format, we'll be swapping in another component to perform tasks 2 and 3 (converting between that data format and database-pseudo-HTML) while leaving task 1 unchanged
* Task 1 can't be made aware of rich text feature flags - at least, not without some major architectural changes - because we have to do it in contexts like the `|richtext` filter, where we only have access to the string itself, and not the model field (which would tell us which features are active)
* It neatly corresponds to the dividing line between wagtailcore (task 1) and wagtailadmin (tasks 2/3)

Currently this whole API is undocumented (#1094), which is good news for us as it means we have a lot of leeway for refactoring it without having to worry about backwards compatibility. However, once this is integrated with rich text features, it really _does_ need to get documented, which makes it all the more important to put in the extra effort now to get the API as polished as it can be.

One thing we almost certainly want to do is fix the hack where the handlers receive attributes as HTML-escaped strings. This means that my latest bugfixes #3879 and #3882 become invalid, but that's a necessary price to pay :-)

**Comment by gasman** [comment]
Completed in #4079
