### ISSUE TITLE
Copy pages without revisions and metadata like first_published_at

### ISSUE THREAD

**Issue by timorieber** [wagtail/wagtail#3891]
When creating a new page it is often easier to copy an existing page with similar content than starting from scratch. The current behaviour when copying a page has some drawbacks and feels more like cloning a page. Wagtail also copies all revisions and metadata specific to this page, like `first_published_at`.

For example if you then publish the page and order by `first_published_at` descending you'll find the page next to the page it was copied from. Most of the time this is not the expected behaviour (at least from the authors perspective).

Perhaps it would be an idea to make copying of revisions and metadata (to be specified) optional? Or to be backwards compatible opt in to exclude this information?

**Comment by lb-** [comment]
@timorieber 

The next version should have the ability to override which fields are excluded when copying (which would include metadata fields). I think that would be sufficient for now to fix the issue you mentioned.

See - Issue #3920 and the merged pull request for it #3987

**Comment by lb-** [comment]
Closing for now, will reopen if this is an issue after that override becomes available.

**Comment by gasman** [comment]
I'm not so sure that #3987 addresses this - that only lets you override the behaviour on a per-page-type level, and I can't see the use-case for some page types preserving page history and not others. More likely, you'd want to make this decision either globally, or on a case-by-case basis at the point of copying a page (e.g. with a 'preserve page history' checkbox).

Having said that, I don't think we need to make this configurable. I think the `first_published_at` behaviour is just plain broken - I can't see any scenario where preserving it is the desirable or expected behaviour - and we should fix it so that the new copy has it set to null, or the current datetime if it's being published immediately. Conversely, I can't see any reason why copying revisions is a _bad_ thing - any other opinions there?

**Comment by lb-** [comment]
@gasman good call.

As we already ask if the user wants to publish copied page, how about:

* When Publish copied page is ticked: Set the `first_published_at` as now.
* When Publish copied page is unticked: Set the `first_published_at` to null as this is not yet published.

I think it is helpful having the page revision history attached to copies, I also don't see a reason to remove them.

**Comment by gasman** [comment]
@lb- Sounds good, yep.

**Comment by lb-** [comment]
Bit more digging - turns out this is definitely the intended behaviour so something odd is happening, I will take a bigger look when I can but here are my notes so far.

Whenever a copy is made that is set to `keep_live`, a new revision is created, this new revision's created_at (which will be now) sets `first_published_at` and `last_published_at` on the page.

This can be seen as being tested here:
https://github.com/wagtail/wagtail/blob/85b7b7c0dfbcd12874837b5b553b52dbb65eb3de/wagtail/core/tests/test_page_model.py#L605-L633

And in the model definition here:
https://github.com/wagtail/wagtail/blob/85b7b7c0dfbcd12874837b5b553b52dbb65eb3de/wagtail/core/models.py#L1149-L1154

If you do not elect to publish the page immediately, `first_published_at` and `last_published_at` are set to None, this means that when publishing this revision for the first time it should set those values to now. See models.py
https://github.com/wagtail/wagtail/blob/85b7b7c0dfbcd12874837b5b553b52dbb65eb3de/wagtail/core/models.py#L1488-L1496

**Comment by timorieber** [comment]
Thanks @lb- and @gasman for your comments and investigation.

I've been following #3987 very interested, but I'm with @gasman that this decision should be made globally or on a page-by-page basis. As for now this could be solved by excluding the same metadata in every model.

Copying revisions is not a bad thing by itself, but feels unnecessary when an author just wants to start with some content from an existing page (e.g. tags or related links), but the pages are not related at all. This revisions could also led to confusion when another author is digging through revisions and is wondering why parts of the content had changed dramatically (because the original author just threw them away while copying).

But I agree that the first focus should be to fix the behavior of `first_published_at` and `last_published_at`.

**Comment by lb-** [comment]
FWIW it looks as though the ability to **not** copy past revisions is built into the model (including tests), it is just not presented in the UI, so it might be possible to present an option on the copy page that is ticked by default 'copy revisions' or something like that.

https://github.com/wagtail/wagtail/blob/85b7b7c0dfbcd12874837b5b553b52dbb65eb3de/wagtail/core/models.py#L1105-L1136

**Comment by lb-** [comment]
@timorieber I probably should have done this before I started digging into this one but...

I have just tried to replicate the specific issue you mentioned and I cannot get it to do the same thing.

What version of Wagtail were/are you using that has this issue (with `first_published_at` and `last_published_at` being copied from the source page).

I have made copies of some pages in the bakerydemo app and they all update the publish dates accurately on copies. It looks like this was fixed around 1.11 but there are no release notes specific to this issue, some notes about how revision dates work though - http://docs.wagtail.io/en/v1.13.1/releases/1.11.html#other-features

**Comment by timorieber** [comment]
Thanks, @lb- !

You are right, with Wagtail 1.13.1 this could not be replicated. We upgraded from 1.9 to 1.13 in October, so it is very likely that you're right. I should have reported this as a bug rather then tie it to this CR.

If the wagtail core team thinks that the other part of this CR (decide when to copy revisions and metadata) still makes sense I will open another, clean CR.
