### ISSUE TITLE
Custom image form support needed.

### ISSUE THREAD

**Issue by kxxoling** [wagtail/wagtail#3892]
Wagtail have a flexible custom image model structure by ``WAGTAILIMAGES_IMAGE_MODEL`` but don't have a corresponding ``WAGTAILIMAGES_IMAGE_FORM`` support.

In my case, I've added 2 unique together fields in my ``CustomImage`` model, it will fire a ``IntegrityError`` issue when a image is uploaded twice. But there's no place to catch it.

I would also like to save image hash as a unique key, this will also be take cared of in custom image form.

**Comment by gasman** [comment]
Thanks for the report @kxxoling!

Rather than offering more 'hooks' into the wagtailimages app to support more and more complex customisations, we plan to convert the wagtailimages views into class-based views (using [generic views](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/views/generic.py) and [viewsets](https://github.com/wagtail/wagtail/tree/master/wagtail/wagtailadmin/viewsets)). This way, it'll be possible to define a custom subclass of the wagtailimages app, that inherits as much or as little of the core functionality as you need.

**Comment by zerolab** [comment]
This is available as of 2.12 via [`WAGTAILIMAGES_IMAGE_FORM_BASE`](https://docs.wagtail.org/en/stable/reference/settings.html#wagtailimages-image-form-base)
