### ISSUE TITLE
Reorganise module names

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3918]
Top-level issue to track progress in renaming modules as proposed in https://github.com/wagtail/rfcs/blob/master/text/012-rationalise-apps.md - further tickets may be opened and linked here to track sub-tasks.

- [x] Create Wagtail 2.0 branch of bakerydemo
- [x] Update vagrant-wagtail-develop to use that branch
- [ ] Move each module in turn, updating documentation and bakerydemo at the same time:
  - [ ] wagtail.wagtailcore -> wagtail.core
  - [ ] wagtail.wagtailadmin -> wagtail.admin
  - [ ] wagtail.wagtaildocs -> wagtail.documents
  - [ ] wagtail.wagtailembeds -> wagtail.embeds
  - [ ] wagtail.wagtailimages -> wagtail.images
  - [ ] wagtail.wagtailsearch -> wagtail.search
  - [ ] wagtail.wagtailsites -> wagtail.sites
  - [ ] wagtail.wagtailsnippets -> wagtail.snippets
  - [ ] wagtail.wagtailusers -> wagtail.users
  - [ ] wagtail.wagtailforms -> wagtail.contrib.forms
  - [ ] wagtail.wagtailredirects -> wagtail.contrib.redirects
  - [x] wagtail.contrib.wagtailapi -> remove completely
  - [ ] wagtail.contrib.wagtailfrontendcache -> wagtail.contrib.frontend_cache
  - [ ] wagtail.contrib.wagtailroutablepage -> wagtail.contrib.routable_page
  - [ ] wagtail.contrib.wagtailsearchpromotions -> wagtail.contrib.search_promotions
  - [ ] wagtail.contrib.wagtailsitemaps -> wagtail.contrib.sitemaps
  - [ ] wagtail.contrib.wagtailstyleguide -> wagtail.contrib.styleguide

Since this is likely to be a large and disruptive change to the codebase, we should aim to keep individual PRs as small and focused as possible, and review them promptly.

**Comment by chosak** [comment]
@gasman @kaedroho how do you want to handle migrations? The RFC mentions a script to help with renaming module imports, but doesn't mention data migrations.

The problem is that renaming an app like `wagtail.wagtailcore` to `wagtail.core`, assuming an associated change to that model's [app config](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailcore/apps.py#L7), will result in different table names (for example, `core_page` instead of the current `wagtailcore_page`). Similarly, the migrations table would use different names like `core_0001` instead of `wagtailcore_0001`.

One possibility (which I think would be my preference) would be to keep the existing app "names" (e.g. even if the path is `wagtail.core`, the app name is still `wagtailcore`). This actually might be a nice thing; one could imagine that in a large Django/Wagtail project there might be confusion/potential conflict for the more generic names like `users` and `forms`. If this is the desired approach, perhaps we could update the RFC to clarify this?

If instead we do want to do the full rename, then actually migrating existing tables would be a tricky task ([for example](https://markusholtermann.eu/2016/04/django-migrations-recipe-3/)). One option would be to just not support migrations of existing data, but this would pretty strongly disincentivize upgrades of existing Wagtail sites.

**Comment by gasman** [comment]
Hi @chosak - yep, app labels / table names should be kept as they are, with the 'wagtail' prefix. It's just the import paths that we want to change.

**Comment by chosak** [comment]
@gasman thanks; how about template subdirectories (e.g. `wagtailcore/templates/wagtailcore`) and template tags (e.g. `wagtailcore/templatetags/wagtailcore_tags.py` and `{% load wagtailcore_tags %}`)?

**Comment by gasman** [comment]
The general rule should be: in any context where Wagtail's modules appear in the same flat namespace as the project's (or Django's) modules, we need to keep the `wagtail` prefix to avoid collisions. So yep, that would include template directories and template tags.

**Comment by kaedroho** [comment]
> Update vagrant-wagtail-develop to use that branch

Done in https://github.com/wagtail/vagrant-wagtail-develop/pull/11

**Comment by kaedroho** [comment]
Done ``wagtail.wagtailcore`` => ``wagtail.core`` conversion in https://github.com/wagtail/wagtail/pull/4031

I've disabled isort in this branch. I think we should leave it disabled until every module is renamed, then resort all the imports in one go. This will be much easier than having to resolve the merge conflicts caused by sorting every single time we want to merge a PR.

**Comment by gasman** [comment]
Completed in #4069.
