### ISSUE TITLE
Userbar z-index is 1

### ISSUE THREAD

**Issue by mgjbroadbent** [wagtail/wagtail#3944]
### Issue Summary

The z-index of the wagtail-userbar element is now set to 1 in the pypi version of wagtail v1.13 instead of 9999 which was used in v1.12.2.  This causes the user bar to appear under page elements that use a z-index of greater than 1.

### Steps to Reproduce

* Download wagtail v1.13 using pip.
* Open the file <python package>/wagtail/wagtailadmin/static/wagtailadmin/css/userbar.css
* Locate the .wagtail-userbar CSS element.
* Observe the z-index in the .wagtail-userbar CSS element:

`... .wagtail-userbar{position:fixed;z-index:1; ...`

In v.1.12.2 version this is:

```
...
.wagtail-userbar {
  position: fixed;
  z-index: 9999;
...
```

### Technical details

The source scss file shows the z-index is set to 9999 as expected:
* https://github.com/wagtail/wagtail/blob/05adf2c85deb534e213591158cecbd56571c8e84/wagtail/wagtailadmin/static_src/wagtailadmin/scss/userbar.scss#L90

**Comment by strindhaug** [comment]
I guess this might be caused by cssnano "optimizing" z-index by default in some versions:
https://github.com/ben-eb/gulp-cssnano/issues/85

Add `zindex: false` to the options of cssnano to stop it from messing with the z-index.

**Comment by gasman** [comment]
@strindhaug Good catch - thanks for the info!

**Comment by strindhaug** [comment]
Yeah, I wasted a few hours some days ago trying to figure why on earth the z-index was 1 in production when it was 999 locally (running unminified); so the  "z-index is 1" title jumped out to me when i glanced at the issue list.

**Comment by gasman** [comment]
Digging into the relevant code, I see that the use of cssnano (and a couple of other bits and pieces related to performance testing) is conditional on `NODE_ENV=production`, which will usually only happen when we're preparing the final release (or release candidate). Clearly, this vastly limits our ability to catch bugs like this during development...

ping @thibaudcolas @jjanssen @vincentaudebert - what can we do to ensure that the frontend assets on our development builds remain as close as possible to the final release version? Would it be reasonable to update our config to always apply 'production' settings on `npm run build` - or would this make development more difficult (e.g. loss of sourcemaps)?

**Comment by vincentaudebert** [comment]
@gasman it has been a while I didn't dive into wagtail FED code but I'm pretty sure that as you said if you switch to prod mode you will lose the sourcemaps and therefore it will be hard to debug anything FED wise.

Maybe @loicteixeira could confirm as he has been working on wagtail recently. Even if this is FED :)

I reckon that the quickest way to check bugs like that is to run the prod mode for each FED PR and make sure everything is like what it should be.
Just my opinion.

**Comment by gasman** [comment]
I'd much prefer to adopt a policy where people are using production-mode assets as the default state, and only switch to development mode when actively doing front-end dev that requires it. Relying on one-off tests during code review to catch these bugs, while spending the other 99% of the time in a development environment that doesn't match "real world" Wagtail installations, seems incredibly risky.

It looks like we already have the appropriate npm commands in place to make this happen: `npm run build` or `npm run watch` when doing front-end dev, and `npm run dist` at all other times - so perhaps we just need to update our [build scripts](https://github.com/wagtail/vagrant-wagtail-develop/blob/ab9100c17a6044d58be55dc21c762be294f67193/vagrant/provision.sh#L42) and [documentation](http://docs.wagtail.io/en/v1.13/contributing/developing.html#setting-up-the-wagtail-codebase) to steer people towards `npm run dist`.

I wonder if there's any more "nudge theory" we can apply to encourage this further, without making life too annoying for front-end devs... renaming the commands to `build-dev` and `build`? Outputting a warning on the `./manage.py` command line whenever development-mode assets are in use?

**Comment by vincentaudebert** [comment]
@gasman sorry and don't be offended but I don't see why suddenly having a dev and a prod build is becoming such a big deal.
There are plenty if not all the projects that are running that way. And they run well.
I think the issue here was a misconfiguration and it has been fixed.
I would rather spend more time making sure the config is fine and doing what we want it to do.

Also we could take the issue the other way around and fix the CSS to be z-index: 1 instead of 9999? What's the point of having 9999 if you can have 1 as the optimised config is saying so?

Again, just my opinion. Also keep in mind that running a prod build is taking slightly longer than just a dev one.

**Comment by thibaudcolas** [comment]
I'll see what happens when using `cssnano` in dev mode. Definitely want to minimise differences between environments, but source maps and compilation times are also important.

For our build scripts, we could probably remove `npm run build` or make it an alias of `dist`. These should be the scripts people use when they aren't doing front-end dev , and I think we can then presume the extra compilation time / absence of source maps isn't a problem.

**Comment by mgjbroadbent** [comment]
Thanks for putting the time and effort into fixing this.  It's much appreciated. 👍

**Comment by gasman** [comment]
@mgjbroadbent Thanks for the report!
