### ISSUE TITLE
Label inconsistency between structblocks and streamblocks

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/wagtail#3952]
StructBlock children a `:` added to their labels.
As per 
```<label{% if child.id_for_label %} for="{{ child.id_for_label }}"{% endif %}>{{ child.block.label }}:</label>``` in struct.html

StreamBlock children don't.

Visually this creates an inconsistency where structblocks and streamblocks are mixed (e.g. a structblock that contains a streamfield element, or a streamfield element that contains a structblock)

It also feels slightly unnecessarily opinionated. Is there a particular reason we have it?

**Comment by gasman** [comment]
Hi @heymonkeyriot,
I think part of the reason is due to some undesirable opinion-pushing on Django's part...

Some time around Django 1.7, Django started adding colons to form field labels generated through its own form helpers (`form.as_p()` et al). @nealtodd has had more direct wranglings with this issue than I have, and can probably recall the details better :-)

Since we're using those helpers elsewhere in Wagtail, and StructBlock child fields are styled to match that label style, we have to add the colon to be consistent. On the other hand, StreamBlock child labels (currently) have their own entirely separate style where we're not subject to that constraint - a colon in that top-right tab position (where it's visually separated from the actual field(s)) would probably look weird anyway.

I think we'd be perfectly happy to standardise on no-colon, if Django can be coaxed into letting us do that. (Maybe it's a bit more friendly in current Django versions, now that form fields have template-based rendering?)

**Comment by heymonkeyriot** [comment]
Ah another reason to dislike the `form.as_p()` abstraction 🙈 I had forgotten about this.

Though where are we using this within Wagtail? e.g. would it be possible to build out those form helpers manually (so we can control the label rendering) and/or if they're not used widely perhaps we can leave the colons on them to increase the consistency on page and snippet pages?

**Comment by thibaudcolas** [comment]
I believe this has been fixed as of the re-implementation of StreamField’s styles a few releases ago. Closing.
