### ISSUE TITLE
"UnicodeEncodeError" when i trying visit a page with categories i(in snippets)

### ISSUE THREAD

**Issue by Sibiryakanton** [wagtail/wagtail#3959]
That error appeared, when i trying to visit my list of categories.

The solution of that error is simple: i just changed __str__ method:
 def __str__(self):
        return self.name.encode('utf-8')

But when i edit that name of categories, error appeared again. Can you fix it?

**Comment by gasman** [comment]
Hi @Sibiryakanton,
Sorry, there's not enough information here to understand what you mean. Please can you open a new bug report, filling in the requested information fields and giving a full description of how to reproduce this issue?

**Comment by ababic** [comment]
Hi @Sibiryakanton,

This sounds like something I experienced with an old site recently running on Python 2.4, and occurs in places where the Wagtail tries to get a default string representation of a model instance. 

Rather than being a Wagtail-specific issue though, the problem is more related to how Python 2 string encoding works. The most appropriate way to get around this issue (using Django 1.5 or later) is to use the `django.utils.encoding.python_2_unicode_compatible` decorator on your model, which then allows you to just add a `__str__()` method to your model without having to worry about encoding the string.  (For more info and examples see: https://consideratecode.com/2017/08/25/what-does-python_2_unicode_compatible-do/)

Using this approach consistently will help reduce the amount of special-case code in your project for making things work Python 2, and make it easier to migrate the project to Python 3 if that's something that might happen in future.
