### ISSUE TITLE
Model admin list filters with custom filters on related model field is not allowed

### ISSUE THREAD

**Issue by todd-dembrey** [wagtail/wagtail#3980]
### Issue Summary

Custom filters on a related model's field using model admin results in a `DisallowedModelAdminLookup`. 

This is because the check on the line below cant inspect the inner tuple when a list filter is defined as  `list_filter = (('related_model__field', CustomListFilter),)`
https://github.com/wagtail/wagtail/blob/aeef5a54541640988eb319fab3331088e57d080a/wagtail/contrib/modeladmin/views.py#L329

For the normal case `list_filter = ('related_model__field',)` the check of `'related_model__field' in ('related_model__field',)` will be `True`.

Custom filters work fine for the models own fields as the `lookup_allowed` method returns `True` for all fields on the model (line 326 `len(parts)==1`) e.g. `list_filter = (('field', CustomListFilter),)`

**Comment by ababic** [comment]
Thank you for raising @todd-dembrey.

I wouldn't class this as an issue per se, because the docs don't mention support for custom filters at all. There's some basic support built in, but it isn't covered by tests and is considered experimental. I would class this as a feature request, which in order to implement, the following will need to happen:

1. The core development team agree whether modeladmin should support custom Django filters at all, and which definition mechanisms they'd like to support.
2. Support being added/removed/modified appropriately
3. Tests being added
4. Docs being updated appropriately

**Comment by mihow** [comment]
@todd-dembrey You can still make a filter for a related field in the current Wagtail modeladmin. Here is one example:

```python
from django.contrib.admin import SimpleListFilter

class ArtistFilter(SimpleListFilter):
    title = "Artist"
    parameter_name = "artist"

    def lookups(self, request, model_admin):
        artists = set([c.artist for c in model_admin.model.objects.select_related('artist').all()])
        return [(c.id, c.display_name) for c in artists]

    def queryset(self, request, queryset):
        try:
            artist_id = int(self.value())
        except ValueError:
            return queryset.none()
        else:
            return queryset.filter(artist__id=artist_id)

class ArtworkAdmin(ModelAdmin):
    model = Artwork
    list_filter = (ArtistFilter,)
```

**Comment by ababic** [comment]
Upon testing, it appears that changes already made in #5226 (which made it into the 2.6 release) resolve this problem, as the lookups are no longer checked for suitability :)
