### ISSUE TITLE
Correcting a typo through browser spelling doesn't count as a changed field in Hallo rich text field

### ISSUE THREAD

**Issue by jordanyeo** [wagtail/wagtail#4016]
### Issue Summary

If you open up an existing page, see in a richtext field that there is a spelling mistake, use your browser's spelling correction tool and hit publish, the change isn't saved. Assuming that wagtail checks to see if a textarea has had text physically typed in it, instead of the contents being changed.

### Steps to Reproduce

Find any page that has a rich text field, and a spelling mistake inside of it.
Right click on the spelling mistake, correct the word
Hit publish
Your changes won't be saved.

### Technical details

Latest wagtail, Google Chrome.

**Comment by gasman** [comment]
Thanks for the report @jordanyeo! The rich text field is backed by a hidden input which is updated in response to changes in the text, so it sounds like whatever event we're listening on isn't being triggered by the browser spellchecker.

We're planning to replace the rich text editor in the next release of Wagtail (see #2409), so this may well get fixed automatically along the way... will re-test when that work is complete.

**Comment by thibaudcolas** [comment]
Draft.js (on which the new editor is built) has [documentation about spell checking](https://draftjs.org/docs/api-reference-editor.html#spellcheck), so I think we can assume it will work (except in IE, as the docs point out). 

Also, at the moment the editor doesn't have spell check enabled – do we all agree it should be turned on once in Wagtail?

**Comment by lb-** [comment]
I just tested out Draft.js [Examples](https://github.com/facebook/draft-js/tree/master/examples) locally on version 0.9.1 and 0.10.1 and stage changes are triggered on the right click and the subsequent change after selecting a correct spelling.

However, the spelling option must be turned on for this to work, otherwise the browser does not seem to treat as text in the same way, so I recommend it should be on by default in Wagtail.

Tested: Chrome 62, Safari 11, Firefox 48 all on macOS Sierra 10.12.6

**Comment by thibaudcolas** [comment]
The new editor doesn't have this issue. Apparently Draft.js has other spellcheck issues in MS Edge and Android 5.0, but I haven't looked into these yet so I think we can close for now.
