### ISSUE TITLE
Make user input fields consistent

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/wagtail#4114]
Depending on the type of field a user interacts with the text will either be serif or sans-serif. This is slightly confusing because it means there's a lack of visual consistency between items the user can editorially control. It was something that was discussed changing at the Bristol sprint.

In #3942 there was a commit to change `input`, `textarea`, `select`, `.richtext`, and `.tagit` to always use $font-serif. That perhaps goes too far since login and search will then be serif - though I have to say that feels like the right direction to take if we're aiming for consistency. In any case something that I think requires more discussion before it's put in a PR.

**Comment by tmsndrs** [comment]
I wonder if there is a meaningful difference between content an editor is creating being serif and all input text being serif. For example I think that it makes sense for all fields used on the page edit screen being serif because it's content the editor is creating. However I'm not sure about fields such as search, login etc that are part of the admin. Certainly worth thinking about and there should be a rational either way.

**Comment by thibaudcolas** [comment]
This has been addressed as part of #7724, where we decided to use sans serif everywhere.
