### ISSUE TITLE
Change to use Material icons

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#4152]
Really just wanted to start a discussion about this for now. The Wagtail icon set is pretty incomplete. It's based on Font Awesome icons for the most part which I personally find ugly. But also it would be good to have a clearer way to include more icons than we currently have.

https://material.io/icons/

I know there were performance considerations around this so that's one thing to consider. 

Many of the icons would likely fail testing and devs are forced to use inappropriate icons for custom UI such as blocks in Streamfield. 

Further reading: 
https://www.nngroup.com/articles/icon-testing/
https://www.nngroup.com/articles/icon-usability/

Related: 
#4095
#4040
#3942
#1224
#2349

**Comment by thibaudcolas** [comment]
@tmsndrs there are two separate considerations here:

1. Whether we should change the icon set from FontAwesome to Material icons, for visual design & UX considerations.
2. Whether Wagtail should come with more icons, either out of the box or as an opt-in (#2349). 

I don't have much of an opinion about item 1. The only problem I foresee is that Material icons don't include anything related to brands. I don't know how common it is for people to need a Facebook or Twitter icon in their Wagtail sites though, or how important it is to have those as part of an icon set since brand logos won't match the set's general design anyway.

For 2., I'll add a comment about performance in #2349.

**Comment by eyesee1** [comment]
Nope to material icons.
+1 font awesome.

**Comment by tmsndrs** [comment]
@eyesee1 can you share your thinking on why? Personally I've always found Font Awesome pretty ugly but I'm pretty easy. The new FA looks a bit nicer anyway.

**Comment by eyesee1** [comment]
Well, I think we’re getting into personal taste here, and there’s no point in arguing about that.

**Comment by FlipperPA** [comment]
@tmsndrs Would developing something like Wagtail FontAwesome for material be an option? https://github.com/alexgleason/wagtailfontawesome

**Comment by eyesee1** [comment]
If someone wants to spend time to write the code to make icon packs a pluggable / configurable option, that would actually be pretty cool as long as it doesn’t hurt performance. 🤷🏽‍♂️
