### ISSUE TITLE
Wagtail needs a YouTube screencast video by a secretary for secretaries

### ISSUE THREAD

**Issue by gz1968** [wagtail/wagtail#4156]
Hello,

NEED:  Wagtail needs one specific screencast video on YouTube.  In the video, a simple office worker whose knowledge of IT is limited to Word and Excel, sits down and creates or modifies complex content pages on a large site using wagtail.  (Not a wagtail pro who pretends to be a secretary).  The person should only use the GUI admin.  The person should never change code in wagtail files via a Linux console.  The video should be oriented to newbie-wagtail office workers such as secretaries.

WHY?:  I think developers want to attract large clients.   Well after a site is up and running, one purpose of a CMS is so that lower salaried office workers can be creative in developing the content part of the site.  Pages such as Marketing, Pricing, About, Terms of Use, FAQ, etc.  What good is a CMS if wagtail pros need to be hired every time content pages and structure needs to be altered?  This runs up cost. 
 Might as well just use html only.

CURRENT SITUATION:  Every wagtail screencast video I watch on YouTube, is by a wagtail pro.  And always involves editing code in some wagtail core files with the cursor flying around.  So this just kills one of the main reasons for using a CMS, versus an html only site.  I've seen no demonstration, that a secretary can sit down, and fairly easily start being productive modifying the site content pages.  And to demonstrate how to create content pages starting with simple to complex.

MY SITUATION:  I'm looking to contract out the build of a fairly complicated Real Estate site based on Linux, PostgreSQL, Python 3, Nginx, etc.  I'm examing Wagtail.  I want to maintain my site as cheap as possible afterwards.  As the site matures, I will want to keep improving on the non-programmed content pages.  But every wagtail demonstration I watch, makes it look like a CMS for coders only.  At the end of the day, a site needs to be turned over to non-coders.

Regards

**Comment by thibaudcolas** [comment]
Hey @gz1968, thank you for the feedback. The intro video from the wagtail.io homepage is akin to what you are after: https://vimeo.com/8671978. The official editor guide is also worth mentioning: http://docs.wagtail.io/en/stable/editor_manual/index.html. It's not a screencast (those are too expensive), but is meant for exactly what you describe. 

Does this help?

The main reason why there isn't more of those comes down to focus/strategy, and cost. Wagtail generally doesn't have resources available for marketing beyond what partner organisations are willing to dedicate (see http://madewithwagtail.org/developers/). Talking from my experience, as an organisation willing to attract large clients we would rather demonstrate "what *we* can achieve with Wagtail" rather than "what Wagtail can achieve" in a broader sense. In terms of strategy, from my perspective it makes perfect sense to want to appeal to developers – they are the ones most aware of the CMS landscape, and often the decision makers.

At this stage, the most likely provider of such screencasts would be the broader Wagtail community, so I'm not sure it's worth keeping this issue open, but let's see whether others have more thought to add to this.

**Comment by tmsndrs** [comment]
I do like this as an idea. 

Another stumbling block though is that Wagtail can be highly customized. In this way no one site works in the same way as another.

**Comment by gz1968** [comment]
The intro video is not what I needed.  I saw simple text.  I saw pictures.  I'm sitting on the fence with using wagtail for ordering a site build.  That video did zero to convince me.  True wagtail is great for developers.  Well, so is html.  I can have any site built with html.  As a possible client I have two concerns on what happens when the developers have finished and are gone:
1) What is the learning curve for office workers?  Can they learn it easily?
2) How creative can office workers be in wagtail without coding?

If all my site content looks identical, because office workers are using simple forms created by developers, then I see no reason to use wagtail.  I can't transfer the creative ability of office workers to the site.  Same problem as a non-CMS html site.

I agree, amateur screencast videos should be by end-users.  But there aren't any by non-coders.  Not one.  What does that say?  Is wagtail so hard, that there is not one secretary/marketer out there, who can demonstrate how they use it?  If this is the case, then again I can't transfer the creative ability of office workers to the site.  Same problem as a non-CMS html site.

**Comment by thibaudcolas** [comment]
I understand the sentiment but I remain unconvinced that there is value in keeping track of this in an issue in this repo. This is a marketing matter, I don't see what change to what's in this repo would "resolve" this so I'll close this issue.

For the lack of screencasts specifically, I'll paraphrase myself: *The main reason why there isn't more of those comes down to focus/strategy, and cost. Wagtail generally doesn't have resources available for marketing beyond what partner organisations are willing to dedicate*. In my experience, to convince client it's **much** more effective to have an in-person workshop / demo than any screencast will ever be, no matter how good.
