### ISSUE TITLE
WAGTAIL_APPEND_SLASH is not applied to /_util/* URLs

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#4201]
If `WAGTAIL_APPEND_SLASH = False` is set in the django settings, I would expect all Wagtail-served URLs to obey it (as [the docs](http://docs.wagtail.io/en/latest/advanced_topics/settings.html#append-slash) say they should). However, neither the `/admin/*` URLs nor (as I discovered today) the `/_util/*` URLs obey this setting. 

I recognize that making every single admin URL obey it might be a pain in the butt, but there are only two `/_util` URLs (`_util/authenticate_with_password/(\d+)/(\d+)/` and `_util/login/`. _And_ they're defined in the same file where `WAGTAIL_APPEND_SLASH` is used to implement its feature (`watailcore/urls.py`).

Heck, it might be as simple as making the ending slash be always optional. Like this:

```
urlpatterns = [
    url(r'^_util/authenticate_with_password/(\d+)/(\d+)/?$', views.authenticate_with_password,
        name='wagtailcore_authenticate_with_password'),
    url(r'^_util/login/?$', auth_views.login, {'template_name': WAGTAIL_FRONTEND_LOGIN_TEMPLATE},
        name='wagtailcore_login'),

    # Front-end page views are handled through Wagtail's core.views.serve
    # mechanism
    url(serve_pattern, views.serve, name='wagtail_serve')
]
```

Or, if you want to limit it with `WAGTAIL_APPEND_SLASH`, you could do this:
```
slash = '/?' if not WAGTAIL_APPEND_SLASH else '/'
urlpatterns = [
    url(r'^_util/authenticate_with_password/(\d+)/(\d+){}$'.format(slash), 
        views.authenticate_with_password,
        name='wagtailcore_authenticate_with_password'),
    url(r'^_util/login{}$'.format(slash), auth_views.login, 
        {'template_name': WAGTAIL_FRONTEND_LOGIN_TEMPLATE},
        name='wagtailcore_login'),

    # Front-end page views are handled through Wagtail's core.views.serve
    # mechanism
    url(serve_pattern, views.serve, name='wagtail_serve')
]
```

Is there any downside to doing that? I understand why there would be a downside to doing this on Page URLs (SEO issues), but these are internal utility URLs. I'm not sure what problems this could possibly cause.

**Comment by gasman** [comment]
Hi @coredumperror,

Perhaps I'm language-lawyering here, but I wouldn't consider `/admin/` or `/_util/` to be "Wagtail-served" URLs. They're part _of_ Wagtail, but in contrast to page URLs - where Wagtail actively plays a part in interpreting the URL and selecting the appropriate page to respond with - serving them is entirely Django's responsibility.

I think it's appropriate for Wagtail to provide the `WAGTAIL_APPEND_SLASH` setting, so that the site's URL format isn't being dictated by Wagtail's opinions - but when it comes to URLs that exist for Wagtail's own functionality, I'd say it makes more sense for Wagtail to choose one convention and stick to it, rather than adding more moving parts.

**Comment by coredumperror** [comment]
Alright, that's fair.
