### ISSUE TITLE
YouTube EmbedBlock is producing a warning on the browser console

### ISSUE THREAD

**Issue by tasken** [wagtail/wagtail#4203]
### Issue Summary

When using EmbedBlock for embedding a YouTube video, the following error appears on the browser console:

`Unrecognized feature: 'autoplay'.`

It seems Chrome is making changes in the [autoplay policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py importing an EmbedBlock from wagtail.wagtailembeds.blocks.
3. Create a page using that model and insert an URL from YouTube.
4. Publish that page and go to its live URL.
5. Check browser console.
6. Warning appears.

Waring refers to the `allow="autoplay; encrypted-media"` segment in the iframe tag generated by the EmbedBlock.

### Technical details

* Python version: 3.5.3
* Django version: 1.11.8
* Wagtail version: 1.13.1
* Browser version: Chrome 63, https://whatsmybrowser.org/b/DSQ9GXL

**Comment by BertrandBordage** [comment]
This cannot be fixed in Wagtail and affects any CMS using oEmbed.
Wagtail is just rendering the HTML Youtube sends through oEmbed, like this: https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=VqwzBeIEfdE

Either Youtube changes its oEmbed generation, or Chrome allows for autoplay or ignores it quietly.
