### ISSUE TITLE
Preview page not updating on browser refresh

### ISSUE THREAD

**Issue by sowinski** [wagtail/wagtail#4211]
### Issue Summary

If I make changes in wagtail admin and save them as a draft and click on the preview button afterwards then I can see my changes. If I change now again and save my draft and only refresh the browser on the already opened preview page I can not see the changes. I always need to click on the preview button first.

I'm not sure if this is a bug or a feature, but from my point of you it makes no sense. I work with a dual-head configuration and have always one browser open with the admin ui and another with the preview page. I would like to click on save and just refresh the preview page to see the changes.

### Technical details

* Python version:  2.7.13
* Django version: 1.10.4
* Wagtail version: 1.13.1
* Browser version: Any, is not browserrelated

**Comment by gasman** [comment]
Hi @sowinski - thanks for the report.
This behaviour is by design. The action of previewing does not save changes to the database (because the purpose of a preview is to test changes before committing them - if a user makes a change, previews, and then leaves without saving, the change should not be made permanent). This means that previewing can only work if we take a temporary copy of the page content as it exists when the user hits Preview - showing the last _saved_ version of the page would give the wrong results.

**Comment by sowinski** [comment]
Hi,

okay this makes sense. Thank you for the interpretation. (I didn't know that preview is working without saving)

**Comment by codefilterPH** [comment]
![image](https://user-images.githubusercontent.com/97372103/196065177-25be91db-2dc5-4ea5-bd0e-9b2bea005e9d.png)

Hi, in my case I tried to enter new information to the paragraph in admin then the preview is not updating or showing what I have entered
