### ISSUE TITLE
Any html tags in RichText

### ISSUE THREAD

**Issue by gagaga67** [wagtail/wagtail#4212]
Hi!
Used wagtail 2 and ckeditor plugin for RichText. Deleted tags div, table, etc after save. How can i fix this? We can't use StreamField for us workflow.

### Technical details

* Python version: 3.6.
* Django version: 2.
* Wagtail version: 2.

**Comment by gasman** [comment]
Hi @gagaga67,
This is by design - please see http://docs.wagtail.io/en/latest/advanced_topics/customisation/page_editing_interface.html#whitelisting-rich-text-elements , and http://docs.wagtail.io/en/v1.13.1/reference/hooks.html#construct-whitelister-element-rules for earlier Wagtail versions.

(Are you _sure_ you're using Wagtail 2? It hasn't been released yet, and as far as I'm aware no ckeditor plugin with Wagtail 2 compatibility exists yet.)

**Comment by gagaga67** [comment]
Yes, i'm sure. We used latest dev version. And ckeditor plugin we already upgrade for us.
Thanks for links!
