### ISSUE TITLE
A Feature Suggestion: Settings > About

### ISSUE THREAD

**Issue by wtorcaso** [wagtail/wagtail#4225]
### Issue Summary
In the Wagtail Admin UI, within ‘Settings’, add a section named ‘About’.  This displays read-only information about the version of Wagtail and the version of Python.  The programmer does not have to do any work to create this section.  

As an extension, there could be a field that the programmer can populate with an arbitrary string.  I can imagine putting a  GIT branch name, or a release identifier in that field.

**Comment by thibaudcolas** [comment]
Hey @wtorcaso, thank you for the suggestion. You might have noticed already but in the admin's nav area the Wagtail logo shows the Wagtail version number on hover, which serves a similar purpose. I can see the value in having this on a separate page with more information though.

I think this could be built first as a separate third-party package, which we could then consider for integration in Wagtail if it seems valuable to have this built-in. How does that sound?

**Comment by wtorcaso** [comment]
That sounds fine – I have thought about doing it myself, as a learning exercise.

I think it is important to have all of the execution-environment information available in one place; I am working with Wagtail projects based on both Python 2 and Python 3, therefore both Wagtail 1.x and 2.x.  My tiny little brain sometimes gets confused about what I am working with.

I see this as a pyramid:

        Which release of my code?
                    Which release of Wagtail?
                Which release of Python?

And that leads me to the suggested extension in which the admin of the Wagtail site can identify all three levels by looking in Admin UI location.

**Comment by thibaudcolas** [comment]
I’m going to close this now since things have moved a bit compared to three years ago – we’re now displaying Wagtail’s version number in the Settings menu.

If people want to add other environment metadata, they can override that templat (https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/menu_settings_menu_item.html), or use our branding overrides (https://docs.wagtail.io/en/stable/advanced_topics/customisation/admin_templates.html).
