### ISSUE TITLE
Is wagtailroutablepage required in INSTALLED_APPS?

### ISSUE THREAD

**Issue by rgant** [wagtail/wagtail#4258]
The documentation for RoutablePageMixin indicates that you need to add the module to the INSTALLED_APPS settings:
http://docs.wagtail.io/en/v1.13.1/reference/contrib/routablepage.html

However the bakery demo doesn't do that:
https://github.com/wagtail/bakerydemo/blob/master/bakerydemo/settings/base.py#L33

And it seems to work just fine without doing that.

So which is correct? Should I add it to installed apps? why? If not should the documentation be changed?

**Comment by gasman** [comment]
I believe adding it to INSTALLED_APPS is needed in order for the `{% routablepageurl %}` template tag to work - if you're not using that tag (as bakerydemo apparently isn't), you can get away without it. However, since we want bakerydemo to be representative of best practices, I'll add that now - thanks!

(In fact, perhaps as a matter of best practice bakerydemo _should_ be using `{% routablepageurl %}`. PRs welcome :-) )
