### ISSUE TITLE
Segregated multi-site support

### ISSUE THREAD

**Issue by DanielSwain** [wagtail/wagtail#4288]
The current multi-site support in Wagtail assumes that all sites are for the same organization.  If I wanted to create sites for multiple organizations of the same type (for instance, Chambers of Commerce) on a single Wagtail installation, then the images and documents uploaded by one organization are visible to all.  Also, the pages of all organizations are visible to everyone else in the Wagtail Explorer.  Creating multiple sites for organizations of the same type on a single Wagtail installation would provide the capability to view statistics across multiple organizations and to promote cross-organization communication among members (and probably other interesting things as well).  Please consider implementing segregated multi-site support in which users who are assigned editing permissions per site can only view the pages and assets of that site.

**Comment by DanAtShenTech** [comment]
Looks like Django sites framework's [CurrentSiteManager](https://docs.djangoproject.com/en/2.0/ref/contrib/sites/#the-currentsitemanager) might be useful.  Perhaps the requested functionality could simply be implemented as an option in Settings.

**Comment by gasman** [comment]
Hi @DanAtShenTech - thanks for the suggestion.

This is indeed something we're keen to implement, and there are various strands of work going towards this (#2869, #4206, #4207) - although it looks like we don't currently have an open issue for the feature as a whole since #2463 was closed, so I'll leave this one open.

It's possible to achieve most of this through user groups and permissions - in particular, a user who's been assigned permission over a single sub-site won't see other sites in the explorer. The main thing that's missing at the moment is introducing a 'choose' permission level so that we can restrict the pages shown in the 'choose a page' popup. Note that we want to avoid tying our model of limited-access users too closely to the concept of 'sites', since we want to keep things flexible enough to allow for other arrangements - for example, an organisation might want to enforce this kind of compartmentalisation between sections of a site, without having a distinct domain name for each one.

**Comment by DanAtShenTech** [comment]
One other thought to consider with this request:  It would be useful to be able to have themes placed outside of app-specific files.  This would allow multiple sites to share the same theme, which is a very real possibility in my use case.  I'm thinking of a general `themes` folder at the same level as the general `templates` folder.  I've accomplished this in my current Wagtail app, but because of how Django handles templates versus what I'll call other static assets (aren't templates really static assets too?) meant that I had to prefix all css and js references with the folder name of the theme and then do an alias in my Apache VirtualHost setup from the prefix to the location of the folder (along with a `Require all granted` directive following the alias).  I would really like to get away from having to create the Apache alias and directive in this type of structure, but this might be a limitation of Django because of how it differentiates between templates and other static assets and doesn't treat the combination of the three (html, js, and css) as a theme.

**Comment by DanAtShenTech** [comment]
**SNIPPETS:**  In order for the requested feature to be complete, it seems that snippets would also have to be made specific to a site in  some way.

**Comment by bahoo** [comment]
> in particular, a user who's been assigned permission over a single sub-site won't see other sites in the explorer.

Could you elaborate on this? I'm having trouble finding any clear avenues for assigning permissions to a site. Thank you! :)

( +1 to fleshing this feature out further, also 👍 )

**Comment by mjlabe** [comment]
My friend and I hacked together something that sort of worked:

https://github.com/mjlabe/bwagtail-cms

We ended up filtering via SQL:

https://github.com/mjlabe/bwagtail-cms/blob/master/bwagtail/bwagtail/get_user_sites.py

And overriding the views for switching the site:

https://github.com/mjlabe/bwagtail-cms/blob/master/bwagtail/wag_custom/views.py

https://github.com/mjlabe/bwagtail-cms/blob/master/bwagtail/wag_custom/forms.py

**Comment by DanielSwain** [comment]
[This video](https://www.youtube.com/watch?v=RKSwjaZKXL0) might be useful in implementing this feature.

**Comment by bahoo** [comment]
I ran a bit farther with @mjlabe's implementation, and made a few small updates:

- updated `edit` and `edit_current_site` to match updated arguments ( circa 2.6.2 )
- monkeypatches / re-sets the view function instead of requiring re-registering all the Wagtail URLs ( though this approach is downright disgusting lol and I would love to hear a cleaner solution here )
- removes the references to `django-currentuser`

Not production ready, but if this is a helpful stepping stone in getting someone else toward a workable prototype, here you go:

https://gist.github.com/bahoo/5f073c15d0e3ff742ab14ecc5a671de9

**Comment by ababic** [comment]
While the tree-based permissions of the page tree and collections allow a great deal of flexibility in defining how multi-tenancy should work for a project - I can't help bit think we're missing something to pull it all together. 

I would like to propose a new `CMSInstance` model to fulfil this role - which would represent an 'instance of the CMS' accessed by editors (as opposed to a `Site` which is accessed by front-end users). And like a `Site`,  a `CMSInstance` would be identifiable by the domain of the current request, but it would only apply to the CMS (which might be at an entirely different domain to any of the `Site` objects). 

Like we did for images and documents when Collections were introduced, we could create a single `CMSInstance` by default and associate all `Site` objects with it (via a new `ForeignKey` field on the `Site` model), and things like the site switcher in `wagtail.contrib.settings` (and perhaps the site list itself) would be limited to sites associated with the current `CMSInstance`.

All views and choosers would use the current `CMSInstance` to filter out anything from other instances, and automatically associate content with the correct instance. And, like we do with `wagtail.search.models.Indexed`, we could include a model mixin (e.g. `CMSInstanceSpecific`) that developers could use to create models with content unique to each instance.

We'd probably also need to provide a version of `CMSInstanceSpecific` to help create tenant-specific user models, (username would have to be unique per `CMSInstance`, rather than completely unique), which would be important for managing users / configuring admin permissions on a per-instance basis (admin authentication would need a rejig too). 

A few other things that would need thinking about are:
- What the relationship between `CMSInstance` / `Collection` / `Image` / `Document` should be
- What we'd do about tags (each `CMSInstance` should probably have it's own tag set/cloud)\
- How would non-CMS users be associated with a `CMSInstance` - maybe indirectly via `Site`?
- Whether there would be a UI to manage this, or whether (like Collections), developers would manage `CMSInstance` objects outside of Wagtail.

Interested to hear what folks think about this general approach? @mjlabe @bahoo @DanielSwain Does this sound like something that would fit your use-cases? If feedback is good, I'll work up these ramblings into a proper RFC.

**Comment by mjlabe** [comment]
It sounds great to me. I think it would be best to have dropdowns to assign
a site to a CMS instance. Even if Django admin were left as is, I still
think it would work for me. The Django admin site is for true admins with
access to everything and the wagtail admin would work on a per CMSInstance
basis.

**Comment by DanielSwain** [comment]
To add to this discussion, I am including here references to my [two comments](https://github.com/wagtail/wagtail/pull/5375#discussion_r301572535) from July 9, 2019.  I also plan to add some other thoughts here as soon as I have time to write them up.

**Comment by carlb** [comment]
@ababic did your proposal ever make it into an RFC (I looked [here](https://github.com/wagtail/rfcs/pulls and couldn't find it)? My group (in a clinical informatics lab in Boston) are just (i.e. in the past 2 weeks) getting started with Wagtail to deal with a sudden surge of content related to the pandemic across our network of hospitals. Loving it so far, but the enhancement discussed here sounds like it might be ideal for some of our uses case both now and longer term. In our case it's not different Chambers of Commerce (the example used by @DanielSwain above), but different hospitals, academic centers, and other organizational units that we support that may have similar content, needs, but need to be segregated in the admin UI.

Would love to contribute to the discussion around this and pick a direction for our urgent need that is compatible with community plans to address this.

**Comment by ababic** [comment]
Hi @carlb. Thanks for posting! It just so happens I implemented something like the above for a client project recently. It made a few things clearer, although many elements were probably a bit too bespoke to apply to many projects.

I haven't put together an RFC yet, as the issue is so multi-facetted that it probably demands 3 or 4 RFCs to tackle the various different aspects, and I simply haven't had the time to put them together (although I'd certainly still like to). 

The `CMSInstance` idea (I went with `CMSSite` in the end) definitely has legs, but I only managed to make it work with each site being administered at a separate CMS domain, e.g. 
- `cms.foo.com` manages content for `foo.com`
- `cms.bar.org` manages content for `bar.org` 

Making things completely segregated is really quite a challenge, I've found. If you want true segregation between each site, I would highly recommend investing the time in your infrastructure instead, and simply redeploy the same codebase multiple times (especially if free hosting plans will do).

**Comment by DanielSwain** [comment]
I am still very hopeful to see this feature come to pass.  In preparation for this eventuality, I want to mention my comment [here](https://github.com/wagtail/wagtail/pull/5375#discussion_r301638555) about use of a `themes` folder.

**Comment by ababic** [comment]
@DanielSwain Broadly speaking, I would say the remaining pieces of the puzzle are:

1. Support for a `can_choose` Page permission for pages (allowing true hiding of pages between sites)
2. Support for "Swappable site identification policies" - Allowing developers to customise how sites are matched to requests (e.g. by the CMS domain being used)
3. Something like the `CMSInstance` model discussed above, allowing you to recognise the site by the domain it is administered on, rather than the domain it is viewed on.
4. Support for a `can_choose_from` permission for collections (you now have site-specific media that can be made private for each site)
5. Support for nested collection in the Wagtail UI ([RFC](https://github.com/wagtail/rfcs/pull/48))  
6. Support for site-specific collections (each site can specify it's own root collection, and a site's collections will be selected by default in various places)
7. Support for site-specific tag clouds
8. Adding some mixin models / utilities to help implement site-specific models and manage them via Wagtail
9. Perhaps a native (but optional) version of https://github.com/moorinl/wagtail-themes
10. A way to manage permissions for multiple sites that doesn't require duplication/management of lots of site-specific groups

Even with all these things in place, I think Wagtail might still have to recommend separate hosting as the favoured way to segregate sites, not least because all it takes is for someone to make the Django admin area available (or some other Django app that doesn't care about Wagtail's site-specific view logic), and you immediately have important security and privacy implications.

**Comment by robslotboom** [comment]
To handle some restrictions I created the folowing models.
Rootpage is the toplevel – independent of any site – to add home pages to.

```
class ProxySite(Site):
    
    objects = ProxySiteManager() < see below
    
    class Meta:
        proxy = True

    @property
    def home_page(self): 
        return self.root_page

class RootPage(Page): < toplevel
    parent_page_types = []
    subpage_types = ['cms.home_page')]
    is_movable = False
    is_copyable = False
    is_deletable = False
    is_unpublishable = False

    @property
    def can_add_homepage(self):
        return self.get_children().count() < MAX_SITES

class HomePage(Page):

    max_count = MAX_SITES
    is_movable = False
    is_unpublishable = False
    @property
    def is_copyable(self):
        return self.get_parent().specific.can_add_homepage

    @property
    def is_deletable(self):
        return self.get_parent().get_children().count() > 1

    subpage_types = [
            'cms.search_page',
            'cms.default_page',
            'cms.album_page',
            'cms.news_page'
        ]

class DefaultPage(Page): 
    
        parent_page_types = [
            'cms.home_page',
            'cms.default_page'
        ]
        subpage_types = [
            'cms.default_page',
        ]

class ProxySiteQuerySet(models.query.QuerySet):

    def default(self):
        try:
            return self.get(is_default_site=True)
        except:
            return
    
    def not_default(self):
        return self.filter(is_default_site=False)
    
    def default_or_first(self):
        return self.default() or self.first()
    
    def get_user_sites(self, user):
        user_perms = UserPagePermissionsProxy(user)
        if user_perms.can_edit_pages():
            site_pks = list(page.get_site().pk for page in user_perms.editable_pages().all())
            site_pks = list(sorted(set(site_pks)))
            return self.filter(pk__in=site_pks).distinct().all()
        
        return self.none()
        
    def get_current_user_site(self, user, site):
        user_site = self.none()
        user_sites = self.get_user_sites(user)
        try:
            user_site = user_sites.get(hostname=site.hostname)
        except ObjectDoesNotExist:
            user_site = user_sites.first()
        return user_site

    def get_sites_for_hostname(self, hostname, port):
        return self.annotate(
            match = Case(
                When(hostname = hostname, port = port, then = MATCH_HOSTNAME_PORT),
                When(hostname = hostname, is_default_site = True, then = MATCH_HOSTNAME_DEFAULT),
                When(is_default_site = True, then = MATCH_DEFAULT),
                default=MATCH_HOSTNAME,
                output_field=IntegerField()
            )
        ).filter(
            Q(hostname=hostname) | Q(is_default_site=True)
        ).order_by(
            'match'
        ).select_related(
            'root_page'
        )

class ProxySiteManager(models.Manager):

    """ Is in wagtail’s SiteManager """
    def get_by_natural_key(self, hostname, port):
        return self.get(hostname=hostname, port=port)

    def get_queryset(self):
        return ProxySiteQuerySet(self.model, using=self._db)

    def default(self):
        return self.get_queryset().default()
    
    def not_default(self):
        return self.get_queryset().not_default()

    def default_or_first(self):
        return self.get_queryset().default_or_first()

    def get_user_sites(self, user):
        return self.get_queryset().get_user_sites(user)
    
    def get_current_user_site(self, user, site):
        return self.get_queryset().get_current_user_site(user, site)
    
    def get_sites_for_hostname(self, hostname, port):
        return self.get_queryset().get_sites_for_hostname(hostname, port)
```

Editors are linked to one or more home page using group and permissions.

And some hooks prevent unwanted actions.

```

@hooks.register('before_delete_page')
def before_delete_home_page(request, page):
    if request.method == 'POST':
        return

    home_page = request.proxy_site.home_page.specific
    specific_page = page.specific
    if specific_page.__class__ == home_page.__class__:
        if request.user.is_superuser:
            messages.warning(
                request,
                _('This is the {home_page} of {site_name}. When deleted the site will be removed to.').format(
                    home_page  = home_page._meta.verbose_name.lower(),
                    site_name = request.proxy_site.site_name
                )
            )
        else:
            messages.error(
                request,
                _('You are not allowed to delete the {home_page}.').format(
                    home_page = home_page._meta.verbose_name.lower()
                )
            )
            return redirect('wagtailadmin_explore', page.id)
            

@hooks.register('before_copy_page')
def before_copy_home_page(request, page):

    home_page = request.proxy_site.home_page.specific
    specific_page = page.specific
    if specific_page.__class__ == home_page.__class__:
        if request.user.is_superuser:
            root_page = home_page.get_parent().specific
            if root_page.can_add_homepage:
                messages.warning(
                    request,
                    _('Please note that you are about to copy the {home_page}.').format(
                        home_page = home_page._meta.verbose_name.lower()
                    )
                )
            else:
                messages.error(
                    request,
                    _('The root page doesn’t allow you to copy the {home_page}.').format(
                        home_page = home_page._meta.verbose_name.lower()
                    )
                )
                return redirect('wagtailadmin_explore', page.id)
        
        else:
            messages.error(
                request,
                _('You are not allowed to copy the {home_page}.').format(
                    home_page = home_page._meta.verbose_name.lower()
                )
            )
            return redirect('wagtailadmin_explore', page.id)


```

**Comment by robslotboom** [comment]
Unfortunately the above code shows an errormessage in the navigator due to 404 for the rootpage raised by the api:

```
class PagesAdminAPIViewSet(PagesAPIViewSet):

    def get_queryset(self):
        queryset = super().get_queryset()
        # Hide root page
        # TODO: Add "include_root" flag
        queryset = queryset.exclude(depth=1).specific()
        return queryset
```
