### ISSUE TITLE
Draftail remaining release blockers

### ISSUE THREAD

**Issue by BertrandBordage** [wagtail/wagtail#4296]
First of all, I’m very sorry to open this issue… I’m totally OK with releasing Draftail with some minor bugs since it’ll still be better than Hallo.js. The purpose of this issue is to focus only on critical, misleading and easily noticeable issues. These important issues must be fixed before 2.0, otherwise Draftail will get a ton of negative feedback and end users will remember Wagtail 2.0 as the release that changed their habits in a bad way (it’s even more important that Draftail is almost the only really noticeable change in 2.0 for end users).

# List of Draftail release blockers

Here is the current list of Draftail release blockers still present in Wagtail 2.0rc1:
- [ ] Deleting an image can delete the whole field
- [x] #4295  Draftail crash when rich text field is named "description"
- [x] The “Alt text” field should either be a modifiable input, or not an input at all. Right now it’s misleading everyone.
- [x] For some reason the “Alt text” input became huge and lost its border radius between 2.0b1 and 2.0rc1

Another very noticeable deprecated functionality is the image that no longer float in the text. While I’m strongly in favor of the Draftail behaviour, it is to be expected that a vast part of users will want to keep the old behaviour (I already got feedback on this).

# Deleting an image can delete the whole field

As listed below, I faced a case where the whole field disappeared when deleting an image. For some reason, the image was previously saved as outside of a paragraph, so the `body` field contains this in the database:
```html
<embed alt="Displaced_Persons_and_Refugees_in_Germany_BU6643.jpg" embedtype="image" format="right" id="503"/><p></p>
```
Note that the issue only occurs when you didn’t modify anything in that field since the page loaded. Adding content after the image, saving and trying to delete the image still does the same issue, even if you add an entire encyclopedia after the image.

## Let’s delete an image!
![capture d ecran 2018-02-16 18 15 19](https://user-images.githubusercontent.com/1119169/36320168-93032dfe-1345-11e8-8fe8-096fafa8dc56.png)
## No, you deleted the entire field.
![capture d ecran 2018-02-16 18 15 56](https://user-images.githubusercontent.com/1119169/36320169-9323e3fa-1345-11e8-8e62-747c6aedb9c5.png)
## Here is the corresponding JS error
![capture d ecran de 2018-02-16 18-16-04](https://user-images.githubusercontent.com/1119169/36320170-933e0b40-1345-11e8-876e-83e0c91b1116.png)

**Comment by BertrandBordage** [comment]
Another deprecated feature I was asked about is the ability to move images within the same field. It was possible with Hallo, though I’m pretty sure it wasn’t supposed to work given the lack of interactive feedback when we do it.

**Comment by gasman** [comment]
To reproduce 'Deleting an image can delete the whole field':

* Enable hallo.js via the setting:

        WAGTAILADMIN_RICH_TEXT_EDITORS = {
            'default': {
                'WIDGET': 'wagtail.admin.rich_text.editors.hallo.HalloRichTextArea'
            }
        }

* Edit a rich text field; delete its contents and continue pressing backspace until the 'P' toolbar button becomes un-highlighted
* Insert an image; after the modal closes, do not re-focus the rich text field. Hit 'publish'.
* Enable draftail by removing the setting above, and re-edit the page
* Click on the image and hit 'delete'

I'd expect the html-to-contentstate converter to produce the same output for `<img />` and `<p><img /></p>` - namely, an unstyled block consisting of a single space character with an entity definition on it. Since it apparently isn't doing so, I think the converter code is at least partly at fault - I'll investigate.

**Comment by BertrandBordage** [comment]
@thibaudcolas Thanks for the detailed answer!

Nice to see we have a workaround for moving images, way better than nothing :)

About the alt field, I personally think it should be replaced by just plain text on the black background of the tooltip.
About its broken styling, I’m positive, it’s coming from this commit: https://github.com/wagtail/wagtail/commit/947b9dab6ed6df55b64db473e4991dde7900dd6a. Here are the rules that break the alt input styling that were not in 2.0b1:
```css
@media only screen and (min-width: 50em)
.full .halloeditor, .full input, .full textarea {
    padding-left: 50px;
    padding-right: 50px;
}

.full .halloeditor, .full input, .full textarea {
    padding: 2em 20px;
    border-radius: 0;
    font-size: 1.2em;
    line-height: 1.6em;
}
```

**Comment by gasman** [comment]
Further on the image deletion issue: it seems that the error happens when the image is the final block in the field to be removed. Draft.js apparently doesn't accept an empty list of blocks as valid...

This doesn't happen in regular Draftail usage because, it seems, the editor always makes sure to place a paragraph block before and after the image, which can't be deleted without also deleting the image. Sure enough, the HTML output on the frontend template also contains a leading / trailing `<p></p>`. This in itself is probably a bad thing: one of the common complaints about hallo.js was that it inserted unwanted / inconsistent whitespace that couldn't be deleted, and it would be really annoying if Draftail did the same :-(

Incidentally, a `<p><img /></p>` sequence in the database representation (which can be generated by hallo.js, but not by Draftail) gets converted to an empty paragraph block followed by the image block, which by sheer chance is the correct thing to prevent Draftail from crashing...

If necessary, I think all of this could be fixed / worked around by applying appropriate fixups during the HTML/contentState conversion: inserting the leading/trailing paragraph block when converting to contentState, and stripping empty paragraphs at the start/end when converting to HTML (or stripping _all_ empty paragraphs regardless of position, which would prevent users from using them to insert extra padding - a good thing or a bad thing depending on how much of an HTML purist you are...). Of course, I'd be keen to hear what's feasible to fix on the editor side before going down that route.

**Comment by thibaudcolas** [comment]
Thanks for chasing this @BertrandBordage. Those styles were in before 2.0b1. They affect `.full` fields, and I did most of my testing within StreamField.

For the image deletion, I have yet to spend meaningful time chasing this but here is what I can say so far:

- An empty list of blocks should be valid, but it won't be of any use – if there are no blocks, there is nowhere for the user to type text. Draftail is probably crashing because it wrongly assumes there is at least one block. In any case, I don't think there is a valid editing scenario leading to "no blocks".
- Draft.js always adds blocks before/after images because otherwise there would be no way for them to be selected, then removed. This isn't true for Draftail, which has the tooltip and "Delete" button, so in theory we could change the default Draft.js behavior. I haven't done this because images have never been a priority. (PR welcome)

For the empty paragraphs – yep, this hasn't been addressed because even with WagtailDraftail generally images were made with StreamField rather than rich text. I don't think this is comparable to the Hallo situation though – it's not inconsistent (empty blocks in the editor = empty paragraph), and it's only unwanted when the image or embed is the first or last block in rich text. In all other configurations, they can be removed.

I don't think it's a good idea to automatically strip paragraphs, we should rather address their unwanted creation in the editor. That's not something I want to do before the release, but if anyone wants to have a go at it [here's where to start](https://github.com/wagtail/wagtail/blob/e8a9f9d8c924aff8659b38766ebdbe6d614adfc5/client/src/components/Draftail/sources/ModalWorkflowSource.js#L162).

**Comment by thibaudcolas** [comment]
Further trying this, there seems to be quite a few parts of Draft.js where "no content blocks" will throw an error. At least the parts that Draftail uses do. I'm not sure whether this can be considered a bug or a feature, but for now let's assume there has to be at least one block for the editor to be functional.

With this in mind, I think the simplest and most future-proof solution would be to change the editor behaviour when removing block-level entities like IMAGE and EMBED so that instead of completely removing the block, it replaces it with an empty one and moves the cursor there. This is similar to how Google Docs and MS Word delete images.

Current behavior:

![draftail-block-delete-before](https://user-images.githubusercontent.com/877585/36591129-a0830a7c-1899-11e8-8d85-3ee96199f6c8.gif)

Proposed behavior:

![draftail-block-delete-after](https://user-images.githubusercontent.com/877585/36591139-a7c31c6e-1899-11e8-80bd-4b7abb895c9c.gif)

This makes it impossible for fields to lose all their blocks when removing an image/embed, and doesn't introduce workarounds to wrap images with unstyled blocks, which we would want to remove later on.

How does that sound?

**Comment by gasman** [comment]
@thibaudcolas That sounds like a good plan (and to me, placing the cursor in the gap left by the image looks intuitively "more correct", so that's good too).

Does this mean we can go ahead and turn off the insertion of leading/trailing paragraphs when inserting an image at the top / bottom of the field? Or does that still need to be addressed separately?

**Comment by BertrandBordage** [comment]
@thibaudcolas: This is an excellent idea, feels more natural to use.

**Comment by thibaudcolas** [comment]
@gasman good question. Do you mean in the editor, or in the HTML -> contentstate transformation?

They are still useful in order to guarantee it's possible to move the cursor before or after an image (eg. if the last block in the editor was an image, it would be impossible to add text after the image without first removing it, then entering text, then inserting it again above the text).

In the editor, I think that should be kept as-is (or perhaps tweaked so it only happens when the image/embed is inserted at the top or bottom of the editor, or next to another image/embed, rather than in all cases) – unless we find a better way to move the cursor around images.

In the contentstate transform, considering the scenario described above causes a usability issue rather than a crash, I think we should turn it off. It will cause some annoyance, but only with content coming from Hallo, and at least it'll preserve content as-is unless intentionally edited.

I'm not entirely sure how this behaves at the moment though so this is just my best guess.

**Comment by gasman** [comment]
@thibaudcolas I meant in the editor... but you're right, having played around a bit more those spacers are pretty important to ensure sensible editor behaviour, and not just for images at the top/bottom. They're also needed when you have two adjacent image blocks, so that you can place the cursor between them.

I think tweaking the HTML -> contentstate converter to always insert the spacer paragraphs should be an easy (and big) win, so I'll have a go at implementing that.

The `<p></p>` appearing in the final output does still bother me a bit: not so much the adjacent-images case (if you're building image galleries in rich text and need to micro-manage the HTML to that extent, Draftail probably isn't for you...), but more the image-at-top case. I suspect that it's quite common for rich text content to consist of a floated image followed by a paragraph of text around it, and it would be nice if we didn't do anything "quirky" in that case. I dare say it's not an absolute release blocker, though.

**Comment by thibaudcolas** [comment]
👍 

The current behavior definitely isn't ideal but I would find it quirkier if there was an empty block shown in the editor that didn't render as a corresponding empty block in the rendered content, at least with a default config. I don't think fixing this is worth breaking the "WYSIWYG" "one block = one block" assumption.

I'd rather spend more time on this (either before or after the 2.0 release) and look for ways to improve the editor's behaviour with image insertions & moving selection on/around images. And if people want an immediate fix they can use some variation of `p:empty { display: none; }` (which any Wagtail site using Hallo already uses, or should use), or StreamField, or stay on Hallo.

For the conversion inserting a spacer paragraph, same, I'm skeptical because it breaks the expectation that what you see in the editor will be reflected on the page. In the editor, those paragraphs would look like any other paragraph, but then on the page they aren't there anymore.

**Comment by gasman** [comment]
Have created a PR for updating the HTML->contentstate converter: #4311. Unless I'm missing something, this change doesn't break WYSIWYG - effectively, it just performs a one-off fixup of hallo.js content to add the spacer paragraphs that Draftail expects. From that point on, it's functionally the same as content entered through Draftail, and the spacing will match what appears on the front-end.

**Comment by gasman** [comment]
Completed as of #4311 and Draftail 0.17.0.

**Comment by BertrandBordage** [comment]
Awesome! Thank you very much to you, @gasman & @thibaudcolas!
