### ISSUE TITLE
Optimise representation of deeply-nested StreamField blocks in migrations

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#4298]
Because the actual database backend of a StreamField is just a simple `LONGTEXT` populated by json-serialized block contents, the database does not need to know about changes made to the Block structure within the StreamField.

However, since Wagtail currently does provide that information to the migrations, this causes complex StreamField instances to generate *gargantuan* migrations whenever even the tiniest change is made to a single Block used by the field. Here's an [example](https://pastebin.com/pMQriqXZ). This one model's migration code is nearly **500,000 characters**. 

And another half megabyte of text will be repeated in each subsequent migration if even a single field in a single Block has a single attribute changed. This is highly undesirable, and as far as I can tell, *completely pointless*. The auto-generated migration files don't need to care about the internal structure of a StreamField; only manually written migrations that migrate the data from an old format to a new one need to care, and those don't need to be half a megabyte of code.

I'm not yet entirely sure how best to remedy this, but I think it will have something to do with `StreamField.deconstruct()`.:

    def deconstruct(self):
        name, path, _, kwargs = super(StreamField, self).deconstruct()
        block_types = self.stream_block.child_blocks.items()
        args = [block_types]
        return name, path, args, kwargs

I don't think there's any good reason for it to care about its child blocks. Though while I do have a lot of experience with dealing with, and hacking around, StreamFields, I'm not an expert. Maybe I'm missing something?

**Comment by gasman** [comment]
Hi @coredumperror,
As mentioned on #3710, this is line with Django's principle of preserving all properties of a model field within migrations, not just the properties that directly affect the database schema. This ensures that any Python code in the migration, particularly for data migrations, has access to a 'frozen' version of the ORM model as it existed at that point in the migration path, regardless of how much the real model in models.py may have moved on from there.

To be honest, your example code shows a level of configurability that goes way beyond anything I anticipated, or would recommend. The purpose of Wagtail as a CMS is to provide a separation between content editing and design decisions - hooking up every conceivable design choice to a StreamField element doesn't achieve that.

**Comment by chosak** [comment]
@gasman following up on this:

> your example code shows a level of configurability that goes way beyond anything I anticipated, or would recommend

This problem (large migrations due to highly configurable StreamFields) is something that we've run into as well, and is a major pain point around maintenance of our large Wagtail site.

I'm curious if you have any guidance on how or where to draw the line between having many Page models that differ slightly versus having fewer Pages but making them more configurable. Consider a use case where you have a few core page types that share certain common design elements (headers, footers, sidebars), but their main content may differ in numerous subtle ways. Now compare these few pages:

- https://www.consumerfinance.gov/data-research/consumer-credit-trends/auto-loans/
- https://www.consumerfinance.gov/data-research/cfpb-research-conference/2016-cfpb-research-conference/speakers/
- https://www.consumerfinance.gov/consumer-tools/sending-money/ht/

Each of these pages has the same basic structure but the main content area is very different (different images, callouts, links, expandables). In our case we accomplish this through the use of at least one highly configurable StreamField, which can contain various blocks (which may be StructBlocks and hold, e.g. lists of other blocks).

This usage results in similar migration issues to that reported by @coredumperror. We've discussed various other ways to set this up, but it's not clear how best to do this with a "many page types" approach. You'd need something like `PageWithImageAndFormAndLinks` and then `PageWithImageAndLinksButNoForm` - the combinations would quickly get out of hand. Then you'd also have a more difficult editor experience where a page creator would have to choose from a large list of page types that differ in subtle ways. The inability to convert a page from one type to another also makes using page types less attractive than configurable StreamFields.

Any insight/suggestion in how best to set up pages like this in "the Wagtail way"?

**Comment by thibaudcolas** [comment]
Ping @loicteixeira as well – we've dealt with projects with tens of megabytes of StreamField migrations, I'm sure he will have good insights to share.

**Comment by chosak** [comment]
One additional point on the topic of StreamFields and migrations:

The use of Django migrations to encode StreamField configuration can also be a bit tricky as it doesn't enforce necessary data migrations when fields change. So, for example, changing a StreamField's nested CharBlock to an IntegerBlock makes a new migration but doesn't change the JSON field content stored in the database. This has come up before (#2110, #3014) but there's no simple or well-documented way to migrate this content (we've written up some notes [here](https://cfpb.github.io/cfgov-refresh/wagtail-migrations/)).

You could imagine a setup where StreamField changes don't create a migration, in which case it's totally on the code author to handle DB content changes themselves; or a setup where StreamField changes create a migration and Wagtail includes the framework to do data migrations. The current implementation exists halfway between those two approaches - I'm curious how others who have experienced this feel about this point.

**Comment by gasman** [comment]
@chosak I don't have a huge amount of experience doing the data modelling on real-world Wagtail sites, but the example pages you give certainly look like candidates for three distinct page types to me. The important thing is to organise them by their purpose rather than by layout/design - so, they would be DashboardPage or SpeakerListingPage, rather than TwoColumnPageWithLinks.

I notice in particular that https://www.consumerfinance.gov/data-research/consumer-credit-trends/auto-loans/ follows exactly the same layout as its sibling pages such as https://www.consumerfinance.gov/data-research/consumer-credit-trends/credit-cards/, which makes it a particularly good candidate for a dedicated template. If your editors are recreating that layout each time from a generic StreamField page consisting of 'two column blocks' and so on, that's wasted effort.

**Comment by loicteixeira** [comment]
We ran into the same issue(s) on a couple websites too. Past a certain point, it is simply not possible to create separate page types for each combination, especially when converting to Wagtail an existing website with very bespoke pages (even after cutting in half the requirements by re-conciliating patterns together).

While I can agree with the general idea of keeping the right hat (i.e. separating content and design), I think the page type isn't the only valid point of separation between design and content. Given that a block has specific fields and renders consistently via a template, I think the separation is present too (as opposed to putting everything in a rich text field). So by giving multiple blocks, we're mostly allowing the content editor to re-organise the blocks and omit some others. This type of pattern reminds me of [Atomic Design](http://bradfrost.com/blog/post/atomic-web-design/) where the blocks would be molecules, nested blocks atoms used in a page/template (skipping organisms because that's pushing probably going too far).

However to be fair, the more flexible Streamfield will be, the lazier the developer will be to organise the content into separate logic units and, can arguably lead to inconsistent page structures (but consistent design).

Back on the migration issue, I don't know what to think of it really. I like the idea of following Django's convention and being able to access a frozen version of the model, but given that it's still rather difficult and fragile to modify the Streamfield data in migrations and that the data isn't converted under the hook when migrating (not sure how feasible it would be anyway), it feels a bit useless.

That being said, when encountering this issue, one of the solution we looked at was to overwrite the `deconstruct` method of a custom `SteamBlock` which would be used as a base of all the `StreamBlock` for all the `StreamField`, we decided against it because as annoying as the current situation can be, this would have removed something quite fundamental from how Django migrations work and could be more painful down the line. Instead we squash migrations more often than usual so we have only a few big migrations and created a custom `runserver_fast` (used in development only) which disable migration checks (because with many big migrations files, the server would take up to 30 seconds to restart on a file change).

**Comment by chosak** [comment]
@loicteixeira thanks for your comments. Much of what you said rings true with our experience. We have adopted an atomic design philosophy and so try to encourage content editors to pick and choose the blocks that make the most sense for a particular page.

Regarding migrations, I hear you about squashing. I'd like to better understand what functionality is gained by being able to access a frozen version of StreamFields, though, besides just breaking Django convention. What bad things would happen if the block details of the SF weren't stored in the migration?

@gasman I agree in part about the wasted effort. One issue we've faced is that on a large site with so many pages and types of content, the final design of a page might go through many iterations before its final publication. So instead of being able to standardize the design of, say, a SpeakerListingPage, creating the model, and publishing it to content editors, we instead seek to work iteratively, allowing content editors to use the Wagtail admin to experiment with page designs before finalizing them.

A common use case is one where editors use an existing page as a template but alter it slightly. So we might have a SpeakerListingPage and then decide we want to add expanded bios for the speakers on a different page. Using multiple page models for this would require considerably more engineering time versus giving the content editors the ability to experiment.

**Comment by loicteixeira** [comment]
In the current state, while it can be complicated to create data migration for StreamField content, it is possible and the fact that the migration knows about the blocks definition means that when you save the page, it will validate the content (i.e. unknown blocks will be stripped and some block sanitisation might happen during the deserialisation/serialiation round).

Arguably Wagtail does a bit of that outside of migrations too (e.g. you removed a block from the definition but it is still present in the data, when the field loads, it will just ignore the now unknown block and it will then be removed upon save) but we probably shouldn't rely on this behaviour.

In any case, while I'm also bothered by this issue, I'm afraid that we might find out later that it was a mistake to remove that information (in other terms, that we had a bit of a short term vision). I don't know if that's a reason enough to not remove it though.

I'm also wondering if there would be a more compact way for blocks to deconstruct (i.e. keeping it but without generating such huge files) and if something can be done for this data to actually be used (I imagine auto conversion might not be possible, but maybe some helpers?).

**Comment by gasman** [comment]
One potential optimisation (which might well also link into #3062) would be to recognise when the same sub-block is re-used in multiple places in a streamfield definition, and assign that block an ID that we can point back to, instead of repeating the definition in full each time.

So, instead of:

    body = StreamField([
        ('one_column', StreamBlock([big_long_list_of_sub_blocks])),
        ('two_column', StructBlock(
            ('left', StreamBlock([big_long_list_of_sub_blocks])),
            ('right', StreamBlock([big_long_list_of_sub_blocks])),
        )
    ])

we could have something like:

    body = StreamField([
        ('one_column', StreamBlock([big_long_list_of_sub_blocks], id=1)),
        ('two_column', StructBlock(
            ('left', BlockReference(id=1)),
            ('right', BlockReference(id=1)),
        )
    ])

or perhaps

    body = StreamField([
        ('one_column', BlockReference(id=1)),
        ('two_column', StructBlock(
            ('left', BlockReference(id=1)),
            ('right', BlockReference(id=1)),
        )
    ], block_refs={1: StreamBlock([big_long_list_of_sub_blocks])})

(Bear in mind that the graph of references might be arbitrarily complex: a block used as a reference might itself contain block references as sub-blocks. For extra bonus points, support circular references to achieve arbitrary-depth nesting. Yes, that's something people have actually requested...)

**Comment by coredumperror** [comment]
I like the IDs idea. ("IDea"?) That would definitely help a lot to cut down on the massive overload of text in migration files.

**Comment by mnieber** [comment]
I wonder if this issue is related to a question I had on my mind (please tell me if this is too off topic): is `StructBlock` functionally duplicating what django.Model already handles? Both have a similar objective, which is to store a collection of fields. 

What if - instead of inserting a `StructBlock` - I could insert a new django.Model instance into a StreamField? Perhaps this would add a few requirements on the particular django.Model (e.g. the existence of a few extra member functions). This instance would have an id, and it could be stored in its dedicated database table. If I change the django.Model's definition, it would not directly affect any StreamField.

**Comment by gasman** [comment]
@mnieber That's definitely worth opening a separate issue about - it's too big a topic to cover here.

**Comment by ababic** [comment]
This was discussed in the core team meeting on 25/01/20. 

In general, it was agreed that including the streamfield block definitions in migrations was the correct default behaviour. This is because at any point in a model's migration history, you should be able to access both the structured content/data AND the full streamblock definition, in case they are both needed for use in a data migration. As unlikely as this may seem, until there are more established solutions for migrating streamfield content, we feel it's important to preserve this as an option.

However, we also recognise the issues that many (even core team members themselves) have reported in relation to this, and would like to offer a way for developers to opt out of this behaviour on a per-project basis, provided they are happy to accept the consequences (as outlined above).

**Comment by coredumperror** [comment]
I would **greatly** appreciate such an opt-out mechanism. My team does not care about keeping the history of our streamfields' structure, and this change would save us several megabytes of useless new migration code being shoved into our repo every week.

**Comment by hazho** [comment]
I had this issue back at 2020, and I just ignored it by having a backed-up copy of the main stream App(at minimum state), before I do migrations for the entire project or related Page models that use stream fields, I rename the **live version** of Stream App, and rename back the **backed-up version** and then after I done from migration, I rename the live version back to be the live one again

**Comment by ababic** [comment]
For those looking for an interim solution... we're currently using this modified version of StreamField internally, which still allows access to the raw values in migrations:

```
import json

from wagtail.fields import StreamField as WagtailStreamfield


class StreamField(WagtailStreamfield):
    def __init__(self, *args, **kwargs):
        """
        Overrides StreamField.__init__() to account for `block_types` no longer
        being received as an arg when migrating (because there is no longer a
        `block_types` value in the migration to provide).
        """
        if args:
            block_types = args[0] or []
            args = args[1:]
        else:
            block_types = kwargs.pop("block_types", [])
        super().__init__(block_types, *args, **kwargs)

    def deconstruct(self):
        """
        Overrides StreamField.deconstruct() to remove `block_types` and
        `verbose_name` values so that migrations remain smaller in size,
        and changes to those attributes do not require a new migration.
        """
        name, path, args, kwargs = super().deconstruct()
        if args:
            args = args[1:]
        else:
            kwargs.pop("block_types", None)
        kwargs.pop("verbose_name", None)
        return name, path, args, kwargs

    def to_python(self, value):
        """
        Overrides StreamField.to_python() to make the return value
        (a `StreamValue`) more useful when migrating. When migrating, block
        definitions are unavailable to the field's underlying StreamBlock,
        causing self.stream_block.to_python() to not recognise any of the
        blocks in the stored value.
        """
        stream_value = super().to_python(value)

        # There is no way to be absolutely sure this is a migration,
        # but the combination of factors below is a pretty decent indicator
        if not self.stream_block.child_blocks and value and not stream_value._raw_data:
            stream_data = None
            if isinstance(value, list):
                stream_data = value
            elif isinstance(value, str):
                try:
                    stream_data = json.loads(value)
                except ValueError:
                    stream_value.raw_text = value

            if stream_data:
                return type(stream_value)(self, stream_data, is_lazy=True)

        return stream_value

```

**Comment by easherma-truth** [comment]
@ababic thanks for the example! Is there any downside to considering such an implementation to be default behavior in Wagtail? This is maybe a roundabout way of asking what the potential issues might be with adopting an approach like that. :-D

**Comment by ababic** [comment]
@easherma-truth the only downside we've found is that you can only access raw Streamfield values in data migrations (i.e. not the fancy 'bound' kind that know how to render themselves). I find that we generally only work with raw values in migrations anyway, so that hasn't been an issue for us. The fact that you always get the full raw value to work with is actually better in some cases, as you can migrate data between blocks without both block definitions having to be present at the same time (usually, block values that don't match up to a block definition are automatically scrubbed from the return value).

**Comment by ababic** [comment]
@gasman I've separated out the 'ability to access raw values in migrations' problem and submitted a couple of candidate PRs for it. The second option is preferred, as there doesn't need to be any migration-specific behaviour there, which is very messy to write automated tests for. Do you have any thoughts on either approach?

**Comment by ssyberg** [comment]
It's been a couple of years since this has been discussed, but we're hitting a wall in a large wagtail project and migrations now take 45+ minutes and generate huge files and we're also wondering how we can proceed. @coredumperror have you experienced any new downsides to your approach?

**Comment by coredumperror** [comment]
@ssyberg our approach of excluding all streamfield details from our migrations is still working fine.

**Comment by Scotchester** [comment]
@ssyberg [This came up again recently in the Wagtail Slack](https://wagtailcms.slack.com/archives/C014L7KJH3N/p1708644100142209), too. One user in that thread endorsed [@ababic's solution, posted just before @coredumperror's](https://github.com/wagtail/wagtail/issues/4298#issuecomment-1159515247).

Also referenced is @cnk's two-part blog series on trimming Django and Wagtail migration cruft:
1. https://cynthiakiser.com/blog/2022/01/06/trimming-django-migration-cruft.html
2. https://cynthiakiser.com/blog/2022/01/06/trimming-wagtail-migration-cruft.html

**Comment by ababic** [comment]
Two years later, and I still stand by the solution above. 

It's part of our default project setup, has saved hours in collective CI time, and many more in developer hours spent on alternative solutions like regular squashing or manual removal of block definitions (or doing nothing, and having to deal with migration tree conflicts in multiple environments 😜).

Personally speaking, I have yet to encounter a situation where I needed to do something in a data migration that I couldn't do before. However, it should be noted that losing access to block definitions makes it impossible to use the Streamfield migration helpers that have since been added to Wagtail.

**Comment by Mr0grog** [comment]
> This came up again recently in the Wagtail Slack

And again today!

The comments about [how much this can slow down migrations](https://github.com/wagtail/wagtail/issues/4298#issuecomment-1976846583) are a little scary. I am helping a client set up a Wagtail site and was mostly thinking the migration noise is annoying, but probably not worth sticking them with the maintenance burden of a solution like @ababic’s (since it requires knowledge of Wagtail’s and Django’s migration internals to maintain). But the slowdown issues definitely suggest to me that stripping this stuff might be worthwhile anyway.

(I have already made some use of the streamfield migration helpers, but it is pretty obvious how you’d write the same migration yourself. Their loss seems unfortunate but not that big a deal compared to the performance problems this would solve.)

@ababic do you have any interest in wrapping that solution up in a package on PyPI? Selfishly, I’d love to use this for my client, and having a package they could depend on (hopefully) to update if Wagtail’s internals change in some way that affects it would be really great.

**Comment by gasman** [comment]
@Mr0grog The above conversation all happened before the optimised representation was introduced in #12059. I've not been made aware of any specific performance issues with StreamField migrations since then.

**Comment by Mr0grog** [comment]
Oh, I’m sorry, I saw that this had been closed originally on philosophical grounds and missed that it was later re-opened and closed to solve the performance problem. Based on that, it looked like those PRs were incremental improvements and not a more in-depth solution. My fault for not reading closely enough. 😓 

FWIW, I would echo most of the other non-performance concerns with this situation, though I understand the philosophical reasons you want to keep this data in the migrations.
