### ISSUE TITLE
 Language chosen in user preferences persists on subsequent requests

### ISSUE THREAD

**Issue by JRafiei** [wagtail/wagtail#4310]
### Issue Summary

When I change the Language preferences setting from account settings in wagtail admin panel, all the translations across the website changes too. Is it the expected behavior of a bug?

### Steps to Reproduce

1. Go to the wagtail admin panel
2. Click on the Account settings section
3. Click on the Language preferences button
4. Select another language, English for example
5. Save changes and log out

Now you should see the sections that use internationalization tags like trans get changed. At least that's my experience 

### Technical details

* Python version: 3.5.2
* Django version: 1.11.7
* Wagtail version: 1.13
* Browser version: Firefox 56.0 and Chrome 61.0.3
* OS: Ubuntu 16.04

**Comment by gasman** [comment]
Hi @JRafiei - I can't replicate this as described. I'm running the following steps against the [bakerydemo](https://github.com/wagtail/bakerydemo) project:

* Edit bakerydemo/templates/base.html to add `{% load i18n %}` and `<h1>{% trans "Messages" %}</h1>` to the top of the page. (I've chosen "Messages" as a string that exists in Django's own translation set)
* Temporarily change `LANGUAGE_CODE` in bakerydemo/settings/base.py from `en-us` to `de` and view http://localhost:8000/ - confirm that the text changes to "Mitteilungen"
* Change `LANGUAGE_CODE` back to `en-us`
* Log in to the admin, go to Account settings -> Language preferences and set language to German
* Visit http://localhost:8000/ - the text still says "Messages", not "Mitteilungen" (and remains that way after I log out)

This is the behaviour I'd expect - the language choice within the admin is applied using [a decorator on `/admin` URLs](https://github.com/wagtail/wagtail/blob/6dc89c1f7f7d846594d093f1e52efcf9d38ab20c/wagtail/wagtailadmin/decorators.py#L28-L29), so I can't see how that choice would "leak" into the language of the website. In fact, we've encountered the opposite problem (#3991) - the Wagtail userbar picks up the language of the website instead of the admin.

If you can provide complete steps for reproducing this bug on a fresh Wagtail instance, let me know and I'll reopen this.

**Comment by JRafiei** [comment]
Hello @gasman,
I haven't checked this behavior on the localhost and after your suggestion, I retry these steps on my PC and didn't find any problem. Sorry for incomplete testing before reporting this issue.
But the problem still remains in the production. I'm using nginx as webserver and gunicorn for appserver. Do you have any idea why this behavior happens only in production?

**Comment by gasman** [comment]
As mentioned, I think it's unlikely that the admin language choice could be leaking into the website front-end - I'd look for other reasons why the wrong language is being served. Do you have server-side caching set up in production, perhaps? If your site is configured to vary language according to the `Accept-Language` HTTP header, but your cache isn't checking that header, it could be serving an old copy of the page as previously served to another user (with a different language setting).

**Comment by JRafiei** [comment]
As far as I know there is no cache for html content and only static files get cached. But to be sure I should recheck the configs. Specially for Accept-Language header that you mentioned.
Thanks for your advise

**Comment by bmihelac** [comment]
Hello everyone,

I just run into this issue, and after some researching I found reproducible test and fix proposal.

For reproducing steps from @gasman comment can be used https://github.com/wagtail/wagtail/issues/4310#issuecomment-368034758, but started server with command below to avoid new threads in dev server randomly affects translation activation:
 
```
./manage.py runserver --nothreading
```

With this setup original issue can be consistently reproduced.

Solution, that would fix this is to explicitly activate previous language in `language_preferences` view  and `require_admin_access` decorator.

I can make a PR for that.

**Comment by bmihelac** [comment]
This stackoverflow comment is related:

https://stackoverflow.com/questions/2336785/set-language-within-a-django-view

> Warning, I just fixed a bug in a current development, due to translation.activate : threads are reused between requests and keep the last language activated. This lead to weird stuff like django admin switching language all the time. If you manually trigger transaction.activate, don't forget to use translation.deactivate after all strings have been rendered ( that's what LocaleMiddleware does after the rendering ).

**Comment by gasman** [comment]
Thanks for tracking this down @bmihelac! Yes, a PR for this would be very welcome.

**Comment by bmihelac** [comment]
PR is here:

https://github.com/wagtail/wagtail/pull/5532

let me know if anything else is needed.

**Comment by gasman** [comment]
Fixed in #5532.
