### ISSUE TITLE
Draftail: Add external link with selected text doesn't include text in dialog

### ISSUE THREAD

**Issue by FlipperPA** [wagtail/wagtail#4328]
### Issue Summary

In Draftail, when you select text and click the link icon, and click the "External link" tab, the "Link text" box is empty. It should show the selected text, as that will be the text that appears linked.

For an existing link, if you click the link and select EDIT, it also doesn't populate the "Link text" field.

### Steps to Reproduce

1. Create a model with a RichTextField()
2. Enter some text in the RichTextField.
3. Select it, and click the LINK button.
4. Click "External link"

### Technical details

* Python version: 3.6.3
* Django version: 1.11.x
* Wagtail version: 2.0
* Browser version: Latest Chrome

### Screenshot, New Link:

![image](https://user-images.githubusercontent.com/68164/36866604-b4f5c334-1d60-11e8-9e69-659d550c57af.png)

### Screenshot, Existing Link:

![image](https://user-images.githubusercontent.com/68164/36866617-c54efb4c-1d60-11e8-8431-d40e3924a3fa.png)

**Comment by tomdyson** [comment]
Confirmed in my tests. Thanks, @FlipperPA!

**Comment by thibaudcolas** [comment]
Yes, this is something we de-prioritised to get the update out sooner. The full list of those things is over at #4263, in "Other tasks".

I think I made that decision because in my opinion this editing workflow needs some rework:

- Is it really useful to insert the link text here instead of in the editor? (which has a spellcheck, among other rich text features)
- If it is, shouldn't this be available for internal links as well?
- Why does it say "add an [...] link" and "Insert" when there is already a link?

All of which is debatable of course.

If anyone wants to pick this up, here is where to start: https://github.com/wagtail/wagtail/blob/76975525f7a3757b280572165f8717cc4c13bba6/client/src/components/Draftail/sources/ModalWorkflowSource.js#L35-L38

**Comment by FlipperPA** [comment]
Ah, I did look at the list, but must've read right through it. Sorry about that - finished a major database migration today so my brain is a bit mush. I agree on the workflow - and adding a "open in new window" checkbox would be delightful as well. Thanks, as always, for your efforts.
