### ISSUE TITLE
Collections dropdown styling issue in Firefox

### ISSUE THREAD

**Issue by nfletton** [wagtail/wagtail#4336]
### Issue Summary
Styling issue on the image chooser and image library section.

![selection_065](https://user-images.githubusercontent.com/1591068/37049432-16695682-212e-11e8-86a9-b210c7bbd7ee.png)

### Steps to Reproduce

Select Images in Wagtail admin.

Looks like a missing '-moz-appearance: none;' on the collection select styling.

### Technical details

* Wagtail version: 2.0
* Browser version: Firefox latest (tested on Linux and Windows)

**Comment by luizboaretto** [comment]
Same here on OSX FF latest. 

Not only in Collections but also in all dropdowns

**Comment by AlexsMathilda** [comment]
The issue is not completely resolved and is visible on IE 11

![wagtail - editing image glacier descending near hof - internet explorer 3_15_2018 10_50_37 am](https://user-images.githubusercontent.com/25057135/37456276-433b31a4-283f-11e8-92ee-a1c0baf7b948.png)

![wagtail - editing image glacier descending near hof - internet explorer 3_15_2018 10_46_44 am](https://user-images.githubusercontent.com/25057135/37456327-5c427112-283f-11e8-9c3c-f63093e15af0.png)
