### ISSUE TITLE
Draftail editor disappears when pasting text in a new page

### ISSUE THREAD

**Issue by jeromelebleu** [wagtail/wagtail#4346]
### Issue Summary

The Draftail editor disappears when I try to paste some text in a new page.

### Steps to Reproduce

From the Wagtail's admin:
1. Create a new page which has at least one `RichTextField`
2. Paste some text in this field, it doesn't matter the source - e.g. enriched text from LibreOffice or simple text from a notepad.

Note that when I edit a page with some content already defined in this field, I do not encounter this bug: I can paste some text without any issue - except some formatting issues, but it is another topic!

### Technical details

* Python version: 3.5.3
* Django version: 2.0.2
* Wagtail version: 2.0
* Browser version: Firefox ESR 52.6.0

Here is the error I have in the Firefox console when I paste some text:
```
> DOMException [NotFoundError: "Node was not found"
code: 8
nsresult: 0x80530008
location: http://localhost:8090/static/wagtailadmin/js/vendor.js:1]  vendor.js:1:144547
> NotFoundError: Node was not found  vendor.js:1
```

Thanks in advance!

**Comment by thibaudcolas** [comment]
Hi @jeromelebleu, thank you for the detailed report! The editor disappears because it crashes. We’ve been working on a “crash recovery” / fallback UI, but it didn’t make the cut for Wagtail 2.0.

There’s been thorough manual testing of copy-pasting in Draftail so I wonder if/how this might be specific to your environment. I’m away from the computer for the next wee while, if you could do further testing it would help a lot:

- Does this work in another browser?
- If it seems specific to Firefox, does it work with the latest non-ESR version? (I’ve done most tests in v57, which is very different to pre-quantum v52).
- What OS are you using?

Finally you mention some formatting issues — could you give more details? The Draftail editor is fairly new so it would be good to know where things break down.

**Comment by jeromelebleu** [comment]
@thibaudcolas, you're welcome! I totally understand that testing all browsers - and all versions! - and trying to make it works with all of them is quite painful...

I am running Debian Buster (testing) and it works indeed with other browsers. I tried with Firefox 58.0.1 and Chromium 62.0.3202.89. It seems to be specific to Firefox ESR version only so.

> Finally you mention some formatting issues — could you give more details? The Draftail editor is fairly new so it would be good to know where things break down.

I did not encountered those formatting issues while testing with those browsers - I did not encountered any issue in fact!

Let me know if you need further details. Also, let me know if I should open a bug report on the Draftail repository instead.

**Comment by thibaudcolas** [comment]
Thank you, that's very helpful. Good call to switch back to Hallo for now.

I couldn't manage to reproduce this while pasting plain text or basic HTML 😞. Tried in FF52.6.0 ESR in macOS 10.13, and FF52 not-ESR (though I'd suspect releases to be the exact same, except for the update channel) in Windows 10 and Windows 8.1. Tested in Wagtail (2.0 release) and directly on https://springload.github.io/draftail/.

I suspect there may be something else specific to your case, either the content you copy-paste, how you copy-paste it, or the OS. Before I go figure out how to install Debian Buster, could you:

- Provide a small sample of content you used. You said the source doesn't matter but it's worth double checking.
- Let how you do the copy-paste – keyboard shortcuts or contextual menu. Ideally via a small screen recording.
- See whether it works on https://springload.github.io/draftail/examples/ (I suspect it won't, but let's be certain).

----

For the bug report, it's best to open them here first and then triage it together depending on what we find out. I expect a lot of Draftail bugs to ultimately be in Draft.js itself (see #4274), but would rather only open bugs there (or in Draftail) once we have been through some troubleshooting.

**Comment by jeromelebleu** [comment]
Thanks for all your tests! I admit that I have an unusual environment, so I've tried on a stock Debian with default configuration for Firefox ESR. I've realized that it's working fine, indeed, as your several tests. I've compared my Firefox configuration so and found the origin of this issue. This bug occurred only when `dom.event.clipboardevents.enabled` is `false`... I took my Firefox configuration from the iceweasel package.

I don't know what's the future of this really specific bug - sorry about the time you spent on that - but I would totally understand if you decide to close it and don't want to go further. I will certainly keep this option enabled...!

**Comment by thibaudcolas** [comment]
Nice! We all learned something, so that time was well spent. I've added a note in the [Draftail docs](https://github.com/springload/draftail/blob/master/docs/README.md#troubleshooting) about troubleshooting this, and will leave it at that for now.

In an ideal world, I think Draft.js should handle this gracefully instead of crashing because of the missing events. I can see however that customising DOM behavior to that extent is quite advanced (I'm not even sure the [DOM clipboard spec](https://www.w3.org/TR/clipboard-apis/#clipboard-event-definitions) allows it), so first let's see whether other people encounter this.

**Comment by jeromelebleu** [comment]
> Nice! We all learned something, so that time was well spent. I've added a note in the Draftail docs about troubleshooting this, and will leave it at that for now.

Yes, indeed! Thanks for the note.

I had a deeper look into why this setting was `false` - by the way, it was from the [Parabola](https://www.parabola.nu/) `iceweasel` package, a fully Free (as in freedom) operating system, not Debian. I found several pages which are talking about disabling this setting in Firefox to enforce privacy - see [here](https://wiki.mozilla.org/Privacy/Privacy_Task_Force/firefox_about_config_privacy_tweeks) or [here](https://www.ghacks.net/overview-firefox-aboutconfig-security-privacy-preferences/).
