### ISSUE TITLE
the focal point box is visible outside the image

### ISSUE THREAD

**Issue by AlexsMathilda** [wagtail/wagtail#4361]
### Issue Summary

encountered a bug while tested #4284. In IE11, MS Edge, Safari, Chrome and FF the focal point box is visible outside of the image. select a image where no focal point has been set yet.

### Steps to Reproduce

1. Login the admin
2. Select images
3. Select a images where no focal point has been set yet
4. set focal point and save
5. click edit again

Result: focal point is visible outside the image

![2018-03-14_12-41-50](https://user-images.githubusercontent.com/25057135/37402626-9964bfae-278c-11e8-8145-ecbc30558854.png)

**Comment by lucasmoeskops** [comment]
I've looked into this, and the problem seems to be that for some images in the bakerydemo project, the image width and height stored in the database are not equal to the actual image width and height. I'm not sure when this occurs, because it is recalculated when an image changes. Maybe the image files where modified in some other way? It's more an issue for the Bakery Demo project than for Wagtail I think.

**Comment by jjanssen** [comment]
Thank you for diving into this @lucasmoeskops 
Closing this due to the fact it's a bakery demo data issue.
