### ISSUE TITLE
Deleting a selected image in Draftail removes the field

### ISSUE THREAD

**Issue by BertrandBordage** [wagtail/wagtail#4370]
In Wagtail 2.0, if you select an image in the Draftail editor, then hit the “Del” key of your keyboard, and not the delete button from the editor, then the field is removed.

**Comment by thibaudcolas** [comment]
😭

**Comment by thibaudcolas** [comment]
Reproducible on the https://springload.github.io/draftail/, and also on https://thibaudcolas.github.io/draftjs-filters/.

Most likely this is due to a bug in handling of `delete` when the selection is precisely on/within an atomic block (https://github.com/facebook/draft-js/blob/73e5a9c3b57116a5a01d26016964ad3ba8fe0e66/src/model/modifier/RichTextEditorUtil.js#L153)

The issue looks a lot like https://github.com/facebook/draft-js/issues/1681#issuecomment-371143376, where [under some circumstances] Draft.js deletes the IMAGE entity, but not the atomic block it's displayed in, causing a crash.

The problem is more visible on the Draft.js filters repo, where there is a fallback "404" image if entities are missing:

![draftjs-delete-image-crash](https://user-images.githubusercontent.com/877585/37422079-ec502360-27ba-11e8-9a49-35e840edb527.gif)

---

For a fix, the first step would be to gracefully handle the absence of an entity on a block in Draftail:

https://github.com/springload/draftail/blob/f97df71641e89fe7165807cf187df734771ec813/lib/components/DraftailEditor.js#L393-L399

It could do a `return null` (thereby not displaying anything), or display some sort of error/placeholder.

With this out of the way, the editor will stop crashing but we still have the issue that this type of `delete` puts it in a weird state. Ideally this would need to be handled with a special case in `handleKeyCommand`, like what Draft.js does here (but better): https://github.com/facebook/draft-js/blob/73e5a9c3b57116a5a01d26016964ad3ba8fe0e66/src/model/modifier/RichTextEditorUtil.js#L72

This'd need further troubleshooting to find out what command exactly is fired, and why the default Draft.js `onDelete` does not correctly handle this scenario.

**Comment by thibaudcolas** [comment]
New behavior, which doesn't fully resolve the issue but at least prevents the crash:

![draftail-delete-image-softfail](https://user-images.githubusercontent.com/877585/37625420-89d5273a-2bd4-11e8-9c91-b9f81a5c3fac.gif)

This still has a block without its image, which is bad, so we still need a special case for `delete` in [`handleKeyCommand`](https://github.com/springload/draftail/blob/master/lib/components/DraftailEditor.js#L229) when inside of an atomic block, that does the right thing.
