### ISSUE TITLE
TypeError: required_fields() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by mikolajkosmal** [wagtail/wagtail#4377]
I've encountered the issue, after moving from wagtail 1.13 to 2.0

### Issue Summary

    Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fdd24fda9d8>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 225, in wrapper
        fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 120, in inner_run
        self.check(display_num_errors=True)
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 364, in check
        include_deployment_checks=include_deployment_checks,
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 351, in _run_checks
        return checks.run_checks(**kwargs)
      File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 73, in run_checks
        new_errors = check(app_configs=app_configs)
      File "/usr/local/lib/python3.4/dist-packages/wagtail/admin/checks.py", line 63, in get_form_class_check
        if not issubclass(edit_handler.get_form_class(), WagtailAdminPageForm):
      File "/usr/local/lib/python3.4/dist-packages/wagtail/admin/edit_handlers.py", line 336, in get_form_class
        fields=self.required_fields(),
      File "/usr/local/lib/python3.4/dist-packages/wagtail/admin/edit_handlers.py", line 261, in required_fields
        fields.extend(handler.required_fields())
      File "/usr/local/lib/python3.4/dist-packages/wagtail/admin/edit_handlers.py", line 261, in required_fields
        fields.extend(handler.required_fields())
    TypeError: required_fields() missing 1 required positional argument: 'self'

### Technical details

* Python version: 3.4
* Django version: 2.0
* Wagtail version: 2.0

**Comment by gasman** [comment]
Thanks for the report, @mikolajkosmal.

In your project, have you defined any custom subclasses of `EditHandler` (or any other classes from https://github.com/wagtail/wagtail/blob/master/wagtail/admin/edit_handlers.py)? This is an internal API that's been changed in Wagtail 2.0, and so you'll need to update your project code accordingly.

**Comment by po5i** [comment]
+1
Hello @gasman, I have the same issue, maybe I can provide more info for you guys...

Indeed I had in my code in some places this import line:
```
from wagtail.admin.edit_handlers import BaseFieldPanel
```
Which I changed for
```
from wagtail.admin.edit_handlers import FieldPanel
```
But I just realized that this is wrong since `FieldPanel` existed before.

So, how can I upgrade this change?

**Comment by gasman** [comment]
Hi @po5i,
It's best to refer to the commit that introduced this change: https://github.com/wagtail/wagtail/commit/5fc191b116ee835762c282e13a5829fa873cc516#diff-507d1915f772f388fd0ef0447953585f

`StreamFieldPanel` is probably a good thing to compare against.

In the old API, you had to define two classes, which we'll call `BaseFooPanel` and `FooPanel`: the definition inside `content_panels` would be an instance of `FooPanel`. This object wasn't very useful by itself, because it didn't know which model class it was attached to... but as soon as a reference to that model class became available, we would call `bind_to_model`, which would construct a specially-adapted subclass of `BaseFooPanel` for working with that model.

In the new API, these are combined into a single `FooPanel` class that inherits from `FieldPanel`, and all the 'binding' happens behind the scenes. All the methods from `BaseFooPanel` should now be moved to `FooPanel`, and if there's any special initialisation code in `bind_to_model` (other than simply copying attributes across), this should now happen in an `on_model_bound` method.

**Comment by po5i** [comment]
Thanks @gasman that was helpful

I am rewriting my classes, but I found one that on the `BaseFooFieldPanel` (that inherits from `FieldPanel`) on the `__init__` method I have:
```
    self.bound_field.field.widget.read_only = read_only
    self.bound_field.field.widget.repository_type = self.repository_type
```

So, I move those lines to my `__init__` method on`FooFieldPanel`. Now, I get:
```
AttributeError: 'FooFieldPanel' object has no attribute 'bound_field'
```

Where should be the best place to move those lines? I'm wondering that I should override some parent method...

**Comment by gasman** [comment]
@po5i Looks like that should go into an `on_instance_bound` method.

**Comment by Dalal0** [comment]
I think you should try: `from wtforms.validators import input_required` instead `required_fields`

Example: 
`
class Login_form(FlaskForm):
    email = StringField('Email *', validators=[input_required(), Email('Invalid email*')])
    password = PasswordField('Password *', validators=[input_required(), Length(min=8, max=20)])
    remember = BooleanField('Remember me')
`


Otherwise if you get error: `TypeError: hidden_tag() missing 1 required positional argument: 'self'`
try:
`
@app.route('/login', methods=['POST', 'GET'])
def login():
    return render_template('login.html', Login_form=Login_form('/login'))
`
