### ISSUE TITLE
documentation of Page.url property mentions *argument*

### ISSUE THREAD

**Issue by sir-sigurd** [wagtail/wagtail#4424]
See http://docs.wagtail.io/en/v2.0/reference/pages/model_reference.html#wagtail.core.models.Page.url

> Accepts an optional but recommended request keyword argument that, if provided, will be used to cache site-level URL information (thereby avoiding repeated database / cache lookups) and, via the request.site attribute, determine whether a relative or full URL is most appropriate.

**Comment by loicteixeira** [comment]
Hi @sir-sigurd, it is unclear to me what you are pointing out here, can you provide more information?

Arguably the function actually accepts [2 arguments][1] (`request` and `current_site`) so it could probably be updated, but maybe you only want to point out that the documentation is not clear to you?

[1]: https://github.com/wagtail/wagtail/blob/18dd01a4cc7f7c51680400d7f39f80d661c4b1d5/wagtail/core/models.py#L787-L820

**Comment by sir-sigurd** [comment]
@loicteixeira 

I want to point that 'argument' is meaningless in the documentation of `Page.url` since it's not callable.

![image](https://user-images.githubusercontent.com/481910/37887915-ed9d0c48-30dd-11e8-8a1a-ed137878a9c5.png)

**Comment by gasman** [comment]
Thanks for the report @sir-sigurd!

Fixed in 8d786c35349f097b1c9c8cdc5c36f81cb68386ec - as of #3354, the preferred way of obtaining a page URL in Python code is the `get_url` method. `url` is now just a wrapper around `get_url`, and this meant that the documentation (which was still referencing `url`) erroneously picked up the docstring from that method.
