### ISSUE TITLE
Regression in PostgreSQL search backend: prefiltering doesn't work anymore

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#4425]
### Issue Summary

Wagtail 2.0 and earlier eversions have different behaviour in PostgreSQL search backend.

### Steps to Reproduce

In Wagtail 1.13.1:

1. Run `./manage.py shell`
2. Run the following code snippet:
    ```python
    from wagtail.wagtailcore.models import Page
    Page.objects.filter(live_revision__gte=1).search('home')
    ```

The `search` method returns a `SearchResults` object.

In Wagtail 2.0:

1. Run `./manage.py shell`
2. Run the following code snippet:
    ```python
    from wagtail.core.models import Page
    Page.objects.filter(live_revision__gte=1).search('home')
    ```

It throws the following exception:

```python
FilterFieldError: Cannot filter search results with field "live_revision_id". Please add index.FilterField('live_revision_id') to Page.search_fields.
```

### Technical details

* Django & Wagtail versions: Django 1.11.8 + Wagtail 1.13.1 (the first scenario) and Django 2.0.3 + Wagtail 2.0 (the second scenario)
* Python version: 3.6.1, but, I think, it doesn't matter

**Comment by m1kola** [comment]
Actually, I it doesn't look like the previous behaviour was documented. At least, I can't find anything about it. So, probably, it's not a bug/regression.

@kaedroho @BertrandBordage I know you guys were working on this during the Bristol sprint last year (and in general). What is your opinion on this?

**Comment by gasman** [comment]
Yes, I'm pretty sure this was deliberately tightened up to make the behaviour more consistent across search backends. I think #3947 is the relevant PR, but it's a bit hard to tell :-)

**Comment by BertrandBordage** [comment]
@kaedroho wanted to get the same behaviour on both backends, so the query willingly breaks.

I wasn’t a big fan of that change, making something break just because the other backend doesn’t support it didn’t seem great.

That being said, the idea with Wagtail search is to first make all backends behave the same, then create a system to have specific features and limits, in the same way Django’s ORM was built: first the same base for everyone, then some PostgreSQL & MySQL specifics.

**Comment by m1kola** [comment]
Ok, I think, we can close this issue then. It has not been documented and it has been done deliberately.

Thank you both for the input.
