### ISSUE TITLE
copy paste from rich text editor X to rich text editor Y loses links/hr

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#4432]
I read through https://github.com/wagtail/wagtail/issues/4274 but we're running into a situation where we have a streamfield with richtext, and creating two richtext blocks, then copy/pasting from one richtext block to the other loses any link information, as well as `<hr>` elements, and from what I can tell, also empty paragraphs.

Taking content from textbox 1 that has HTML representation:
```html
<p>test1</p>
<p></p>
<hr>
<p><a href=...>test2</a></p>
```
instead becomes the following content when copy-pasted into textbox 2:
```html
<p>test1</p>
<p>test2</p>
```

**Comment by thibaudcolas** [comment]
Hey @Pomax, I think both of those are covered by #4274. Thank you for reading through that first – I realise it might not be very helpful if you're not familiar with Draft.js (the labels in there come from its issue tracker), but we'll fix that over time. I've added better labels for those two things.

The empty paragraphs being removed is https://github.com/facebook/draft-js/issues/1082, and the hr / links being removed is https://github.com/facebook/draft-js/issues/787.  Fixing these would require overriding Draft.js copy-paste handling within [Draftail](https://github.com/springload/draftail) with a new implementation, which I'd love to do but likely won't have time for in the foreseeable future.

I'll most likely close this in favour of #4274 because it doesn't help much to keep issues open separately for every Draft.js bug that can't easily be acted upon. I think this issue might be fixed for links though (at least the external ones and email ones, maybe not the internal links) so will double check that first.
