### ISSUE TITLE
When model name of home page is changed, a server error results when Pages is clicked

### ISSUE THREAD

**Issue by DanAtShenTech** [wagtail/wagtail#4438]
### Issue Summary

I'm learning Wagtail and so am having to do some reorganization of classes.  I had started `Page` class names with the name of the template (e.g. `SaliqueGalleryPage(Page)`.  I've successfully removed these leading characters from all page classes (e.g. now `GalleryPage(Page)`) except the home page. By successfully, I mean that, after running migrations successfully, the pages still display correctly on the site and all of their defined fields can still be edited in the Wagtail admin.  However, though a change to the name of `HomePage(Page)` can be migrated successfully, the page cannot be found by the Wagtail admin after migrations.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject` and go through the Your First Site instructions through [this point](http://docs.wagtail.io/en/v1.13.1/getting_started/tutorial.html#extend-the-homepage-model).
2. Create a site in the Wagtail admin and associate HomePage as the root page of the site.
3. Edit the home page (note the url - used in step 6), add some information in the `body` field, and publish the page.  View the page to ensure it displays correctly.
4. Rename `HomePage(Page)` to `Home(Page)`, run migrations, and then click on Pages in the Wagtail admin.
5. The above-described error results.
6. Edit the home page in the Wagtail admin by going directly to its url.  Only the `title` field is displayed - the `body` field is not displayed.
7.  Visit the home page and only the word "Home" is displayed.

Perhaps this problem is somewhat related to [this issue](https://github.com/wagtail/wagtail/issues/157).

### Technical details

Python version: 2.7.12
Django version: 1.11.11
Wagtail version: 1.13.1
Browser version: Chrome 65

**Comment by gasman** [comment]
Hi @DanAtShenTech - thanks for the report.

This is because Django's `./manage.py makemigrations` command is not clever enough to detect that the class has been renamed, and treats it as a deletion and creation instead. Deleting the `HomePage` model means that the existing homepage instance reverts to a basic Page (which only has a title field).

Manually fixing the migration to perform a `RenameModel` operation (rather than a deletion/creation) before running `./manage.py migrate` should address this.

Unfortunately this isn't something we can fix within Wagtail - at best we could cover it in the documentation, but there's not really a good place for it since it ultimately boils down to acquired Django wisdom (namely: "you need to sanity-check the results of `makemigrations`, particularly when renaming things") and the documentation currently isn't geared towards people coming to Wagtail without prior Django knowledge...

**Comment by DanAtShenTech** [comment]
Thank you.  I have had bad experience with trying to rename Django models in the past (where it deletes the existing model and creates a completely new model), however, in this case it asked me if I had renamed  the model.  I hadn't seen that prompt before in the times that I've tried to rename a model, so that's why I went ahead and tried it.
