### ISSUE TITLE
namespaced hooks

### ISSUE THREAD

**Issue by Speedy1991** [wagtail/wagtail#4475]
It would be awsome if it would be possible to add an optional namespace to the hooks, e.g.:

```
@hooks.register('register_admin_urls', namespace='videos')
def urlpatterns():
  return [path('videos/', cmsv.VideosView.as_view(), name='all')]
```

and use it with:

`{% url videos:all %}`

**Comment by gasman** [comment]
Hi @Speedy1991 - thanks for the suggestion.

This can already be achieved by passing the namespace as part of an `include` line - see [this example from the wagtail.contrib.forms app](https://github.com/wagtail/wagtail/blob/c3097533782833d2dbedea451da4825c3c86dcc5/wagtail/contrib/forms/wagtail_hooks.py#L11-L15).

It wouldn't really make sense to define this as a parameter to `hooks.register`, since hooks are used for many different purposes and `register_admin_urls` is the only one related to URL configuration.
