### ISSUE TITLE
Limit collections in image/document chooser based on permissions

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#4488]
### Summary
When a user is assigned to a group with permissions to add/edit images and/or documents to a collection named “Collection One”, the chooser still has a select with options for all collections.

### Quick and dirty solution:

wagtail/images/views/chooser.py

```
def chooser(request):
	...
	collections = None
	groups = request.user.groups.all()
	if groups:
		collection_permissions = GroupCollectionPermission.objects.filter(group__in=groups)
		if collection_permissions:
			collections = [cp.collection for cp in collection_permissions.all()]

	if not collections:
		collections = Collection.objects.all()
	
	if len(collections) < 2:
		collections = None

	...
```

### Technical details

* Python version: 3.6.4.
* Django version: 2.0.4.
* Wagtail version: 2.0.1.

**Comment by gasman** [comment]
Hi @robslotboom - thanks for the report.

The change you're proposing wouldn't be entirely correct - a user with no permission to add or edit images should still be able to select existing images to be inserted into their pages, and so it's intentional that the chooser ignores add/edit permission.

The correct way to fix this (and make it possible to limit a user's ability to choose images) would be to introduce a new 'choose' permission type. This was mentioned in passing in #4288, but it looks like we don't currently have an issue open to address this for images/documents, so I'll leave this one open as a feature request.

**Comment by robslotboom** [comment]
Thanks Matt,

I see the problem.

The project I am working on does has a kind of ‘choose’ permission.
It’s a portal with sites and each site has a corresponding group and collection…

I’ll wait and hope there will be a ‘choose’ permission type in the future :-)

Best regards,


Robert Slotboom

**Comment by marqpdx** [comment]
Yes, this is an important feature on one of our sites too. Users create a Member Profile for themselves, and need access to **only** their images, not that of all users.

+1 for this. 

thx,
m

**Comment by marqpdx** [comment]
OK, followup.

The core of the issue seems to be that there doesn't appear to be a way to turn off permissions for a User/Group for the Root level Collection. This i think should be added.

For the code above, the following line returns Root collection, plus whatever other Collections the user has permissions to. 
```
	if len(collections) < 2:
		collections = None
```
So even if a user is part of a specific collection, the drop down will always include the Root collection. This inclusion of root level is hard-coded in:`wagtail/images/templates/wagtailimages/chooser/chooser.html` which includes `

So it seems we could add a permission to deny access to the Root Collection, and we'd be a lot closer.

**Comment by gasman** [comment]
@marqpdx There _is_ an explicit permission setting for the root collection - on a stock Wagtail install you can find it at Settings -> Groups -> Editors, under "Document permissions" / "Image permissions". Deleting these will revoke add/edit access on the root collection.

Yes, the dropdown has a hard-coded "all collections" option, but that really means "all collections that you have permission for".

**Comment by marqpdx** [comment]
hi @gasman 

i have a single user, the sole member of a group called Member. 

under the Member group permissions, i added Add and Edit for a new Collection i created. So to me, this user should only have permissions for the New Collection i added, yes? The new group did not have a line for Root permissions under Images.

this Member group has access the the Wagtail Admin, and has Add permissions for the Home page (Profile is under that).

this user is not a member of the Editor group, but i deleted Root from the Image section there, too.

when i am logged in as this user, and go to edit their page with an Imagefield, when i select the chooser, i first see all images, and then in the dropdown for Collections i see All, Root, and New Collection.

IMHO, they should not have permission to the Root collection, b/c it is not in their Group permissions, yet it shows up by default.

When i modify chooser.py as noted above to call `collections_user_has_any_permission_for` then Root drops off the select box in the image chooser, but the images that show include ones that seem to belong to no Collection at all. When i use the chooser to select my New Collection, it limits it to just this user's images, which is what i want.

So it appears access to Root Collection cannot being turned off as you described.

I tried this on my app, and on a brand new test install of Wagtail.

**Comment by gasman** [comment]
Right, yep - within the image chooser popup, you will see all collections including the root, because the chooser view ignores permissions entirely. It's nothing to do with the root collection having special treatment.

The proposal in this issue is to introduce a new 'choose' permission type. Once this exists, the behaviour of the chooser will be changed to only show collections the user has permission for, and revoking that permission from the root collection will cause it to disappear from the dropdown, as expected.

**Comment by robslotboom** [comment]
@marqpdx,

Maybe the code in the attached file will be of any help for the time being...
Restrict the pages, images and documents in the admin root view for a ‘sub site’ account.

Cheers,
Rob

[wagtail_hooks.txt](https://github.com/wagtail/wagtail/files/2101254/wagtail_hooks.txt)

**Comment by marqpdx** [comment]
thank you @robslotboom - will totally look into that.

**Comment by fransbernhard** [comment]
Hi @robslotboom ! Could you upload or link to your SiteAccountAdminGroup modal code?

**Comment by robslotboom** [comment]
Hi @fransbernhard,

Currently I’m not working on this project but maybe the attached file will solve your issue.

Cheers,
Rob
[wagtail_hooks.txt](https://github.com/wagtail/wagtail/files/2486726/wagtail_hooks.txt)

**Comment by robslotboom** [comment]
Hi Frans,


> Op 17 okt. 2018, om 10:19 heeft fransbernhard <notifications@github.com> het volgende geschreven:
> 
> Hi @robslotboom <https://github.com/robslotboom> ! Could you upload or link to your SiteAccountAdminGroup modal code?
> 

Have a look at github.

Best regards,

Rob

**Comment by robslotboom** [comment]
Hi @fransbernhard,

I guess it has something to do with changes in Wagtail itself.
Currently I don’t use this code anymore because I’m waiting for a ‘choose’ permission type in Wagtail

**Comment by RodrigoMGarcia** [comment]
How fix this problem?

**Comment by juan0tron** [comment]
For anyone having issues with  @robslotboom 's code, I was able to get it to work partially for the image/document choosers. I haven't figured out how to filter collections with a wagtail hook at the moment, so this will only filter the images/documents.

[wagtail_hooks.txt](https://github.com/wagtail/wagtail/files/3199299/wagtail_hooks.txt)

If you want further explanation, the `construct_document_chooser_queryset` and `construct_image_chooser_queryset` hooks don't accept a list of collections anymore, only documents/images. 

I simply removed "collections" from the return statements of `get_user_collections_and_documents()` and `get_user_collections_and_images()` in @robslotboom 's script and renamed the functions.

**Comment by juan0tron** [comment]
As an update to my previous comment: it IS possible to filter collections with a template override and a simple menu tag. For the template, override `/templates/wagtailadmin/shared/collection_chooser.html`, by copying the existing template from wagtail's source, then add these two lines:

{% load menu_tags %}
{% get_user_collections as collections %}

Then, register a new tag under menu_tags.py that will get the user's collections:

```
# Get a user's collections based on their groups
@register.simple_tag(takes_context=True)
def get_user_collections(context):
	user = context['request'].user
	collections = Collection.objects.all()
	if not user.is_superuser:
		groups = user.groups.all()
		if groups:
			collection_permissions = GroupCollectionPermission.objects.filter(group__in=groups)
			if collection_permissions:
				collection_pks = [cp.collection.pk for cp in collection_permissions.all()]
				collections = collections.filter(pk__in=collection_pks)
	return collections
```

**Comment by coredumperror** [comment]
@gasman How does this sound as a potential solution for limiting chooseability to specific Collections?

Add a `choose` Collection permission, alongside `add` and `edit`, like discussed above. Then add a data migration that creates a `choose` permission on the Root collection for every existing Group. That should retain the existing choose behavior of the current system, where permissions are ignored when choosing, because every users will _explicitly_ have `choose` permission on every Collection (since permissions cascade). 

Then, users who wish to limit choose permission can remove that `choose` entry for Root, and replace it with an entry that limits `choose` to one or more specific Collections. If you think that's a viable generalized solution that would make a good PR, I'll write said PR. 

This is just the kind of thing that Wagtail will need to implement fully separated multitenancy, as separate sites will need their own Collections, with users of Site A not being able to choose images/docs in Site B's Collection. Caltech already does something like this, but being able to implement it through permissions, rather than our monkey patches to various parts of the Wagtail code, would be ideal.

**Comment by gasman** [comment]
@coredumperror That plan sounds good to me! I'd just change one detail:

> a data migration that creates a `choose` permission on the Root collection for every existing Group.

should be: "every existing Group that has the 'can access Wagtail admin' (`wagtailadmin.access_admin`) permission". (Functionally this is no different, since groups with no access to the Wagtail admin obviously won't be able to access the chooser UI at all - but if there happen to be a large number of non-Wagtail-related groups on the system, we wouldn't want to create redundant permission records for them all.)

I think we'd still need to mention the new permission in the 'upgrade considerations' section of the release notes, for the benefit of developers who are creating groups programmatically or through fixtures and will need to update their code accordingly.

**Comment by coredumperror** [comment]
Yeah, good point on both counts. I'll incorporate that into the PR, once I write it. I'm currently finishing up the initial submission for another Collection-related PR, so I'll get to work on this one once the work I can do on that other one is blocked.

**Comment by coredumperror** [comment]
Hoo boy, it took me a looong time to circle back to this one. But I'm finally working on this. No clue yet how long it'll take, but as of today it's my primary focus.

**Comment by coredumperror** [comment]
OK, the first commit of the PR is up! Took me a while to *actually* get started on this, despite my assurance last week that I would make it my primary focus. lol

**Comment by coredumperror** [comment]
@gasman Alright, I think the PR is effectively done (baring code review). Please take a look. I'd love to get this into Wagtail 2.11, if possible.

**Comment by gasman** [comment]
Thanks @coredumperror! It's unlikely we'll get this into 2.11 I'm afraid - the release candidate was due at the start of this week, so we're already running a bit behind.

**Comment by coredumperror** [comment]
Drat! 

Well, do please let me know if there's anything I've missed with this PR, so that I won't be the blocker for getting this into 2.12.

**Comment by gasman** [comment]
Completed in #6466.
