### ISSUE TITLE
Tags over 100 characters

### ISSUE THREAD

**Issue by Chino96** [wagtail/wagtail#4564]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When adding a tag while using the ClusterTaggableManager class, if the tag name is greater than the character limit for the database column no validation error is given.

### Steps to Reproduce

1. login to admin and edit a page with a tag content panel
2. create a tag with more than 100 characters
3. save, or publish the page 

### Technical details

* Python version: Python 3.5.1
* Django version: 1.11.13
* Wagtail version: 1.13.1

**Comment by thoang43** [comment]
Hi, I and my friend are trying to fix this issue. We confirm that we can reproduce the bug already.
![image](https://user-images.githubusercontent.com/39248704/153656922-551f4606-7ee8-4ad8-9996-2a29df5c6ebd.png)

We are able to navigate the createTag function. However, we are not sure how the error should pop up. Should we pop a red message right below the tag area? This seems unnecessary since other errors do not show this way. Can we highlight the tag with color (yellow/red) and do not create the tag until the length is valid? In this case, the users may not know what is wrong with the tag. Do you have any suggestion?

**Comment by vupham04** [comment]
Hi, just want to check in again - I wonder if @thoang43 and I can get some feedback on our suggested solution above?

**Comment by vupham04** [comment]
Hi, because there is no comment, so we just create a pull request that create a ValidationError whenever the length of tag exceeds 100 characters. We think that modifying "A comma separated list of tags" to include a sentence about tag limit character would be a good additional too, but don't know how to do that - it seems that the help_text is taken from the default one of Taggit, so if anyone knows how to override that help_text, or have any comments about our code, please let me know

**Comment by lb-** [comment]
Thanks for that @vupham04
