### ISSUE TITLE
Feature request: Hooks for publishing and unpublishing pages

### ISSUE THREAD

**Issue by jonatasbaldin** [wagtail/wagtail#4590]
### Hooks for publishing and unpublish pages

Today the only mechanism to act upon the Publish and Unpublish Page actions are `Signals`, but I don't think they are useful because:
1. You can only execute code _after_ the action, not before
2. You don't have access to the `request` object

That said, I think we could use the `Hooks` mechanism to enable code execution before/after the publish/unpublish actions.

I created a small PR (#4591) to demonstrate how that could work. I didn't write any tests or documentation because I don't know if this interests the maintainers/users, but if so, I could improve the PR with that.

What do you think?

Cheers!

**Comment by gasman** [comment]
Thanks @jonatasbaldin! Happy with the principle of these hooks, but I think we need to be careful about how we specify and document their behaviour, since the 'publish' button on the edit page isn't the only point where a page might get published: it could be submitted for moderation and approved by a moderator, or it could be scheduled for publishing on a future date (in which case the actual publishing will happen from the `publish_scheduled_pages` management task, where there isn't a `request` object available at all).

(Also, if a page is 'published' from the edit page, but has a go-live date in the future, does that count as triggering the hook or not?)

Originally the `before_edit_page` / `after_edit_page` hooks were implemented as a way to modify the admin workflow: e.g. "if the user editing the page is in the 'restricted users' group, redirect them to a custom dashboard page instead of the standard explorer view". I think that's a useful guideline to stick to: anything related to the view / workflow level should be done with hooks, and anything at the model level (e.g. sending notifications, pushing the published pages to an external server...) should be done with signals.

If we're following that convention, then the behaviour as implemented in #4591 is mostly correct (but we should trigger the hook from the 'add' view as well as the 'edit' view). We should make this distinction clear in the documentation, though.

**Comment by gasman** [comment]
Hi @linxuanmax - please use the [Wagtail tag on Stack Overflow](https://stackoverflow.com/questions/tagged/wagtail) for support queries.

**Comment by lb-** [comment]
Merged in via #6000
