### ISSUE TITLE
Page Modal Search Doesn't Correctly Handle Results

### ISSUE THREAD

**Issue by trumpet2012** [wagtail/wagtail#4594]
### Issue Summary

When using the search inside a page chooser modal, if you do not type your search query fast enough it will make multiple requests for each letter you type. These AJAX requests are sometimes completed in an order different from the order they requested. This leads to the final search results being incorrect.

### Steps to Reproduce

1. Open any page chooser modal, such as the one for creating internal links.
2. Search for a page.

Here are two different videos showcasing the issue. https://imgur.com/a/m7Fu4Oj

### Technical details

* Python version: `3.5.4`
* Django version: `1.11.13`
* Wagtail version: `1.13.1`
* Browser version: Chrome 67.0.3396.79

**Comment by jjanssen** [comment]
Thanks for report! 

What currently is happening: when typing slowly the search makes a single request per character. So when you have a 3 requests pending and the 2nd one is taking more time then the 3rd one (which already came back), it will return results from the 2nd request.

I was able to confirm this suspicion by quickly adding a conditional `time.sleep` to the first two characters in the corresponding search view, because it didn't occur directly in my local development environment (a.k.a. it works on my machine).

When initiating a new search request it would make sense to cancel the previous Ajax request, to prevent this from happening.

**Comment by thibaudcolas** [comment]
Looking into this with @Esperk, it seems that this is an issue with all chooser modals, not just the one for pages.

**Comment by thibaudcolas** [comment]
Fixed in #5137, will be released in Wagtail v2.5!
