### ISSUE TITLE
Implement immutable page revision events per RFC 29, Task 1

### ISSUE THREAD

**Issue by dprothero** [wagtail/wagtail#4650]
[See RFC 29](https://github.com/wagtail/rfcs/blob/master/text/029-immutable-revision-events.md) for complete details. This issue is to implement Task 1 of that RFC.

**Comment by dprothero** [comment]
$500 bounty from Twilio: https://www.bountysource.com/issues/60101801-implement-immutable-page-revision-events-per-rfc-29

**Comment by loicteixeira** [comment]
I would like to work on this in September if nobody has had a go at it by then.

However some aspect of the RFC are still vague and I would like to discuss them.

**1. Immutability (of revisions and revision events):**

Are we talking immutability in principle (i.e. the model is mutable but we don't mutate it) or enforced immutability (i.e. it isn't possible to mutate the model via the ORM)?

The promise of immutability will be broken sooner or later if it's only in principle but enforcing it might be problematic for future migrations or fixups.

**2. Event Identifier (string)**

The RFC mention it should be *expandable by the user* and the attached notes mention *registering new events*. The notes also mention *expanding Page state beyond draft/live*, but once you allow states to be added, the next request will be about replacing or removing some of the default states. Does that mean that the built-in event types could be replaced?

What should happen to event types (either custom or built-in) which were once registered and used but aren't available anymore?

**3. Event Data (JSON)**

It makes sense for the `PageRevision` to have a `content_json` since:

- each page type is different so we can't have a defined list of fields
- while the data will be vastly different from a page type to another, the data is only ever accessed in the context of a unique page type (i.e. you don't compare the revision of the homepage with the revision of the contact form page)
- we always ever access the data as a whole and use it to load it onto a object
- the data is somehow non-essential to the revision itself
- we don't want/need to search through that data

But I'm not sure it is the right pick for a revision event since:

- we might want/need to search through that data
- for a given event type, we will need to access a particular key on the data; in other words, some fields are required for specific event type but it isn't something which can be enforced easily with JSON data.

Have other approach been though of? I can think of the following:

- Multiple table inheritance similarly to the `Page` model.
	- Each event type could define its own fields.
- Extensible abstract models similarly to the `AbstractImage`, `AbstractRendition` and `AbstractDocument`.
	- All the fields would be on the same model, but it would be possible to enforce some validation logic through forms.
- Swappable models, although it's not an official feature so it's probably not a good idea.

**4. Deprecation period?**

I don't think page revisions have ever been part of the public API, but should be worry of breaking changes?

**5. What's next?**

I understand that given the amount of work required, it had to be broken down in several steps but I'm afraid we would be solving step 1 with the hope that's it's going to work further down the line.

Design should be involved asap, not necessarily for the visual design (at least not at first) but for the user experience side of things. The different ideas thrown in the notes and the proposed wagtail/rfcs#24 raise many questions. While many of them might only involve UI (e.g. how to add comment to a revision of a specific field, how to tag revisions manually), other might require vastly different approaches (e.g. custom approval workflow).

**Comment by dprothero** [comment]
> 1. Immutability (of revisions and revision events):
> 
> Are we talking immutability in principle (i.e. the model is mutable but we don't mutate it) or enforced immutability (i.e. it isn't possible to mutate the model via the ORM)?

*At least* in principle. I've only been hacking on Django for a couple years and have never needed to enforce immutability, so I can't speak to how feasible it would be.

> 2. Event Identifier (string)
> ...
> Does that mean that the built-in event types could be replaced?

No, I would not envision that. The expandability is purely additive. The events/states managed within the Wagtail core would not be something that could be changed.

> What should happen to event types (either custom or built-in) which were once registered and used but aren't available anymore?

So, while not (theoretically) possible for built-in, this certainly could happen for custom event types. I would expect that they would remain in the database, but just not exposed via the ORM. That would seem to be the safest approach in case an event type was inadvertently removed, it could be re-added without the data being destroyed? (Again, not sure how this is implemented in Django.)

> 3. Event Data (JSON)

I don't think this is applicable to this RFC. You make valid points, but we are not proposing any changes to `PageRevision`. The RFC is only dealing with another model, `RevisionEvents`, and would not have any of the page content stored within them.

> 4. Deprecation period?

Again, we're not changing page revisions.

> 5. What's next?

Here is a doc with a brain dump of the notes that led to this specific step 1.

https://hackmd.io/s/ByDdmUZWm#

**Comment by loicteixeira** [comment]
Thank you for your answers @dprothero.

Just to keep everybody in the loop, life got in the way in September and I hadn't got time to work on this in the end. We had a chat with @chosak and he might have some time to pick it up.

Also, I would like to paste @kaedroho [comment on the RFC](https://github.com/wagtail/rfcs/pull/29#issuecomment-412490072) which many of us might have missed:

> I'm thinking it would be better if this event model was linked to the page as well as optionally being linked to a revision. This would allow events that aren't specific to a revision to be captured as well such as unpublishing, copying or moving the page.
> 
> I think we would like to add an admin log for admins to see all actions editors have performed on the site, including deletions. It would be great if this event model could be used for this use case as well.

**Comment by thibaudcolas** [comment]
It looks to me like this is no longer required (see [RFC 29](https://github.com/wagtail/rfcs/blob/main/text/029-immutable-revision-events.md)). Closing.
