### ISSUE TITLE
Account Register Page/API required

### ISSUE THREAD

**Issue by Marcnuth** [wagtail/wagtail#4670]
Currently, Wagtail only allows superuser to create a user.

But it is also necessary for a user to register his account by himself, and the superuser could limit its roles for permissions.

Please consider about this, this becomes more and more important in modern CMS system.

**Comment by gasman** [comment]
Hi @Marcnuth - thanks for the suggestion.

Wagtail uses the standard Django user/permission model, so it's fairly easy to set up a 'create user' view as part of your project, possibly using Django's provided [UserCreationForm](https://docs.djangoproject.com/en/2.0/topics/auth/default/#django.contrib.auth.forms.UserCreationForm). I don't think it makes sense for Wagtail to offer this as a built-in feature, because the mechanism will most likely be different on every site - I think it'd be rare for a site to offer completely open signup for anyone to become an editor. Rather, they'll have varying requirements for authentication (e.g. sending invitation emails, or requiring a specific email domain, or using an external account system such as LDAP), as well as differing in other details (which user groups should they be assigned to; are we using a custom User model; does the form need to be styled/branded to match the site front-end, etc).

Any built-in view provided by Wagtail would need so many configuration options that there would be little benefit over having the developer implement it themselves. It's potentially something that could be implemented as a third-party add-on, though.
