### ISSUE TITLE
Have python3 installed but wagtail won't install

### ISSUE THREAD

**Issue by officerebel** [wagtail/wagtail#4690]
Inside virtualenv 
Python2.7 and python 3.6 installed.
$ python3 -m pip install wagtail

$ wagtail python3  start mysite
This version of Wagtail requires Python 3.4 or above - you are running 2.7

**Comment by Meteor0id** [comment]
did you make that virtual environment with pip3 ? I have no idea what I am talking about, but I remember there was a seperate pip3 command for python 3 in some cases. Please look into that.

**Comment by mikedingjan** [comment]
Hi @officerebel ,

Can you try running
```
python3 -m wagtail start mysite
```

**Comment by officerebel** [comment]
Yes I have virtualenvironment and pip an pip3 installed wagtail

$ python3 -m wagtail start mysite

results in:
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3: No module named wagtail.__main__; 'wagtail' is a package and cannot be directly executed

$wagtail start mysite
results in:
This version of Wagtail requires Python 3.4 or above - you are running 2.7

**Comment by NDevox** [comment]
@officerebel sounds like you've installed wagtail as a python 2.7 package outside of your virtualenv first and that's overriding your current env. Remove it from the 2.7 one, wipe the virtualenv and try in a new one if you can.

**Comment by jjanssen** [comment]
Hi @officerebel  - please use the [Wagtail tag on Stack Overflow](https://stackoverflow.com/questions/tagged/wagtail) for support queries.

**Comment by alexrayu** [comment]
Installing the Wagtail as per instructions results in a non-working setup. When asking for help, users are redirected to StackOverflow instead.

**Comment by gasman** [comment]
Hi @alexrayu,
It simply isn't possible for the instructions to cover every situation that might occur on every platform, such as selecting the correct Python version when multiple versions are installed, as in the case here. This is not a Wagtail-specific issue, and so it's appropriate to ask on Stack Overflow, where there's a larger pool of people available to help, and better tools for gathering the necessary information.

**Comment by tomdyson** [comment]
@alexrayu thanks for taking the time to respond. We appreciate your perspective on this. FWIW, this wouldn't have helped the original issue creator, who wasn't following the instructions and had already installed Wagtail outside the virtualenv. On the other hand, we certainly want to make sure that our standard instructions work in default environments. Would you be happy to submit a PR with your suggestions? I have two points of feedback:

 - you don't need `env/bin/` in front of `wagtail start projectname`, because you have already activated the virtual environment
 - you need to `cd projectname` before you can `pip install -r requirements.txt`

**Comment by alexrayu** [comment]
@tomdyson Thanks, I have corrected my commands list for the future.

**Comment by gasman** [comment]
The docs have now been updated in #4849 to cover creating/activating a virtualenv.
