### ISSUE TITLE
Account Settings need better design

### ISSUE THREAD

**Issue by michael-yin** [wagtail/wagtail#4700]
When Wagtail 2.x are released, I have seen some new features in `account settings`.

Now user can edit timezone and even change email address in accout settings, I am sure people would not be satisfied and would like to add more functions in `account settings` page in future.

About `email changing`, let's first take a look at the current code.

```python
def change_email(request):
    if request.method == 'POST':
        form = EmailForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, _("Your email has been changed successfully!"))
            return redirect('wagtailadmin_account')
    else:
        form = EmailForm(instance=request.user)

    return render(request, 'wagtailadmin/account/change_email.html', {
        'form': form,
    })
```

1. User can change email address without confirming, is this really a good implementation?

2. What if I do not want my user to edit email address?

As you can see, the current design have some drawback and I really believe **we should be clear about what account settings in Wagtail should be** before merging PR from other people.

### What to Do and What Not to Do

I have built many projects using Wagtail, and I think the biggest feature of Wagtail is to help people `construct content, organize content, publish content`.

> Write programs that do one thing and do it well.     --Unix philosophy

**Wagtail should focus, focus, focus on the content part!** 

### What is the next step with Accout settings

Right now the account settings is not easy to customize, we need to find a better way to solve this problem.

1. Wagtail should work fine without the account settings feature. 

2. `wagtail.users.models.UserProfile` We should make this class like `AbstractUser` in Django, so developer can inherit it and add custom fields.

2. `ProfileEditForm` should be used same like `WAGTAIL_USER_EDIT_FORM`, developer can customize the profile edit page.

**Comment by gasman** [comment]
Hi @michael-yin - thanks for the comments.

Not sure what you mean re "wagtail should focus on content" - I definitely agree with the sentiment, but can you elaborate more on how that should influence the decisions we make on this feature? (It's probably fair to say that the account settings area hasn't had as much love as it needs from developers, precisely _because_ it's been lower priority than the core content editing features...)

I'd definitely like to see the account settings area reworked so that all settings are on a single form, rather than individual forms for each feature. We currently have a hook [`register_account_menu_item`](http://docs.wagtail.io/en/stable/reference/hooks.html#register-account-menu-item) for adding new entries to the account settings landing page - this was added mainly for the benefit of third-party Wagtail extensions (see #4421). We'd probably want to add a new hook for inserting additional sections into the new unified form (but keep the existing `register_account_menu_item` hook for backwards compatibility, and for the benefit of add-ons that are extensive enough to need their own page). This new hook could then be used in user code to insert custom fields (I don't think it would be feasible to support the hook _and_ swapping out the form class via a setting).

Rather than making the `UserProfile` model swappable (which is always a messy process), I'd suggest you create a separate custom model with a `OneToOneField` relation to User, so that the `wagtail.users.models.UserProfile` model remains Wagtail-specific.

I suspect that disabling the account settings completely would be quite an uncommon requirement, but it could probably be implemented quite neatly as follows:

* convert all existing forms in the accounts area (avatar, language, timezone etc...) to use the hook mentioned above
* provide a way to un-register those forms within user code
* if no forms are registered, hide the accounts area entirely

**Comment by zerolab** [comment]
#7050 addresses the bit for inserting custom fields/panels

https://github.com/wagtail/wagtail/blob/0790f3b1108c35d8b1469fccfe5f4c01be107592/wagtail/admin/views/account.py#L191-L210

**Comment by lb-** [comment]
Wagtail 2.13 introduced a new account settings interface which is much simpler.  

This, and the comment above, cover the main points of this issue.

It should be possible to block the accounts settings with either a template override. Which is the first point. 

I think we can close this. 

If someone wants to raise a new and more specific enhancement suggestion we can discuss further on that. Or if this should be re-opened, a core team member can do this.
