### ISSUE TITLE
Incompatible Unidecode requirement in wagtail and django-oscar

### ISSUE THREAD

**Issue by narunask** [wagtail/wagtail#4722]
### Issue Summary

It seems that `django-oscar` and `wagtail` want different versions of the `Unidecode`:
- django-oscar 1.6.3 has requirement Unidecode<1.1,>=1.0
- wagtail 2.1.2 has requirement Unidecode<1.0,>=0.04.14

### Steps to Reproduce

```
pip install django-oscar
pip install wagtail
```

Is it possible to run `wagtail` with the `Unidecode==1.0`? If so, could you please fix it on `pip`?

**Comment by gasman** [comment]
Hi @narunask,
This has been already been updated on master and the forthcoming 2.2 release, but I forgot to include it in 2.1.2, sorry. Since the release of 2.2 is only a few days away it's unlikely that there'll be another 2.1.x release - if you need a pip-installable version of Wagtail with Unidecode 1.0 support, I'd suggest using the 2.2 release candidate (`2.2rc2`).
