### ISSUE TITLE
AppRegistryNotReady("Apps aren't loaded yet.")

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#4729]
### After updating wagtail from 2.1 to 2.2 I get an AppRegistryNotReady error when migrating.

Removing **from .sitemap_generator import Sitemap**
from **wagtail/contrib/sitemaps/__init__.py**
fixed the problem.

Maybe it has something to do with the User model; I use a custom one.

**Comment by gasman** [comment]
Hi @robslotboom,
I think this is because you have `wagtail.contrib.sitemaps` in INSTALLED_APPS - this hasn't been required since Wagtail 1.10. However, there was never a release note to explicitly tell people to remove it, so I think it's appropriate for us to fix this so that `wagtail.contrib.sitemaps` in INSTALLED_APPS doesn't break... I'll work on a fix now.

**Comment by robslotboom** [comment]
Hi @gasman,

Does this mean I can remove wagtail.contrib.sitemaps from INSTALLED_APPS?

**Comment by gasman** [comment]
@robslotboom Yes, you can. (You may need to add `'django.contrib.sitemaps'` if it's not there already, though.)

**Comment by robslotboom** [comment]
Hi @gasman,

Thanks.

**Comment by robslotboom** [comment]
Hi @gasman,

Removing wagtail.contrib.sitemaps from INSTALLED_APPS is indeed solving this for the time being.
