### ISSUE TITLE
Master README.md not accurate regarding django version support

### ISSUE THREAD

**Issue by daredevil82** [wagtail/wagtail#4752]
The current [README on master](https://github.com/wagtail/wagtail/blob/6604cdfdaebff52b5c2446136e8ebc66412cee28/README.md) is not accurate as far as django versions supported from the release available on pypi.  Specifically, [`pip install wagtail`](https://pypi.org/project/wagtail/) installs v 2.2.1, which is _not_ compatible with django 2.1.x.

This is a significant issue for incoming users to wagtail who have latest django installed on their venv and want to use wagtail only to find its not installable.

However, the latest release [2.2.1 readme](https://github.com/wagtail/wagtail/blob/v2.2.1/README.md) _is_ accurate regarding version support, but expecting users to look at the tag readme for basic startup instructions over master is problematic.

I can appreciate the challenges of making release updates and keeping information up to date.  And the information does exist, just in a different location and is possibly causing frustration with potential users.

**Comment by gasman** [comment]
Hi @daredevil82 - thanks for the report. I don't think there's much we can do here, though - Wagtail's Github presence is ultimately a resource for developers _of_ Wagtail rather than Wagtail implementors, and if we held back updates to the readme so that it reflected the last release version, then we'd be faced with the opposite problem, i.e. developers thinking that Django 2.1 support is still an outstanding task. (We'd also have the extra admin work of keeping track of pending changes to the readme for the next release...)

We do aim to keep a 2-month release cycle for Wagtail feature releases, so the lag between features appearing in Github and being shipped in a release should hopefully be minimised.

**Comment by tiffanynwyeung** [comment]
Apologies for resurrecting a closed topic, but as someone who was excited to read about Django 2.1 support in not only the master branch README, but also on https://docs.wagtail.io/en/latest/getting_started/integrating_into_django.html, it's extremely frustrating to go through the trouble of finding out that wagtail is actually incompatible with my project when there is official documentation that says it is.
