### ISSUE TITLE
Feature request: a Category class, similar in many ways to the Page class, but without rendering a view and without a url_path

### ISSUE THREAD

**Issue by Meteor0id** [wagtail/wagtail#4764]
Some things can only be achieved using the Page class at this time. But sometimes one might which to cherry pick some functionality the Page class has, while leaving other functionality behind.

For example one thing I would like to have are categories. There are Pages which have no URL_path to visit, do not render, and have no editable content other than the title, but which are part of the pages tree, can be created as child page of a Page model, and can have children of the Category type or of the Page type.
Think of them as dummy pages if you will.

Model admin comes close, but not close enough. A model which does not inherit from the Page class can not be defined as a subpage_type or parent_page_type. Therefor they can not be used as tree elements like Pages can.

To sum that up, I propose a class to inherit from so one may create:
- a model wich I can set up as a subpage and parent_page of Page models.
- a model which can be created as child page of other models though the editor interface, just like Page models.
- a model which does not actually have a url_path, and does not render a template.
- a model which does have a path field and a numchild field. (but not a url_path field)

Use case:
Though a custom template tag such model may aslo be retreived, for example to group pages in a site navigation element. If this where doen with models based of the Page class, the urls would become unnessesarily long, and it would have a negative impact on SEO. A Category class would provide a solution for such problem.

**Comment by zerolab** [comment]
I think https://posts-by.lb.ee/building-a-configurable-taxonomy-in-wagtail-django-94ca1080fb28 describes what you are looking for, achieved with Treebeard's MP_Node and ModelAdmin rather than Page models

**Comment by Meteor0id** [comment]
I am hoping a class for this can be added to Wagtail natively (in the future). Glad to see this stackoverflow question, suggesting I am not the first to look for something like this.

@zerolab I was pointed to that same article by its author earlier today. It is certainly an approach to what I am requesting here, but it is still missing the same ease of ordering in Wagtails interface like I would with models based of the Page class. Most importantly, it is missing things like subpage_type and parent_page_type. I want to emporer editors to add, move around, and delete these categories just like ordenary pages, while constraining editors from using them all over the place.

**Comment by Meteor0id** [comment]
A category class would be quite similar to why there is a root note. To quote Gasman on that:

> Setting 'Root' as the root page of your site is a bad idea. The tree root is not designed to be an editable page, and only really exists as an implementation detail so that you can navigate to the top level within the explorer.

That's excatly what I am proposing to add further down in the tree as well, a page only there to aid navigation. A categroy page would be editable in some ways, such as locking it, scedualling when it goes public, changing its privacy, etc. It has all the fields a Page has, minus the url_path. It cannot be viewed nor previewed, and cannot contain content such as textfields or images of its own.

**Comment by gasman** [comment]
Hi @Meteor0id,
There are a couple of things here that I don't think will be architecturally possible:

* Having a model in the page tree that _doesn't_ inherit from the base `Page` model. This would mean tree methods like `Page.get_children()` would have to be aware of all other models that might appear in the tree, perform separate queries on each such model, and return the results in a custom data structure rather than a Django queryset - this would amount to a complete rewrite of the Treebeard library.
* Disabling the `url_path` field for one particular model. `url_path` isn't actually used for locating pages for a given URL - that's done by looking up the top-level page based on its slug and calling  (which then recursively does the same thing for its child pages, unless `route` has been overriden, e.g. for RoutablePageMixin). Effectively, `url_path` is just an extra copy of the URL path that logically exists already, based on the page's tree position and slug - clearing it wouldn't answer the question of "what happens when you visit this page's _logical_ URL".

Given that a model in the tree has to be a `Page` model and has to have an implied URL path, there are only two options I can see of making it "not a standard page":

1) Create your category tree at the root level of the page tree, and don't assign a Site record to it, so that while it has a `url_path`, it doesn't have an accessible URL;

2) Define a `serve` method that serves a 404 when the page is visited directly (or redirects elsewhere, or whatever other behaviour you decide is appropriate):

    def serve(self, request):
        raise Http404("Page does not exist")

(I realise this was suggested and immediately dismissed in Slack, but if your other requirements are fixed, this seems to be the only other option...)

Since these approaches involve zero and one lines of code respectively, I don't think there's much value in making them a built-in feature of Wagtail.

One thing that _is_ on our long-term wishlist is to move more of the specialised behaviours of Wagtail's models (e.g. tree navigation for pages, renditions for images) into mixins and class-based views, so that developers can define similar models through something like ModelAdmin. In this case, this would mean being able to define a Category model that exists separately to the page tree but has the same kind of tree navigation. However, this would need further specification and is out of scope for this issue.
