### ISSUE TITLE
Error 'Site' object has no attribute 'settings' after integrating into existing Django project

### ISSUE THREAD

**Issue by yogesh-kamble** [wagtail/wagtail#4792]
I followed integration docs from here
[http://docs.wagtail.io/en/v2.2.2/getting_started/integrating_into_django.html](http://docs.wagtail.io/en/v2.2.2/getting_started/integrating_into_django.html)
and integrated wagtail into saleor project.

But when I try to access home page I get following error

> 

Request Method: | GET
-- | --
http://localhost:8000/en/
2.0.8
AttributeError
'Site' object has no attribute 'settings'
/Users/synerzip/tutorial/saleor/saleor/core/views.py in home, line 17
/Users/synerzip/tutorial/saleor/env/bin/python3
3.6.3
['/Users/synerzip/tutorial/saleor',  '/Users/synerzip/tutorial/saleor/env/lib/python36.zip',  '/Users/synerzip/tutorial/saleor/env/lib/python3.6',  '/Users/synerzip/tutorial/saleor/env/lib/python3.6/lib-dynload',  '/anaconda3/lib/python3.6',  '/Users/synerzip/tutorial/saleor/env/lib/python3.6/site-packages',  '/Users/synerzip/tutorial/saleor']
Fri, 28 Sep 2018 00:28:13 -0500

>

**Comment by gasman** [comment]
Hi @yogesh-kamble - thanks for the report.

It looks like something in your project is setting `request.site`, most likely because you have `django.contrib.sites.middleware.CurrentSiteMiddleware` enabled, and this is conflicting with Wagtail's `request.site` variable. There's a plan to eliminate Wagtail's `request.site` detailed at https://github.com/wagtail/wagtail/issues/3834#issuecomment-340009510 - see also #4748.
