### ISSUE TITLE
Read The Docs default version should be "latest"

### ISSUE THREAD

**Issue by benjaoming** [wagtail/wagtail#4867]
### Issue Summary

Thanks for accurately tracking documentation for individual releases with tags! This is important!

Currently, navigating to `https://docs.wagtail.io/`, redirects to `https://docs.wagtail.io/en/v2.3/`. This way, we will have humans and search engines remember and spread URLs as permalinks to a version that's going to be replaced.

Instead, use `https://docs.wagtail.io/en/latest/` -- nevermind that this can have the side-effect of a few future 404s as things are moved around. This is a design and implementation issue for RTD IMO... not for individual projects to worry about.

Fix: Change the setup on RTD:

![image](https://user-images.githubusercontent.com/374612/47616328-a82c1180-dabb-11e8-9b32-ff2bbf56b1a1.png)

### Steps to Reproduce

Go to https://docs.wagtail.io/

### Technical details

n/a

**Comment by gasman** [comment]
Hi @benjaoming,
`latest` is not a suitable choice for the default, as this tracks the git master which might not match the status of the current release. (For example, during the Wagtail 2.3 development, several people followed the 'latest' documentation by mistake and were misled into thinking Django 2.1 support was already available - see #4752.)

Redirecting to `stable` would be an option, but I think it's better overall for URLs to reference a specific version when people share them on (e.g.) Stack Overflow, so that they are guaranteed to remain active and accurately reflect the content that was in place at the time. This is the same approach used by the Django docs.

Search engines should honour the `<link rel="canonical">` tag in the page metadata, which points to the current release version. There are some outstanding issues with this caused by RTD's use of tags rather than branches - many of the older versions can't be regenerated due to broken dependencies or configuration changes at RTD's end, and we can't retrospectively fix them without deleting and recreating the tag - but we're working on a solution for this.

**Comment by benjaoming** [comment]
@gasman 

> `latest` is not a suitable choice for the default, as this tracks the git master which might not match the status of the current release.

RTD can configure this behavior.

![image](https://user-images.githubusercontent.com/374612/47618941-17fcc500-dad9-11e8-8c8a-f5ae5620dd3e.png)


> Search engines should honour

Then, there are also humans who will copy-paste links to Stack Overflow -- but having just googled `link:docs.wagtail.io`, it doesn't seem that bad. You can review the results on StackOverflow here:

https://www.google.com/search?hl=en&q=%22docs.wagtail.io%22+site%3Astackoverflow.com

Anyways, no biggy, taking a lot of inspiration from the "Wagtail way", so was also wondering if this could act as an improvement or not. Thanks for the response!

**Comment by benjaoming** [comment]
The obvious disadvantage of setting the default branch is obviously that it has to be updated at each release.
