### ISSUE TITLE
Pages named "before" raise slug validation errors on save

### ISSUE THREAD

**Issue by dougfir-lc** [wagtail/wagtail#4881]
### Issue Summary

Naming a new page "**before**" or "**Before**" seem to leave the slug field blank on save, thus raising a page validation error. Manually entering the slug and saving the page a second time resolves the issue. I have tested this in versions 1.13.1 and 2.2.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create a child page (in this case a homepage but any model that inherits Page seems to have this issue)
3. Name the page **before** or **Before** and save.
4. Following error is raised "The page could not be created due to validation errors" and promote tab is highlighted.
5. Click on Promote tab and see that the slug field is empty.
 
Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
This is a page because it doesn't generate the slug as it would for any other page title. Entering the slug manually or adding a character to 'before' ex.(before2) allows it to auto generate the page slug as expected.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
Yes

### Technical details

* Python version: 3.6.
* Django version: 1 and 2
* Wagtail version: 1.13.1 and 2.2
* Browser version: Chrome, Safari, Firefox

<img width="1339" alt="before_error" src="https://user-images.githubusercontent.com/43281330/47811504-2c240a80-dd03-11e8-9eb4-16971c1645e6.png">
<img width="1339" alt="before_error2" src="https://user-images.githubusercontent.com/43281330/47811505-2c240a80-dd03-11e8-9215-6e4e73cd260d.png">
<img width="1326" alt="before_error3" src="https://user-images.githubusercontent.com/43281330/47811606-5ece0300-dd03-11e8-9f46-25e7a0be4990.png">

**Comment by gasman** [comment]
Hi @dougfir-lc - thanks for the report.

This will be because "before" is on the list of stopwords that get removed by Django's URLify function:

https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/contrib/admin/static/admin/js/urlify.js#L172

We should add a special case (probably in [cleanForSlug](https://github.com/wagtail/wagtail/blob/0dacda913337d6a24c962b906811b857679831b2/wagtail/admin/static_src/wagtailadmin/js/page-editor.js#L240)) that catches when the result of URLify is empty, and if so, falls back on the alternative implementation that doesn't remove stopwords.

**Comment by gasman** [comment]
Hi @chosak,
I don't have any strong opinion on whether it's better to keep or remove stopwords in slugs, but I do strongly feel that editors shouldn't be _expected_ to care about the details of slugs, and features that a user doesn't care about should get out of the user's way to the greatest extent possible. On that basis, I'd consider the current bug (failure to automatically deal with a title like "Before") to be more severe than the issue of URLify producing surprising output - so I'd prefer to go ahead with the immediate fix, rather than let it get bogged down in a wider discussion of the ideal behaviour of URLify.

**Comment by chosak** [comment]
@gasman thanks; that makes sense to me. I was hoping there might be time to consider larger changes to URLify before 2.4, but I can see the value in moving forward with this fix to address it for now.
