### ISSUE TITLE
Add documentation for ParentalKey

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#4909]
## Issue Summary
The ParentalKey class seems to be missing documentation. There is no docstring, and searching the Wagtail docs site turns up few relevant results.

**Comment by tim1724** [comment]
That's because it's not part of Wagtail per se. ParentalKey is defined in [django-modelcluster](https://pypi.org/project/django-modelcluster/).

But modelcluster's documentation is fairly minimal and it might be a good idea to cover it directly in the Wagtail documentation. It's pretty central to Wagtail after all.

**Comment by dameeolawuyi** [comment]
Hi all. I would like to write a documentation for Parental key if I could be pointed to the resources needed.

**Comment by zerolab** [comment]
`ParentalKey` is provided by https://github.com/wagtail/django-modelcluster
The package README has the explanation

**Comment by zerolab** [comment]
Also, it looks like we have more docs about it - https://docs.wagtail.org/en/stable/topics/pages.html#inline-models

Thank you all
