### ISSUE TITLE
Expose `getSelectedBlocksList` and `getSelectionText` as globals

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#4911]
See [DraftUtils.js](https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/client/src/components/Draftail/DraftUtils.js).

It would be great to have these exposed like `window.draftail.utils.getSelectionText` and `window.draftail.utils.getSelectedBlocksList`.

Chances are, if you're making a Draftail plugin, you'll need to use these. Maybe `window.draftail.utils` can be designated for helper-functions used in plugin creation.

**Comment by thibaudcolas** [comment]
#8923 exposes Draftail’s DraftUtils, which I believe is the most important set of utils to have available. For `getSelectedBlocksList` and `getSelectionText`, I’m not convinced they are that worthwhile to have reusable for third-party plugins. They’re only so complex because they support multi-line selections. Even for what they’re used for right now (pre-populating the page chooser’s link text field), there isn’t really any value to end users in supporting multi-line selections, as links are single-line anyway.
