### ISSUE TITLE
Make better use of logging

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#492]
We should add some better logging into wagtail.

Some examples:
- INFO logs when pages are created/published/edited/deleted/etc
- WARNING logs when there are permission issues, bad uploaded files, etc

This could really help people diagnose issues with their sites. And it would've been very useful if we had this on RCA on a couple of occasions in the past.

**Comment by kaedroho** [comment]
I'm thinking the logger names for the whole admin interface should be prefixed with ``wagtail.admin``.

Eg. ``wagtail.admin.pages``, ``wagtail.admin.images``, etc.

Loggers for the internals of a particular module would be named after the module.

eg. ``wagtail.core``, ``wagtail.images``, etc.

Any ideas/comments?

**Comment by gasman** [comment]
Sounds good to me!

**Comment by okal** [comment]
Any hope of this happening? :-) Trying to find out why moderation emails aren't going through, but there doesn't seem to be a way to figure that out in retrospect.

**Comment by lb-** [comment]
Not sure if this can be closed now that we have extensive logging / page history and auditing features.

https://docs.wagtail.org/en/stable/extending/audit_log.html

**Comment by gasman** [comment]
Yep, closing. While @kaedroho does specify that this refers to Python logging to the console / logfiles as distinct from the database, I believe the audit log serves this purpose for 'INFO' level logging. That just leaves 'warning' logs, and since the list suggested here is open-ended, this doesn't count as an actionable task that can ever be considered 'complete'.

If anyone still feels there are places where Wagtail is still lacking adequate logging, I'd suggest they open a new issue identifying specific conditions that should be logged.
