### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get_prep_value' after trying to use a StreamField

### ISSUE THREAD

**Issue by support-wantify** [wagtail/wagtail#4962]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Whenever I try to migrate, I get the error: AttributeError: 'str' object has no attribute 'get_prep_value'

### Steps to Reproduce

1. Add a StreamField at one point
2. Remove StreamField - the error sticks around

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I cannot migrate, so that's why I feel that it's a bug.

### Technical details

* Python version: Run `python --version`.
3.7.0

* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
2.1.3

* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`.
2.3

* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.

This is happening in the terminal

**Comment by gasman** [comment]
Hi @support-wantify - thanks for the report.
Unfortunately there's not enough information here for us to replicate the issue or determine whether it's caused by a Wagtail bug or user error - adding and removing a StreamField on a newly-created Wagtail project does not produce this error as described. To investigate further, we would need to know the exact sequence of steps which produces this.

You may be able to get further support on this [on Stack Overflow or the Wagtail Slack workspace](https://docs.wagtail.io/en/stable/support.html), but you'll need to provide full detail of the problem, including the complete error traceback, the code change you made before creating the migration, and the resulting migration file.
