### ISSUE TITLE
Reordering Pages in admin stopped working

### ISSUE THREAD

**Issue by 5in4** [wagtail/wagtail#4964]
### Issue Summary
Reordering Pages in admin stopped working, new state is not saved to database

### Steps to Reproduce

As default, pages are ordered by UPDATED. Clicking on "Enable ordering of child Pages" does not change the view to the previously defined order, but ordering stays sorted by UPDATED

When dragging a Page to a new position, a POST request with the correct new order is done, but nothing is saved to the database.

As a result we are not able order pages anymore.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no, only one project/data set is affected

At this point I am assuming this has something to do with our document tree (about 3000 pages, the management command fixtree found issues, but did not resolve the issue). If needed, I might be able to momentarily provide access to an environment where this behaviour occurs.

### Technical details

* Python version: Python 3.5.2
* Django version: 2.0.8
* Wagtail version: 2.3
* Browser version: Firefox Developer Edition 65.0b4 (64-bit) on macos (doesn't seem to be browser related)

**Comment by gasman** [comment]
Hi @5in4 - can you share the output of the `fixtree` command, please?

**Comment by 5in4** [comment]
Hi,

this is the output when I run fixtree now:

`$ ./manage.py fixtree`
`No problems found.`

When I ran fixtree before, it found an issue which could be fixed, but it changed nothing in behaviour

**Comment by gasman** [comment]
Ah, I misread - I thought fixtree was reporting issues that it couldn't fix itself... Thanks for the clarification.

Just to be sure that this isn't the UI issue described in #882 - can you confirm that clicking on "Enable ordering of child Pages" again after doing the POST still shows the pages in the original (updated-at) order?

**Comment by 5in4** [comment]
Yes. With enable ordering enabled, I can drag all items to the position I want them to be, after disabling it again all changes are lost and it reverts to sorting by updated at.

**Comment by gasman** [comment]
And if you _re-enable_ it again after that, they're still lost?

**Comment by 5in4** [comment]
Yes. Here's a gif showing the behaviour:
![ezgif-1-fc1653cbe4a2](https://user-images.githubusercontent.com/286750/50283856-769a4b80-0457-11e9-9c6e-44cf476f5b38.gif)

**Comment by NickdeDycker** [comment]
In our case we need to order something like chapters in a book and this quite bothering us. The UX for ordering at the moment is confusing. You can order your fields, but you'll only actually see this order when you are busy ordering? Another thing is that a queryset is actually ordered by `ord` and not by `-latest_revision_created_at`.

I propose an easy (and backwards compatible) change. At the moment the ordering is like this:
`ordering = request.GET.get('ordering', '-latest_revision_created_at')`

Change it to: 
`ordering = request.GET.get('ordering', getattr(parent_page, sort_order, '-latest_revision_created_at'))`

It keeps the current ordering so nothing changes, but by setting sort_order to 'ord' it changes the ordering on a per page basis. I feel like this is the best solution as ordering pages is not useful on every page, but this way you can enable it if you need it. You're also able to sort on other fields this way. 

A thing to consider is if we should  add a default to the Page object. It might be more clear in the code that the standard ordering will be `-latest_revision_created_at`, instead of just a getattr fallback.

Let me know if this is acceptable, then I'll create a PR for it.

**Comment by gasman** [comment]
Hi @NickdeDycker - please see the discussion on #882. The solution proposed there is similar to what you propose, but a bit more involved, as it's changing the database-level ordering too - rather than just making it a display preference in the admin listing - so that the chosen ordering is automatically used on the front-end too.

**Comment by thibaudcolas** [comment]
As of Wagtail 4.0 (RC), this seems to be working as expected, so I’ll close this now. I don’t think we made any changes to this recently so I won’t mark it as fixed in any particular release.

Screen recording of enabling manual sort order, changing the order, switching back to the non-manual ordering, and then again in manual sort order:

![sort-order](https://user-images.githubusercontent.com/877585/185086138-0a07a606-f136-4d41-b41a-3f0f99cba94d.gif)

Please let me know if I’m not going through this correctly or there is a specific context needed (different browser?)
