### ISSUE TITLE
Add cache keys to admin static files

### ISSUE THREAD

**Issue by MikeOverkamp** [wagtail/wagtail#4966]
### Issue Summary

Wagtail admin static files do not have cache keys / hashes in their file names, which causes caching problems for some users when upgrading Wagtail. 

### Steps to Reproduce

Obviously this cannot be reproduced on a fresh Wagtail installation, as caching is no issue there. However in existing sites, some admin functionality may break because old static files are served from cache. An example is that search and adding links seem broken to one of our clients.

**Comment by gasman** [comment]
Hi @MikeOverkamp,
Thanks for the report. This is covered by #3700 and the resulting PR #4745 - the template for new projects created since Wagtail 2.3 now enables `ManifestStaticFilesStorage` in production, and there's [a note recommending this in the deployment docs](https://docs.wagtail.io/en/stable/advanced_topics/deploying.html#static-files). Unfortunately there's probably no good way for Wagtail to 'push' a fix to older sites without interfering with their existing deployment mechanisms or creating maintainability issues.
