### ISSUE TITLE
{{ site_name }} is returning host name instead of site name

### ISSUE THREAD

**Issue by DanAtShenTech** [wagtail/wagtail#4970]
In [customizing the Wagtail login page](https://docs.wagtail.io/en/v2.4/advanced_topics/customisation/admin_templates.html?highlight=site_name%20#specifying-a-site-or-page-in-the-branding), I set up the following using {{ site_name }} as documented:

```
{% extends "wagtailadmin/login.html" %}
{% block branding_login %}Sign in to {{ site_name }}'s CMS{% endblock %}
```
I expected (and wanted) to see the site name on the login page, but instead it renders the host name.  Is this how it is supposed to behave?

### Technical details

* Python version: 3.6
* Django version: 2.1.4
* Wagtail version: 2.4
* Browser version: Chrome 71

**Comment by allcaps** [comment]
Digging a bit:

Wagtail subclasses the Django LoginView.
The django.contrib.auth.views.LoginView#get_context_data uses the get_current_site method from django.contrib.sites.shortcuts this is based on the Django sites framework.

We don't need the Django Site we need a Wagtail site. Something like:
wagtail.core.sites.get_site_for_hostname or wagtail.core.models.Page#get_site

**Comment by DanAtShenTech** [comment]
Thank you.  I won't have time to do anything on this for at least several months so am hopeful someone else can pick up on this.

**Comment by edbrown** [comment]
Had a crack at this, check the PR here: #4987

**Comment by andruwwwka** [comment]
I fix it for non-admin login view and edit test for this. Please check Pull Request #4988

**Comment by gasman** [comment]
I don't think this is a bug. The documentation for [`site_name` and the related template variables](https://docs.wagtail.io/en/v2.4/advanced_topics/customisation/admin_templates.html#specifying-a-site-or-page-in-the-branding) indicates that these are only available on the admin dashboard page - in particular, their values are defined in terms of the logged-in user's permissions, which doesn't make sense for the login page.

At the moment, it's a deliberate design principle of Wagtail that there is a single 'global' instance of the admin, which provides access to the full page tree (or whatever subset of it the current user has permission over) regardless of the hostname the user is accessing it through. This has a number of benefits over conceptually giving each subsite its 'own' admin:

* it allows suitably high-level users to perform administration tasks across the whole set of sites in a single login session, instead of having to log in individually to each site
* it allows the admin to exist on a hostname that's distinct from all of the hosted sites (e.g. `admin.example.com`), which might be appropriate if the admin interface needs to be locked down to a local network, for example
* more abstractly, the choice of whether or not a particular bit of content belongs on its own domain is fairly arbitrary, and it feels wrong for access control logic to be tied to that decision. (For example, if a university hosted their site on Wagtail, and wanted the physics department to be able to edit their own subsite, then whatever featureset Wagtail might offer for achieving that compartmentalisation shouldn't be conditional on the subsite existing at `physics.exampleville.edu` rather than `www.exampleville.edu/departments/physics`.)

For this reason, the idea of "logging into the admin for subsite X" doesn't really fit with the way Wagtail currently works. In the case of the very similar message on the dashboard, we _can_ identify the special case where the user's permissions are confined to a particular subsite and adjust the message accordingly, but that's not the case for the pre-login message. For certain setups, varying the message according to the domain being accessed is _close enough_ to the truth that it's a useful prompt to editors, and for those setups, it would be fine to implement that using something like:

    {% block branding_login %}
        {% if request.site and request.site.site_name %}
            Log in to {{ request.site.site_name }}
        {% else %}
            Log in to Wagtail
        {% endif %}
    {% endblock %}

However, I don't think this is something that Wagtail itself should provide formal support for, as it effectively means we're faking a concept of "logging into subsite X" that we can't make work consistently.

**Comment by allcaps** [comment]
@gasman Thank you for the thorough explanation and example. 

I'm fine that Wagtail doesn't want to make assumptions about multitenant systems.

There is still a small issue: Wagtail uses Django's `auth_views.LoginView`. This Django view provides context containing `site` and `site_name`. But the values are looked-up in the Django way. They fall back to the domain name. The default login template doesn't use these context variables.

I'm not surprised that integrators assume that `site` and `site_name` context is the current Wagtail site and available for convenience. They only get the current domain name. That is not the expected behaviour.

Should the `site` and `site_name` variables be removed from the login view context? Or are these redundant context variables something we can live with? 

I do understand the desire to display the current site name on a login page. The user is about to submit credentials and needs to know he is in the right place. Multitenant or single site setup, this need stays the same.

The fact that the view provides misleading context is a bug imho.
