### ISSUE TITLE
Best way to redirect the homepage to another page

### ISSUE THREAD

**Issue by commadelimited** [wagtail/wagtail#4977]
### Issue Summary

Eventbrite is using Wagtail as a headless CMS. We're going to be creating page models for a number of different areas of the site, and retrieving data via the API. This means that we don't want the homepage `/`.

We'd like to intercept any attempt at accessing the default Wagtail homepage and redirect it to the main Eventbrite homepage. After some digging it appears that all of this is handled by the guts of Wagtail and we couldn't determine how to override this.

Is there any way for us to manage this on our own? Our fallback would be to do a redirect at our load balancer.

**Comment by zerolab** [comment]
Hi @commadelimited,

You can accomplish this in several ways:

1. do the redirect at the server level (or load balancer)
2. Use the [before_serve_page hook](https://docs.wagtail.io/en/v2.4/reference/hooks.html?#before-serve-page) if you want this to happen for more than just the homepage.
3. Override the serve method for your homepage model - https://docs.wagtail.io/en/v2.4/reference/pages/model_recipes.html#overriding-the-serve-method

I would probably do this at the server level as you skip reaching the application and is scalable.

--- 
A more general note: #4276 is somewhat related to this in that there is currently no way to have Wagtail be purely headless because of `wagtail_serve`

**Comment by tomdyson** [comment]
You could also manage this with standard Django URL routing, e.g. with a RedirectView for `/` in your `urls.py`:

https://docs.djangoproject.com/en/2.1/ref/class-based-views/base/#redirectview

**Comment by commadelimited** [comment]
@zerolab the `before_serve_page hook` sounds perfect actually. We don't want to allow any public facing pages generated by Wagtail to be visible. We'll only be using the admin, and API drive pages in other areas around our site. Thanks!

@tomdyson that's good to know as well, thank you!

**Comment by commadelimited** [comment]
These are all great suggestions so I'm going to close this issue now. Thank you both for your time, and assistance.
