### ISSUE TITLE
`runtests.py` should use a default database if no database is configured

### ISSUE THREAD

**Issue by WoLpH** [wagtail/wagtail#4991]
I just created a pull request for a different issue and dutifully ran `python runtests.py` only to see it succeed and see the consecutive travis and other CI tests fail.

After a bit of research it appears that it's mostly failing because it's skipping 99% of the tests because no database is configured. When looking at the `tox.ini` file I noticed the `sqlite: DATABASE_NAME=wagtail.db` line which "fixed" the issue.

If no database is configured however, I think `runtests.py` should default to that one (or some other database), but at least some indication should be shown that most tests are not being executed. It would have saved me some time.

**Comment by gasman** [comment]
Hi @WoLpH - thanks for the report.
The behaviour you're reporting sounds very unusual, and I suspect there's something subtle going on with your setup - I'd be keen to see the console output, and any details of your environment (are you running under Vagrant, Docker, some other VM...?) that might help us to replicate this.

I routinely use the `./runtests.py` command in its default configuration (via [vagrant-wagtail-develop](https://github.com/wagtail/vagrant-wagtail-develop)) with no issues. Omitting the database name under sqlite is valid as per https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-TEST_NAME - in this case it defaults to an in-memory database rather than an on-disk one. The `DATABASE_NAME` line was added to tox.ini to fix an issue specific to our CI environment (see #4626 and https://github.com/travis-ci/travis-ci/issues/7873) and shouldn't be required on developer setups. In any case, I'd expect the test runner to abort immediately if it can't connect to the database, not silently skip over tests.

**Comment by WoLpH** [comment]
No Vagrant or Docker, just a regular Ubuntu 16.04 install running Python 3.6.6 in a decicated virtualenv created for this purpose alone.

Upon further inspection though... it seems I didn't see the `segmentation fault` (two computers running the same tmux screen and it was outside of my viewport... sigh). So this can be considered a duplicate of https://github.com/travis-ci/travis-ci/issues/7873 I guess.

Apparently the bug is not specific to the CI alone. Would it be useful to investigate further?

**Comment by gasman** [comment]
Thanks for the confirmation - will close this, then, as it's not specific to Wagtail.
