### ISSUE TITLE
Reduce contrast of rich text toolbar

### ISSUE THREAD

**Issue by tomdyson** [wagtail/wagtail#4997]
I propose that we reduce the contrast of the rich text toolbar, which - in my opinion - is heavy and distracting.

Current:

<img width="743" alt="screenshot 2019-01-17 15 54 34" src="https://user-images.githubusercontent.com/15543/51330825-39ce6e00-1a70-11e9-8d84-a42c30d458ae.png">

Proposed:

<img width="740" alt="screenshot 2019-01-17 15 50 19" src="https://user-images.githubusercontent.com/15543/51330832-405ce580-1a70-11e9-8c8b-c70afb2b2b2a.png">

Note that my proposed option (`background-color: #606060`) renders the dividers (e.g. between I and H2) barely visible. We could make these dividers darker or lighter, but I suggest removing them altogether.

Please use 👍 or 👎, or comment below, on the general suggestion to reduce the contrast.

**Comment by ollywillans** [comment]
I'd really love this to go white, but it seems like this is a good interim step to make it less heavy. Good idea. I'd be happy to lose the dividers and keep it simple.

**Comment by bentuckwell** [comment]
I like the suggestion of removing the divider lines, they feel unnecessary and add noise. The colour change takes a little bit of weight out of it but it's still pretty dominant. Be good to go white.

**Comment by chosak** [comment]
Considering accessibility, the [WebAIM Color Contrast Checker](https://webaim.org/resources/contrastchecker/) reports that both #606060 and #707070 (the highlighted background) meet the WCAG AA standard for "Graphical Objects and User Interface Components" with contrast ratios of 6.29 and 4.95, respectively (the requirement is 3:1).

**Comment by allcaps** [comment]
I like high contrast. It is functional.

It seems that we loose contrast in the active state of the button.

Contrast depends on the context, sometimes giving other page elements a bit more weight balances things out. For example the reds look a bit flat. Especially since the darkening of the teal. Looking at just a black bar as example isn't really fair imho.

I like @ollywillans proposal to go black on white and keep maximum contrast.

**Comment by ollywillans** [comment]
At the moment, the #333 is pretty much the darkest colour on the whole interface and as such the toolbar leaps out creating an angry punctuation and interrupting the flow of the page. I'd prefer dark on white because it would most reduce this effect to the minimum, but if we are looking for a v.quick interim fix, Tom's is definitely an improvement and in my opinion retains more than enough contrast.

**Comment by nmorduch** [comment]
I think:
- I agree with @ollywillans that we should go to a light toolbar, which can have higher contrast without being so in-your-face
- There's no good reason not to meet AAA anywhere on this site. None of our branding is important enough not to meet AAA. It looks like #595959 is the lightest color that always meets AAA when paired with white.
- Grouping buttons is helpful for finding things quickly. There are ways to do it other than the lines in between, e.g. extra space in between. The lines in the existing design would also probably look better with more padding and with being a little easier to see so that they feel more intentional.
- The active state is less obvious than I would like.

I think that if we want to make an intermediate change, we can lighten the background such that  active buttons' background is #595959, and not make any major changes to the dividers in an intermediate version because I think that that is a change that could make a difference for users.

**Comment by nicklee** [comment]
Mockup showing how a white background could look:

![Rich text editor - white option](https://www.dropbox.com/s/a23o69hl8e21uv5/richtext-editor--white-bg.png?raw=1)

**Comment by thibaudcolas** [comment]
This feels like a really straightforward change dev-wise, and I think it would be nice to have this released at the same time as the new StreamFiled (#4942)  — how should we proceed to make a decision?

**Comment by tomdyson** [comment]
If you mean that dark on white would be a straightforward change, let's go ahead and do that.

**Comment by benenright** [comment]
Hi

@thibaudcolas and I have had a look at this, and agree the best approach is as follows:

- Invert the toolbar to be black on white and not full width as per Nick's mockup https://github.com/wagtail/wagtail/issues/4997#issuecomment-455484037

- Hide it until user has focused on the field. Ideally we will create a space for it above the field text so that it doesn't jarringly push the content down when it appears on focus

- We suggest removing the undo and redo functions at the far end of the toolbar as they are rarely used and un-intuitive icons

Ben

**Comment by thibaudcolas** [comment]
Contrast has been changed according to @benenright and @nicklee’s input in #5740. This will be released in Wagtail 2.9. I have created two new issues for Ben’s two related points: #5791, #5792.
