### ISSUE TITLE
Feature request: Import/Export data between environment (including images)

### ISSUE THREAD

**Issue by Benoss** [wagtail/wagtail#5010]
I am building a website using wagtail and I would really appreciate a way to import export data and have cross environment data import.

Let me explain.
We have a local environment for dev, 127.0.0.1 a staging environment for the non technical project members to test and approve design and a prod environment public facing.
All the release process is using CI CD and we can deploy code very fast to staging and prod.

Our main pain-point at the moment with wagtail is not being able to create some content on Staging and then send it to to prod. The copywriters are testing on Staging by creating the content with the images, the text in all mainly streamfields. One piece of content may have 20 images and a lot of text in 10 different kind of blocks.

At the moment it takes a lot of time to copy paste to prod.
I found this project not really maintained as it is not working with Wagtail 2.3 https://github.com/torchbox/wagtail-import-export but I don't think this can work with images.

Would be awesome to have a a way to export a Page with an optional option to zip all related images and then import them on another environment with the same model.
This would also be very useful for creating fixtures for automation testing.

Maybe using the API could be an option as well https://github.com/wagtail/wagtail/issues/4667 but this is not on the roadmap I think.

I would be happy to work on this but this is rather large and a bit of solutioning needs to be done before (API vs ZIP for example)

**Comment by nealtodd** [comment]
Hi Benoit,

The [wagtail-import-export](https://github.com/torchbox/wagtail-import-export) hasn't been actively maintained recently because we haven't been using it of late so resources have gone into other things.

There is an [open issue](https://github.com/torchbox/wagtail-import-export/issues/5) for getting it working again with Wagtail 2.3. Hopefully that shouldn't be a big fix.

It would certainly be nice if wagtail-import-export handled images (and documents) as well. We developed it for a specific client use-case where image copying wasn't required and open-sourced it as-is because, as you've identified, there's quite a lot to consider (including edge cases) for a full, robust solution.

If you do have time to submit some proposals on how image copying could work in wagtail-import-export they'd be very gratefully received, and we may be able to find resource to support development. 

Cheers, Neal

**Comment by chosak** [comment]
I wonder if some of the collector logic being created in #4702 could be useful for exporting images, documents, etc. that are referenced by pages. Implementing a complete page export would require the ability to know all objects being referenced by the page, and the [`collectors.py`](https://github.com/wagtail/wagtail/blob/b7d1ec24223f8ef61b8cf6b99f95e6759e7c39c4/wagtail/core/collectors.py) in that PR seems like it'd make that much easier.

**Comment by nealtodd** [comment]
Aside: v0.2 wagtail-import-export has just been released to [PyPI](https://pypi.org/project/wagtail-import-export/) so that it works on Wagtail 2.3 (albeit without related image support).

**Comment by BertrandBordage** [comment]
Indeed @chosak, that could benefit from the RichText & StreamField collectors.

**Comment by jacobtoppm** [comment]
I believe [wagtail-transfer](https://github.com/wagtail/wagtail-transfer) now solves this issue - it supports images and documents.
