### ISSUE TITLE
 "Install Wagtail in just 7 lines" doesn't works

### ISSUE THREAD

**Issue by gagarine** [wagtail/wagtail#5047]
I try to install wagtail following the instruction on the front page:

```
pip install wagtail
wagtail start mysite
cd mysite
pip install -r requirements.txt
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
```

Sadly it fail already on pip install wagtail:

```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python3.6/dist-packages/modelcluster'
Consider using the `--user` option or check the permissions.
```

I'm using a clean EC2 instance on AWS started from https://aws.amazon.com/cloud9/ with Python 3.6.7. I guess I should use a virtual environment.

The point is: if it can break so easily why showing those instruction? I just wanted to test wagtail and launched an VM in the cloud to try it, this give me a bad first impression.

**Comment by digitallyamar** [comment]
No, I was able to run the same commands and get Wagtail up and running with only those 7 commands. The only issue you are facing is that you need to run those commands with adequate permissions. In my case, I ran those commands with '**sudo**' permissions and they went through just fine. May be you could try the same?

**Comment by BenSturmfels** [comment]
I would recommend against installing with sudo, as this will install into a location normally reserved for operating system files - it's more difficult to clean up and risks breaking your system in ways that are hard to fix.

The smallest change that would work would be to replace `pip install` with `pip install --user` in both locations. While it's a less common approach, it makes for a nice quick demo.

**Comment by gasman** [comment]
I like the idea of using `pip install --user` - it's a good middle ground that avoids the two extremes of giving people advice that contradicts real-world best practices, versus "here's how to install Wagtail in 7 commands once you've read a whole load of documentation about Python virtualenvs" :-) And for people who _are_ already familiar with virtualenvs, it should hopefully be self-explanatory enough that they should be able to confidently adapt the instructions accordingly. Thanks @BenSturmfels!

Any objections to this approach? I'll go ahead and update the page if not.

**Comment by gagarine** [comment]
Why not adding virtual env directly? It doesn't matter if it's 7 or 10
commands. What matters is the commands works and that I can try something I
don't understand without risk for my own machine (so sudo is certainly to
avoid).

**Comment by gasman** [comment]
@gagarine That's definitely something we can consider, if we can come up with a 3-or-so line snippet for setting up a virtualenv that reliably works across all machines irrespective of what is or isn't pre-installed - or, failing that, is self-explanatory enough that a user can adapt them to their setup without in-depth knowledge.

(For starters, that would probably imply using Python 3's [venv](https://docs.python.org/3/library/venv.html) rather than [virtualenv](https://virtualenv.pypa.io/en/latest/installation/) - the latter just has too many system-specific variations.)

These instructions will always have to assume _some_ kind of baseline starting point, both in knowledge and what's pre-installed on the system (even if that's just "knowing how to open and use the command line"). Reducing that baseline is a worthwhile goal, but that rapidly gets harder the less we assume, especially if you're aiming to make it a 'mechanical' process that someone can follow without understanding what's going on.

**Comment by BenSturmfels** [comment]
If ``venv`` is ommitted from the 7 lines, then it may be worth making mention of it on the [Your First Wagtail Site](http://docs.wagtail.io/en/latest/getting_started/tutorial.html) page.

Worth noting that the 7 lines are on the home page and also duplicated on the Developers page.

**Comment by gagarine** [comment]
I come to realize venv and package management is really the place where
python is hard for new user. Not because those concept are particularly
hard but because most python projects assume you already know them. In top
of that their is a lot of confusion between different tools (venv,
virtualenv,...). So nobody really tell you "this is the way to go".

For beginners I think it's absolutely necessary to include those kind of
things. To do that we certainly have to limit the beginner introduction to
python 3. Limiting is nice for beginners, as their is already so many
things you have to understand.

**Comment by tomdyson** [comment]
Thanks very much for the feedback @gagarine. We discussed some options in the last core team meeting and agreed on this:

![image](https://user-images.githubusercontent.com/15543/54999046-5c788800-4fc7-11e9-9b5e-6f85e75b174e.png)

the link goes to https://docs.python.org/3/tutorial/venv.html. Do you think this gives the right level of help to beginners?

**Comment by gagarine** [comment]
@tomdyson yeah that good!

**Comment by nmorduch** [comment]
I've updated the wagtail.io homepage, as well as the documentation (in #5210), with thanks to @tomdyson. The instructions on the wagtail.io homepage note that you need a virtual environment without providing a link or instructions (because putting a link into the plaintext code block isn't trivial), but if you click through to the install guide, it has full instructions including venv.

I think that we should probably change that "Install guide" link to go directly to the docs (probably the [Getting Started](http://docs.wagtail.io/en/latest/getting_started/index.html) page) rather than to the Developers page.

**Comment by gasman** [comment]
> I think that we should probably change that "Install guide" link to go directly to the docs (probably the Getting Started page) rather than to the Developers page.

👍 . We should make sure that both the homepage and Developers page point to the `/stable/` version of the docs rather than `/latest/` too.

**Comment by nmorduch** [comment]
Submitted for moderation the update to the homepage link. (The Developers page is locked.)

**Comment by gasman** [comment]
Sorry for the delay in approving! Links on homepage and developer page are now updated. (I've linked to the tutorial rather than the 'getting started' index page, as the tutorial is the one with the detailed instructions on virtualenvs - we ought to do something about that duplication really...)
