### ISSUE TITLE
LTS Duration

### ISSUE THREAD

**Issue by SemVerTsar** [wagtail/wagtail#5049]
Hi folks,

I'm not quite sure what to tag this as, but I believe a discussion should be had regarding the length of the LTS releases of wagtail. At present the LTS release of wagtail [2.3](https://docs.wagtail.io/en/v2.4/releases/upgrading.html?highlight=LTS) is expected to have a life of 7 months. I think it would be valuable to bring the LTS support into line with the [Django LTS duration](https://www.djangoproject.com/download/#supported-versions) of typically 3 years. For reference [this](https://en.wikipedia.org/wiki/Long-term_support) is a quick breakdown of life cycles of various LTS'.

This would provide the community with the ability to develop a wagtail project over a much longer period without needing to perform core wagtail updates. What do you think @gasman?

Cheers,
Philip

**Comment by loicteixeira** [comment]
It all depends on how you measure length because just like Django, every 4th Wagtail release is an LTS. So in a way, Wagtail is on the same schedule.

But obviously you're just talking about length of time and the reason why it differs comes down to two main differences:

- Wagtail has a release cycle of 2 months while Django's is 8 months.
- Django LTS versions are still being supported for a little while after a new LTS has been released, while Wagtail ones lose that status as soon as a new LTS is released.

Unfortunately I don't think changing Wagtail release cycle to 8 months would be an option, neither would it be to keep LTS support for 18 versions (so it last 3 years).

Longer release cycle and/or LTS support is definitely something which would be beneficial for the community but I'm not sure the Wagtail core team has the resources to do so.

**Comment by gasman** [comment]
As @loicteixeira says, Wagtail is an outlier here because we make new feature releases much more frequently than other projects. We think this approach serves users better, as it means there's a shorter turnaround for features to make it into a release and less work involved in upgrading to the next point release - however, it does mean that it would be a disproportionately large amount of work to keep supporting old releases for extended periods.

Extending the LTS period for individual releases might be possible if we receive sponsorship for it - this was the case for the 1.13 release, so we were able to extend the support period by 6 months.
