### ISSUE TITLE
proposal cli

### ISSUE THREAD

**Issue by ah8ad3** [wagtail/wagtail#5053]
Hi 
my question is why you start a project with youre wagtail cli

but for migration and run you use django staff
    python manage.py migrate
    python manage.py createsuperuser
    python manage.py runserver

i propose to add this to you're cli

**Comment by gasman** [comment]
Hi @ah8ad3 - thanks for the suggestion.

The `wagtail start` command is necessary because there's no way to 'insert' Wagtail-specific behaviour into the `django-admin` command before the project has been created. Once the project exists, the `manage.py` script can do everything we need.

I think it's a good thing to stick with familiar Django conventions such as `manage.py` wherever possible, so that it's clear to developers that their existing knowledge and workflows can still be used on Wagtail projects - I believe that's more valuable than introducing new commands just for aesthetic reasons.
