### ISSUE TITLE
Template fragment caching potentially harmful

### ISSUE THREAD

**Issue by harrislapiroff** [wagtail/wagtail#5074]
### Issue Summary

Django provides optional [template fragment caching](https://docs.djangoproject.com/en/2.1/topics/cache/#template-fragment-caching) wherein a portion of a template is cached when it is first rendered and that cache is reused to render that portion of the page until the cache expires or is invalidated.

Wagtail provides two ways of viewing pages that have unpublished content: "Preview" and "View Draft."

Used in conjunction, these features can create scenarios in which live data may be cached and then rendered in preview OR in which draft data may be cached and rendered on the live site. The former is annoying, the latter is a potential vulnerability that could inadvertently leak unpublished information 😱 

Since this behavior exists _because_ all the parts are behaving as designed, it's not 100% clear to me what the solution should be. I can imagine a few possible solutions off the top of my head:

1. Add a note to the documentation somewhere cautioning against the use of template fragment caching for this reason
2. Somehow add Wagtail-specific behavior to the Django `{% cache %}` tag that causes it to no-op in draft and preview modes (may be possible through middleware or the cache API? not sure)
3. Create a Wagtail-specific template fragment caching system that respects draft and preview modes

### Steps to Reproduce

Start with a Wagtail project with the following files:

`models.py`

```python
from django.db import models

from wagtail.core.models import Page
from wagtail.admin.edit_handlers import FieldPanel


class HomePage(Page):
    a_charfield = models.CharField(max_length=255)
    
    content_panels = Page.content_panels + [
        FieldPanel('a_charfield')
    ]
```

`templates/home/home_page.html`

```html+django
{% load cache %}

{% cache 3600 homepage_charfield %}
  {{ self.a_charfield }}
{% endcache %}
```

(Generate and run all migrations, create necessary admin user, etc.)

From the Wagtail admin, edit and publish a new Home Page:

![screen shot 2019-02-12 at 09 52 22](https://user-images.githubusercontent.com/296631/52644139-45188c00-2eac-11e9-8d14-3c9e8e6255f4.png)

DO NOT visit this page. Edit the page again with new values:

![screen shot 2019-02-12 at 09 56 09](https://user-images.githubusercontent.com/296631/52644374-b48e7b80-2eac-11e9-8550-511154ae0a33.png)

Do not save, but click "Preview." You'll see a previewed page that says "Privileged Information." Now, load up the live page. Observe that it _also_ renders "Privileged Information" even though that is unsaved content that an editor was merely testing.

![screen shot 2019-02-12 at 09 57 51](https://user-images.githubusercontent.com/296631/52644821-907f6a00-2ead-11e9-8111-dd088b320d32.png)

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

### Technical details

Tested on:

* Python version: Python 3.7.2
* Django version: Django 2.1.7
* Wagtail version: Wagtail 2.4

**Comment by chosak** [comment]
Nice catch, @harrislapiroff. This is a tricky one.

My first thought was that Wagtail could provide an alternate `{% cache %}` tag that checks [`request.is_preview`](https://github.com/wagtail/wagtail/blob/dbb7ec77b30a7bd55201e069603b1ae3e6aa3b90/wagtail/core/models.py#L712) and skips the caching behavior if the page is being previewed. I prototyped what seemed like a reasonable solution [here](https://gist.github.com/chosak/c957a2bacb7dbc2e725423ef07a46606), and it works for the test case you provide... but might not be ideal due to something interesting/surprising about how previews work under the hood:

Wagtail uses a [`dummy_request`](https://github.com/wagtail/wagtail/blob/dbb7ec77b30a7bd55201e069603b1ae3e6aa3b90/wagtail/core/models.py#L1195) method used to generate the dummy request used for previews. As part of this method, it [applies the full middleware chain](https://github.com/wagtail/wagtail/blob/dbb7ec77b30a7bd55201e069603b1ae3e6aa3b90/wagtail/core/models.py#L1269) on the request, presumably to make the dummy request work as closely as possible to a real one. The `handler._middleware_chain` method that gets called there invokes [`django.core.handlers.base.BaseHandler._get_response`](https://github.com/django/django/blob/543fc97407a932613d283c1e0bb47616cf8782e3/django/core/handlers/base.py#L85), which not only applies all middleware `process_response` methods but also [renders the response](https://github.com/django/django/blob/543fc97407a932613d283c1e0bb47616cf8782e3/django/core/handlers/base.py#L143).

This means that Wagtail previews actually render the page **twice** -- once (with live data) as part of the middleware chain used to generate the dummy response, and then again (with draft data) to render the preview.

(Getting even more complicated, the URL used for the request is based on the [best guess](https://github.com/wagtail/wagtail/blob/dbb7ec77b30a7bd55201e069603b1ae3e6aa3b90/wagtail/core/models.py#L1206) for where the page is going to live (or even [the root URL](https://github.com/wagtail/wagtail/blob/dbb7ec77b30a7bd55201e069603b1ae3e6aa3b90/wagtail/core/models.py#L1223), I think if the page has never been published).)

This means that the live cache data for a page gets set not necessarily when the page is viewed live for the first time, but also potentially when the page is previewed. This isn't a problem as long as cache keys are tied to specific pages (because caching the live data is what you'd want to do), but it is unexpected that it'd happen on page preview.

**Comment by kaedroho** [comment]
This issue also effect any calls to the cache using custom tags, model methods and middleware. So adding a new ``{% cache %}`` would only solve part of problem.

Also, I don't think that many developers would test using the preview, so they probably wouldn't think that they need to be using a separate ``{% cache %}`` tag for Wagtail pages.

I think this could be solved by mocking out the cache backends while previews are being rendered. This should fix the issue for the other cases and also work with the Django's existing ``{% cache %}`` tag.

```python
# wagtail/admin/views/pages.py

from wagtail.utils.cache import disable_caches

def view_draft(request, page_id):
    page = get_object_or_404(Page, id=page_id).get_latest_revision_as_page()
    perms = page.permissions_for_user(request.user)
    if not (perms.can_publish() or perms.can_edit()):
        raise PermissionDenied

    with disable_caches():
        return page.serve_preview(page.dummy_request(request), page.default_preview_mode)
```

An implementation of ``disable_caches`` might look like: https://gist.github.com/kaedroho/cefd778ff5ea85166ded1ef817c62c6d (not tested though)

**Comment by jorenham** [comment]
Any progress?

**Comment by solarissmoke** [comment]
Just leaving a note here to say that having attempted it, I don't think the approach suggested by @kaedroho is viable. 

The reason is that [Python caches module imports](https://docs.python.org/3/reference/import.html#the-module-cache), so monkey-patching `django.core.cache.caches` in this way will only affect code that attempts to import this module _after_ we modify it. Any code that has already imported the module will use the previously referenced module (clearing the cache will not help with this).

The result of this basically is that you can't monkey-patch the cache inside a request context like this.

I tested this with the following code:

```python
class DummyCacheHandler:

    def __getitem__(self, alias):
        return DummyCache(None, {})


@contextmanager
def disable_caches():
    original_caches = django.core.cache.caches
    django.core.cache.caches = DummyCacheHandler()

    try:
        yield
    finally:
        django.core.cache.caches = original_caches


class Page(BasePage):
    """
    Page model that overrides the preview() method to ensure that caches are
    bypassed when previewing.
    """

    def make_preview_request(self, *args, **kwargs):
        with disable_caches():
            response = super().make_preview_request(*args,**kwargs)
        return response

    class Meta:
        abstract = True 
```

which doesn't work as far as template fragment caching goes. By the time `make_preview_request`, `django.templatetags.cache` has already been loaded, and the `caches` import used there references the module before we changed it.

**Comment by solarissmoke** [comment]
For anyone who wants to implement a workaround until a solution is found in core, I've done this:

```python
import django
from django.templatetags.cache import CacheNode


class SmartCacheNode(CacheNode):
    """
    A subclass of django.templatetags.cache.CacheNode for Django's default cache tag
    that bypasses the cache entirely if there is a request in the context and
    request.is_preview is True.
    """
    def render(self, context):
        request = context.get('request', None)
        # If request.is_preview, then skip caching entirely
        if request and getattr(request, 'is_preview', False):
            return self.nodelist.render(context)

        return super().render(context)


# Monkey-patch Django's cache node with out own.
django.templatetags.cache.CacheNode = SmartCacheNode
```

This (a) doesn't deal with caching outside of templates and (b) will not work for template fragments that don't have `request` in the context - so it only partially mitigates the security risk posed by this bug.

**Comment by jorenham** [comment]
Similarly to @solarissmoke 's solution, this is the modified version of the jinja2 cache tag from [django-jinja](https://github.com/niwinz/django-jinja) .

```python
from django.core.cache import cache
from django.utils.encoding import force_text
from django_jinja.builtins.extensions import make_template_fragment_key
from jinja2 import TemplateSyntaxError
from jinja2 import nodes
from jinja2.ext import Extension


class CacheExtension(Extension):
    tags = {'cache'}

    def parse(self, parser):
        lineno = next(parser.stream).lineno

        expire_time = parser.parse_expression()
        fragment_name = parser.parse_expression()
        vary_on = []

        while not parser.stream.current.test('block_end'):
            vary_on.append(parser.parse_expression())

        body = parser.parse_statements(['name:endcache'], drop_needle=True)

        return nodes.CallBlock(
            self.call_method('_cache_support',
                             [expire_time, fragment_name,
                              nodes.List(vary_on), nodes.Const(lineno),
                              nodes.ContextReference()]),
            [], [], body).set_lineno(lineno)

    def _cache_support(self, expire_time, fragm_name, vary_on, lineno, context, caller):
        try:
            expire_time = int(expire_time)
        except (ValueError, TypeError):
            raise TemplateSyntaxError('"%s" tag got a non-integer timeout '
                'value: %r' % (list(self.tags)[0], expire_time), lineno)

        cache_key = make_template_fragment_key(fragm_name, vary_on)

        request = context.get('request', None)
        # If request.is_preview, then skip caching entirely
        if request and getattr(request, 'is_preview', False):
            return caller()

        value = cache.get(cache_key)
        if value is None:
            value = caller()
            cache.set(cache_key, force_text(value), expire_time)
        else:
            value = force_text(value)

        return value

```

**Comment by lb-** [comment]
This will be in the 5.2 release.
