### ISSUE TITLE
I can't upload image: 404 error

### ISSUE THREAD

**Issue by mowshon** [wagtail/wagtail#5075]
### Issue Summary
I can't upload images. I got 404 error on wagtail fresh install.

### Steps to Reproduce
1. I try to upload image: http://site.com/admin/images/multiple/add/
![first](http://dl4.joxi.net/drive/2019/02/12/0008/1467/529851/51/1d50dd7430.jpg)
![second](http://joxi.net/nAyeqgzSgX0vGA.jpg)

### Technical details

* Python version: 3.6
* Django version: 2.1.7
* Wagtail version: 2.4
* Browser version: whatsmybrowser.org/b/CATAARZ

**Comment by gasman** [comment]
Hi @mowshon,
Judging from the logo in your screenshot, it looks like you have some old CSS / JS from an outdated version of Wagtail cached in your browser. Please can you try clearing your browser cache, and then try the upload again?

**Comment by mowshon** [comment]
@gasman I deleted the entire cache from the browser. Problem still exists. I tried to upload new avatar for the admin and got this error:
![error](http://joxi.net/krD7OopCK0YOjA.jpg)

**Comment by gasman** [comment]
This looks like an issue specific to your hosting setup. Are you able to test this on your local machine, using `./manage.py runserver`?

Also, do any of the following work:
* submitting a form that doesn't require an upload, e.g. `/admin/account/notification_preferences/`
* uploading a document through the Documents area
* uploading a small image (<500K)?

**Comment by mowshon** [comment]
@gasman I tried to install a fresh wagtail on my local machine, and it works. Apparently the problem is hosting. I cannot upload images and documents, but I can create new records through POST and edit the profile. Do I need any additional libraries except those that are installed through the pip?

**Comment by gasman** [comment]
Unfortunately we can't help with troubleshooting hosting issues here - you might have more success on StackOverflow or another of our [support channels](https://docs.wagtail.io/en/stable/support.html).

The Pillow image library does require some system-wide dependencies, libjpeg and zlib - see https://pillow.readthedocs.io/en/latest/installation.html#external-libraries . However, if documents are failing too, it doesn't sound like that's the immediate problem. File permissions on the 'media' folder would be one thing to check, but in any case it's very strange that this is throwing a 404 Not Found rather than a more descriptive error.
