### ISSUE TITLE
Streamfield saves data differently based on "Save as Draft" or "Publish"

### ISSUE THREAD

**Issue by bmoe872** [wagtail/wagtail#5085]
### Issue Summary

When writing a custom validator for the StreamField, I discovered the stream_data gets saved out differently based on "Save as Draft" or "Publish" 

Clicking "Save as Draft" saves out the stream_data as a list of tuples.

Clicking "Publish" saves out the stream_data as a list of dicts. 

### Steps to Reproduce

1. With a working project, add a custom validator to the streamfield that iterates over the stream_data. Maybe like this:
```
def validate_streamfield(value):
    items = [data[0] for data in value.stream_data]
```

Then add `validate_streamfield` to the validators on your streamfield like so:
```
body = StreamField([...], validators=[validate_streamfield])
```

2. Now if you click "save as draft" in the CMS, the model should save no problem. However if you click "Publish" it will error out with a key error on '0'. 

### Technical details

* Python version: 3.6.7
* Django version: 2.1.3
* Wagtail version: 2.4.0
* Browser version: Chrome 71.0.3578.98 (Official Build) (64-bit)

### Workaround
I did make a workaround for this behavior, but it would seem to me like it should be saved out the same way in both instances. 

My workaround is just to check if its a list of tuples or a list of dicts, and then respond accordingly. e.g.

```
    if all(isinstance(data, tuple) for data in value.stream_data):
        items = [
            data[0] for data in value.stream_data
        ]
    elif all(isinstance(data, dict) for data in value.stream_data):
        items = [
            data['type'] for data in value.stream_data
        ]
```

**Comment by gasman** [comment]
Hi @bmoe872,
This is by design. `stream_data` is an internal property not intended for end-users to access - in retrospect it should really have been given a name with an leading underscore to clarify this - and the data format varies depending on whether we already have the fully evaluated data available (e.g. a `Page` instance for a `PageChooserBlock`), or whether we only have the raw data from the database representation (in which case the data for a `PageChooserBlock` will just be the page ID, and be converted to a `Page` instance when first accessed). End users should access the elements of `value` itself, rather than `value.stream_data`, e.g. `[data[0] for data in value]`.

See https://github.com/wagtail/wagtail/blob/087434f3480b09f730d8fc7e3a88ff7f5283df32/wagtail/core/blocks/stream_block.py#L357 and https://github.com/wagtail/wagtail/pull/2886#issuecomment-262634338 for further background.

**Comment by bmoe872** [comment]
ahhh I see - its right there in the code!

Thanks for the insight @gasman !!

**Comment by m-aciek** [comment]
@bmoe872 Thank you for sharing this. But did you keep the validator at the StreamField or moved it somewhere else?

**Comment by bmoe872** [comment]
Hi @m-aciek and sorry for such a late response! 

I did keep the validator in the StreamField, so it looked something like this:

```
body = Streamfield([ ... ], validators=[valdiate_streamfield_method])
```
