### ISSUE TITLE
Redundant try-except

### ISSUE THREAD

**Issue by patta42** [wagtail/wagtail#5122]
Hi all!

Just a minor issue, but I do not see any difference between the  code in the `try` and the `except` block.
https://github.com/wagtail/wagtail/blob/e0fc0da491bec154b34d1c196cf4c90fc5988f90/wagtail/admin/menu.py#L91-L95

**Comment by gasman** [comment]
Thanks @patta42 - well spotted! It looks like the `request` arg was erroneously added in this commit:

https://github.com/wagtail/wagtail/commit/648efe0e186ec5d91feb22007cfdc33fb39567d7#diff-475d6e4328cc589120d160e95756d7adR101

Any third-party code that relied on this fallback would have been broken since Wagtail 1.0, so it's clearly not being used by anything in the real world - I'd be happy to accept a PR to remove this.

**Comment by gasman** [comment]
Fixed in #5123
