### ISSUE TITLE
Rich text page links use admin display title instead of regular title

### ISSUE THREAD

**Issue by solarissmoke** [wagtail/wagtail#5131]
### Issue Summary

When inserting a link to a page from the rich text editor, the anchor text that is pre-populated (if you haven't selected some text to anchor) is generated from the admin page title (`Page.get_admin_display_title`). This is not expected behaviour, because this is not the public page title that is visible on the published page.

### Steps to Reproduce

1. Override `Page.get_admin_display_title` on a page model - for example to include some additional context about the page such as when it was created. This should only be visible when viewing pages in the admin.
2. In a rich text field, add a link to this page. The auto-populated anchor text will use the admin display title instead of just the `title` field value.

### Technical details

* Python version: 3.6
* Django version: 2.0
* Wagtail version: master

**Comment by chosak** [comment]
I've opened #5491 to address this, by using `page.title` instead of `page.get_admin_display_title`.

The one reservation I have about this change is that the fallback behavior for `get_admin_display_title` is to [show the _draft_ page title `page.draft_title`](https://github.com/wagtail/wagtail/blob/b818eeab5d14848bfc97cd8067d2590a7219b96a/wagtail/core/models.py#L628). Assuming that custom admin display titles are fairly rare, this might mean that editors are currently used to links showing the _draft_ page title in the rich text editor, as opposed to the _live_ one. Again, this might be fairly rare, but making this change will alter how things work now.

@gasman since you marked this as a "type:Bug" it seems like you agree that the current behavior isn't ideal. Wagtail could potentially show `page.draft_title` in the editor to maintain current behavior. What do you think?

**Comment by gasman** [comment]
Thanks @chosak! I think the use of the draft title is also an oversight, rather than behaviour worth preserving. I can see how the draft title might be the preferred alternative if an editor is updating a group of pages with the intention of publishing those changes all in one go, but in the more general case I think it's better to avoid information from draft edits 'leaking' onto other pages when the editor hasn't taken an explicit step to do that.

**Comment by chosak** [comment]
@gasman thanks; see my comment at https://github.com/wagtail/wagtail/pull/5491#issuecomment-519659524 -- are you suggesting changing the default behavior of `get_admin_display_title` to not use the draft title at all? That feels like a different issue than this one which is more constrained about behavior of link titles within rich text editors.

**Comment by gasman** [comment]
@chosak Sorry, I should have been more specific there... I think the use of the draft title **as the default link text for generated links in rich text** is an oversight. Displaying the draft title to editors within listings etc _is_ appropriate (and so no changes to `get_admin_display_title` are necessary), but that's where it should end - the draft title shouldn't find its way into other pages' content.

(This does mean that in this one specific case, where a title has been edited in draft, there'll be a slightly jarring effect where the editor sees one title in the listing, clicks on it, and ends up with a different title as the link text. I think that behaviour is justified, though.)

**Comment by gasman** [comment]
Fixed in #5491
