### ISSUE TITLE
instance.live set to True in "page_unpublished" signal handler

### ISSUE THREAD

**Issue by lorenzo-ange** [wagtail/wagtail#5166]
### Issue Summary

A page instance has the "live" property set to True in "page_unpublished" signal handler function.
This happens when a custom Page model instance is deleted.

### Steps to Reproduce

1. connect a handler function to "page_unpublished" signal with a custom Page model sender
2. from the wagtail admin delete a page of the custom Page model
3. if you debug the handler function you can see that "instance.live" is set to True instead of False

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

I suppose the problem is caused by the commit=False in this piece of wagtail code:

wagtail.core.signal_handlers.py, line: 20
```
def pre_delete_page_unpublish(sender, instance, **kwargs):
    # Make sure pages are unpublished before deleting
    if instance.live:
        # Don't bother to save, this page is just about to be deleted!
        instance.unpublish(commit=False)
```

commit=False won't save the model instance to db, but the "page_unpublished" signal is sent passing "instance=self.specific".
**self.specific will refresh instance data from DB, resetting the "live" property to True.**

wagtail.core.models.py, line: 700
```
page_unpublished.send(sender=self.specific_class, instance=self.specific)
```

Removing commit=False should resolve the issue.

**Comment by gasman** [comment]
Thanks for the report, @lorenzo-ange.
As mentioned at https://github.com/wagtail/wagtail/pull/5669#issuecomment-626613226 , removing the `commit=False` would make this fully logically correct, but would add a performance penalty since we need to make two database queries when deleting pages (one for unpublishing, then another for deletion). Can you give an example of a problem that the current implementation causes, so that we can understand the tradeoffs here and maybe find an alternative (such as setting `live=False` on the in-memory `specific` instance)?
