### ISSUE TITLE
Support twitter previews in Draftail embeds

### ISSUE THREAD

**Issue by fabienheureux** [wagtail/wagtail#5176]
### Issue Summary
Draftail's EmbedBlock have troubles displaying tweets' informations (thumb / title)
  
### Steps to Reproduce
1. Start a new project with `wagtail start myproject`
2. Add a RichTextField to an example model
3. Add a new content for this example model 
4. Click embed block in draftail toolbar
5. Add a tweet `https://twitter.com/libe/status/1110520362930974721?s=20` 

Expectations: get a sumary (title, description, thumbnail or any other relevant information) displaying in the textarea
Result: Nothing except the generic look of embeds in the editor. 
  
As discussed on slack with @thibaudcolas , this comes from here: https://github.com/wagtail/wagtail/blob/b1fab7084719ddbb88b9581567660930a6c082b4/client/src/components/Draftail/blocks/EmbedBlock.js#L13-L27  

Also, as said on slack, on good generic workaround to this case (and other future cases like this one) could be to display embed source in the preview. 

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details
* Python version: 3.7.2
* Django version: 2.1.7
* Wagtail version: 2.4

**Comment by fabienheureux** [comment]
For additionnal information, we can see here that the rendered json from oembed does not return title and thumbnail for twitter. 
http://oembed.frdnspnzr.de/

**Comment by thibaudcolas** [comment]
👌 as discussed, this is because currently the embed block expects embeds to have a `thumbnail` and `title` – those fields aren't always defined.

I think a good fix for this would be to introduce a new rendering of embeds for cases when no thumbnail is available; perhaps displaying a list of field values that seem relevant. We'd have to look at the oembed schema (https://oembed.com) as well as most common embeds to determine what those fields would be. The source URL of the embed would be the lowest common denominator, but we might be able to do more.

Relevant code: https://github.com/wagtail/wagtail/blob/b1fab7084719ddbb88b9581567660930a6c082b4/client/src/components/Draftail/blocks/EmbedBlock.js#L16-L27

**Comment by thibaudcolas** [comment]
Assigning this to @imansyed000

**Comment by imansyed000** [comment]
There are a few options here:
1) ![Screenshot 2019-08-02 at 09 36 34](https://user-images.githubusercontent.com/52247241/62357318-b9062980-b50a-11e9-9067-fdf8544723d3.png)
A html widget provided by twitter

2) ![Screenshot 2019-08-02 at 09 50 31](https://user-images.githubusercontent.com/52247241/62357527-2b770980-b50b-11e9-8de1-98acccabf325.png)
A profile picture thumbnail (good because can use this with existing MediaBlock)

3) ![Screenshot 2019-08-02 at 09 51 15](https://user-images.githubusercontent.com/52247241/62357558-3d58ac80-b50b-11e9-9f0e-1f56f42c3e5d.png)
A description (the same as the tweet itself)

I think the html widget is the nicest of the options but the thumbnail would be more consistent with the existing use of thumbnail with MediaBlock for other providers.

**Comment by thibaudcolas** [comment]
@imansyed000 if we can access some of these then great – I would recommend `thumbnail` so we stay close to the existing behavior.

**Comment by thibaudcolas** [comment]
If anyone wants to finish this off, the only thing missing for #5545 to be merged is tests. There is guidance on the PR on what to write tests for exactly.

**Comment by PaarthAgarwal** [comment]
> If anyone wants to finish this off, the only thing missing for #5545 to be merged is tests. There is guidance on the PR on what to write tests for exactly.

I'll try fixing it.

**Comment by thibaudcolas** [comment]
Done in #8167 :)
