### ISSUE TITLE
Set context_object_name when defining model?

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#5213]
When defining a Wagtail Page model, it would be nice to be able to set the `context_object_name`, e.g. as a `Meta:` field. This would allow the use of meaningful context object names without needing to define a view.

**Comment by gasman** [comment]
Thanks for the suggestion @brylie! To clarify, are you proposing something like:

    class EventPage(Page):
        start_date = models.DateField()
        end_date = models.DateField()

        class Meta:
            context_object_name = 'event'

so that you can refer to `{{ event.start_date }}` rather than `{{ page.start_date }}` in the template? If so, that sounds good to me. (I guess we'd set that variable in _addition_ to `page`, as it's quite likely that base templates will want to continue doing `<title>{{ page.title }}</title>`, for example.)

**Comment by brylie** [comment]
Yeah that is it exactly. Basically, I would like to have a meaningful object name in my code, so it is easier to understand and explain. Keeping `page` around is fine.
