### ISSUE TITLE
Django Management Command Name Conflict With Haystack

### ISSUE THREAD

**Issue by edmenendez** [wagtail/wagtail#5241]
The command update_index is also a management command in Django Haystack.

This causes problems with both the rebuild_index and update_index command in Haystack making it impossible to update the index in haystack using these commands.

Possible solutions are:

- Rename the command and add a wagtail namespace. This should probably be done via deprecation process so it won't fully work until it's renamed.
- Detect if the other command exists and instead use wagtail namespace. This keeps everything working like it does not except if you're using Haystack it will have a different name.

**Comment by chosak** [comment]
@edmenendez thanks for the bug report. This was previously submitted in #2447.

PR #5009 added `manage.py wagtail_update_index` as an alias for Wagtail's `update_index` command. This new command will be available in the [upcoming 2.5 release](https://docs.wagtail.io/en/latest/releases/2.5.html#other-features), which is currently available [as a release candidate](https://pypi.org/project/wagtail/2.5rc1/).

The documentation for this new command is [here](https://github.com/wagtail/wagtail/blob/61e1e4c2f961d854ad8dc679f58174eacdaf940a/docs/reference/management_commands.rst#wagtail_update_index), and suggests placing Haystack before `wagtail.search` in `settings.INSTALLED_APPS` so that its `update_index` takes precedence over Wagtail's.
