### ISSUE TITLE
prevent unsafe-inline CSP errors by putting all JS in their own file?

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#5247]
### Issue Summary

The wagtail 2.4 admin still loads some JS inline: 

```html
<!doctype html>
<html class="no-js" lang="en-gb">
<head>
    <meta charset="utf-8" />
    ...
    <link rel="shortcut icon" href="/static/wagtailadmin/images/favicon.ico" />
</head>
<body id="wagtail" class="page-explorer  ">
    ...
    <script>
        (function(document, window) {
            window.wagtailConfig = window.wagtailConfig || {};
            wagtailConfig.ADMIN_API = {
                PAGES: '/cms/api/v2beta/pages/',
                DOCUMENTS: '/cms/api/v2beta/documents/',
                IMAGES: '/cms/api/v2beta/images/',
```
which means that wagtail cannot be deployed on servers with a CSP that forbid `unsafe-inline` scripts (which is quite a sensible thing to do these days).

### Steps to Reproduce

1. add https://github.com/jsocol/django-csp to the project
2. make sure the script CSP does not include `unsafe-inline`
3. load the wagtail CMS admin view with the dev console open

Making sure that all js like this is in its own file and loaded from `src` should solve this.

**Comment by gasman** [comment]
Hi @Pomax,
It isn't possible to move this particular block to a static JS file, as it's defining configuration options that originate from Django and might vary between installations. (Indeed, the example you give is using a non-default setup - `/cms/` in URLs rather than `/admin/`.)

An alternative approach (which I've successfully used in https://github.com/gasman/wagtail-generic-chooser) would be to pass the relevant bits of config as `data-*` attributes on the HTML elements of the relevant widgets. Not sure how this fits with the React way of doing things though...

**Comment by gasman** [comment]
See also https://github.com/wagtail/rfcs/pull/33 which proposes a way to eliminate 'init' blocks from JS-based widgets, the other main culprit for inline `<script>` tags.

**Comment by thibaudcolas** [comment]
Yes, this particular bit could easily be serialised as JSON and as an HTML data attribute server-side, then de-serialised client-side. There is some performance cost to this over generating JS directly, but that should not be significant.

I think being able to remove `unsafe-inline` would take more work than moving JS into files though,

- There is code like this that's generated server-side, and will need a similar refactoring to JSON / attributes encoding to separate the dynamic parts in templates from what's static and can be loaded in a separate file.
- A lot of code relies on inline script being synchronous/blocking during the page load for its execution order, and might not work (might not have access to its dependencies) if extracted from a JS file that's loaded asynchronously. We wouldn't want to load JS files synchronously (is that even possible in modern browsers?) like we use inline scripts because of the performance cost.
- Finally, I wouldn't be surprised if there was code that dynamically generated `<script>` or `<style>` tags in our dependencies. For example Draftail does this to generate styles for list nesting of arbitrary depth.

Some of these refactorings could come as added benefits of a potential move to Webpack (#3804, #2797, ping @jonnyscholes). As an alternative solution, would it be realistic to use nonces or hashes of inline scripts/styles? I've never implemented that myself but I imagine this would be impossible for dynamic things, but might work for the ones that are static?

**Comment by jonnyscholes** [comment]
CSP isn't something I have a heap of experience with so I can't comment on a short term solution, however in my refactoring I'll definitely keep this in mind and do what I can to reduce the number of inline scripts.

**Comment by Pomax** [comment]
Note that you don't need to move the code into a static file: it's just as easily turned into a .js file with wagtail/django templates and simply served on request with the right values templated it by hitting something like `src="/apiv2beta/admin_base.js"`.

**Comment by thibaudcolas** [comment]
@Pomax I'd like us to move away from server-generated JS as much as possible, because it makes it harder to use JS tooling on those sources (static analysis, & unit tests running in Node). There are lots of places where we do this in inline scripts, and I think it would be a good rule to never do it in scripts that have their own file.

For the JSON, I was just thinking of having this as a serialisation format, but the data would be passed through an HTML data attribute – there's indeed no need to go as far as refactoring code to use more AJAX-y data loading.

@jonnyscholes has started refactoring a lot of the legacy JS code to use newer patterns over at #5252, a good extension of this current backlog would be to do the same for inline scripts.

**Comment by Pomax** [comment]
HTML data attributes make sense, we do that for "bits of the page only" React apps so that the data's available up front as well, although we took it one step further, as JS can already read from `element.dataset` directly. So we end up with bootstrapping elements like:
```
<div class="profile-card"
  data-name="...."
  data-profile-url="..."
  data-thumbnail-url="..."
  data-etc
>some innerhtml that can be preserved</div>
```
Rather than using JSON as embedded transport format (e.g. `<div data-conf="{...to be parsed json...}"></div>`). We had embedded JSON for a while, but then you made it impossible to make your HTML checker verify that all the data you need gets generated into your page, having to test JS while testing HTML (which is effectively the same problem as "testing JS with Django templating in it" I suppose), plus it means a delay caused by JSON.parse, which is always a tricky customer because that function can (and will!) throw on even the simplest typo, breaking your site.

**Comment by thibaudcolas** [comment]
Ah that's a good point, I hadn't though of the "data inspection" aspect of it in testing. And I imagine it might not be that much work to make a serialiser from a flat Python data structure to the corresponding data attributes. Thanks for sharing!

**Comment by lb-** [comment]
I had not seen this issue before but we are investigating a lightweight framework and heading in the direction of Stimulus JS. 

Stimulus provides a convention and consistent approach to preparing data attributes as the init values for a frontend component. 
https://stimulus.hotwired.dev/reference/values#types

Specifically it has one for the JSON approach described above. 

Head over to the discussion thread and related research doc and add to the feedback there 
- https://github.com/wagtail/wagtail/discussions/7689#discussioncomment-2037913

**Comment by Pomax** [comment]
Perhaps a silly question, but if you're going down the MCV road, why not something like Vue instead and have the benefit of a huge community that already solved every conceivable problem you might run into several times over?

**Comment by lb-** [comment]
Hey @Pomax thanks for the feedback - not a silly question at all. 

However - I encourage you to read the linked sub-thread on the comment above. The short version is that we are trying to solve for some constraints and goals and Vue does not suit for these. 

Have a read of the thread and the linked research and if you see how Vue can work please add some ideas and example code.

**Comment by Pomax** [comment]
I'll be honest: as much use as you're getting out of that discussion thread, for someone just looking in from the sidelines the fact that it's part of a huge book worth of discussion about every single thing tech-debt-ish instead of there being dedicated discussions for each aspect of the overhaul makes it pretty much untrackable.

**Comment by lb-** [comment]
@Pomax thanks for giving it a go - these things evolve slowly and yes in hindsight it's a bit confusing. We don't have a way to split sub-threads out. 

Here is a direct link to the investigation. 
https://github.com/lb-/bakerydemo/blob/ui-experiments/lightweight-frontend-framework-investigation-2022.md

Here is a direct link to the code. The header search is a good example of removal of a large amount of inline scripts tags and also setting up data on data attributes where needed. 
https://github.com/lb-/wagtail/pull/5/files

I will post here when the RFC is up - that will give a better chance to comment.

**Comment by lb-** [comment]
@Pomax  as discussed

RFC 78 created https://github.com/wagtail/rfcs/pull/78

**Comment by thibaudcolas** [comment]
Closing in favour of #1288, which covers more than just the JS and has been opened longer.
