### ISSUE TITLE
Feature Request: Automatic creation of multiple Streamfields when pasting formatted content

### ISSUE THREAD

**Issue by pvetch** [wagtail/wagtail#5321]
Content creation workflows often involve pasting of content from a formatted source document (such as a Google Doc) into Wagtail. In the context of Streamfield-enabled page model, the easiest / quickest way to achieve this is by pasting formatted content into a single Streamfield "paragraph block". This approach undermines the editorial flexibility of Streamfield by effectively perpetuating a monotlithic 'body text' field - but the only alternative is to manually split out the formatted content into multiple Streamfields, which is time consuming and unlikely to be something that is consistently done by editors.

If content is *not* split into multiple Streamfields, then the editor UX is not as strong as that provided by other tools (for example the Gutenberg editor in Wordpress)

It would be really good if it were possible to allow for formatted content to be pasted in a way that would automatically parse the content, create appropriate Streamfields at block level, and populate them with the pasted content.

There'd be a number of UX, UI and technical considerations here: a few initial ones: 

- Would this be something that would work only when creating new pages or could it work on existing ones - how would this work on a page where there were already Streamfields in place?
- How would a 'parser' map formatted content to custom Streamfield models?

**Comment by tomdyson** [comment]
> Would this be something that would work only when creating new pages or could it work on existing ones - how would this work on a page where there were already Streamfields in place?

Perhaps, rather than splitting content on paste, we should have a 'split' control within Draftail. This would allow editors to decide whether to split or not, as well as supporting 'monolithic' content on existing pages.

**Comment by kaedroho** [comment]
Making each paragraph its own streamfield block would significantly simplify and improve a number of other features as well. Including Diffing revisions, breaking up pages into segments for translation and also provide a stable identifier to use for comments on page content.

**Comment by harrislapiroff** [comment]
I want to offer my 2¢ as this is a feature I was just independently thinking about. I think a "split" control would not be as good UI-wise as splitting automatically (or at least giving the developer the option of making it split automatically).

I think a split button means introduces a foreign concept whose applications aren't immediately clear to content editors ("What does it mean for my article to be 'split?' Why would I want to do that?") that would reduce most of the gains of having such a feature. My goal for a feature like this would be to make smooth for a content editor to insert an image, heading, video, embedded tweet, etc. _without_ having to think about the structure of the streamfield. I imagine a feature like this behaving the same way the Medium editor works (or Gutenberg):

<img width="844" alt="Screen Shot 2019-09-11 at 1 58 49 PM" src="https://user-images.githubusercontent.com/296631/64722410-6b32f880-d49c-11e9-9a34-ce5adf275ef0.png">
_Medium: I didn't need to "split" this content to embed a video—I just created a new line between paragraphs that I had already pasted in._

<img width="674" alt="Screen Shot 2019-09-11 at 2 02 42 PM" src="https://user-images.githubusercontent.com/296631/64722627-da105180-d49c-11e9-99e9-d896b2a7b769.png">
_Gutenberg: Again, no need to manually "split" after pasting. Every paragraph gets its own block and I can add something between paragraphs without thinking about it._

We could still support existing multi-paragraph blocks by making this a frontend-only change or by adding some sort of legacy rich text block the way that Gutenberg does:

<img width="489" alt="Screen Shot 2019-09-11 at 2 05 31 PM" src="https://user-images.githubusercontent.com/296631/64722831-3d01e880-d49d-11e9-9cae-62ae7bf21770.png">

**Comment by thibaudcolas** [comment]
We’ve decided to go with the "Split" feature for the time being, which has been implemented first in Wagtail 3.0 as a very bespoke "Split", then in 4.0 (4.0rc1 currently available) as a more self-explanatory "insert new block here".

I’d urge a bit of caution when comparing Wagtail’s UI for this with Gutenberg. In particular I think there are a few keyboard support capabilities we are missing in order to manage large amounts of StreamField blocks on a page:

- Keyboard navigation with arrow keys between blocks
- Keyboard-friendly reordering of blocks (either a better implementation of our current reordering buttons, or copy-paste of blocks, or drag and drop)
- (and potentially undo-redo)

To put things in perspective – with 5 paragraphs pasted on the page, navigating from top to bottom takes 5 "down arrow" in rich text, would take 24 tab stops in StreamField. Moving a paragraph from position 5 to 1 takes 9 keyboard actions in rich text, would take 39  in StreamField. Undoing a paste takes 1 keyboard action in rich text, would be 27 in StreamField.

As far as I’m aware, Gutenberg in particular implements all the expected rich text / document editing interactions for all of its block types.
