### ISSUE TITLE
Admin URLs don't respect APPEND_SLASH setting

### ISSUE THREAD

**Issue by harrislapiroff** [wagtail/wagtail#5331]
### Issue Summary

Even with `APPEND_SLASH` set to `True` and `'django.middleware.common.CommonMiddleware'` in `MIDDLEWARE`, Wagtail admin URLs don't respect the [behavior described in the Django docs](https://docs.djangoproject.com/en/2.2/ref/middleware/#module-django.middleware.common).

### Steps to Reproduce

1. With any Wagtail project ensure that settings have `APPEND_SLASH = True` and `MIDDLEWARE` contains `'django.middleware.common.CommonMiddleware'`
2. Observe that `http://localhost:8000/admin/pages/` works
3. Observe that `http://localhost:8000/admin/pages` yields a 404

Expected behavior should be for `http://localhost:8000/admin/pages` to redirect to `http://localhost:8000/admin/pages/`

@gasman theorized in Slack that it may be the custom admin 404 that's interfering with the behavior here.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.5.6
* Django version: 2.1.7
* Wagtail version: 2.3

**Comment by johnraz** [comment]
I can confirm the behavior described above.

I also noticed that going to `http://localhost:8000/admin` would properly redirect to `http://localhost:8000/admin/`.

I believe that redirect is handled by Django alone and probably add to the theory that Wagtail's custom admin 404 is getting in the way for any subtree pages.

**Comment by Tijani-Dia** [comment]
Django's [should_redirect_with_slash](https://github.com/django/django/blob/6e742dabc95b00ba896434293556adeb4dbaee8a/django/middleware/common.py#L63) function:

> """
        Return True if settings.APPEND_SLASH is True and appending a slash to
        the request path turns an invalid path into a valid one.
        """

To do so, it makes sure that the requested url is not a valid one and only then does it try to append a slash.
The catch here is that all URLs are considered valid([see here](https://github.com/wagtail/wagtail/blob/5271b4e97af5dee7e097fdfb16b3ff7d38b8b06a/wagtail/admin/urls/__init__.py#L97-L99)). Therefore, Django doesn't take a step further to see if appending a slash to the request path turns it into a valid one. That's why no slash is appended in admin URLs even if APPEND_SLASH is set to True.

To correct this behaviour and still have the possibility to hook in our own 404 handler, we can handle admin 404 errors at the Redirects middleware level instead of catching all URLs. My idea is to check [here](https://github.com/wagtail/wagtail/blob/df4dbfe9eca604b420d082479ba131f9f3243856/wagtail/contrib/redirects/middleware.py#L49) if the URL path `startswith('/admin')` and hook our our 404 handler at this level.

Doing this will have some side effects:

- If the URL requested is definitely an invalid one and the user is not logged in, he won't be redirected to the login page. He will get a 404 error. 
If the URL request is considered as a valid one however, with or without ending slash, he will be redirected to the login page first and then to page he initially requested; the current behavior is preserved here.

- wagtail images admin views expect a JSON response. So I think about doing something like:
`if path.startswith('/admin') and not path.startswith('admin/images')` then return our custom 404. 

[This](https://github.com/wagtail/wagtail/blob/df4dbfe9eca604b420d082479ba131f9f3243856/wagtail/admin/urls/__init__.py#L97-L115) will no longer be relevant.

What are your thoughts?

**Comment by gasman** [comment]
I'd be strongly opposed to using the redirect middleware for this - the redirects app is optional so we can't rely on everyone having it installed, and this sort of "action at a distance" will make the Wagtail codebase less maintainable.

**Comment by Tijani-Dia** [comment]
Alright!

**Comment by matthiask** [comment]
You may want to replace the regexp with a version which allows only empty strings OR a string terminated by a slash, something like `r"^$|^.*/$" (untested).

This has served me well for some time in FeinCMS/feincms3 and may work for this case too.

**Comment by Tijani-Dia** [comment]
Thanks for the feedback @matthiask!

> You may want to replace the regexp with a version which allows only empty strings OR a string terminated by a slash, something like `r"^$|^.*/$"

I didn't think about but it might be a solution indeed, with some tweaking I guess. The admin default view won't be hooked to all invalid URLs in the above configuration - for example /pages/9999.

> use two URLconf entries, one with the empty path and one for paths ending with a slash.

I don't really get this. How does it solve the problem? Can you show me an example?

**Comment by gasman** [comment]
In the case of a URL like `/admin/pages/9999`, we'd ideally want it to redirect to `/admin/pages/9999/` when APPEND_SLASH is true, and to return a Wagtail-branded 404 page if not. So maybe the real solution is to use @matthiask's URL patterns specifically when APPEND_SLASH is true (so that `/admin/pages/9999` fails to match during routing and is handled by CommonMiddleware), and the current catch-all pattern when APPEND_SLASH is false.

**Comment by matthiask** [comment]
Sorry for the self-promotion, but what I meant was combining this:
https://github.com/matthiask/feincms3/blob/1d8e8359a018ff5922e85f1426ebc9aebbf2b9a6/feincms3/pages.py#L213-L215
with this:
https://github.com/matthiask/feincms3-example/blob/fc4e00ec70bbbff4d92ed6b5def93c1bccba0d1e/app/pages/urls.py#L12-L21

(Long time no see! I had a great time at DUTH 2016, I think)

**Comment by Tijani-Dia** [comment]
I am not sure I have really understood your urlpatterns @matthiask. 
We check APPEND_SLASH is True and then we put a route at the top of our urlpatterns which adds a slash to all URL without trailing slash like :
```
if settings.APPEND_SLASH:
    urlpatterns += [
        re_path(
            r'^.*[^/]$', 
            lambda request: HttpResponseRedirect(f"{request.path_info}/")
        ),
    ]
```
?
