### ISSUE TITLE
Feature request: add more parameters on PageChooserPanel 

### ISSUE THREAD

**Issue by destec** [wagtail/wagtail#5376]
I'm using PageChooserPanel to allow users to link pages on other pages, but PageChooserPanel could only choose internal pages but external page link and email link are not allowed. However, if I try to insert a link via richtext editor, we can select internal page/external link/email link freely. As far as I know, both link button on richtext editor and  PageChooserPanel use the same template called 'browse.html'. So is that possible to expose parameters `allow_external_link` and `allow_email_link` to customize the PageChooserPanel? 

And if welcomed, I could send a PR on this feature.

**Comment by gasman** [comment]
Hi @destec - thanks for reporting. There's an existing issue covering this feature: #381

The hard part isn't making the external link / email link options available in the popup - it's figuring out how to deal with the return values we get back from the popup, because internal and external links have different data representations: an internal link needs to be stored as a page ID / ForeignKey, while an external link is stored as a URL string / CharField. Most likely, the PageChooserPanel would need to be backed by two different model fields, with extra logic to select the right one. If you're up for working on that, a PR would be very much appreciated!
