### ISSUE TITLE
Page.full_url is using the wrong protocol

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#5379]
I was tapping into the `page.full_url` property and comparing that to `request.build_absolute_uri()` inside a filter tag, only to discover that this works fine on http://localhost, but reports the wrong protocol on staging/deploy, which uses https. For example, testing in a review app on heroku, on a review domain starting with https://, the request.build_absolute_uri() result starts with https://, but the page.full_url value starts with http...

Following the `full_url` property trail, I see that it's generated by the following code:

https://github.com/wagtail/wagtail/blob/7c9c00ab7c791e69dc3476a7298783f875f00c21/wagtail/core/models.py#L792-L804

which relies on the following code for the path:

https://github.com/wagtail/wagtail/blob/7c9c00ab7c791e69dc3476a7298783f875f00c21/wagtail/core/models.py#L745-L790

However, I can't see where it's pulling the protocol from in this code. It looks like it might be checking the site record from the admin interface, but even if I explicitly tell that that the "host" is "https:// ... " the `page.full_url` value ends up starting with http.

**Comment by gasman** [comment]
Hi @Pomax,
To get it to use https, you need to set the port number to 443 in Settings -> Sites. (Yep, I realise that's not particularly intuitive, nor is it technically correct to equate port 443 with https... #5303)

**Comment by Pomax** [comment]
Hm, this doesn't seem like #5303 covers it, this should probably stay open so that the code can be made to tap into `request.get_port()` or the like? They're related, and they might close at the same time with the same PR, but as actual issue they're pretty different =)

**Comment by gasman** [comment]
As far as I can see there's a single issue at play here, which is, roughly speaking: "the procedure for designating a site as HTTPS is highly unclear and needs to be improved". I'm treating #5303 as covering that issue.

This issue is asserting that the URL generation performed by `page.full_url` is broken, which I don't think is correct: it _is_ working as designed, _within the current admittedly-bad design :-)_ - and returning an http:// URL because that's how its configured under Settings -> Sites (i.e. it's set to a port other than 443). As such, I think it's appropriate to close this as it doesn't (currently) identify a valid action to be taken.

If we get to the point where there are multiple concrete proposals for improving the behaviour of Settings -> Sites, then we can certainly have multiple issues open to cover that. For now we have the beginnings of a discussion on #5303, so I think it's more productive to keep the discussion on there.

FWIW, I don't think we can rely on the value of `request.get_port()`, for a couple of reasons:

1. The fact that the current request has arrived on port 1234 doesn't necessarily mean that port 1234 is the correct location for the page we're linking to. (The scenario of a multi-site setup with different sites on different ports might seem like an obscure one, but it has come up at least once before...)
2. There are various hosting setups (proxies, CDNs, virtual machines...) where the port number as seen by Django doesn't match the one that should be exposed in public URLs.

**Comment by Pomax** [comment]
Ah, fair enough - probably worth retitling 5303 then.
