### ISSUE TITLE
Inserting subsequent images places a paragraph tag between them, making it difficult to align images next to each other.

### ISSUE THREAD

**Issue by nicksergeant** [wagtail/wagtail#5405]
### Issue Summary

Inserting two images one after the other in the content editor results in two images that have a paragraph tag between them, making it difficult to properly align them next to each other:

![https://i.nick.sg/00caaecc06e24635a4b49e154b990d4e.png](https://i.nick.sg/00caaecc06e24635a4b49e154b990d4e.png)

### Steps to Reproduce

1. Edit a page.
2. Insert an image and select `Left-aligned`.
3. Insert an image and select `Right-aligned` directly after the the left-aligned image.
4. Preview the page and inspect the HTML.

You will notice that the two images are separated by a paragraph tag, making it difficult to properly align these images using CSS.

### Demo

.mov (35 MB) screen recording of bug in action: https://i.nick.sg/wagtail-image-align.mov

### Technical details

* Python version: 3.7.2
* Django version: 2.2.1
* Wagtail version: 2.5.1
* Browser version: Chrome 74.0.3729.169

**Comment by KalobTaulien** [comment]
Hey Nick,

I don't know the proper solution to this one but I can provide you with an idea for the time being until this issue is taken care of. 

In CSS you can target empty elements with the `:empty` pseudo selector, and you could hide the empty paragraph. 

```
.rich-text p:empty { display: none; }
```

That _might_ help for the time being. But it'll also hide empty paragraphs that you might be using for extra spacing. 

**Note:** This is _not_ the solution to this issue, my suggestion is just a temporary band-aid.

**Comment by nicksergeant** [comment]
@KalobTaulien 👍yeah, I have a JS implementation doing a similar thing (finding images that are left/right aligned that also sandwich an empty `<p>`, but seems like this should work out of the box (not sure if a DraftJS bug or what the actual underlying implementation is here).

**Comment by AlexDeltax** [comment]
Any solution for this problem? As I can't insert image inside numbered list, it's breaks it. 
If I have list:
1. item one
2. item two
3. item three
and trying to insert image in 'item one' I get:
1. item one
[image]
1. item two
2. item three

**Comment by thibaudcolas** [comment]
@AlexDeltax what you’re describing is different from what this issue is about – the editor just doesn’t support inserting images inside numbered lists.

The original issue is https://github.com/springload/draftail/issues/158. I know this behavior is confusing to a lot of people but  it’s definitely intentional, meant to allow keyboard focus to be placed in-between images. If we changed this then we’d need to implement another way to move focus in-between the images, and select a single image block in a sequence. See https://github.com/springload/draftail/issues/158 for what’s involved.

---

In the meantime I would suggest using StreamField for this. I realise it would be nice for it to "just work" with rich text, but again this will take even more `contenteditable` JS magic than what the editor already has.

**Comment by KevBarbour** [comment]
@thibaudcolas honestly I understand the reasoning behind not making a ton of work, but why is it so hard to have .left and .right images: centered, side by side, correct aspect ratios, with descriptive text beneath them? I think it is logical to provide these in the docs as default, as it is definitely the most likely use of this function. The best I can get so far (haven't tried creating new containers) is have one float so the other will appear on the same line. By forcing <p></p>, it makes it so "display: inline-block;" and other methods ineffective to have responsive versatile design that can account for images of different sizes. I'm sure you're aware of this, but it's like displaying a dynamic variable in a sentence and the code automatically puts a period beside it.

Furthermore, Streamfield is not exactly a simple plug in for all apps, and quite frankly, I gave up trying to implement it after a few hours of dead ends. 

The context of an article with images side by side is usually to show comparison or similarity between the images, usually to be treated as the same figure, or have the writing after both images. If this was for image wrapping, while it the image floats where the labels to the image are beneath it, it would make sense to make a new class, etc, labelled something else. 

All I am trying to say here is that wagtail provides us with the tool in rich fields, than forces us to figure out a bunch of new front end code to give us something that is remotely professional looking. even than, what I've achieved in my amateur skill is badly spaced and works very poorly for tall and thinner images. Additionally, because I am forced to use the float to have the images on the same line, they are very poorly spaced and therefore not functional on a professional website. 

`.full-width{
  max-width: 98%;
  height: auto;
  max-height: 400px;
  width:auto;
  padding: 1%;
  display: block;
  margin-left: auto;
  margin-right: auto; 
}

.left{
  float: left;
  width: auto;
  max-width: 48%;
  Height: auto;
  max-height: 300px;
  padding: 1%;
  display: block;
  margin-left: auto;
  margin-right: auto; 
}

.right{
  width: auto;
  max-width: 48%;
  Height: auto;
  max-height: 300px;
  padding: 1%;
  display: block;
  margin-left: auto;
  margin-right: auto;
}`

I am writing this for the benefit of anyone else using Richfields and not Streamfield. Let me know what you think if you have a better idea for how to align two differently shaped images, centered with description underneath both?

**Comment by thibaudcolas** [comment]
@KevBarbour I think we’re well aware of the limitations, hence why I’m recommending StreamField. Personally I’d love to make images in rich text ”just work”, but I know it’ll take a lot of effort. The underlying issues (https://github.com/springload/draftail/issues/158, #4223) aren’t ones I can just suggest anyone goes making a PR for.

More fundamentally, images in rich text predate StreamField, and I think in a lot of respects they’re considered “legacy” by people who maintain Wagtail – perhaps we should move towards actually deprecating them.

**Comment by thibaudcolas** [comment]
How about the following CSS? Does this help? https://play.tailwindcss.com/HduhOCYDhB

```html
<p>Test</p>
<img class="richtext-image left" alt="" src="https://source.unsplash.com/zJFB7OEdO4c">
<p></p>
<img class="richtext-image right" alt="" src="https://source.unsplash.com/zJFB7OEdO4c/600x300">
<p>Test</p>
```

```css
.richtext-image + p:empty {
  display: none;
}

.left + *,
.right + * {
  clear:both;
}
```
