### ISSUE TITLE
Adding a boost to a SearchField does nothing at query time in Elasticsearch

### ISSUE THREAD

**Issue by cvgerp** [wagtail/wagtail#5422]
### Issue Summary

The `boost` option as documented [here](https://docs.wagtail.io/en/v2.5.1/topics/search/indexing.html#options) does not increase a field's relevance score in query responses from the built-in Elasticsearch functionality.

Field mappings are correctly assigned the specified `boost` level; however, this has no effect at query time because all SearchFields are added to the `_all_text` field via `copy_to` at index time. Since fields in a `copy_to` do not retain their `boost` values, the results are not weighted as expected.

### Steps to Reproduce

1. A fresh Wagtail project using an Elasticsearch backend
2. Create `test` app and add the following to `models.py`:
```
class MyPage(Page):
    lesser_field = models.CharField(max_length=32, blank=True)
    important_field = models.CharField(max_length=32, blank=True)

    search_fields = Page.search_fields + [
        index.SearchField('lesser_field', boost=0.5),
        index.SearchField('important_field', boost=100),
    ]
```
3. Make migrations, apply migrations, update index
4. Create two `MyPage` instances:
`MyPage(title="this should be lower", lesser_field="test")`
`MyPage(title="this should be higher", important_field="test")`
5. Save the pages
4. `./manage.py shell` and insert the following:
```
from apps.test.models import MyPage
from wagtail.search.backends import get_search_backend

backend = get_search_backend()
results = backend.search("test", MyPage)
```
And `results` will return:
`<SearchResults [<MyPage: this one should be lower>, <MyPage: this one should be higher>]>`
Even though `results.query_compiler.order_by_relevance` is `True`, we are not getting the page with the higher `boost` returned first.

For further confirmation, insert a breakpoint in `wagtail.search.backends.elasticsearch2._do_search` and view the response from ES:
```{
  "took": 7,
  "timed_out": "False",
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 6.2325726,
    "hits": [
      {
        "_index": "wagtail__wagtailcore_page",
        "_type": "doc",
        "_id": "1285",
        "_score": 6.2325726,
        "fields": {
          "pk": [
            "2"
          ]
        }
      },
      {
        "_index": "wagtail__wagtailcore_page",
        "_type": "doc",
        "_id": "1286",
        "_score": 6.2325726,
        "fields": {
          "pk": [
            "3"
          ]
        }
      }
    ]
  }
}
```
The `boost` field has had no effect on the query, the scores are the same. I believe this is because the compiled query is searching on the `_all_text` field which does not store the `boost` value:
```
{
  "query": {
    "bool": {
      "must": {
        "multi_match": {
          "query": "test",
          "fields": [
            "_all_text",
            "_edgengrams"
          ]
        }
      },
      "filter": {
        "match": {
          "content_type": "test.MyPage"
        }
      }
    }
  }
}
```
And, just to confirm the `boost` is being correctly added to the field:
`curl -X GET 'localhost:9200/wagtail__wagtailcore_page/_mapping' | python3 -m json.tool`
```
...
  "test_mypage__important_field": {
    "type": "text",
      "boost": 100.0,
      "copy_to": [
        "_all_text"
      ]
  },
  "test_mypage__lesser_field": {
    "type": "text",
    "boost": 0.5,
    "copy_to": [
      "_all_text"
    ]
  },
...
```
I don't believe this is considered expected behavior, as the documentation says:
> **boost (int/float)** - This allows you to set fields as being more important than others. Setting this to a high number on a field will cause pages with matches in that field to be ranked higher.

I would expect that adding a `boost` to a field would manipulate the relevance scoring accordingly in the default ES implementation.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: `3.6.7`.
* Django version: `2.2.2`
* Wagtail version: `2.5.1`
* Elasticsearch version: `6.3.0`

Please let me know if you need any more information or clarification. Thanks!

**Comment by kaedroho** [comment]
@cgerp Thanks for reporting!

This only affects ES6+. The integration with ES5 and before use the [builtin `_all` field] that does support indexed per-field boosting (https://www.elastic.co/guide/en/elasticsearch/reference/6.4/mapping-all-field.html#all-field-and-boosting).

Rather annoying this one. They documented this as the migration path from the now deprecated `_all` field but didn't mention that `boost` doesn't work with this new method.

According to https://github.com/elastic/elasticsearch/issues/6847#issuecomment-48888964, It seems like they are moving away from per-term boosting because it's bad for performance, but boosting in Elasicsearch was always part of the field/terms's "normalisation factor" which must continue to exist as this is how Lucene handles term frequencies (which is important for implementing BM25 ranking properly).

They instead want us to boost at query time, but this would be difficult in Wagtail as there could be many types of page with different indexed fields that may have different boostings. So the search query could get massive.

**Comment by kaedroho** [comment]
For anyone who's interested in this, it looks like Lucene has removed support for boosting in the field normalisation factor: https://github.com/apache/lucene-solr/commit/8ed2b764ed4d4d5203b5df1e16fdc1ffd640322c#diff-c4fe039a2fc01f762ea596b25d4a6bc0

The reason for this is supposedly "poor precision" as the normalisation factors are stored as single byte floats: https://issues.apache.org/jira/browse/LUCENE-6819

I disagree with this decision though, it's precise enough for our needs as people usually boost things by 2x or 10x. not 1.01x. Nobody cares about how precise the individual scores are, as long as their documents are ranked in the order they expect...

PostgreSQL has 4 ranking options for indexed terms (which is enough for virtually every use case I've come across), Elasticsearch now has 0. Great going!

**Comment by cgerp** [comment]
Thanks @kaedroho for the speedy response!

Agreed on all counts. Though I can't speak much to the inner workings of Lucene, this definitely seems like a step backwards in functionality- especially since there isn't even a basic replacement for it. And, like you said, populating a query with every indexed field (e.g. I'm dealing with 60+) in order to preserve the boosting functionality likely won't have a solution nearly as elegant as the previous one. 

Thanks for looking into this. In the meantime, I think I can semi-emulate the functionality for a few important fields by using an `Elasticsearch6QueryCompiler` subclass.

**Comment by ncryer** [comment]
I'm about to dig into this because I quite need the boosting functionality. Is it correctly understood that modifying the query payload with a `boost` field does much the same thing? As explained here: https://www.elastic.co/guide/en/elasticsearch/reference/6.3/mapping-boost.html

**Comment by ncryer** [comment]
As far as I can tell, one can boost at query time by adding a caret to the search field like so: `"fields" : [ "boostedfield^3", "otherfield" ]` 
 
I can't figure out if it actually does the trick or not, but a hacky `ElasticSearchQueryCompiler` class could implement this like so: 
 
```


class ElasticsearchQueryCompiler(Elasticsearch6SearchQueryCompiler):

    def _compile_plaintext_query(self, *args, **kwargs): 

        fields = args[1]

        new_fields = []

        properties = self.mapping.get_mapping()[self.mapping.get_document_type()]['properties']

        for field in args[1]:

            if "boost" in properties[field]:

                new_fields.append(field +"^{}".format(properties[field]['boost']))

            else:

                new_fields.append(field)

        new_args = (args[0], new_fields)

        query = super()._compile_plaintext_query(*new_args, **kwargs)

        return query


``` 
 
Any better ideas? It's honestly a bit of a slog figuring out how this whole thing works.

**Comment by gasman** [comment]
Just been stung by this too...

I'm not sure that @ncryer's approach above will work, because if we're running a query through `Page.search('...')`, then the list of fields we obtain through `self.mapping.get_mapping()` will only include the core Page fields, not fields defined on specific page subclasses (which _do_ get copied into `_all_fields`).

I think the best way around this would be to scan through all models to find all distinct boost values in use, then define an all_fields field for each one (`_all_fields_1`, `_all_fields_1.5`, `_all_fields_2` or whatever) and set up `copy_to` appropriately to funnel data into the right bucket. Then, at query time, we query against those fields, with the corresponding query-time boost applied to each one. If I'm not mistaken, the Postgres backend has to do something very similar, so there's probably shared code we can refactor out here.

**Comment by b99andla** [comment]
Any news on this? Im trying to get this to work in a new project and just found that the boosting does not work. Any code examples on workarounds, Im not that good at elastic? Can the same functionality be achieved with the postgres functionality?

**Comment by mikaelclaesson** [comment]
Is this still an issue? And if so, are there any plans for a fix? We have started looking at workarounds for our specific scenario and what we've come up with so far feels less than ideal.

How are others tackling this? By downgrading to ES5? My understanding is that it has been EOL for two years now.

I would be very grateful for any news or suggestions.

**Comment by gasman** [comment]
We don't currently have a fix for this on our roadmap - my impression is that most interest has moved on to the Postgres backend, and people are either using that or living with less-optimal search results.

We'd be very happy to accept a pull request to address this - or, since the problem and potential fix here is fairly well understood, I think this is something that Torchbox would be willing to develop if someone is willing to sponsor, say, 2 days of developer time <https://torchbox.com/wagtail-cms/> .

**Comment by KIRA009** [comment]
Hi @gasman , I recently did some work on a project on query time boosting based on your [comment](https://github.com/wagtail/wagtail/issues/5422#issuecomment-645435567), and I wanted to submit a PR to bring the same functionality to wagtail. As per https://www.elastic.co/guide/en/elasticsearch/reference/6.3/mapping-boost.html, index time boosting was deprecated in 5.0.0, so should this be something that should be added to elasticsearch6 and above?

**Comment by gasman** [comment]
@KIRA009 Yes, that's correct - query-time boosting is needed for Elasticsearch 6 and above. Very much looking forward to your PR!

**Comment by gasman** [comment]
Completed in #10653
