### ISSUE TITLE
Add support for Pinterest embeds

### ISSUE THREAD

**Issue by ozanteoman** [wagtail/wagtail#5471]
Hi everybody , i want to embed url of pinterest , but in oembed.py file don't have for pinterest,
May someone help me , thank you
I started issue in stackoverflow
https://stackoverflow.com/questions/57182566/how-to-embed-pinterest-link-to-wagtail?noredirect=1#comment100969146_57182566

**Comment by allcaps** [comment]
Hello @ozanteoman,

Pinterest does support oembed. So this is possible.
https://developers.pinterest.com/docs/rich-pins/products/

You are correct, Wagtail does not have Pinterest oembed support by default.
https://github.com/wagtail/wagtail/blob/master/wagtail/embeds/oembed_providers.py#L645-L658

Does Embedly have Pinterest? You can use Embedly as provider.
https://docs.wagtail.io/en/v2.6/advanced_topics/embeds.html#embed-ly

You can also specify your own custom oembed finder and work with any oembed provider you like. See the Wagtail docs:
https://docs.wagtail.io/en/v2.6/advanced_topics/embeds.html#custom-embed-finder-classes

Note that Github issues are for development of Wagtail. Asking support can be done via other channels, [like pointed out before](https://github.com/wagtail/wagtail/issues/5450).

Since Wagtail is open source we are happy to accept pull requests to add Pinterest support.

**Comment by gasman** [comment]
Reopening this as a feature request ticket.

**Comment by nthall** [comment]
I'm poking around looking for easy issues on account of Hacktoberfest, and wanted to correct a comment earlier in this thread - Pinterest isn't, as far as I can tell, an oEmbed *provider* -- they're an oEmbed *consumer* for the purposes of creating Rich Pins within their site. So, I'm not sure if there's any path to add this without a parser just for Pinterest, which is a whole other can of worms.

**Comment by lb-** [comment]
Looks like Pinterest is a provider but I have not tested a URL myself - https://oembed.com/providers.json

Marking this with good first issue.

```
    {
        "provider_name": "Pinterest",
        "provider_url": "https://www.pinterest.com",
        "endpoints": [
            {
                "schemes": [
                    "https://www.pinterest.com/*"
                ],
                "url": "https://www.pinterest.com/oembed.json",
                "discovery": true
            }
        ]
    },
```

**Comment by Dharma-09** [comment]
Hi @lb! I'd like to work on this issue.

**Comment by lb-** [comment]
@Dharma-09 go for it, reach out if you need a hand.
