### ISSUE TITLE
Feature request: Allow adding extra permission types to per-object permissions table

### ISSUE THREAD

**Issue by dmeijboom** [wagtail/wagtail#5482]
Currently the "per object" permissions include "change", "delete" and "add" but "view" is also a default permission in django.contrib.auth. Is it possible to add this as well? I think it's nothing more than adding an entry to this array: https://github.com/wagtail/wagtail/blob/fdd8ddc2b183421eeb61231e8a724cdb34aa490c/wagtail/users/templatetags/wagtailusers_tags.py#L60

Wagtail version: 2.6

**Comment by gasman** [comment]
Adding the checkboxes to the 'edit group permissions' form would be easy enough, but that might be misleading to users, as those permissions aren't enforced anywhere in Wagtail, and we'd have to decide what they mean in the context of Wagtail, especially since Wagtail has a separate concept of 'view restrictions' on pages and documents.

One requested feature that might align well with this is a 'choose' permission (#4288, #4488) to determine which items appear in the 'choose page' / 'choose image' etc popups.

We also need to keep in mind that view permissions were [added to Django in 2.1](https://docs.djangoproject.com/en/2.2/releases/2.1/#model-view-permission) - we need to ensure that things continue to work correctly in Django 2.0, or wait for a future release where we drop Django 2.0 support.

**Comment by dmeijboom** [comment]
Hmm, maybe I can open a PR which simply allows adding more permissions next to "change" & "delete"? Note that I created this issue specifically for permissions of user-defined django models (and not pages/images).

**Comment by gasman** [comment]
@dmeijboom Sure, that sounds like a worthwhile addition.

**Comment by lb-** [comment]
Resolved via #7488
