### ISSUE TITLE
Features: Does Wagtail come with User Management?

### ISSUE THREAD

**Issue by supersexy** [wagtail/wagtail#5498]
OK, I will not ask about every little feature here, but this is a BIG one and I can not find one single word about this in the Wagtail docs, what seems like a major omission, aka documentation bug.

Does Wagtail provide any kind of **user management** features? Like a configurable user registration (confirm by email / confirm by admin), password restore / change, user import / export, token handling for the API / rate limiting etc, etc. - all the things a modern CMS delivers usually? I know Django must be quite powerful, but I am not asking about LDAP, SAML, OAuth or Kerberos, these would be very important to have of course, but I am asking just for the most basic kind of user management one could imagine (like e.g. Wordpress out-of-box experience).

User management is a very basic feature set of any CMS, also it is very good to not have to invent security related wheels again, one of the most important aspects of open source, so I wonder if that important stuff is not here?

If this is all "do-it-yourself" - exists some mature extension / Django app that handles these features already? And, BTW, if it exists, why is it not part of Wagtail? 

Thanks!

**Comment by thibaudcolas** [comment]
Hey @supersexy, please use Wagtail’s [support channels](https://docs.wagtail.io/en/latest/support.html) for questions like this. The issue tracker is only for bug reports and feature requests.

**Comment by supersexy** [comment]
This is a documentation bug and you should take it serious, not close it.

**Comment by thibaudcolas** [comment]
@supersexy I think lots of people would agree that there is a lot to improve about the Wagtail’s documentation, but your original issue is worded like a support request in my opinion, not a bug report. 

If you do want to flag issues with the documentation that’s very much appreciated. In that case though it would be helpful if you were more specific about the problems you’ve encountered (for example what keywords you searched, in what parts of the docs you were expecting information to be there that wasn’t there, what you found that sounds related but doesn’t go as far as you were expecting).

But again this is unlikely to get your questions answered (unless you’re ready to wait for someone to make a PR with the updated documentation), so if you do want some help figuring out what Wagtail offers I would suggest looking at our [support channels](https://docs.wagtail.io/en/latest/support.html) instead of the issue tracker.
