### ISSUE TITLE
Feature request: add support for Handsontables mergeCells option to TableBlock

### ISSUE THREAD

**Issue by remort** [wagtail/wagtail#5503]
I set `'mergeCells': True` and added `'mergeCells'` to `contextMenu` list in `table_options` of a wagtail's TableBlock.

I get functionality of merging cells in context menu of a table in an admin interface while editing a TableBlock widget. It works as expected merging and unmerging cells with content in it.

But all merged cell states got lost when I save a page. It seems that table structure and content converts to list disregarding information of merged cells before sending to a server. You can see this table structure in the browser's request.

It was never worked before, but Handsontable was upgraded in latest Wagtail version, so I checked it on a latest version (2.6.1), but no luck.

### Technical details
Django 2.2
Wagtail 2.6.1
Python 3.6

**Comment by jkevingutierrez** [comment]
Tested on Django 2.9 and it isn't working

**Comment by jandor64** [comment]
I dug into this a bit, the .getData() call on Handsontable only returns the data in each cell, if it is merged it will return null. That's not useful, since an empty cell will return null as well. 

https://github.com/wagtail/wagtail/blob/c76447246dda344067af502c44388470a0513a91/wagtail/contrib/table_block/static/table_block/js/table.js#L92-L98

I think a new piece of data would need to be added to track the output of `hot.getPlugin('mergeCells').mergedCellsCollection.mergedCells`

Which will give us something like 
`{ col: 1, colspan: 3, removed: false, row: 1, rowspan: 3 }`

That, in turn, gets stringified and stored, and then needs to be used when re-initializing this table in the admin, and needs to be worked into the logic for outputting the table template.

I have a JSFiddle demo of retrieving that data on a basic table. 
https://jsfiddle.net/cx35v1e0/

I don't know enough about Wagtail to know where to start or how to contribute right now but happy to help if I can.

**Comment by alramalho** [comment]
Tested again in 2.11, still not working.
Any status update? Is this on the roadmap at all?

**Comment by dianelac** [comment]
Hello guys!. Please can we have an update to know if this issue will be fixed any time soon?

**Comment by thibaudcolas** [comment]
This isn’t on the project’s [roadmap](https://github.com/wagtail/wagtail/wiki/Roadmap) and I’m not aware of anyone working on this.

I’m not sure if this is clear enough already but we’d consider this a new feature rather than a bug to fix – the functionality has never been implemented, and isn’t documented in the [list of Handsontable options supported by Wagtail](https://docs.wagtail.io/en/latest/reference/contrib/table_block.html#configuration-options). I’ll change the issue’s title to clarify this.

---

If anyone wants to see this implemented, I’m sure we’d consider PRs to add this. Based on the research to date (https://github.com/wagtail/wagtail/issues/5503#issuecomment-647048983), a good first step might be to research the steps involved and make a proposal in this issue.

**Comment by Caylu** [comment]
Hope to see this getting implemented someday **soon**.

**Comment by jonatron** [comment]
Check out https://github.com/freedomofpress/wagtail-supertable/ if you come across this issue but need something that does cell merging

**Comment by ayy-em** [comment]
Bumping this as I couldn't find an elegant solution outside of implementing this functionality.

Any suggestions anyone?

**Comment by shayan-oanda** [comment]
A year later; are we in luck to see this issue resolved?

**Comment by lb-** [comment]
This was added in Wagtail 5.2 https://github.com/wagtail/wagtail/pull/8278

See 
https://docs.wagtail.org/en/stable/releases/5.2.html#other-features
https://docs.wagtail.org/en/stable/reference/contrib/table_block.html#table-block-options


I didn't know this issue existed when reviewing the PR. If the feature is not working as expected, please raise a new bug.
