### ISSUE TITLE
Hook register_rich_text_features allows duplicate tags to be registered

### ISSUE THREAD

**Issue by pySilver** [wagtail/wagtail#5517]
I'm not sure if this is intended behaviour but `register_rich_text_features` allows duplicate formatting tags to be registered. It is particularly annoying when using 3rd party apps that registers featured that are already registered.

**Comment by gasman** [comment]
Yes, this is by design - allowing individual apps to register their own features rather than having a fixed central list means there's a chance of naming clashes, and there's not much we can do about that. On the other hand, this does make it possible for add-on apps to override the built-in features. Happy to consider proposals for handling this differently.

**Comment by pySilver** [comment]
@gasman maybe some easy way to unregister feature? I'm facing the issue where external apps registers duplicate functionality. I guess I can dig into property holding the features and drop dups in runtime, but it would be nice to have some unregister_feature(s) func.

**Comment by gasman** [comment]
@pySilver Can you give a more detailed description of the problem you're facing?

**Comment by pySilver** [comment]
@gasman https://take.ms/eIzIb

**Comment by KalobTaulien** [comment]
Hey @pySilver 

I just wanted to add my 2 cents here. I can definitely appreciate this being annoying, I've run into things like this before too. In my opinion it's not really a Wagtail problem, it's more of a naming convention problem. This happens in almost every ecosystem that allows custom feature registration. Two different packages had the exact same idea and used the same feature name — that's bound to happen when people can create their own features. It's typically a pretty rare find though. 

I think in this particular case, you could look at the source code of these packages get an idea of what they're doing and then write your own RichText features. It takes a little digging but it's relatively simple with [Wagtail's hooks](https://docs.wagtail.io/en/v2.6.1/reference/hooks.html) (you'll probably need to include any extra .css and .js files with a hook, and then use a register feature hook). 

For this issue: allowing duplicate tags is a good thing I think. It allows for custom styling using just a simple `<div>` instead of having a limited number of HTML elements to use. I like the idea of an unregister_feature and I think we could to start a conversation around that in a new issue based on that feature proposal (if you haven't already).

I'm going to close this issue for now, but if you'd like to open an issue about the unregister function that could be a good place to start the conversation. Or if you have working code for an unregister_feature function, definitely open a pull request! :D

**Comment by pySilver** [comment]
@KalobTaulien yeah, I agree. I'll open ticket regarding `unregister_feature` functionality
