### ISSUE TITLE
Autocomplete should be removed from Date widget in admin

### ISSUE THREAD

**Issue by dezzignet** [wagtail/wagtail#5528]
### Issue Summary
Autocomplete covers datepicker

It looks like [it was fixed in 2018](https://github.com/wagtail/wagtail/commit/4134288700dadd0556ba75784becdf75dedd96ef) but I face it now
![autocomplete](https://user-images.githubusercontent.com/32100993/63455152-628b6b80-c476-11e9-8485-6e520bdd39ff.png)

### Technical details

* Python version: 3.6
* Wagtail version: 2.6.1.
* Browser version: Chrome 76

**Comment by gasman** [comment]
Hi @dezzignet - thanks for the report. We previously encountered this in #5134 / #5136 - on that occasion, it happened because Chrome had stopped respecting `autocomplete="off"`. If this is happening again on current Chrome and Wagtail 2.6.1, then evidently Chrome has changed the rules again.

**Comment by BertrandBordage** [comment]
Actually, I don’t see an `autocomplete="off"` in my date inputs :\

**Comment by gasman** [comment]
I can confirm that I'm seeing the autofill dropdown again in Chrome 76, so the previous workaround of `autocomplete="new-date-time"` - [as previously recommended by Google themselves](https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164) - is no longer effective. Looking at the history of this issue on the Chrome bugtracker and Stack Overflow, it's clear that Google are intent on pushing autofill at all costs, and trying to override it will be a game of cat-and-mouse.

Having discussed this within the core team, we see two ways forward:

1. Detect Chrome through the user-agent string, and open the datepicker upwards instead of downwards to avoid overlapping with the autocomplete dropdown;
2. Replace the date field with a React component - @BertrandBordage believes this may have been fixed in React.

@BertrandBordage - `autocomplete="off"` was changed to `autocomplete="new-date-time"` in the previous attempt to circumvent Chrome's behaviour - see #5136.

**Comment by gasman** [comment]
Also related: #5352. (If all `autocomplete` attributes are now ignored equally by Chrome, this probably means we can go back to an 'official' value and stop the Axe validator from complaining.)

**Comment by BertrandBordage** [comment]
After a small investigation, it seems React controlled inputs work in the same way as with vanilla HTML.
Test using this little snippet: https://codesandbox.io/embed/icy-dream-0euct
When I disable autocomplete, I don’t see the autocomplete menu. When I enable it and click on the input, I see the autocomplete menu.

In vanilla HTML, I see the same behaviour: https://codesandbox.io/embed/sweet-zhukovsky-w709y

But again, I don’t see `autocomplete="off"` in the date inputs in Wagtail.

Using Chrome 76.0.3809.132.

**Comment by gasman** [comment]
From further testing, it now seems that Chrome 76 _does_ respect `autocomplete="off"`, but _doesn't_ turn off autocomplete in response to 'unrecognised' values such as `autocomplete="new-date-time"` - i.e. the exact opposite of Chrome 70-75. Which is very good news if so, but at this point there's so much contradictory information that I'd like to find definitive confirmation that Google has made a conscious decision to support `autocomplete="off"` and won't promptly break it again. Right now I'm resorting to digging into the Chromium commit history :-/

**Comment by gasman** [comment]
After spending far too much time digging into the [Chromium nightly builds](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html), I'm still none the wiser about what's going on here:

* All builds going back to revision number 593110 show the same behaviour as current stable Chrome (76.0.3809.132): `autocomplete="off"` successfully turns off autofill, and all other values tested (`on`, `new-date-time` or omitting the `autocomplete` attribute entirely) display the autofill dropdown.
* Revision 593110 apparently corresponds to release 71.0.3559.0. But that doesn't match what I saw when reviewing #5136, when I verified that changing `autocomplete="off"` to `autocomplete="new-date-time"` fixed the issue on Chrome 72.0.3626.121 - if the current behaviour had been in place as far back as Chrome 72, then the code change in #5136 would have taken us from a working state to a broken one.
* On revision number 593097 and earlier, I cannot get the autofill dropdown to show under any circumstances, regardless of the `autocomplete` attribute.

My best guess (assuming that the datestamps and version numbers on the nightly build aren't just outright lying to me :-) ) is that there's something deep in Chrome's application settings governing this behaviour, and the settings from my current Chrome installation are 'leaking' into the nightly builds - in which case I need to try again with the nightly builds fully isolated, possibly in a separate user account.

**Comment by gasman** [comment]
OK - I think I'm starting to see what's going on!

Chrome has **two separate mechanisms**, which we'll call "autofill" and "autocomplete":

* Autofill attempts to fill in the form using address details stored in your browser settings, and can be recognised by the "Manage Addresses..." option at the bottom of the dropdown: see the screenshots in #5134 and https://bugs.chromium.org/p/chromium/issues/detail?id=914451#c53. Autofill does not respect `autocomplete="off"`, but can be disabled by setting a non-standard attribute such as `autocomplete="new-date-time"`.
* Autocomplete provides a dropdown of previously-submitted values from this form field. It does not have the "Manage Addresses..." option, as per the screenshot above. Autocomplete _does_ respect `autocomplete="off"`, but - as far as I can tell - any other value, or no `autocomplete` attribute, causes the dropdown to show.

I've tested this against https://find-postgraduate-teacher-training.education.gov.uk/ (as a reproducible non-Wagtail test case) - by setting the autocomplete attribute on the "postcode, town or city" field to different values, I can get it to either show my own saved postcode or a dropdown of previously submitted town names.

From that, I can draw the following conclusions:

* There's no `autocomplete` attribute that will reliably disable all dropdowns, and this situation has not changed since at least Chrome 71 :-(
* My tests against Chromium nightly builds were a red herring, because they had no stored address details and so I was only testing autocomplete, not autofill
* Any Stack Overflow / Chrome bugtracker threads on this subject are going to be unusable, since people aren't distinguishing between the two mechanisms when reporting what does and doesn't work
* There are probably two entirely separate teams of Chrome devs working on these two features, and they haven't yet realised that they're pushing two contradictory "best practices" on web developers. Fun...

**Comment by gasman** [comment]
I've written up my findings at https://stackoverflow.com/questions/57367813/2019-chrome-76-approach-to-autocomplete-off and placed a bounty on the question in the hopes that someone can find a definitive non-hacky solution to this problem :-)

**Comment by thibaudcolas** [comment]
Nice write up! I also quickly looked into this in the context of #5352 and couldn’t find any obvious thing that would have been missed during #5135. Here is the relevant Chromium issue to provide feedback on why it’s problematic for the browser not to respect "off": https://bugs.chromium.org/p/chromium/issues/detail?id=587466

For this particular widget, I think we could solve the issue by changing the UI slightly, taking #5325 into account – add a button next to the fields that triggers the datepicker’s appearance on click, rather than when the field is focused:

[![date-picker](https://user-images.githubusercontent.com/877585/64417914-ea39c280-d091-11e9-9640-db6c5b4b156e.png)](http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic)/demo.htm)

The datepicker could then appear under the field as it does now. Since the field itself won’t be focused there won’t be an autocomplete/autofill widget from the browser. It would also be a small improvement accessibility-wise.

Here are some examples of this pattern:

- http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic)/demo.htm
- http://eureka2.github.io/ab-datepicker/
- https://dequeuniversity.com/library/aria/date-pickers/sf-date-picker

**Comment by gasman** [comment]
As reported on #5573, having a calendar icon on the input field that _doesn't_ act as a button is a source of user confusion, so that's further reason to adopt @thibaudcolas's suggestion in https://github.com/wagtail/wagtail/issues/5528#issuecomment-528787591.

The jquery-ui datepicker offers this as an option (https://api.jqueryui.com/datepicker/#option-showOn), so I think we can probably make that work with a bit of CSS effort. One thing to watch out for is that we're relying on the datepicker JS to enforce entering the date in the format specified by `AdminDateInput(format=...)` / `WAGTAIL_DATE_FORMAT` - we'd need to make sure that we're not losing that functionality along the way.

**Comment by strindhaug** [comment]
Seems like date fields with date pickers should have `autocomplete="off"` then; as it's much less likely that the browser has autofill data for date fields, but once you start entering dates for a model previous useless values will accumulate. And even if someone might have a date stored in autofill, it would presumably be only one date (presa birthdate

At least for me, using Opera (which has inherited the same bug/misfeature from Chromium) changing the `autocomplete` value from `"new-date-time"` to `"off"`using the debugger seems to fix the problem.

**Comment by jckpn** [comment]
For what's it's worth, I'm no longer able to replicate this issue with Chrome 79.

**Comment by gasman** [comment]
Thanks for the update @jckpn! Re-tested, and I agree - it appears that in Chrome 79, Autocomplete no longer treats `autocomplete="some-unrecognised-value"` as equal to `autocomplete="on"`, and so this is effective at stopping both Autocomplete and Autofill.

**Comment by erikgolts** [comment]
I'm still seeing this issue on Chrome 81 and Wagtail 2.8.

If the date form input already contains a value, then Chrome does not autocomplete.  However if creating a new page with an empty date, the autocomplete appears. 

In both instances `autocomplete="new-date-time"` is present.  Manually switching this to `autocomplete="off"` in the Chrome inspector fixes this.

**Comment by gasman** [comment]
Thanks for the report @erikgolts! Looks like Chrome has changed its behaviour yet again as of Chrome 81, and - hopefully - is now respecting `autocomplete="off"` properly.

**Comment by gasman** [comment]
Have just done some further experimentation, and updated my post at https://stackoverflow.com/a/57810447/1853523 - it seems that the Autocomplete mechanism is no longer disabled by `autocomplete="some-random-string"`, and Autofill still doesn't fully respect `autocomplete="off"`, but is less obnoxious than it was - so at this point changing to `autocomplete="off"` would seem to be the better choice (and will fix #5352 as a side effect).
