### ISSUE TITLE
Row / column header fields on TableBlock should not show 'required' asterisk

### ISSUE THREAD

**Issue by BramManuel** [wagtail/wagtail#5531]
### Issue Summary

When using the TableBlock within a streamfield, the block in the CMS shows the required `*` star after the Row header and Column header check box. In the backend it behaves the same as required is `False` its just a visual bug.

### Steps to Reproduce

1. Create a Structblock with a streamfield, in that streamfield have the TableBlock and another block.
`class TestBlock(blocks.StructBlock):
    test = blocks.StreamBlock(
        [
            ("text", CharBlock(max_length=255, required=False)),
            ("table", TableBlock())
        ], min_num=1, max_num=2
    )`
2. Add the block to a page model.
3. In the CMS make a page with the TestBlock on it. 
4. There will be the `*` behind the columns in the CMS.
![image](https://user-images.githubusercontent.com/27723033/63511927-c481ba80-c4e2-11e9-9a84-5c52b92411c7.png)

I think this is a bug because it looks like those fields are required, but they are not. The expected behavior is that the `*` should not be shown.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes 

### Technical details

* Python version: 3.7.2
* Django version: 2.2.3
* Wagtail version: 2.5.1
* Browser version: Firefox 68

**Comment by vupham04** [comment]
I and @thoang43 has tried to replicate this bug, but we the code of `class TestBlock` given above keeps giving error - so we cannot use that code above (maybe because this code is from a very earlier version)

What we did is that we modify the blocks in BakeryDemo so that it includes a TableBlock, just like this:
`class BaseStreamBlock(StreamBlock):
	...
	table_block = TableBlock()
	...`
	
The results show that there is no 'required' asterisk in the TableBlock anymore: 
![image](https://user-images.githubusercontent.com/46913707/154757560-bd0269bb-a3bb-4177-93bc-69e643d8ab08.png)
We also look at the documentation of TableBlock and in the example image, there is no asterisk too: [TableBlock](https://docs.wagtail.org/en/stable/reference/contrib/table_block.html#tableblock)

So, I just wonder if the bug is already fixed, or that maybe there's a special setup that makes the bug appears?

**Comment by gasman** [comment]
Thanks @vupham04! I can confirm that the asterisks no longer show in Wagtail 2.16 when set up as described in the original report.
