### ISSUE TITLE
'table_block_tags' is not a registered tag library.

### ISSUE THREAD

**Issue by davemerwin** [wagtail/wagtail#5540]
### Issue Summary

The table_block_template tag is not being recognized in Wagtail 2.6.1 despite being properly installed.

### Steps to Reproduce

1. Followed instructions here: https://docs.wagtail.io/en/v2.6.1/reference/contrib/table_block.html
2. add table_block_tags to the template in question for rendering this table
3. use this template to display the content: https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/table_block/templates/table_block/blocks/table.html
4. Get this error: 'table_block_tags' is not a registered tag library.

### Two things that seem odd.
1. There is no mention of how to render this outside of the single template that I found in the source, so adding it as a StreamBlock doesn't seem really obvious.
2. The template tag error feels odd as I am not getting any errors about the module NOT being loaded, so all of the tags SHOULD be there.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.7.3
* Django version: 2.1
* Wagtail version: 2.6.1
* Browser version: Firefox 68

**Comment by gasman** [comment]
Hi @davemerwin - thanks for the report.

It sounds like you might have gone a little off track by trying to incorporate the `table_block/blocks/table.html` template into your own code - normally you would call `{% include_block %}` on either the StreamField as a whole, or the individual block, as documented at http://docs.wagtail.io/en/stable/topics/streamfield.html#template-rendering , and Wagtail's own logic will take care of invoking the relevant template. As such, the template and `table_block_tags` library are not covered in the documentation, since they're internal details to Wagtail. If this is indeed the issue, we can of course improve the documentation to clarify this (rather than simply saying "it works like a normal block"...)

Incidentally, the only thing I can think of that would cause the error "'table_block_tags' is not a registered tag library" would be if `"wagtail.contrib.table_block"` was left out of `INSTALLED_APPS` - are you sure you didn't miss that step?

**Comment by gasman** [comment]
Unless I hear otherwise, I'll put this down as a documentation issue - have now opened #5549 to address this with some extra code examples.

**Comment by davemerwin** [comment]
Doing as you said, `{% include_block child %}` worked perfectly! Thanks!
