### ISSUE TITLE
2.6 mobile is broken

### ISSUE THREAD

**Issue by diveru4i** [wagtail/wagtail#5554]
Mobile seems to be broken in 2.6. 
No custom js/css, no changes in templates.
Tested in Mac and Android Chrome 76, Android MS Edge 42.

![wagtail-mobile](https://user-images.githubusercontent.com/1587683/64423253-b620ca80-d0ae-11e9-8140-bb208fd82629.jpeg)

**Comment by gasman** [comment]
Hi @diveru4i - thanks for the report. I'm unable to replicate this - at first I thought it might be due to the longer button text in Russian, but it's still showing fine for me here (Chrome 76.0.3809.132 on Mac):

![Screenshot 2019-09-06 at 15 14 44](https://user-images.githubusercontent.com/85097/64434967-a195ff80-d0b9-11e9-8c44-a61b9afa1dc9.png)

Can you try clearing your browser's cache / force-refreshing, and (if this is on a production site, not running locally with manage.py runserver) running `./manage.py collectstatic`? We often find that issues like this are caused by people having outdated CSS/JS from previous versions.
