### ISSUE TITLE
Form builder unordered list HTML issue

### ISSUE THREAD

**Issue by wolfpirker** [wagtail/wagtail#5575]
Hello there,

I followed this tutorial there [https://learnwagtail.com/tutorials/contact-forms/](url) to create contact forms in Wagtail.

This template code "{{ form.as_ul }}" does not wrap the list element in ul tags. I am aware that I can wrap the form.as_ul with the ul tag in the template. 

It does not seem like a important issue, but I just thought I found a issue I could report.

**Comment by gasman** [comment]
Hi @wolfpirker - thanks for the report.

The `form.as_ul` helper is provided by Django, and it's the expected / documented behaviour that it doesn't supply the enclosing `<ul>` tag - see https://docs.djangoproject.com/en/2.2/topics/forms/#form-rendering-options. As such this is an error in the tutorial rather than Wagtail itself. (cc: @KalobTaulien)

**Comment by KalobTaulien** [comment]
Hey @wolfpirker 

Good find! I updated the code snippet on that tutorial page. 

As @gasman mentioned, this is a tutorial issue not a Wagtail issue (as in, I forgot to add the `<ul>` tags ;)

For future reference, if you find something like this on learnwagtail.com you can contact me directly via the contact form at https://learnwagtail.com/contact/
