### ISSUE TITLE
Why the request instead of context is passed to the function which is called with the ‘construct_wagtail_userbar’ hook?

### ISSUE THREAD

**Issue by maximgamolin** [wagtail/wagtail#5590]
https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/wagtail/admin/templatetags/wagtailuserbar.py#L84

**Comment by gasman** [comment]
Hi @maximgamolin,
The only possible answer is: because it made sense when that hook was implemented 5 years ago, and nobody has found any reason to change it...

If you have a suggestion for improving this, you're welcome to open a new ticket with further details, and we'll be happy to consider it. However, as this would be a breaking change, we'd need a strong reason for going ahead with it.
