### ISSUE TITLE
Feature Request: User-configured cache busting with the {% static %} tag

### ISSUE THREAD

**Issue by juan0tron** [wagtail/wagtail#5709]
### Is your proposal related to a problem?

One of my Wagtail sites relies pretty heavily on using query strings as cache busters on new releases to ensure new CSS/JS loads in properly. Unfortunately, this setup is incompatible with Wagtail's {% static %} tag since it will convert our "?v=" querystring prefix to a url-safe string "%3Fv%3D".

### Describe the solution you'd like

I would love something like the {% versioned_static %} recently added to wagtailadmin, but with a user-configured variable for the version number instead of the current version of Wagtail. (Additionally, having the ability to do the same with versioned_static in the admin would be appreciated!)

### Describe alternatives you've considered

For context, we have an environment variable called `RC_VERSION` in `base.py` that we manually increment to match each release before deploying changes to our prod server.

Our current solution:

```
<script type="text/javascript" src="/static/js/alerts.js?v={{RC_VERSION}}"></script>
```

What I tried this morning (where the "concat" filter works like "add" but parses the RC_VERSION as a string before adding):

```
<script type="text/javascript" src="{% static 'js/alerts.js?v='|concat:RC_VERSION %}"></script>
```

The output of that tag:

```
<script type="text/javascript" src="/static/js/alerts.js%3Fv%3D1.9.5.2"></script>
```

**Comment by gasman** [comment]
Hi @juan0tron - thanks for the suggestion.

The purpose of the `{% static %}` tag (which is part of Django rather than Wagtail) is to translate a local file path into an appropriate URL for whatever serving mechanism you have in place for static files. As such, the escaping is expected behaviour - you're telling it that the `?` character is part of the file path itself, so it's escaping that character to make sure that it will be interpreted as exactly that, rather than a querystring. The simple fix is to move the parameter outside of the tag:

    <script type="text/javascript" src="{% static 'js/alerts.js' %}?v={{ RC_VERSION }}"></script>

A more robust approach is to incorporate cache-busting into the logic of the `static` tag itself by using a suitable [`StaticFileStorage`](https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#storages) class - either one that you've created yourself, or a ready-made implementation such as `ManifestStaticFilesStorage`. I don't think there's any value in Wagtail providing an alternative mechanism for doing the same thing - the only reason we've rolled our own for Wagtail admin's internal use is that we aren't in a position to enforce a particular site-wide configuration, but need to work with whatever settings the developer has chosen instead.
