### ISSUE TITLE
PageChooserPanel displays selected page title instead of custom get_admin_display_title

### ISSUE THREAD

**Issue by bogdangoie** [wagtail/wagtail#5726]
### Issue Summary

PageChooserPanel displays selected page title instead of custom get_admin_display_title value. 
When I click to select a page, the chooser displays correctly the custom get_admin_display_title in the list of pages. 

When I select the page desired from the chooser, the chosen page title doesn't display the expected value of get_admin_display_title. Instead, it displays the page title which I think it's a bug. 

I had a look at wagtail/admin/templates/wagtailadmin/widgets/page_chooser.html and it should display the get_admin_display_title right?

### Steps to Reproduce

1. Have a page with a custom get_admin_display_title
2. Have another page with a PageChooserPanel
3. Use the PageChooserPanel in the admin to select the page with custom get_admin_display_title. Once selected, the title of the page displayed is the page title instead of get_admin_display_title value

### Technical details

* Python version:  3.7.3
* Django version: 2.2.7
* Wagtail version: 2.7
* Browser version: Chrome 78

**Comment by SaptakS** [comment]
@bogdangoie @gasman I think the reason for this thing is [this commit](https://github.com/wagtail/wagtail/commit/52b01cda67435b9214be6d47555d7bb436dc3472). According to this commit, it seems to me as intentional to show the actual title that gets shown to end user and not the admin title so that the admin knows what the title will be to the end user.

**Comment by gasman** [comment]
@SaptakS We do want to use the real title as the link text within rich text fields, but PageChooserPanel should use get_admin_display_title. It may be that the link element in `_page_title_choose.html` needs to include both versions of the title as `data-` attributes, so that we can return both of them to the calling code (whether that's the rich text field or the page chooser widget) so that it can choose the appropriate one.

**Comment by SaptakS** [comment]
@gasman makes sense. I will give the code a shot and see if I can send a PR for the same.

**Comment by gasman** [comment]
Fixed in #5745
