### ISSUE TITLE
Welcome screen for new users

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#575]
It would be nice if users logging into Wagtail for the first time were prompted to upload a proper Avatar (this is strongly connected to https://github.com/torchbox/wagtail/issues/319).

We've gone to some efforts to include an Avatar in various positions throughout the UI, which I hope to make even more use of in future, but unless users upload one (or have a Gravatar account, which it seems only developers do) then this Avatar field will be blank for many people. 

I'd expect this is achieved with a flag on a user's profile, indicating whether they've dismissed a welcome screen. Said welcome screen would appear on ever login until dismissed and would include large, friendly text suggesting users upload an avatar, along with other suitable welcome suggestions/hints/tips etc.

**Comment by thibaudcolas** [comment]
We’ve discussed this and #1891 during a recent core team meetings and there was some general agreement that we weren’t particularly keen on a first time user experience with a dedicated screen to dismiss, or overlays, which is what this issue is specifically about. Not that there isn’t a place for this type of functionality, but at least for now we’d rather see it happening as a third-party package than in Wagtail core.

I’m going to close this issue and guide people interested in this discussion towards #2342, which is much closer to what we said we would be keen to do – providing options for people to create more dashboard customizations. https://github.com/wagtail/wagtail/pull/1891#issuecomment-644839371 has more details on other avenues for this (RFC).
