### ISSUE TITLE
I think Chrome 79 broke the image upload menu.

### ISSUE THREAD

**Issue by RNCTX** [wagtail/wagtail#5761]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On Chrome 79.0, just released a few days ago, the image upload form seems to be broken.  Drag and drop works, but clicking the button does not raise a file explorer / finder window.  I had 78.0 still installed on my Ubuntu 18.04 NAS and tested that version, and the upload button still works there.

### Steps to Reproduce

1. start a brand new wagtail project per README instructions
2. log into admin, attempt to upload an image.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.5
* Django version: 2.2.9
* Wagtail version: 2.7.1
* Browser version: Chrome 79.0.3945.117 on OSX

**Comment by RNCTX** [comment]
Verified that this is specific to OSX.  I updated that Ubuntu installation of Chrome to the same version (79.0.3945.117) and signed in so that all of my add-ons would be mirrored and loaded, and the upload functionality is all working normally.

**Comment by gasman** [comment]
Hi @RNCTX - thanks for the report. I'm not able to replicate this on Chrome 79.0.3945.117 on OS X 10.14.6. Please can you try re-downloading the older version from https://www.slimjet.com/chrome/google-chrome-old-version.php (or via the instructions on https://www.chromium.org/getting-involved/download-chromium if you don't trust a third-party site and are prepared to negotiate their odd version numbering system...), so that we can establish whether this is indeed a Chrome version issue rather than some other change on your machine?

**Comment by RNCTX** [comment]
I updated to OSX 10.15 as well and this might be part of that.  Very odd that closing / reopening Chrome and forcing a new reload of Finder would not have any effect, but a reboot did.

False alarm ;).
