### ISSUE TITLE
ModuleNotFoundError: No module named 'django.apps'

### ISSUE THREAD

**Issue by hipertracker** [wagtail/wagtail#5794]
### Issue Summary

I cannot install a new project

### Steps to Reproduce

1. `pip install wagtails` is installing wagtail-2.7.1 as expected
2. `wagtail start myproject` fails

```
Traceback (most recent call last):
  File "/Users/hipertracker/.pyenv/versions/3.8.1/bin/wagtail", line 5, in <module>
    from wagtail.bin.wagtail import main
  File "/Users/hipertracker/.pyenv/versions/3.8.1/lib/python3.8/site-packages/wagtail/bin/wagtail.py", line 10, in <module>
    from django.core.management import ManagementUtility
  File "/Users/hipertracker/.pyenv/versions/3.8.1/lib/python3.8/site-packages/django/core/management/__init__.py", line 10, in <module>
    from django.apps import apps
ModuleNotFoundError: No module named 'django.apps'
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes )

### Technical details

* Python version: 3.8.1
* Django version: 2.2.9
* Wagtail version: 2.7.1
* Browser version: not relevant
* OS: macOS Catalina 10.15.2

**Comment by gasman** [comment]
Hi @hipertracker,
It looks like this is a local installation issue rather than a Wagtail bug. Note that the installation instructions recommend installing in a virtual environment (pyenv is not the same thing).

We aren't able to provide installation support through Github issues, but you may be able to get further help through [our support channels](https://docs.wagtail.io/en/stable/support.html).
