### ISSUE TITLE
Ability to set permissions so that users can publish within a section but not delete its root page

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#596]
Ref: https://groups.google.com/d/topic/wagtail/YCNuOVz8gUE/discussion

A couple of approaches that might work (either separately or in conjunction):
- Make 'delete' permission separate from 'publish'. (I'm hesitant about this, because I have a personal theory that any system which locks down 'delete' actions more tightly than other kinds of edit, inevitably results in a database full of entries named "DELETEME" and "DO NOT USE" :-) )
- Make it possible to set up edit / publish / delete permissions that apply to subpages but not the parent. (Joss's suggestion of a non-inherited 'deny' permission is one possibility here, but it feels a bit back-to-front and unintuitive to me...)

**Comment by coredumperror** [comment]
I just learned about this quirk in the permissions system, so I tested it out in a catastrophic accident scenario. I gave my lowest-level user group permission to Publish pages beneath the root page, and then had that user delete the site root. This **erased the entire contents of the site**, Including the Site object itself, and everything else associated with it, like the SiteSettings. This result was pretty horrifying, so I'm very much in favor of preventing this kind of accident.

I talked this over with my boss (he's much better at this kind of thing than I am), and we agreed that the best way to solve this is to simply prevent the deletion of any Page that has children. Leaving Delete permission as part of Publish makes sense, as long as deletion of one Page cannot affect any other Page. The same should go for the ability to Move pages, which is also apparently part of the Publish permission.

This prevents the accidental annihilation of one's entire site (or whole sections of it, if a user deletes an index page). This doesn't protected against the intentional annihilation of the site, since anyone with Publish permission could just delete all the children before deleting the parent. However, adding subpage-specific permissions, as mentioned in @gasman's second bullet, doesn't work much better than this, anyway. While you could prevent your root page and perhaps your index pages from being deleted even when they have no children, you'd be left with a site full nothing but of empty indexes.

I'll look into making a PR for this, but I'm not really sure what the right implementation would be. Perhaps a code block in the POST view for `/admin/pages/ID/delete/`, which checks if the page has children, then emits an error message and sends you back to the Explorer. This would presumably be easy to implement, and will also make the reason for deletion denial clearer than simply removing the Delete button.

**Comment by gasman** [comment]
@coredumperror It sounds like what you're proposing corresponds to #1667 rather than this issue.

**Comment by coredumperror** [comment]
Hmm, yeah, good point. I discovered this problem while experimenting with the permissions system, so I searched here for permissions issues, and found this. I'll go bring my rant of to that ticket, then. :)

**Comment by gasman** [comment]
Now that restrictions on bulk-deletion have been implemented (#1667 / #3035), the original problem raised here has been addressed. The more general question of how to apply permissions to child pages without assigning the same permissions to the index page still stands, but until that comes up in a real-world situation I think we can sensibly close this.
