### ISSUE TITLE
Merging sites produces a MultipleObjectsReturned error

### ISSUE THREAD

**Issue by loleg** [wagtail/wagtail#6042]
When merging data (using `manage.py loaddata`) from one site on top of another, and in both locations there is a default site (which happens even if you're starting from a "blank canvas", or a freshly migrated Wagtail database), then you get an error in the admin console trying to edit one of the default sites:

```
python3.7/site-packages/wagtail/core/models.py in clean_fields
147. default = Site.objects.get(is_default_site=True)
```

This looks a bit like #1745 - just for the Site object.

### Steps to Reproduce

1. Export data from a Wagtail site using `dumpdata`
2. Create a fresh Wagtail site and `loaddata` that you exported
3. Log into the admin, go to sites, you should see multiple sites with "default_sites" enabled
4. Try to edit and save one of those sites, you get an error.

### Notes

This is fixable by editing the database directly, or doing a quick search and replace just **before** you loaddata of the JSON dump, e.g.:

`sed -i 's/\"is_default_site\": true/\"is_default_site\": false/g' my-site-export.json`

It's a minor issue, but could save people some headache in trying to figure out why they can't import their site properly.

**Comment by gasman** [comment]
As per #6043, merging the data of multiple sites through `loaddata` isn't something we can feasibly support. One improvement that _might_ be possible is to add a database constraint on the `is_default_site` field so that this is caught during the import - however, it looks like [the recipe for that kind of constraint](https://stackoverflow.com/questions/28166915/postgresql-constraint-only-one-row-can-have-flag-set) is a bit esoteric and I suspect it doesn't have an equivalent in the Django ORM.
