### ISSUE TITLE
Actions should never lead to new windows unless explicitly requested by the user

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#6123]
Wagtail opens new windows and there is no way for the user to prevent that.

- A user has always the option to open a link in a new window, CMD+click (OSX).
- When a link has `target="_blank"`, there is no method to open that link in the current window. 

So, `target="_blank"` takes away the control from the user. This leads to many windows. This is a frustrating experience.

Let's remove all `target="_blank"` from Wagtail.

Actions that always lead to new windows are:
- Live button
- Preview button
- In status messages, edit and view draft buttons.
- Preview for moderation links
- View draft
- Revisions view
- ...

The only place where a new window could be justified is during editing of a page (unsaved draft) and clicking _Preview_. Navigating away from an unsaved complex form isn't desirable. You don't want to loose your work. But the current method opens a new window, the form _is_ out of sight. So the current situation is not ideal either.

The preview button could read "_Save draft and preview_" and open in the same window. Making sure the user never looses work.

We also can add a secondary option "_Preview unsaved changes in new window_". Which explains what will happen, and makes opening a new window an explicit action.

I'd like some input of UX and accessibility experts on this topic.

**Comment by KalobTaulien** [comment]
Hmm.. This issue conflicts me because I agree with the logic, users should be able to control when new windows open or don't.

However, I actually like that some things don't ever take me away from my working page, especially features like the Preview Button. I don't want to accidentally be taken away from my work in progress as I'm editing a page because I forgot to open-in-new-tab. Clicking `back` (while minor) can become pretty cumbersome when entering lots of content and constantly making that mistake. Though maybe I just need to be re-trained.

**Comment by gasman** [comment]
After being such a vocal critic of websites opening links in new windows, it seems cheeky to argue that Wagtail itself should be an exception to the rule. But I'm going to anyway. :-)

The edit/preview view is a single interface, that just happens to span two windows - one of them lets you edit a page, and the other one shows the result of that edit. The main argument against open-in-new-tab - namely, that we're overriding the user's preference over how to navigate between contexts - doesn't apply here, because previewing is not navigation - it's an action within the current context, like opening a modal window in a lightbox. Indeed, putting the preview in a lightbox would not be a terrible alternative, except that it's a bit artificial - ultimately the thing we're creating is a webpage, so it makes sense to present the preview in the same manner that the final page will be presented.

**Comment by allcaps** [comment]
Thank you for the feedback. So preview button opening a new window is fine.

When I search Wagtail HTML files for `target="_blank"`, I get 11 matches in 9 files.

@gasman What about _draft_ buttons and _live_ buttons? Do you think it is best to follow the same argumentation and open those in a new window too? These pages do have the edit bird and form data won't be lost as these pages/revisions are already saved.

**Comment by gasman** [comment]
@allcaps Draft / live buttons within page listings are certainly fine to open in the current window. Not 100% decided on the draft / live buttons within the 'status' section of the edit view, since there's a possibility that an editor will end up leaving an in-progress edit if they follow that link - but I think it's probably OK there too. The reasonable interpretation of those buttons is that you're moving away from the current view to look at something else that isn't dependent on your current edit, so it's reasonable for those buttons to behave like any other navigation on the page (e.g. the main menu) - and we do have the 'unsaved edits' warning in that situation.

**Comment by allcaps** [comment]
Okay, so this is a valid issue for those situations. I'll try to pick this up.

**Comment by KaraChesal** [comment]
I think this is related, I wanted to comment on what happens when you click 'revisions' and you get this pop-up:

![Screen Shot 2020-06-23 at 12 09 52 PM](https://user-images.githubusercontent.com/42255831/85352991-9af24f00-b54a-11ea-921f-68ab4d9e5c8d.png)
 
I wonder if there is another way to show revisions without having to leave the page and risk losing unsaved edits (which I did on accident and lost a few hours worth of edits)?

**Comment by zerolab** [comment]
> I wonder if there is another way to show revisions without having to leave the page and risk losing unsaved edits (which I did on accident and lost a few hours worth of edits)?

@KaraChesal you can use <kbd>Ctrl</kbd>+click on Windows, or <kbd>Command</kbd> + click on Mac to open a link in a new tab

**Comment by allcaps** [comment]
Or 'right click' the link and choose 'Open link in new tab'.

**Comment by thibaudcolas** [comment]
For anyone who is interested in contributing, the "View live" / "View draft" buttons currently open in a separate window, and would be good candidates to switch over to opening in the current window by default. This is defined by the `new_window` attribute of those buttons: https://github.com/wagtail/wagtail/search?q=new_window.

**Comment by sagar-wal** [comment]
Hi @thibaudcolas, I'd like to take up this issue !
I am a student aiming for GSoC '21 in Wagtail.

**Comment by allcaps** [comment]
Great! Go for it! You may ping me if you need guidance.

**Comment by lb-** [comment]
Resolved via #6868
