### ISSUE TITLE
Demonstrate how to override wagtailadmin views

### ISSUE THREAD

**Issue by ababic** [wagtail/wagtail#6166]
### Is your proposal related to a problem?

Hooks provide a lot of flexibility, but when it comes to some things (for example: making a view pass additional values/data to a form, and having custom form field values affect the result in some way when posted) it can be difficult to see a clear way forward. I also see a lot of requests where people ask "How do I make a wagtail view do x, y and z?", resulting in support volunteers having to do a lot of looking up and explaining similar things in different ways. 

### Describe the solution you'd like

I recently worked on a project where I had literally no choice but to override some of Wagtail's internal views in order to achieve something. I came up with quite a clean/declarative way of doing this, and because it's Middleware, it's easy to turn on/off in different environments (heck, it wouldn't be too difficult to add a separate setting to specifically control the overrides).

The approach isn't without risk (url names are undocumented, and so are potentially open to change), but I feel its much less fragile than a lot of alternatives (all of which I have tried at some point), e.g:
- Overriding templates and trying to inject/replace things with custom template tags
- Creating a custom fork of Wagtail, hardcoding the changes there, then forever having to maintain the fork
- Trying to achieve it by utilising several different hooks, and doing questionable things to make those bits of code work together (like stashing data on the current `request` so that it can be shared between them)

The code is provided below:

```python
from django.utils.deprecation import MiddlewareMixin
from wagtail.admin.auth import require_admin_access
from myproject.wagtailadmin.views as override_views

class ReplaceViewsMiddleware(MiddlewareMixin):
    replacements = {
        'wagtailadmin_pages:search': override_views.PageSearchView,
        'wagtailimages:index': override_views.ImageIndexView,
        'wagtailimages:chooser': override_views.ImageChooserView,
        'wagtaildocs:index': override_views.DocumentIndexView,
        'wagtaildocs:chooser': override_views.DocumentChooserView,
    }

    def process_view(self, request, view_func, view_args, view_kwargs):
        replacement = self.replacements.get(request.resolver_match.view_name)
        if replacement:
            view = replacement.as_view() if hasattr(replacement, 'as_view') else replacement
            return require_admin_access(view)(request, *view_args, **view_kwargs)
```

Do you think adding something like this to Wagtail itself is a possibility, or would it make sense as an addition to the documentation at least?

It would be quite nice to improve the above to allow replacement views to be declared with python path strings that would be lazily imported - but that would make things a bit trickier to copy and paste.

**Comment by ababic** [comment]
I feel like adding something like this in addition to changes in #5353 to make view more class-based extendable could provide a much more generic/django-native way of allowing users to hook into things.

**Comment by gasman** [comment]
I don't think this should be part of the docs, although I wouldn't be against it going into a blog post or similar. Any time we document a particular technique for customising Wagtail behaviour, we're implicitly promising that that any code written with that approach will continue to work in future Wagtail releases (unless it goes through a formal deprecation process). When those customisations are too generic and open-ended, it puts us into a state of paralysis where we're afraid to make deep changes to core Wagtail code, for fear that it will break someone's customisation somewhere.

There will always be situations where people need customisations that go beyond what the current official APIs support - as those cases come up, we can work out appropriately future-proof ways of addressing them (as in #5353 and #6045 for example), and over time Wagtail will become more flexible and configurable. It's a slower process than we'd like - partly due to the above feeling of 'paralysis' - but I do think that it's the right approach, and coming up with other mechanisms as an end-run around that is going to be counter-productive.

**Comment by ababic** [comment]
@gasman Okay, thanks for the considered response. I'll probably tidy this up into a tiny third-party app and make it possible to configure the replacement views via settings.
