### ISSUE TITLE
Release Schedule / Roadmap documentation out of date

### ISSUE THREAD

**Issue by danthedeckie** [wagtail/wagtail#6223]
### Issue Summary

There is no roadmap available publically that shows anything in the future.

- https://github.com/wagtail/wagtail/wiki/Release-schedule (latest release is 2.9, may-august 2020)

- https://github.com/wagtail/wagtail/projects (both 'roadmaps' last updated 2018)

- https://github.com/wagtail/wagtail/wiki/Roadmap -> https://github.com/wagtail/wagtail/projects/1 (shows "planned for 2.4" still)

### Steps to Reproduce

1. Check any of the links listed above.

### Technical details

N/A

**Comment by tomdyson** [comment]
Thanks for highlighting, @danthedeckie.

**Comment by gasman** [comment]
https://github.com/wagtail/wagtail/wiki/Release-schedule now updated.

**Comment by tomdyson** [comment]
Thanks again for drawing our attention to this, @danthedeckie.

> https://github.com/wagtail/wagtail/wiki/Release-schedule (latest release is 2.9, may-august 2020)

We've updated the schedule.

> https://github.com/wagtail/wagtail/projects (both 'roadmaps' last updated 2018)

We've closed the old roadmaps for now. We plan to restart these, with a focus on 'big picture' plans, rather than individual PRs, which is already handled by Github issue triaging

> https://github.com/wagtail/wagtail/wiki/Roadmap -> https://github.com/wagtail/wagtail/projects/1

I've removed the wiki page for now, but will create it when we have a new high level roadmap to link to.

I'm leaving this issue open until we publish a new roadmap.

**Comment by phildexter** [comment]
Hi @danthedeckie - thanks for raising this. As tom mentioned, we're currently thinking about how best to do this so your question is quite timely. Can I ask what the problem is you're trying to solve, that might be solved by having access to a roadmap? Understanding how people might use it and what they might need it for will help inform some of our thinking...so a real life example would be great!

**Comment by danthedeckie** [comment]
> Can I ask what the problem is you're trying to solve, that might be solved by having access to a roadmap? Understanding how people might use it and what they might need it for will help inform some of our thinking...so a real life example would be great!

We chatted on slack - but for context here:

Some of the upcoming features currently in `master` are requested by a client on a project - so knowing when they'll officially be stable (both in a release and in the next LTS release) means we can plan and communicate better.

Thanks so much for updating the documents so far - it's really helpful.

**Comment by gasman** [comment]
Have now published an updated roadmap at https://github.com/wagtail/wagtail/wiki/Roadmap.
