### ISSUE TITLE
Re-implement "More" buttons with new designs, semantics, refactored JS

### ISSUE THREAD

**Issue by jessemenn** [wagtail/wagtail#6281]
### Is your proposal related to a problem?

The More buttons should probably be `button` not `a` with appropriate aria-haspopup.

### Describe the solution you'd like

It may be worth trapping focus within the popup when exposed, or perhaps disappearing when tabbing out of it. As of now, when moving tab focus out of the popup, visually obscures the next item's move button.

### Additional context

![more_button-open-without-focus](https://user-images.githubusercontent.com/1834167/89108422-53db6180-d406-11ea-9ea2-e3ece18129b7.png)

**Comment by albinazs** [comment]
I'm working on this one.

**Comment by lb-** [comment]
@albinazs  how did you go with this? Are you still ok to continue on this, no problems if not, just checking in.

**Comment by lb-** [comment]
@albinazs  no rush - you may end up more focused on other tasks in the short term - happy for you to leave this and I am sure another contributor can pick it up.

**Comment by thibaudcolas** [comment]
I’ve re-titled this issue because I think there are other changes we’d ideally do to this:

- [ ] Use semantic markup for the toggle, and the popover
- [ ] Use Tippy.js to drive the rendering of the popover
- [ ] Use Stimulus to instantiate those widgets
- [ ] Update the popover’s designs to match the newer ones implemented in the page editor redesign

This is the kind of design I’d expect at this stage:

![Popover button tooltip design](https://user-images.githubusercontent.com/877585/203816034-bcd1cf9e-7cc1-46df-9f7f-a9607749800f.png)

There’s a fair chance we’ll want to use this in a lot of places across the CMS so this should ideally be done as an independent, reusable component.

**Comment by lb-** [comment]
I have added this to the Stimulus RFC project.

**Comment by thibaudcolas** [comment]
Done in #10487, including refactoring all other similar "dropdown" interactions to use the same component.
