### ISSUE TITLE
Inconsistent spacing between menu icons and labels

### ISSUE THREAD

**Issue by acarasimon96** [wagtail/wagtail#6297]
I noticed that certain menu icons have bigger right margins than others. They are supposed to be equal like in versions of Wagtail before 2.10.

### Steps to Reproduce

1. Log in to the Wagtail admin
2. Note that the space (margins) between the Reports menu item and its icon is twice as much as the rest of the items. This also occurs with site settings menu entries, where the cog icon has more spacing before the label.

In the screenshot below, I used Firefox Developer Tools to highlight the box model dimensions in each menu item. Note that the first three menu items with the cog icon use `wagtail.contrib.sitesettings`, and the "Cache" menu item is from the `wagtailcache` package.

![Screenshot_20200805_133053](https://user-images.githubusercontent.com/17580077/89455669-e8540580-d71f-11ea-8c6d-857759fe107f.png)

### Further details

It appears that this is caused by ~~extra whitespace before the actual label text, and removing them manually using DevTools in the browser brought the labels vertically aligned with the others.~~ This behavior can be reproduced reliably in both Firefox and Chrome (or any Chromium-based) browser.

**Update:** The cause of this bug isn't caused by whitespace but rather inconsistent `margin-right` values in the CSS files. It turns out the right margins of `<svg>` icon elements that are used typically for single menu items without submenus are 0.25em. But the items that use icons through CSS (i.e. their parent `<a>` elements have `icon icon-some-action` classes) use 0.5em instead.

I think this bug was introduced in eed16e0.

---

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **yes**

### Technical details

* Python version: 3.8.5
* Django version: 3.0.9
* Wagtail version: 2.10-rc2
* Browser version: Firefox 79, Chrome 84

**Comment by allcaps** [comment]
Thank you for the issue.

How do you propose we should restore this? Can you create a pull request?

**Comment by acarasimon96** [comment]
This appears to be a pretty easy task for me, so yes, I can make a PR to resolve this.

Also, I just updated my above comment, so please do check it out.

**Comment by allcaps** [comment]
I was a bit surprised your code is a change to the font icon margin, and not the SVG icon positioning. Because SVG icons are introduced later, I expected menu items that use SVG icons are wrongly positioned. Not the font icons.

Turns out, font icons have variable width. Therefore they do not have consistent positioning. `label postion == icon width + margin`. The width of the icon from the icon font is variable! Conclusion: There is no way to claim that any icon font based menu item is the correct one. It is technically impossible to get consistent positioning with the font icons.

Proof, bread, bakery and reports are font icons.

![Screenshot 2020-08-07 at 09 50 24](https://user-images.githubusercontent.com/1969342/89623403-d3e54980-d894-11ea-92fc-734201fd4ae6.png)

We probably took a wide icon like in the bread menu item as reference to position the SVG's.

The only way out of this is to stop using font icons, and migrate all menu items to SVG. The SVG icons have a fixed ratio, and thus a fixed width.

I love your observation and the speed and quality of your ticket and PR. So, thank you!

All icon work is tracked in this 'meta ticket' https://github.com/wagtail/wagtail/issues/6107 . Contributions are welcome ;)

I'll add a reference to this issue. I don't think we should fiddle with font icon positioning. 
Just move to SVG and be done with it.

**Comment by gasman** [comment]
Closing as per #6298.
