### ISSUE TITLE
Userbar icon missing with certain 

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#6333]
The userbar icon doesn't display in certain FE configurations. e.g. 
![Screenshot 2020-08-18 at 10 45 13](https://user-images.githubusercontent.com/31622/90498250-f6eae580-e13f-11ea-9a8b-8007a575dfc9.png)

SVG icon change happened in #6125
The issue is the `.icon .wagtail-userbar-icon` combination. And the fact that `.icon` is fairly common for front-end.

For our build adding `fill: inherit;` to the `.wagtail-userbar-icon` rule solves the issue

**Comment by karranb** [comment]
Hi, if this issue is still available I'd like to work on it.

@zerolab, this issue is not happening on a clean `bakery demo`, it's probably caused for some custom styles or the `.icon` class as you suggested. 

Should I add `fill: inherit;` to `.wagtail-userbar-icon` class or should we avoid using `.icon` outside admin pages? Maybe this kind of conflict should be handled only when it happens by creating a custom rule like @zerolab did.

**Comment by zerolab** [comment]
Hey @karranb the better fix would be to avoid using `.icon` (which means you'd need to port its rules to `.wagtail-userbar-icon`). And it is still available so thank you for looking into this

**Comment by gasman** [comment]
Fixed in #6360
