### ISSUE TITLE
Inconsistent Handling of permission denied errors

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#6352]
There's a couple of methods we use for handling permission denied errors:

 - When I attempt to edit a page without edit permission, I am given a 403 "Permission denied" response
 - When I attempt to edit a snippet without edit permission, I am redirected to the dashboard with a "Sorry, you do not have permission to access this area." message at the top.

I think we should use the latter approach in general, but perhaps not always go back to the dashboard (ideally should go to a passed `next_url`/`back_url` so the user is sent back to the view they came from)

**Comment by gasman** [comment]
If we're doing everything correctly, a user should probably never encounter an actual permission denied error unless they're visiting the offending URL directly, as we ought to be hiding the links / buttons that would take them to those actions. And if they're visiting URLs directly, `next_url` is a moot point...

**Comment by samgans** [comment]
As I see, all the Page views have the PermissionDenied raised during the lack of permissions, so maybe it'll be better to change all that exceptions to wagtail.admin.auth.permission_denied function used in the snippets' views to make all admin pages more consistent. What do you think about this?

**Comment by gasman** [comment]
@samgans Yes, I think standardising on wagtail.admin.auth.permission_denied (rather than raising PermissionDenied directly) is the way to go. Additionally, if you find any links / actions within the admin that lead to a permission denied error (i.e. any way of reaching those views other than by visiting the URL directly), those ought to be fixed - e.g. by hiding the link for users without that permission.

**Comment by samgans** [comment]
Okay, I'm gonna fix this!
