### ISSUE TITLE
Primary keys are cast instead of relying on serialization

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#6512]
The javascript multi views for dashboard choosers are inconsistent with handling of primary keys.  In some places they cast to int and others they rely on serialization.

For example, the [images.views.multiple.add](https://github.com/wagtail/wagtail/blob/master/wagtail/images/views/multiple.py#L81) view uses both approaches in the same view.  It would be best to let Django handle serialization to avoid edge cases.

Similar to https://github.com/wagtail/wagtail/issues/6509 - I am happy to fix these today if you approve the issue.  Looks like there are two spots where this happens - document and image multiple add view.

[There is already a field in the tests that can be used for testing on the custom image and custom document tests](https://github.com/wagtail/wagtail/blob/master/wagtail/tests/customuser/fields.py#L11)

**Comment by gasman** [comment]
Addressed in #8985 so that we don't end up version-bumping this yet again (sorry for the lack of response!). It looks like fully supporting non-integer IDs on image models will require much more widespread changes (e.g. to URL routes), and I'm not clear on what the use case of this is - but if you're still interested in pursuing this, we're happy to look at any follow-up PRs.
