### ISSUE TITLE
Database error results in 500 error page

### ISSUE THREAD

**Issue by Shaffle1** [wagtail/wagtail#6524]
### Issue Summary

So my Wagtail sites are mostly in Russian, and fairly often editors forgot to change page's slug to English(when writing a title in Russian, js automatically generates slug for it, obviously in Russian). The issue is that some databases don't allow russian characters(in some tables or at all, for example A2 Shared Hosting, for some reason they set database's collation to latin1_swedish_ci, which doesn't allow Russian characters). When editors save the page, database returns an error, and they just get 500 error page... So maybe this is a feature request or a bug report, but I ran into this quite a lot of times. Could you make a notification when page is saved, that database returned an error or something went wrong? Or a CLI command that changes all of the database's collation to unicode? Or a settings that does not allow any other characters other than English in slug? So editors don't get confused every time they forgot to change the slug and save the page...

### Steps to Reproduce

1. Change database's collation to latin1_swedish_ci
2. Save the page with slug in Russian characters

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.8
* Django version: 3.0.8
* Wagtail version: 2.9.3
* Browser version: Chrome 84

**Comment by gasman** [comment]
Hi @Shaffle1,
The Django documentation at https://docs.djangoproject.com/en/3.1/ref/unicode/ documents the need to configure your database with Unicode support, and provides some pointers for doing this on MySQL. Since this is a system-level configuration issue, it's not really within the scope of Wagtail to handle this error.

Wagtail does provide a setting to disallow non-ASCII slugs: https://docs.wagtail.io/en/stable/reference/settings.html#unicode-page-slugs
