### ISSUE TITLE
Delete page in admin and get 404

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#6527]
### Issue Summary
When I delete the root page (a new project) I get a 404 in admin as after a delete Wagtail tries to go back to that page.

### Steps to Reproduce

1. start wagtail project
2. delete homepage that is made
3. get 404 page

I would expect to back to the three or see a screen that the page is deleted.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes 

### Technical details

* Wagtail version: 2.11.1

**Comment by gasman** [comment]
Thanks for the report @onno-timmerman! I can confirm that I'm seeing the same when I initiate the deletion from http://localhost:8000/admin/pages/3/ (but not http://localhost:8000/admin/pages/).

**Comment by Tijani-Dia** [comment]
I think that this happens for all type of pages as long as we initiate the deletion from `/admin/pages/<page_id>/`. It's due to the fact that when we request a page like `/admin/pages/<page_id>/`, the request comes with a parameter next which equals to `/admin/pages/<page_id/`. The [delete page view](https://github.com/wagtail/wagtail/blob/90a98f0cf5dd992960c7ea02b0a621664766bfb3/wagtail/admin/views/pages/delete.py#L13) uses this parameter [here](https://github.com/wagtail/wagtail/blob/90a98f0cf5dd992960c7ea02b0a621664766bfb3/wagtail/admin/views/pages/delete.py#L37-L39).
If we hover on the delete button from any page listing view, we can see an url like `/admin/pages/<page_id>/delete/?next=/admin/pages/<page_id/`. This means that wagtail will try to redirect us to the page we want to delete; which raises a 404 error.

As @gasman pointed, this error doesn't occur when we delete the page from its parent listing view. In that case the next parameter values to `/admin/pages/<parent_page_id/`.
From the parent page listing view, if we hover on the delete button of a child page,  we can see an url like `/admin/pages/<page_id>/delete/?next=/admin/pages/<parent_page_id/`, which means that we will be redirected to the parent page if we try to delete a child page from its parent page listing view.

So this avoid this error, I think we have to do a check [here](https://github.com/wagtail/wagtail/blob/90a98f0cf5dd992960c7ea02b0a621664766bfb3/wagtail/admin/wagtail_hooks.py#L211-L221) and update the `next_url` parameter.
We can:
-Either not add the new_url parameter to the url. To achieve it, we can do something like:
`if next_url:
            if next_url != reverse('wagtailadmin_admin_explore', args=[page.id]):
                url += '?' + urlencode({'next': next_url})` 
 In that case, the delete page view[(here)](https://github.com/wagtail/wagtail/blob/90a98f0cf5dd992960c7ea02b0a621664766bfb3/wagtail/admin/views/pages/delete.py#L39) redirects automatically to the parent page of the page we deleted.
-Or we can update the `new_url` parameter to redirect to another page.

What do you think about it?
