### ISSUE TITLE
Documention 2.0 bug

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#6604]
When you lookup wagtail documentation via google the documentation of 2.0 is first link you encounter. Then you enter the documentation and want to switch to latest. But the selector is broken you can't switch. Note that you should enter it on version 2.0 the documentation. It's not broken for later versions.

<img width="556" alt="Internationalisation — Wagtail 2 0 documentation 2020-12-02 09-25-47" src="https://user-images.githubusercontent.com/178425/100847709-70ed7300-3480-11eb-969c-f2016548f8c6.png">

**Comment by gasman** [comment]
Thanks for the report @onno-timmerman. Google indexing the old versions has been an annoyance for us - the platform we're using to host documentation (readthedocs.org) limits our ability to edit the files directly, so we probably can't fix the Javascript on those old versions without recreating everything on Github.

However, I've now managed to update https://docs.wagtail.io/robots.txt so that Google will hopefully stop indexing old versions and start returning the current one instead.
