### ISSUE TITLE
Userbar / edit bird broken

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#6657]
### Issue Summary

The userbar no longer opens since the JS was moved to `/client` (160d66ca93fb071c71785897eddf4d638a3c6d6c / 27133f957074635bf6efe461eff9f61d206d8443).

### Steps to Reproduce

1. Install bakerydemo in a virtualenv as per https://github.com/wagtail/bakerydemo#setup-with-virtualenv
2. `pip uninstall wagtail` then install a build of current Wagtail master with `pip install -e .`
3. Log in to http://localhost:8000/admin/
4. Visit http://localhost:8000/ , click on the bird icon in the bottom right; menu fails to appear

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.2
* Django version: 3.1.4
* Wagtail version: master fe79fbb48f807da0f10d23548019ff8b496afcf8
* Browser version: Chrome 87.0.4280.88

**Comment by kaedroho** [comment]
This seems to be caused by the `splitChunks` optimisation that is currently configured in Webpack. I think [this issue](https://github.com/webpack/webpack/issues/7230) might have something to do with it, but I'm really struggling to get my head around what split chunks is supposed to be doing with our configuration:

```javascript
    optimization: {
      splitChunks: {
        cacheGroups: {
          vendor: {
            name: getOutputPath('admin', 'vendor'),
            chunks: 'initial',
            minChunks: 2,
            reuseExistingChunk: true,
          },
        },
      },
    },
```

Switching to webpack's default chunking behaviour fixes this:

```javascript
    optimization: {
      splitChunks: {}
    },
```
