### ISSUE TITLE
Respect cache_until when retrieving embeds

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#6664]
[The oEmbed spec](https://oembed.com/) defines `cache_age` as 

> The suggested cache lifetime for this resource, in seconds. Consumers may choose to use this value or not.

My initial search hasn't pulled up any details about this being used.  It would be helpful if this was stored on the embed model.  This could be used in conjunction with `last_modified` for automatically refreshing stale content.

Since `last_modified` doesn't necessarily translate to when the data was fetched, there could ideally be an additional field that captures the fetch time.

This could also be combined into one DateTime field `cache_until` which would simplify queries and simply be set to the fetch time plus the cache age.

**Comment by thenewguy** [comment]
Will you accept a PR for this one?

**Comment by gasman** [comment]
@thenewguy Yes, sure!

**Comment by thenewguy** [comment]
@gasman Started PR here https://github.com/wagtail/wagtail/pull/6966/files

Have a preference on how stale embeds are handled?

- We can modify [get_embed](https://github.com/wagtail/wagtail/blob/e973c3d54421fffaacf6cdcfd8ef161671893e55/wagtail/embeds/embeds.py#L9) to check for stale embeds and attempt to delete & refetch in a transaction, serving the stale content if this fails
- We can emit a signal in [get_embed](https://github.com/wagtail/wagtail/blob/e973c3d54421fffaacf6cdcfd8ef161671893e55/wagtail/embeds/embeds.py#L9) when we fetch a stale embed
  - and perhaps return the first embed instance received from the handlers?
- We can add a db_index to the `cache_until` datetime and assume this is handled by the local project
  -  and perhaps include a management command that updates stale embeds in the database?

**Comment by thenewguy** [comment]
@gasman not to nag - just want to get this one closed up.  If you don't have a preference, I am leaning towards the last option with a management command so the refresh can happen outside of the request/response cycle.

**Comment by gasman** [comment]
Thanks @thenewguy! I'd be inclined to treat stale embeds in the same way as an embed that has never been fetched at all - if the re-fetch fails then I think it's reasonable enough to propagate that failure back to the end-user. From a quick look I think that can be done as a two-line change to `get_embed` - exclude embeds with a `cache_until` in the past [when fetching](https://github.com/wagtail/wagtail/blob/1408761e42f4f605f2d7fd627a7190d4f0b0402b/wagtail/embeds/embeds.py#L14), and change [the `get_or_create`](https://github.com/wagtail/wagtail/blob/1408761e42f4f605f2d7fd627a7190d4f0b0402b/wagtail/embeds/embeds.py#L50) to an update_or_create so that the stale embed is overwritten on successful fetch.

In the meantime, I'll go ahead and merge your PR as that all looks good to me.

**Comment by gasman** [comment]
Fixed in #7279
