### ISSUE TITLE
Editing a card, disassociates a card

### ISSUE THREAD

**Issue by jdatcmd** [wagtail/wagtail#6722]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Cards become unlinked from pages if card name changes.

### Steps to Reproduce

Create a card.
Create a page.
Add card to page.
Edit card title.
Save.
Page will no longer have card (because the title of the card changed).

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

This should be able to be fixed with proper foreign key constraints (ON UPDATE)

### Technical details

Latest Wagtail 2.11.3

**Comment by zerolab** [comment]
@jdatcmd what is a card in your case? can you provide some sample code?

**Comment by jdatcmd** [comment]
Dan,

I realize now that perhaps this is not a direct wagtail issue and that
"Cards" may be an extension?. In my admin interface, I have snippets, one
of those snippets is a "card" choice. You can see an example here:

https://www.commandprompt.com/services/

Cards are the listed services.

**Comment by gasman** [comment]
This sounds very much like a bug in the implementation of this card feature, whether that's a third-party add-on or custom code in your project, rather than in Wagtail itself. I can think of several possible ways this might be implemented (StreamField, inline panel, snippets), and none of them involve cards being associated with pages by name.
