### ISSUE TITLE
Remove "[default]" when site name is displayed using {% wagtail_site %}

### ISSUE THREAD

**Issue by DanielSwain** [wagtail/wagtail#6752]
In the wagatil admin, I always set up `login.html` and `home.html` templates and include the following:

```
{% load wagtailcore_tags %}

{% block branding_login %}
    Sign in to {% wagtail_site %}'s CMS
{% endblock %}
```
If I define a site as the default site, then it displays "[default]" after the site name when the above is used.  This looks clunky when, for example, someone logging in sees:  Sign in to Some City [default]'s CMS.  Of course it's the same thing when the site name is listed at the top of any admin page after a user is logged in.  My request is to prevent "[default]" from displaying when the site name is displayed using `{% wagtail_site %}`.  I could submit a PR for this request if @gasman is in agreement.

**Comment by gasman** [comment]
Hi @DanielSwain,

The `{% wagtail_site %}` tag isn't really intended for outputting the site name directly onto the template - the intention is that you use `{% wagtail_site as current_site %}` to retrieve the current site as [a Site object instance](https://docs.wagtail.io/en/stable/reference/pages/model_reference.html#site). Returning an object rather than just a site name means that it can be used for more general purposes, such as `{% if page == current_site.root_url %}`. You can use `{{ current_site.site_name }}` to display the site name without the "[default]" suffix.

Using `{% wagtail_site %}` directly means that you're actually seeing the `str(...)` representation of the Site object, which includes the "[default]" label.

I wouldn't be averse to `{% wagtail_site %}` returning just the human-readable site name, but I don't think there's going to be a way of doing that without causing unwanted side effects to code that relies on it returning a Site object, or changing the string representation at the model level (which would be a negative change, because you _do_ want to see the "[default]" label when you're configuring site records in the admin).
