### ISSUE TITLE
Allow relative urls in URLBlock

### ISSUE THREAD

**Issue by jkevingutierrez** [wagtail/wagtail#6808]
### Is your proposal related to a problem?

URLBlock doesn't allow to insert relative URLs.

As per #3141 there isn't any block for adding external links and internal links. As a temp solution, it would be good to allow relative URLs (`/internal-url/` in the URLBlock.

![image](https://user-images.githubusercontent.com/6220055/107799291-3f6c1000-6d2b-11eb-88c4-dd5c56f2a4aa.png)

### Describe the solution you'd like

it would be good to allow relative URLs in the URLBlock. I know that we can customize the Validators, but it would be good to have that by default in Wagtail.

**Comment by thibaudcolas** [comment]
Hi @jkevingutierrez, this is because URLBlock uses Django’s URLField. I’m not sure if this is defined explicitly anywhere but I believe there’s a strong association in people’s minds that "URLBlock means URLField". If we had a block that supported different validation rules from URLField, presumably we should call it something else?

**Comment by thibaudcolas** [comment]
👋 I’m going to close this now based on my last comment and the lack of activity. I believe `URLBlock` is too strongly tied to `URLField` to warrant any kind of change. We could introduce another block, but this feels like the type of thing where we’d expect a clear, specific proposal based on pre-existing patterns.
