### ISSUE TITLE
Update StreamField Screenshot in Editor's Guide

### ISSUE THREAD

**Issue by kbehlers** [wagtail/wagtail#6925]
### Pertinent section of the Wagtail docs 

https://docs.wagtail.io/en/stable/editor_manual/new_pages/creating_body_content.html#streamfield

### Details

The screenshot for StreamField seems to precede [the 2.7 release ](https://github.com/wagtail/wagtail/blob/16c34fd6e155a73fd5f148b2ef647e0b9dbacc44/docs/releases/2.7.rst#improved-streamfield-design)

It is possible that the[ release notes screenshot ](https://github.com/wagtail/wagtail/blob/16c34fd6e155a73fd5f148b2ef647e0b9dbacc44/docs/_static/images/releasenotes_2_7_streamfield_styles.png)could be used directly as the replacement.

**Comment by vladutmd** [comment]
I've just completed that but have a quick question before creating a pull request. The forked version I have is for the latest version, which includes the following sentence on that documentation page:

> You can duplicate a block (including the content) using the button towards the top right corner of an existing block.

In the documentation for the stable version that point is not yet there. Do we want new screenshots for the latest version or stable version or both? I ask because in order to have it for the latest version the screenshot should also include the duplicate button.

Vlad

**Comment by gasman** [comment]
Hi @vladutmd,
Please use the latest version (with the 'duplicate' button) - the 'stable' version of the docs will only be updated in the case of serious errors, so any pull request you make now will be part of the upcoming (2.13) release which does include that feature.
