### ISSUE TITLE
The 'link-external' icon does not render in the CMS

### ISSUE THREAD

**Issue by eyemyth** [wagtail/wagtail#6929]
### Issue Summary

The 'link-external' icon does not render in the CMS. The effect is the same whether the block is configured using a keyword argument or a `Meta` property.

### Steps to Reproduce

Start a new wagtail project as described in the documentation.

Replace the contents of `mysite/home/models.py` with this code:

    from wagtail.admin.edit_handlers import StreamFieldPanel
    from wagtail.core import blocks
    from wagtail.core.fields import StreamField
    from wagtail.core.models import Page
    from wagtail.images.blocks import ImageChooserBlock

    class PersonBlock(blocks.StructBlock):
        first_name = blocks.CharBlock()
        surname = blocks.CharBlock()
        photo = ImageChooserBlock(required=False)
        biography = blocks.RichTextBlock()

        class Meta:
            icon = 'user'

    class BrokenPersonBlock(blocks.StructBlock):
        first_name = blocks.CharBlock()
        surname = blocks.CharBlock()
        photo = ImageChooserBlock(required=False)
        biography = blocks.RichTextBlock()

        class Meta:
            icon = 'link-external'

    class HomePage(Page):
        person = StreamField(
            [
                ('working_person', PersonBlock()),
                ('broken_person', BrokenPersonBlock()),
                (
                    'also_broken',
                    blocks.StructBlock(
                        [
                            ('first_name', blocks.CharBlock()),
                            ('surname', blocks.CharBlock()),
                            ('photo', ImageChooserBlock(required=False)),
                            ('biography', blocks.RichTextBlock()),
                        ],
                        icon='link-external'
                    )
                ),
            ],
            blank=True,
        )

        content_panels = Page.content_panels + [
            StreamFieldPanel('person'),
        ]

Make and apply database migrations and create a user, then load up the CMS in a browser. Edit the Home page and note that the 'Broken person' block is missing its icon, as is the 'Also broken' block.

I tested this with a handful of other icons from the style guide, but all of the others worked as expected.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.8.7
* Django version: 3.1.7
* Wagtail version: 2.12.3
* Browser version: Safari 14, Firefox 86, Chrome 89

**Comment by ababic** [comment]
@eyemyth Maybe I'm missing something, but where does Wagtail imply that there is a `link-external` class/icon? Why would you expect this would work?

**Comment by gasman** [comment]
@ababic It's listed in the style guide:
https://github.com/wagtail/wagtail/blob/ee71bd3d07d1e70b335bc68e45f5a301613e568f/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html#L848

I can confirm it doesn't show up when used as a StreamField icon, testing against current main and bakerydemo. (It does work as a ModelAdmin `menu_icon` though...)

**Comment by ababic** [comment]
@gasman Ah, I see. This must be a recent addition, as I don't think I've seen it before. Would be handy to have an up-to-date list in the docs somewhere.

**Comment by Stormheg** [comment]
@ababic an icon list was requested as part of [#6028 (comment)](https://github.com/wagtail/wagtail/pull/6028/files#r590144224 )

**Comment by Stormheg** [comment]
After investigating this, it looks like StreamField is still using an icon font (which we are planning on phasing out, see https://github.com/wagtail/wagtail/issues/6107).

The `link-external` icon was introduced last year as an SVG icon in https://github.com/wagtail/wagtail/commit/b30aa2dc3fe07408421a606acb27d6bd5c5a61d3 along with a few others. The icon font was not updated and does not contain the `link-external` icon.

The styleguide and model admin both use SVG versions of the icon. Which is why they do work there.

We can:

1. Update the icon font to include the missing icons. This would be a quick fix.
2. Update StreamField (and other places still using the icon font) to use SVG icons. We are going to end up doing this anyway in the next few months...

If we're going to update the icon font to include the missing icons we can use [Icomoon](https://icomoon.io/) with the [`wagtail-icomoon.json`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/static_src/wagtailadmin/fonts/wagtail-icomoon.json) file.

**Comment by thibaudcolas** [comment]
This is no longer relevant as of quite a few versions ago (we now have the opposite issue of StreamField icons no longer supporting the icon font, see #8533).
