### ISSUE TITLE
JSONField for BaseLogEntry data_json

### ISSUE THREAD

**Issue by m5seppal** [wagtail/wagtail#6942]
This issue is very much related to the issue https://github.com/wagtail/wagtail/issues/5280 which is requesting JSONField for Blocks. I would extend that request to also cover BaseLogEntry data_json, so that it would be using JSONField as well.

My proposed solution and rationale would be pretty much the same as explained in https://github.com/wagtail/wagtail/issues/5280:

_"I would like to propose a configuration option to use JSONField instead of text field which will allow the data to be stored as JSON directly._

_It will also enable user to leverage query options available for the JSONField."_

JSONField is now supported by Django:
https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.JSONField

The current implementation is based on TextField which strangely stores empty values differently depending on the action:
<img width="269" alt="Screenshot 2021-03-22 at 20 07 14" src="https://user-images.githubusercontent.com/22469162/112037883-e2921f80-8b4a-11eb-96a9-00c51a7ec1e3.png">

Not really a huge issue but would make sense to use the same empty value, for example {}, no matter whether the implementation is based on TextField or JSONField.

**Comment by zerolab** [comment]
Hey @m5seppal, thank you for this!
I would absolutely love to switch to JSONFIeld in both cases. We cannot yet since JSONField is a Postgres backend only feature for Django < 3.1.

**Comment by m5seppal** [comment]
Could we do it so that it's configuration based and defaults to TextField for now so people using Django < 3.1. won't have to do anything?

**Comment by gasman** [comment]
@m5seppal I don't think there's any good way to make that work with Django migrations - in order to change the field from one type to another, you need a migration inside the wagtail.core app. If we leave that choice up to the user, then it's not possible to ship that migration as part of a Wagtail release - and if the migrations we ship with Wagtail aren't consistent with the expected database state (as determined by the model definitions), you end up in a situation where a user running `./manage.py makemigrations` ends up creating spurious 'auto' migrations inside the Wagtail package.

**Comment by m5seppal** [comment]
Okay makes sense.  I guess the change will be made in the future when there is no need to support Django versions < 3.1.
