### ISSUE TITLE
Refactor `Page.serve_preview()` and `Page.serve()`

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#6987]
The [recipie](https://docs.wagtail.io/en/v2.12.3/reference/pages/model_recipes.html) for custom `serve()` and `serve_preview()` results with a page preview that doesn't set `request.is_preview = True` or `patch_cache_control(response, private=True)`

The way it is currently written, `serve_preview()` must be replaced if you have a custom `serve()` method because `super().serve_preview(request, mode_name)` will not call the custom `serve()` method.  This isn't very DRY and means that at some point in the future an implementation's custom `serve_preview()` methods are likely to break.

It would be awesome if there was a way to use `super().serve_preview(request, mode_name)` in conjunction with a custom `serve_preview()` that handles page specific logic without bypassing the custom page `serve()` method.

The fix could be as simple as optionally passing the `serve()` method to the super method like:

```
    def serve_preview(self, request, mode_name, serve=None):
        request.is_preview = True
        serve = serve or self.serve
        response = serve(request)
        patch_cache_control(response, private=True)
        return response
```

or it could be refactored into three methods to replace the functionality currently provided like:

```
def serve_preview(self, request, mode_name):
	request = self.process_preview_request(request, mode_name)
	response = self.get_preview_response(request, mode_name)
	return self.process_preview_response(request, mode_name, response)

def process_preview_request(request, mode_name):
	request.is_preview = True
	return request

def get_preview_response(request, mode_name):
	return self.serve(request)

def process_preview_response(request, mode_name, response):
	patch_cache_control(response, private=True)
	return response
```

This is probably the optimal case and then custom pages would override `process_preview_request()`, `get_preview_response()` and `process_preview_response()` as needed instead of `serve_preview()`

**Comment by rgs258** [comment]
hmmmm. I seem to be up against this too. What's really weird is that I already had code for serve_preview() that needed to run alongside code in serve() that handled previews.

I'm not sure yet what I need to do to fix our app, but this ticket seems to be on topic.

**Comment by laymonage** [comment]
We refactored how `serve_preview()` works in Wagtail 4.0 as we extracted preview-related methods to a [`PreviewableMixin`](https://github.com/wagtail/wagtail/blob/f77229da2a0dc93520b9083552d312217382de1a/wagtail/models/__init__.py#L566) so that it works with non-page models as well.

The `is_preview` and `patch_cache_control` stuff is now set in the `Handler` in `make_preview_request()`:

https://github.com/wagtail/wagtail/blob/f77229da2a0dc93520b9083552d312217382de1a/wagtail/models/__init__.py#L599-L607

Could you revisit this and tell us if you're happy with the changes or if there are other improvements we can make in this area? Thanks!

**Comment by gasman** [comment]
Closing due to lack of updates - assuming the changes in 4.0 have addressed this.
