### ISSUE TITLE
StreamValue no longer sliceable

### ISSUE THREAD

**Issue by alxbridge** [wagtail/wagtail#7012]
### Issue Summary

Following an upgrade from Wagtail 2.10 to 2.12.3, it appears that `StreamValue` items are no longer sliceable.

e.g. 
```django
{% for footer in footernav|slice:":2" %}
  {% include_block footer %}
{% endfor %}
```

would previously render the first 2 blocks in `footernav`, but now renders `None` twice instead.

(This can be worked around by first casting the `StreamValue` with `list()`.)

### Steps to Reproduce

1. Pass a `StreamValue` variable into a request's context
2. Use the `|slice` filter on the variable
3. Check the resulting values

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: No

### Technical details

* Python version: 3.8.2
* Django version: 3.0.13
* Wagtail version: 2.12.3
* Browser version: Any

**Comment by gasman** [comment]
Thanks @alxbridge!
I don't think this has ever worked - I suspect that the pre-2.12 behaviour of the above code was to output the complete unsliced list, so we've basically traded one bit of undefined behaviour for another. That's what I'm seeing when I test against bakerydemo, changing the `{{ page.body }}` in blog_page.html to

                {% for block in page.body|slice:":2" %}
                    {% include_block block %}
                {% endfor %}

This is because the `|slice` filter [returns the original value in the case of a TypeError](https://github.com/django/django/blob/e3e2276e6fe6fd77e4fbdeeb2a287288d31de3bb/django/template/defaultfilters.py#L600), and [the old implementation of `StreamValue.__getitem__`](https://github.com/wagtail/wagtail/blob/stable/2.10.x/wagtail/core/blocks/stream_block.py#L386) tries looking up the index in the `_bound_blocks` dict, which will always fail with `TypeError: unhashable type` when passed a slice object.

Hopefully this should be a pretty quick thing to fix though...

**Comment by gasman** [comment]
PR: https://github.com/wagtail/wagtail/pull/7013

**Comment by alxbridge** [comment]
Thanks @gasman : that makes sense about the pre-2.12 behaviour - I can see that's the case now.

I've tested your PR and it works well for the example I gave above.
