### ISSUE TITLE
Decorating RoutablePageMixin routes with "route_path" instead of "route" (path vs re_path)

### ISSUE THREAD

**Issue by junctionapps** [wagtail/wagtail#7031]
### Is your proposal related to a problem?

In migrating a Django application to a Wagtail app, I've been using RoutablePageMixin in some cases and wanting to use the newer Django django.urls.path patterns instead of the re_path to make copying the url patterns from the original application's urls.py a bit easier.

I've mentally switched away from the regular expressions for url matching and am struggling going back to using the regex's.

### Describe the solution you'd like

I'd like to decorate the route with something like `@route_path` or have `route()` in `routable_page/models.py` have a check to see if the pattern is a regular expression or not and (RegexPattern or RoutePattern). 

### Describe alternatives you've considered
For now I've created a custom `route_path` function in `/custom/routable_pages/models.py` that appends a `path` to _routablepage_routes instead of `re_path` (as in stock). It looks like:

/custom/routable_page/models.py
```python
from django.urls import path, re_path

_custom_creation_counter = 0

def route_path(pattern, name=None):
    """
    Adds a path more like the Django 2.0+ Url Dispatcher rules
    """
    def decorator(view_func):
        global _custom_creation_counter
        _custom_creation_counter += 1
        # Make sure page has _routablepage_routes attribute
        if not hasattr(view_func, '_routablepage_routes'):
            view_func._routablepage_routes = []

            view_func._routablepage_routes.append((
                path(pattern, view_func, name=(name or view_func.__name__)),
                _custom_creation_counter,
            ))
        return view_func
    return decorator

    # a copy of the stock route follows right below, included in this location for my own sanity in the global scope
``` 

and decorate the routable functions with `@route_path` which seems to be working so far, but just getting into it and wondering if I'm going to get burned doing things this way.

/subscribers/models.py
```python
from myprojectname.custom.routable_page.models import route_path

class SubscribePage(RoutablePageMixin, Page):

    ....

    @route_path("subscribe/")
    def subscribe(self, request, *args, **kwargs):
        """
        Confirm the form is submitted correctly, and conditionally add
        the subscriber to the list
        """
        from subscribers.forms import SubscribeForm
        if request.method == 'POST':
            form = SubscribeForm(request.POST)
            if form.is_valid():
                form_submission = form.save(commit=False)
                ....
```

### Additional context
Obviously, the 'try it and see' approach applies here, but wondering if there is a deeper design decision in Wagtail which would suggest to not take this direction.

**Comment by Tijani-Dia** [comment]
I think that it would be more beginner-friendly too.
I tried to implement the second solution you proposed where  `route()` in `routable_page/models.py` checks to see if the pattern is a regular expression or not.

> wondering if there is a deeper design decision in Wagtail which would suggest to not take this direction.

Wondering too.

**Comment by gasman** [comment]
I don't think there's a deep design decision behind it - it's just that RoutablePageMixin was created before an alternative to regexp-based paths existed, and hasn't been redesigned since then...

I'd definitely prefer using two different decorators here, rather than trying to 'guess' the type of pattern with heuristics - there's too much risk of it making the wrong choice (is `/foo.bar/` a regexp or not?) and producing unexpected results that are hard to troubleshoot, especially for newer developers who started learning Django after the switch and skipped over learning about regexps. [The relevant code in Django](https://github.com/django/django/blob/f9f6bd63c98dc2f01412887f4a98dbfdab363fdf/django/urls/resolvers.py#L285) is only used to output a warning, so they can get away with just detecting the most obvious signs of a regexp - I don't think that's reliable enough to use in actual routing logic.
