### ISSUE TITLE
One click to view changes diff between revision submitted to moderation queue and live revision

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#7098]
We have been using the moderation queue workflows and it takes a lot of time to get to the history diff view to see the actual changes compared against the live revision - also, I could be mistaken but I believe the history view only shows against the previous revision instead of the live revision.  Often times this is easier to use the diff than directly jumping to the preview - or for spelling corrections and other one word fixes the diff is just more useful.  It would be very helpful if there was a one click "view changes" button to the "Awaiting your review" section that pulled up this visual diff against the live revision.

Currently, you have to click "edit", wait for the page to load, "history", wait for the page to load, find the correct draft, click "compare with previous version", wait for the page to load, then you have to click "edit this page", wait for the page to load, click "preview" to verify the change, wait for the page to load, then "approve and publish".

We are using Wagtail 2.11 but I didn't see any improvements here in the 2.12 notes.  This really adds a lot of time to the moderation process.  Anything to simplify it would be a big bonus

**Comment by jacobtoppm** [comment]
Hi @thenewguy , thanks for raising this! This sounds like a really good idea, and I'd be happy to review a PR that adds this, if you'd be up for making one. Alternatively I can look into adding this at some point.

**Comment by rgs258** [comment]
Hello folks, this same concern has come up at WRDS and we would love to see this issue move forward. @jacobtoppm , can you please let me know if there's anything that we can do to help with this?

**Comment by rgs258** [comment]
Hi Sage, that's great and I'll share this with out content moderators!

Since we can have the links there, do you think it'd be possible to also add them to the listings on the CMS landing page?
![image](https://user-images.githubusercontent.com/482540/224369102-44a9b72d-f294-408c-9682-5a575f6fdbf3.png)

**Comment by sarahcstringer** [comment]
My team has also discussed wanting this feature recently, specifically on the page's history to compare revisions with the live version of a page. I created [this PR](https://github.com/wagtail/wagtail/pull/6701) a long time ago but then closed it because I realized you could get the diff by editing the URL; but, my team has recently also been mentioning that a button would be good. This might be off topic because this is more about the moderation flow, though.
