### ISSUE TITLE
UI/UX for the navigation between tree page is confusing 

### ISSUE THREAD

**Issue by Ermite-bossu** [wagtail/wagtail#7149]
Navigation in the pages are pretty counter-intuitive in term of UX, when you want to go on subpages you have to click on the arrow at the right of the bloc instead of the page name.
It would have been more logical to be redirected to the subpages when clicking on the name of the page and just keep the edit button to modify it.

![Capture d’écran 2021-05-04 à 10 59 52](https://user-images.githubusercontent.com/83450946/116982432-15dad900-acc9-11eb-9ea2-3f4f24761fc7.png)

**Comment by gasman** [comment]
Thanks for the comment @Ermite-bossu! I think it's a bit more complicated than that though... for pages that conventionally don't have child pages (such as news articles), it would be even more unintuitive for that link to take you to the list of subpages (which would be an empty listing saying "no pages have been created here"). I think the "expected" behaviour depends on whether you think of the page type as an 'index' page or an 'article' page - and, of course, changing the behaviour depending on the type of page would be more confusing again...

A couple of more radical solutions I've thought about:
* for 'index' pages, make it possible to manage/navigate the list of child pages from the 'edit' view, so if you do click that link, you're not in the "wrong" place
* make 'index' pages and articles meaningfully different in the listing view, so that it doesn't seem weird for the title links to go to different places

**Comment by Ermite-bossu** [comment]
Thanks @gasman for the explanation and indeed it seems more difficult than I thought. Maybe it’s because I’m an editor with wagtail and I still have noob vision of the navigation, but if I take the exemple of the navigation in file system like MacOS finder / Windows file explorer, as long as the item you click on is a folder, you will go down in the tree until it’s just a file, in which case the file will open.
And the other point which is confusing is that when you navigate in the side menu, when you clicking on the page name, you open the index page (same as the arrow) and not the page itself (witch you can only open with the edit button).

As for the solutions you’ve thought about, the second one would be perfect to know what kind of pages you have to deal with ! Maybe I can work on a visual exemple on Figma and propose it to you?

![Capture d’écran 2021-05-05 à 12 22 55](https://user-images.githubusercontent.com/83450946/117128124-4b50f680-ad9d-11eb-849c-032e615a960c.png)

**Comment by NotANormalNerd** [comment]
Hey @Ermite-bossu 

I encountered the same thing when using the Wagtail. If you have access to the deployment or the source code you can change `templates/wagtailadmin/pages/listing/_page_title_explore.html`

```
{% if page.is_navigable %}
        <a href="{% url 'wagtailadmin_explore' page.id %}" title="{% trans 'Explore this page' %}">{{ page.get_admin_display_title }}</a>
{% else %}
        {{ page.get_admin_display_title }}
{% endif %}
```

This way you will get the behaviour we all know from the explorer, but only in explorer view.

**Comment by thibaudcolas** [comment]
@gavin-bailey no, there is no plan to change this at this time. See [this explanation](https://github.com/wagtail/wagtail/issues/7149#issuecomment-831819953) as to why it’s not that clear cut what to do with this.

**Comment by thibaudcolas** [comment]
Based on the recent [universal listings discussion](https://github.com/wagtail/wagtail/discussions/10446), I believe it’s clear we’re happy with the page title being an "Edit" link. It’s also much less confusing than it used to be in Wagtail 5.2, because the "Edit" button is much further away from the title link. So I’ll close this now.
