### ISSUE TITLE
TextField widget allows horizontal resize instead of vertical

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/wagtail#7210]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The admin widget for `TextField` allows vertical resize instead of vertical.

### Steps to Reproduce

1. Setup the Wagtail Bakerydemo (e.g. with https://github.com/wagtail/docker-wagtail-develop)
2. Navigate to the "Gallery" page (ID = 70) -- http://localhost:8000/admin/pages/70/edit/. 
3. Try to resize the "Introduction" field

* Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Instead of the horizontal resizing I would expect to be able to vertically resize. 

Inspecting the field, you will find: `style="overflow: hidden; overflow-wrap: break-word; resize: horizontal; height: 75px;"`

Manually changing the `resize: horizontal` to `resize: vertical` creates the expected behaviour. 

https://user-images.githubusercontent.com/24797493/119425723-bdda3580-bcbc-11eb-981d-0d15cb62971f.mov

https://user-images.githubusercontent.com/24797493/119425784-dcd8c780-bcbc-11eb-9792-2dcb7ffe03fb.mov

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / ~~no~~)

### Technical details

* Python version: Run `python --version`. -> Python 3.7.10
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`. -> Django 3.1.11
* Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`. -> `master`
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out. -- Firefox 88 (macOS)

**Comment by tbrlpld** [comment]
I tried to find the culprit in the Wagtail codebase but could not figure out where this is being defined. I am wondering if this is some default in a (React) dependency.

**Comment by gasman** [comment]
Thanks for the report @tbrlpld! I don't recall noticing this before, but a quick check shows that it's been like this since at least 2.11.

This style is being defined in [jquery.autosize.js](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/static_src/wagtailadmin/js/vendor/jquery.autosize.js#L37-L41), which hasn't been changed for years (if ever). I wonder if perhaps browsers have recently started enabling textarea resizing by default, making this bit of weirdness apparent - before then, all resizing would have been handled automatically by this jquery plugin.

**Comment by CharString** [comment]
This is a temporary workaround

```python
# wagtail_hooks.py in one of your installed apps.
from wagtail.core import hooks


@hooks.register("insert_global_admin_css", order=100)
def global_admin_css():
    return "<style>textarea {resize:vertical !important}</style>"
```

**Comment by lb-** [comment]
<img width="1736" alt="Screen Shot 2022-09-08 at 10 29 46 pm" src="https://user-images.githubusercontent.com/1396140/189122027-7b668292-dfd2-4f3c-8d95-651caa1c7e4a.png">

Confirming this is still an issue in Wagtail 4.0

**Comment by Dorothy2020** [comment]
Can I work on this issue @thibaudcolas since there is no PR

**Comment by lb-** [comment]
@Dorothy2020  go for it, I think we would probably want to add a new vendor overrides file in `client/scss/overrides` similar in purpose to `client/scss/overrides/_vendor.datetimepicker.scss`.

We will want to ensure the css is specific to the jquery widget classes only ideally so we do not block all text area elements globally from allowing this.

Be sure to then import it in `client/scss/core.scss`.

**Comment by AnishaSingh0118** [comment]
@lb- @tbrlpld I have not seen any update on this issue so i would like to take up this issue as I have an idea to resolve it.

**Comment by lb-** [comment]
Thanks @AnishaSingh0118 - I see you have a PR up & appreciate you checking

**Comment by AnishaSingh0118** [comment]
> Thanks @AnishaSingh0118 - I see you have a PR up & appreciate you checking

Thank you for responding. 
It's my pleasure :)

**Comment by thibaudcolas** [comment]
I’ve marked #9651 as a fix for this, and it seems to me like an improvement to the status quo, however I don’t think I understand the bug report as stated here.

Our TextField implementation uses jQuery’s autosize widget, which is meant to control the height of the textarea on users’ behalf. We can allow both horizontal and vertical resizing but ultimately vertical resizing will be updated by the autosize widget upon the content starting to overflow.

**Comment by gasman** [comment]
@thibaudcolas My impression is that the intent of the code in jquery.autosize.js was to disable the ability to vertically resize the textarea by dragging, so that vertical sizing was entirely under the control of the plugin. As I said in https://github.com/wagtail/wagtail/issues/7210#issuecomment-847705405, I suspect that at some point browsers switched the default style of `<textarea>` from being fixed size (in which case the disabling in jquery.autosize.js had no effect) to being drag-to-resize in both directions (in which case jquery.autosize.js changed it to being draggable horizontally only).

If there's any doubt about whether this is an actual bugfix, it should probably be rolled back from stable/4.1.x.

**Comment by tbrlpld** [comment]
@thibaudcolas My confusion with the demonstrated behaviour is that horizontal resizing works while vertical does not. This is because the field is already fairly wide but does not have much vertical space. To me it would feel more natural to be able to resize vertically, but that may be a matter of taste. I think not being able to manually resize and only have the field automatically resize would also work.

**Comment by gasman** [comment]
Reopening as I believe this has been misdiagnosed in #9651. The jquery.autosize plugin (in its original version) intentionally disables manual vertical resizing so that the element height is solely under the control of the auto-size logic. Taking out this step means that resizing the box and then editing the text causes it to suddenly jump to its natural height, which I think is just as undesirable as the horizontal-only resize control.

There's a potential "best of both worlds" solution where we keep the vertical resizing control in place, and make the manually-set height "sticky" so that the autosize behaviour is only reintroduced when the text overflows that new height. However, in the absence of such an implementation the best alternative is to disable manual resizing completely - and in fact I'd argue that this is more in line with our long-term vision where the form is visualised as a Dropbox-paper-style single flowing document, rather than a series of discrete boxes.

I'll roll this back from the 4.1.x branch, but leave it in place on main and open an alternative PR for consideration.

**Comment by thibaudcolas** [comment]
@gasman personally I’m happy with either allowing both directions of manual resizing (what I’ve merged) or none (your PR).

The point in allowing vertical resizing in addition to horizontal is that people can make a field narrower as needed, and also change the height of the field so they can still see the whole content, without having to press "Enter" in the field to let the auto-size kick in. Preventing the auto-size logic from kicking in when the field is already big enough would be nice but certainly not a blocker to supporting this.
