### ISSUE TITLE
User section showing in wrong part of menu after upgrading to 2.13.x

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail#7233]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Since upgrading from 2.12.4, the admin user avatar and sub-menu shows in the main part of the menu with the previous area blank:

![image](https://user-images.githubusercontent.com/72310199/120491002-2d38df00-c3b9-11eb-89d2-b0d10e35e1cc.png)

### Steps to Reproduce

The error doesn't show on my dev server (Windows) but shows after upgrade to 2.13.x on the prod server (Ubuntu)

The user menu is expanded always, the expected container for the user area is left blank.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.8.5
* Django version: 3.2
* Wagtail version: 2.13.1
* Browser version: Replicated on latest version of Chrome/Firefox & Edge.

**Comment by gasman** [comment]
Hi @enzedonline,
If this is only happening on the production server, then it's very likely this is a deployment issue (such as failing to run `./manage.py collectstatic` after upgrading) rather than a Wagtail bug. You may be able to get more help on [our support channels](https://docs.wagtail.io/en/stable/support.html).
