### ISSUE TITLE
Streamfield can't render (show) own content blocks since version 2.13 in some cases

### ISSUE THREAD

**Issue by bestasholli** [wagtail/wagtail#7278]
### Issue Summary

Wagtail  >2.13 StreamField performance and functionality updates caused issue with stream-fields with large amount of blocks (content). Streamfield field stays collapsed and can't open. This only happens in streamfields with lots of content (some other pages are working properly, one of the pages that is not working contains content of  54904 chars). Also, the problem happens in the production environment only, locally it looks to work just fine. Errors seems to be from some javascript methods that "are" undefined. See the methods causing trouble attached below:

<img width="746" alt="Screenshot 2021-06-22" src="https://user-images.githubusercontent.com/49398841/123092700-0fe0b900-d42b-11eb-80e5-9823dd80c2ea.png">

### Steps to Reproduce

1. Add streamfield to a page
2. Use streamfield features like richtext or rawhtml to insert lots of content.
3. Publish it
4. Come back to edit the page
5. Streamfield content won't render

* I have confirmed that this issue has only happened since the 12.3 wagtail updates

### Technical details

* Python version: 3.8.5
* Django version: 3.1.7
* Wagtail version: 2.13, 2.13.1, 2.13.2
* Browser version: Chrome 91

**Comment by gasman** [comment]
Hi @bestasholli - thanks for the report. However, this doesn't give us enough detail to troubleshoot the issue. Usually, "...is not defined" JS errors would be a sign that you're running outdated Javascript from the previous version, perhaps because you didn't run `./manage.py collectstatic` after upgrading or because you have the old files cached - the fact that this is only happening in production and not locally would back this up.

If you're able to find a set of steps starting from a clean Wagtail installation that reproduces this problem, we'll be happy to reopen and investigate further.
