### ISSUE TITLE
Comment system stops publication of some entries with "The page could not be saved due to validation errors" message

### ISSUE THREAD

**Issue by bva-mike** [wagtail/wagtail#7297]
### Issue Summary

I can no longer publish some entries in wagtail which have a comment attached, i get a red banner at the top stating "The page could not be saved due to validation errors", but the validation error(s) are not highlighted anywhere on the entry. If i turn off the commenting system with `WAGTAILADMIN_COMMENTS_ENABLED = False` the issue no longer occurs and all effected entries are now able to be published.

Hopefully some of the below notes will help tracking the issue down:

- The issue doesn't occur for all entries of the same model type, some entries publish fine with comments still attached.
- An example entry i have that doesn't publish, has a comment attached to a RichTextBlock within StreamfieldBlock.
- If i move the comment to another entry (changing `page_id` in the `wagtailcore_comment` database table), the problematic entry can now be published, and the entry where the comment was moved to can also still be published without any issues.
- If i move the comment back again to the original entry, that entry can no longer be published again citing the same initial validation error.
- Our build server will have bumped the version of Wagtail from 2.13 to 2.13.1, then 2.13.2 quite recently, which is when the issue started appearing (within the last few weeks).

### Technical details

* Python version: 3.6.5
* Django version: 3.2.4
* Wagtail version: 2.13.2

**Comment by zerolab** [comment]
Hey @bva-mike, would you be able to narrow this down in which Wagtail version it happens. ie. is it between 2.13 and 2.13.2 or, 2.13.1 and 2.13.2?

**Comment by bva-mike** [comment]
hey @zerolab i'm pretty sure it happened between 2.13 & 2.13.1

**Comment by jacobtoppm** [comment]
Hey @bva-mike , thanks for raising this! This is a bit of a mysterious one. To help narrow it down:
- Have any of the affected comments been added programatically, rather than through the Wagtail admin?
- Do all of the affected comments have a `contentpath` and non-empty `text`?
- Is the issue with users saving pages with their own comments, or with other people's comments?
I did see a similar issue on 2.13rc2, but it should have been addressed there.

**Comment by bva-mike** [comment]
Hey @jacobtoppm 

- All the comments have been added through WT admin
- Yeah looking at the table it _seems_ ok (attached screenshot)
- Ah! A step further: it seems the user who made the comment can publish the page and/or resolve the comment and publish, but other users can do neither

![image](https://user-images.githubusercontent.com/51820538/123936578-3653a680-d98d-11eb-867a-eb03e0a89303.png)

**Comment by jacobtoppm** [comment]
I can't reproduce this locally, I'm afraid - I've tried just now with two users. Would you mind double checking that you're definitely on 2.13.2, rather a pre-release version, as this definitely was an issue with the release candidates?

Otherwise, do you have any custom forms or edit handlers on the affected pages?

**Comment by bva-mike** [comment]
hey @jacobtoppm yeah i think we're definitely on 2.13.2 im just going on what the version number is in the Admin UI though, screenshot below.



![image](https://user-images.githubusercontent.com/51820538/124118332-1ee9eb80-da69-11eb-8ec1-4a4d0f080a80.png)


we do have a some AutoCompleteSelectMultipleWidget's on most page type models:

![image](https://user-images.githubusercontent.com/51820538/124118903-c535f100-da69-11eb-91f7-ed087ad29cd8.png)
![image](https://user-images.githubusercontent.com/51820538/124119079-f31b3580-da69-11eb-89f5-854533800134.png)

**Comment by jacobtoppm** [comment]
Hey @bva-mike 

Thanks for answering all these questions. I've tried a few more configurations - publish rather than save, non-admin users, but still can't reproduce the issue as yet.
- Does this occur with all users trying to publish/save another user's comments on your site, or only some/in some circumstances?
- If only sometimes, is it on all page types or some? Does it occur only when publishing, or when saving a draft as well?
- Have you overridden the page edit handler class in any way?
- Are you using any kind of custom authentication?

**Comment by bva-mike** [comment]
Hey @jacobtoppm 

I think i might have fund the issue... steps to reproduce:

1. user 1: add comment to text within RichTextField within StreamBlock
2. user 1: publish entry
3. user 1: edit previous entry
3. user 1: remove previous text from within RichTextField within StreamBlock, (important: but keep comment there unresolved)
4. user 1: publish entry
3. user 2: edit previous entry
4. user 2: pusblish entry
5. user 2: validation error appears

i'm guessing the coment has been "orphaned"? 

this is using WT version 2.13.2.

let me know if those steps don't reproduce the issue for you, and i can maybe attach a video of it happening as well as answer our previous questions!

**Comment by jacobtoppm** [comment]
Thanks @bva-mike ! It turns out it's slightly more general than that - you just need to edit any next in or preceding another user's comment in a rich text field or block. I've created a PR that should fix the issue, which hopefully we'll get in 2.13.3.

**Comment by bva-mike** [comment]
@jacobtoppm ah cool! Thanks for the help/fix!

**Comment by jacobtoppm** [comment]
@bva-mike No problem! Thanks for helping me pin it down
