### ISSUE TITLE
Wagtail community discussion platform

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#7355]
While there is a [Wagtail support mailing list](https://groups.google.com/g/wagtail), there isn't an "official" community discussion platform listed on the Wagtail website or documentation. 

![image](https://user-images.githubusercontent.com/17307/126479586-6034244d-4936-4ee4-9f90-bbcd3fca5540.png)

Providing a more general discussion platform with broader topics and an engaging user interface might better promote community conviviality.

## Describe the solution you'd like

Many open-source projects provide a community discussion platform with topics such as:

- announcements
- technical support
- ideas
- showcase your work
- job opportunities

### Discourse

Many open-source communities are adopting the Discourse discussion platform. Discourse is highly engaging and serves as a hybrid forum/mailing list (including reply-by email). The Discourse platform has [many features to promote usability and engagement](https://www.discourse.org/features), such as badges, rich media embeds, periodic summary emails, topic subscriptions, and user profiles.

## Describe alternatives you've considered

GitHub has also rolled out a Discussions feature that can be added to repositories. However, the variety and scope of Wagtail discussions may extend beyond a single GitHub project/repository.

## Additional context

Many community interactions occur over time (are asynchronous) and are hard to fit into a Q&A or "tech support" bubble. Wagtail has excellent options for Q&A/tech support questions and ephemeral threaded chat. However, there is a gap for more broad and extended community discussions.

**Comment by RealOrangeOne** [comment]
What's wrong with Slack? In my experience it's a great place where people needing help get help, people who know things provide help, and there's lots of related discussions on working groups, community updates etc.

**Comment by brylie** [comment]
Slack is good for short-lived conversations, particularly for people who have a Slack client running. Anything beyond the latest few discussion threads tends to get buried in the Slack UX. Slack also lacks some key UX elements for community engagement like reply-by-email and recent activity summary email.

The suggestion here isn't to replace Slack. I just believe the Wagtail community could be better served for asynchronous conversations by a discussion platform such as Discourse.

**Comment by tomdyson** [comment]
Thanks for this, @brylie. We have an agenda point to discuss it at next week's core team meeting.

**Comment by tomdyson** [comment]
Apologies for the slow response on this, @brylie. We had the discussion a few weeks ago but (for non-work reasons) I've been late with my action to respond to you here.

We agree with your central point that "the Wagtail community could be better served for asynchronous conversations by a discussion platform". In particular we're keen that these conversations should be permanent and searchable. 

We're nervous about proliferating platforms; we already have Slack, Stack Overflow, Google Groups, Github RFCs and we're worried about confusing users or diluting the community by adding new overlapping options. 

Discourse is working well for Django, and several of the core team have positive experiences with it, both personally and professionally. However, we've decided to adopt Github Discussions, because we'd rather not be responsible for maintaining another service and because we think the integration between issues / discussions / RFCs will be easier. We plan to retire the rarely used Google Groups service at the same time as introducing Github Discussions, to partly address the issue of platform proliferation.

The next steps are to set up Github Discussions, and then to announce it on Slack and the Wagtail blog.

Thanks again for prompting this.

**Comment by tomdyson** [comment]
> The next steps are to set up Github Discussions

Done! Thanks to @gasman:

https://github.com/wagtail/wagtail/discussions

**Comment by brylie** [comment]
> In particular we're keen that these conversations should be permanent and searchable.

Yes, really important! :smiley:
