### ISSUE TITLE
Enable download all PO files at once in Transifex

### ISSUE THREAD

**Issue by itbabu** [wagtail/wagtail#7441]
### Is your proposal related to a problem?

Hello,
I have just completed the Italian translation, but I would like to test it locally. 
There is a Transifex feature that would allow me to [download all PO files at once](https://docs.transifex.com/projects/downloading-translations#downloading-a-zip-file-with-all-translation-files). But it is not enabled.

Here [the italian page](https://www.transifex.com/torchbox/wagtail/language/it/) as example

![t](https://user-images.githubusercontent.com/650691/129703102-4cfd372e-98f0-4b2a-a606-77b611505232.png)

### Describe the solution you'd like

Can you enable this feature which would greatly simplify the translation work? It should just be a permissions issue.

**Comment by gasman** [comment]
Hi @itbabu - I don't think Transifex provides the feature you're looking for. The documentation you linked to is referring to "a ZIP file containing the source file and all the translation files **from a single resource**" - e.g. being able to download a ZIP file containing the translations for wagtailadmin in all languages - and that _is_ available, under "resources". There's no mention of being able to download a ZIP file containing all resources in one language.

Even if that ZIP file was available, to try it out you'd still have to copy each .po file into the correct place within each app, so it wouldn't save you much work. Maybe the `fetch-translations.sh` script as documented on https://github.com/wagtail/wagtail/wiki/Managing-Wagtail-translations will do what you need? (It'll fetch all translations across all languages rather than just Italian, but that shouldn't be a problem.) The docs there are written from the perspective of a Wagtail maintainer, but I don't _think_ it should require any special permissions.

**Comment by itbabu** [comment]
ok thanks, i'll do a test with a fork of wagtail repo.
