### ISSUE TITLE
Allow to get_admin_display_title() return SafeString

### ISSUE THREAD

**Issue by it-management** [wagtail/wagtail#7490]
It's almost working until there are quotations mark inside ;-). Which is possible to handle easy.
But there are special cases where it doesn't work at all.

For example wagtail.admin.views.pages.edit.EditView.add_save_confirmation_message() method:
```python
    def add_save_confirmation_message(self):
        if self.is_reverting:
            message = _(
                "Page '{0}' has been replaced with version from {1}."
            ).format(
                self.page.get_admin_display_title(),
                self.previous_revision.created_at.strftime("%d %b %Y %H:%M")
            )
        else:
            message = _(
                "Page '{0}' has been updated."
            ).format(
                self.page.get_admin_display_title()
            )

        messages.success(self.request, message)
```
should by:
```python
    def add_save_confirmation_message(self):
        if self.is_reverting:
            message = format_html(_(
                "Page '{}' has been replaced with version from {}."
            ), self.page.get_admin_display_title(),
                self.previous_revision.created_at.strftime("%d %b %Y %H:%M")
            )
        else:
            message = format_html(_(
                "Page '{}' has been updated."
            ), self.page.get_admin_display_title()
            )

        messages.success(self.request, message)
```

**Comment by gasman** [comment]
I can't see us ever wanting to support this formally - there are too many possible edge cases (including the title in plaintext emails, JSON, passing it to Javascript...) for us to guarantee that it will work reliably. Additionally, in the fairly near future we're considering making the admin display title an explicit database field (so that it's always available without having to fetch the specific model), which will break this behaviour entirely.
