### ISSUE TITLE
 unable to find the view live buttons when wagtail is integrated into existing django project

### ISSUE THREAD

**Issue by pupattan** [wagtail/wagtail#7513]
I followed the link and integrated wagtail to my existing django project .
I am unable to find the view live buttons for pages. https://docs.wagtail.io/en/stable/getting_started/integrating_into_django.html
Unable to see VIew live buttons while or Live buttons 
Note : I am not overriding any settings or header config

![image](https://user-images.githubusercontent.com/19246595/132940075-6caabcb0-949c-4bdd-987a-93fe3cfe990a.png)

**Comment by pupattan** [comment]
I have fixed using the following in setting.py. It should be mentioned in the documentation
```

WAGTAIL_CONTENT_LANGUAGES = [
    ("en", _("English")),
]
WAGTAIL_I18N_ENABLED = True

```

**Comment by gasman** [comment]
WAGTAIL_CONTENT_LANGUAGES and WAGTAIL_I18N_ENABLED do not affect the presence of the "view live" button - most likely, the problem was that you hadn't created a site record under Settings -> Sites.

For future support queries, please use the [Wagtail tag on Stack Overflow](https://stackoverflow.com/questions/tagged/wagtail), or see [the Support page in the documentation](https://docs.wagtail.io/en/stable/support.html) for other options.
