### ISSUE TITLE
Custom Icon is not shown in the chooser related blocks and their elements

### ISSUE THREAD

**Issue by hazho** [wagtail/wagtail#7517]
hey guys, the icon replacement is not work for choosers' chosen elements, I investigated and found that the telepath is responsible of it, exactly at
<i class="icon icon-'+c.escapeHtml(l.blockDef.meta.icon)+'"></i>  area in the file /static/wagtailadmin/js/telepath/blocks.js , everything is quite fine in the chosen except the meta.icon attrib

* Python version: Run 3.8.
* Django version: 3.2.5
* Wagtail version: 2.14.1
* tested on new project as well (same issue)

**Comment by gasman** [comment]
Hi @hazho,
When you make a bug report, _please_ fill in all the requested information in the bug report form:

* what you did (including any code you wrote)
* what you expected to happen
* what happened instead

If the problem is something visual, including screenshots helps too.

If you don't do this, we have to reconstruct your bug report from just a few key words (icon, chooser, telepath), and that's not a constructive use of our time.

I _think_ what you're saying is that when you set the `icon` property on an ImageChooserBlock (or other chooser type), this icon doesn't change:
<img width="222" alt="Screenshot 2021-09-13 at 21 51 37" src="https://user-images.githubusercontent.com/85097/133155288-5006e2be-594f-471f-9a7e-63b011663fd6.png">

This is expected. The `icon` property only changes the icon used for the block listing:
<img width="920" alt="Screenshot 2021-09-13 at 21 59 28" src="https://user-images.githubusercontent.com/85097/133155660-622b0e3b-4da2-4df9-9702-ee831bbdb60a.png">

If this isn't what you mean, then please open a new bug report with full detail.
