### ISSUE TITLE
WAGTAILADMIN_PERMITTED_LANGUAGES setting not respected

### ISSUE THREAD

**Issue by dinoperovic** [wagtail/wagtail#7549]
### Issue Summary

`WAGTAILADMIN_PERMITTED_LANGUAGES` setting is not respected when `UserProfile.preferred_language` is left empty which happens by default and can't be changed when the setting contains only one language.

### Steps to Reproduce

1. Configure the project settings:
```python
LANGUAGE_CODE = "es"
LANGUAGES = [
    ("es", "Spanish"),
    ("en", "English"),
]
WAGTAILADMIN_PERMITTED_LANGUAGES = [("en", "English")]
```
2. In 'Chrome', go to settings -> languages and move 'Spanish' to the top (This sets 'Accept-Language' header to 'es')
3. Navigate to the admin panel, which will be in Spanish even though English is the only permitted language.

The issue seems to be caused by `UserProfile.get_preferred_language` method which defaults to Django's `get_langauge()` without checking against the permitted languages.

The same issue would happen In a case where `WAGTAILADMIN_PERMITTED_LANGUAGES` is changed after the user has already selected the preferred language and that language gets removed from the setting.

Right now the way around is to explicitly set the `preferred_language` on user profiles using signals. 
Changing the method to something like this would help:
```python
def get_preferred_language(self):
    lang = self.preferred_language or get_language() 
    admin_languages = get_available_admin_languages()
    if len(admin_languages) and lang not in [x[0] for x in admin_languages]:
        lang = admin_languages[0][0]
    return lang
```

Even with this, the other templates such as the login page will still render in Spanish.

### Technical details

* Python version: 3.9.
* Django version: 3.2.7.
* Wagtail version: 2.14.1.
* Browser version: Chrome 93

**Comment by gasman** [comment]
Hi @dinoperovic - thanks for the report.

Setting WAGTAILADMIN_PERMITTED_LANGUAGES to a list that doesn't contain the default LANGUAGE_CODE seems like an odd setup, and I'm not sure why that would happen in practice - what's the use-case for that?

The main intent of the WAGTAILADMIN_PERMITTED_LANGUAGES setting is to avoid the dropdown being cluttered with a load of languages that only have 10% complete translations, but to still allow developers to 'opt in' to those languages if they want them. While you're right that there are certain scenarios where a user would end up with a language not on that list, I don't see any real harm in letting them continue using the "forbidden" language.

I agree that in the case that WAGTAILADMIN_PERMITTED_LANGUAGES only contains one language, and a user's current language is set to something else, it would be better to _not_ hide the language chooser so that they have the ability to switch to the 'officially allowed' language. But since this only happens in obscure edge cases (as far as I can see), I don't think this is a high priority to fix.

**Comment by dinoperovic** [comment]
@gasman I agree this setup is odd (it is a requirement from a client) but regardless the same is true for a setup such as this:
```python
LANGUAGE_CODE = "en"
LANGUAGES = [
    ("en", "English"),
    ("es", "Spanish"),
    ("it", "Italian"),
]
WAGTAILADMIN_PERMITTED_LANGUAGES = [
    ("en", "English"),
    ("es", "Spanish"),
]
```

Using `Accept-Language: it` will render the admin in Italian (If the user has not set the preferred language)

Having explained the intent of this setting I do get your reasoning behind it, seems I have misunderstood it :) 

I just prefer having the admin fixed to English to avoid having to translate custom admin-related stuff.

**Comment by SebCorbin** [comment]
Allow me to reopen this, we have exactly the case that @dinoperovic mentionned:
 - our admin interface is only available in French and English
   ```
   WAGTAILADMIN_PERMITTED_LANGUAGES = [
       ("fr", _("French")),
       ("en", _("English")),
   ]
   ```
 - we allow administrators to edit content in a few other languages:
   ```
   LANGUAGES = WAGTAIL_CONTENT_LANGUAGES = [
       ("fr", _("French")),
       ("en", _("English")),
       ("nl", _("Dutch")),
       ("de", _("German")),
       ("es", _("Spanish")),
   ]
 - our default language is `LANGUAGE_CODE = "fr"`
  - on translated pages, we use `translation.override()` so that non-editorial strings are correctly translated to the page's language when `gettext` is used
  - but in the `{% wagtailuserbar %}` templatetag, due to `with translation.override(userprofile.get_preferred_language())`, if the user has let empty its language, the language is defaulting to `get_language()` and not `LANGUAGE_CODE` resulting in 

    ![Image](https://github.com/user-attachments/assets/88bd7911-6adf-4d03-b339-c5a7adc0cc22) (the first item is in French due to Wagtail brand removal) 
  - which is not what the user chose (or let as default): 
    ![Image](https://github.com/user-attachments/assets/f7d6937a-06b5-4630-b2d6-6e61f2e2d7c0) _Use server language: French_
