### ISSUE TITLE
Unpublish / Delete / Move a page should optionally cascade to other locales

### ISSUE THREAD

**Issue by phildexter** [wagtail/wagtail#7592]
There is a use case where as a user unpublishes / deletes a page, they want to also unpublish / delete that same page on many locales.

A solution to this would be that on the confirmation "Are you sure" screen, to show the other locales with checkboxes to select them to be deleted also.

**Unpublishing**
When unpublishing the user currently gets to choose if subpages should also be unpublished. We think the best solution here would be to show the locales above this subpages checkbox. The checkbox would relate to every locale then, and the total number of subpages being unpublished should update as checkboxes are selected / deselected.

**Deleting**
When deleting all subpages are automatically deleted also, and the user gets to see how many will be deleted. Again, we think the locales should be tickboxes to select, and the total number of deleted pages should update.

**Permissions**
Some users will be able to unpublish / delete pages in the main tree but not the locales. For these users, we should show the locale checkboxes still but have them unselected and greyed out. 

Ref: https://github.com/mozilla/foundation.mozilla.org/issues/7372

**Comment by phildexter** [comment]
Need to think a little about how this would interact with bulk actions. That could be a follow on action to this though..

**Comment by zerolab** [comment]
May depend on #7740, #7723, #7707

**Comment by zerolab** [comment]
Here's a high level change write-up:

The feature will only be available when synced trees is enabled. In Wagtail core, this is accomplished via the `WAGTAILSIMPLETRANSLATION_SYNC_PAGE_TREE = True` setting from the `simple_translation` package. When using Wagtail Localize, this is accomplished by [enabling the “sync from” feature](https://www.wagtail-localize.org/how-to/installation/#enabling-the-sync-from-field-optional) when editing a Locale. With Wagtail Localize we would then need to feed in the various related pages. 

We will not make a distinction between pure tree mirrors (that is the synced page tree has only aliases) and synced trees that have all pages submitted for translation or a mix of aliases and translated pages.

We will provide a new hook that other packages can use to provide additional pages to do the action on. We will implement this in the `simple_translation` core package, as well as `wagtail-localize`

In all three cases, the cascading will happen by default with appropriate messaging. e.g. 

### **Unpublish**

**Single action**

| Type | Message |
| --- | --- |
| Main, with translations | Are you sure you want to unpublish this page? This will also unpublish all 5 translations of the this page. |
| Main, no translations (only aliases) | Are you sure you want to unpublish this page? |
| Subpages checkbox, with translations | This page has 23 subpages and its translations have a combined 345 subpages. Unpublish these too |
| Subpages checkbox, no translations (only aliases) | This page has 23 subpages. |

**Bulk actions confirmation messages**

| Type | Message |
| --- | --- |
| Full, with subpages and translations | This page has 11 subpages. 6 translations of this page will also be unpublished, which have a combined 345 subpages. |
| With translations, but no subpages | 2 translations of this page will also be unpublished.  |
| With only aliases, no subpages |  |
| With only aliases and subpages | This page has 6 subpages |

### Move

⚠️  We will only move related pages if they have the same parent as the source page. If the translation page was moved under a different parent in the synced tree, it is no longer a mirror

**Single action**

| Type | Message |
| --- | --- |
| Main, with translations | Add new sentence:      This will also move 6 translations of tis page and their children |
| Main, no translations (only aliases) |  |

**Bulk actions confirmation messages**

| Type | Message |
| --- | --- |
| Full, with subpages and translations | This page has 6 subpages. There are also 6 translations of this page with a combined 345 subpages. |
| With translations, but no subpages | There are 6 translations of this page. |
| With only aliases, no subpages |  |
| With only aliases and subpages | This page has 6 subpages |

### Delete

ℹ️  Unlike the current alias page behaviour on *Delete*, instead of unlinking the alias page from its source (i.e. transform into fully fledged pages), the alias page will get deleted, but only in a sync tree scenario. Alias pages created in the same tree will continue to behave as they do currently.

⚠️  We will only move related pages if they have the same parent as the source page. If the translation page was moved under a different parent in the synced tree, it is no longer a mirror

**Single action**

| Type | Message |
| --- | --- |
| Full, with subpages and translations | Deleting this page will also delete 11 more subpages, 6 translations of this page and their combined 345 subpages. |
| With subpages but no translations (only aliases) | Deleting this page will also delete 11 more subpages. |
| Without subpages, with translations | Deleting this page will also delete 6 translations of this page |
| Without subpages, with translations and standalone subpages (i.e. create only under the translation) | Deleting this page will also delete 6 translations of this page and their combined 12 subpages. |

**Bulk actions confirmation messages**

| Type | Message |
| --- | --- |
| Full, with subpages and translations | This will also delete 11 more subpages, 6 translations of this page and any of their subpages. |
| With translations, but no subpages | This will also delete 4 translations of this page and any of their subpages. |
| With only aliases, no subpages |  |
| With only aliases and subpages | This will also delete 6 more subpages. |

**Comment by jaap3** [comment]
We stopped using `WAGTAILSIMPLETRANSLATION_SYNC_PAGE_TREE` but have implemented similar "auto translation" behaviour because of #7782. Can we replicate this behaviour by re-implementing `construct_translated_pages_to_cascade_actions` and removing the settings check?

**Comment by zerolab** [comment]
Hey @jaap3, at the moment `construct_translated_pages_to_cascade_actions` is only used in unpublish, move and delete, so I don't think that'll work.

Will happily review a PR for #7782, though
