### ISSUE TITLE
Documentation link links to no content

### ISSUE THREAD

**Issue by webquest-nz** [wagtail/wagtail#7630]
### Pertinent section of the Wagtail docs 
The url https://docs.wagtail.io/reference/pages/model_reference.html#wagtail.core.models.Page linked from https://docs.wagtail.io/en/stable/topics/pages.html goes nowhere.  Does anyone know when the wagtail documentation will be back online ?  All I get is a maze drawn in ascii art.

(Insert the permalink of the section heading in the Wagtail docs. Choose the most specific section / lowest-level heading to which your suggested change would apply. (In the docs, hover over the the heading to see the permalink icon.))

### Details

(Write your answer here.)
To go to an actual page, not a page of ascii art showing a maze.

**Comment by gasman** [comment]
Thanks for reporting! The correct link is https://docs.wagtail.io/en/stable/reference/pages/model_reference.html#wagtail.core.models.Page - we'll fix the broken link.

**Comment by gasman** [comment]
It turns out this was already fixed in #7390 on the 'latest' branch, but it didn't get ported over to 'stable' - unfortunately our docs hosting platform (readthedocs) doesn't make it easy to retrospectively change existing versions of docs without us putting out a whole new Wagtail release, so it's likely that it'll stay this way until we release 2.15 at the start of November.
