### ISSUE TITLE
Wagtail binary doesn't get detected on PATH on MacOS when installed from PIP

### ISSUE THREAD

**Issue by hash3liZer** [wagtail/wagtail#7678]
The wagtail command doesn't get detected on MacOS (Tested on Big SuR) when installed through pip. I tried with both sudo and non-sudo privileges but no success. At the end i'd to clone into latest release tag `2.14.2` from GitHub and install it manually using `python3 setup.py install` and it worked fine after that. 

### Steps to Reproduce
On MAC, simply run: 
```
$ pip3 install wagtail
$ wagtail
...
No command found
...
```

**Comment by gasman** [comment]
Hi @hash3liZer - I think this is a Python setup issue rather than a Wagtail one. Assuming you installed Python from one of the packages on https://www.python.org/downloads/macos/, within the /Applications/Python 3.x folder you should find a script named `Update Shell Profile.command` - running this should fix the issue.

If you need further assistance, please visit [our support channels](https://docs.wagtail.io/en/stable/support.html).
