### ISSUE TITLE
Silenced System Checks for "search_fields contains non-existent field"

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail#7722]
I set many-to-many relationship fields as index.FilterField in search_fields of the Page.
Whenever I start to run the program, the warnings "**search_fields contains non-existent field**" will display.
![image](https://user-images.githubusercontent.com/81170508/142832607-dece4658-aa15-438b-b596-f0aaca4aacf2.png)

Is there any solution to this problem?

**Comment by gasman** [comment]
This means that the `search_fields` definition contains a name that does not correspond to an actual field. This may be because the field has been removed, or there's a typo in the name - you should remove the entry or fix the mistake as appropriate.

If you think the message is appearing when it shouldn't be, please open a new issue giving steps to reproduce the problem.
