### ISSUE TITLE
Error running migration for empty (image) `Collection` records

### ISSUE THREAD

**Issue by ajharry69** [wagtail/wagtail#7853]
### Issue Summary

I get `__fake__.DoesNotExist` error (at [this](https://github.com/wagtail/wagtail/blame/main/wagtail/images/migrations/0023_add_choose_permissions.py#L65) line) when attempting to run [0023_add_choose_permissions](https://github.com/wagtail/wagtail/blob/main/wagtail/images/migrations/0023_add_choose_permissions.py) migration.

### Steps to Reproduce

1. Clear all collections added as per the [docs](https://docs.wagtail.io/en/v2.14.2/editor_manual/documents_images_snippets/collections.html).
2. Run `python manage.py migrate`

I expected the migration to run to completion without assuming there will always be an instance of `wagtailcore.Collection`.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: `3.8.5`.
* Django version: `3.2.11`.
* Wagtail version: `2.14.2`.
* Browser version: https://www.whatsmybrowser.org/b/LBLWR.

**Comment by gasman** [comment]
Closing as per above - I don't think it's possible to create the conditions for this error without directly modifying the database, but if you can provide more detailed steps to reproduce then I'd be happy to reconsider.

**Comment by ajharry69** [comment]
@gasman This is apparently an non-issue. The database I was working on was corrupt hence the weird error. Thanks for the assistance though.

**Comment by gasman** [comment]
Glad you got to the bottom of it! For future reference - if it's an issue that only occurs on one particular database and can't be reproduced on a new installation, please answer 'no' to "I have confirmed that this issue can be reproduced as described on a fresh Wagtail project". We rely on this being answered accurately so that we're not spending resources on investigating bug reports that are only local issues.
