### ISSUE TITLE
Add setting to activate comments toggle by default

### ISSUE THREAD

**Issue by ralphdelfs** [wagtail/wagtail#7892]
### Is your proposal related to a problem?

Our customer makes intensive use of the new commenting feature and they would like to avoid the repetitive task of always having to click on the comments toggle after starting to edit a Page.

### Describe the solution you'd like

It would be helpful to have a global setting flag (similar to WAGTAILADMIN_COMMENTS_ENABLED, e.g. WAGTAILADMIN_COMMENTS_TOGGLE_ACTIVE) that activates the commenting by default on editing page load.

### Describe alternatives you've considered

Another option could be to remember the toggle status for the current user session.

### Additional context

--

**Comment by thibaudcolas** [comment]
Hi @ralphdelfs, thank you for the suggestion. We’re about to revisit how comments are displayed in the page editing UI so I’ll make sure we take this into account as part of this.

**Comment by th3hamm0r** [comment]
Since we've also got a customer request for auto-enabling the comments, I wanted to place some additional thoughts:
A global setting could be a first start, and if that setting is used by a method in wagtail's page model, a subclass could also modify the decision based on custom logic (e.g. enabling comments automatically if unresolved comments exist).

**Comment by thibaudcolas** [comment]
I believe this will be solved by #9269, where we will remember which of the side panels is opened by default. Users who prefer to always comment can then move from page to page with comments still active.
