### ISSUE TITLE
embed template tag seems to be broken

### ISSUE THREAD

**Issue by awhileback** [wagtail/wagtail#7894]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

{% embed %} seems to be broken

### Steps to Reproduce

1. Make a StructBlock with an EmbedBlock in it and an optional field for `max_width`
2. point it to the following template...

```
{% load wagtailembeds_tags %}

{% if self.max_width %}
{% embed self.url max_width=self.max_width %}
{% else %}
{% embed self.url %}
{% endif %}

```
3. fill out that block in a page body and preview the page

I get the following error:

```
'EmbedValue' object has no attribute 'encode'
```

The last error in the chain refers to:

```
def get_embed_hash(url, max_width=None, max_height=None):
    h = md5()
    h.update(url.encode("utf-8")) 
```

Oddly, I put a pdb trace in that function and ran through it manually, and it seems to work...

```
(Pdb) url.encode('utf-8')
b'https://youtu.be/MghSXEvg734'
```

```
(Pdb) hgt = md5()
(Pdb) hgt.update(url.encode("utf-8"))
(Pdb) hgt
<md5 HASH object @ 0x7fc235911da0>
```

(had to rename h variable because h is reserved for 'help' in pdb)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I tried taking the max_width field out and just running `{% embed self.url %}` on twitter rather than youtube, but got the same result at the same place in the same function.

### Technical details

* Python version: 3.6.8
* Django version: 3.2.9
* Wagtail version: 2.15.1
* Browser version: Safari 15.2

**Comment by gasman** [comment]
Hi @awhileback,
You don't use the `{% embed %}` tag with EmbedBlock - it's one or the other. The `{% embed %}` tag converts the given URL into an embeddable HTML fragment, but the value returned by EmbedBlock is already a representation of the embeddable HTML - so you end up passing an embeddable HTML value to the `{% embed %}` tag when it just wants a URL.

If you want to call the `{% embed %}` tag yourself, to have control over the size, then you should use a plain URLBlock instead of EmbedBlock.
