### ISSUE TITLE
Wagtail 2.16 - Slim Sidebar open only settings

### ISSUE THREAD

**Issue by niakriss67** [wagtail/wagtail#7930]
### Issue Summary
When click on any menu item with submenu pages, the settings submenu always opens. 

### Steps to Reproduce

1. Open admin page
2. Click on any menu item with a submenu 
3. Settings submenu always opens

When click on the pages menu item, both submenus open. 

### Technical details

* Python version: 3.9.9.
* Django version: 3.2.12.
* Wagtail version: 2.16
* Browser version: firefox 96.0.3

**Comment by gasman** [comment]
Hi @niakriss67 - thanks for the report. However, I'm unable to replicate this on a fresh installation of [bakerydemo](https://github.com/wagtail/bakerydemo/) (with requirements/base.txt updated to `wagtail>=2.16,<2.17`).

**Comment by niakriss67** [comment]
It is very good that everything works on a clean installation of your specific assembly. But you didn't write anywhere that version 2.16 is incompatible with previous versions. Rollback to 2.15.3 fixes this problem.

**Comment by gasman** [comment]
If you can find a sequence of steps that independently replicates the issue (perhaps involving creating a project under 2.15 then upgrading) then we'll be happy to investigate further - however, if it only happens on a single project then there's no way for us to determine whether it's a legitimate bug, a customisation within that project, or user error.

Often, issues with upgrading can be caused by stale JS files from the previous version being cached in the browser (or, on a production site, failing to re-run `./manage.py collectstatic`).

**Comment by niakriss67** [comment]
You need to create a new module.
Create three submenu links with ModelAdmin. Specify some models.
Add a group with these links. The link name must be in Cyrillic! For example, menu_label = "Опросы"
Register a group with modeladmin_register.

Those. the error appears when the link name is not written in English. I checked with another language besides Cyrillic.

**Comment by niakriss67** [comment]
The same error appears even without a new module. It is enough to add another localization to the settings. LANGUAGE_CODE = 'ru-ru'. Then the settings submenu appears everywhere, as the very last in the list.

**Comment by gasman** [comment]
Thanks for the additional detail - I can confirm that I'm seeing the same issue on bakerydemo when set to `LANGUAGE_CODE = 'ru'`.

The issue is that Django's `slugify` function is being used to generate an ID from the label, and on non-Latin alphabets this results in an empty string, causing all menu items to have the same ID. I'll open a PR to fix this now.

**Comment by niakriss67** [comment]
Thank you for efficiency!
