### ISSUE TITLE
Third-party libraries selection for major UI components

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7980]
Dropdown, Tabs, Modal, Tooltips, Datepicker

**Comment by lb-** [comment]
each of these libraries provide a low-ish level API that we can use in both React and whatever other lightweight replacement for jQuery gets decided upon.

* https://github.com/SortableJS/Sortable -> not listed above but a staple when working with **drag/drop UIs** (note: this will not fill the gap of file upload dropping)
* https://github.com/transloadit/uppy OR https://github.com/dropzone/dropzone -> **drag & drop file uploading** (uppy can be extended with non-filesystem things like google drive, obviously requires a bit more on the sever side for integrating that)
* https://github.com/flatpickr/flatpickr OR https://github.com/Pikaday/Pikaday-> **datepicker** OR 
* https://github.com/focus-trap/focus-trap -> **focus trap** (for modals, note: we may not need much more beyond styles for our modals, and whatever lightweight framework gets adopted), we are already using focus-trap-react
* https://github.com/floating-ui/floating-ui -> was popperjs, can be used for **tooltips, dropdowns, popovers** and maybe toast (notifications)
* https://github.com/ccampbell/mousetrap OR  https://github.com/jaywcjlove/hotkeys OR https://github.com/github/hotkey **keyboard shortcuts**
* https://github.com/TarekRaafat/autoComplete.js OR https://github.com/algolia/autocomplete - **typeahead/autocomplete/search** -> looks like the algolia one could also support tags (instead of taggit) https://www.algolia.com/doc/ui-libraries/autocomplete/api-reference/autocomplete-plugin-tags/createTagsPlugin/

Notes
* Most come with no or minimal styles, this gives us the freedom (but a bit of overhead) to provide our own
* Most of the above have wrappers available in React, Lit & Stimulus - the Stimulus wrappers are pretty thin and may not be needed)
* Tabs - we may not need a tabs JS library, most could be solved with the lightweight framework of our choice, here are some Stimulus examples https://excid3.github.io/tailwindcss-stimulus-components/

**Comment by lb-** [comment]
https://github.com/KittyGiraudel/a11y-dialog - for modal (aka dialog)?

**Comment by thibaudcolas** [comment]
## Datepicker

I would like to propose we go with the native `<input type="date">`, `<input type="time">`, `<input type="datetime-local">` ([MDN docs & demo](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local)). There are a few problems with them:

- [Assistive technology support](https://a11ysupport.io/tech/html/input(type-datetime-local)_element): There is apparently no support in Dragon Naturally Speaking, and issues in iOS Safari.
- Browser support: no support for Safari 13, which clashes with our policy. I would like us to make an exception for this, considering we’re already planning to remove Safari 13 support either in the August 2022 or November 2022 releases, and it’d still be possible to enter at least dates and times as plain text (even if clunky).
- No (or very little) options for customisations. I’m hoping we can at least brand the field, if not the actual picker.

I’m interested in giving those a go nonetheless for a few reasons:

- The current pickers are completely unusable with the keyboard, and all assistive technologies. So any improvement from this is a step in the right direction. It might feel odd to go for a solution we’re not 100% happy with, but in the case of the native elements, there will be very little for us to configure / invest in customising. So we’ll be in a great position to switch to something else again later down the line, if we want to.
- I couldn’t find any **datetime** picker that works well (there are a few ok date pickers, and plenty of good time pickers). My go-to options for date pickers don’t do datetime. My preference for a greenfield project would be to use separate date and time fields, I believe this would be possible in Wagtail, but I expect this would be too much work for the time being.
- The fact those elements are native browser controls seems to mean they have excellent support for multilingual usage, and localised date input. It’s just how it works out of the box, validated at the browser level.

It’s also worth mentioning their UI is pretty good, with input masking in the field, and excellent keyboard support in the picker UI.

### Alternative: flatpickr

I have reviewed flatpickr and ruled it out. It has basic keyboard support, but looking at the markup it’s not going to work with a screen reader at all. It also seems to be impossible to enter a time within the picker with the keyboard

### Alternative: Pikaday

I have reviewed it multiple times in the past and it has basic accessibility issues.

### Alternative: [react-dates](https://github.com/react-dates/react-dates)

This tends to be my go-to due to the extensive keyboard and screen reader support (reviewed multiple times), as well as multilingual support. However it requires React to initialise, which makes it a bit clunky when used in a non-React project. It’s also very heavy of a library (relies on Moment.js, although they have plans to remove the dependency in the future). And it has no time picker.

### Alternative: [Duet Date Picker](https://duetds.github.io/date-picker/)

I have no real-world experience with this but it has a great reputation and worked very well under accessibility testing. It’s built by a Finnish company, so I would expect multilingual support & localisation works well. Unfortunately no datetime picker.

### Alternative: separate date and time fields

This could be done at the widget level rather than requiring model changes, so not impossible. However this would mean having two fields present, most likely side-by-side if we didn’t want to change the UI too much. While that might be possible for long forms, it could be annoying when using datetimes in restricted spaces – filters, mostly.

I’m still interested in this as a plan B, but hoping "plan A" could be good enough.

## Modal / dialog

I would like to go for [a11y-dialog](https://github.com/KittyGiraudel/a11y-dialog), based on:

- The reputation of its author and recommendations online (https://www.scottohara.me/blog/2019/03/05/open-dialog.html)
- The fact there’s no CSS – that’s perfect for us.
- Testing the demo, everything works as expected

### Alternative: native dialog element

With the current browser support, this would also mean using the polyfill, so doesn’t seem compelling enough to me compared to using a library. Particularly due to the reserves with the polyfill listed on https://www.scottohara.me/blog/2019/03/05/open-dialog.html. This is something we might be able to revisit in a year or two, but right now it wouldn’t work

### Alternative: some other library

I haven’t looked around much for this, simply because a11y-dialog seems excellent. There could be other good options!

## Dropdowns and tooltips

I would like to go for [Tippy.js](https://atomiks.github.io/tippyjs/), because:

- It seems to work well and is well documented
- Screen reader and keyboard testing gave me good results
- It has "headless" support
- It has an official React wrapper

### Alternative: floating-ui

I found this confusing, because some of the examples on the demo page are built with… Tippy.js. Didn’t assess it much further.

## Tabs

I haven’t found a library that stood out at this stage, so I’m leaning towards us building a custom implementation with either our lightweight UI framework, or React, or both, based on the [Tabs pattern in ARIA practices](https://w3c.github.io/aria-practices/#tabpanel).

**Comment by lb-** [comment]
@thibaudcolas this is a great roundup, no pushback from me.

Tippy even has a headless mode if we wanted to glo lighter and have our own styling and more control over the Dom elements rendered. 

https://atomiks.github.io/tippyjs/v6/headless-tippy/

**Comment by lb-** [comment]
Possibly useful tab guidance: https://inclusive-components.design/tabbed-interfaces/  (from UI meeting)

**Comment by thibaudcolas** [comment]
I’ll close this now just because based on our recent discussions we’re happy enough with the options outlined above.

- If anyone still has options to present or feedback on the above choices – please keep posting here. I think this can still be revisited up until the point at which we merge code using any one of those libraries.
- Looks like we _might_ be able to use `accent-color` to style our native datetime pickers


Another interesting one which I only learned about recently is [headless UI](https://headlessui.dev/), by the Tailwind team, though it only supports React and Vue.
