### ISSUE TITLE
Documentation logo and title rotation

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#7987]
The documentation logo and title rotate on hover. See the screencast:

https://user-images.githubusercontent.com/1969342/154029311-b947e2d7-662e-41c5-beb4-a6f6f667b05d.mov

There has been no recent theme release. 🤔 

https://pypi.org/project/sphinx-wagtail-theme/#history

**Comment by zerolab** [comment]
introduced in #7956 as far as I can tell

**Comment by thibaudcolas** [comment]
Hahaha, I saw that and thought it was a feature, as a nod to our admin easter egg. This is most likely because I "fixed" our `custom.css` which wasn’t getting loaded, in which case the fix will be to remove all customisations from it except the banner: https://github.com/thibaudcolas/wagtail/blob/53289e045b92643ff117eeb2c0181ddc92809f40/docs/_static/css/custom.css#L1-L53.

**Comment by thibaudcolas** [comment]
@allcaps @zerolab should be fixed in #7990 if either of you can take a look. I’ve also removed other customisations as I assume they’re all undesirable.
