### ISSUE TITLE
Searching documentation returns no results for pinned versions

### ISSUE THREAD

**Issue by wimfeijen** [wagtail/wagtail#8159]
Searching the Wagtail documentation regularly returns no results, while it should.

For example, when I search on image, I get no results.

https://docs.wagtail.org/en/v2.16.1/search.html?q=image#

I am using Firefox 98.0.1 as a browser
![Screenshot 2022-03-17 at 11 37 38](https://user-images.githubusercontent.com/68889/158791746-76b0627e-4a29-467f-8165-5bb4074b8818.jpg)
.

**Comment by lb-** [comment]
Yeah, looks like the search does not work for versions but it does for stable/latest

* ✅  https://docs.wagtail.org/en/latest/search.html?q=image#
* ✅ https://docs.wagtail.org/en/stable/search.html?q=image#
* ❌ https://docs.wagtail.org/en/v2.16.1/search.html?q=image#
* ❌ https://docs.wagtail.org/en/v2.15.4/search.html?q=image#


Not sure if it is a limitation of our usage of read the docs?

Also, if you use the search field in the versions popup you get taken to a completely different version of the docs.
https://readthedocs.org/projects/wagtail/search/?q=image

![Screen Shot 2022-03-17 at 8 47 10 pm](https://user-images.githubusercontent.com/1396140/158793141-9ae3e797-1264-41f1-a653-2a38f23f9d86.png)

![Screen Shot 2022-03-17 at 8 47 18 pm](https://user-images.githubusercontent.com/1396140/158793162-e49ce2eb-0ac3-4b81-aa42-c5052063a9a9.png)

**Comment by thibaudcolas** [comment]
This is now fixed as of #10207 for versions released since last Friday. I’ve tested with the recently-released `v4.2.1`, which doesn’t contain the documentation for "StreamField validation" added in `latest`.

Unfortunately I believe it’s impossible for us to make search work for past versions – I’m checking just to be sure before closing this, and will add any notes to the [Documentation search wiki page](https://github.com/wagtail/wagtail/wiki/Documentation-search).

**Comment by thibaudcolas** [comment]
Here is documentation from Read The Docs on this: [How we envision versions working](https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working).

Since we use tags for each version, it’s currently not possible for us to rebuild past versions of the docs. If we wanted to do this, we’d need to switch from tags to branches. They would either need to be named the same in git, or we could switch to `4.2.x`-type patterns and set up redirects.

This would be quite a lot of work to do if we kept publishing separate versions of the docs for each patch release, so I’m going to guess this is too much work for us to consider. If we only published documentation for major and minor releases in the future, it might be more manageable for each of them to have a long-lived branch which we could update when needed.
