### ISSUE TITLE
Bulk publishing is broken for pages without revisions

### ISSUE THREAD

**Issue by MarkBird** [wagtail/wagtail#8187]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The bug is in `wagtail.admin.views.pages.bulk_actions.publish.py` in `execute_action`:

`for page in objects:
            page.get_latest_revision().publish(user=user)`

If a page doesn't have any revisions, get_latest_revision() returns None and you get a `'NoneType' object has no attribute 'publish'` error.

### Steps to Reproduce

Create a draft page that has no revisions and try to publish it using bulk actions.

### Technical details

* Python version: 3.10.0
* Django version: 3.2.9
* Wagtail version: 2.15.4 or 2.16.1
* Browser version: Chrome 99.0.4844.74

**Comment by chosak** [comment]
Fixed by #8263. Merged to main in https://github.com/wagtail/wagtail/commit/00adeb8cf29cd22d83e75aee425e9d47bf62659d, stable/2.15.x in https://github.com/wagtail/wagtail/commit/6f0f188bfc4270c4199cc87cdb7344659eeff1d0, and stable/2.16.x in https://github.com/wagtail/wagtail/commit/1a28c44add84d19cd962b33bcc71c78576d4f030.
