### ISSUE TITLE
Wagtail 2.16.1 sub-classing AdminURLHelper leads to telepath exception if WAGTAIL_SLIM_SIDEBAR is enabled

### ISSUE THREAD

**Issue by vladox** [wagtail/wagtail#8286]
### Issue Summary

Extending the sidebar using the sub-classing described [here](https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/primer.html#modeladmin-url-helper-class) leads an exception in telepath `telepath.UnpackableTypeError: don't know how to pack object: <bound method PageIndexEditAdminURLHelper.index_url of <app_base.modeladmin.helpers.PageIndexEditAdminURLHelper object at 0x7f587d036d60>>`

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Extend sidebar by following the instructions in https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/primer.html#modeladmin-url-helper-class 
3. Launch the Admin backend and log in, see it crash.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.9.6
* Django version: 3.2.12
* Wagtail version: 2.16.1
* Browser version: Chrome 99
* Running on Divio Cloud: https://latest-wagtail-reference-project.us.aldryn.io/admin (user/password)

**Comment by vladox** [comment]
A test repo is available here: https://github.com/elpatiostudio/wagtail-no-aldryn-addons

**Comment by gasman** [comment]
Hi @vladox - thanks for the report, and for putting together a test case demonstrating the issue.

In your test repo:

    class DummyAdminURLHelper(AdminURLHelper):
        def index_url(self):
            return '/admin/pages/'

`index_url` should be defined as a property, rather than a method - the problem occurs because the ModelAdmin code is referencing `url_helper.index_url` (rather than `url_helper.index_url()`), expecting it to return a string to pass on to the front-end code - but it's getting back a bound method object instead, which the front-end code can't handle.

Adding `@property` above `def index_url(self):` fixes this.
