### ISSUE TITLE
Add Wagtail to the JAMstack headless CMS section

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8322]
### Is your proposal related to a problem?

I am often looking at the CMSs listed on JAMstack and think it would be good to also see Wagtail listed as we support a basic headless API out of the box. 

### Describe the solution you'd like

Prepare a pull request to the JAMstack repo with an additional page. 

### Describe alternatives you've considered

Maybe this should not be an issue but just something the core team sort out. 

### Additional context

- https://github.com/jamstack/jamstack.org/tree/main/src/site/headless-cms - pages for headless CMSs
- https://jamstack.org/headless-cms/ - main section

**Comment by Ruth-ikegah** [comment]
Hi @lb-, I am a potential Outreachy intern interested in the Wagtail documentation project and would love to fix this issue. 

I agree Wagtail should be on that list. I do know an active Jamstack contributor I could reach out to when I create my PR to their repo.

Please could you assign this issue to me?

**Comment by Scotchester** [comment]
Welcome @Ruth-ikegah. We do not usually assign issues (except for major sponsored initiatives). You are welcome to open the PR on the jamstack.org repo, but please propose your changes here in this issue before opening the PR, so that those of us with more experience with the Wagtail project can agree on the language we want to use to describe it on the Jamstack site.

**Comment by Ruth-ikegah** [comment]
Alright, thanks for the information, @Scotchester will do that!

**Comment by Temidayo32** [comment]
@Ruth-ikegah are you working on this issue?

**Comment by Ruth-ikegah** [comment]
yes I am @Temidayo32

**Comment by activus-d** [comment]
@Ruth-ikegah Are you still interested in this issue or I should work on it?

**Comment by Ruth-ikegah** [comment]
Hi @activus-d I am sorry i got caught up in a lot of work and couldn't work on this, yes, please you can work on it! Thank you

**Comment by activus-d** [comment]
While trying to resolve this issue, I discovered the following details, which community members may need to consider:
* All headless CMS that have been added in the past have a dedicated website. It is also worth noting that these websites are meant just for that particular purpose.
* The last time a new product/software was added to the repository was August 3, 2022.
The following information about the Wagtail headless CMS would be needed to make a pull request:
Dedicated Twitter account
  * The Type of Wagtail headless CMS (whether it is API driven or otherwise)
  * Site generators supported by Wagtail headless CMS
  * The Description of Wagtail headless CMS
  * Whether Wagtail headless CMS is open source or otherwise
  * The features of Wagtail headless CMS

**Comment by lb-** [comment]
Here are some Wagtail resources for usage as a headless CMS

- https://areweheadlessyet.wagtail.org/
- https://wagtail.org/blog/headless-wagtail-guide/
- https://github.com/torchbox/wagtail-headless-preview
- https://wagtail-grapple.readthedocs.io/en/latest/

From these it should be possible to answer most of those questions, I'm not aware of what site generators explicitly support Wagtail though.

**Comment by activus-d** [comment]
@lb- @Scotchester Please review this description of the Headless Wagtail CMS.

---
title: Headless Wagtail
homepage: https://areweheadlessyet.wagtail.org/
twitter: WagtailCMS
opensource: "Yes"
typeofcms: "API Driven"
supportedgenerators:
  -  Next.js, Gatsby
description: Headless Wagtail is an open-source and API-driven CMS written in Python and built on the Django web framework. It is highly customizable and has robust capabilities for managing your content.
---

## All about Headless Wagtail

Headless Wagtail is a variant of Wagtail's content management system (CMS). It gives you more options to incorporate technologies that don't run on Python. 

Headless Wagtail CMS offers developers the ability to create custom front-end applications while still leveraging the powerful content management features of the traditional Wagtail CMS. By decoupling the content management interface from the front-end display, Wagtail can be used as a backend for your front-end applications.

```Note
I would need a sample screenshot of the Admin interface of the Headless Wagtail CMS to make the  
pull request
```

**Comment by activus-d** [comment]
@lb- @Scotchester Please review this description of the Headless Wagtail CMS.

---
title: Headless Wagtail
repo: torchbox/wagtail-headless-preview
homepage: https://areweheadlessyet.wagtail.org/
twitter: WagtailCMS
opensource: "Yes"
typeofcms: "API Driven"
supportedgenerators: Next.js, Gatsby
description: Headless Wagtail is an open-source and API-driven CMS written in Python and built on the Django web framework. It is highly customizable and has robust capabilities for managing your content.
---

## All about Headless Wagtail

Headless Wagtail is a variant of Wagtail's content management system (CMS). It gives you more options to incorporate technologies that don't run on Python. 

Headless Wagtail CMS offers developers the ability to create custom front-end applications while still leveraging the powerful content management features of the traditional Wagtail CMS. By decoupling the content management interface from the front-end display, Wagtail can be used as a backend for your front-end applications.

**Comment by Scotchester** [comment]
Thanks for having a go at this, @activus-d!

I think we should follow the example of another major traditionally "headed" CMS that has a headless option – [WordPress](https://jamstack.org/headless-cms/wordpress/). Specifically, I would not call it "Headless Wagtail", I would simply call it Wagtail and then describe how it can be used in a headless fashion. Here's what I'd suggest for a `wagtail.md` file that could be PRed to the directory linked in @lb-'s original post:

```markdown
---
title: Wagtail
repo: wagtail/wagtail
homepage: https://wagtail.org/
twitter: WagtailCMS
opensource: "Yes"
typeofcms: "API Driven"
supportedgenerators:
  - All
description: The Wagtail CMS enables headless development through a built-in REST API and supports a GraphQL API via plugin.
---
## All about headless Wagtail

Wagtail offers several built-in and add-on capabilities to support a headless architecture, giving you the option to use your favorite front-end framework instead of traditional Django-served templates, while still leveraging the powerful content management features of the Wagtail admin interface.

(describe generally Wagtail's currently level of support for various headless things and link to https://areweheadlessyet.wagtail.org/ and any other appropriate general resources)

### REST API

(describe built-in REST API and link to docs for it)

### GraphQL

(describe how wagtail-grapple can be used to create a GraphQL API and link to its docs)
```

> I would need a sample screenshot of the Admin interface of the Headless Wagtail CMS to make a pull request.

I would recommend pulling a few from the Bakery Demo.

**Comment by allcaps** [comment]
Maybe also explain that Wagtail CMS is built on top of Django. All Django features and third-party apps are available. This gives great flexibility to support any frontend. For example, use the Django Rest Framework directly.

**Comment by activus-d** [comment]
@allcaps @Scotchester Alright. I will work on all the recommendations in my next draft and leave it here as a comment for further scrutiny.

**Comment by activus-d** [comment]
> ## All about headless Wagtail
>Wagtail offers several built-in and add-on capabilities to support a headless architecture, giving >you the option to use your favorite front-end framework instead of traditional Django-served >templates, while still leveraging the powerful content management features of the Wagtail admin interface.
>
>(describe generally Wagtail's currently level of support for various headless things and link to >https://areweheadlessyet.wagtail.org/ and any other appropriate general resources)

@Scotchester @allcaps @lb- As regards this, I have read the information on [areweheadlessyet](https://areweheadlessyet.wagtail.org/) and I need to ask that since some of the features listed there are still under development, shouldn't we skip the details or description, and just provide the the link to [areweheadlessyet](https://areweheadlessyet.wagtail.org/)? I believe doing this increases the chances of the PR getting merged.

I can just improve the content of this section with the recommendations for @allcaps as regards the great flexibility and customization of Wagtail. 

Kindly let me know your opinion on this matter.

**Comment by activus-d** [comment]
@Scotchester @allcaps @lb- Kindly go through this draft

---
title: Wagtail
repo: wagtail/wagtail
homepage: https://wagtail.org/
twitter: WagtailCMS
opensource: "Yes"
typeofcms: "API Driven"
supportedgenerators:
  \- All
description: Wagtail CMS supports headless development through a built-in REST API. Wagtail CMS also supports a GraphQL API via a plugin.
---

## All about Headless Wagtail
Wagtail is an open-source and API-driven CMS built on the Django web framework.

Wagtail provides headless architecture support through a number of built-in and add-on capabilities. By using Wagtail, you can use your favorite front-end framework instead of the traditional Django templates. In addition, you can manage all your content from one location, thanks to the powerful Wagtail admin interface.

Wagtail is flexible and highly customizable. Since it's built on the Django framework, you can integrate all Django features and third-party plugins. For example, if you don't want to use Wagtail's built-in REST API, you can build your own using the [Django REST framework](https://www.django-rest-framework.org).

With Wagtail, you also get a [built-in page preview and image optimization.](https://areweheadlessyet.wagtail.org/)

## REST API
REST APIs are native features of Wagtail with some built-in functionality. You can use Wagtail's REST API to retrieve any page, image, document, or other data as a JSON response that your website can consume via the HTTP protocol. However, if you don't want to use Wagtail's built-in REST API, you can build your own using the [Django REST framework](https://www.django-rest-framework.org).

## GraphQL
You can use GraphQL to interact with your website's content using the [wagtail-grapple](https://github.com/torchbox/wagtail-grapple) library. By using wagtail-grapple, you can build GraphQL endpoints on a model-by-model basis as quickly as possible with a simple configuration. The wagtail-grapple library provides support for the following:
-   Easily create GraphQL types by adding a small annotation in your models.
-   Traditional Wagtail models:
    -   Pages (including Streamfield & Orderables)
    -   Snippets
    -   Images
    -   Documents
    -   Media
    -   Settings
    -   Redirects
    -   Search (on all models)
-   Custom Image & Document model
-   Pagination
-   Middleware
-   Advanced headless preview functionality built with GraphQL subscriptions to allow for page previews on any device.

**Comment by thibaudcolas** [comment]
Submitted at https://github.com/jamstack/jamstack.org/pull/860, combining @activus-d’s sections with a draft I had written without realising this was an issue on our repository.

I’ll close this now, it’s largely out of our hands whether this gets accepted or not, and anyone who wants to follow up should subscribe to that pull request’s updates directly.

**Comment by lb-** [comment]
This is now live - https://jamstack.org/headless-cms/wagtail/

Thanks @thibaudcolas  & @activus-d  - great to see this in.
