### ISSUE TITLE
Hard-coded purple/indigo color. Maybe a CSS variable instead?

### ISSUE THREAD

**Issue by havardox** [wagtail/wagtail#8424]
Currently, the sidebar and many other UI components use a hard-coded purple color as their background. This color doesn't work well with a variety of different color schemes. If you want to use something else besides purple, you have to manually override every CSS class that uses said hard-coded color.

I propose creating a new CSS variable, so this process of overriding would be less pain-inducing.

**Comment by havardox** [comment]
Here's some examples:
<img width="960" alt="example-1" src="https://user-images.githubusercontent.com/19144650/165132182-5bf33a69-414f-49ef-bd26-acc24600aa93.png">
<hr>
<img width="960" alt="example-2" src="https://user-images.githubusercontent.com/19144650/165132185-b222c5e2-a577-4ee2-9646-1f4a0b421379.png">
<hr>
<img width="960" alt="example-3" src="https://user-images.githubusercontent.com/19144650/165132187-02be8e7e-dc34-42a3-bdba-9ef031140d89.png">
<hr>
<img width="960" alt="example-4" src="https://user-images.githubusercontent.com/19144650/165132177-5adf01f4-9aa8-405c-858b-58a1e4806a29.png">
<hr>
<img width="960" alt="example-5" src="https://user-images.githubusercontent.com/19144650/165132180-2ac96819-2385-4777-b084-f5524c259fd6.png">

Let's override Wagtail's color variables with some user-defined colors.

```
:root {
    --color-primary: #b71234;
    --color-primary-darker: #980f2a;
    --color-primary-dark: #980f2a;
    --color-primary-lighter: azure;
    --color-primary-light: aliceblue;
    --color-input-focus: #fff4e9;
    --color-input-focus-border: #e6e6e6;
    --color-button-hover: white;
    --color-button-hover-border: #b71234;
}
```

The end result is this:

![image](https://user-images.githubusercontent.com/19144650/165133061-e11c2fd6-21a4-48fe-95bc-6627cafffcef.png)

That looks quite... hideous.

**Comment by gasman** [comment]
I'd like to push to get this into 3.0 final if possible - the purpose of introducing CSS variables was to allow overriding the primary colour scheme, and if Wagtail 3 has effectively introduced the purple/indigo as a new primary colour, not having a CSS variable for it seems like an oversight.

**Comment by thibaudcolas** [comment]
This strikes me as a change that would require some consensus before we proceed, so ideally deferred to Wagtail 4.0 or beyond. Our CSS variables setup for colors wasn’t satisfactory even before this change of sidebar color, and it’d be nice for us to have proper time to consider naming (right now we’re using a mixture of brand, descriptive, and semantic names, which feels confusing).

@havardox the specific example you shared is already looking jarring with the default color on the header, so I don’t think another CSS variable would be the correct solution to this either.

**Comment by gasman** [comment]
> This strikes me as a change that would require some consensus before we proceed

I disagree. The ability to customise colour schemes was [an advertised feature of Wagtail 2.12](https://docs.wagtail.org/en/stable/releases/2.12.html#admin-color-themes). Adding a new non-customisable colour means that it's no longer possible to do that satisfactorily, so it's a regression from previous behaviour - fixing it shouldn't be a contentious decision.

I don't know the background to why the CSS variables setup is considered unsatisfactory, but nevertheless it's a convention that we introduced, and we should continue following it until we have something better - if anything, the decision to _not_ do that is the one should have received consensus before going ahead.

**Comment by thibaudcolas** [comment]
What we introduced in Wagtail 2.12 is the customisation of the primary teal only, all the other colors with CSS variables are meant to be hues derived from it. We’ve had all other colors in the CMS hard-coded so far, and in particular the color scheme of the sidebar has always been specific to the sidebar, and hard-coded.

> iI don't know the background to why the CSS variables setup is considered unsatisfactory, but nevertheless it's a convention that we introduced, and we should continue following it until we have something better - if anything, the decision to not do that is the one should have received consensus before going ahead.

We’ve discussed this multiple times in UI team meetings over the last 3 months, I recall in particular:

- As a part of the GSoC Windows High Contrast Mode project since that would likely be much simpler to roll out with CSS variables.
- More recently as a follow-up to work currently under way to make our fonts available as CSS variables (#8406)

We seemed to have consensus then that when we revisit this it’d be better to roll this out for all other colors at once.

---

Back to this one color, what we had discussed as needing further validation was:

- Whether our usage of design tokens for colors should be based on semantic names or descriptive ones
- Whether we use our `w-` or another prefix for CSS variables
- (I have a vague recollection we also wondered whether we should have "immutable" variables for people to reuse Wagtail’s colors as-is, _and_ in addition variables intended to customise the UI)

Someone additionally raised the need for us to be careful with this so we don’t start creating backwards compatibility issues for ourselves as we introduce more variables.

I’d be happy for us to pick all of this up sooner than Wagtail 4.0 but again in my opinion this isn’t a regression to deal with during a release candidate, it needs some agreement on the above points.

**Comment by thibaudcolas** [comment]
First draft from @stevedya: #8457

This needs further tweaking and I think we could use more feedback from people interested in this on which of the following we’d go for:

1. Switching the existing single color customisation to target indigo rather than teal
2. Introducing another single color customisation for indigo (and its accent), in addition to what we’re doing with teal (kept as-is)
3. Introducing a way to change the colors of the sidebar only, keeping the teal color customisation as-is
4. Make all our colors customisable and leave it up to people to make their pick of which ones to customise

And additionally – do we want to do the same as what we’ve done with the primary teal, where you can set only a single color and all of the lighter/darker tones are automatically derived from it – or leave it up to people to make sure they determine and configure the appropriate lighter and darker hues as well as the main hue of a given color?

@havardox what do you think? @wagtail/ui does anyone have comments about this? We had discussed option 2. for Wagtail 3.0, but now that we’re targeting 4.0 we could go for something more disruptive.

**Comment by lb-** [comment]
Django CSS custom properties/ dark mode support for reference. 
https://docs.djangoproject.com/en/dev/ref/contrib/admin/#admin-theming

**Comment by thibaudcolas** [comment]
For anyone needing this _for Wagtail 3.0_ – here is a repository describing a workaround for this release: https://github.com/thibaudcolas/wagtail_color_overrides. Screenshot with a blue theme:

![wagtail_color_overrides](https://user-images.githubusercontent.com/877585/169300981-b260fee6-2708-48a1-8660-f83783b50067.png)

We’re still planning to have similar capabilities in Wagtail 4 so this should be a one-off workaround for 3.0.

**Comment by thibaudcolas** [comment]
For people following this – the UI team discussed this again yesterday and came to the following resolutions:

- We’ll make all of our colors customisable and leave it up to people to make their pick of which ones to customise
- We’ll keep the existing setup for `color-primary`, where it’s possible to only set one hue variable, or three HSL component variables, and have other accent / lighter / darker colors generated from this.

This will mean on the order of 80 to 100 CSS variables, so we’ll need to think a bit carefully of how to structure and document this.

---

We’re likely to be replacing quite a few "legacy" colors very soon as part of a rework of the page editor’s forms styles, I think this might get easier to implement afterwards so I’d recommend waiting before we move to implementation.
