### ISSUE TITLE
Custom Image model with additional required fields - impossible to add image in multi-add view.

### ISSUE THREAD

**Issue by LKozlowski** [wagtail/wagtail#847]
It is not possible to add images in wagtail admin under images submenu, because after adding image it tries to save object, raising validation error.

**Comment by gasman** [comment]
> The only way I can see of fixing this directly is to store the uploaded images in a temporary database table, so that we're only creating real image records after the user has filled in the 'extra details' form - which would be a significant structural change to make just to address an unusual custom requirement. (We'd consider any patches that implement this, though.)

Revisiting this idea, as I think it may not be as dramatic a change as I was fearing... the approach would be something like:

* Create a new model `UploadedImage` in the wagtailimages app, unrelated to any existing `Image` model; this would consist of an image file field, and any other fields that can be immediately populated from the image upload with no further user input (width / height, and possibly focal point)
* The POST action of the multiple uploader creates an in-memory Image object for each uploaded file, as it does now; however, at the point of saving the image, we catch model validation errors (probably by catching `ValidationError` exceptions at the point of saving, so that any custom `save` logic has chance to take effect and potentially fix up fields to make them valid)
* If validation fails, we instead create an `UploadedImage` record in the database, populated from the data in the in-memory Image object.
* We then generate a ModelForm based on the Image instance, as per the current implementation; in this case the instance is unsaved and invalid, and the form will be unsubmittable without further edits. This form will be given additional hidden fields to indicate that it corresponds to an `UploadedImage` instance, including the ID of that instance.
* The POST action for that form submission will recognise the new hidden fields; if they are present, then rather than using the form data to update an existing `Image` object, it will attempt to create a new `Image` object based on the form data and the linked `UploadedImage`. If this resulting image is valid, it is saved to the database and the `UploadedImage` record is deleted.

**Comment by lb-** [comment]
Implemented via https://github.com/wagtail/wagtail/pull/5266
