### ISSUE TITLE
Replace Bootstrap tooltips with Tippy.js

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8565]
We currently have two styles of tooltips in the CMS. One legacy style with an implementation from Bootstrap, using the `data-wagtail-tooltip` attribute in templates:

![bootstrap-tooltips](https://user-images.githubusercontent.com/877585/169305838-8ca35d7f-d8e0-472b-b5c6-da5754ce326b.png)

And one modern style implemented with Tippy.js with a set of attributes prefixed with `data-tippy`:

![tippy-tooltips](https://user-images.githubusercontent.com/877585/169305916-8a8d1446-453c-450d-9f4e-dcf59bdc0ce0.png)

---

The Bootstrap tooltips need to be replaced across the whole admin interface, with the library eventually removed. Aside from the visual aspect, Bootstrap tooltips seem to be impossible for screen reader users to reach the contents of.

**Comment by lb-** [comment]
We should explore CSS isolation instead of z-index so that we don't create a z-index mess. 

https://developer.mozilla.org/en-US/docs/Web/CSS/isolation

https://www.smashingmagazine.com/2022/05/lesser-known-underused-css-features-2022/#creating-stacking-context-with-isolate

https://caniuse.com/?search=isolation

**Comment by lb-** [comment]
Adding this to the Stimulus RFC project as a potential bit of scope.

**Comment by lb-** [comment]
Made a start on this here - will hopefully have a PR up in a few days
https://github.com/lb-/wagtail/tree/feature/8565-replace-bootstrap-tooltips
