### ISSUE TITLE
password reset not working if WAGTAILADMIN_BASE_URL unset

### ISSUE THREAD

**Issue by derhedwig** [wagtail/wagtail#8582]
### Issue Summary
After upgrading an old project to wagtail 3.0 where BASE_URL or WAGTAILADMIN_BASE_URL is unset, the password reset functionality of the wagtail admin stops working with the error `KeyError: 'request'` raised from `get_admin_base_url`.

### Steps to Reproduce

1. Have a fresh wagtail install with wagtail 3.0
2. Remove WAGTAILADMIN_BASE_URL setting
3. Create a user account
4. Try the password reset with the email address of the user account
5. You get a 500 with `KeyError: 'request'`

Either `get_admin_base_url` should be fixed to work in emails when WAGTAILADMIN_BASE_URL is unset or it should be made clearer in the release notes, that you need a WAGTAILADMIN_BASE_URL setting.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.10
* Django version: 4.0.4
* Wagtail version: 3.0
* Browser version: Chrome 101

**Comment by gasman** [comment]
Thanks for reporting! Confirming that I'm seeing the same issue when testing against a fresh Wagtail install, and against bakerydemo.

It looks like the logic in #8268 for [determining the hostname in the absence of the WAGTAILADMIN_BASE_URL setting](https://github.com/wagtail/wagtail/pull/8268/files#diff-8b9763e540faf1b3d5966de49693a9e8b744b5b4b3b6e17bbbbdb317afa79391R24-R32) was heavily flawed:

* It assumes that if a context object is supplied, it must contain a `request` object. This is not the case for either the password reset or notification emails; this is fixable for the password reset by overriding the `extra_email_context` property on `wagtail.admin.views.account.PasswordResetView`, but for workflow notifications there's no clear way of fixing this, since those emails are triggered from signal handlers and so no request object is available.
* It accesses `request.site`, which originates from the SiteMiddleware class deprecated in 2.9 and obsolete since 2.11.
* Trying to use Site records to locate the admin backend is mostly redundant anyhow; there are probably more scenarios where it will fail (e.g. a site record was never set up correctly because it largely doesn't matter for single-site installations, or it's pointing to the front-end hostname of a headless setup that's different from the Django server) than ones where it'll give a better result than using `request.get_host()` directly.
* To make matters worse, [the try/except blocks in wagtail.admin.mail](https://github.com/wagtail/wagtail/blob/cb43536f07f0a43412b3ff1c8c0d8ed61af5b3db/wagtail/admin/mail.py#L124-L152) that are supposed to guard against email server errors are overly broad, and will swallow up errors that happen while rendering the email template, like this one. This means that when the WAGTAILADMIN_BASE_URL setting is missing, notification emails would be silently dropped.

Given that we can't realistically supply a request object for notification emails without major API changes, I propose that we drop this logic from `get_admin_base_url` and revert to the previous behaviour where a missing WAGTAILADMIN_BASE_URL / BASE_URL setting will return incomplete URLs in emails; and then add a startup check to warn if WAGTAILADMIN_BASE_URL is missing.

**Comment by lb-** [comment]
Thanks for explaining this all @gasman
