### ISSUE TITLE
Error message shown in the page for duplicated slug

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail#8627]
If I create a page with one slug already existed, a validation error will arise. When it's in the production mode, 500 error page will shown to editors without knowing what type of errors occurred.

ValidationError at /admin/pages/add/articles/articlepage/20/
{'slug': ['This slug is already in use']}

I would appreciate if there is a new feature that "slug in use" validation error shown in page edition, instead of breaking the page.

**Comment by gasman** [comment]
I'm unable to replicate this issue - attempting to create a page with an already existing slug returns an inline validation error as intended, not a server error:

<img width="1413" alt="Screenshot 2022-06-06 at 16 46 18" src="https://user-images.githubusercontent.com/85097/172196441-98177a60-1fc3-477c-b3bd-85f15f5b2b81.png">

If this is not working on your project, it may be due to a customisation you've made. If you're able to replicate this on a new project, please open a new bug report, filling in all the requested fields including "steps to reproduce".
