### ISSUE TITLE
Refactor Avatar styles into UI component

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8655]
We currently have an "avatar" component as reusable CSS styles that are copy-pasted with the relevant HTML across the admin. This feels like a good candidate to refactor to a UI component:

- [ ] With a template partial in the `shared` folder for us to `{% include %}` where needed
- [ ] With Storybook stories for different variations of that component
- [ ] Refactoring some of the current usage to that template partial as appropriate
- [ ] In particular, updating the styleguide to use the template partial.

This shouldn’t change the component’s rendering in any way, just how it’s included in different places (and introduce a way for us to test the variations more easily in Storybook).

**Comment by thibaudcolas** [comment]
@lb- Steve is only meant to help with our usage of Storybook for the time being so I’ve told him not to attempt any CSS refactorings – it’s beyond what he has time for, and will also make any changes trickier for me to review.

**Comment by yokwejuste** [comment]
I'm currently on this issue.

**Comment by lb-** [comment]
@stevedya if it's ok - I'll un-assign you for now - Thibaud let me know if that's an issue.

**Comment by salty-ivy** [comment]
should i pick this one too ? since i have already worked  with https://github.com/wagtail/wagtail/issues/8656 status tags

**Comment by lb-** [comment]
Go for it @salty-ivy

**Comment by salty-ivy** [comment]
@lb-  i would like to ask in this process of creating a new partial for avatar perticularly for  avatar css in span `<span class="avatar"></span>`  there are 2 options.
1. is to treat https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/user_avatar.html 
as  new partial but there's this line  https://github.com/wagtail/wagtail/blob/4246c0b703bccc9aafb6f86524bbbdb55c3c9e1e/wagtail/admin/templates/wagtailadmin/shared/user_avatar.html#L7  
which is making it complex because this partial has already been included in some places 
eg:-  if i just need to use `<span class="avatar"></span>` via tag but username/ user line would also be  rendered 

2. to create a new partial `shared_avatar,html`

i am not sure if its the best approach lemme know your views about this

**Comment by salty-ivy** [comment]
@lb-  @thibaudcolas  PR is ready for the review

**Comment by salty-ivy** [comment]
@lb-  sure why not, thanks.
