### ISSUE TITLE
Audit log AttributeError if page type has been removed

### ISSUE THREAD

**Issue by tjwalch** [wagtail/wagtail#8699]
### Issue Summary
If a Page model is removed from project the audit log will crash when trying to display events related to this page type.

### Steps to Reproduce

1. Create a new page type
2. Create a page of this type, make edits
3. Delete the page
4. Remove the page type from code, migrate database
5. Navigate to Audit log

### Technical details

> Traceback (most recent call last):
>  File "/path/to/virtualenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/path/to/virtualenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
>     return func(*args, **kwds)
>   File "/path/to/virtualenv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/path/to/virtualenv/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper
>     return view_func(request, *args, **kwargs)
>   File "/path/to/virtualenv/lib/python3.8/site-packages/wagtail/admin/auth.py", line 174, in decorated_view
>     response = view_func(request, *args, **kwargs)
>   File "/path/to/virtualenv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/path/to/virtualenv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/path/to/virtualenv/lib/python3.8/site-packages/wagtail/admin/views/reports/base.py", line 40, in get
>     self.object_list = self.decorate_paginated_queryset(self.object_list)
>   File "/path/to/virtualenv/lib/python3.8/site-packages/wagtail/admin/views/reports/audit_logging.py", line 174, in decorate_paginated_queryset
>     for log_entry, instance in log_entries:
>   File "/path/to/virtualenv/lib/python3.8/site-packages/wagtail/core/models/audit_log.py", line 66, in with_instances
>     model_instances = model.objects.in_bulk(object_ids)
> 
> Exception Type: AttributeError at /admin/reports/site-history/
> Exception Value: 'NoneType' object has no attribute 'objects'

**Comment by chosak** [comment]
I can confirm this on Wagtail 4.2, Django 4.1.7. Here's a simple test case:

1. `wagtail start myproject && cd myproject`
2. `./manage.py migrate && ./manage.py createsuperuser`
3. `./manage.py runserver`
4. Navigate to http://localhost:8000/admin/pages/3/edit/, logging in using the superuser you created.
5. Make an edit to the page, for example changing its title, and Save draft.
6. Navigate to the Site history report at http://localhost:8000/admin/reports/site-history/ and see your edit of the page, of type HomePage.
7. Stop your server, and delete home/models.py, removing the HomePage model.
8. `./manage.py makemigrations && ./manage.py migrate` to delete that model.
9. `./manage.py runserver` again and navigate back to http://localhost:8000/admin/reports/site-history/

You'll get the following error:

> AttributeError at /admin/reports/site-history/
> 'NoneType' object has no attribute 'objects'

This is because of these lines:

https://github.com/wagtail/wagtail/blob/ab05f7dd3c843d6af53c5ea0dbb67298c8541562/wagtail/models/audit_log.py#L68-L69

because `content_type_id` refers to a model which has been deleted. There are actually two possible issues here: if the stale content type for the deleted model is still in the database, you get the error above because the model class no longer exists. But if you also run `./manage.py remove_stale_contentypes` after migrating you'll get an alternate error: "ContentType matching query does not exist.", because there isn't even a ContentType to retrieve.

Theoretically we might be able to substitute the base Page model in cases like these, but that is tricky to generalize because LogEntry can log any models, and there isn't always a "base" model to substitute. The site history report also [assumes](https://github.com/wagtail/wagtail/blob/0187a1494bc56bab4592dc0d3d314121edf590d0/wagtail/admin/templates/wagtailadmin/reports/site_history.html#L37) that there's a valid content type to render; it could say "None" or "Removed" or something to inform the user that the log entry refers to a model that is no longer retrievable.
