### ISSUE TITLE
Modal header styling needs tidy up

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#8941]
The modal header alignment is off in relation to the contents (via `header .row`) 
![Screenshot 2022-07-31 at 17 19 35](https://user-images.githubusercontent.com/31622/182807358-c3e2ba0c-cf6a-446c-8542-7035fbdcb776.png)

and it sports extra bottom padding (via `header.merged`
![Screenshot 2022-07-31 at 17 18 03](https://user-images.githubusercontent.com/31622/182807288-d6af1f38-7b46-4554-b562-8007ba62780d.png)
)

**Comment by lb-** [comment]
@PaarthAgarwal any chance you can take a look at this one? It uses the shared header template

**Comment by PaarthAgarwal** [comment]
> @PaarthAgarwal any chance you can take a look at this one? It uses the shared header template

Sure

**Comment by lb-** [comment]
@zerolab  please confirm what you are expecting - I assume vertically centred title?
Or maybe the padding 'in' from the left is too much?

**Comment by zerolab** [comment]
@lb @PaarthAgarwal 

pre 3.0 the icon (or the title text if there was no icon) would align with the start of the content.

Also `header.merged` adds an extranous `1rem` bottom padding to the header area

**Comment by lb-** [comment]
Ok - yeah that padding/ position issue is known and is kind of indirectly covered by https://github.com/wagtail/wagtail/issues/8906 but unfortunately it will not be a simple fix due to the complex positioning of the sidebar toggle. 

I know this is the modal variant but it uses the same CSS. 

There could also be an argument for showing a consistent position of the title irrespective of the icon. 

But yeah the merged class could be fixed easily.

On top of that - this variant of the modal looks like the bootstrap one which will be replaced at some point. Also - are you sure you are on the latest main here, I thought we updated all header classes to use BEM and be `w-header` not against the bare header element. 

@PaarthAgarwal - maybe find where this template is used and see how it looks without the merged value set.

**Comment by zerolab** [comment]
Oh, thank you for the prompt @lb-. 
I now pulled the latest `main` and it paints a different picture:

![Screenshot 2022-08-07 at 13 30 17](https://user-images.githubusercontent.com/31622/183290667-fc5f5957-0c09-4377-b9dd-65ac3abf60dc.png)

The title text is properly aligned. It must've been fixed by Thibaud's epic PR. Should serve me well for not re-checking after that PR was merged.

`.w-header.w-header--merged` has the `.25rem` bottom padding. We could close this if that is insignificant.

Thank you for taking the time, and sorry for the noise

**Comment by lb-** [comment]
If it's ok. I think we can close this. 

As the new modal designs get adopted for all modals - they won't even use this shared header template.  

The header for the new modals is built very differently (which has its own complexity in tailwind classes and using the same name like subtitle to render differently) but that's an issue for another day. 

The point is that both this modal header and the new one look good on main now and I think we can leave this as is.
