### ISSUE TITLE
updatemodulepaths stdout.write error

### ISSUE THREAD

**Issue by adi1** [wagtail/wagtail#8970]
### Issue Summary

updatemodulepaths uses `sys.stdout.write(line.encode("utf-8"))` which is not supported in python3.
I think this should be `sys.stdout.write(line)`

### Steps to Reproduce

1. run `wagtail updatemodulepaths` in a project where updates need to be made.

### Technical details

-   Python version: 3.7.11
-   Wagtail version: 3.0.1

**Comment by gasman** [comment]
Hi @adi1 - thanks for the report.

The `line.encode("utf-8")` was introduced in #8450, and is needed when running on Windows because it opens files in Windows-1252 encoding rather than UTF-8 by default, and there's no way to override this when using the [fileinput](https://docs.python.org/3/library/fileinput.html) library (until Python 3.10).

This line of code runs inside a `with fileinput.FileInput(...)` block, where `sys.stdout` has been substituted with a file opened in binary mode, so `sys.stdout.write(line.encode("utf-8"))` should be correct as far as I can see. Can you give more detail about the error you're getting, and the OS you're running on?

**Comment by gasman** [comment]
Thanks - I can confirm I'm seeing the same issue on Python 3.7.12, but not 3.8.

(This is when testing the `wagtail updatemodulepaths` command directly - running `sys.stdout.write('foo'.encode('utf-8'))` on the python command line isn't a valid test for this, as it needs to be run inside a `with fileinput.FileInput` block to match what updatemodulepaths is doing.)

**Comment by gasman** [comment]
PR: #8973
