### ISSUE TITLE
wagtail.documents.views.ListingResultsView uses a template that doesn't extend wagtailadmin/base.html, so it has no CSS styles

### ISSUE THREAD

**Issue by ZachPerkitny** [wagtail/wagtail#8979]
### Is your proposal related to a problem?

The view `wagtail.documents.views.ListingResultsView` uses a template (`wagtaildocs/documents/results.html`) that doesn't extend `wagtailadmin/base.html` and as a result it doesn't have any styling. This results in a weird user experience when they get redirected after updating a resource.

### Describe the solution you'd like

The template `wagtaildocs/documents/results.html` should extend `wagtailadmin/base.html` so it has the same CSS styling as the rest of the admin views.

**Comment by gasman** [comment]
Hi @ZachPerkitny,
ListingResultsView intentionally only returns an HTML fragment, because it's only used in AJAX requests when running a search query - the response is used to replace the results listing element without refreshing the whole page. A user should never be sent to that URL directly - if that's happening, that sounds like a bug. Please can you give more details of where this is occurring - ideally, as a set of steps someone can perform on a fresh Wagtail instance to replicate the problem?

**Comment by ZachPerkitny** [comment]
Just upgraded version of Wagtail, no longer an issue
