### ISSUE TITLE
Auto-capatilization of block (and field) names

### ISSUE THREAD

**Issue by robmoorman** [wagtail/wagtail#8984]
### Is your proposal related to a problem?

In Django it's best practice to put the verbose_name in lowercase as Django is auto-capitalizing these values in e.g. the Django admin and/or forms.

In Wagtail this auto-capitalizing isn't done, so you have to capitalize these value yourselves in StreamField labels. 

### Describe the solution you'd like

In the UI, capitalize the labels on two places (the name of block, and the label for the form fields).

<img width="293" alt="Screenshot 2022-08-12 at 10 44 21" src="https://user-images.githubusercontent.com/529396/184319391-6db55d34-5baa-4501-b79b-258f8e002c0b.png">
<img width="671" alt="Screenshot 2022-08-12 at 10 46 06" src="https://user-images.githubusercontent.com/529396/184319392-86afe99f-206b-49fe-95f8-3cd18128ab51.png">

```python
# from
class MyBlock(blocks.StructBlock):
    text = blocks.RichTextBlock(label=_("Text"))

    class Meta:
        label = _("My custom block")


# to
class MyBlock(blocks.StructBlock):
    text = blocks.RichTextBlock(label=_("text"))

    class Meta:
        label = _("my custom block")
```

**Comment by gasman** [comment]
Hi @robmoorman,
I don't think it's valid to consider the `label` argument on blocks as analogous to `verbose_name`. In the case of `verbose_name`, it makes sense to define it as lower-case because it might be used in situations where it doesn't get capitalised, e.g. "Add a %s". However, `label` is only used in this one place, so it's more appropriate for the developer to specify it exactly as they want it to appear.

In the case that the developer doesn't specify `label`, we build a default label from the internal name, and capitalise it at that point:

https://github.com/wagtail/wagtail/blob/d202624458db83e27d250e4d0ec709dda20a5203/wagtail/blocks/base.py#L98-L99

This is consistent with how Django handles labels for form fields: https://docs.djangoproject.com/en/4.1/ref/forms/fields/#label - so I think Wagtail is correctly following Django conventions here.

**Comment by robmoorman** [comment]
That makes actually sense @gasman thanks for your quick and well argumented answer.
