### ISSUE TITLE
graphical Hierarchy of models needed, especially for streamField blocks

### ISSUE THREAD

**Issue by hazho** [wagtail/wagtail#9012]
### Details
Recently I have increased the number of developers in my team, but due to rapid changes we old developers make, the new developers get blurry vision, after we investigated and toke their feedbacks, it turns out that the documentation is the reason, thought the currently documentation is great, however the only missing part is the graphical structure of the classes' hierarchy, I have checked some other frameworks' documentations that have the graphical structure and updated per release, i.e. ArcPy (https://desktop.arcgis.com/en/arcmap/latest/manage-data/using-sql-with-gdbs/what-is-the-st-geometry-storage-type.htm)

it would really be helpful to have same or similar graphics regarding nested classes of wagtail, especially the streamField related and the registrable classes/functions to wagtail_hooks.py 
and for the client side resources as well (if possible)

**Comment by Temidayo32** [comment]
Hi @hazho I can feel your pain and how important this modification to the documentation will help new developers on your team get started with using Wagtail. 

Can someone from the Wagtail documentation team attend to me on this one? I think the graphical representation of  Streamfield will serve as an **easy reference** for developers, which will be extremely useful to developers. It will make grasping Wagtail easier. Personally, I would think it would make transversing the documentation/code be with more ease and direction. Developers can just know what subclass of Streamfield they need from looking it up the graphic, and navigating to the documentation they need to use that class.

I would even suggest in addition , perhaps, some UI writing be done for each node on the tree diagram, so developers can have an idea of a class and its purpose. It will further help developers quick access to getting things done with Wagtail.

**Comment by thibaudcolas** [comment]
👍 generally I think diagrams or visual representation in the documentation would be nice. A class / model hierarchy seems like an interesting one to do.

@Temidayo32 for your contribution in particular – I would suggest starting small with StreamField, in the following order:

1. Do a bit of research on the different tools and types of diagrams we could produce for StreamField
2. Try a couple on StreamField only and report back here for feedback

An important point for us in particular is that any visuals need to be straightforward to update, so we have to think of tools that make this possible.

**Comment by Temidayo32** [comment]
Thanks so so much @thibaudcolas I will immediately begin and report back.

**Comment by Temidayo32** [comment]
@thibaudcolas Here is a report back on my findings on the best tool for that would suit our purpose.

I reviewed four diagramming tools namely Miro, Diagrams.net, Graphvix, Mermaid.js, and I **think Mermaid.js is the best option**.

Miro and Diagrams.net are both image diagramming tools that involve drawing shapes and diagrams using drag and drops. This could pose a barrier to suit the goal you mentioned above: **visuals that are straightforward to update**. 

It would be more safe to assume documentarians for Wagtail are writers, and not visual designers. Drawing whole diagrams might call up a lot of expertise with designing: colors, drawing shapes and boxes, structure of the diagram and all that. These are activities that could be painful and frustrating.  I would think for future considerations, you will want anybody to be able to work on the diagram without facing too much barriers due to lack of design skills.

Then secondly, since Wagtail is under Git control, tracking changes to images and diagrams using both tools wouldn't be very feasible. Thirdly, Miro is a tool with a paid version. The free version can only support 4 team members. I would think you will want as many doc team members as possible access to any task or work. 

Fourthly, with diagramming tools, then we have to think about importing these images, resizing them to fit the page, which could birth further complexities and need to use even more tools.

**While Graphiz** would be great to use, as it suports diagramming with text and code., it lacks a modern appeal and easy syntax that would make it easy to learn.

**Mermaid.js** on the other hand is diagramming tools that allows the creation of diagrams using **Markdown-inspired syntax**. I belief it is safe to assume all Wagtail doc team members can all work with Markdown, so this tool would have a low barrier in terms of learning to use it. It is completely open source and free which is great for Wagtail. Then, since it stores diagrams as text, it is easy to track changes using Git. 

**And then lastly, all changes can be done to the diagram right inside the documentation**. There is an extension that allows us to easily integrate Mermaid.js into Wagtail sphinx documentation.  Check out [Sphinxcontrib-mermaid](https://github.com/mgaitan/sphinxcontrib-mermaid).


You can read this Medium story to get some further insights on UX of Mermaid.js https://towardsdatascience.com/mermaid-create-diagrams-quickly-and-effortlessly-d236e23d6d58

**Comment by Temidayo32** [comment]
@hazho Just some more information from you. In the graphic, what information do you want exposed? For instance, working with the StreamField, we could have an inheritance diagram that shows all the block types and their relationships and inheritance between different blocks. 

Mind you, this might involve exposing information of some internal block type that are **not** exposed as an API for working with Wagtail when writing your models. A good example is the FieldBlock. The CharBlock inherits from it, but it is not [documented here](https://docs.wagtail.org/en/stable/reference/streamfield/blocks.html#streamfield-block-reference) as a Wagtail API. So a sort of diagram like would be more complete with more information but **complex** and **large**.

On the hand, we could have a simpler diagram that just mentions all the block types in the documentation (that same documentation). What do you think?

**Comment by Temidayo32** [comment]
@thibaudcolas @hazho Here is  prototype diagram. Let me know what you both think of it. 
https://mermaid.ink/svg/pako:eNqVlM1u4jAQgF_FmkNP6aqU0qo5VCp00a4E0jawl1UuU2dKrHXsyHa6sJR3r0lICNBINKf5_cYz43gNXCcEISwM5imbRLFi_rPFS2V4fLHOIHdsJNHayjmUmv9llUwqOcqYolCn0ZeXD2wsSCal2pU7FsY6NqE3kpVnn1IS2Htp2DHnq5ze2ShFU-kXbE5LV8tjqbFRnoiLDGWr-BH5E3BEC1rWgN_RpBaHWktC1aDR0Ze424S5yKgG_FTOV2p6GKKlUaoF_xr1e4ZC1oxI8LQ9iwj__ZhPmw48Xttdxa5VzIhrlbR3sQd2HKGUnwt9MI9zyEctd_HbIRdsWkgncnk6q3MqtifQVe4XLuggzq8qO7XNlMhzcufM9OR6t-rPnCm4KwzKg0NMhG22WIW0NMJsr6ET_LA6BJCR8fci8f_3emuOwaWUUQyhFxN6RT_DGILKxQvztnNJoQhNDLHaeAgWTs9WikPoD0ABFHnir_CTQN9VBuErSuutlAinzbR6TcpHJYAcFYRrWEJ4fTf4Nrjt3wz6_Zu73n3vNoAVhFebAP5r7SG9MvhPKW-rbD4AMmKDxA

**Comment by Temidayo32** [comment]
This is done using Mermaid.js. There is lot more interactivity that could be added to this diagram, but might involve some Javascript code.
A built functionality allows us to hyperlink each node. I think that would super helpful so we can hyperlink each node to their main documentation content.@hazho 
Then, I could add some Javascript code that allows some pop up text when you hover on each node. Check out this one for an idea of what I am saying: https://jsfiddle.net/s37cjoau/3/

**Comment by hazho** [comment]
@Temidayo32 this is good, except if you rotate it to become a vertically generated, would be much easier to see and feed the developer's imagination

**Comment by hazho** [comment]
and for the first question you asked, you can add some descriptions and labels to indicate for each

**Comment by Temidayo32** [comment]
@hazho Yeah, I would have prefered the vertical format, but then, it would have been too wide to fit into a web page. Then the tool is limited, and wouldn't allow me to change the layout. I am thinking of how to get around that. I might need some code to change that

**Comment by easherma-truth** [comment]
https://django-extensions.readthedocs.io/en/latest/graph_models.html would also be nice for generating graphs dynamically from the code itself

**Comment by Temidayo32** [comment]
Nice suggestion @easherma

**Comment by thibaudcolas** [comment]
Nice work @Temidayo32! I think Mermaid would be a nice addition to our documentation capabilities, as well as a good fit for what we’re doing here.

However, if what we want is a classic inheritance diagram, as Eric mentions, it might be even better to use Django/Python-aware tools. We have trouble updating screenshots when code changes, I’d expect the same with diagrams, so any tools that allows the docs to be derived from the code should be conisdered first and foremost.

Let’s ask people in #documentation on Slack what they think.

**Comment by Temidayo32** [comment]
@thibaudcolas That's a good consideration. I am okay with that!

**Comment by hazho** [comment]
What about https://kolo.app/

**Comment by Temidayo32** [comment]
Hi @hazho  I think your idea of a graphical diagrams for the StreamField class was a good one. I have tabled it before the documentation team for a thorough review to ensure it fits easily into the Wagtail documentation standards and laid down processes, but in order to avoid future documentation issues, it won't be incorporated at the moment. 

The major push back was due to the maintenance burden of working with diagramming tools. 

Currently, Wagtail text reference documentation are auto-generated from the source code, which as you would expect, would evolve naturally as the code base changes. This lessens the maintenance burden.

 Diagrams require some manual work. With more diagrams comes the need to track each diagram and ensure changes are done to them given any change in the code base. This is where the maintenance burden might pose an issue that could jeopardize the Wagtail documentation quality.

 I hope you understand.

However, if you want I could provide you the Mermaid.js code I used in creating the graph above. It is a very easy syntax. You could have this implemented locally in a forked branch of this documentation repo for the benefit of your team. How does that sound?

**Comment by Temidayo32** [comment]
@hazho And for your information, we decide to touch up the StreamField documentation, with some **Colour highlighting, indentation, and inheritance** for the StreamField classes. Watch out for the next documentation release. Here is a pull request on this: https://github.com/wagtail/wagtail/pull/9451


Also, we also considered adding to the reference guide documentation on internal classes. Would that help?

**Comment by hazho** [comment]
Thanks @Temidayo32, I was expecting the same burden, however, there are tools that do automate the diagram processing, it will be worthy to do your researches for that, meanwhile me and my team are way far from wagtail, though we may need this in the future points.. but yes I understood, in deed this idea may help other wagtail developers more than me and my team, thanks again, and happy coding.

**Comment by Temidayo32** [comment]
Thanks for your understanding, @hazho

**Comment by Temidayo32** [comment]
@thibaudcolas @Lb I think this issue might be considered closed.
