### ISSUE TITLE
Unpublished content can become visible when using a ParentalKey relation

### ISSUE THREAD

**Issue by akrawchyk** [wagtail/wagtail#906]
Wagtail does not protect you from publishing draft content when it is related to a Page with a ParentalKey and ForeignKey. For example:

```
class HomePageFeaturedEvents(Orderable, models.Model):
    page = ParentalKey('app.HomePage', related_name='featured_events')
    event_page = models.ForeignKey(
        'events.EventPage',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

class HomePage(Page):
    # yadda yadda

HomePage.content_panels = [
   # yadda yadda
    MultiFieldPanel(
        [
            InlinePanel(HomePage, 'featured_events', label="Featured events"),
        ],
        heading="Featured Events",
        classname="collapsible collapsed",
    ),
]
```

_Scenario:_
1. User creates draft event page
2. User assigns draft event to featured slot on a live home page
3. User submits live home page changes for moderation
4. Moderator approves live home page changes
5. System publishes live home page
6. Draft event page becomes visible in featured home page content. (note: draft event page is still technically not public, i.e. navigating to the page will result in a 404).

**Comment by gasman** [comment]
Hi @akrawchyk - thanks for pointing this out. There's an extra subtlety here that hadn't occurred to me up to now, which is that any subsequent edits to the draft page are immediately reflected on the homepage without going through moderator approval. Not ideal...

Do you have any suggestions on how we could do this differently? I don't think we can realistically impose a complete block on links to draft content (either during page editing or at the point of publication) because it's quite common for people to work on a new section of a site with many interlinked pages in draft, before putting them all live in one go at a determined time. The best we can do is probably a warning to the moderator, perhaps on the preview screen. Ultimately it still relies on the moderator to be aware of where the content is coming from, and know what should and shouldn't be published at any time - which is probably a reasonable thing to expect from them!

**Comment by akrawchyk** [comment]
> any subsequent edits to the draft page are immediately reflected on the homepage without going through moderator approval. Not ideal...

Is there a way to lock an approval request against a page revision? That way, more revisions can be created and only the previously approved revisions would be published.

> I don't think we can realistically impose a complete block on links to draft content (either during page editing or at the point of publication) because it's quite common for people to work on a new section of a site with many interlinked pages in draft, before putting them all live in one go at a determined time.

A complete block would be too inflexible, I agree. But to me the draft state indicates that the draft content will not be publicly visible. For now, can we filter the draft states from either the template context or the wagtailadmin page choose modal workflow?

> Ultimately it still relies on the moderator to be aware of where the content is coming from, and know what should and shouldn't be published at any time - which is probably a reasonable thing to expect from them!

Definitely agree this is something that might not work with strict defaults. However, the current process needs improvement at least for transparency to the user. I'm thinking it could be a setting with different strictness values. For example, no warning, warn when approving/publishing, error when approving/publishing. Maybe even have a button to auto adjust the go_live_at field of anything to be published to make it easy to fix for the user.

**Comment by gasman** [comment]
> Is there a way to lock an approval request against a page revision? That way, more revisions can be created and only the previously approved revisions would be published.

This is how it works at the moment - moderation requests are tied to specific page revisions, so that the moderator sees the page in the state that it was at when the editor clicked "Submit for moderation", regardless of any subsequent edits. However, this doesn't deal with pages that display content sourced from other pages, as in this example - that would entail making a snapshot of the entire database for each moderation request...
