### ISSUE TITLE
Documentation note with misplaced header

### ISSUE THREAD

**Issue by jsma** [wagtail/wagtail#9125]
There is a small issue with this note on the [Inline Models](https://docs.wagtail.org/en/stable/topics/pages.html#inline-models) documentation:
<img width="968" alt="Screen Shot 2022-09-01 at 9 51 25 AM" src="https://user-images.githubusercontent.com/24574/187985320-b0c65ade-42f0-4e9e-a5d3-717e7f3ef5cc.png">

It appears "django-modelcluster and ParentalKey" was meant to included in the note header after "Note". According to the [MyST documentation](https://myst-parser.readthedocs.io/en/latest/syntax/roles-and-directives.html#admonitions), `{note}` does not accept any arguments, only `{admonition}` does. At the same time, the [contributing docs](https://docs.wagtail.org/en/stable/contributing/documentation_guidelines.html#call-outs) say that only `{note}` and `{warning}` are allowed for Wagtail documentation.

I intended to submit a PR but it's not clear to me what the solution is. Remove the "django-modelcluster and ParentalKey" entirely and call it a day? Switch to `{admonition}`, which does accept arguments, and update the contributing docs to say this is also allowed? Something else entirely?

**Comment by lb-** [comment]
PR up - the title itself is not really required here as the sentence uses the same two items a few words in.
I have also added clarity that we do not need to use `admonition` https://github.com/wagtail/wagtail/pull/9143

While these call outs are helpful in some cases, they should be kept to a minimum so that the docs are kept simple.

Thanks @jsma
