### ISSUE TITLE
Chooser modals without tabs are missing top margin above search/filter forms

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9130]
### Issue Summary

Snippet chooser modals with search/filter forms are missing a top margin:

![Screenshot 2022-09-02 at 15 27 45](https://user-images.githubusercontent.com/85097/188171182-2575104a-2bfe-48f6-bb1c-76c33422ef77.png)

To test on bakerydemo, edit a blog post and click Change on the Author field.

In other choosers, such as the document chooser, this margin is added as a bottom margin on the `.w-tabs__wrapper` class, but snippet choosers do not have tabs as standard.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.8.0
-   Django version: 3.2.15
-   Wagtail version: 4.0 / main
-   Browser version: Chrome 104.0.5112.101

**Comment by lb-** [comment]
Can confirm this issue is happening in 4.0 code, looks like `wagtail/admin/templates/wagtailadmin/generic/chooser/chooser.html` still uses the tabs container but does not set multiple tabs in this scenario.

This also triggers a console error, this does not block anything but should be fixed also.

<img width="1831" alt="Screen Shot 2022-09-07 at 3 51 46 pm" src="https://user-images.githubusercontent.com/1396140/188804524-dbc66281-041e-4f9b-a184-1ea662b41449.png">
