### ISSUE TITLE
Document option not appearing in new editing UI via slash command or "+" button.

### ISSUE THREAD

**Issue by nicksergeant** [wagtail/wagtail#9171]
### Issue Summary

There appears to be a bug where you cannot insert a document without first typing text and then highlighting it to get the toolbar to appear.

### Steps to Reproduce

1. Type `/` in a rich text field
2. Note that while `Image` exists, there is no option for `Document`:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/27332/189135063-a4ab2474-fca5-4952-9957-34eac1fa6c8c.png">

But if you type some text and highlight it, Document option appears in the toolbar:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/27332/189135190-f9784410-0fa0-4554-b6a1-a0faf88a39d8.png">

Clicking the "+" also does not show the Document option:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/27332/189135274-89252137-c5ed-40b1-b6fd-19eb72e10b29.png">

### Technical details

-   Python version: Run `python --version`.

3.10.6

-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.

4.1

-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.

4.0.1

-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

Version 104.0.5112.101 (Official Build) (arm64)

**Comment by gasman** [comment]
This is by design - a document link is not a block-level element, but a piece of formatting applied within a paragraph, just like bold / italic or a regular link, so it makes sense to treat it consistently with those.

**Comment by nicksergeant** [comment]
@gasman huh, interesting. I can see how that distinction is made. I've had several users report this as a bug within the first few days of releasing the new UI, so I think this will be common confusion.

Is there a hook we can use to add to the slash and "+" commands to somehow trigger the document insert functionality?

**Comment by bdarfler** [comment]
@gasman as one of those users who have reported this as a bug to @nicksergeant I wanted to add some more color.

Today I was adding a new document to a list of documents on a particular page. Before the update, I could simply click the document button in the edit bar, upload the document, and it would insert the document title as text and link to the document itself. It was a very easy and intuitive user flow.

Now, the flow is significantly different. First off, there is nothing in the UI that points me in the direction of how I would even add a document. It was only after a lot of headbanging that I noticed there was an edit bar that popped up when I selected text and only because I'm observant did I notice a little document icon in that edit bar. Having now figured out how to actually add the document I have to type out the full document name (which is annoying because the system used to do this for me) and then highlight it and then upload the document.

As someone who currently works in OSS for my day job I hate to be a pain but as a user here I would really love it if you could make this less painful ❤️
