### ISSUE TITLE
Translations conflate "Change" and "Edit" terminology

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9201]
Follow-up to #9113. We have translations currently using the same terms for Wagtail’s "Edit" and "Change" concepts – which denote similar concepts in English, but in Wagtail are technically different.

From what I understand, "Change" is our name for the `change` permission coming from Django. In Wagtail,

- "Edit" is what we consistently use to refer to the "Update" functionality from CRUD.
- "Change" means the user can access Wagtail’s "Edit" functionality for content they don’t own themselves.

Even if both terms don’t appear side-by-side like on #9113, it’s still problematic that translations conflate both under the same name, while we don’t in English. Either we should stop using the vague "Change" denomination in English too, or we should update translations to use different terms.

**Comment by lb-** [comment]
I think change and edit are too similar, even in English. 

We should look at a different term for change (to mean change the value of an existing selection). Even change selection might be better.

**Comment by gasman** [comment]
To clarify - with #9113 applied, we're back to using "Choose another" for "change the value of an existing selection", so that particular case is already solved (unless the decision on #9200 is that "Choose another" is unsatisfactory too, in which case we need to decide on something that's better than both "Change" and "Choose another").

If I'm following correctly, the only place where "Change" is used now is in the name of the permission. This is Django's standard, so I don't think it's wise for Wagtail to go against this.

The nuance about a user being able to edit their own content (but not other people's) even without Change permission is _not_ a terminology issue - it's a special case in Wagtail's business logic for pages (and other models that have a concept of ownership, such as images and documents) where we've slightly repurposed Django's built-in permissions since it's more useful that way. For other models, such as snippets, the "add" and "change" permissions exactly map to the add and edit views.

**Comment by lb-** [comment]
Agreed.

**Comment by thibaudcolas** [comment]
@gasman I’d like to keep this opened until we’ve had a chance to discuss this if that’s ok with you. Since this is about translations, I’d like to get input on this from people who work on translations in particular. And specifically those who work with languages where the same terms are used for both concepts.

I agree it’s not a big deal and not all languages might want to express the difference between two very similar terms, but then that means the concepts can’t be distinguished from one-another by end users. That’s a clear UX issue to me. And there are clear ways to improve upon this that won’t take much effort:

- Get the translations changed for languages that can convey the difference
- Add extra context, either as a longer label, or tooltip, or help text, so the concepts can be distinguished even when using the same terms ("Change (includes all state modifications)")

On "Change" in particular, if it does convey special meaning to people familiar with Django, then adding that extra context in the UI would likely be very beneficial to all users in all languages, as lots of people who set permissions in the CMS won’t have any understanding of why we use "Change" for object permissions and "Edit" elsewhere.

**Comment by gasman** [comment]
Given that there's been no movement on this for the last 18+ months, I'd like to push for this to be closed again.

@thibaudcolas, it sounds like your position here is: Wagtail's UI strings use "edit" in some places and "change" in others, and it's possible that the semantic similarity of these could cause as-yet-unidentified issues. We should therefore talk to translators and UX specialists to find out if any such issues exist.

While I accept that an issue _could_ potentially exist - and I'm not inherently against doing further research on the subject - at this moment there's no evidence that a problem _does_ exist, and I feel we should hold off on having an open Github issue for it until that's been established. There are any number of aspects of Wagtail where I could theorise about potential bugs ("what happens if you use emoji in a page slug", to pick a totally arbitrary example :-) ) - but given that there's no shortage of existing confirmed issues to keep us busy, this sort of pre-emptive bug hunting is inevitably going to sit at the bottom of our priorities, and that doesn't seem like an effective use of Github issues.

When this did cause an identifiable issue in the past (#9045, #9113, #9193) people were quick to report it, and I believe we can trust that to happen again in the event that it does arise in another form.

**Comment by thibaudcolas** [comment]
@gasman makes sense to me! Closing now, and we’ll reconsider if/when people report this in the future. In any case, a very likely course of action would be changes in the translation strings rather than the code.

For future ref, here are our current translations for the standalone "Edit" and "Change" label. There are 6 that use the same word (Estonian, French, Indonesian, Italian, Dutch, Portugal Portuguese).

| Locale | Edit text | Change text | Identical text ? |
| ------ | --------- | ------------ | --------------- |
| en | "Edit" | "Change" |  |
| ar | "تعديل" | "غيّر" |  |
| be | "Рэдагаваць" | "Змяніць" |  |
| ca | "Editar" | "Canviar" |  |
| cs | "Editovat" | "Upravit" |  |
| cy | "Golygu" | "Newid" |  |
| de | "Bearbeiten" | "Ändern" |  |
| el | "Επεξεργασία" | "Αλλαγή" |  |
| es | "Editar" | "Cambiar" |  |
| et | "Muuda" | "Muuda" | Yes |
| fa | "ویرایش" | "تغییر" |  |
| fi | "Muokkaa" | "Muuta" |  |
| fr | "Modifier" | "Modifier" | Yes |
| gl | "Editar" | "Cambiar" |  |
| he_IL | "ערוך" | "שנה" |  |
| hr_HR | "Uredi" | "Promijeni" |  |
| hu | "Szerkesztés" | "Megváltoztatás" |  |
| id_ID | "Ubah" | "Ubah" | Yes |
| is_IS | "Breyta" | "Breyta" |  |
| it | "Modifica" | "Modifica" | Yes |
| ja | "編集" | "変更" |  |
| ka | "რედაქტირება" | "შეცვლა" |  |
| ko | "수정" | "변화" |  |
| lt | "Redaguoti" | "Keisti" |  |
| lv | "Labot" | "Mainīt" |  |
| mi | "Whakarerekē" | "Panoni" |  |
| mn | "Засах" | "Солих" |  |
| my | "ပြင်ဆင်ပါ" | "ပြောင်းလဲပါ" |  |
| nb | "Rediger" | "Endre" |  |
| nl | "Wijzigen" | "Wijzigen" | Yes |
| pl | "Edytuj" | "Zmień" |  |
| pt_BR | "Editar" | "Alterar" |  |
| pt_PT | "Alterar" | "Alterar" | Yes |
| ro | "Editează" | "Modifică" |  |
| ru | "Редактировать" | "Изменить" |  |
| sk_SK | "Upraviť" | "Zmeniť" |  |
| sl | "Uredi" | "Spremeni" |  |
| sv | "Redigera" | "Ändra" |  |
| tet | "Hadia" | "Troka" |  |
| th | "แก้ไข" | "เปลี่ยน" |  |
| tr | "Düzenle" | "Değiştir" |  |
| tr_TR | "Düzenle" | "Değiştir" |  |
| uk | "Редагувати" | "Змінити" |  |
| vi | "Biên tập" | "Sửa" |  |
| zh_Hans | "编辑" | "更改" |  |
| zh_Hant | "編輯" | "更改" |  |
