### ISSUE TITLE
Chooser buttons not visible on hover with wagtail 4.0.2

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9260]
### Issue Summary

The [issue](https://github.com/torchbox/wagtailmedia/issues/175) I've created for wagtailmedia initially, seems to be an issue with these changes https://github.com/wagtail/wagtail/commit/44d954e00a6f894eb6951f9fcbb9285a0bf1946b. Because the problem also exists for simple custom choosers created as described in the [docs](https://docs.wagtail.org/en/stable/extending/generic_views.html#chooserviewset).

The changes in the above changeset seem to be very specific with class names and this does not work with any custom chooser (like the one for wagtailmedia).

### Steps to Reproduce

1. Start a new project with `wagtail start myproject` or use the bakerydemo
2. Create a custom chooser as described in https://docs.wagtail.org/en/stable/extending/generic_views.html#chooserviewset
3. Use this chooser in the admin and as soon as you select an object, you won't see the actions when hovering the widget.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 3.2, 4.1
-   Wagtail version: 4.0.2
-   Browser version: Firefox 105

**Comment by thibaudcolas** [comment]
Thanks for the report @th3hamm0r. This is because we switched to relying on the widget types for those styles, and currently our widget-specific classes only allow us to target the field widget’s own class rather than any of the inheritance chain.

Template tags we rely on: https://github.com/wagtail/wagtail/blob/82119360acf19961bf6169290995c916fdfe9bb6/wagtail/admin/templatetags/wagtailadmin_tags.py#L113-L132

And the styles in question: https://github.com/wagtail/wagtail/blob/82119360acf19961bf6169290995c916fdfe9bb6/client/scss/components/_chooser.scss#L86

Perhaps the solution would be to introduce a new `widgettypes` filter that outputs one class name per class in the inheritance hierarchy of the widget? So we can add our styles based on inheriting from `BaseChooser`, with a `w-field--BaseChooser` class name?

**Comment by stanpresshook** [comment]
As a hotfix for any active projects, override the `.chooser__actions` class in your custom admin css file with `opactiy: 1 !important`

**Comment by thibaudcolas** [comment]
@stanpresshook keep in mind we’ve intentionally changed the chooser action buttons to be hidden by default. If you make this specific change, the buttons will always be visible, for all choosers, even once we roll a fix in Wagtail.

Here is the fix I’m intending to add to Wagtail itself:

```css
:is(.w-field--model_choice_field):is(:hover, :focus-within) .chooser__actions {
    opacity: 1;
```

Not my favourite approach to rely on form fields’ class names rather than widget class names, but in this instance I’m not expecting issues with this.

**Comment by jsma** [comment]
> keep in mind we’ve intentionally changed the chooser action buttons to be hidden by default.

I sort of understand why, at least on a long page with lots of things going on, but in the case of the "move" confirmation page, this means the most important buttons on the page are hidden by default:

<img width="1101" alt="Screen Shot 2022-10-18 at 1 59 12 PM" src="https://user-images.githubusercontent.com/24574/196543631-da933f19-69c4-4dbd-863a-97390b5afc58.png">

The help text "Select a new parent" is displayed by default, but the actual action buttons are not which leads to confusion. Editors see the "Confirm" button and expect there to be other buttons nearby, but they can only find these buttons if they move their mouse _above_ the help text and confirm buttons (rather than adjacent to them) to the page title container.
