### ISSUE TITLE
PageChooserBlock missing in documentation

### ISSUE THREAD

**Issue by andre-fuchs** [wagtail/wagtail#9287]
Somehow the documentation of the PageChooserBlock went missing. The last version I could find it in is 2.12.5, see link below.

### Pertinent section of the Wagtail docs
**Before**:
[https://docs.wagtail.org/en/v2.12.5/topics/streamfield.html#pagechooserblock](https://docs.wagtail.org/en/v2.12.5/topics/streamfield.html#pagechooserblock)

**After** (some block types missing):
https://docs.wagtail.org/en/v4.0.2/topics/streamfield.html

**Comment by Temidayo32** [comment]
Hi @andre-fuchs The reason the PageChooserBlock didn't appear in the documentation you referenced is because it is not a Structured block. It is a basic block type, and the latest documentation for Wagtail separated the documentation. You can find PageChooserBlock here.

https://docs.wagtail.org/en/latest/reference/streamfield/blocks.html#wagtail.blocks.PageChooserBlock

**Comment by gasman** [comment]
Thanks @Temidayo32!
