### ISSUE TITLE
Page title visual cue that it is a field

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#9318]
I notice that users are skipping the first field Title, "page title" in wagtail 4.0. They are not aware of that this is a form field. So there is slight learning curve. However they keep missing it even when knowing this need to fill it in.

Maybe it would be good to have a better visual que or auto focus on this field so they can't mis it when creating a page or changing a page?

<img width="1116" alt="screen" src="https://user-images.githubusercontent.com/178425/195303329-1e956b37-5f54-4091-842b-0ef111a55fe3.png">

**Comment by Theresa-o** [comment]
This UI would be improved

**Comment by Theresa-o** [comment]
@thibaudcolas I can confirm that this is a UI semantics bug that needs to be fixed.

I propose that in order to make it easier for the User to easily fill the Title Field, I make the following changes;

- We create the page title as a label for with a bolder text and the same colour as subtitle and introduction
- We create a border making it easier for users to notice that it is a form field that should be filled

This would help the users easily notice that this field is clickable and should be edited.

I would start working on this immediately and provide feedback

**Comment by thibaudcolas** [comment]
@onno-timmerman thanks for the feedback! So far we’ve acknowledged this was a potential issue but decided to give it a go anyway. We were hoping the help text underneath might be enough indication that this is a field, as well as the addition of the asterisk to indicate it being required (#9028).

Do you think the asterisk could be enough? Or that people you work with could get used to this?

@Theresa-o if you spend more time looking at the code you will notice it’s very much intentional for this field to look different. All fields normally have a label as well as a border. We took those out for this field in particular, so we can make this larger text style work and to reduce the overall height of the page.

**Comment by Theresa-o** [comment]
@thibaudcolas Should I work on something else while waiting for onno-timmerman feedback or I should go ahead and implement the change?

**Comment by thibaudcolas** [comment]
@Theresa-o I’ve marked this issue as "needs info" and "needs UI design", so we need to agree on what needs to be done before anyone makes any change. If you want to work on other issues that aren’t explicitly marked as "good first issue" – please always start by investigating the code and reporting back your finding, so we agree on where the issue comes from. Making the change is the last part of the process.

**Comment by Seremba** [comment]
Hi @thibaudcolas, I was working on this issue! I added an autofocus attribute such that when one is creating a new page, the title field is automatically under focus. This will help users to identify that the field needs to be filled in. Should I go on with it or I stop there? 

@onno-timmerman is what I have described above what you meant? Thanks a lot

**Comment by Theresa-o** [comment]
Hello @thibaudcolas While, we await more info, I edited the code to show what it would look like if a border is added to the title.

![pagetitleUIdesign1](https://user-images.githubusercontent.com/62052443/196051200-838e18d9-92aa-4803-b599-bd1b087ac8ac.PNG)

**Comment by thibaudcolas** [comment]
@Seremba autofocus wouldn’t be appropriate for this, as we can’t expect people arriving on this page to necessarily want to interact with that specific field. It’d be confusing for keyboard users if they are taken straight to one specific field like this.

**Comment by Seremba** [comment]
Oh! I had not given that a thought. It makes sense!

**Comment by Seremba** [comment]
@thibaudcolas I sent a message on slack, you must have been busy though. Kindly if you get time check your slack inbox

**Comment by Theresa-o** [comment]
@thibaudcolas, should I go ahead implementing this.

> Hello @thibaudcolas While, we await more info, I edited the code to show what it would look like if a border is added to the title.
> 
> @onno-timmerman i believe this would make users UI journey easier, please share your thoughts on this.
> 
> ![pagetitleUIdesign1](https://user-images.githubusercontent.com/62052443/196051200-838e18d9-92aa-4803-b599-bd1b087ac8ac.PNG)

**Comment by onno-timmerman** [comment]
Looks perfect for me! :)

**Comment by Theresa-o** [comment]
@onno-timmerman Awesome to know

@thibaudcolas Should I go ahead updating?

> Looks perfect for me! :)

**Comment by thibaudcolas** [comment]
@Theresa-o No. As stated above this really doesn’t need a new implementation at this stage, but consensus that there is a problem. I feel like I’m just repeating myself now but it’s very much intentional for there _not_ to be a border!

I’ll check with our designer as well, personally I’m not convinced it makes sense for us to change this – if there’s a confusion it’d only be the first time people encounter this, and it should be quicky resolved.

**Comment by Theresa-o** [comment]
@thibaudcolas Got it

**Comment by thibaudcolas** [comment]
For everyone interested in this, we’ve adjusted slightly in #9719 by using `:placeholder-shown` so the title field’s border appears when the field is empty. We’re hoping this alleviates the problem without us having to rely on autofocusing the field, which could cause issues for screen reader and keyboard users.
