### ISSUE TITLE
Wagtail 4.0.2 Orderables still broken

### ISSUE THREAD

**Issue by Elrigor** [wagtail/wagtail#9389]
Hi!
I recently saw in an issue that orderables were broken and then fixed. However, they still broke for me.

Are they fixed? Thx! :D

This is the issue
[](https://github.com/wagtail/wagtail/issues/9145)

**Comment by lb-** [comment]
@Elrigor  please can you provide a bit more detail - we have not received any further feedback that this is a problem.

One user was using an external package (multi image upload from memory) but the bug was with that package.

**Comment by gasman** [comment]
In fact the issue I'm seeing also occurs on 3.0.3 and 2.16.3, so if you only saw it emerging in 4.0 then this is probably something different. In any case, I'll continue investigating, since there might be something subtle about this model that triggers both issues.

**Comment by gasman** [comment]
Just realised what's causing the issue I'm seeing - the `min_num=1` causes an initial form to be rendered (which wouldn't usually be the case - normally you'd have to explicitly "add image" to get the first form), and that form has a blank value for the hidden 'order' field. I'll open a new issue for that - not sure how long that bug has been around for, and I'm pretty sure it's not related to the 4.0 regression.

Once I get past that initial bug, ordering is working as expected for me - I'm testing on a fresh Wagtail 4.0.2 installation, with home/models.py changed to match your model definition (just with the `content` StreamField changed to built-in block types rather than your custom ones, and `FieldPanel("banner_subtitle")` added to `content_panels` to make it a valid form submission).

A couple more questions:

* Are you seeing this bug on a local development site, or a production server?
* Have you force-refreshed the page since upgrading to 4.0.2, to ensure that you're using the most up-to-date version of Wagtail's Javascript files?
* If this is a production server, did you run `./manage.py collectstatic` after upgrading to 4.0.2?
* Are you able to replicate this issue on a newly-created Wagtail project?

**Comment by lb-** [comment]
No issue has been opened as per comment above - https://github.com/wagtail/wagtail/issues/9391

**Comment by Elrigor** [comment]
Hi! it is solved now :D!

The website is in a production enviroment in a server. Removing the `min_num=1`, making `migrations` and then `collectstatic` seemd to fix the problem.

Not it's working as intended. Thank you so much, I've been struggling with this for a week now :(

**Comment by lb-** [comment]
Glad you got it resolved - @Elrigor
