### ISSUE TITLE
Grammatical adjustments for page models not addressed in PR #9395,

### ISSUE THREAD

**Issue by activus-d** [wagtail/wagtail#9398]
## Issue Summary
Grammatical adjustments, which were not addressed in PR #9395, are needed on the [Pages model](https://github.com/wagtail/wagtail/blob/main/docs/topics/pages.md#page-models) section of the `Usage guide` to enhance readability

**Comment by activus-d** [comment]
I'm working on this already.

**Comment by thibaudcolas** [comment]
@activus-d sorry I have to reverse course a bit on this – As I’m sure you can realise, there isn’t that much value in opening an issue for grammar changes. If you open an issue, then it needs to stand out on its own for us to understand what the problem is and discuss a solution. Creating an issue without describing either of those is pointless.

**Comment by activus-d** [comment]
@thibaudcolas Well understood. I would take note of that subsequently.
