### ISSUE TITLE
Grammatical adjustments for `Search index page` usage guide not addressed in PR #9395

### ISSUE THREAD

**Issue by activus-d** [wagtail/wagtail#9402]
Grammatical adjustments, which were not addressed in PR #9395, are needed on the [Search index page](https://github.com/wagtail/wagtail/blob/main/docs/topics/search/index.md#search) section of the Usage guide to enhance its readability.

**Comment by activus-d** [comment]
I'm working on this already.

**Comment by thibaudcolas** [comment]
@activus-d sorry I have to reverse course a bit on this – As I’m sure you can realise, there isn’t that much value in opening an issue for grammar changes. If you open an issue, then it needs to stand out on its own for us to understand what the problem is and discuss a solution. Creating an issue without describing either of those is pointless.
