### ISSUE TITLE
Grammatical adjustments for advanced topic `images` 

### ISSUE THREAD

**Issue by activus-d** [wagtail/wagtail#9407]
## Issue Summary
Grammatical adjustments are needed in the advanced topic [images](https://github.com/wagtail/wagtail/tree/main/docs/advanced_topics/images) for better readability.

**Comment by activus-d** [comment]
I'm working on this already.

**Comment by adetyaz** [comment]
@activus-d please can i join you on the documentation. I'm new here and I'm just wrappng my head around it all

**Comment by activus-d** [comment]
@adetyaz you can read through the documentation there are so many issues to be resolved. If you need additional help getting started, you can message me via the wagtail official slack channel.

**Comment by adetyaz** [comment]
Thanks alot, I'll do that

**Comment by thibaudcolas** [comment]
@activus-d sorry I have to reverse course a bit on this – As I’m sure you can realise, there isn’t that much value in opening an issue for grammar changes. If you open an issue, then it needs to stand out on its own for us to understand what the problem is and discuss a solution. Creating an issue without describing either of those is pointless.

**Comment by thibaudcolas** [comment]
@activus-d sorry I have to reverse course a bit on this – As I’m sure you can realise, there isn’t that much value in opening an issue for grammar changes. If you open an issue, then it needs to stand out on its own for us to understand what the problem is and discuss a solution. Creating an issue without describing either of those is pointless.
