### ISSUE TITLE
Grammatical adjustments for advanced topic `Documents`

### ISSUE THREAD

**Issue by activus-d** [wagtail/wagtail#9425]
## Issue Summary
Grammatical adjustments are needed in the advanced topic [Documents](https://github.com/wagtail/wagtail/tree/main/docs/advanced_topics/documents) for better readability

**Comment by thibaudcolas** [comment]
@activus-d sorry I have to reverse course a bit on this – As I’m sure you can realise, there isn’t that much value in opening an issue for grammar changes. If you open an issue, then it needs to stand out on its own for us to understand what the problem is and discuss a solution. Creating an issue without describing either of those is pointless.
