### ISSUE TITLE
Comments notice background overflows its container

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9446]
This is tagged as a [**good first issue**](https://github.com/wagtail/wagtail/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) – if you want to take it on, please leave a comment below to say so, no need to ask for permission, first come first serve! State your intent and share any questions / plans you have on how to approach the task.

### Issue Summary

Our comments’ notices overflow their parent container, thereby lacking the rounded corners at the bottom:

<img width="244" alt="Screenshot 2022-10-20 at 22 03 51" src="https://user-images.githubusercontent.com/877585/197057735-da3f1d57-3fad-4c2f-9e41-b495fb728590.png">

It would be nice for this to get the same rounded corners as the top of the comment’s floating box.

### Steps to Reproduce

1. Go to a page editing interface and switch on Comments
2. Add a new comment and click "Save"

### Proposed solution

I believe we’d need to add border-inline-start and border-inline-end radius declarations matching the radius defined for the whole block, to the notice element: https://github.com/wagtail/wagtail/blob/main/client/src/components/CommentApp/main.scss#L57

**Comment by thibaudcolas** [comment]
Assigning this one to **Yeka Asumah**.

**Comment by fyunusa** [comment]
Hi @thibaudcolas i'll like to take up on this

**Comment by fyunusa** [comment]
Proposing a fix for it, will send in a PR soon

**Comment by fyunusa** [comment]
I could confirm the issue persist from my end too.
<img width="352" alt="Screenshot 2022-10-22 at 12 02 02 AM" src="https://user-images.githubusercontent.com/55334829/197303171-66646c98-b266-452e-aaf5-be8d27a87eb9.png">

Will send in a fix soon

**Comment by fyunusa** [comment]
I think border-inline-start and border-inline-end radius declarations won't work as they'll only add borders to the left and right sides and will thicken the border around
<img width="358" alt="Screenshot 2022-10-22 at 1 35 12 AM" src="https://user-images.githubusercontent.com/55334829/197314215-6a5b964a-a918-4fd1-96d1-758e7f37cf06.png">

So the fix to it which i propose and happens to work is the border-bottom-left-radius and border-bottom-right-radius property 
<img width="353" alt="Screenshot 2022-10-22 at 1 36 06 AM" src="https://user-images.githubusercontent.com/55334829/197314709-08000f07-f0bb-4e2f-9f7e-f8ab74d07db2.png">

but seem to be present in the logic https://github.com/wagtail/wagtail/blob/df0b36fdb7871b9e32cebdbd8be3f82022139c7c/client/src/components/CommentApp/main.scss#L75 already.

**Comment by Yekasumah** [comment]
> Assigning this one to **Yeka Asumah**.

Thank you, I'm working on it now

**Comment by Yekasumah** [comment]
@thibaudcolas I have been able to find a solution to it. I added border-bottom-radius-left & right of 5px to line 57 and it worked. As you can see in the representation below. I'll be sending in a pull request soon. Thank you.

-Replicated the issue here
<img width="838" alt="Screenshot 2022-10-23 at 12 42 01" src="https://user-images.githubusercontent.com/105293813/197390617-51e435c3-332d-4a49-8f2d-b7be7c00bda6.png">

-resolved it here 
<img width="770" alt="Screenshot 2022-10-23 at 12 41 26" src="https://user-images.githubusercontent.com/105293813/197390636-e1274686-055c-4b74-9541-9daffc53452e.png">

**Comment by fyunusa** [comment]
Hi @Yekasumah I think i'll just drop off my pull request here.

You should locate the https://github.com/wagtail/wagtail/blob/df0b36fdb7871b9e32cebdbd8be3f82022139c7c/client/src/components/CommentApp/main.scss#L57 file on your local version of the wagtail and add the snippet below then make your pull rquest from there.

that's how i was able to solve the issue but i'll be dropping off my pull request as it was a misunderstanding from my end before i took the issue.

```
border-bottom-left-radius: $box-border-radius;
border-bottom-right-radius: $box-border-radius;
```

**Comment by Scotchester** [comment]
@Yekasumah, thank you for opening the PR. Unfortunately, I believe Thibaud slightly misdiagnosed the issue. It's not that the border radius code is _missing_ – it is there, but not quite implemented correctly.

If you look below the code you changed, there is already this SCSS block, which seems intended to do what the original post of this issue suggested:

```scss
  > :last-child &__notice {
    bottom: -$box-padding;
    // Remove once we drop support for Safari 14.
    // stylelint-disable-next-line property-disallowed-list
    border-bottom-left-radius: $box-border-radius;
    border-end-start-radius: $box-border-radius;
    // Remove once we drop support for Safari 14.
    // stylelint-disable-next-line property-disallowed-list
    border-bottom-right-radius: $box-border-radius;
    border-end-end-radius: $box-border-radius;
  }
```

However, the selector seems malformed. The resulting compiled CSS looks like:

```css
> :last-child .comment__notice
```

but this is invalid, because you can't use the `>` combinator with nothing on the left side. I think the intent was for it to be:

```css
.comment > :last-child .comment__notice
```

### What to try next

Try adding an ampersand to the start of the selector in CSS to ensure that the `.comment` appears to the left of the `>` in the compiled CSS:

```scss
& > :last-child &__notice
```

This work if a comment has no replies, but is still not quite right if a comment does have replies as `:last-child` would then be `ul.comment-replies`, which may have _multiple_ `.comment__notice`s within it, resulting in border radii when we don't want them. See the middle notice here:

![A comment with two replies, each with an unsaved notice](https://user-images.githubusercontent.com/1044670/197415527-bfed85b0-cd10-4c32-8c32-acc81966014b.png)

To handle all the cases I'm aware of, I think we need two selectors:

```scss
& > &__notice-placeholder:last-child &__notice,
&__replies:last-child > :last-child &__notice
```

It's convoluted, but I've tested this via browser dev tools and I think it covers everything. @Yekasumah, could you please modify your PR to remove your original changes and update the selector on the existing code to that? Please also remove the `bottom: -$box-padding;` line, which seems to be unnecessary.

**Comment by Yekasumah** [comment]
@Scotchester Thank you very much for the clarification. I will modify my PR and make the necessarily changes as suggested.

**Comment by Yekasumah** [comment]
@Scotchester HI, please can you review my PR I've modified it as you suggested. I also don't know why my PR keeps failing tests.

**Comment by Scotchester** [comment]
@Yekasumah Thanks for the mention; I didn't notice you had updated it. Will try to review soon!
