### ISSUE TITLE
In StreamField, Duplicate control doesn't respect max_num

### ISSUE THREAD

**Issue by rgs258** [wagtail/wagtail#9513]
### Issue Summary

Within a StreamField, when block count is constrained by max_num, then the Add button is disabled when no more blocks may be added. In this same situation, the Duplicate button does NOT become disabled.

### Steps to Reproduce

1. set max_num of a block type to 1
2. add that block
3. duplicate that block

Ideally, the Duplicate control would become disabled.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **NO**

### Technical details

-   Python version: 3.8
-   Django version: 4.0.8
-   Wagtail version: 4.0.4
-   Browser version: Chrome Latest

**Comment by gasman** [comment]
Thanks @rgs258! I can confirm I'm seeing the same thing, both for a global max_num on the StreamField and a per-block-type limit - looks like this behaviour disappeared some time after 2.16. I vaguely recall an argument being made that we _shouldn't_ disable these controls dynamically and should only validate at the point of submitting the form instead - so that editors can temporarily exceed the limit while making changes if they're doing some large-scale reorganisation of blocks - but if that's the case, then the Add button should follow the same rule.

**Comment by gasman** [comment]
This change happened in https://github.com/wagtail/wagtail/commit/0cdb9d8915b83c2a2b9dc119b757eb6b7fabf1a9. From the conversation on https://github.com/wagtail/wagtail/pull/8923 it's clear that this was intentional, and knowing now that it was done in the context of block splitting / insertion operations, I think it does make sense - otherwise the semantics of splitting a block get a bit weird when you're about to hit the limit.

As per https://github.com/wagtail/wagtail/pull/8923#discussion_r935385161, there was an acknowledgement at the time that the 'add' control should follow suit, but I suspect that didn't make it into a new issue. I think the ideal arrangement, to support the new behaviour without it looking like a regression on the old, would be to allow additional blocks to be created but immediately give the new blocks an 'error' state. Currently the server-side validation just places an error message on the stream as a whole, but I think we could sensibly move this into the specific block(s) that exceed the limit, and then use the same error styling for both client-side and server-side validation.

![Screenshot 2022-11-01 at 14 57 11](https://user-images.githubusercontent.com/85097/199264262-b2fbe3ad-3d62-4f70-9e71-5364a035bfda.png)

Since that's probably more re-plumbing than we'd want to do in a bugfix release (and it's not strictly a bug), I'll bump this to 4.2.

**Comment by rgs258** [comment]
Sorry to see this get bumped to 4.3. I hope we'll see the errors on the blocks in May :)
