### ISSUE TITLE
Discrepancy between intended design system colors and actual implementation leads to contrast issues

### ISSUE THREAD

**Issue by Theresa-o** [wagtail/wagtail#9571]
### Issue Summary
After adding a page, the success message has insufficient color contrast of 4.45 (foreground color: #ffffff, background color: #1c8767, font size: 10.2pt (13.6px), font weight: normal).

### Steps to Reproduce

1. Go to admin user interface
2. Go to settings
3. Go to "Add new promoted result"

Expected contrast ratio - 4.5:1

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

![wagfirstissueaddresult](https://user-images.githubusercontent.com/62052443/199437684-2b12ab26-d232-4a66-bed6-5bce6cca26e4.PNG)

### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

**Comment by Theresa-o** [comment]
This is being worked on

**Comment by AnishaSingh0118** [comment]
Is this issue still unconfirmed?

**Comment by Theresa-o** [comment]
Hello @AnishaSingh0118 

I'm investigating the best way to solve this

**Comment by AnishaSingh0118** [comment]
> Hello @AnishaSingh0118
> 
> I'm investigating the best way to solve this

Ok, all the best.

**Comment by thibaudcolas** [comment]
Reviewing #9622, this appears to be due to a fundamental issue with our colors’ HSL values. Our design system documents colors as hex codes / RGB, which were chosen to pass contrast checks, while in our design tokens we manually converted to HSL so we could support simple color customisation options.

I believe I did this conversion with browser DevTools, which always output round HSL values. Perceptually that does the job, but technically round values don’t match exactly to RGB – so when browsers convert HSL back to RGB for rendering, we end up with a different value than the color from our design system.

In this specific instance, `positive-100` is #1b8666, but the browser renders #1c8767.

This turns out to be an issue with most of our colors:

| Name                       | HSL hard-coded            | HSL from RGB                                         | RGB hard-coded   | RGB from HSL     |
| -------------------------- | ------------------------- | ---------------------------------------------------- | ---------------- | ---------------- |
| `#000000` black            | hsl(0deg, 0%, 0%)         | hsl(0deg 0% 0%)                                      | rgb(0 0 0)       | rgb(0 0 0)       |
| `#262626` grey-600         | hsl(0deg, 0%, 15%)        | hsl(0deg 0% 14.9019607843%)                          | rgb(38 38 38)    | rgb(38 38 38)    |
| `#5c5c5c` grey-400         | hsl(0deg, 0%, 36%)        | hsl(0deg 0% 36.0784313725%)                          | rgb(92 92 92)    | rgb(92 92 92)    |
| `#929292` 🔴 grey-200      | hsl(0deg, 0%, 57%)        | hsl(0deg 0% 57.2549019608%)                          | rgb(146 146 146) | rgb(145 145 145) |
| `#c8c8c8` 🔴 grey-150      | hsl(0deg, 0%, 78%)        | hsl(0deg 0% 78.431372549%)                           | rgb(200 200 200) | rgb(199 199 199) |
| `#e0e0e0` grey-100         | hsl(0deg, 0%, 88%)        | hsl(0deg 0% 87.8431372549%)                          | rgb(224 224 224) | rgb(224 224 224) |
| `#f6f6f8` grey-50          | hsl(240deg, 12%, 97%)     | hsl(240deg 12.5% 96.862745098%)                      | rgb(246 246 248) | rgb(246 246 248) |
| `#ffffff` white            | hsl(0deg, 0%, 100%)       | hsl(0deg 0% 100%)                                    | rgb(255 255 255) | rgb(255 255 255) |
| `#2e1f5e` 🔴 primary       | hsl(254deg, 50%, 25%)     | hsl(254.2857142857deg 50.4% 24.5098039216%)          | rgb(46 31 94)    | rgb(47 32 96)    |
| `#261a4e` 🔴 primary-200   | hsl(254deg, 50%, 20%)     | hsl(253.8461538462deg 50% 20.3921568627%)            | rgb(38 26 78)    | rgb(37 26 77)    |
| `#004345` 🔴 secondary-600 | hsl(182deg, 100%, 14%)    | hsl(181.7391304348deg 100% 13.5294117647%)           | rgb(0 67 69)     | rgb(0 69 71)     |
| `#005b5e` 🔴 secondary-400 | hsl(182deg, 100%, 18%)    | hsl(181.914893617deg 100% 18.431372549%)             | rgb(0 91 94)     | rgb(0 89 92)     |
| `#007d7e` 🔴 secondary     | hsl(180deg, 100%, 25%)    | hsl(180.4761904762deg 100% 24.7058823529%)           | rgb(0 125 126)   | rgb(0 128 128)   |
| `#00b0b1` 🔴 secondary-100 | hsl(180deg, 100%, 35%)    | hsl(180.3389830508deg 100% 34.7058823529%)           | rgb(0 176 177)   | rgb(0 179 179)   |
| `#80d7d8` 🔴 secondary-75  | hsl(181deg, 53%, 67%)     | hsl(180.6818181818deg 53.0120481928% 67.4509803922%) | rgb(128 215 216) | rgb(126 214 215) |
| `#f2fcfc` 🔴 secondary-50  | hsl(180deg, 63%, 97%)     | hsl(180deg 62.5% 96.862745098%)                      | rgb(242 252 252) | rgb(243 252 252) |
| `#1f7e9a` 🔴 info-100      | hsl(194deg, 66%, 36%)     | hsl(193.6585365854deg 66.4864864865% 36.2745098039%) | rgb(31 126 154)  | rgb(31 124 152)  |
| `#e2f5fc` 🔴 info-50       | hsl(196deg, 81%, 94%)     | hsl(196.1538461538deg 81.25% 93.7254901961%)         | rgb(226 245 252) | rgb(227 245 252) |
| `#1b8666` 🔴 positive-100  | hsl(162deg, 66.5%, 32.5%) | hsl(162.0560747664deg 66.4596273292% 31.568627451%)  | rgb(27 134 102)  | rgb(28 138 105)  |
| `#e0fbf4` 🔴 positive-50   | hsl(164deg, 77%, 93%)     | hsl(162.0560747664deg 66.4596273292% 31.568627451%)  | rgb(224 251 244) | rgb(223 251 244) |
| `#faa500` 🔴 warning-100   | hsl(40deg, 100%, 49%)     | hsl(39.6deg 100% 49.0196078431%)                     | rgb(250 165 0)   | rgb(250 167 0)   |
| `#faecd5` 🔴 warning-50    | hsl(37deg, 79%, 91%)      | hsl(37.2972972973deg 78.7234042553% 90.7843137255%)  | rgb(250 236 213) | rgb(250 236 214) |
| `#cd4444` 🔴 critical-200  | hsl(0deg, 58%, 54%)       | hsl(0deg 57.805907173% 53.5294117647%)               | rgb(205 68 68)   | rgb(206 70 70)   |
| `#fd5765` 🔴 critical-100  | hsl(355deg, 98%, 67%)     | hsl(354.9397590361deg 97.6470588235% 66.6666666667%) | rgb(253 87 101)  | rgb(253 88 102)  |
| `#fde9e9` 🔴 critical-50   | hsl(0deg, 83%, 95%)       | hsl(0deg 83.3333333333% 95.2941176471%)              | rgb(253 233 233) | rgb(253 232 232) |

<details>
<summary>Calculations source for this table (Sass)</summary>

```scss
@use "sass:color";

$black-hex: #000000;
$black-hsl: hsl(0 0% 0%);
@debug "HSL black: #{$black-hex} hsl(#{hue($black-hex)} #{saturation($black-hex)} #{lightness($black-hex)}) vs #{$black-hsl}";
@debug "RGB black: rgb(#{red($black-hex)} #{green($black-hex)} #{blue($black-hex)}) vs. rgb(#{red($black-hsl)} #{green($black-hsl)} #{blue($black-hsl)})";
$grey-600-hex: #262626;
$grey-600-hsl: hsl(0 0% 15%);
@debug "HSL grey-600: #{$grey-600-hex} hsl(#{hue($grey-600-hex)} #{saturation($grey-600-hex)} #{lightness($grey-600-hex)}) vs #{$grey-600-hsl}";
@debug "RGB grey-600: rgb(#{red($grey-600-hex)} #{green($grey-600-hex)} #{blue($grey-600-hex)}) vs. rgb(#{red($grey-600-hsl)} #{green($grey-600-hsl)} #{blue($grey-600-hsl)})";
$grey-400-hex: #5c5c5c;
$grey-400-hsl: hsl(0 0% 36%);
@debug "HSL grey-400: #{$grey-400-hex} hsl(#{hue($grey-400-hex)} #{saturation($grey-400-hex)} #{lightness($grey-400-hex)}) vs #{$grey-400-hsl}";
@debug "RGB grey-400: rgb(#{red($grey-400-hex)} #{green($grey-400-hex)} #{blue($grey-400-hex)}) vs. rgb(#{red($grey-400-hsl)} #{green($grey-400-hsl)} #{blue($grey-400-hsl)})";
$grey-200-hex: #929292;
$grey-200-hsl: hsl(0 0% 57%);
@debug "HSL grey-200: #{$grey-200-hex} hsl(#{hue($grey-200-hex)} #{saturation($grey-200-hex)} #{lightness($grey-200-hex)}) vs #{$grey-200-hsl}";
@debug "RGB grey-200: rgb(#{red($grey-200-hex)} #{green($grey-200-hex)} #{blue($grey-200-hex)}) vs. rgb(#{red($grey-200-hsl)} #{green($grey-200-hsl)} #{blue($grey-200-hsl)})";
$grey-150-hex: #c8c8c8;
$grey-150-hsl: hsl(0 0% 78%);
@debug "HSL grey-150: #{$grey-150-hex} hsl(#{hue($grey-150-hex)} #{saturation($grey-150-hex)} #{lightness($grey-150-hex)}) vs #{$grey-150-hsl}";
@debug "RGB grey-150: rgb(#{red($grey-150-hex)} #{green($grey-150-hex)} #{blue($grey-150-hex)}) vs. rgb(#{red($grey-150-hsl)} #{green($grey-150-hsl)} #{blue($grey-150-hsl)})";
$grey-100-hex: #e0e0e0;
$grey-100-hsl: hsl(0 0% 88%);
@debug "HSL grey-100: #{$grey-100-hex} hsl(#{hue($grey-100-hex)} #{saturation($grey-100-hex)} #{lightness($grey-100-hex)}) vs #{$grey-100-hsl}";
@debug "RGB grey-100: rgb(#{red($grey-100-hex)} #{green($grey-100-hex)} #{blue($grey-100-hex)}) vs. rgb(#{red($grey-100-hsl)} #{green($grey-100-hsl)} #{blue($grey-100-hsl)})";
$grey-50-hex: #f6f6f8;
$grey-50-hsl: hsl(240 12% 97%);
@debug "HSL grey-50: #{$grey-50-hex} hsl(#{hue($grey-50-hex)} #{saturation($grey-50-hex)} #{lightness($grey-50-hex)}) vs #{$grey-50-hsl}";
@debug "RGB grey-50: rgb(#{red($grey-50-hex)} #{green($grey-50-hex)} #{blue($grey-50-hex)}) vs. rgb(#{red($grey-50-hsl)} #{green($grey-50-hsl)} #{blue($grey-50-hsl)})";
$white-hex: #ffffff;
$white-hsl: hsl(0 0% 100%);
@debug "HSL white: #{$white-hex} hsl(#{hue($white-hex)} #{saturation($white-hex)} #{lightness($white-hex)}) vs #{$white-hsl}";
@debug "RGB white: rgb(#{red($white-hex)} #{green($white-hex)} #{blue($white-hex)}) vs. rgb(#{red($white-hsl)} #{green($white-hsl)} #{blue($white-hsl)})";
$primary-hex: #2e1f5e;
$primary-hsl: hsl(254 50% 25%);
@debug "HSL primary: #{$primary-hex} hsl(#{hue($primary-hex)} #{saturation($primary-hex)} #{lightness($primary-hex)}) vs #{$primary-hsl}";
@debug "RGB primary: rgb(#{red($primary-hex)} #{green($primary-hex)} #{blue($primary-hex)}) vs. rgb(#{red($primary-hsl)} #{green($primary-hsl)} #{blue($primary-hsl)})";
$primary-200-hex: #261a4e;
$primary-200-hsl: hsl(254 50% 20%);
@debug "HSL primary-200: #{$primary-200-hex} hsl(#{hue($primary-200-hex)} #{saturation($primary-200-hex)} #{lightness($primary-200-hex)}) vs #{$primary-200-hsl}";
@debug "RGB primary-200: rgb(#{red($primary-200-hex)} #{green($primary-200-hex)} #{blue($primary-200-hex)}) vs. rgb(#{red($primary-200-hsl)} #{green($primary-200-hsl)} #{blue($primary-200-hsl)})";
$secondary-600-hex: #004345;
$secondary-600-hsl: hsl(182 100% 14%);
@debug "HSL secondary-600: #{$secondary-600-hex} hsl(#{hue($secondary-600-hex)} #{saturation($secondary-600-hex)} #{lightness($secondary-600-hex)}) vs #{$secondary-600-hsl}";
@debug "RGB secondary-600: rgb(#{red($secondary-600-hex)} #{green($secondary-600-hex)} #{blue($secondary-600-hex)}) vs. rgb(#{red($secondary-600-hsl)} #{green($secondary-600-hsl)} #{blue($secondary-600-hsl)})";
$secondary-400-hex: #005b5e;
$secondary-400-hsl: hsl(182 100% 18%);
@debug "HSL secondary-400: #{$secondary-400-hex} hsl(#{hue($secondary-400-hex)} #{saturation($secondary-400-hex)} #{lightness($secondary-400-hex)}) vs #{$secondary-400-hsl}";
@debug "RGB secondary-400: rgb(#{red($secondary-400-hex)} #{green($secondary-400-hex)} #{blue($secondary-400-hex)}) vs. rgb(#{red($secondary-400-hsl)} #{green($secondary-400-hsl)} #{blue($secondary-400-hsl)})";
$secondary-hex: #007d7e;
$secondary-hsl: hsl(180 100% 25%);
@debug "HSL secondary: #{$secondary-hex} hsl(#{hue($secondary-hex)} #{saturation($secondary-hex)} #{lightness($secondary-hex)}) vs #{$secondary-hsl}";
@debug "RGB secondary: rgb(#{red($secondary-hex)} #{green($secondary-hex)} #{blue($secondary-hex)}) vs. rgb(#{red($secondary-hsl)} #{green($secondary-hsl)} #{blue($secondary-hsl)})";
$secondary-100-hex: #00b0b1;
$secondary-100-hsl: hsl(180 100% 35%);
@debug "HSL secondary-100: #{$secondary-100-hex} hsl(#{hue($secondary-100-hex)} #{saturation($secondary-100-hex)} #{lightness($secondary-100-hex)}) vs #{$secondary-100-hsl}";
@debug "RGB secondary-100: rgb(#{red($secondary-100-hex)} #{green($secondary-100-hex)} #{blue($secondary-100-hex)}) vs. rgb(#{red($secondary-100-hsl)} #{green($secondary-100-hsl)} #{blue($secondary-100-hsl)})";
$secondary-75-hex: #80d7d8;
$secondary-75-hsl: hsl(181 53% 67%);
@debug "HSL secondary-75: #{$secondary-75-hex} hsl(#{hue($secondary-75-hex)} #{saturation($secondary-75-hex)} #{lightness($secondary-75-hex)}) vs #{$secondary-75-hsl}";
@debug "RGB secondary-75: rgb(#{red($secondary-75-hex)} #{green($secondary-75-hex)} #{blue($secondary-75-hex)}) vs. rgb(#{red($secondary-75-hsl)} #{green($secondary-75-hsl)} #{blue($secondary-75-hsl)})";
$secondary-50-hex: #f2fcfc;
$secondary-50-hsl: hsl(180 63% 97%);
@debug "HSL secondary-50: #{$secondary-50-hex} hsl(#{hue($secondary-50-hex)} #{saturation($secondary-50-hex)} #{lightness($secondary-50-hex)}) vs #{$secondary-50-hsl}";
@debug "RGB secondary-50: rgb(#{red($secondary-50-hex)} #{green($secondary-50-hex)} #{blue($secondary-50-hex)}) vs. rgb(#{red($secondary-50-hsl)} #{green($secondary-50-hsl)} #{blue($secondary-50-hsl)})";
$info-100-hex: #1f7e9a;
$info-100-hsl: hsl(194 66% 36%);
@debug "HSL info-100: #{$info-100-hex} hsl(#{hue($info-100-hex)} #{saturation($info-100-hex)} #{lightness($info-100-hex)}) vs #{$info-100-hsl}";
@debug "RGB info-100: rgb(#{red($info-100-hex)} #{green($info-100-hex)} #{blue($info-100-hex)}) vs. rgb(#{red($info-100-hsl)} #{green($info-100-hsl)} #{blue($info-100-hsl)})";
$info-50-hex: #e2f5fc;
$info-50-hsl: hsl(196 81% 94%);
@debug "HSL info-50: #{$info-50-hex} hsl(#{hue($info-50-hex)} #{saturation($info-50-hex)} #{lightness($info-50-hex)}) vs #{$info-50-hsl}";
@debug "RGB info-50: rgb(#{red($info-50-hex)} #{green($info-50-hex)} #{blue($info-50-hex)}) vs. rgb(#{red($info-50-hsl)} #{green($info-50-hsl)} #{blue($info-50-hsl)})";
$positive-100-hex: #1b8666;
$positive-100-hsl: hsl(162 66% 32%);
@debug "HSL positive-100: #{$positive-100-hex} hsl(#{hue($positive-100-hex)} #{saturation($positive-100-hex)} #{lightness($positive-100-hex)}) vs #{$positive-100-hsl}";
@debug "RGB positive-100: rgb(#{red($positive-100-hex)} #{green($positive-100-hex)} #{blue($positive-100-hex)}) vs. rgb(#{red($positive-100-hsl)} #{green($positive-100-hsl)} #{blue($positive-100-hsl)})";
$positive-50-hex: #e0fbf4;
$positive-50-hsl: hsl(164 77% 93%);
@debug "HSL positive-50: #{$positive-50-hex} hsl(#{hue($positive-50-hex)} #{saturation($positive-50-hex)} #{lightness($positive-50-hex)}) vs #{$positive-50-hsl}";
@debug "RGB positive-50: rgb(#{red($positive-50-hex)} #{green($positive-50-hex)} #{blue($positive-50-hex)}) vs. rgb(#{red($positive-50-hsl)} #{green($positive-50-hsl)} #{blue($positive-50-hsl)})";
$warning-100-hex: #faa500;
$warning-100-hsl: hsl(40 100% 49%);
@debug "HSL warning-100: #{$warning-100-hex} hsl(#{hue($warning-100-hex)} #{saturation($warning-100-hex)} #{lightness($warning-100-hex)}) vs #{$warning-100-hsl}";
@debug "RGB warning-100: rgb(#{red($warning-100-hex)} #{green($warning-100-hex)} #{blue($warning-100-hex)}) vs. rgb(#{red($warning-100-hsl)} #{green($warning-100-hsl)} #{blue($warning-100-hsl)})";
$warning-50-hex: #faecd5;
$warning-50-hsl: hsl(37 79% 91%);
@debug "HSL warning-50: #{$warning-50-hex} hsl(#{hue($warning-50-hex)} #{saturation($warning-50-hex)} #{lightness($warning-50-hex)}) vs #{$warning-50-hsl}";
@debug "RGB warning-50: rgb(#{red($warning-50-hex)} #{green($warning-50-hex)} #{blue($warning-50-hex)}) vs. rgb(#{red($warning-50-hsl)} #{green($warning-50-hsl)} #{blue($warning-50-hsl)})";
$critical-200-hex: #cd4444;
$critical-200-hsl: hsl(0 58% 54%);
@debug "HSL critical-200: #{$critical-200-hex} hsl(#{hue($critical-200-hex)} #{saturation($critical-200-hex)} #{lightness($critical-200-hex)}) vs #{$critical-200-hsl}";
@debug "RGB critical-200: rgb(#{red($critical-200-hex)} #{green($critical-200-hex)} #{blue($critical-200-hex)}) vs. rgb(#{red($critical-200-hsl)} #{green($critical-200-hsl)} #{blue($critical-200-hsl)})";
$critical-100-hex: #fd5765;
$critical-100-hsl: hsl(355 98% 67%);
@debug "HSL critical-100: #{$critical-100-hex} hsl(#{hue($critical-100-hex)} #{saturation($critical-100-hex)} #{lightness($critical-100-hex)}) vs #{$critical-100-hsl}";
@debug "RGB critical-100: rgb(#{red($critical-100-hex)} #{green($critical-100-hex)} #{blue($critical-100-hex)}) vs. rgb(#{red($critical-100-hsl)} #{green($critical-100-hsl)} #{blue($critical-100-hsl)})";
$critical-50-hex: #fde9e9;
$critical-50-hsl: hsl(0 83% 95%);
@debug "HSL critical-50: #{$critical-50-hex} hsl(#{hue($critical-50-hex)} #{saturation($critical-50-hex)} #{lightness($critical-50-hex)}) vs #{$critical-50-hsl}";
@debug "RGB critical-50: rgb(#{red($critical-50-hex)} #{green($critical-50-hex)} #{blue($critical-50-hex)}) vs. rgb(#{red($critical-50-hsl)} #{green($critical-50-hsl)} #{blue($critical-50-hsl)})";
```

</details>

I think this should relatively easily be solved by switching over to more precise HSL values, though I don’t understand why browsers wouldn’t output those precise values to start with (/ whether decimal values are supported). Ideally we’d also do a bit of rounding to the least-amount-of-decimal that works so colors stay readable.

**Comment by Dev-Liz** [comment]
@thibaudcolas I used a different tool to convert  and I got the exact values with no decimal points. 

![IMG_20221214_184159](https://user-images.githubusercontent.com/40176275/207668842-1af272f3-cba7-444a-9087-5a3157b1ecb1.jpg)

I think the browser is being too detailed. 

Looking closely, I figured we could still get the standard HSL values if we round the decimals to the nearest whole number.

**Comment by thibaudcolas** [comment]
@Dev-Liz rounding the decimals to the nearest whole number is what we have done so far and what is causing this issue. If this is how your tool works, try it with `rgb(146 146 146)`, you’ll see it output `hsl(0deg, 0%, 57%)`. If you then provide that output to your tool as input – it’ll subsequently output `rgb(145 145 145)`. So whole numbers aren’t enough for all RGB values.

**Comment by thibaudcolas** [comment]
For anyone interested in this, happy to report they’ve fixed the issue that caused this in Chrome too! [Issue 1400984: DevTools color picker notation conversion shouldn’t round HSL values](https://bugs.chromium.org/p/chromium/issues/detail?id=1400984)
