### ISSUE TITLE
Documentation content copyright should align with the code licence

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9688]
### Footer copyright notice 

Currently the footer copyright notice calls out the documentation content as under copyright. 

> © Copyright 2022, Torchbox and contributors 

However, this is probably not correct as the content comes under the same licence as the code BSD - https://github.com/wagtail/wagtail/blob/main/LICENSE

I propose we update this to something like...

> Content copyright waived under BSD-3 (link), thanks to Torchbox and individual contributors

Alternatively we update this to be CC0, as per the Wagtail guide. 

> Copyright and related rights waived via CC0. (Add link)

### Details

https://github.com/wagtail/wagtail/blob/baddbfad424afa797287151e6b04d9c0459df3ef/docs/conf.py#L81

![Screenshot_20221117-064904](https://user-images.githubusercontent.com/1396140/202291103-71da7e09-c1a2-44d2-9f50-e0d9c1198b04.png)

See similar discussion on the Wagtail guide - https://github.com/wagtail/guide/issues/164#issuecomment-1295746332

**Comment by AnishaSingh0118** [comment]
Can I work on this issue ?

**Comment by lb-** [comment]
@AnishaSingh0118 this is probably something we will wait on others in the core team to agree on. 

I'll flag this as needs decision.

**Comment by AnishaSingh0118** [comment]
> @AnishaSingh0118 this is probably something we will wait on others in the core team to agree on.
> 
> I'll flag this as needs decision.

Ok, no problem.

**Comment by thibaudcolas** [comment]
I’ve addressed this quickly in 8a6ab17 now. Note the "Copyright 2022, Torchbox and contributors" already aligns with the license – regardless of what the license is, the content still has the same copyright holders. It just happens that those copyright holders share the code under an open source license. A public domain dedication like CC0 is the one exception here, where all potential copyright holders explicitly waive all copyright-derived rights (so rather than it being a license, there’s really no need or even no right for anyone to license the works).

The BSD license is for source code so I don’t think it’s really that appropriate for content, hence why we chose CC0 for the guide website. Nonetheless, I still think it’s an improvement to mention it in the footer.
