### ISSUE TITLE
Wagtail breaks migrations for apps with data migrations

### ISSUE THREAD

**Issue by schinckel** [wagtail/wagtail#9690]
### Issue Summary

Wagtail installs a post_save receiver, which is present during migration runs.

If any data migrations are run before all of wagtail's migrations, then this causes migrations to fail.

### Steps to Reproduce

The commit where it was introduced is:

https://github.com/wagtail/wagtail/commit/212b2e19a680410ac1ab3fe4f18cdcb318afaa67

It can be fixed by ensuring that the first data migration that is run has a wagtail dependency.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.9
-   Django version: 3.2
-   Wagtail version: 212b2e19a680410ac1ab3fe4f18cdcb318afaa67
-   Browser version: Irrelevant

**Comment by gasman** [comment]
Hi @schinckel - thanks for the report. However, I'm unable to replicate this as described on Wagtail 4.1. I performed the following steps, starting from a fresh Python 3.9 virtualenv:

```sh
pip install "wagtail==4.1"
wagtail start datamigration
cd datamigration
./manage.py startapp core
```

add core to the top of INSTALLED_APPS in datamigration/settings.py

edit core/models.py to:

```python
from django.db import models


class Band(models.Model):
    name = models.CharField(max_length=255)


class Musician(models.Model):
    name = models.CharField(max_length=255)
    band = models.ForeignKey(Band, on_delete=models.CASCADE)
```

```sh
./manage.py makemigrations
./manage.py makemigrations --empty core --name populate_band
```

edit core/migrations/0002_populate_band.py to:

```python
from django.db import migrations

def create_band(apps, schema_editor):
    Band = apps.get_model('core', 'Band')
    Musician = apps.get_model('core', 'Musician')
    beatles = Band.objects.create(name="The Beatles")
    Musician.objects.create(name="John Lennon", band=beatles)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_band)
    ]
```

Finally, run `./manage.py migrate` - the output shows the `core` migrations running before any of Wagtail's, but the migrations complete successfully.

The ForeignKey relation between Band and Musician would be sufficient to trigger the ReferenceIndex signal handler, and indeed running `./manage.py rebuild_references_index` afterwards does insert a ReferenceIndex record for the band/musician we created. I also tried importing the live Band and Musician directly from core.models within the data migration rather than going through `apps.get_model` (which is less correct, but might open up more opportunities for things to break), but that succeeded as well.

Happy to reopen and investigate further if you can find a more specific set of steps that replicates the problem.
