### ISSUE TITLE
Suggestion: set is_staff if moderator 

### ISSUE THREAD

**Issue by frankwiles** [wagtail/wagtail#970]
Hi, 

While I realize Wagtail isn't typically used much in conjunction with the Django admin, I ran into a situation today that was a bit confusing at first and if I'm confused others will be.  Scenario: 

1) I setup some non-Wagtail admin interfaces (custom, not using the Django admin at all) wrapped with using @staff_required (well actually the django-braces version)

2) Setup users in the Wagtail admin as moderators, but not administrators 

3) Confused as to why the users were able to get into the Wagtail admin and not the custom admin menu items I had created. 

I can foresee scenarios where setting is_staff on a user automatically would be a bad thing, so perhaps it's enough to just call it out in the docs or perhaps have a Is Staff option in Roles in the Wagtail User admin?

**Comment by gasman** [comment]
Hi @frankwiles,
I think it's best for Wagtail to avoid making any assumptions about the level of access to Django-admin that users should receive. As you say, there are scenarios where Django-admin access should be restricted even for users with effectively 'full' privileges over Wagtail. (Also, it's worth bearing in mind that there's nothing special about 'moderator' as a status within Wagtail - it's just a group that's created by the default Wagtail install with a particular set of publish permissions, and sites are free to delete it and replace it with whatever policy they like.)

At the moment, we have [a hard-coded rule](https://github.com/torchbox/wagtail/blob/f064fe93d03efef3090e50ca6ade5c290bca957a/wagtail/wagtailusers/forms.py#L132) that the 'is_staff' flag is set for administrators and only administrators - and that's not a brilliant design choice either, on similar grounds. To solve this with full generality, we probably need to expose the is_staff flag on the 'edit user' form, and possibly have some extra logic to set/unset that by default e.g. if Administrator is ticked. Needs more consideration...

**Comment by frankwiles** [comment]
Agreed, I think just adding it to the User or Role forms will be great.

**Comment by jorge-marques** [comment]
I'm currently experiencing an issue where an user modified by wagtail gets the is_staff flag set to false, even if it was previously set to true. Is this the expected behaviour?

**Comment by gasman** [comment]
@jorge-marques This is the expected behaviour (or, to put it another way - it's a design flaw, not a programming bug). The `is_staff` flag is set to the value of `is_superuser` on save, so if you edit a user with is_staff=True, is_superuser=False through the Wagtail interface, the is_staff=True flag will be lost.

https://github.com/torchbox/wagtail/blob/e0a7a472e62aca7b08b61178b92d65f637566e80/wagtail/wagtailusers/forms.py#L175-L176

I'd be happy to consider suggestions / pull requests for fixing this. I'd *prefer* not to add 'is staff' as a new checkbox on the Wagtail form, because it's not meaningful for the simplest and most common type of Wagtail project (where the project is *only* a Wagtail project, with no custom Django models, and therefore there's no need for anyone to use django admin), and so it breaks our design principle of "hide complexity until it's actually needed". I suspect that'll be the 'least worst' solution though...

The alternatives I can see are: 1) don't touch the `is_staff` flag at all (which would mean that superusers created through Wagtail don't get access to django-admin - I think?), or 2) only do the `user.is_staff = user.is_superuser` assignment when creating users.

**Comment by jorge-marques** [comment]
@gasman I understand the rationale for not showing the checkbox. Regarding the other options, I think option 2 would probably be good enough. Can't think of any problematic side effects, off the top of my head.

**Comment by gasman** [comment]
After further discussion in the core team, we've decided not to touch the `is_staff` flag at all: ordinarily using Wagtail doesn't require access to Django admin, so it makes sense for Wagtail to not enforce an opinion on who does or doesn't get access. This also neatly fixes #2777 / #2816.

A developer who wants to make is_staff configurable can add that checkbox via the WAGTAIL_USER_CUSTOM_FIELDS setting, or use signals to set it automatically.
