### ISSUE TITLE
Allow moving blocks between streams of the same type

### ISSUE THREAD

**Issue by fgiering** [wagtail/wagtail#9757]
### Is your proposal related to a problem?

I'm always frustrated when I need to reorder streamfields between different columns oder column-blocks.

### Describe the solution you'd like

I wish I could just drag and drop or reorder the streamfield components and not have to copy and paste every single input field.

Is it just me?

**Comment by gasman** [comment]
StreamField blocks do provide reordering controls, in the header bar of each block.

Wagtail has no built-in concept of "column blocks" - is that a third-party extension you're using, perhaps?

**Comment by fgiering** [comment]
Ah yes. Sorry need to speak of nested StreamFields. 
And I want to drag the upper nested field to the bottom nested part.
![Screenshot](https://user-images.githubusercontent.com/35344457/206489858-2b81d67e-6d9c-47b2-9c2a-1ee1a0e1d604.png)

**Comment by gasman** [comment]
Thanks for clarifying! So, in general Wagtail terms, this is about the ability to move child blocks between two ListBlocks / StreamBlocks of the same type - for example, if you have a multi-column view implemented as a list of StreamBlocks (or perhaps a StructBlock with 'left' and 'right' streams), being able to move a block between columns rather than just moving it up and down within the column it's already in. Have updated the issue title accordingly.

I can see this being quite difficult to implement, both in designing a good user interface and writing the logic to determine if a given move is valid, but I'm happy to accept this as a future feature request.

**Comment by thibaudcolas** [comment]
See also #1033, which is about general "drag and drop" support for StreamField.

**Comment by cnk** [comment]
This is now being discussed in issue #8339
