### ISSUE TITLE
Broken link spotted under the "gettings_started/tutorials"  in the wagtail repo.

### ISSUE THREAD

**Issue by dchidindu5** [wagtail/wagtail#9843]
I was navigating through some of the technical docs to fixed an error and spotted a broken link that generates an "error 404".
I don't know if it's necessary.

### This is were the broken links are located

  [ getting_started>>tutorials.md](https://github.com/dchidindu5/wagtail/blob/main/docs/getting_started/tutorial.md)

### Details
 These should be the correct location of the link.
(https://github.com/wagtail/wagtail/blob/main/docs/advanced_topics/third_party_tutorials.md)
(https://github.com/wagtail/wagtail/blob/main/docs/advanced_topics/index.md)

**Comment by gasman** [comment]
Hi @dchidindu5 - thanks for the report.

These links fail when viewed through Github because Github doesn't support [the Sphinx documentation generator that we use for the docs](https://docs.wagtail.org/en/stable/contributing/developing.html#compiling-the-documentation) - if you view the built documentation at https://docs.wagtail.org/en/latest/getting_started/tutorial.html, you'll see that the links are working correctly.

**Comment by dchidindu5** [comment]
okay, I noticed that too
