### ISSUE TITLE
Wrong nplurals in Spanish causes to prepend Wagtail snippets translation to application translations

### ISSUE THREAD

**Issue by fmerges** [wagtail/wagtail#9852]
Hello,

The nplurals of the snippets for Spanish is wrong causing DjangoTranslation to prepend (insert 0) the snippets translations as a new catalog to main catalog (with the right nplurals function), with the side effect that application overridden translation strings are not being used, as the lookup for translation strings follow a for loop through the available catalogs in the TranslationCatalog._catalogs list.

https://github.com/wagtail/wagtail/blob/185bdec8be69c7e91edf0d621fa54d6eb49fa4b1/wagtail/admin/locale/es/LC_MESSAGES/django.po#L33

The nplurals string should be like it was before as per the documentation: http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms

    nplurals=2; plural=(n != 1);

Cheers

**Comment by fmerges** [comment]
The same happens here:

https://github.com/wagtail/wagtail/blob/185bdec8be69c7e91edf0d621fa54d6eb49fa4b1/wagtail/snippets/locale/es/LC_MESSAGES/django.po#L30

**Comment by gasman** [comment]
Hi @fmerges - thanks for the report.

It looks like this change was introduced as a result of this: https://community.transifex.com/t/important-update-languages-plural-rules/2832, and I'm not sure that Transifex allows us to override their global pluralisation rules.

However, the [CLDR document they link to](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html?utm_source=hs_email&utm_medium=email&_hsenc=p2ANqtz-_DnZPQk_vRsUlKDYwgK0PT-V_5rSkRLCXU_69K9ZHcUtwWnBm1BB5wTcIRL_PZa5ekjh0u) does indeed include the special case for 1000000 - since this is apparently the new Unicode standard as of 2022, and the page you link to [was apparently last updated in 2017](https://github.com/translate/l10n-guide/blob/master/docs/l10n/pluralforms.rst), I believe the `nplurals=3` version is the more correct / up-to-date rule, and so the appropriate fix would be to update your application overrides accordingly.

**Comment by fmerges** [comment]
Yes, I would have to change my locales if this is the way moving forward. Django still uses the default language rules.

Eventually this ticket may help someone else save time trying to figure out what is going on. I did not read about it in the upgrade consideration notes, neither for 3.x nor 4.x.

Cheers, and thanks for your prompt reply!
