### ISSUE TITLE
Documentation search delivers 404 result

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#9894]
The following result delivers a 404 result.
The 4th item

https://docs.wagtail.org/en/latest/search.html?q=search

https://docs.wagtail.org/en/latest/reference/contrib/postgres_search.html?highlight=search

**Comment by vupham04** [comment]
Can confirm that I see the 404 error too. It is because the documentation file for reference/contrib/postgres_search.html is already removed in this commit: https://github.com/wagtail/wagtail/commit/00582ba35a2368890586c167636c9c2aad21cab3

But somehow the search page still shows the searching result for postgres_search.html (which should not exist)

**Comment by zerolab** [comment]
The docs use Algolia for the search feature. We're working on getting that updated and tweaked as there are other issues. Please bear with us

**Comment by thibaudcolas** [comment]
I believe this will be fixed in #10207.

**Comment by thibaudcolas** [comment]
This has been fixed for the `latest` search. Will make its way to other versions over the next few days.
