### ISSUE TITLE
Page in workflow can't be locked

### ISSUE THREAD

**Issue by WilliamHenryTanza** [wagtail/wagtail#9943]
### Issue Summary

When a page is in a workflow, it can't be 'personally' locked, the page is shown as 'Locked', but when checking the page.locked, it returns False. (It can be locked via shell/command line, by setting page.locked to True and locked_by to whichever user you want it to be locked by)

### Steps to Reproduce

1. Submit a page to workflow
2. Lock toggle is hidden (page is shown as locked, and can't be locked)

**Comment by laymonage** [comment]
Thanks for the report! I can confirm this is a regression in a743bf962de7d59889ab23d7639eb4550303f9a2.

**Comment by laymonage** [comment]
I tried having a go at this in #9946, but I think I found a reason why we lost this feature.

Before 4.0, the "Locked/Unlocked" information in the status side panel relies only on "manual" locks (aka `BasicLock` introduced in #8911), i.e. whether someone has explicitly locked a page. If a page gets "locked" by a workflow, it doesn't count -- the info still says "Unlocked". So, both editors and reviewers will see the status as "Unlocked" (but only reviewers can see the "Lock" button). Pic:
![image](https://user-images.githubusercontent.com/6379424/214095984-1c5dd6f1-d2ea-4d06-a816-c91de2e7552a.png)

In 4.0, we "lock" pages that are scheduled for publishing (#8917). As with the workflow lock, this is different from the "manual" lock. When we added this, we also updated the status panel info to better reflect the state of the page (whether it can be edited or not):
- Show the status title as "Locked" if there's either a scheduled publishing lock, a manual lock, or a workflow lock (in that order).
  - Even if the lock doesn't apply to the user (e.g. it's a workflow lock and the user is a reviewer), it still says "Locked", but the description will say "You can edit this page, but others may not". It only says "Unlocked" if there's no lock at all.
- Only show the "Lock" button if the user has permission to manually lock the page and there is no lock at all.
  - This is what causes the issue, as now it's impossible to manually lock a page that already has a workflow lock.
  - I tried re-enabling this feature, but it means there's this weird state where the title says "Locked" (because it's in a workflow), but you can still lock it... I tried changing the description to clear it up a bit, but it still looks a bit weird to me:
    ![image](https://user-images.githubusercontent.com/6379424/214096227-1f01b422-a967-46c8-9369-38ae861e9cbb.png)

Maybe we could improve this by making the title clearer, e.g. "Locked for moderation", "Locked by X", etc. Or, we could also make the title say "Locked"/"Unlocked" depending on whether the lock applies to the current user, rather than whether there's a lock or not.

It would be nice if we could fix this for 4.2, but considering that we've lost this ability since 4.0 and it's not a straightforward fix as I initially thought, we might have to fix this in 4.3 instead.

**Comment by laymonage** [comment]
Considering that we'll likely need some design changes and new translatable strings, I'll bump this to 5.0. If other core team members have a different opinion, feel free to discuss.
