### ISSUE TITLE
Header Search (Images, Documents) 

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9953]
### Issue Summary

When clearing an existing search (or typing and clearing a search) the results shows that there are no images at all, instead of showing all images again.

### Steps to Reproduce

1. In the Wagtail bakerydemo (clean installation), or in a new installation with some images added.
2. Navigate to the images page - http://localhost:8000/admin/images/
3. Observe that there should be multiple images shown
4. Now type in a search that you know will result in no results (e.g. 'zzzzz'), observe you get a result shown similar to `Sorry, no images match "zzz"`
5. Now type in a search that you know will result in one/some values (e.g. 'olivia' in the bakerydemo), observe that you get the correct results shown
6. Now clear the search value
7. Expected: All images should be shown again (as per first load)
8. Actual: The message shows as if no images were ever loaded `You haven't uploaded any images. Why not [upload one now](http://localhost:8000/admin/images/multiple/add/)?`

-   Note that this also happens if you refresh, e.g. a full load of http://localhost:8000/admin/images/?q=
-   This does not seem to happen for searches in users, groups, redirects, search picks, chooser modals
-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

-   Wagtail version: 4.2rc
-   Browser version: Firefox 109

### Screenshot

<img width="1263" alt="Screenshot 2023-01-24 at 3 29 30 pm" src="https://user-images.githubusercontent.com/1396140/214222006-da4f6b3a-0d9a-4905-a347-50d34b4e743f.png">

**Comment by lb-** [comment]
Found this when working through https://github.com/wagtail/wagtail/pull/9952

**Comment by th3hamm0r** [comment]
The same is also broken in wagtailmedia. I've just tested it against other wagtail versions, 4.0.4 and 4.1.1 don't have this problem, so it seems to be 4.2, maybe related to #9918?

**Comment by lb-** [comment]
I think this is more related to the view code - not the front-end code as it fails to show a proper listing on a fill refresh. 

Maybe this change? https://github.com/wagtail/wagtail/pull/8104

**Comment by th3hamm0r** [comment]
You're right, must be view code. #8104 is already included since 4.0, and works there without issues, so it must be something else. I've also found #9900, but it seems to only change chooser modals, so I think it does not fit either.

**Comment by th3hamm0r** [comment]
Ok, maybe it could have something to do with the changes in #9900: When I first went through the changeset, I've missed that the `autocomplete_query_compiler_class` has been commented out for [mysql](https://github.com/wagtail/wagtail/pull/9900/files#diff-cc07b6f1485e460c5edada4850f65cdeb234cd4265541eaa948173ede6a71dfc) and [sqlite](https://github.com/wagtail/wagtail/pull/9900/files#diff-fbac32e285a65587e7d49abd41beb17f19810c604501f93840cf8259d172f607). So if the issue does not exist for postgres, maybe that issue is related to those changes.

**Comment by gasman** [comment]
`git bisect` shows that this was introduced in c8edfd13b22bea2dc9921473ba3b2c8899fac394 as part of #9923.

**Comment by gasman** [comment]
I think the problem is that the view is using `is_valid()` on the form as an indicator of whether it should add the `search()` filter to the query or not - previously this would have returned False for an empty search term and thus skipped the call to `search()`, but now it's running that on the empty string, which returns no results.
